### ISSUE TITLE
Getting error for DatePicker

### ISSUE THREAD

**Issue by mayukhgit** [valor-software/ngx-bootstrap#1000]
Getting this for DatePicker with latest version 1.1.5 and Angular final release. Timepicker loads without error.

Unhandled Promise rejection: Template parse errors:
Binding to event attribute 'onlyCurrentMonth' is disallowed for security reasons, please use (lyCurrentMonth)=... ("ustomClass]="customClass"
                      [dateDisabled]="dateDisabled"
                      [ERROR ->][onlyCurrentMonth]="onlyCurrentMonth"
                      [shortcutPropagation]="shortcutPropagatio"): DatePickerComponent@20:22
'daypicker' is not a known element:
1. If 'daypicker' is an Angular component, then verify that it is part of this module.
2. If 'daypicker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("ation]="shortcutPropagation"
                      (selectionDone)="onSelectionDone($event)">
      [ERROR ->]<daypicker tabindex="0"></daypicker>
      <monthpicker tabindex="0"></monthpicker>
      <yearpicker"): DatePickerComponent@23:6
'monthpicker' is not a known element:
1. If 'monthpicker' is an Angular component, then verify that it is part of this module.
2. If 'monthpicker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("        (selectionDone)="onSelectionDone($event)">
      <daypicker tabindex="0"></daypicker>
      [ERROR ->]<monthpicker tabindex="0"></monthpicker>
      <yearpicker tabindex="0"></yearpicker>
    </datepicke"): DatePickerComponent@24:6
'yearpicker' is not a known element:
1. If 'yearpicker' is an Angular component, then verify that it is part of this module.
2. If 'yearpicker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("
      <daypicker tabindex="0"></daypicker>
      <monthpicker tabindex="0"></monthpicker>
      [ERROR ->]<yearpicker tabindex="0"></yearpicker>
    </datepicker-inner>
    "): DatePickerComponent@25:6 ; Zone: <root> ; Task: Promise.then ; Value: Error {message: "Template parse errors:
Binding to event attribute …atepicker-inner>
    "): DatePickerComponent@25:6"} Error: Template parse errors:
Binding to event attribute 'onlyCurrentMonth' is disallowed for security reasons, please use (lyCurrentMonth)=... ("ustomClass]="customClass"
                      [dateDisabled]="dateDisabled"
                      [ERROR ->][onlyCurrentMonth]="onlyCurrentMonth"
                      [shortcutPropagation]="shortcutPropagatio"): DatePickerComponent@20:22
'daypicker' is not a known element:
1. If 'daypicker' is an Angular component, then verify that it is part of this module.
2. If 'daypicker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("ation]="shortcutPropagation"
                      (selectionDone)="onSelectionDone($event)">
      [ERROR ->]<daypicker tabindex="0"></daypicker>
      <monthpicker tabindex="0"></monthpicker>
      <yearpicker"): DatePickerComponent@23:6
'monthpicker' is not a known element:
1. If 'monthpicker' is an Angular component, then verify that it is part of this module.
2. If 'monthpicker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("        (selectionDone)="onSelectionDone($event)">
      <daypicker tabindex="0"></daypicker>
      [ERROR ->]<monthpicker tabindex="0"></monthpicker>
      <yearpicker tabindex="0"></yearpicker>
    </datepicke"): DatePickerComponent@24:6
'yearpicker' is not a known element:
1. If 'yearpicker' is an Angular component, then verify that it is part of this module.
2. If 'yearpicker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("
      <daypicker tabindex="0"></daypicker>
      <monthpicker tabindex="0"></monthpicker>
      [ERROR ->]<yearpicker tabindex="0"></yearpicker>
    </datepicker-inner>
    "): DatePickerComponent@25:6
    at TemplateParser.parse (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:8530:21)
    at RuntimeCompiler._compileTemplate (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:16905:53)
    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:16828:85)
    at Set.forEach (native)
    at compile (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:16828:49)
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.6.23?main=browser:192:28)
    at Zone.run (https://unpkg.com/zone.js@0.6.23?main=browser:85:43)
    at https://unpkg.com/zone.js@0.6.23?main=browser:451:57
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.6.23?main=browser:225:37)
    at Zone.runTask (https://unpkg.com/zone.js@0.6.23?main=browser:125:47)
Error {rejection: Error: Template parse errors:
Binding to event attribute 'onlyCurrentMonth' is disallowed for securi…, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask, message: "Uncaught (in promise): Error: Template parse error…atepicker-inner>
    "): DatePickerComponent@25:6"}

**Comment by zakhenry** [comment]
@mayukhgit I got the same error, what was your resolution? (Assuming that's why you closed this issue)

**Comment by zakhenry** [comment]
This is caused by the update to angular that throws Error on event-like attribute names:

https://github.com/angular/angular/blob/2300c23332fe8a61427562770fb4e1911aad6e2e/modules/%40angular/compiler/src/template_parser/template_parser.ts#L905-L912

As the property `onlyCurrentMonth` starts with `on`, the error is thrown. Suggest renaming attribute to `currentMonthOnly` to circumvent the convention.
