### ISSUE TITLE
Open list data when focus on input

### ISSUE THREAD

**Issue by tuoitrexuquang** [valor-software/ngx-bootstrap#1005]
I'm using "typeahead"
<input [typeahead]="statesComplex"
         [typeaheadItemTemplate]="customItemTemplate"
         [typeaheadOptionField]="'name'"
         (typeaheadOnSelect)="typeaheadOnSelect($event)"
         class="form-control">

How do open the list "statesComplex" and select it when focus on input. I mean it like with example  "Typeahead inside a form" on this link http://valor-software.com/ng2-bootstrap/#/typeahead

Thanks

**Comment by chriscbrock** [comment]
If I have read your question right, what you are missing is:
[typeaheadMinLength]="0"
Which opens the list as soon as you click on the input.

**Comment by valorkin** [comment]
@chriscbrock thank for your help!

**Comment by sanyooh** [comment]
Would be cool to add this to an example to the demo page.
