### ISSUE TITLE
getting errors when compiling with gulp

### ISSUE THREAD

**Issue by skyplusplus** [valor-software/ngx-bootstrap#1006]
Hi,

i'm starting using angular2 and i'm having a problem with ng2-bootstrap. the ts compilation process is failing because of the errors shown below. i'm working in visual studio and using gulp to compile the ts files. I have the sample that i'm experimenting on in this repo: https://github.com/skyplusplus/ng2bootstrap-hell

> C:/Solution/Project/node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts(15,22): error TS1005: '=' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/buttons/button-radio.directive.d.ts(10,14): error TS1005: '=' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/buttons/button-radio.directive.d.ts(10,22): error TS1005: ';' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/dropdown/dropdown-toggle.directive.d.ts(11,14): error TS1005: '=' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/dropdown/dropdown-toggle.directive.d.ts(11,20): error TS1005: ';' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/modal/modal.component.d.ts(14,14): error TS1005: '=' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/modal/modal.component.d.ts(14,21): error TS1005: ';' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/modal/modal.component.d.ts(22,22): error TS1005: '=' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/position.d.ts(29,22): error TS1005: '=' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/position.d.ts(30,22): error TS1005: '=' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/tooltip/tooltip-container.component.d.ts(21,14): error TS1005: '=' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/tooltip/tooltip-container.component.d.ts(21,24): error TS1005: ';' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts(18,14): error TS1005: '=' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts(18,26): error TS1005: ';' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts(18,44): error TS1005: '(' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts(46,14): error TS1005: '=' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts(46,21): error TS1005: ';' expected.
> C:/Solution/Project/node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts(46,33): error TS1005: '(' expected.

**Comment by adrianfaciu** [comment]
You need to tell gulp-typescript to use the installed version of typescript instead of the bundled one. Have a look at #982.
