### ISSUE TITLE
chore(docs): Would be great if we can have an example on how to include in Webpack

### ISSUE THREAD

**Issue by born2net** [valor-software/ngx-bootstrap#101]
Would be awesome if we could have an example on how to include in Webpack, as Webpack is the de-facto ng2 packaging system... and with bootstrap it requires some work due to the assets included BS etc...

tx

Sean.

**Comment by valorkin** [comment]
ok

**Comment by born2net** [comment]
FYI the only way I can get it working so far with Webpack is to use the plugin of https://github.com/bline/bootstrap-webpack

and so my Webpack vendor file looks like:

```
// Polyfills
import 'angular2/bundles/angular2-polyfills.js';

// Angular 2
import 'angular2/platform/browser';
import 'angular2/platform/common_dom';
import 'angular2/core';
import 'angular2/router';
import 'angular2/http';

// RxJS
import 'rxjs';

require("bootstrap-webpack");
require("ng2-bootstrap/ng2-bootstrap");
require("bootbox");
require("font-awesome-webpack");
require("./styles/style.css");
require("./styles/fonts/Raleway.woff2");
require('underscore');
require('Immutable');
```

but I am sure there is way to achieve this without require("bootstrap-webpack");

regards

Sean

**Comment by valorkin** [comment]
oh, you mean bootstrap styles?
To be honest, I am including them into html directly
I was trying to import bootstrap styles webpack,
and then dropped this idea

For this module, I was planning to create css per module
so only needed css could be included

**Comment by born2net** [comment]
I don't mind loading first the require("bootstrap-webpack"); 
but is that ok? I mean, isn't loading just the entire BS x 2 ?
FYI 

I added this lib to: http://ng2.javascriptninja.io

should help this lib get more tracktion

**Comment by valorkin** [comment]
it is actually loading js and css,
I will check source code of one my projects
I did some hack to require only css

**Comment by valorkin** [comment]
actually I have ended up with 
`<link rel="stylesheet" href="./libs/bootstrap/dist/css/bootstrap.min.css">`

**Comment by born2net** [comment]
ya, I am trying to webpack it all in....

**Comment by valorkin** [comment]
is it really worth of efforts?

**Comment by born2net** [comment]
I think so, but I am happy with https://github.com/bline/bootstrap-webpack
seems to do the trick and works with this project... so good!

**Comment by valorkin** [comment]
I was removing section with scripts here : https://github.com/bline/bootstrap-webpack/blob/master/bootstrap.config.js
to include only css

**Comment by born2net** [comment]
I see

**Comment by valorkin** [comment]
@born2net should I close it, or you can create a PR with webpack instructions? to readme

**Comment by born2net** [comment]
we can close, tx!
