### ISSUE TITLE
Cannot do "typings install moment --save"

### ISSUE THREAD

**Issue by guidoffm** [valor-software/ngx-bootstrap#1015]
Doc for webpack says:

typings install moment --save

This is impossible:

:\app1>typings install moment --save
typings WARN hastypings Typings for "moment" already exist in "node_modules\moment\moment.d.ts". You should let TypeScript resolve the packaged typings and uninstall the copy installed by Typings
typings ERR! message Unable to find "moment" ("npm") in the registry.
typings ERR! message However, we found "moment" for 1 other source: "dt"
typings ERR! message You can install these using the "source" option.
typings ERR! message We could use your help adding these typings to the registry: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/npm/moment/versions/latest responded with 404, expected it to equal 200

typings ERR! cwd C:\app1
typings ERR! system Windows_NT 10.0.14393
typings ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\nc_guidomueller\AppData\Roaming\npm\node_modules\typings\dist\bin.js" "install" "moment" "--save"
typings ERR! node -v v6.2.2
typings ERR! typings -v 1.3.2

typings ERR! If you need help, you may report this error at:
typings ERR!   https://github.com/typings/typings/issues

**Comment by sudhashri** [comment]
Use `typings install dt~moment --save`.

**Comment by guidoffm** [comment]
I have tried this before and get:

C:\app1>typings install dt~moment --save
typings ERR! message Attempted to compile "moment" as an external module, but it looks like a global module. You'll need to enable the global option to continue.

typings ERR! cwd C:\app1
typings ERR! system Windows_NT 10.0.14393
typings ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\nc_guidomueller\AppData\Roaming\npm\node_modules\typings\dist\bin.js" "install" "dt~moment" "--save"
typings ERR! node -v v6.2.2
typings ERR! typings -v 1.3.2

typings ERR! If you need help, you may report this error at:
typings ERR!   https://github.com/typings/typings/issues

**Comment by Martin-Luft** [comment]
I would recommend PR #1020

**Comment by guidoffm** [comment]
This works for me
