### ISSUE TITLE
Uncaught ReferenceError: System is not defined with angular-cli generated project

### ISSUE THREAD

**Issue by guidoffm** [valor-software/ngx-bootstrap#1016]
I have set up a new project with angular-cli.

ng new app1

What do I have to do to add ng2-bootstrap to this empty app?

angular-cli uses webpack2.

**Comment by sudhashri** [comment]
Install ng2-bootstrap in previous way
`npm i -save ng2-bootstrap` 

For installing moment, do the following
`npm install -save @types/moment`

You can start using ng2-bootstrap features straightaway. If any of the features include have directives, like Modal, declare them in your root component(ngModule).

For Modal,

```
import { ModalModule } from 'ng2-bootstrap/ng2-bootstrap';
@NgModule({
   declarations: [
       .....
   ],
   imports: [
      .....
      ModalModule, //Modals
      ......
  ],
  ....
```

In your template, use the templates according to ng2-bootstrap usages.

```
 <!-- Small modal -->
 <button type="button" class="btn btn-primary" (click)="smModal.show()">Small modal</button>

 <div bsModal #smModal="bs-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
     .......
 </div>
```

**Comment by guidoffm** [comment]
This is all known.

But when you use angular-cli then SystemJS is not used but WebPack. You only get an error message from ng2-bootsrap complaining that SystemJS is missing.

**Comment by guidoffm** [comment]
If you would like to check this do the following:

Install angular-cli:
`npm i - angular-cli`

Create a new project:
`ng new app1`

Go into the app1 folder.

Add other npm libraries by installing them with
`npm i bootstrap ng2-bootstrap bootstrap@4.0.0-alpha.4 --save`

Adjust the file angular-cli.json in the generated project and add additional entries to the "scripts" and "styles" arrays:

Add `"../node_modules/bootstrap/dist/css/bootstrap.min.css"` to styles
Add `"../node_modules/ng2-bootstrap/bundles/ng2-bootstrap.js"` to scripts

Add one ng2-bootstrap component to the generated component app.component.html, app.component.ts and app.module.ts. (Optional. Not needed to get the error.)

Start the project by running

`ng s`

Open up a web browser and and goto http://localhost:4200

Watch the browser console for messages

I have created a test project here:

https://github.com/guidoffm/ng2-bootstrap-issue1016

**Comment by isaackehle** [comment]
Seeing the same thing with this last description.

**Comment by guidoffm** [comment]
You mean you get the error message too?

**Comment by isaackehle** [comment]
Yes, I do.  I have the same setup as you, and I get the same error message.

**Comment by valorkin** [comment]
As far as I now ng-cli is not system.js any more,
they are using webpack now,
so you don't need to use system.js bundle
rather use common.js ng2-bootstrap.js

**Comment by valorkin** [comment]
Or I will have to change bundles to common.js

**Comment by guidoffm** [comment]
Please make it compatible with angular-cli beacuse that is the recommended way to create an app

**Comment by valorkin** [comment]
Already did, will be published today.
Readme already updated
Closing this issue
