### ISSUE TITLE
Few issues while using ng2-bootstrap

### ISSUE THREAD

**Issue by pratiksharma9** [valor-software/ngx-bootstrap#1019]
Hello Friends,

**Error occurred after import in modules.**  

node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts(14,22): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts(15,22): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/buttons/button-radio.directive.d.ts(10,14): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/buttons/button-radio.directive.d.ts(10,22): error TS1005: ';' expected.
node_modules/ng2-bootstrap/components/dropdown/dropdown-toggle.directive.d.ts(11,14): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/dropdown/dropdown-toggle.directive.d.ts(11,20): error TS1005: ';' expected.
node_modules/ng2-bootstrap/components/modal/modal.component.d.ts(14,14): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/modal/modal.component.d.ts(14,21): error TS1005: ';' expected.
node_modules/ng2-bootstrap/components/modal/modal.component.d.ts(22,22): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/position.d.ts(29,22): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/position.d.ts(30,22): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/tooltip/tooltip-container.component.d.ts(21,14): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/tooltip/tooltip-container.component.d.ts(21,24): error TS1005: ';' expected.
node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts(18,14): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts(18,26): error TS1005: ';' expected.
node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts(18,44): error TS1005: '(' expected.
node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts(46,14): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts(46,21): error TS1005: ';' expected.
node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts(46,33): error TS1005: '(' expected.

let me know when it is fixed .

**Comment by adrianfaciu** [comment]
You need to update your Typescript version used. [Several closed issues](https://github.com/valor-software/ng2-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20typescript) about this, have a look through [them](https://github.com/valor-software/ng2-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20typescript).

**Comment by pratiksharma9** [comment]
Thanks, **adrianfaciu**. Now it is working  :+1:
