### ISSUE TITLE
feat(carousel): add toggle opportunity for carousel-indicators

### ISSUE THREAD

**Issue by artdias90** [valor-software/ngx-bootstrap#1021]
Is there a way to switch off carousel slides direct link below the slide? Would like to not show that.

**Comment by valorkin** [comment]
small PR could help
- you can add new @Input() property `....` (not sure about name)
- and one *ngIf to carousel template

it should be visible by default of course, or it will be a breaking change for other users

**Comment by valorkin** [comment]
BTW if you have any questions, welcome to slack

**Comment by gmenih** [comment]
@valorkin which branch should I branch off of, if I want to implement this?

**Comment by valorkin** [comment]
https://github.com/valor-software/ng2-bootstrap/tree/feat-ng-cli

if possible wait until Friday, I want to finish structure refactoring and update deploying model
test it and merge to dev

**Comment by gmenih** [comment]
@valorkin yeah sure. I hide them with CSS for now, so no rush.
