### ISSUE TITLE
No provider for ModalBackdropOptions!

### ISSUE THREAD

**Issue by Neill83** [valor-software/ngx-bootstrap#1022]
Hi,

I use angular-cli 1.0.0-beta.15 with webpack, angular 2.0.0 final and ng2-bootstrap 1.1.5

I got the following Error

No provider for ModalBackdropOptions!

I have an own npm package with NgModule which imports ModalModule from ng2-bootstrap.
I installed the npm package on my main-project and imported the "AppModule" from my npm package.

When i start the App from my npm package it works fine, but when i start my main-project i get this error.

Maybe you can help me.
Thanks

**Comment by Neill83** [comment]
closed... i made a mistake injecting the components dynamically

**Comment by kavi87** [comment]
Hi, would you mind commenting on your solution ? I'm also compiling component dynamically and whenever a component uses a modal I get this error.
