### ISSUE TITLE
How to call Modal showChildModal method in the parent modal to open the modal in a table list

### ISSUE THREAD

**Issue by calvinKG** [valor-software/ngx-bootstrap#1029]
Hi Guys, 

I have table list and I want to call showChildModal () method to open the modal when i click on a raw. 

Code. 

`

@Component({
    selector: 'ua-add-function',
    templateUrl: 'src/app/pages/user-auth/components/function-admin/add/ua-add-function.html',
    exportAs: 'child'
})
export class Add_function
{
  @ViewChild('lgModal') public childModal:ModalDirective;

public showChildModal():void {
        this.childModal.show();
    }
}
`

Parent
`export class UA_Functional_Admin{
      onRowSelect(event)
    {
        // I want to call the showChildModal() to open the modal in here
    }
}
`
html 

`<button type="button" class="btn fnb-submit-btn" (click)="c.showChildModal()">Add Function</button>           
`

**Comment by valorkin** [comment]
@calvinKG are you trying to achieve nested modals?
