### ISSUE TITLE
add jquery plugin in the provideplugin of the webpack 

### ISSUE THREAD

**Issue by alaa-bourouissi** [valor-software/ngx-bootstrap#1037]
Hello , I want to add the jquery plugin in the webpack file , but I don't find where to add it , 

plugins: [
        new webpack.ProvidePlugin({
            'window.jQuery': 'jquery',
            'window.$': 'jquery',
        })
],

Where to add this code ???

**Comment by Martin-Luft** [comment]
The ng2-bootstrap is a project to provide Bootstrap widgets for Angular 2 without jQuery (widgets are written in Angular 2). So please do not include jQuery!

**Comment by alaa-bourouissi** [comment]
So how can I add plugins in my app ??

**Comment by Martin-Luft** [comment]
What kind of plugins?

**Comment by alaa-bourouissi** [comment]
I want to add this example : http://www.jqueryscript.net/chart-graph/Canvas-Based-Temperature-Gauge-Plugin-For-jQuery-TempGauge.html

**Comment by Martin-Luft** [comment]
Then you should use Bootstrap with jQuery. We can't provide support for webpack with Bootstrap and jQuery in this project because it is offtopic. Please ask the webpack, Bootstrap or jQuery guys.

@valorkin or do you think differently about?

**Comment by alaa-bourouissi** [comment]
I found the solution for using jQuery with angular 2 but I would like to know where can I add this code : plugins: [
        new webpack.ProvidePlugin({
            'window.jQuery': 'jquery',
            'window.$': 'jquery',
        })
],

I get it from  (https://github.com/fronteed/icheck/issues/322)  , the webpack.config.js is complicated to understand

**Comment by Martin-Luft** [comment]
Then add it to your webpack config? Do you have a webpack project?

**Comment by alaa-bourouissi** [comment]
yes , but I just tell you I don't know or I don't find where to add it , there is many files related to the webconfig.ts

**Comment by Martin-Luft** [comment]
Please understand that your question is a webpack related and not ng2-bootstrap related... Do you have a webpack.common.js file? Add the plugin inside the plugins list.
