### ISSUE TITLE
splice slide in carousel results in no slide being active

### ISSUE THREAD

**Issue by artdias90** [valor-software/ngx-bootstrap#1039]
I tried to manually map() my slies and set the next one as `active,` but it doesn't work when I move to the next slide (2 slides get active).

**Comment by valorkin** [comment]
yeah, carousel state machine should be rewritten

**Comment by valorkin** [comment]
in terms of timeline, all of it will be rewritten before end of december ;)

**Comment by valorkin** [comment]
Tomorrow will be merged
