### ISSUE TITLE
chore(css): style problem

### ISSUE THREAD

**Issue by PotatoTroll** [valor-software/ngx-bootstrap#104]
Sorry for writing in the wrong place, I tried to implement ng2-bootstrap but there is a problem, I cannot change the style of components. I implemented an "alert" in on of my page where it had all margins removed before by applying a style only to my component. But now with ng2-bootsrap, I cannot change the style of components at all...
Am I missing something?
I don't think adding all styles for each component to the the global bootstrap.css file is an option.

**Comment by valorkin** [comment]
Adding bootstrap.css to html is always is option :)
extracting only required styles are tricky
check this thread for now https://github.com/valor-software/ng2-bootstrap/issues/101
later on ng2-bootstrap will have different bundles
- without styles
- with bs3
- with bs4

**Comment by valorkin** [comment]
What you actually want is emulating shadow dom and in lining or referencing component specific styles
BS3 doesn't provide inbox this separation, unfortunately

**Comment by PotatoTroll** [comment]
Well, there is a possibility to insert the bootstrap.css globally, and override each property you need in shadow DOM. For example with alerts, bootstrap.css is global, and I override the margin property of alert class(or any other property I need) in component style or styleUrl.

**Comment by valorkin** [comment]
you can use bootstrap-theme.css approach for global overrides
and extend component and add competent level style overrides
