### ISSUE TITLE
ModalDirective: Background of modal dialog is not hiding after navigation to another page

### ISSUE THREAD

**Issue by aperevalov** [valor-software/ngx-bootstrap#1051]
Trying to use modal directive and found an issue. Background is not hiding when you navigate to another page.
Reproducible on official demo site:
1. Navigate to http://valor-software.com/ng2-bootstrap/#/
2. Click on Modals menu
3. Click on "Large Example" button, Dialog should appear.
4. Click "Back" button in your browser
5. Observe the whole page hidden behind semi transparent dialog's background.

Also reproducible if I put routerLink in the body of my dialog to navigate to another component, so it's not linked directly to browser navigation through native buttons.

I also tried to implement OnDestroy in my component and call there dialog's hide() method, but looks like OnDestroy is not called at all in steps above, maybe I understood meaning of OnDestroy wrong.

I'll try to find a solution, but maybe someone already know a workaround.

**Comment by tbadlov** [comment]
This is actually not fixed. 

Check your documentation page, open a modal window and then navigate back and forth. 
The modal is still open. I wasn't able to solve this by using the `bsModalRef.hide()`method.

Any workaround known workarounds this?
