### ISSUE TITLE
feat(alerts): ng2-bootstrap native implementation of Toastr/Notify.js

### ISSUE THREAD

**Issue by IlyaSurmay** [valor-software/ngx-bootstrap#1063]
It would be great if we had native ng2 implementation of  [Toastr](http://codeseven.github.io/toastr/demo.html) or  [Notify.js](https://notifyjs.com/)

**Comment by Martin-Luft** [comment]
How this is bootstrap related?

**Comment by IlyaSurmay** [comment]
This module may use bootstrap elements like alerts. But bootstrap is not the only ng2 project of Valor Software, there are also  ng2-tables, ng2-charts etc, so it's just another idea

**Comment by Martin-Luft** [comment]
@valorkin can you please say something about what people can do with ideas :) ?

**Comment by valorkin** [comment]
I need to update positioning part first,
and it will be available as not core module
