### ISSUE TITLE
How to add this library to Angular2 app which is written in es6 instead of typescript

### ISSUE THREAD

**Issue by NishantDesai1306** [valor-software/ngx-bootstrap#1064]
Can anyone guide me how to add this library in angular2 module 

```
(function(app) {
    app.AppModule = function AppModule() {};
    app.AppModule.annotations = [
        new ng.core.NgModule({
            imports: [ng.platformBrowser.BrowserModule],
            declarations: [app.TodoListComponent],
            bootstrap: [app.TodoListComponent]
        })
    ];
})(window.app || (window.app = {}));
```

I guess it should be added in imports array but I don't know (for example after adding angular2 cdns 
i can access angular2 modules using `ng.` )

**Comment by Martin-Luft** [comment]
Duplicate of https://github.com/valor-software/ng2-bootstrap/issues/921 and https://github.com/valor-software/ng2-bootstrap/issues/923
