### ISSUE TITLE
invalid date input destroys datepicker

### ISSUE THREAD

**Issue by dasAnderl** [valor-software/ngx-bootstrap#1065]
i'm using ng2-bootstrap with bootstrap 4.
when i select a date its fine, as soon as i change the value in the input, the datepicker reflects the changes and freaks out (especially if its an invalid date )
(see attached screenshot)
<img width="1920" alt="bildschirmfoto 2016-10-03 um 13 41 10" src="https://cloud.githubusercontent.com/assets/4852884/19041548/ce7a143a-8988-11e6-9b3e-bff4d7fb7b7b.png">

as long theres no validation error datepicker behaves normal
src:

`<div class="input-group">
                    <span class="input-group-addon">start time</span>
                    <input type="text" class="form-control" #start="ngModel"
                           name="start" [(ngModel)]="geoDefinition.periodicSchedule.startTime">
                    <div class="input-group-addon"
                         (click)="showStartTimePicker = !showStartTimePicker">
                        <i class="fa fa-calendar-plus-o" aria-hidden="true" *ngIf="!showStartTimePicker"></i>
                        <i class="fa fa-calendar-minus-o" aria-hidden="true"  *ngIf="showStartTimePicker"></i>
                        <div class="app-datepicker" *ngIf="showStartTimePicker">
                            <datepicker [(ngModel)]="geoDefinition.periodicSchedule.startTime"
                                        [showWeeks]="true" name="startTimePicker">
                            </datepicker>
                        </div>
                    </div>
                </div>`

package.json

{
"name": "web2",
"version": "0.0.0",
"license": "MIT",
"angular-cli": {},
"scripts": {
"start": "ng serve",
"lint": "tslint \"src/*/.ts\"",
"test": "ng test",
"pree2e": "webdriver-manager update",
"e2e": "protractor"
},
"private": true,
"dependencies": {
"@angular/common": "2.0.0",
"@angular/compiler": "2.0.0",
"@angular/core": "2.0.0",
"@angular/forms": "2.0.0",
"@angular/http": "2.0.0",
"@angular/platform-browser": "2.0.0",
"@angular/platform-browser-dynamic": "2.0.0",
"@angular/router": "3.0.0",
"core-js": "^2.4.1",
"ng2-bootstrap": "^1.1.5",
"ng2-cookies": "^1.0.2",
"ng2-validation": "^2.0.0",
"rxjs": "5.0.0-beta.12",
"ts-helpers": "^1.1.1",
"zone.js": "^0.6.23"
},
"devDependencies": {
"@types/jasmine": "^2.2.30",
"angular-cli": "1.0.0-beta.15",
"codelyzer": "~0.0.26",
"jasmine-core": "2.4.1",
"jasmine-spec-reporter": "2.5.0",
"karma": "1.2.0",
"karma-chrome-launcher": "^2.0.0",
"karma-cli": "^1.0.1",
"karma-jasmine": "^1.0.2",
"karma-remap-istanbul": "^0.2.1",
"protractor": "4.0.5",
"ts-node": "1.2.1",
"tslint": "3.13.0",
"typescript": "2.0.2"
}
}

**Comment by valorkin** [comment]
fixed in new datepicker
available in v1.9.2
http://valor-software.com/ngx-bootstrap/#/datepicker
