### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by khs-fn** [valor-software/ngx-bootstrap#1067]
Got the following npm message during installation but I actually have @angular @2.0.1installed on my machine. Is there a way to get rid of the message? Please advise. Thanks
P.S.: npm -v => 3.8.1

npm WARN ng2-bootstrap@1.1.5 requires a peer of @angular/common@2.0.0 but none was installed.
npm WARN ng2-bootstrap@1.1.5 requires a peer of @angular/compiler@2.0.0 but none was installed.
npm WARN ng2-bootstrap@1.1.5 requires a peer of @angular/core@2.0.0 but none was installed.
npm WARN ng2-bootstrap@1.1.5 requires a peer of @angular/forms@2.0.0 but none was installed.

**Comment by Gapplay** [comment]
It's just a warning, ignore it. They have to update the package to suppress it.

**Comment by zrhmn** [comment]
Hmm. I've got

```
npm ERR! peer dep missing: @angular/common@2.0.0, required by ng2-bootstrap@1.1.5
npm ERR! peer dep missing: @angular/compiler@2.0.0, required by ng2-bootstrap@1.1.5
npm ERR! peer dep missing: @angular/core@2.0.0, required by ng2-bootstrap@1.1.5
npm ERR! peer dep missing: @angular/forms@2.0.0, required by ng2-bootstrap@1.1.5
```

**<Edit>**
Ubuntu 14.04
Node v6.3.1
NPM v3.10.6
**</Edit>**

So, not really _just a warning_. The problem is: In 1.1.5, the versions of `@angular/*` is tied at version `"2.0.0"`. It should be `"~2.0.0"` or something like that. This was fixed in 19c0c611afb8c292f0e666d8a859569af6c839fe (develop) but hasn't been tagged for release yet.

**Comment by nthonymiller** [comment]
:+1: Please deploy latest to npm

**Comment by Martin-Luft** [comment]
Related to https://github.com/valor-software/ng2-bootstrap/issues/1028

**Comment by valorkin** [comment]
testing... publish to npm later today
