### ISSUE TITLE
How I can set viewContainerRef  if I'm using ngUpgrade?

### ISSUE THREAD

**Issue by gios** [valor-software/ngx-bootstrap#1069]
`adapter.bootstrap(document.documentElement, ["myApp"]).ready((a) => {
  console.log("myApp Ready!");
});`
My main ngModule doesn't have bootstrap component because I loaded it through UpgradeAdapter?

**Comment by gios** [comment]
Thanks for your quick response!

**Comment by valorkin** [comment]
Please confirm that this hack is working for you, so I can update docs :)

**Comment by gios** [comment]
`const comps = this.applicationRef.components;`
comps constant returns 0, and I got an error **ApplicationRef instance not found**

**Comment by valorkin** [comment]
Not fun, do you have a repo so I can reproduce it?

**Comment by gios** [comment]
I have a private repository not in github, unfortunately I can't give you access to it.

**Comment by gios** [comment]
What is the progress with this issue?

**Comment by valorkin** [comment]
I need a sample to reproduce and debug locally

**Comment by gios** [comment]
I answered this question here [#1056](https://github.com/valor-software/ng2-bootstrap/issues/1056)
