### ISSUE TITLE
chore(dropdown): check behaviour

### ISSUE THREAD

**Issue by dumham** [valor-software/ngx-bootstrap#107]
dropdown doesn`t work for versions combination, marked in title.

**In case of importing .js sources:**
it`s included and initialized but the only thing it does is to set 'dropdown' class to host element.

**In case of .ts including**
_Uncaught SyntaxError: Unexpected token )_ errors appear in dropdown.directive.ts and dropdown-toggle.directive.ts at lines with @HostBinding statements

**Comment by dumham** [comment]
dropdowns also don`t work for me for angular2@2.0.0-beta.2 + ng2-bootstrap@1.0.1-beta.2

**Comment by valorkin** [comment]
ok, latest tomorrow will be next version of ng2-bootstrap
with a bunch of fixes, I will ask you to try again, ok?

**Comment by dumham** [comment]
looking forward, will try
Thank you

**Comment by dumham** [comment]
not sure what was the cause, but it works now

**Comment by valorkin** [comment]
@dumham it seems some issues was fixed with upgrading to 0-beta.3
