### ISSUE TITLE
Tooltip inside animated element is not placed correctly

### ISSUE THREAD

**Issue by nobilo** [valor-software/ngx-bootstrap#1070]
Hello,
It looks like there is problem with tooltip position if it is placed inside an animated element. I have created plunker for more details:

https://plnkr.co/edit/ck8Z15Q648Me5QYNeDlZ?p=preview

When one hovers over yellow div tooltip is not displayed onto it.
Thanks for your work !

**Comment by valorkin** [comment]
Just to keep you updated
Some strange behavior in positioning
So I will be rewriting positioning service
stay tunned

**Comment by JulioC** [comment]
I'm having the same issue when using tooltips inside elements with `transform: scale`

**Comment by valorkin** [comment]
Please check new implementation
