### ISSUE TITLE
Imports from ng2-bootstrap\components\... don't work since 1.1.6

### ISSUE THREAD

**Issue by ctrl-brk** [valor-software/ngx-bootstrap#1076]
All these files are deleted now.
Are we suppose to use ng2-bootstrap\ng2-bootstrap only?

**Comment by valorkin** [comment]
@ctrl-brk what exactly you was importing? modules should be available
check this one https://unpkg.com/ng2-bootstrap@1.1.6/components/accordion/

**Comment by ctrl-brk** [comment]
DropDown. There used to be a dropdown.js file in the components folder. Don't see it anymore. Same for accordion.

**Comment by valorkin** [comment]
you need *.module.js files now

**Comment by valorkin** [comment]
I was thinking of making index.js files

**Comment by ctrl-brk** [comment]
So, `ng2-bootstrap/components/dropdown`
goes to
`ng2-bootstrap/components/dropdown/dropdown.module`

Ok. More typing is always fun :)

**Comment by valorkin** [comment]
not really :)
I was planning to have it like `ng2-bootstrap/dropdown`

**Comment by valorkin** [comment]
or `ng2-bootstrap/dropdown.module`
BTW what if you will be able to import needed module from
`ng2-bootstrap` ?

**Comment by ctrl-brk** [comment]
Kind of similar to using ng2-bootstrap/ng2-bootstrap now? Fine with me if it doesn't affect performance. I was under impression that importing from separate modules is more efficient.

**Comment by valorkin** [comment]
is issue solved? :)

**Comment by ctrl-brk** [comment]
For me - yes. Fortunately I don't use many of these components yet so it's easy to update ))
