### ISSUE TITLE
Typeahead custom view value

### ISSUE THREAD

**Issue by vlahanas** [valor-software/ngx-bootstrap#1078]
Hello all,

this is a question, not an issue.
I want to know if there is an option of having different view value and query value for typeahead. Let's say i have an array of json objects that are like:

{
  name: 'Alpha',
  description: 'this string is the description of the alpha object'
}

I want the typeahead to search within the description property so i am using this as typeaheadOptionField. Also, i am using typeaheadItemTemplate in order to show the name of the item in the dropdown. My problem is that after selecting an item, i want the input field of the typeahead to show its name instead of the description, and this i cannot achieve. 

Any suggestions?

**Comment by Martin-Wegner** [comment]
You could use `[(ngModel)]="selectedValue" (typeaheadOnSelect)="applyDescription($event.item)"` and the applyDescription() method could make `this.selectedValue = ...` but for that you must cache your result from which you could get the description, hmmm...

**Comment by Martin-Luft** [comment]
You could use the 'Custom item template example' from http://valor-software.com/ng2-bootstrap/#/typeahead

**Comment by vlahanas** [comment]
Thanks for the reply,
not exactly the same, since i want the typeahead to also display a custom template in the input box after a selection has been performed. In the example, the custom template only appears in the dropdown options.

**Comment by Martin-Luft** [comment]
The custom template appears in the dropdown options and after the selection a total different string apperas in the input box. So that is exactly what you described above? What I'm missing?

**Comment by vlahanas** [comment]
Sorry for not making it clear,

i want the custom template to also appear in the input box after selection, instead of the typeaheadOptionField.

**Comment by Martin-Luft** [comment]
So you could do this:

```
public typeaheadOnSelect(e: any): void {
  this.customSelected = e.item.name;
  console.log('Selected value: ', e.item.id);
}
```

**Comment by vlahanas** [comment]
Thanks again for the reply @Martin-Wegner ,

this is what i tried initially, but it creates a small "flicker" as the input value changes twice on each selection (Once before the event was raised, and once inside the typeaheadOnSelect function).

**Comment by Martin-Luft** [comment]
@valorkin any idea?

**Comment by valorkin** [comment]
@vlahanas fast solution is:
inherit typeahead and replace some function with methods of your desire
it is easier than sounds

When you are done you will be able to make a PR
if you have any question how to: join slack and we can chat about it

**Comment by Martin-Luft** [comment]
@vlahanas does this help you? Can I close?

**Comment by vlahanas** [comment]
Yes, thank you

i think you can close the issue for now, and if something more is needed i will ask you to re-open it!
