### ISSUE TITLE
btnRadio is private

### ISSUE THREAD

**Issue by cummingsi1993** [valor-software/ngx-bootstrap#1079]
Hey all, maybe im missing something but i'm having a hard time with the buttons module. If i write something like: 
`<label class="btn btn-primary-outline" [(ngModel)]="view" name="view" [btnRadio]="simple">Simple View</label>`

I get the error message:

> Property 'btnRadio' is private and only accessible within class 'ButtonRadioDirective'

After looking at the module the error message is correct. In the ButtonRadioDirective, the 'btnRadio' is a private input. Is there an updated way to use this directive? 

Edit: I don't know if its significant, but i am using ngc to compile my application ahead of time.

**Comment by Martin-Luft** [comment]
The ButtonCheckboxDirective is declared and exported in the buttons module. But the btnRadio input property is marked private. But in the example https://valor-software.com/ng2-bootstrap/#/buttons it is public. The code in the example is not the current code in the repository. @valorkin I think something is broken!

**Comment by cummingsi1993** [comment]
Thats what i was thinking too. It probably works under normal circumstances because the 'private' modifier is a compile time construct. But when you use AOT the angular compiler generates typescript code that accesses that property. Since the property is private the typescript compiler throws up all over the place.

**Comment by valorkin** [comment]
@cummingsi1993 please try v1.1.8

**Comment by cummingsi1993** [comment]
Sweet thanks!
