### ISSUE TITLE
Pager issue 'totalItems' since it isn't a known property

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#1082]
Hi Guys,

I'm using pager in the same way as pagination, but doesn't work as pagination, I'm receiving the following error:

Can't bind to 'totalItems' since it isn't a known property of 'pager'

I've reviewed and I can't find that property in pager.component

**Comment by Martin-Luft** [comment]
Pager extents Pagination and Pagination has public setter and getter methods for totalItems.

The pager component works for me. Please have a look at: https://valor-software.com/ng2-bootstrap/#/pagination

If you still have problems: Please show us your HTML template, the related component and your ngModel definition.

@bruno-serfe I will close this issue. Please comment this issue if you still have problems and I will reopen it.
