### ISSUE TITLE
pagination module not working

### ISSUE THREAD

**Issue by kodiraj** [valor-software/ngx-bootstrap#1091]
**in my module.ts**

i included the following statement

import { PaginationModule } from 'ng2-bootstrap/components/pagination';

in my ngmodule i added PaginationModule as well.

**in my componnent**  i added 

public totalItems:number = 64;
  public currentPage:number = 4;

  public maxSize:number = 5;
  public bigTotalItems:number = 175;
  public bigCurrentPage:number = 1;

in my **html**

<pagination [totalItems]="totalItems" [(ngModel)]="currentPage" ></pagination>

when i ran it,i am getting 
main.bundle.js:42026 Error: Template parse errors:(…)

**Comment by Martin-Luft** [comment]
Can you show use your HTML and the complete error message?

**Comment by Martin-Luft** [comment]
@kodiraj please answer...

**Comment by kodiraj** [comment]
hi,

My bad.With further debugging,i found out its due to my code it didnt work.

Thanks.

Do you have any plnkr with working example.

**Comment by Martin-Luft** [comment]
We have the demo page:
http://valor-software.com/ng2-bootstrap/#/pagination

And a basic plnkr:
https://plnkr.co/edit/2lDiJaezvCOcSyd2dd2Q?p=info
