### ISSUE TITLE
Datepicker: selectionDone triggered on any ngModel change

### ISSUE THREAD

**Issue by renehamburger** [valor-software/ngx-bootstrap#1095]
I am aware that a complete overhaul of the datepicker is on the way, but this issue has been introduced very recently (between ng2-bootstrap 1.1.5 and 1.1.7). In 1.1.5, 'selectionDone' was only triggered when the user made a selection in the datepicker, but in 1.1.7 and later, any change to datepicker's ngModel now triggers it, including the very first one on initialisation. (This is particularly devastating for any popup version of the datepicker closing the popup on selectionDone.)

**Comment by valorkin** [comment]
yep, this behavior was introduced with https://github.com/valor-software/ng2-bootstrap/commit/fb6d532af210093f5b0570840106e7056b144e25

**Comment by valorkin** [comment]
please check v1.1.11

**Comment by renehamburger** [comment]
Yes, great. Thanks for the quick fix!
