### ISSUE TITLE
How to create templates for modal bodies and pass them to the modal (service?)

### ISSUE THREAD

**Issue by 281330** [valor-software/ngx-bootstrap#1101]
Just wondering if there's some way to do this.

For example, if I have a modal that shows some offer information, and another modal that will have exit confirmation (Are you sure you want to quit?), how can I keep these modal templates separate and just simply pass them to the modal service?

Right now, I have basically followed the documentation.  In the case of the exit confirmation modal, it is part of the UploadPhoto component, which is a series of 3 steps (its for uploading pro photography stuff, so needs a lot of info) and if the user tries to exit from uploading steps, this modal should pop up that asks Are you sure you want to quit?  I have the template for the modal included at the bottom of the `upload-photo.component.html`.

If there's a way to separate the modal templates that'd be great.  Please let me know if that's possible.

**Comment by valorkin** [comment]
right now, you can create separate components which will encapsulate your modals
you can track this issues #579
