### ISSUE TITLE
timepicker mousewheel / arrowkeys not working

### ISSUE THREAD

**Issue by ttrmnn** [valor-software/ngx-bootstrap#1102]
I'm following the example setup from http://valor-software.com/ng2-bootstrap/index-bs4.html#/timepicker. 

However neither `[mousewheel]="true"` or `[arrowkeys]="true"` seems to work.

Anyone having the same problem?

Thanks a lot!

**Comment by adrianfaciu** [comment]
From what I see these properties are not [used/implemented yet.](https://github.com/valor-software/ng2-bootstrap/blob/development/components/timepicker/timepicker.component.ts#L160)

**Comment by ttrmnn** [comment]
Oh I didn't realize that. Thank you!
