### ISSUE TITLE
Typeahead: Extra nesting bug with onSelect data since v1.1.10

### ISSUE THREAD

**Issue by adrienverge** [valor-software/ngx-bootstrap#1103]
Hi,

`(typeaheadOnSelect)` previously emitted an `Object {item: any}` argument, from v1.1.10 it emits an `Object {item: TypeaheadMatch {item: any, value: string, header: string}}`, causing an exception in the parent component because the data is now in `event.item.item` (previously `event.item`).

One would expect either `Object {item: any}` or `TypeaheadMatch {item: any, value: string, header: string}` instead.

I'd be happy to provide additional information if needed (v1.1.9 appears to be working correctly).

**Comment by Martin-Luft** [comment]
In 1.1.11 a `TypeaheadMatch` object will be provided via the onSelect() method and you can use it's `item` or `value` property.

```
onSelect(selection: TypeaheadMatch): void {
  console.log(selection.item);
  console.log(selection.value);
}
```

**Comment by adrienverge** [comment]
Hi @Martin-Wegner,

No, on 1.1.10 and 1.1.11 the emitted value is not a `TypeaheadMatch` but an `Object: {item: TypeaheadMatch}`.

**Comment by Martin-Luft** [comment]
@adrienverge I'm using 1.1.11 and in my application it is a `TypeaheadMatch` object:

> TypeaheadMatch {item: "201", value: "201", header: false}

**Comment by adrienverge** [comment]
I've cut as much options as possible to reduce the bug to this very simple piece:

``` ts
export class MyComponent {
  str: string;
  suggestions$ = Observable.of([1, 2, 3]);

  typeaheadOnSelect(e: any): void {
    console.log(e);
  }
}
```

``` html
<input [(ngModel)]='str' [typeahead]='suggestions$'
       (typeaheadOnSelect)='typeaheadOnSelect($event)' />
```

Output in browser:

```
Object {item: TypeaheadMatch}
    item: TypeaheadMatch
        header: false
        item: 2
        value: "2"
```

For information:

```
$ grep version node_modules/ng2-bootstrap/package.json
  "version": "1.1.11",
$ grep version node_modules/@angular/core/package.json
  "version": "2.0.2",
```

**Comment by Martin-Luft** [comment]
@adrienverge arg you are totally right, I missed `onSelect($event.item)` in my template...

**Comment by Martin-Luft** [comment]
The problem is in `typeahead-container.component.ts`

```
private selectMatch(value:TypeaheadMatch, e:Event = void 0):boolean {
    if (e) {
      e.stopPropagation();
      e.preventDefault();
    }
    this.parent.changeModel(value);
    setTimeout(() =>
      this.parent.typeaheadOnSelect.emit({
        item: value
      }), 0
    );
    return false;
  }
```

Should be

```
private selectMatch(value:TypeaheadMatch, e:Event = void 0):boolean {
    if (e) {
      e.stopPropagation();
      e.preventDefault();
    }
    this.parent.changeModel(value);
    setTimeout(() =>
      this.parent.typeaheadOnSelect.emit(value), 0
    );
    return false;
  }
```

**Comment by adrienverge** [comment]
Thanks a lot @Martin-Wegner.

I'll do a pull request.
