### ISSUE TITLE
How to use it with: Angular2 Seed

### ISSUE THREAD

**Issue by joelmuskwe** [valor-software/ngx-bootstrap#1108]
How can i use ng-bootstrap with [Angular2 Seed](https://github.com/mgechev/angular-seed)

**Comment by adrianfaciu** [comment]
You can check out the [examples part on angular2-seed project](https://github.com/mgechev/angular-seed#examples) there is at least one using ng2-bootstrap.

**Comment by Martin-Luft** [comment]
@joelmuskwe can I close this issue?
