### ISSUE TITLE
feat(position): "auto" placement in tooltip|popover|etc.

### ISSUE THREAD

**Issue by daniru** [valor-software/ngx-bootstrap#1111]
Hi,

Could be possible to expose the "auto" option for placement in the tooltip element ?
[http://getbootstrap.com/javascript/#tooltips-options](http://getbootstrap.com/javascript/#tooltips-options)

Thanks

**Comment by valorkin** [comment]
yes! positioning service will be updated

**Comment by sergeushenecz** [comment]
+1

**Comment by 1-0-1** [comment]
Can auto positioning be applied to dropdowns such as in typeahead?

**Comment by evandrojr** [comment]
+1

It is mostly finished. There is some unknown bug that needs to be fixed.

https://github.com/valor-software/ngx-bootstrap/pull/1986

**Comment by cannontechnology** [comment]
Is there any way to specify "auto bottom"...  It appears that it now defaults to "auto right" which does not work in all use cases.  In my case I have a very long popover that forces a scroll when opened near the bottom of the page.  Having the flexibility to specify the default position i.e. "auto bottom" or "auto top" would be great.
