### ISSUE TITLE
feat: add pills support 

### ISSUE THREAD

**Issue by Ovidiu-S** [valor-software/ngx-bootstrap#1112]
Is there a plan for supporting bootstrap pills: 
http://getbootstrap.com/components/#nav-pills

Temporarily we use them from this project: 
https://github.com/ng-bootstrap/ng-bootstrap
but it would be nice to have them in ng2-bootstrap.

**Comment by Martin-Luft** [comment]
~~You mean https://github.com/valor-software/ng2-bootstrap/issues/540 ?~~

**Comment by Ovidiu-S** [comment]
Thank you for the quick response, I updated the link to the bootstrap pills that I am referring to. They are available in bootstrap 3 and 4

**Comment by IlyaSurmay** [comment]
https://valor-software.com/ngx-bootstrap/#/tabs#tabs-Pills
