### ISSUE TITLE
Feature Request: Ability to style alert component

### ISSUE THREAD

**Issue by ctrl-brk** [valor-software/ngx-bootstrap#1114]
I use my own alert-sm style which I'd like to apply to alert component's internal div.

Thanks!

**Comment by valorkin** [comment]
@ctrl-brk easiest way is to inherit alert component and provide it with your template
and than reuse it

**Comment by pexi** [comment]
@valorkin this does not seem to be possible. I cannot override the template specified in alert component decorator.

**Comment by valorkin** [comment]
Added description to docs
