### ISSUE TITLE
1.1.14 webpack warnings

### ISSUE THREAD

**Issue by smnbbrv** [valor-software/ngx-bootstrap#1123]
Hi guys,

there are webpack warnings

> ./~/ng2-bootstrap/bundles/ng2-bootstrap.umd.js
> Critical dependencies:
> 1:3743-3750 require function is used in a way in which dependencies cannot be statically extracted
> 1:3789-3796 require function is used in a way in which dependencies cannot be statically extracted
>  @ ./~/ng2-bootstrap/bundles/ng2-bootstrap.umd.js 1:3743-3750 1:3789-3796
> bundle.js:122 ./~/ng2-bootstrap/bundles/ng2-bootstrap.umd.min.js
> Critical dependencies:
> 1:3743-3750 require function is used in a way in which dependencies cannot be statically extracted
> 1:3789-3796 require function is used in a way in which dependencies cannot be statically extracted
>  @ ./~/ng2-bootstrap/bundles/ng2-bootstrap.umd.min.js 1:3743-3750 1:3789-3796

actually happens after update to 1.1.14

**Comment by valorkin** [comment]
not good, hm

**Comment by fattslug** [comment]
I'm getting this on Angular 2.1 with the latest version of ng2-bootstrap.
Any updates on possible causes?

**Comment by valorkin** [comment]
Don't use bundle with webpack! At least for now :)
Use ng2-bootstrap/ng2-bootstrap

**Comment by ghost** [comment]
Not using the bundle works.

**Comment by valorkin** [comment]
who is in slack and able to fast check beta version with another UMD file?

**Comment by szh** [comment]
Any news on this? The issue still exists on version 1.1.16.

**Comment by BigRomanov** [comment]
What does it mean "use ng2-bootstrap/ng2-bootstrap"? How do I do that?

**Comment by valorkin** [comment]
Follow up https://github.com/valor-software/ng2-bootstrap/pull/1223

**Comment by szh** [comment]
@BigRomanov instead of `import { ModuleName } from "ng2-bootstrap"`, use `import { ModuleName } from "ng2-bootstrap/ng2-bootstrap"`

**Comment by valorkin** [comment]
This issue happens to often, so in next version it will be just 'ng2-bootstrap'. No worries, old code will still be working, but will show deprecation warning

**Comment by ebakunin** [comment]
I may have found a new case of this bug. When I use `@ViewChild()` with timepicker via a local variable I get the webpack warning. When I do not use `@ViewChild()` no warning happens. I am importing from "ng2-bootstrap/ng2-bootstrap".

**Comment by ChristopherPope** [comment]
Hi, I am getting this error when using 
NG 2.1
NG2-BOOTSTRAP 1.1.16
WEBPACK 1.13.3

I am using the import format
import { ModuleName } from "ng2-bootstrap/ng2-bootstrap"

@valorkin what did you mean by:
Don't use bundle with webpack! At least for now :)

Is that the solution to this problem?


Thanks.
