### ISSUE TITLE
Change timepicker input to string?

### ISSUE THREAD

**Issue by damiandennis** [valor-software/ngx-bootstrap#1124]
Any chance of changing the ngModel input to a string, This makes the most sense since that is usually how it will translate from a database without any extra work. The problem I am faced with is linked below with Dates being generated in a getter causes the browser to crash.

https://github.com/angular/angular/issues/12288

**Comment by damiandennis** [comment]
found a workaround if I define a new Date() as a property in the class it avoids the problem.

**Comment by valorkin** [comment]
https://github.com/angular/angular/issues/3009

**Comment by valorkin** [comment]
ok, sounds reasonable
