### ISSUE TITLE
Increase rating stars size?

### ISSUE THREAD

**Issue by theunreal** [valor-software/ngx-bootstrap#1125]
Is it possible to increase the rating stars size of `RatingModule`?
The stars are really small and untouchable in touch screens.

**Comment by valorkin** [comment]
good idea

**Comment by valorkin** [comment]
at least provide a way to style them

**Comment by IlyaSurmay** [comment]
It's possible via css
```
.glyphicon.glyphicon-star, .glyphicon.glyphicon-star-empty {
    font-size: 50px;
}
```
