### ISSUE TITLE
What is the workflow to write and build a component for ng2-bootstrap?

### ISSUE THREAD

**Issue by amanwebdev** [valor-software/ngx-bootstrap#113]
I was planning to fix the error in date picker component and also new components. After doing the `npm install`, I tried `npm start`. Which resulted in the error: `missing script dev` ?  So, what are the steps to write, run and test a component?

**Comment by valorkin** [comment]
fixed, `npm start` now will work
but be careful minification is not working as expected,
known issue, trying to fix it now
