### ISSUE TITLE
feature request: beforeShowDay callback

### ISSUE THREAD

**Issue by cristianmtr** [valor-software/ngx-bootstrap#1134]
wondering how hard it would be to add a `beforeShowDay` callback, similar to the one in jQuery UI [here](https://api.jqueryui.com/datepicker/#option-beforeShowDay), or the one in this [JS datepicker](https://uxsolutions.github.io/bootstrap-datepicker/?markup=component&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=2&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&calendarWeeks=on&autoclose=on&todayHighlight=on&keyboardNavigation=on&forceParse=on&beforeShowDay=on&toggleActive=on#sandbox)

I would be willing to contribute to this, but I would appreciate some guidance

**Comment by valorkin** [comment]
please check new datepicker
available in v1.9.2
http://valor-software.com/ngx-bootstrap/#/datepicker

source code is easier to modify now
