### ISSUE TITLE
Cannot switch to Bootstrap 4 in angular2-meteor project

### ISSUE THREAD

**Issue by hongbo-miao** [valor-software/ngx-bootstrap#114]
Link to #109

@valorkin I already add `"typings/ng2-bootstrap.d.ts"` to `tsconfig.json`. So I am sure the path is correct. Because if I change to `ng2-bootstrap/ng2-bootstrap`, it will show: `Cannot find module 'ng2-bootstrap/ng2-bootstrap'.`

One problem is that Ng2BootstrapConfig and Ng2BootstrapTheme are not exported in the **ng2-bootstrap.d.ts** file.

(Sorry I don't have access to reopen that issue #109, so I just create a new one.)

**Comment by valorkin** [comment]
Can you share a peace of code you are working on as a repository ?

**Comment by hongbo-miao** [comment]
Sure, I created a clean one. It is here:
https://github.com/Hongbo-Miao/issue-ng2-bootstrap

The default is Bootstrap 3, right now the program runs well.
Need uncomment `import {Ng2BootstrapConfig, Ng2BootstrapTheme} from 'ng2-bootstrap';` in **client/app.ts**  and run again to see the error.

(Just type `meteor` in terminal to let it run)

**Comment by valorkin** [comment]
Thanks, I was not touching meteor last year:)  so it will be fun
