### ISSUE TITLE
Missing imports in examples

### ISSUE THREAD

**Issue by RoelRoel** [valor-software/ngx-bootstrap#1142]
All the examples that I try won't work because the imports are missing.
For example when I try the tabs example and I use the example code I get the error `'tab' is not a known element`

**Comment by valorkin** [comment]
Not possible, or to hard to have module per sample

**Comment by vernjensen** [comment]
It would be nice to have a complete demo somewhere. Right now I'm upgrading from Angular RC5 to a modern release, and am having errors. Seeing how to properly include the new version of ngx-bootstrap in a complete demo would be helpful.
