### ISSUE TITLE
Can't use Modal 

### ISSUE THREAD

**Issue by asnike** [valor-software/ngx-bootstrap#1143]
Hello, guys.
I used ng2-bootstrap module. I tried to open modal on my app. But, it occured error.
I try to find a solution. But there're no solution.
![image](https://cloud.githubusercontent.com/assets/661041/19546462/060e412e-96cb-11e6-95da-1283d26c4f46.png)

I followed the modal example in demo page exactly same. 
Please help

Sorry about my english

**Comment by hkb1990** [comment]
Did you import `{ ModalModule } from 'ng2-bootstrap/ng2-bootstrap';` and imports `ModalModule` to your modules?

``` js
...
import { ModalModule } from 'ng2-bootstrap/ng2-bootstrap';
import { App } from './app';
...

@NgModule({
  bootstrap: [App],
  declarations: [
  ],
  imports: [
    ...,
    ModalModule,
    ...
  ],
  providers: [
  ]
})
```

**Comment by asnike** [comment]
Yes, I did. Already import my app module.
I installed ng2-bootstrap by npm.

**Comment by hkb1990** [comment]
Maybe it's the same issue as #1027 .

**Comment by soupman99** [comment]
+1 Followed the instructions and still running into the error

**Comment by tonimaristelaestabillo** [comment]
Try     ModalModule.forRoot() instead of  ModalModule.
