### ISSUE TITLE
Angular Universal : this.document.body.removeChild is not a function

### ISSUE THREAD

**Issue by sroucheray** [valor-software/ngx-bootstrap#1145]
When using `modal.show()`, angular universal will throw on executing `this.document.body.removeChild` on this line :
https://github.com/valor-software/ng2-bootstrap/blob/369175700e11f31a59a234fcbfc4b1df3d91aaa5/components/modal/modal.component.ts#L339

**Comment by valorkin** [comment]
I am adding e2e over universal build, so I am expecting to cover all universal use cases soon

**Comment by paulogr** [comment]
Having exactly same problem here. 
Any workaround for this? @sroucheray @valorkin 
Thank you!

**Comment by IlyaSurmay** [comment]
Fixed in 2.0.0-beta.5
