### ISSUE TITLE
tooltipIsOpen doesn't work

### ISSUE THREAD

**Issue by tamasfoldi** [valor-software/ngx-bootstrap#1152]
I have a version 1.1.14 and if I use tooltip as in the code below I expect that tooltip to be always shown, but in my case it works as without the tooltipIsOpen attribute.
`<h2 [tooltip]="'Foo'" #tooltip="bs-tooltip" [tooltipIsOpen]="true" >Header 2</h2>`

Am I missing something or it is in a work-in-progress state?

**Comment by guzmo** [comment]
Same

**Comment by valorkin** [comment]
fixed a long time ago,
btw field renamed to `isOpen`
