### ISSUE TITLE
Popover component architecture discussion

### ISSUE THREAD

**Issue by DethAriel** [valor-software/ngx-bootstrap#1157]
I've started to implement the Popover component, and I even have it working already. Yet, the code appears to be in a far-from-ideal condition, and that's why I open this discussion.

The problems arise from the fact that `popover` and `tooltip` share a fair bit of common functionality.
There are multiple ways to make this work:
1. Reusability by inheritance: refactor `tooltip` a bit and inherit all `popover`-related code from respective `tooltip` pieces.
   - **Problem**: one would need to copy-paste the template, all `@Input()` / `@Output()` properties, and all implement methods with `@HostBinding()` decorators that would call respective `tooltip` methods.
2. Reusability by inheritance (extended): rename `@Input()` / `@Output()` properties to have a less tooltip-tied names (e.g. `tooltipIsOpen` => `bsIsOpen`). This only partially solves the problem from above while resulting in a breaking change.
3. Reusability by inclusion: extend `tooltip` to support `popover` component
   - **Problem**: obviously, `tooltip` users would have to wear the overhead of `popover` component, which is not great

These are the best 3 options that I see, with 2) being the best one, in my opinion.

@valorkin I believe you have some vision for that, too, and I would love to hear your feedback on that matter.

**Comment by valorkin** [comment]
yes, I have some ideas, but for some reason for me easier to write peace of code than explain in human text >.<
this is mine cons
but I will do

**Comment by valorkin** [comment]
Added
