### ISSUE TITLE
chore(deps): use typescript 1.8

### ISSUE THREAD

**Issue by binarious** [valor-software/ngx-bootstrap#116]
## **update**: blocked by https://github.com/angular/angular/issues/6468

When building my app with webpack I get:

```
ERROR in ./~/ng2-bootstrap/components/timepicker/timepicker.ts
(112,5): error TS7027: Unreachable code detected.
```

Seems legit, because there is an `if (true)` with a `return` and code after that:
https://github.com/valor-software/ng2-bootstrap/blob/802c64f65b42ca8f9b6d5a184f229c19934ecbb6/components/timepicker/timepicker.component.ts#L103

**Comment by valorkin** [comment]
You using ts 1.8 :)

**Comment by binarious** [comment]
Whoops possible. Is 1.8 not yet supported?

**Comment by valorkin** [comment]
Is it out of beta?

**Comment by valorkin** [comment]
I am really waiting for it, it may simplify system js bundling

**Comment by binarious** [comment]
No it's not out of beta: https://github.com/Microsoft/TypeScript/releases
Shall I leave this issue open? Since the problem will occur in the future.

**Comment by valorkin** [comment]
updated description to contain angular blocker issue https://github.com/angular/angular/issues/6468

**Comment by binarious** [comment]
fyi: blocker issue closed.

**Comment by valorkin** [comment]
Yeap, I know. But not available until Monday, in trip right now

**Comment by binarious** [comment]
All good. Have a nice trip ;-).

**Comment by valorkin** [comment]
Thanks, when I am back, I will be updating all the things :)
