### ISSUE TITLE
[Pagination] Expression has changed after it was checked

### ISSUE THREAD

**Issue by liucui0035** [valor-software/ngx-bootstrap#1167]
When I changed `ngModel` and  `itemsPerPage` at the same time, error is occurred

```
ORIGINAL EXCEPTION: 
Expression has changed after it was checked. Previous value: '1'. Current value: '6'.
```

**HTML**

``` html
<pagination class="pagination-sm" 
    [totalItems]="totalItems" 
    [itemsPerPage]="_option.paging.itemsPerPage" 
    [maxSize] = '_option.paging.maxSize'
    [boundaryLinks] = "true"
    [(ngModel)]="currentPage" 
    (pageChanged)="pageChanged($event)">    
</pagination>
```

**JS**

``` javascript
this._option.paging.itemsPerPage = 50;
this.currentPage = 1;
```

**Comment by chauey** [comment]
I am also having some issues when for example on page 7 and i delete an item making it go down to 6 pages.

**Comment by chintan3100** [comment]
I am also having same issue. Is any one found solution for that. ?.  This issue will come when we are on second page and total record is 20 and record/page=10.  Now if i change total record to 7. We will get issue.Expression has changed after it was checked. Previous value: '1'. Current value: '2'.

**Comment by valorkin** [comment]
this is issue is gone
starting v1.1.16-9
