### ISSUE TITLE
typeahead with scroll

### ISSUE THREAD

**Issue by arins** [valor-software/ngx-bootstrap#1168]
There is no possibility to have a long list with scroll with a typeahead component. You can add overflow-y:scroll to the ul element but that doesn't work when you use up/down arrow keys. I have made a fork and added two options two the typeahead.

typeaheadScrollable: boolean
typeaheadOptionsInScrollableView: number

if typeaheadScrollable is true the component container is scrollable and also reacts to key up/down keys.
You can also set number of items in the scrollable "view".

Is it possible to do a pull request on this when me and my colleague are done?

**Comment by rdettai** [comment]
+1

**Comment by arins** [comment]
yes I can look into it after this has been merged and when I have time. I agree it's a pretty important feature if you have a lot of items and can not fetch them in one go.

**Comment by joebri** [comment]
+1 for this feature. Is there an ETA?

**Comment by arins** [comment]
Yes I need this feature as well that's why I implemented it but it seems valor software don't have time to merge this. They have not been responding on this for a while so we went ahead and created a clone of there pacakge https://www.npmjs.com/package/symbrio-ng2-bootstrap which has the scroll. I try to update our package when they do updates and with the scroll. You can use that until they merged this.

**Comment by valorkin** [comment]
@arins finaly I got here

**Comment by valorkin** [comment]
@arins I am incredibly sorry, I was working with documentation >.<

**Comment by arins** [comment]
Hi! I can make a new pull request. Because I saw there was a lot of changes in the master branch. It might be eaiser if I just make a new pull request.

**Comment by valorkin** [comment]
@arins it would be very helpful
fork from development branch
I am merging into master only stable releases

**Comment by arins** [comment]
@valorkin ok

**Comment by BenElliottBV** [comment]
Hi both!

Don't suppose there's any progress on this at all? We could really use this feature!

**Comment by M1strall** [comment]
Yea, we are also very interested in this feature

**Comment by arins** [comment]
I have made a pull request so it's up to the repo owners to merge it. https://github.com/valor-software/ng2-bootstrap/pull/1543

**Comment by Ankushi** [comment]
Any further updates on this?

**Comment by M1strall** [comment]
Bump. Would be really great to support this.

**Comment by Argyos** [comment]
I need this with the intensity of thousand suns. Bump

**Comment by vikkivikrant** [comment]
@arins @valorkin It will be really helpful if we can add this feature.

**Comment by puneetratan** [comment]
try this

```
document.addEventListener("keydown", function (e) {
    document.getElementById(e.target.attributes['aria-activedescendant'].value).scrollIntoView(true)
});
```

**Comment by kamalSaiDd** [comment]
> document.addEventListener("keydown", function (e) {
>     document.getElementById(e.target.attributes['aria-activedescendant'].value).scrollIntoView(true)
> });

Wow it worked for me. You saved my day..

Just modified the following for angular 4+ (Make sure you add html tag (HTMLInputElement) as git hub is parsing out when i pasted the following code

document.addEventListener('keydown', (e) => {
      document.getElementById((<HTMLInputElement>e.target).attributes['aria-activedescendant'].value).scrollIntoView(true);
    });

**Comment by Chealer** [comment]
This feature is available (using the options mentioned by arins) in ngx-bootstrap 5.2.0 (and probably earlier).
