### ISSUE TITLE
I see only "Loading..." message.

### ISSUE THREAD

**Issue by SebastianPozoga** [valor-software/ngx-bootstrap#117]
http://valor-software.github.io/ng2-bootstrap/ doesn't work.

User:
I see only "Loading..." message.

Console error:
`Uncaught TypeError: m.values is not a function
24 Failed to update emulated device list. Error: Emulated device is missing required property 'page-rect'`

CHROME VERSION: 43.0.2357.124
OS VERSION: Linux: 3.16.0-39-generic
data_reduction_proxy: disabled

**Comment by valorkin** [comment]
It seems to be an angular issue, please check their issues list and is your browser version supported
And link it here later, thanks
