### ISSUE TITLE
Tooltip does not support other triggers than mouse over

### ISSUE THREAD

**Issue by roswah** [valor-software/ngx-bootstrap#1170]
Hi,

We need the to be able to send click event as trigger for tooltip since mouse over does not work so well in  
touch screens. In your documentation it says: "tooltipTrigger: (not implemented)". When are you planning to implement this? I think this is a very needed feature. Thanks in advance.

**Comment by musienkoyuriy** [comment]
Hi! I will send a pull request related to this changes soon.

**Comment by valorkin** [comment]
works fine now,
check triggers input in docs preview http://valorkin.github.io/ng2-bootstrap/#/
