### ISSUE TITLE
chore(typeahead): with http promise problems

### ISSUE THREAD

**Issue by fkowal** [valor-software/ngx-bootstrap#118]
hi i've got some weird behaviours when working with typeahead "ng2-bootstrap": "1.0.2-beta.0"

```
<input [(ngModel)]="parameterInput"
           [typeahead]="getParameters(getContext())"
           [typeaheadMinLength]="3"
           [typeaheadWaitMs]="300">
...
getParameters(context) {
        if (this._prevContext === context) {
            return this._cache;
        }
        this._prevContext = context;

       // this.parameterService.getParametersByName(): Observable<any>
        this._cache = () => this.parameterService.getParametersByName(this.parameterInput).toPromise();
        return this._cache;
    }
getContext() { return this; }
```
1. minlength is not respected at all
2. when i start to type 3 chars when the result of http is really long, so it takes longer to fetch
   when i get to 5 chars the results show, and the the result from the first promise (3 chars) kicks in and displays :(
   it also happens that when i type something in and tabout, when the fetching of data takes a longer, the list with typeahead hints pops up when i am already editing another field.
   The hint list doesn't go away unless i go back to typeahead and esc or do something else. :(

The UX is really bad when i compare with the http://angular-ui.github.io/bootstrap/#/typeahead i used before. None of these things happened before.

**Comment by valorkin** [comment]
Check this PR
https://github.com/valor-software/ng2-bootstrap/pull/99
UX should be `rx.Subject` based

**Comment by fkowal** [comment]
yes the PR look promising

http://blog.thoughtram.io/angular/2016/01/06/taking-advantage-of-observables-in-angular2.html
this works verynice
