### ISSUE TITLE
Component modals

### ISSUE THREAD

**Issue by dmlukichev** [valor-software/ngx-bootstrap#1181]
I have a couple of places in different components, where I open similar modal (for instance, 'settings')
Now I have to declare independent component that I insert everywhere, get access to it with `ViewChild` and proxy `show()` function to `bsModal` directive. But, imho, it's not best way to do this.

Is there a way to open component modals as we could in `ui-bootstrap`:
https://angular-ui.github.io/bootstrap/#/modal : $ctrl.openComponentModal section

**Comment by elynnaie** [comment]
This would be very nice indeed!

**Comment by valorkin** [comment]
work in progress

**Comment by jdev27** [comment]
+1

**Comment by AllSeeingEye** [comment]
+1
