### ISSUE TITLE
Modal not showing, because bootstrap renamed fade.in to fade.active

### ISSUE THREAD

**Issue by Gillardo** [valor-software/ngx-bootstrap#1190]
As the title says, i have downloaded the latest version of bootstrap 4 from the v4-dev branch along with the latest version of ng2-bootstrap and none of my modal windows are displaying.  After checking the elements, the modal window is there, but the fade.in css class has been removed from bootstrap and has been renamed to fade.active

.fade.in {
    opacity: 1;
}

CHANGED TO 

.fade.active {
    opacity: 1;
}

**Comment by valorkin** [comment]
Nice reason for small PR changing bs4 template

**Comment by Gillardo** [comment]
Happy to make the PR, but question.  Readme says that this should all work bs3 and bs4.  Is there anywhere that the user sets this, as to whether they are using bs3 or bs4, or do you just add the classes for both when applying css to elements?
