### ISSUE TITLE
ngc -p ./tsconfig.aot.json fail

### ISSUE THREAD

**Issue by alanhe421** [valor-software/ngx-bootstrap#1191]
> ngc -p ./tsconfig.aot.json

Error: Template parse errors:
Can't bind to 'totalItems' since it isn't a known property of 'pager'. ("
                        </option>
                    </select>
                    <pager [ERROR ->][totalItems]="totalItems" [(ngModel)]="currentPage"
                           (pageChanged)="pageCha"): LegislationIndexComponent@167:27

i can't understand why?

my package.json
` 
 "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/compiler-cli": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/platform-server": "2.1.2",
    "@angular/router": "3.1.2",
 "ng2-bootstrap": "1.1.16",
`

my tsconfig.aot.json
`
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": false,
    "sourceMap": false,
    "suppressImplicitAnyIndexErrors": true,
    "noEmitHelpers": true,
    "strictNullChecks": false,
    "rootDir": "./client",
    "outDir": "./dist",
    "lib": [
      "dom",
      "es6"
    ],
    "types": [
      "node"
    ],
    "typeRoots": [
      "./node_modules/@types"
    ]
  },
  "files": [
    "client/app/components/app.module.ts",
    "client/polyfills.browser.ts",
    "client/vendor.browser.ts",
    "client/custom-typings.d.ts"
  ],
  "exclude": [
    "node_modules",
    "dist"
  ],
  "angularCompilerOptions": {
    "genDir": "client/compiled",
    "skipMetadataEmit": true
  }
}
`

**Comment by alanhe421** [comment]
Code is not rigorous。
i run a test.
please commit fixed version quickly。
thanks

**Comment by valorkin** [comment]
You forgot to add pager module to your app module

**Comment by alanhe421** [comment]
you can have a try .
I create a sharedModule
pager module is  PaginationModule?
some code like below
`@NgModule({
    imports: [CommonModule, RouterModule, FormsModule,
        TranslateModule,
        NgbModule,
        ModalModule,
        TypeaheadModule,
        PaginationModule,
        AlertModule,
        TooltipModule,
    ],`

**Comment by valorkin** [comment]
try to use angular-cli

**Comment by valorkin** [comment]
@heqiang421 ok, I have found where this is issue is coming,
we have a blocker from angular2 https://github.com/angular/angular/issues/11606

**Comment by valorkin** [comment]
status update it will be fixed in next release, actually hacked until ng2 blocker issue not solved

**Comment by alanhe421** [comment]
next release?when?i am waiting.

**Comment by valorkin** [comment]
almost there https://github.com/valor-software/ng2-bootstrap/compare/eaba9cab9d64450063e1e18249ee3359badc89f4...development

**Comment by valorkin** [comment]
published in v1.1.16-9
docs preview http://valorkin.github.io/ng2-bootstrap/#/
