### ISSUE TITLE
button group disabled state not working

### ISSUE THREAD

**Issue by dicbrus** [valor-software/ngx-bootstrap#1202]
Is it possible to disable one (or few) buttons in button group?

I tried [disabled] - it is not working.

**Comment by stevefarwell** [comment]
prior to upgrading to Angular 2.1.2, ng2-bootstrap 1.1.16, [disabled]=condition worked for btnRadio.
I believe it was ng2-bootstrap 1.0.6.  

I have a test page with:
dropdownToggle: [disabled] functions as expected
btnRadio: [disabled] fails
btnCheckbox: [disabled] fails

with the checkbox and radio the attribute 'ng-reflect-disabled="true"' is added however the 'disabled' attribute is not added to the DOM tag (button, label, div)

In the dropdown-toggle directive I noticed it has @HostBinding('class.disabled') which is not in the button directives...

**Comment by stevefarwell** [comment]
ping

**Comment by SergeyKuryatnick** [comment]
Thanks, we'll look at this.

**Comment by stevefarwell** [comment]
any update on the fix?

**Comment by SergeyKuryatnick** [comment]
Waiting for merge :-|

**Comment by stevefarwell** [comment]
still waiting....

**Comment by ghost** [comment]
still.. waiting.

**Comment by danilomcb** [comment]
waiting....

**Comment by ptrzyna** [comment]
still waiting...this merge is taking forever apparently :)

**Comment by RobertBernstein** [comment]
Hi!  I'm running into the same issue.  Any idea when the code will be merged?

Thanks!
Rob

**Comment by vincentfierant** [comment]
+1, any updates on this?

**Comment by sudosandwich3** [comment]
Is there any updates to this issue? For anyone looking for a workaround, you might be able to do something like this:

```html
<ng-container *ngFor="let option of options">
  <button
    *ngIf="!someDisableCondition"
    [(ngModel)]="myModel"
    [btnRadio]="option.id"
  >
    {{ option.name }}
  </button>
  <button
    *ngIf="someDisableCondition"
    disabled
    [(ngModel)]="myModel"
    [btnRadio]="option.id"
  >
    {{ option.name }}
  </button>
</ng-container>
```

**Comment by IlyaSurmay** [comment]
Works on 2.0.0-rc.0 (https://stackblitz.com/edit/ngx-bootstrap-3aabbe?file=app/app.component.html), closing as works as expected.

**Comment by michael-x** [comment]
I don't think this is actually solved (for the OP and others):

Adding `disabled` does in fact disable the button, while `[disabled]="true"` (or applying any other expression that evaluates to `true`) does not, **visually**. The `click` event is suppressed, but the button still looks like it is enabled.

Apparently in this case setting the `disabled` property to true does not add the `disabled` attribute.

**Comment by brian15co** [comment]
Still an issue

**Comment by michael-x** [comment]
@SergeyKuryatnick @IlyaSurmay please see https://ngx-bootstrap-4am3wr.stackblitz.io
