### ISSUE TITLE
Typeahead: special characters lead to strange typeahead results

### ISSUE THREAD

**Issue by negberts** [valor-software/ngx-bootstrap#1205]
We have a list of water descriptions in our typeahead. The first time there is no problem and results are shown nicely. When we select our description like '999,8 kg/m3 8 °C' the next time the typeahead results open there are a lot of strange `<strong>` tags in the typeahead.  See pictures:

![image](https://cloud.githubusercontent.com/assets/20299260/19997392/8b3cf376-a266-11e6-8cc6-8e5ba4b17261.png)

![image](https://cloud.githubusercontent.com/assets/20299260/19997408/9ead1b52-a266-11e6-8f4c-5b41b81a3aa9.png)

**Comment by negberts** [comment]
There's a double space between m3 and 8 which gives the strange results. Removing the double space gives me no errors. Issue can be closed. (Or solved that two spaces don't lead to these strange results.)

**Comment by valorkin** [comment]
:)

**Comment by jestersimpps** [comment]
bump
