### ISSUE TITLE
Tooltip doesn't disappear after navigating away

### ISSUE THREAD

**Issue by sapiraz** [valor-software/ngx-bootstrap#1213]
When placing a tooltip on a link and navigating away from the page, the tooltip simply stays visible.

**Comment by SergeyKuryatnick** [comment]
@sapiraz 
Could you provide part of the code where you use it?

**Comment by sapiraz** [comment]
I'm really not doing much, simply using the directive.
`<div [tooltip]="'Simple text'">{{title}}</div>`
And just to make sure I'm clear, obviously it happens when navigating in-site.

**Comment by mpx200** [comment]
same happening to me, especially when i'm using [tooltipAppendToBody]="true"

**Comment by SergeyKuryatnick** [comment]
@sapiraz 
Could you make few things:
1. Add in your tooltip next attribute 
`<div [tooltip]="'Simple text'" (tooltipStateChanged)="tooltipStateChanged($event)">{{title}}</div>`
2. Add `console.log('destroyed');` after string 109 in the file `components/tooltip/tooltip.directive.ts`
3. Start your code and look at console when you will navigate away from the page
In console should be:

> Tooltip is open: true
> destroyed
> Tooltip is open: false

All commands are displayed?

**Comment by Shadowlauch** [comment]
I have the exact same problem. And I can also confirm that this problem only seem to happen when the tooltip is appended to the body.

**Comment by BenDevelopment** [comment]
It's not only happening after navigating away. It's happening when the parent is removed.

**Comment by valorkin** [comment]
can not reproduce in ngx-bootsrtap v1.7.1
