### ISSUE TITLE
[BUG] package.json github dependency

### ISSUE THREAD

**Issue by DanielKucal** [valor-software/ngx-bootstrap#1216]
When I want to define my npm dependency in package.json, for example like:

    "dependencies": {
        "ng2-bootstrap": "git+https://github.com/valor-software/ng2-bootstrap#development"
    }

Then the module comes without any sources since .ts files are npm-ignored and the build isn't run in `prepublish` script (it's executed only when getting the module via npm).
Because of this bug it's impossible to use other branch or even fork of this repository, please fix it as soon as possible. Thanks in advance.

**Comment by valorkin** [comment]
Hey, I can't do this. All .ts based projects has an issue like this, because if I will include .ts it will break npm users flow.
I am planning to make nightly builds who need latest changes fast
