### ISSUE TITLE
dropdownToggle directive stops and prevents click events

### ISSUE THREAD

**Issue by milichev** [valor-software/ngx-bootstrap#1217]
We need to catch click events on the document level, but `dropdownToggle` directive has hardcoded `stopPropagation` and `return false` (which leads to `preventDefault`) in its click handler. Can it be changed? Either remove both or move to `if` with a property like so:

```TypeScript
  @Input() public suppressClick:boolean = true;
  
  @HostListener('click', ['$event'])
  public toggleDropdown(event:MouseEvent):boolean {
    if (this.suppressClick) {
      event.stopPropagation();
    }

    if (!this.isDisabled) {
      this.dropdown.toggle();
    }

    return !this.suppressClick;
  }
```

**Comment by valorkin** [comment]
Hm, this is how it is in twitter bootstrap. But we can make it configurable

**Comment by H--o-l** [comment]
Same issue here, related to line:
https://github.com/valor-software/ngx-bootstrap/blob/development/src/dropdown/bs-dropdown-toggle.directive.ts#L44

I think the issue can be reopen :-)

**Comment by valorkin** [comment]
@H--o-l need to remove it on one side, and have controversial requirements to keep it :(

**Comment by H--o-l** [comment]
@valorkin thanks for the quick answer !
In the meantime I opened the PR #2964 on the subject. Let me know what you think about it and if it's possible to merged it.
If it's not possible I will find another way but I think the option doesn't hurt. You let me know !
