### ISSUE TITLE
Typeahead dropdown appears, then immediately disappears

### ISSUE THREAD

**Issue by OriginalMoscato** [valor-software/ngx-bootstrap#1219]
This is a weird situation.  I have an event listener attached to my typeahead in a parent component.  The typeahead uses an Observable to fetch an array of Objects.  I have `typeaheadAsync` set to "true", using `typeaheadLoading` to create the Observable and populate the model [dropdown] (I'm not sure if I'm doing this right).  So each time I type something into the typeahead, an Observable is created, which then fetches the array of Objects and populates the model.  

There is a bootstrap "wait" modal that is running on top of all this when the Observable is doing its thing.  The modal runs for the entirety of the event listener's life.  I can see the typeahead dropdown briefly appear beneath the modal, but then disappears after less than a second.  This doesn't occur for every string that I type; sometimes the typeahead works as expected.  

Perhaps it's not cooperating with the modal?  Maybe I should have a callback somewhere or implement the Observable differently?

**Comment by valorkin** [comment]
can you create a plunker to reproduce?
you can use sample one from readme to start

**Comment by valorkin** [comment]
it disappears if looses focus

**Comment by CodeSpeak11** [comment]
I'm seeing the same behavior, following the example exactly as shown at https://www.npmjs.com/package/ng2-bootstrap-modal
Trying to figure out the syntax for the option "autoCloseTimeout" which I'd like to set to one minute or something to workaround this issue. Anyone else have a better solution? 
    
    import { Component } from '@angular/core';
    import { DialogComponent, DialogService } from "ng2-bootstrap-modal";
    export interface ConfirmModel {
        title: string;
        message: string;
    }
    @Component({
        selector: 'confirm',
        template: `<div class="modal-dialog">
                    <div class="modal-content">
                       <div class="modal-header">
                         <button type="button" class="close" (click)="close()" >&times;</button>
                         <h4 class="modal-title">{{title || 'Confirm'}}</h4>
                       </div>
                       <div class="modal-body">
                         <p>{{message || 'Are you sure?'}}</p>
                       </div>
                       <div class="modal-footer">
                         <button type="button" class="btn btn-primary" (click)="confirm()">OK</button>
                         <button type="button" class="btn btn-default" (click)="close()" >Cancel</button>
                       </div>
                     </div>
                  </div>`
    })
    export class ConfirmComponent extends DialogComponent<ConfirmModel, boolean> implements ConfirmModel {
        title: string;
        message: string;
        constructor(dialogService: DialogService) {
            super(dialogService);
        }
        confirm() {
            // we set dialog result as true on click on confirm button, 
            // then we can get dialog result from caller code 
            this.result = true;
            this.close();
        }
    }

**Comment by CodisRedding** [comment]
Found that if you set the typeaheadAsync option to false it still works as intended with async http and the dropdown shows as it should
