### ISSUE TITLE
moment.js system.js loader and datepicker doesn't run. Why?

### ISSUE THREAD

**Issue by j-nord** [valor-software/ngx-bootstrap#1220]
We get follow error:

Error loading http://localhost:59101/moment as "moment" from http://localhost:59101/node_modules/ng2-bootstrap/components/datepicker/date-formatter.js

package.json:
{
  "version": "1.0.0",
  "name": "asp.net",
  "private": true,
  "scripts": {
    "postinstall": "typings install",
    "typings": "typings"
  },
  "dependencies": {
    "@angular/common": "2.1.0",
    "@angular/compiler": "2.1.0",
    "@angular/core": "2.1.0",
    "@angular/forms": "2.1.0",
    "@angular/http": "2.1.0",
    "@angular/platform-browser": "2.1.0",
    "@angular/platform-browser-dynamic": "2.1.0",
    "@angular/router": "3.1.0",
    "@angular/upgrade": "2.1.0",
    "alertifyjs": "^1.8.0",
    "angular2-in-memory-web-api": "0.0.20",
    "core-js": "^2.4.1",
    "ng2-bootstrap": "1.1.14",
    "ng2-modal": "0.0.22",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "simple-line-icons": "2.4.1",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25"
  },
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-clean": "^0.3.2",
    "gulp-concat": "^2.6.0",
    "gulp-cssmin": "0.1.7",
    "gulp-typescript": "^2.13.6",
    "gulp-uglify": "2.0.0",
    "path": "^0.12.7",
    "typescript": "^2.0.3",
    "typings": "^1.3.2"
  }
}

We have tried everything. We have stackoverflow through.

It does not work like that!

Try all System.config.js commands.

Finally,
 'Moment': 'node_modules/ng2-bootstrap/node_modules/moment'

and
'Moment': {main: 'moment.js', defaultExtension: 'js'},

Also on the Internet have all already tried. But there was something wrong programmed. Because nothing works.

What's wrong.

**Comment by valorkin** [comment]
why not read readme first?
it contains link to: https://github.com/valor-software/angular2-quickstart/blob/master/systemjs.config.js#L8

**Comment by j-nord** [comment]
The wrong answer!

why not read readme first?  <- Did not work, because you have in Version 1.14 an error !!!! ( the directory for Moment is wrong!) 

The solution:
Update to Version 1.16 and then you must delete the complete node-modules and restore it again!

Then you can use the standard moment path and use it in other Code!

**Comment by valorkin** [comment]
So it worked, but you still unhappy about it? :)

**Comment by j-nord** [comment]
i love tested code :-)

**Comment by valorkin** [comment]
Me too, docs and test is a top priority now
