### ISSUE TITLE
feature: accordion panel styling

### ISSUE THREAD

**Issue by figuerres** [valor-software/ngx-bootstrap#1221]
I have had a lot of difficulty with customizing the look of the accordion.
on thing that I think should be changed is the class name defaults
while the bootstrap classes a are good to use  there can be cases where it would be better to have a local css with a new set of class names.
for example a "css class prefix"
so that I could copy the bootstrap classes and tweak them we a company name like
.acme-panel-default
.acme-panel-warn
and so on.....

also I am not sure why but when I have a css file local to my component folder that should override bootstrap is did not work.
I am sure there is a reason but I was not bale to find it.

classes that were not related to the bootstrap panels worked.
ones that were .panel were not seen by chrome at all!

**Comment by valorkin** [comment]
I have a template for tutorial of how to style elements... but it will be added later
in two words: inherit component you need and replace template
than copy paste corresponding module and use your version of component
it will allow you to use any styles

**Comment by valorkin** [comment]
will be added to documentation

**Comment by codedoge** [comment]
I'm having a lot of troubles custom styling some components like panels and modals with component based css files. These seems to be ignored for ng2-bootstrap components. Is there a solution to this?
What do you mean by "inherit component you need and replace template"?

**Comment by Flood** [comment]
Would be great if there was a possibility to not add all panel/card classes. I've used version 1.1.5 before, and now updating to 1.3.2 these classes was added and my layout is broken.

**Comment by valorkin** [comment]
css `:host` selector, or more heavy css selectors should help
