### ISSUE TITLE
moment security upgrade

### ISSUE THREAD

**Issue by tamascsaba** [valor-software/ngx-bootstrap#1231]
Medium severity vulnerability found on moment@2.15.1
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:moment:20161019
- from: ng2-bootstrap@1.1.11 > moment@2.15.1

**Comment by valorkin** [comment]
ok! added to the list https://github.com/valor-software/ng2-bootstrap/pull/1223

**Comment by tamascsaba** [comment]
thx :+1:

**Comment by valorkin** [comment]
done starting v1.1.16-9
