### ISSUE TITLE
Carousel becomes hidden if I remove first element

### ISSUE THREAD

**Issue by Invizible** [valor-software/ngx-bootstrap#1233]
I have such a template

```
<carousel>
    <slide *ngFor="let image of images">
      <img [src]="image.base64">
    </slide>
  </carousel>
```

and when I remove the first element from the array carousel becomes hidden

**Comment by SergeyKuryatnick** [comment]
Duplicated https://github.com/valor-software/ng2-bootstrap/issues/1017
