### ISSUE TITLE
Datepicker - Today's color

### ISSUE THREAD

**Issue by andershagebakken** [valor-software/ngx-bootstrap#1246]
Hi. Is there anyway to set today's color in the Datepicker module? When today is not selected, the text has the same color as the background color of the Datepicker. Thanks

**Comment by aidemsined** [comment]
additionally use if classes
```css 
.btn-info
``` 
and 
```css 
.active
``` 
are inconsistent

**Comment by valorkin** [comment]
theming and replacing day rendering templates will be released next week

new datepicker (new style and pop up version)
available in v1.9.0+
check this out: http://valor-software.com/ngx-bootstrap/#/datepicker#examples

**Comment by dave0688** [comment]
I still haven't seen it (another day layout in datepicker, or at least a class appended to todays' grid cell) in the current version (2.0.3). What's the status with the feature?
