### ISSUE TITLE
How can I customize the style of Datepicker

### ISSUE THREAD

**Issue by helloljq** [valor-software/ngx-bootstrap#1249]
I would like to change some borders, colors and other styles, but do not know how to do

**Comment by GuskiS** [comment]
Just look at the DOM and write up your own CSS.

**Comment by SergeyKuryatnick** [comment]
@helloljq is issue solved for you?

**Comment by linusbrolin** [comment]
There really should be @Input() variables for the classes used.
For example, what if I don't want to use btn-sm for the buttons?

The same thing should be done for the Timepicker, where it currently uses regular size of both buttons and formcontrols.
What if I want to use form-control-sm?

**Comment by rodrigoreal** [comment]
Does anyone had success with that?
I'm trying even with `:host /deep/`, but no success :(

**Comment by rodrigoreal** [comment]
Ok, adding the `daypicker` after the `/deep/` works.
```
:host /deep/ daypicker {
    table {
        background: white;
    }
}
```

**Comment by valorkin** [comment]
now you can fully customize css ;)
new datepicker (new style and pop up version)
available in v1.9.0+
check this out: http://valor-software.com/ngx-bootstrap/#/datepicker#examples

**Comment by chanakyanet** [comment]
is there a way to use 

containerClass: '#336699'

can I add a different blue color to datepicker not the defaults, default themes are not close to match my layout perfectly.

**Comment by valorkin** [comment]
Check how custom themes implemented datepicker css, and do your own

**Comment by mirellyssl** [comment]
Hello, to customize the datepicker component, add to your css:
:: ng-deep (Whenever to customize the component start with this) and then start a class, for example:
:: ng-deep.bs-datepicker-body {
Width: 130%! important;
}
