### ISSUE TITLE
Timepicker Doesn't have any validation

### ISSUE THREAD

**Issue by harilalinapp** [valor-software/ngx-bootstrap#1253]
There is no validation in timepicker. Is it possible to return an null value if the validation fails?
That would be great.

**Comment by valorkin** [comment]
if it will return null, you will not be able to use custom validation outside of timepicker
but there are a cases when it should return null

**Comment by artdias90** [comment]
Right now it returns the most recent valid value (or undefined), which is not the best. Only assigns a css-invalid class to input but that's not useful for form validation if you have webworkers and therefore no easy way into DOM

**Comment by valorkin** [comment]
Is there are any standards for this behavior?

**Comment by artdias90** [comment]
I think together with setting `has-error` class, it should carry an Output()
e.g  `<timepicker (hasError)=""></timepicker>`  so we are free to decide how to take actions if an invalid hour or minute is set.
