### ISSUE TITLE
chore(datepicker): support null value

### ISSUE THREAD

**Issue by valorkin** [valor-software/ngx-bootstrap#126]
actually: currently as a hack, when ng-model equals null selected date set to `now`
expected: but date should be unselected

**Comment by NandanPhadke** [comment]
Is there an update on this. Would it be possible to have a initially empty/null date?

**Comment by valorkin** [comment]
yeap, datepicker popups and refactoring is next prio
just after documents restyling :)
http://betrozov.github.io/ng2-bootstrap/#/datepicker

**Comment by anil-kk** [comment]
@valorkin is there any progress with this issue? sometimes people need to have value null for date
