### ISSUE TITLE
docs(tabs): focus at specific tabs in form with HTML5 required fields

### ISSUE THREAD

**Issue by fxcosta** [valor-software/ngx-bootstrap#1260]
If a user is on the second tab and there are empty mandatory fields on the first tab and if he clicks in submit there is no feedback on the required fields in the first tab. How to implement this detection and change of tab? Thx!!

**Comment by valorkin** [comment]
I got your idea, it will be pretty common situation
I will try to add it to documentation

**Comment by IlyaSurmay** [comment]
This looks like a part of #1502
