### ISSUE TITLE
Extend Datepicker

### ISSUE THREAD

**Issue by AlexKhymenko** [valor-software/ngx-bootstrap#1262]
When you try to extend datepicker v.1.1.16 it will throw an error.

export class SomeName extends DatepickerComponent{}

**Comment by valorkin** [comment]
unfortunately this will not work with AoT at the moment
blocked by ng2 issue https://github.com/angular/angular/issues/11606

without AoT it could work,
but you need to provide more details about this issue

FYI we are planning to provide tutorial how to extend and customize components

**Comment by valorkin** [comment]
should work in ng v4+

**Comment by horsebuzz** [comment]
Is this working now?

Any tutorial on how to extend component or customise template?
