### ISSUE TITLE
Tabs - Remember clicked tab

### ISSUE THREAD

**Issue by guzmo** [valor-software/ngx-bootstrap#1268]
When we specify a tabset to work in and then go back to previous page and fourth we will come to the first tabset again. These tabs shouldn't remember which tabset was last used by using the url? If I remember correct it did in Angular 1.

Cheers

**Comment by IlyaSurmay** [comment]
> These tabs shouldn't remember which tabset was last used by using the url?

Nope, we don't mess with url and hashes. This kind of functionality should be implemented in app itself.
