### ISSUE TITLE
Timepicker's invalidHours/invalidMinutes does not apply to inputs

### ISSUE THREAD

**Issue by ebakunin** [valor-software/ngx-bootstrap#1271]
In timepicker, an invalid value is marked in the surrounding `<td>` elements. However, the input still remains `.ng-valid`.

For example, add a minimum value to a timepicker. Type a value in the hour field that is before the minimum time (do not use the arrow icons). `this.invalidHours` will be set to true and `.has-error` will be applied to the surrounding `<td>`. However, `ngClassValid` will remain true.

Can this be fixed? Thanks.

**Comment by valorkin** [comment]
need to add hack in with ngModelValidation

**Comment by valorkin** [comment]
unfortunately, I don't see a way for changing validation status inside of timepicker
so we will provide custom validation demo
