### ISSUE TITLE
ng2-bootstrap.js 404 Not Found after upgrade from 1.1.13 to 1.1.16

### ISSUE THREAD

**Issue by toni-moreno** [valor-software/ngx-bootstrap#1277]
This is the error my web server is logging.
```
2016-11-30 00:31:26: Completed /node_modules/ng2-bootstrap/bundles/ng2-bootstrap.js 404 Not Found in 223.737µs
```
and these are the changes made in package.json
```
-    "ng2-bootstrap": "1.1.13",
+    "ng2-bootstrap": "1.1.16",
```

And these the changes in systemjs.config.js ( as suggested in https://github.com/valor-software/angular2-quickstart) 

```
-      'ng2-bootstrap': 'npm:ng2-bootstrap/ng2-bootstrap.js',
+      'ng2-bootstrap/ng2-bootstrap': 'npm:ng2-bootstrap/bundles/ng2-bootstrap.umd.js',
```

There is any other thing to do  before trying again ?

**Comment by toni-moreno** [comment]
Sorry I notice that i had harcoded on index.html the script load.

 <script src="node_modules/ng2-bootstrap/bundles/ng2-bootstrap.js"></script>

**Comment by toni-moreno** [comment]
After deleted that line the app is trying to load with error 404 Not Found, the following URL
```
http://localhost:8090/ng2-bootstrap/components/modal/modal.component 
```

The component exist and its real path is
```
http://localhost:8090/ng2-bootstrap/node_modules/components/modal/modal.component 
```
Is like systemjs ignores the "npm:" prefix in the following  systemjs.config.js configuration item
```
ng2-bootstrap/ng2-bootstrap': 'npm:ng2-bootstrap/bundles/ng2-bootstrap.umd.js',
```

**Comment by XidongHuang** [comment]
Hi, toni.
I try to follow the  https://github.com/valor-software/angular2-quickstart too, but I don't see "**bundles**" folder or "**ng2-bootstrap.umd.js**" under "**ng2-bootstrap**", and I am using the 1.1.16, so how did you configure the "systemjs.config.js file"??

fixed:
Hey man, I found "**bundles**" folder, the reason is that I used "**bower**" to download ng2-bootstrap at the beginning. Maybe it doesn't support "bower" now, and I re-download it by npm, now I can find it!

**Comment by valorkin** [comment]
@XidongHuang it doesn't support bower
`ng2-bootstrap/components/modal/modal.component`
@toni-moreno please show me how do you import ModalComponent?
you should import it from `ng2-bootstrap/ng2-bootstrap`

**Comment by toni-moreno** [comment]
Hi  @valorkin  with 1.1.13 we have this config (rigth now)

https://github.com/toni-moreno/snmpcollector/blob/master/package.json
https://github.com/toni-moreno/snmpcollector/blob/master/public/systemjs.config.js

and a hardcoded javascript load in index.html as you can see in:

https://github.com/toni-moreno/snmpcollector/blob/master/public/index.html#L20

And here the imports.

https://github.com/toni-moreno/snmpcollector/blob/master/public/main.module.ts#L31-L34

When trying to update to 1.1.16 i have replaced in systemjs.config.js
```
'ng2-bootstrap': 'npm:ng2-bootstrap/ng2-bootstrap.js',
```
with 
```
'ng2-bootstrap/ng2-bootstrap': 'npm:ng2-bootstrap/bundles/ng2-bootstrap.umd.js',
 ```

and removed the <script src=XXX ></script> in index.html. 

I have maintained the imports exactly as I had in 1.1.13 version.

https://github.com/toni-moreno/snmpcollector/blob/master/public/main.module.ts#L31-L35

it compiles ok with tsc but crashes on load with "Not Found 404" in 
```
http://localhost:8090/ng2-bootstrap/components/modal/modal.component 
```

as I told you before the "moda.component.js" script  exist at
```
http://localhost:8090/node_modules/ng2-bootstrap/components/modal/modal.component 
```

The correct path has "/node_modules/" as prefix but I it can not load with the suggested config in https://github.com/valor-software/angular2-quickstart.

Can you help us please?

Thank you very much

**Comment by valorkin** [comment]
Problem with system.js, that it doesn't see separate filed, but you already knew it :)
  ..

**Comment by toni-moreno** [comment]
Sorry. I did know nothing, I'm a  angular beginner . Indeed I had configured 1.1.13 some months ago and I did testing a lot of configurations until it was working.

So , I can not understand where is the error? perhaps in my configuration ? in systemjs lib? or in ng2-bootstrap ? .

Can you clarify me please?

**Comment by valorkin** [comment]
If application is small, please please please,switch to angular-cli. An forget about such issues

**Comment by toni-moreno** [comment]
Yes. 
The main motivation of the upgrade is move to a AoT compilation with rollup.js . (https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) When trying to add the  the compiler cli last version 2.2.3  (the npm dependencies ask me to upgrade the ng2-boostrap)  and I did.

My first goal now is the update... and after I will move to the new AoT.

this is now my  new package.json while trying to upgrade angular2 and ng2-bootstrap

````
"dependencies": {
    "@angular/common": "~2.2.3",
    "@angular/compiler": "~2.2.3",
    "@angular/compiler-cli": "~2.2.3",
    "@angular/core": "~2.2.3",
    "@angular/forms": "~2.2.3",
    "@angular/http": "~2.2.3",
    "@angular/platform-browser": "~2.2.3",
    "@angular/platform-browser-dynamic": "~2.2.3",
    "@angular/platform-server": "^2.2.3",
    "@angular/router": "^3.0.1",
    "@angular/upgrade": "~2.2.3",
    "angular-in-memory-web-api": "~0.1.1",
    "bootstrap": "^3.3.7",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.35.0",
    "file-saver": "^1.3.3",
    "jquery": "^2.2.3",
    "lodash": "^4.11.1",
    "moment": "^2.13.0",
    "ng2-bootstrap": "1.1.16",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.31",
    "zone.js": "^0.6.25"
  },
````
There is any way to test if new angular2/ng2-bootstrap is running ok on our package?

**Comment by toni-moreno** [comment]
Hi @valorkin When trying to update angular with ng2-bootstrap 1.1.13 we first have this npm warn.

```
developer@snmpcoldev01:~/src/gospace/src/github.com/toni-moreno/snmpcollector$ npm install

> snmpcollector@0.5.5 postinstall /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector
> typings install

typings WARN deprecated 2016-10-15: "registry:npm/lodash#4.0.0+20160416211519" is deprecated (updated, replaced or removed)

├── lodash@4.0.0
├── es6-shim (global)
├── filesaver (global)
└── jasmine (global)

snmpcollector@0.5.5 /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector
+-- UNMET PEER DEPENDENCY @angular/common@2.2.3
+-- UNMET PEER DEPENDENCY @angular/compiler@2.2.3
+-- UNMET PEER DEPENDENCY @angular/core@2.2.3
+-- UNMET PEER DEPENDENCY @angular/forms@2.2.3
`-- ng2-bootstrap@1.1.13 

```

And after this error when trying to open a modal box.

````
core.umd.js:2843 Error: ApplicationRef instance not found
    at ComponentsHelper.getRootViewContainerRef (components-helper.service.js:59)
    at ComponentsHelper.appendNextToRoot (components-helper.service.js:94)
    at ModalDirective.showBackdrop (modal.component.js:183)
    at ModalDirective.show (modal.component.js:102)
    at GenericModal.parseObject (generic-modal.ts:71)
    at MeasGroupCfgComponent.viewItem (measgroupcfg.component.ts:179)
    at DebugAppView.View_MeasGroupCfgComponent1.handleEvent_20 (/AppModule/MeasGroupCfgComponent/component.ngfactory.js:476)
    at DebugAppView.eval (core.umd.js:9474)
    at SafeSubscriber.schedulerFn [as _next] (core.umd.js:5733)
    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:238)ErrorHandler.handleError @ core.umd.js:2843ngZone.onError.subscribe.next @ core.umd.js:6423schedulerFn @ core.umd.js:5721SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238SafeSubscriber.next @ Subscriber.ts:190Subscriber._next @ Subscriber.ts:135Subscriber.next @ Subscriber.ts:95Subject.next @ Subject.ts:61EventEmitter.emit @ core.umd.js:5713NgZone.triggerError @ core.umd.js:6017inner.inner.fork.onHandleError @ core.umd.js:5996ZoneDelegate.handleError @ zone.js:236Zone.runTask @ zone.js:157ZoneTask.invoke @ zone.js:335
core.umd.js:2846 ERROR CONTEXT:
````
It seems like upgrade to 1.1.16 is needed to upgrade angular from 2.0.1 to 2.2.3 isn't it?

If there is not any other way to upgrade. there is some good document to switch to angular-cli from npm + systemjs ?

**Comment by valorkin** [comment]
1. try to use 1.1.16-8
2. it will fix issue with AppRef not found
3. to migrate app to angular-cli, just create new app in new folder
```
ng new my-app
cd my-app
ng serve
```
4. play with it ;)
5. move to it module per module

or get in touch in slack with me

**Comment by valorkin** [comment]
if you have any other questions please join slack: https://ngx-slack.herokuapp.com/
