### ISSUE TITLE
rename lib

### ISSUE THREAD

**Issue by elvisbegovic** [valor-software/ngx-bootstrap#1280]
Since Angular use semver, **ng2-** prefix's anti pattern, might be:
- vs-bootstrap
- valor-bootstrap

**Comment by valorkin** [comment]
in my opinion, company name in lib name is inappropriate.
so it could be ng-bootstrap (and produce complete mess)
or @ng/bootstrap or @ngx/bootstrap

**Comment by valorkin** [comment]
@istiti what about ngx- prefix?

**Comment by critchie** [comment]
I found [this](https://github.com/angular/angular/issues/1598). A prefix is definitely needed if anything just to mark your territory so to speak. Helps me easily identify which library a component belongs too.  Using ngx- doesn't feel right because it is random and has no connection back to Valor Software. I'd have no problem with valor-. Or ngv- maybe?

Also don't miss [this](http://angularjs.blogspot.com/2016/12/ok-let-me-explain-its-going-to-be.html?m=1&utm_campaign=NG-Newsletter&utm_medium=email&utm_source=NG-Newsletter_179).

**Comment by valorkin** [comment]
ngx- is an initiative by @ocombe and @amcdnl
as a common name space for angular 2+ libs

**Comment by critchie** [comment]
So what will Valor Software use for the ng2-charts library? @amcdnl already has a ngx-charts.

I liken these Angular namespaces to how Java uses the reverse domain name for their name spacing. Like com.valorsoftware.ng.bootstrap for example. They are guaranteed unique in the Java world where in Angular... not so much; but at least we are trying. This is why I like @istiti's valor- suggestion.

Having a common ngx- prefix doesn't solve anything IMO. Unless what you put in it is truly common, like reusable pipes or something.

(I'm using ng2-charts. Very nice work and the library is simple to use. The other chart libraries didn't have what I needed.)

**Comment by amcdnl** [comment]
I'd go for `ngx-bootstrap`.

@critchie - This isn't Java so I don't think we should emulate that pattern. Also in JavaScript, name lengths are KB's sent to the browser, so shorter is better.

If scoping is an issue, I'd do `@valor-software\ngx-bootstrap` in npm.

**Comment by elvisbegovic** [comment]
I agree with @critchie

**Comment by ocombe** [comment]
Like @amcdnl said, the name on npm is irrelevant, you can use a scoped module.
And the collisions in the code are probably not a real problem either because if two libraries have the same name then they probably do something similar and you won't use both at the same time.

**Comment by ocombe** [comment]
yes, if the library is modularized you should not have name collisions.
You can always rename services, I wish you could rename directives / pipes selectors as well... it's a design flaw in my opinion.

Anyway exported modules are usually just for convenience, you can import just a small component from a library if you need (you'll have to be careful about its dependencies though)

**Comment by valorkin** [comment]
bs* prefix for modules and directives and components and ngx-* prefix for libs,
ok?

**Comment by ocombe** [comment]
sounds good to me

**Comment by Martin-Luft** [comment]
Google wants that we all use the word "Angular" instead of "AngularJS", "Angular 2", "ng2", "Angular 4" or "ng4". So why not **angular-bootstrap**?

**Comment by valorkin** [comment]
done, renamed to ngx-bootstrap

**Comment by elvisbegovic** [comment]
good news :)  too much time to decide, name not so important

> wonder if google succeeded with "google" name

**Comment by valorkin** [comment]
@istiti problems was not with decision, ngx-bootstrap npm name was busy
so I had to go through npm dispute process

**Comment by dev054** [comment]
> bs* prefix for modules and directives and components and ngx-* prefix for libs,
ok?

What happened to the above comment? I can see a lot of selectors not being prefixed. cc @valorkin
