### ISSUE TITLE
Compatible version with Angular 2.2.0 or 2.4.0

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#1282]
Hi,
Which version of ng2-bootstrap is compatible with Angular 2.2.0 or 2.2.4

I tried 1.1.16 with Angular 2.2.0 but I was getting error that "ng2-bootstrap.min.js is not available."

Thanks 
Sanat

**Comment by valorkin** [comment]
wrong name https://unpkg.com/ng2-bootstrap@1.1.16/bundles/

**Comment by valorkin** [comment]
BTW we actively working on new version of component help to be 
compatible with 2.0.0 up to 2.3.0

**Comment by 408796571** [comment]
@valorkin Any hint on when the compatible with 2.3.0 will be released?

**Comment by valorkin** [comment]
New dynamic components injection service and reactive forms support planned for next week

**Comment by lucienimmink** [comment]
bump

**Comment by valorkin** [comment]
I will add 👍 to bump, what if it really works :)

**Comment by valorkin** [comment]
progress track is here: https://github.com/valor-software/ng2-bootstrap/pull/1328

**Comment by valorkin** [comment]
unfortunately breaking changes unavoidable

**Comment by valorkin** [comment]
BTW, give a try to https://unpkg.com/ng2-bootstrap@1.1.16-4/
v1.1.16-4
please, pay attention there are `.forRoot()` now on each module

**Comment by valorkin** [comment]
Please check v1.1.16-7, it is confirmed to work fine

**Comment by valorkin** [comment]
Docs preview available here http://valorkin.github.io/ng2-bootstrap/#/
