### ISSUE TITLE
Pagination is broken in 1.1.16 since 02/12/2016

### ISSUE THREAD

**Issue by Scipionh** [valor-software/ngx-bootstrap#1285]
Hey the pagination doesn't work anymore with your latest 1.1.16 version since you pushed your latest commits, I had to rolleback my prod app to 1.1.15 to have it working. Can you please fix this and be careful when updating the master version.

**Comment by gleibfried** [comment]
Same bug here... :-1:

**Comment by valorkin** [comment]
@Scipionh works here: http://valor-software.com/ng2-bootstrap/#/pagination
so provide more details please

**Comment by Scipionh** [comment]
Here is the error I had this morning, without changing anything else in my code: 

```
 Template parse errors:
More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: PagerComponent,PaginationComponent
```

The error doesn't happen when I did revert to 1.1.15 and didn't happen either yesterday with the 1.1.16 version

**Comment by valorkin** [comment]
can you show me a component?

**Comment by Scipionh** [comment]
```
<pagination [totalItems]="totalNumberOfItems" [itemsPerPage]="itemsPerPage" [(ngModel)]="page" (pageChanged)="page=$event.page; refreshPaginationQueryParams();" previousText="&lsaquo;" nextText="&rsaquo;" firstText="&laquo;" lastText="&raquo;"></pagination>
```

**Comment by valorkin** [comment]
https://unpkg.com/ng2-bootstrap@1.1.16/components/pagination/pager.component.js

But selectors are different, did you try clean install and clean build?

**Comment by Scipionh** [comment]
Yep, I did it several times

**Comment by valorkin** [comment]
need plunker or something to reproduce
we are using v16 without such issues
