### ISSUE TITLE
Using datepicker causes all lazily-loaded chunks' code to be duplicated in 0.chunk.js

### ISSUE THREAD

**Issue by aaronleestic** [valor-software/ngx-bootstrap#1296]
Using Angular CLI beta.21 with Angular 2.2.1

Reproducible bug at repo https://github.com/aaronleeucla/angular-cli-lazy-load-bug-repro

**Comment by valorkin** [comment]
I am afraid I will need help with this issue from angular cli team

**Comment by valorkin** [comment]
I have seen similar behavior eventually
how did I fixed it
I have imported a datepicker **only** in lazy loaded module
and imported it from `ng2-bootstrap/datepicker`
