### ISSUE TITLE
Unit testing with ComponentsHelper

### ISSUE THREAD

**Issue by BkSouX** [valor-software/ngx-bootstrap#1302]
Hi, 

I have an issue with my unit test using ComponentsHelper.
Before I used to inject a `ComponentFactoryResolver` and an `Injector` every time I wanted to create a component and my tests were fine.

I was doing this in my app : 

```
const injector = this.buildStructureComponentInjector();
const factory = this.componentFactoryResolver.resolveComponentFactory(StructureComponent);
// Create component
const componentRef = this.structuresLocation.createComponent(factory, null, injector);
```

And now I do this : 

```const structureRef = this.componentsHelper.appendNextToLocation(StructureComponent, this.structuresLocation, this.getStructureProviders());```

In my tests, I have that error : 

>     Error: No component factory found for StructureComponent

I already have StructureComponent in my entryComponents array of app module and the app is working fine.

So, how do you deal with ComponentsHelper test ?

**Comment by valorkin** [comment]
I removed it completely, please try v1.1.16-7
Docs preview here http://valorkin.github.io/ng2-bootstrap/#/
