### ISSUE TITLE
datepicker and model-driven forms 

### ISSUE THREAD

**Issue by emilfighter** [valor-software/ngx-bootstrap#1316]
Is there any way to connect <datepicker> with model-driven / reactive-driven forms in Angular 2? 
Currently, it looks like <datepicker> does not support formControlName attribute.

**Comment by valorkin** [comment]
already implemented, 
should be available in @next version
try to `npm i ng2-bootstrap@next`

**Comment by stephsavoie** [comment]
Can you update documentation  or do a plunkr for that case?  I still don't know how to implement it in reactive forms.

**Comment by mattmcardle** [comment]
Can someone provide an example of how this is used? I can't figure out how to implement it.

**Comment by zhenghao1** [comment]
Please show how it's done...I'm considering PrimeNG because I don't know how it's done here.

**Comment by valorkin** [comment]
I am not adding sample to existing datepicker, because I have reworked it from the ground. And will publish in nearest couple of weeks
