### ISSUE TITLE
Carousel compatible version with Angular 2.3.0

### ISSUE THREAD

**Issue by ComadoDragon** [valor-software/ngx-bootstrap#1317]
Hi,
I tried 1.1.16 with Angular 2.3.0 but carousel also all of the pictures on the bottom of looks. Also Angular 2.1.0 worked well.

thanks

**Comment by valorkin** [comment]
oh, I love no breaking changes updates in ng2 :D

**Comment by valorkin** [comment]
Please try v1.1.16-7 
Docs preview here http://valorkin.github.io/ng2-bootstrap/#/

**Comment by ComadoDragon** [comment]
v1.1.16-7 and Angular 2.3.1 worked well. Thanks.

**Comment by valorkin** [comment]
Awesome :)
