### ISSUE TITLE
minor typo in class carousel-caption

### ISSUE THREAD

**Issue by Methodician** [valor-software/ngx-bootstrap#1326]
The class carousel-caption is misspelled carusel-caption. When you fix this, I'll have to fix my CSS in a few apps. Thanks for a great tool! Looking forward to the refined product.

**Comment by valorkin** [comment]
Ups, can you do a small PR, please?

**Comment by Methodician** [comment]
I don't know those acronyms.

**Comment by valorkin** [comment]
PR - pull request

**Comment by Methodician** [comment]
Hey I'd love to get involved next time but this one is my bad. I thought the class was coming from ng2-bootstrap but it was actually my own typo. Sorry to divert your attention.

**Comment by valorkin** [comment]
It happens :)
