### ISSUE TITLE
pagination showing additional pages

### ISSUE THREAD

**Issue by Bhushan001** [valor-software/ngx-bootstrap#1331]
I have used pagination module as below: 

    public config: any = {
        id: 'advanced',
        itemsPerPage: 8,
        currentPage: 1,
        totalItems: 20
    };
    <pagination [totalItems]="config.totalItems" [(ngModel)]="config.currentPage" (pageChanged)="pageChanged($event)"></pagination>

Its working good, but Its supposed to show only 3 pages , but it shows 4 pages where 4th one is blank.

I want only those no of pages upto which I have records.

any inputs?

Thanks.

**Comment by valorkin** [comment]
@Bhushan001 I am sure issue is here: https://github.com/valor-software/ng2-bootstrap/blob/development/src/pagination/pagination.component.ts#L282-L287

it will be a nice reason for small PR,
and add test for this edge case,
thanks in advance ;)

**Comment by jeff-jacobs** [comment]
I just started using this myself, and I'm experiencing the exact same issue. On the request I'm making, there is one last result on page 7 and then a blank page 8.

I hope this gets merged soon :)

**Comment by jeff-jacobs** [comment]
Nevermind on mine. I realized mine was due to how I was determining the offset on my API call, so on page change, I was essentially chopping off the first page of results by accident resulting in the last page being blank.

**Comment by brulejr** [comment]
Any update on this issue? I don't see a PR, but then again it could be my eyes. If a PR is still needed, do you think the change to be as simple as removing the "+1" from endPage:  https://github.com/valor-software/ng2-bootstrap/blob/development/src/pagination/pagination.component.ts#L282-L287

I'd be happy to put in the PR, but could use some guidance.

BTW, keep up the great work!

**Comment by IlyaSurmay** [comment]
Seems fixed in 2.0.0-beta.8, will be reopened if we have sample to reproduce.
