### ISSUE TITLE
Typeahead's typeaheadOptionField option not working

### ISSUE THREAD

**Issue by johan13** [valor-software/ngx-bootstrap#134]
I am providing locations from a geocoding API as typeahead options. The have the format `{long:number, lat:number, name:string}`. When I try to show the name using `[typeaheadOptionField]="name"` the typeahead suggestions still appear as `[object Object]`.

It appears the problem is that we lose `this` and access properties on the global object instead at [typeahead.directive.ts:278](https://github.com/valor-software/ng2-bootstrap/blob/fab59095933a29eb88657f9f31e690ed759fae33/components/typeahead/typeahead.directive.ts#L278).

**Comment by johan13** [comment]
Never mind. I should have written `[typeaheadOptionField]="'name'"` obviously! Regarding `this`, I think Chrome's developer tools has me fooled somehow...

**Comment by valorkin** [comment]
@johan13 please check that `typeaheadOptionField="name"` works too
no extra quotes should be needed and without `[]`
