### ISSUE TITLE
Tooltip right position works not correctly

### ISSUE THREAD

**Issue by EinarValholl** [valor-software/ngx-bootstrap#1341]
[https://s29.postimg.org/4042dn0iv/image.png](https://s29.postimg.org/4042dn0iv/image.png)
I thought that it is problem for me only, but I see that bug on your web-site

**Comment by SergeyKuryatnick** [comment]
Yeah, thanks.
it's already fixed, but not published yet on demo.

**Comment by EinarValholl** [comment]
Thanks. When it will be published in library?
