### ISSUE TITLE
caused by: No provider for TabsetConfig!

### ISSUE THREAD

**Issue by guzmo** [valor-software/ngx-bootstrap#1344]
Tried to update to "1.1.16-7" and now I got caused by: No provider for TabsetConfig!. 
It worked fine in 1.1.16. 
Do I need to add a provider for this Injectable? Seems nothing has changed in the documentation :)
I'm importing the TabsModule

**Comment by valorkin** [comment]
Yep, I had to `prerelease` as latest so guys can use it with 2.3
I am working on documentation at the moment
http://valorkin.github.io/ng2-bootstrap/#/tabs

in two words: `call TabsModule.forRoot()`

**Comment by guzmo** [comment]
Thanks, will try it now

**Comment by guzmo** [comment]
Worked like a charm (Y)

**Comment by valorkin** [comment]
Awesome :)

**Comment by SylTi** [comment]
What's the point of using semver if you publish breaking change without updating the right number ?
