### ISSUE TITLE
Tabset (select) issue

### ISSUE THREAD

**Issue by alarv** [valor-software/ngx-bootstrap#1346]
I discovered a nasty bug, that unfortunately can't provide a reproducible plunker for, as I don't know the exact circumstances to reproduce it. It's currently happening on my app, about the (select) event.

I have a tabset like this: 
```html
<tabset justified="true" [hidden]="loading" >

    <tab heading="Dashboard" (select)="navigateTo('/admin')">
    </tab>
    <tab heading="Tweets" (select)="navigateTo('/admin/tweets')">
    </tab>
    <tab heading="Posts" (select)="navigateTo('/admin/posts')">
    </tab>
    <router-outlet></router-outlet>
  </tabset>
```

and a navbar like this:
```html
<ul class="nav navbar-nav navbar-left">
            <li><a routerLink="/upload" routerLinkActive="active">Upload</a></li>
            <li><a *ngIf="authService.isAdmin" routerLink="/admin" routerLinkActive="active">Admin</a></li>
            <!--<li><a href="#">About</a></li>-->
</ul>
```

When I'm on the admin route and I click on the navbar to go the upload tab, the last tab is somehow getting triggered, which leads to another change of route (it goes to `/upload`, then instantly changes to `admin/posts`. I thought it was a routing issue, but it's definitely on the tabset. If you want more info I can provide you with a gif etc.

**Comment by slubowsky** [comment]
Sounds like https://github.com/valor-software/ng2-bootstrap/issues/696

**Comment by olaf89** [comment]
I have the same issue.

**Comment by valorkin** [comment]
closing in favour of #696 
I was able to reproduce this issue, so it will be fixed soon
