### ISSUE TITLE
TimepickerComponent minutesOnBlur/hoursOnBlur signature mismatch

### ISSUE THREAD

**Issue by ngladitz** [valor-software/ngx-bootstrap#1349]
In 1.1.16-7 the template for TimepickerComponent contains:
`(blur)="hoursOnBlur($event)"`
and 
`(blur)="minutesOnBlur($event)"`

But the signatures currently don't allow any arguments:
  `public minutesOnBlur(): void`
  `public hoursOnBlur(): void`

With ngc this results in:
> Error at .../timepicker.component.ngfactory.ts:651:35: Supplied parameters do not match any signature of call target.
>Error at .../timepicker.component.ngfactory.ts:669:35: Supplied parameters do not match any signature of call target.

**Comment by valorkin** [comment]
fix published as 16-8
