### ISSUE TITLE
chore(typeahead): Please support nested property in typeaheadOptionField if possible

### ISSUE THREAD

**Issue by hongbo-miao** [valor-software/ngx-bootstrap#135]
I am trying to use Typeahead.

The example code 

```
private statesComplex:Array<any> = [
    {id: 1, name: 'Alabama'}, {id: 2, name: 'Alaska'}, {id: 3, name: 'Arizona'}];
```

and 

```
<input [(ngModel)]="selected"
       [typeahead]="statesComplex"
       (typeaheadOnSelect)="typeaheadOnSelect($event)"
       [typeaheadOptionField]="'name'"
       class="form-control">
```

runs well.

But when I try to change the data format

```
private statesComplex:Array<any> = [
    {id: 1, profile: {name: 'Alabama', email: '111'}}, {id: 2, profile: {name: 'Alaska', email: '222'}}, {id: 3, profile: {name: 'Arizona', email: '333'}}];
```

and use

```
<input [(ngModel)]="selected"
       [typeahead]="statesComplex"
       (typeaheadOnSelect)="typeaheadOnSelect($event)"
       [typeaheadOptionField]="'profile.name'"
       class="form-control">
```

It does not work. The problem is typeaheadOptionField does not support nested property. I got the answer from here. http://stackoverflow.com/questions/35187354/typehead-in-ng2-bootstrap-cannot-show-items-in-angular-2/35187996#35187996

Please support nested property in typeaheadOptionField if possible. Thanks!

**Comment by bhaveshvyas007** [comment]
Can we have this feature more options ? so that I can have two attributes path to match
I am facing issue in implementing grouped json structure.

For example : 
`{
    "Skill": [
            {
              "SkillName": "Data Analysis",
              "SubSkills": [
                {"SkillName": "SQL"},
                {"SkillName": "RDBMS"},
                {"SkillName": "Oracle"},
                {"SkillName": "Postgresql"},
                {"SkillName": "Sybase"},
                {"SkillName": "MongoDB"},
                {"SkillName": "JSON"},
                {"SkillName": "XML"}
              ]
            },
     {
              "SkillName": "Skill 2",
              "SubSkills": [
                {"SkillName": "abc"},
                {"SkillName": "xyz"},
                {"SkillName": "pqr"},
              ]
            },
   ]
}`

In above example I am using typeaheadOptionField = SkillName. But I also need to match SkillName from subskills and return the whole skill object on select

Is it possible now?
