### ISSUE TITLE
Pagination: v1.1.16-7 PaginationConfig error

### ISSUE THREAD

**Issue by kirjai** [valor-software/ngx-bootstrap#1354]
After upgrading to `1.1.16-7`, I started getting `No provider for PaginationConfig!` errors.
Was importing `PaginationModule` in my module declaration and then using in the template:
```
<pagination [totalItems]="items.length"
     [(ngModel)]="currentPage"
     [itemsPerPage]="perPage"
     previousText="&lsaquo;"
     nextText="&rsaquo;"></pagination>
```

Worked totally fine for months. No mention of `PaginationConfig` in the docs or anywhere, for that matter. Downgraded back to `16-3` to get it working.

Versions:
`angular: 2.2.3`
`node: 4.4.2`
`npm: 3.10.9`

**Comment by Martin-Luft** [comment]
You must import them odule with `forRoot()`:

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { PaginationModule } from 'ng2-bootstrap';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

@NgModule({
  imports: [
    AppRoutingModule,
    BrowserModule,
    PaginationModule.forRoot()
  ],
  declarations: [
    AppComponent
  ],
  bootstrap: [ AppComponent ]
})
export class AppModule {}

```

**Comment by muthucse7** [comment]
Great!  Thank you.

PaginationModule.forRoot() - Fixed my issue.

**Comment by gazee** [comment]
but my problem still not fixed yet
still showing 
R3InjectorError(AppModule)[PaginationConfig -> PaginationConfig -> PaginationConfig -> PaginationConfig]: 
  NullInjectorError: No provider for PaginationConfig!
