### ISSUE TITLE
feat(datepicker): add open\close\toggle visibility methods

### ISSUE THREAD

**Issue by Sookii** [valor-software/ngx-bootstrap#1359]
I need a time interval data. so I put two <input ngbDatepicker> on the page , 
now is the question , first I click the startdate input (the previous one), and I didn't do anyting with it, then I click the enddate input (the second one),  now is the problem . there are tow datepickers on the page .

I cann't find any APIs to solve this problem. my english is not good, hope you can understand it and give me a hand.

**Comment by valorkin** [comment]
indeed, let me change this issue to feat req

**Comment by valorkin** [comment]
fixed in new datepicker
available in v1.9.2
http://valor-software.com/ngx-bootstrap/#/datepicker
