### ISSUE TITLE
NPM install 1.1.15 ENOENT

### ISSUE THREAD

**Issue by montella1507** [valor-software/ngx-bootstrap#1372]
verbose stack Error: Error extracting Roaming\npm-cache\ng2-bootstrap\1.1.15\package.tgz archive: ENOENT: no such file or directory, open 'Roaming\npm-cache\ng2-bootstrap\1.1.15\package.tgz'
883 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:308:10)
883 verbose stack     at emitOne (events.js:77:13)
883 verbose stack     at ReadStream.emit (events.js:169:7)
883 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:181:14
883 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:232:16

Even with npm cache cleaned..

**Comment by valorkin** [comment]
please refer to https://github.com/npm/npm/issues/15248
and update ng2-bootstrap to latest version
