### ISSUE TITLE
ng build --aot fails 

### ISSUE THREAD

**Issue by harilal** [valor-software/ngx-bootstrap#1383]
I got this following error 

`ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 7:12 in the original .ts file), resolving symbol Ng2BootstrapConfig.theme in /home/harilal/works/node_modules/ng2-bootstrap/components/ng2-bootstrap-config.d.ts, resolving symbol TypeaheadContainerComponent in /home/harilal/works/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts, resolving symbol TypeaheadContainerComponent in /home/harilal/works/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts`

angular-cli: 1.0.0-beta.24
node: 6.9.1
os: linux x64
@angular/common: 2.4.0
@angular/compiler: 2.4.0
@angular/core: 2.4.0
@angular/forms: 2.4.0
@angular/http: 2.4.0
@angular/platform-browser: 2.4.0
@angular/platform-browser-dynamic: 2.4.0
@angular/router: 3.4.0
@angular/material: 2.0.0-alpha.11-3
@angular/compiler-cli: 2.4.0

**Comment by valorkin** [comment]
Please install latest ng2 bootstrap version
1.1.16-9

**Comment by dessalines** [comment]
Just a note, I kept getting this error, even after I updated my `package.json`, until I realized yarn wasn't picking up the new dependency, and I had to manually install it with `npm i ng2-bootstrap@1.1.16-11` . So it doesn't look like yarn can handle this custom semver.

**Comment by valorkin** [comment]
It is not custom, it is just npm version prerelease, command
