### ISSUE TITLE
ng help display ember insted of ng

### ISSUE THREAD

**Issue by alyahmedaly** [valor-software/ngx-bootstrap#1386]
angular-cli: 1.0.0-beta.24
node: 6.9.2
os: win32 x64
@angular/common: 2.4.0
@angular/compiler: 2.4.0
@angular/core: 2.4.0
@angular/forms: 2.4.0
@angular/http: 2.4.0
@angular/platform-browser: 2.4.0
@angular/platform-browser-dynamic: 2.4.0
@angular/router: 3.4.0
@angular/compiler-cli: 2.4.0

sample of result
ember build <options...>
  Builds your app and places it into the output path (dist/ by default).
ember completion
  Adds autocomplete functionality to `ng` commands and subcommands
ember doc <keyword>
  Opens the official Angular documentation for a given keyword.

ember e2e
  Run e2e tests in existing project

**Comment by valorkin** [comment]
How can I help you?

**Comment by alyahmedaly** [comment]
Sorry, wrong place
