### ISSUE TITLE
Datepicker fire ngModelChange different when changing months differently

### ISSUE THREAD

**Issue by quiringk** [valor-software/ngx-bootstrap#1392]
When I change months by clicking the month name, and selecting the name of the month, the bound date changes (to the first of the month.) When I change months by clicking the left and right arrows, the bound date doesn't change. Is this correct behavior?

My goal: when a month or year changes I want to keep the datepicker open in my dropdown. When the day changes I want the dropdown to go away. I can't implement the logic when different ways of changing months affect the bound date object differently.

**Comment by valorkin** [comment]
should fixed in new datepicker
available in v1.9.2
http://valor-software.com/ngx-bootstrap/#/datepicker
