### ISSUE TITLE
feat(docs): add popover component

### ISSUE THREAD

**Issue by guysenpai** [valor-software/ngx-bootstrap#1394]
I have compare this angular2 bootstrap module and the ng-bootstrap module. I saw the popover component is missing in this. it's in development or it's an oversight?

**Comment by valorkin** [comment]
Popover implemented, documentation is missing

**Comment by valorkin** [comment]
code is documented, so try to check it out
https://github.com/valor-software/ng2-bootstrap/blob/development/src/popover/popover.directive.ts

**Comment by valorkin** [comment]
Let it open as a reminder for me :)

**Comment by Klinton90** [comment]
Thank you for your hard work. Please allow templates for header as well...

**Comment by valorkin** [comment]
@Klinton90 templates usages samples added to doc

**Comment by Klinton90** [comment]
Thank you
