### ISSUE TITLE
Typeahead box alignment issues

### ISSUE THREAD

**Issue by hassanasad** [valor-software/ngx-bootstrap#1396]
Hi - Typeahead was working perfectly in previous version, however i believe in one of the recent updates the alignment of the box that shows suggestions are messing up. The box now shows up after the input field and not below it.

Also i am not sure how to debug its CSS values as it closes as soon as i click anywhere inside my chrome inspector :)

Just for reference here is a screenshot: https://www.dropbox.com/s/zqxr1lzjc76zhy9/Screenshot%202016-12-24%2012.56.16.png?dl=0

**Comment by zkorz** [comment]
Same thing happening to me when updating:
![image](https://cloud.githubusercontent.com/assets/1299559/21471929/c67e9e00-ca91-11e6-8660-a52a22387bce.png)

**Comment by valorkin** [comment]
@zkorz @hassanasad are you using hybrid app too?

**Comment by hassanasad** [comment]
@valorkin - I am not sure what hybrid apps are. I am just using your package with Angular2 (2.4 to be exact) and angular-cli.

**Comment by olaf89** [comment]
I had same problem, i used .form-inline, after updating to latest version dropdown was aligned as showed on screenshots. Its not specific to hybrid apps.

**Comment by valorkin** [comment]
Can you give me peace of html with Typeahead
So I can reproduce it

**Comment by olaf89** [comment]
Sure,
```
<div class="form-inline">
    <div class="form-group">
        <label>label</label>
        <input type="text" id="input" class="form-control" [(ngModel)]="selected" [typeahead]="items">
    </div> 
</div>
```

**Comment by zkorz** [comment]
Mine works when I take away the class navbar-form from the parent span.

```
<span class="navbar-form" role="search">
    <form class="btn-group ng-valid ng-touched ng-dirty">
        <input class="form-control ng-valid ng-touched ng-dirty" name="search" placeholder="Search students or assignments..." type="search">
        <span class="glyphicon glyphicon-remove-circle searchclear"></span>
    </form>
</span>
```

**Comment by hassanasad** [comment]
Well looking at the mark up of other folks here, i believe its some issue that appears with bootstrap ? (I too am using it with bootstrap) - however it was working fine before the recent updates.

**Comment by valorkin** [comment]
Before, I was forcing position of container and internal elemement, now only container.
One way or another I will publish a fix today

**Comment by hassanasad** [comment]
Thanks @valorkin and happy holidays ;)

**Comment by valorkin** [comment]
@hassanasad thanks, you too ;)

**Comment by valorkin** [comment]
ok, issues was with form inline
so I fixed it and now you can use `container="body"` to attach typeahead to body ;)

**Comment by valorkin** [comment]
published as 1.1.16-10, please try and drop me a note

**Comment by hassanasad** [comment]
Works perfectly for me again!

Thanks @valorkin :)

**Comment by zkorz** [comment]
@valorkin the main form is working great now:

![image](https://cloud.githubusercontent.com/assets/1299559/21506322/4997eee8-cc3d-11e6-8d3c-ce934ba05efc.png)


However on the extra small screen the typeahead is only showing the first choice, maybe sensing that there is not a lot of room below even though there really is beneath the navbar.

![image](https://cloud.githubusercontent.com/assets/1299559/21506317/3dc083aa-cc3d-11e6-9d50-9182d98d2483.png)

Here is the simplified markup:

```
<nav class="navbar navbar-default" role="navigation" style="">
    <div class="collapse navbar-collapse" aria-expanded="true" aria-hidden="false" style="display: block; overflow: visible; height: auto;">       
        <ul class="nav navbar-nav" id="navbarSearchBox">
            <li>
                <div class="col-xs-12">
                    <span class="navbar-form" role="search">
                        <form class="btn-group">
                            <input class="form-control" name="search" type="search">
                        </form>
                    </span>
                </div>
            </li>
        </ul>
    </div>
</nav>
```

**Comment by valorkin** [comment]
@zkorz can you try container="body" ?

**Comment by aleksander351** [comment]
@valorkin is there any way to align the dropdown to the right?
Otherwise it overflows the page if the list items are very long.
I borrowed the image from @zkorz 
I see that the typeahead directive has a protected placement property.
![image](https://user-images.githubusercontent.com/7508670/141302815-67b6078b-e014-4cd6-aa93-00fcedf49857.png)
