### ISSUE TITLE
feat(docs): add description of bug and workaround in angular ngUpgrate (ng1/ng2 hybrid app)

### ISSUE THREAD

**Issue by hisham** [valor-software/ngx-bootstrap#1398]
Tooltips stopped working in hybrid apps In the latest ng2-bootstrap repo (1.1.16-9). See attached screenshot. 

I made a repro repo at https://github.com/hisham/ng1-ng2-modal. Would be great if this can be fixed asap as it's preventing from using ng2-bootstrap properly in our project. 

![angular_quickstart](https://cloud.githubusercontent.com/assets/81853/21469266/69e03140-ca0f-11e6-90b9-0d17eb80d271.png)

**Comment by hassanasad** [comment]
I believe its similar issue for other components as well #1396

**Comment by valorkin** [comment]
@hisham ok, so thing is, [host] binding works differently in ngUpgrade app ;(
it adds tooltip in first round, than... it adds classes to tooltip container...

**Comment by valorkin** [comment]
So I will have to add some hack.. to make it work

**Comment by valorkin** [comment]
in particularity `this._ngZone.onStable` fired before it actually became stable

**Comment by valorkin** [comment]
@hisham please add this hack to your appModule, it will run additional zone.onStable event loop
```typescript
export class AppModule {
  constructor(ngZone: NgZone) {
    let repeat = true;
    ngZone.onUnstable.subscribe(() => { if (!repeat) { repeat = true; } } );

    ngZone.onStable.subscribe(() => {
      if (repeat) {
        setTimeout(() => { ngZone.run(() => { repeat = false; }); }, 50);
      }
    })
  }
}
```

**Comment by hisham** [comment]
The hack worked @valorkin thanks. But there is still a brief flicker where the tooltip is not in the right location. After that flicker the tooltip appears in and stays in the right location. 

I updated the https://github.com/hisham/ng1-ng2-modal repo where you can see this. 

I also filed https://github.com/angular/angular/issues/13694 in the angular 2 repo. But I don't understand the bug fully - can you review and add more detail to the ticket fully so that angular 2 team can understand what's going on and fix?

**Comment by hisham** [comment]
Also in my app in production it appears tooltip does not show until the item is clicked, but when app is reloaded, it starts appearing fine. So this hack doesn't seem to be a 100% fix.

**Comment by valorkin** [comment]
@hisham how to run your sample repo in prod mode?

**Comment by hisham** [comment]
That's a good question. I'm using angular cli in another repo with 'ng build -p' command. I'm not super familiar with systemjs so will have to modify the sample repo to reproduce the issue I'm seeing in my other repo that's using angular cli.

**Comment by valorkin** [comment]
Angular cli most probably shouldn't have such issues

**Comment by hisham** [comment]
Ok - please take a look at https://github.com/hisham/ng1-ng2-modal-cli for the repro of this second issue. It's not a build prod issue, but appears to be an issue that only happens when you navigate from an ng2 component to an ng1 controller.  

To run: 

`npm install`
`ng s`

Then go to localhost:4200, click 'Login'. Then hover over the star, you will see the tool does not appear correctly. Then refresh that page and hover over star again and you will see tooltip now appears correctly. 

![test_app](https://cloud.githubusercontent.com/assets/81853/21822153/573ed542-d733-11e6-8497-2957301abee4.png)

**Comment by ericmackrodt** [comment]
Any news on this? I upgraded ng2-bootstrap to the latest version (1.2.6) and my tooltips are all messed up now, they flicker, don't float and break my layout. It was working perfectly on 1.1.16.

**Comment by marcalj** [comment]
I've just upgraded to Angular 2.4.5 and ng2-bootstrap 1.3.2 with ngUpgrade (not static) and SystemJS and all seems to work perfectly without hacks.

**Comment by h6784rfg6** [comment]
Using Angular 2.4.8 and ng2-bootstrap 1.3.3 get the tooltip working only with the workaround with NgZone

**Comment by IlyaSurmay** [comment]
Seems outdated now, closed.
