### ISSUE TITLE
 Property 'forRoot' does not exist on type 'typeof DatepickerModule'

### ISSUE THREAD

**Issue by d668** [valor-software/ngx-bootstrap#1399]
just following the docs http://valor-software.com/ng2-bootstrap/#/datepicker

**Comment by bidelakbari** [comment]
The same for me. in all bootstrap Modules

**Comment by valorkin** [comment]
```
export class DatepickerModule {
  public static forRoot(): ModuleWithProviders {
    return {ngModule: DatepickerModule, providers: [DatepickerConfig]};
  }
}
```
but it is starting from v1.1.16-9

**Comment by d668** [comment]
what is that supposed to mean? why are you closing the issue?

**Comment by valorkin** [comment]
It means it is not an issue, you just need to install latest version
