### ISSUE TITLE
Typeahead options closing on back press when keyboard opened

### ISSUE THREAD

**Issue by tushar-velingkar** [valor-software/ngx-bootstrap#1400]
Typeahead options dismiss when we press back button when keyboard is open.

**Expected behaviour** : Keyboard should close and not the options

**Comment by valorkin** [comment]
ok, this is kinda mobile issue
good to know

**Comment by tushar-velingkar** [comment]
Hi

This issue gets fixed if I remove hide event from onBlur method in typeahead.directive.js
`TypeaheadDirective.prototype.onBlur = function () {
        if (this._container && !this._container.isFocused) {
            //this.hide();
        }
    };`

**Comment by IlyaSurmay** [comment]
Closed as can't reproduce (latest version, 2.0.0-rc.0, both desktop and mobile). Will be reopened if we have a reproduction via plunkr/stackblitz or sample repo.

You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by MarkJAmes1217** [comment]
Any updates ?
