### ISSUE TITLE
Min date limitation failed

### ISSUE THREAD

**Issue by zidisma** [valor-software/ngx-bootstrap#1401]
Hi, i got a little bug for you ;0)

use case:
1-Set a date of month as Min date (not 1st) (e.g: 2016-12-10)
2-Navigate into month selection grid
3- Click on Min date current month (for this example "December" of 2016)

=> it'll set 2016-12-01 as selected date which is outside min date range.

**Comment by valorkin** [comment]
fixed in new datepicker
available in v1.9.2
http://valor-software.com/ngx-bootstrap/#/datepicker
