### ISSUE TITLE
Multiple dropdownToggles in Navbar?

### ISSUE THREAD

**Issue by thehashrocket** [valor-software/ngx-bootstrap#1405]
ng2-bootstrap: 1.1.16-9
angular-cli: 1.0.0-beta.24
angular: 2.3.1

**Issue:**
In the standard [Bootstrap Navbar Component](http://getbootstrap.com/components/#navbar) you can have multiple dropdown menus. If I use the`dropdownToggle` on more than one dropdown menu, and then try to select one, it'll select the other one instead.

What ends up happening is this:

1. Dropdown 1 lives in navbar-left, and Dropdown 2 lives in navbar-right.
2. If I click on Dropdown 1, it works just fine, no issues.
3. If I click on Dropdown 2, then Dropdown 1 is triggered first. If I click on it again, then Dropdown 1 collapses and Dropdown 3 expands. 

My code looks almost exactly like the demo on the bootstrap site with some minor changes to get ng-bootstrap2 to work:

> <nav class="navbar navbar-default">
>   <div class="container-fluid">
>     
>     <div class="navbar-header">
>       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" (click)="isCollapsed = !isCollapsed">
>         <span class="sr-only">Toggle navigation</span>
>         <span class="icon-bar"></span>
>         <span class="icon-bar"></span>
>         <span class="icon-bar"></span>
>       </button>
>       <a class="navbar-brand" href="#">LEGO Organizer</a>
>     </div>
> 
>     
>     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" (collapsed)="collapsed($event)"
>          (expanded)="expanded($event)"
>          [collapse]="isCollapsed">
>       <ul class="nav navbar-nav">
>         <li><a [routerLink]="['']">Home <span class="sr-only">(current)</span></a></li>
>         <li><a [routerLink]="['login']" *ngIf="!auth.authenticated()">Log In</a></li>
>         <li><a (click)="auth.logout()" *ngIf="auth.authenticated()">Log Out</a></li>
>         <li id="dropdown3" class="dropdown" dropdown [(isOpen)]="status.isopen">
>           <a href="#" class="dropdown-toggle" data-toggle="dropdown3" role="button" aria-haspopup="true" aria-expanded="false" dropdownToggle>
>             Dropdown 3<span class="caret"></span>
>           </a>
>           <ul class="dropdown-menu">
>             <li><a href="#">Action</a></li>
>             <li><a href="#">Another action</a></li>
>             <li><a href="#">Something else here</a></li>
>             <li role="separator" class="divider"></li>
>             <li><a href="#">Separated link</a></li>
>             <li role="separator" class="divider"></li>
>             <li><a href="#">One more separated link</a></li>
>           </ul>
>         </li>
>       </ul>
>       <form class="navbar-form navbar-left">
>         <div class="form-group">
>           <input type="text" class="form-control" placeholder="Search">
>         </div>
>         <button type="submit" class="btn btn-default">Submit</button>
>       </form>
>       <ul class="nav navbar-nav navbar-right">
>         <li><a href="#">Link</a></li>
>         <li id="dropdown1" class="dropdown" dropdown [(isOpen)]="status.isopen">
>           <a href="#" class="dropdown-toggle" data-toggle="dropdown1" role="button" aria-haspopup="true" aria-expanded="false" dropdownToggle>
>             Dropdown 1<span class="caret"></span>
>           </a>
>           <ul class="dropdown-menu">
>             <li><a href="#">Action</a></li>
>             <li><a href="#">Another action</a></li>
>             <li><a href="#">Something else here</a></li>
>             <li role="separator" class="divider"></li>
>             <li><a href="#">Separated link</a></li>
>           </ul>
>         </li>
> 
>         <div class="btn-group">
>           <li class="dropdown" dropdown [(isOpen)]="status.isopen" *ngIf="loggedin" >
>             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" dropdownToggle>
>               Dropdown 2<span class="caret"></span>
>             </a>
>             <ul class="dropdown-menu">
>               <li><a href="#">Action</a></li>
>               <li><a href="#">Another action</a></li>
>               <li><a href="#">Something else here</a></li>
>               <li role="separator" class="divider"></li>
>               <li><a href="#">Separated link</a></li>
>             </ul>
>           </li>
>         </div>
>       </ul>
>     </div>
>   </div>
> </nav>

Here's the relevant info from package.json:

>   "dependencies": {
>     "@angular/common": "^2.3.1",
>     "@angular/compiler": "^2.3.1",
>     "@angular/core": "^2.3.1",
>     "@angular/forms": "^2.3.1",
>     "@angular/http": "^2.3.1",
>     "@angular/platform-browser": "^2.3.1",
>     "@angular/platform-browser-dynamic": "^2.3.1",
>     "@angular/router": "^3.3.1",
>     "angular2-jwt": "^0.1.27",
>     "auth0-js": "^7.2.1",
>     "bootstrap": "^3.3.7",
>     "core-js": "^2.4.1",
>     "ng2-bootstrap": "^1.1.16-9",
>     "rxjs": "^5.0.1",
>     "ts-helpers": "^1.1.1",
>     "zone.js": "^0.7.2"
>   },
>   "devDependencies": {
>     "@types/auth0": "^2.3.32",
>     "@types/jasmine": "2.5.38",
>     "@types/node": "^6.0.42",
>     "angular-cli": "1.0.0-beta.24",
>     "codelyzer": "~2.0.0-beta.1",
>     "jasmine-core": "2.5.2",
>     "jasmine-spec-reporter": "2.5.0",
>     "karma": "1.2.0",
>     "karma-chrome-launcher": "^2.0.0",
>     "karma-cli": "^1.0.1",
>     "karma-jasmine": "^1.0.2",
>     "karma-remap-istanbul": "^0.2.1",
>     "protractor": "~4.0.13",
>     "ts-node": "1.2.1",
>     "tslint": "^4.0.2",
>     "typescript": "~2.0.3"
>   }

**Comment by critchie** [comment]
I can't guarantee this will fix it but it looks like you are mixing bootstrap drop down attributes with ng2-angular attributes.  For example data-toggle="dropdown1" looks like a bootstrap drop down setup.

First thing I would do is remove bootstrap drop down concerns.  Follow the ng2-bootstrap example to the letter [here](http://valor-software.com/ng2-bootstrap/#/dropdowns).

**Comment by thehashrocket** [comment]
@critchie you were right, that fixed it. Thanks! :)

**Comment by hbsoftco** [comment]
@critchie Page not found!
