### ISSUE TITLE
Tooltip with delay only appears once

### ISSUE THREAD

**Issue by zkorz** [valor-software/ngx-bootstrap#1406]
I noticed this on my page, but it also is an issue on your demo page:

![image](https://cloud.githubusercontent.com/assets/1299559/21506829/38d21b3e-cc41-11e6-8d48-ff9d74068079.png)

Hover over "delayed" for one second and the tooltip appears (as expected), but then unhover and hover over it again and it will never appear a second time.

**Comment by Valery-vs** [comment]
Hi. When could we see this fix in release?

**Comment by AhsanAyaz** [comment]
@valorkin when can we see in a release? 
I'm building a project for a client and it really requires the delayed effect 😄

**Comment by IlyaSurmay** [comment]
fixed in #2826
