### ISSUE TITLE
In the README, shouldnt bootstrap style come FIRST?

### ISSUE THREAD

**Issue by dylanh724** [valor-software/ngx-bootstrap#1412]
open angular-cli.json and insert a new entry into the styles array
      "styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css"
      ],

^ Shouldn't it be **bootstrap, styles** rather than **styles, bootstrap**? Otherwise bootstrap will override custom styles, right?

**Comment by valorkin** [comment]
It depends on what you want to achieve, I just wanted to look familiar to ng cli users

**Comment by austince** [comment]
Is there a use case for having it overwrite your styles?
