### ISSUE TITLE
Tab fires select event on destroy

### ISSUE THREAD

**Issue by WiseBird** [valor-software/ngx-bootstrap#1413]
Part of the stack trace:

![first](https://cloud.githubusercontent.com/assets/1745378/21540088/32ec6e0a-cdc6-11e6-8e3d-8d3656f9f9bb.png)

![second](https://cloud.githubusercontent.com/assets/1745378/21540089/349624ee-cdc6-11e6-86a7-8de41ab88c31.png)

![third](https://cloud.githubusercontent.com/assets/1745378/21540090/35de0aec-cdc6-11e6-9bba-0f379e6e16b1.png)

**Comment by valorkin** [comment]
I am closing this, will be published as 16-11 today
