### ISSUE TITLE
Dropdown adding 'active' class when isOpen

### ISSUE THREAD

**Issue by rpdmiranda** [valor-software/ngx-bootstrap#1415]
Dropdown component is adding 'open' and 'active' classes when a dropdown is opened. The 'active' class is also used in navbars, to mark which item is active. That way, it's  difficult to use the dropdown component in menus.

May the  `@HostBinding('class.active') ` be removed?

**Comment by patrick-mackay** [comment]
We're having the same issue here. Bootstrap only uses "open" on the <li>, but ng2-bootstrap is adding also the "active" class. We have some css that are being activated with the active class.

following rpdmiranda's pointer, removing

__webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__angular_core__["HostBinding"])('class.active'), (line 4965)

from ng2-bootstrap.umd.js, and I guess that removing 

"{ type: HostBinding, args: ['class.active',] }," 

from dropdown.directive.js (line 157) will do the trick before bundling.

Any chance to get this change? I could do a PR but not sure its worthwhile for such a small change.

**Comment by nsobral** [comment]
same issue
