### ISSUE TITLE
Semantic releases

### ISSUE THREAD

**Issue by vdclouis** [valor-software/ngx-bootstrap#1418]
Any reason this project is not following semantic releases?
Things like `1.1.16-11` doesn't mean anything...

Up to date `CHANGELOG` would be nice as well.

Keep it up!

**Comment by valorkin** [comment]
Thing is I am working on massive update, and 16-11 is semver pre-release version.
I want to go with semver starting from v2

**Comment by valorkin** [comment]
@vdclouis good point about changelog
I have updated it and added migration notes, please check it
https://github.com/valor-software/ng2-bootstrap/blob/development/CHANGELOG.md

thanks in advance for feedback

**Comment by tonihelminen** [comment]
@valorkin, seems that the usage of pre-release versioning is not following semver specification. If you are working on a massive (sounds like major) update, I suppose you should have used pre-releases 2.0.0-x, not 1.1.16-x. 

Clip from http://semver.org/#semantic-versioning-specification-semver :
"When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version. Example: 1.0.0-alpha < 1.0.0." 

Here is one unsuccessful scenario from real life:
- Install the latest version from ng2-bootstrap and save the semver into package.json (currently "ng2-bootstrap": "^1.1.16-11"):
  * npm install ng2-bootstrap --save 
- Take the bootstrap into use in your codebase.
- After a couple weeks run 'npm update' to update the dependencies to the latest ones.
  => ng2-bootstrap 1.1.16-11 will be replaced by 1.1.16, which is two months older and actually contains breaking changes and e.g. 'ng build' is not working anymore:

C:\projects\x\src\y> ng build
 35% building modules 215/376 modules 161 active ...s\node_modules\ng2-table\ng2-table.jsresolve 'ng2-bootstrap/pagination' in 'C:\projects\x\src\y\scripts\app\z'
  Parsed request is a module
  using description file: C:\projects\x\src\y\package.json (relative path: ./scripts/app/z)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\projects\x\src\y\package.json (relative path: ./scripts/app/z)
    resolve as module
      looking for modules in C:\projects\x\src\y\node_modules
        using description file: C:\projects\x\src\y\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\projects\x\src\y\package.json (relative path: ./node_modules)
          using description file: C:\projects\x\src\y\node_modules\ng2-bootstrap\package.json (relative path: ./pagination)
            as directory
              C:\projects\x\src\y\node_modules\ng2-bootstrap\pagination doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\projects\x\src\y\node_modules\ng2-bootstrap\pagination doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\projects\x\src\y\node_modules\ng2-bootstrap\pagination.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\projects\x\src\y\node_modules\ng2-bootstrap\pagination.js doesn't exist

C:\projects\x\src\y\node_modules\webpack\lib\Compiler.js:220
                                        if(err) return callback(err);
                    ^
TypeError: Cannot read property 'hash' of undefined
    at C:\projects\x\src\y\node_modules\angular-cli\tasks\build-webpack.js:35:26

**Comment by rdsedmundo** [comment]
Very good to have.

It's not good at all having breaking changes, for example: from 1.4.2 to 1.5.0 - which have breaking changes. This should be a Major release, or a Minor if it has backward support. 👍

**Comment by valorkin** [comment]
Yep, v1 will have mainly fixes and new features,
V2 will be ready in May, with a lot of new things :)
