### ISSUE TITLE
fix(tabs): all tabs are showing (initiated and added to the DOM) even if no tab is selected.

### ISSUE THREAD

**Issue by guzmo** [valor-software/ngx-bootstrap#1422]
I might have missed how to solve this but currently all tabs are "showing" ( Components initiated and added to the DOM ), even the ones not selected which has a HUGE performance impact when you have alot of tabs. Not sure if you want them to be showing by default and we have to hide them programmatically when we want to?

Feels like using "ngShow" instead of "ngIf" in Angular 1 = Not nice :)

A fix would be appreciated! :)

**Comment by niklas-dahl** [comment]
same here..
