### ISSUE TITLE
Collapse with several collapse contents on one page

### ISSUE THREAD

**Issue by KevKo1990** [valor-software/ngx-bootstrap#1423]
Hi,

I want to build a page with some listed documents and provide some meta information if clicked on them. My idea was to implement that via the collapse feature in the following way with NgFor:

`<div class="panel panel-default" *ngFor="let Document of Documents">

      <div class="panel-heading" (click)="isCollapsed = !isCollapsed">
        tbd
      </div>
      <div (collapsed)="collapsed($event)"
           (expanded)="expanded($event)"
           [collapse]="isCollapsed"
           class="card card-block card-header">
        tbd
      </div>
    </div> `

However, the problem is now that if I click on one panel-heading all collapse divs are opened and for closing vice versa. Is there a way to specify the collapse just for one single panel-heading?

Thanks!

**Comment by valorkin** [comment]
Looks like you need to use tabs?

**Comment by KevKo1990** [comment]
No tabs was wrong... however Accordion was the one I searched for... Didn't think of that. Cheers mate!

**Comment by valorkin** [comment]
Cheers :)

**Comment by webkhushboo** [comment]
How you are implementing accordion for this above example ? Can you please tell me. I am having same situation .

**Comment by DejanVeljkov** [comment]
I have same problem.
This works for me
For example:
If you have some ngFor="let object of objects"
you can add some boolean property ("collapsed") on object model, and implement collapse like
![image](https://user-images.githubusercontent.com/17719042/36584882-da6e3522-187b-11e8-8c4f-c303003b27fe.png)

**Comment by sidjai09** [comment]
![image](https://user-images.githubusercontent.com/46618565/73067099-bf7bc980-3ecd-11ea-96d4-b7e10b202b18.png)

![image](https://user-images.githubusercontent.com/46618565/73067131-d3273000-3ecd-11ea-89d2-bbca69d9a97a.png)


This worked for me
