### ISSUE TITLE
feat(package): Provide default, custom configs to modules

### ISSUE THREAD

**Issue by wojciechpolak** [valor-software/ngx-bootstrap#1427]
I would like to provide a default, global `TooltipConfig` with, for example, `container` always set to `'body'` to avoid repeating this attribute all over the code. Is it possible to do it now? If not, maybe it would be good to pass a custom `TooltipConfig` to `.forRoot()` methods? The same would apply to other modules.

```
@NgModule({
  imports: [
     TooltipModule.forRoot(myTooltipConfig),
     ...
  ]
})
export class AppModule() {}
```

**Comment by valorkin** [comment]
please check `Configuring defaults` section
http://valor-software.com/ng2-bootstrap/#/popover

sorry didn't yet implemented shareable links in docs

**Comment by valorkin** [comment]
Please drop me an update about it,
as for now AoT will complain if I will try to do what you are asking for

**Comment by wojciechpolak** [comment]
Just checked and it works the way you pointed. Thanks!

**Comment by valorkin** [comment]
Awesome, documentation is working :)

**Comment by valorkin** [comment]
@wojciechpolak you know... this idea didn't let me go
I did a bit more research let me leave it open
I like it... but need to think about it a bit more

**Comment by manuelfink** [comment]
Can you add an sample on how to load customized tooltips within shared.module.ts with forRoot?

I'm trying the same, however not getting it working within the shared.module.ts. posted question on stackoverflow http://stackoverflow.com/questions/42393551/ng2-how-to-load-ng2-bootstrap-with-customized-tooltipconfig.
