### ISSUE TITLE
ng2-bootstrap carousel stops on selecting a particular slide using bullet

### ISSUE THREAD

**Issue by VishalGulati** [valor-software/ngx-bootstrap#1428]
I am facing issue with ng2-bootstrap carousel. If I select a particular slide by clicking on bullet corresponding to that then my carousel gets fixed to that slide and doesn't continue sliding. The same problem is also in the carousel implemented on valor site [https://valor-software.com/ng2-bootstrap/#/carousel](https://valor-software.com/ng2-bootstrap/#/carousel).Below is my code:

**PLEASE NOTE: THIS HAPPENS ONLY IN MOBILE MODE AND NOT IN DESKTOP MODE. TRIED THIS ON VALOR SITE AS WELL**.

```
<carousel [noWrap]="false" [interval]=1000>
        <slide *ngFor="let slide of pdDataObj.product_images;">
          <img [src]="slide" style="margin:auto;" />
        </slide>
</carousel>
```
I am using **1.1.16-10** version of ng2-bootstrap and **2.4.1** version of angular2. Please help me resolve this.

**Comment by valorkin** [comment]
Yep, it stops when has focus in
and resumes on blur
this is an issue

**Comment by felixkubli** [comment]
In the carousel component template,
`<div (mouseenter)="pause()" (mouseleave)="play()"  class="carousel slide">`
the mouse events can only be used with a cursor.
I added a `(mouseup)="play()"` , so it can also be used in a mobile mode.

**Comment by felixkubli** [comment]
#1433

**Comment by valorkin** [comment]
@felixkubli awesome!

**Comment by VishalGulati** [comment]
Thanks @felixkubli - but how do I use your latest build? Should I delete node_modules and install ng2-bootstrap again?

**Comment by valorkin** [comment]
I need to merge and publish it, so it will be there later today
most probably as 16-12

**Comment by valorkin** [comment]
fix merged, testing and publishing now .... (should be available in couple of hours)
