### ISSUE TITLE
ModalDirective cannot be imported from location specified in Documentation

### ISSUE THREAD

**Issue by goleary** [valor-software/ngx-bootstrap#1435]
http://valor-software.com/ng2-bootstrap/#/modals

in the above link it shows you can import it using `import { ModalDirective } from 'ng2-bootstrap';`

This causes an error during the rollup step of my build process.

I  ended up having to use the following syntax for importing: `import { ModalDirective } from 'ng2-bootstrap/modal/modal.component';`

**Comment by valorkin** [comment]
ng2-bootstrap version?

**Comment by valorkin** [comment]
`ng2-bootstrap/modal` ok it means from latest

**Comment by valorkin** [comment]
any way, if it was true, AoT would be throwing issues, but it doesn't
so I need more info why it doesn't work for you
please try clean install and clean build
if it will be an issue, please drop me more details
