### ISSUE TITLE
Typeahead ngModel value

### ISSUE THREAD

**Issue by lehresman** [valor-software/ngx-bootstrap#1441]
I'm using an array of objects as my options source.  From what I can tell, it's impossible to get the full item object set as the ngModel.  My ngModel is only getting set to the typeaheadOptionField value.  Is this intended, or is there a way to have the ngModel be set to the item object?

**Comment by critchie** [comment]
If you want the entire object setup a handler for the typeaheadOnSelect event.

In your template add:
```
(typeaheadOnSelect)="typeaheadOnSelect($event)"
```

And in your component.ts:
```
typeaheadOnSelect($event) {
  // selected object is $event.item
  console.log($event.item);
}
```

**Comment by lehresman** [comment]
Yeah, that's how I'm doing it.  It just seemed more natural to be able to set it on the `ngModel`.  Thanks though!

**Comment by critchie** [comment]
General info: it is not possible to use ngModel the way you are describing.

From the angular docs:
The ngModel data property sets the element's value property and the ngModelChange event property listens for changes to the element's value.

The typeahead is using an input element of type text most likely so the value property wants a simple string.  If the typeahead were to assign the object to ngModel the input box would probably display something like "object: Object".

You might actually see just that if you leave the typeaheadOptionField empty.  I haven't tried it.

**Comment by abelardolg** [comment]
Hi,
I am using this component. 
When I type a city:
![image](https://user-images.githubusercontent.com/22522883/33929509-06498428-dfea-11e7-8e08-17462073c68f.png)

the typeahead component shows this one:
![image](https://user-images.githubusercontent.com/22522883/33929537-1f2e121a-dfea-11e7-844d-1dc451b53276.png)

Why it happens if I have this code?:
HTML: 
![image](https://user-images.githubusercontent.com/22522883/33929569-398d9342-dfea-11e7-8a25-8f627da1b37e.png)

COMPONENT.TS:
![image](https://user-images.githubusercontent.com/22522883/33929589-54169bc8-dfea-11e7-9c05-b3118dc5c6e9.png)

What's wrong?
Any help would be welcome.
Best regards and thanks in advance. :)

**Comment by Bruswei** [comment]
@abelardolg You need `[resultFormatter]="formatter"` and a formatter function to convert the result before listing it, like `formatter = (x: { name: string }) => x.name`.

Read more on [https://ng-bootstrap.github.io/#/components/typeahead/api](api)

**Comment by abelardolg** [comment]
Thanks, @Onelastfall 👍

**Comment by byhoratiss** [comment]
Sorry to ask @Onelastfall, but is this https://valor-software.com/ngx-bootstrap/#/typeahead#api-reference the right documentation of typeahead? Can't find any way to set a custom formatter. Any idea?

**Comment by Bruswei** [comment]
@byhoratiss Depends on if you are using ngx- or ng-bootstrap. [Here is the documentation for ng-bootstrap ](https://ng-bootstrap.github.io/#/components/typeahead/api). Your documentation link was for ngx-bootstrap.

[Difference between ngx and ngbootstrap](https://stackoverflow.com/questions/43758400/what-is-the-difference-between-ng-bootstrap-and-ngx-bootstrap)

**Comment by byhoratiss** [comment]
I see, I'm using ngx version, and it does not have any formatter. Thanks @Onelastfall !

**Comment by pratik97** [comment]
I am using ngx-bootstrap ,how do I pass entire object with the typeahead instead of a string?

**Comment by ZinalMehta** [comment]
I had a same doubt as @abelardolg .
but I have to pass model with id and value in ngbTypeHead and bind ngModel with object .
Is is possible by using ngbtypehead?

![productdetails](https://user-images.githubusercontent.com/41180275/42675337-34d25ab0-8691-11e8-93de-38da25b12de5.PNG)
![afterselectiongproduct](https://user-images.githubusercontent.com/41180275/42675352-3f7fd3a2-8691-11e8-940b-4b3bdb5b4920.PNG)
![coding](https://user-images.githubusercontent.com/41180275/42675357-434108a8-8691-11e8-9221-10525eae0b80.PNG)
![html](https://user-images.githubusercontent.com/41180275/42675360-46911516-8691-11e8-8d6b-66353faf8b79.PNG)

Is it possible to bind whole object with ngbtypeahed in ngModel?
