### ISSUE TITLE
Uncaught TypeError: ctorParameters.map is not a function

### ISSUE THREAD

**Issue by dreweird** [valor-software/ngx-bootstrap#1453]
I follow the instructions...and ive got an error....is there something wrong with angular cli version compatibility???

**Comment by valorkin** [comment]
please provide versions of angular-cli, angular, ng2-bootstrap
and error stack trace

**Comment by luishmcmoreno** [comment]
I had a similar error... I fixed updating angular-cli and at package.json all these libs from 2.0.0 to 2.3.1. 

```
{
    dependencies: {
        "@angular/common": "^2.3.1",
        "@angular/compiler": "^2.3.1",
        "@angular/core": "^2.3.1",
        "@angular/forms": "^2.3.1",
        "@angular/http": "^2.3.1",
        "@angular/platform-browser": "^2.3.1",
        "@angular/platform-browser-dynamic": "^2.3.1"
    }
}
```

Don't forget to update the version at angular-cli.json:
```
{
  "project": {
    "version": "1.0.0-beta.24",
    "name": "your-project"
  }
}
```

**Comment by valorkin** [comment]
drop me a note if it did not helped
