### ISSUE TITLE
Packing problem

### ISSUE THREAD

**Issue by moostafaa** [valor-software/ngx-bootstrap#1454]
I am using webpack configuration that described in this path:
https://angular.io/docs/ts/latest/guide/webpack.html

now I adde ng2-bootstrap to my project but when I tried to create a build version all angular2 files also added to my app.js file, what's wrong with this configuration or it is a bug in ng2 bootstrap?

**Comment by valorkin** [comment]
error stack trace?

**Comment by moostafaa** [comment]
There is no error, I am trying to extract vendor and polyfills scripts to separate files and any java script codes that I am writing to another script file(app.js), any thing is good until I used ng2-bootstrap in my project,
now when I wanna run build and get dest files I see that vendor scripts(such as angular) added to my app.js.

**Comment by valorkin** [comment]
I am afraid this is about webpack configuration issues
I would recommend using angular-cli
Regards
