### ISSUE TITLE
Dropdowns Bootstrap4 Alpha 6 not opening

### ISSUE THREAD

**Issue by Crigite** [valor-software/ngx-bootstrap#1458]
Bootstrap 4 requires class.show instead of class.open

**Comment by slubowsky** [comment]
Another alpha 6 issue - Looks like modal backdrop needs "show" class or it doesn't become visible.

**Comment by valorkin** [comment]
published v1.2 with update to bs4-alfa.6 and AoT fix

**Comment by stofte** [comment]
In case anyone else comes here via Google with the same issue (IE, dropdown fails to work due to incorrect class), be sure you're setting the "__theme" flag, otherwise you'll have this issue as well.

    
    <script>window.__theme = 'bs4';</script>

Maybe obviously stated somewhere in the docs, but I certainly missed it and wasted a few hours.

**Comment by valorkin** [comment]
@stofte one month ago no one was really using bs4 :)
if you have an idea where to put this in docs, I will highly appreciate it
even small PR :)

**Comment by haoweicrushu** [comment]
@stofte  really good!

**Comment by dantavo** [comment]
in my case the modal is shown but after everything is blocked I must click back on browser to navigate, otherwise everything in the website is freezed...any suggestion?

**Comment by fdm20** [comment]
I've added:

<script>window.__theme = 'bs4';</script>

However my dropdown still isn't working. :(

Any thoughts?
