### ISSUE TITLE
Typeahead - Select an active item when closing the results dropdown

### ISSUE THREAD

**Issue by koodikindral** [valor-software/ngx-bootstrap#1461]
Is it possible to automatically select a highlighted item from typeahead's results dropdown when the dropdown is closed by clicking outside of the dropdown area?

**Comment by koodikindral** [comment]
Any updates on it? :) It would be much more user-friendly with this feature.

**Comment by valorkin** [comment]
are sure it is a good UX?

**Comment by koodikindral** [comment]
Consider the possibility where there's no 100% match between the user input and predefined list of items. For example, user might enter just 3 first letters of a word. In this case, I can't get the resulting match from a typeahead. 
I thought this would solve this problem. Currently user has to select manually a specific item from a dropdown menu.

**Comment by valorkin** [comment]
ok, now seems I understood you
so if I enter 3 first letters, first mach should be active
than I press enter and gets selected 
this is perfect use case

what I thought you asked initially
I have hovered some entry and pressed tab (or esc or click away) `closing the results dropdown`
and I need to select first active match

**Comment by koodikindral** [comment]
What about selecting the first match without hitting the enter? For example moving the foucus out from typeahead input by clicking outside or another button on a web page?

**Comment by imribarr-compit** [comment]
I think that an OnBlur event should do the trick, I'm creating a PR, adding OnBlur event to typeahead component which sends the active item as the $event. Will this suffice?

**Comment by cyberdante** [comment]
Any progress on this issue?

**Comment by martadelgado** [comment]
I was looking to do the same thing. Select the highlighted item (in this case, the 'active li', which is usually the first one on the list) when you lose focus from the input- this occurs when you click outside of the input or dropdown. Any way to achieve this?

**Comment by valorkin** [comment]
I did not find similar behavoir in autoselects, I suppose this will be not obvious UX
