### ISSUE TITLE
feat(docs): fix component styling sections

### ISSUE THREAD

**Issue by seekheart** [valor-software/ngx-bootstrap#1468]
I tried the previous ticket solution but have not had any luck

`<accordion><accordion-panel [panelClass]=" 'panel-primary' "> stuff</accordion>`

does not change the color at all I've done it with `<accordion-group>` as well and I'm using bootstrap 3

**Comment by seekheart** [comment]
I tried it with `[panelClass] = " ' card-primary' " ` and it works on both BS3 and 4 but the styling is completely off, the entire accordion group becomes blue....

**Comment by seekheart** [comment]
my temp workaround was going back to BS3 and using `panelClass="panel-primary"` for now but you can still do `panelClass="card-primary"` to style the entire panel blue in BS3.

**Comment by valorkin** [comment]
`panelClass="panel-primary"` is the only correct form of binding for BS3

**Comment by tnarp** [comment]
We also find this issue in accordion styling demo.
This issue can solve through putting css to **src/styles.css** not in component css file.

**Comment by ghost** [comment]
@seekheart if you still use bootstrap 3 - you should add  `[panelClass]="panel-primary"` class (in a new ngx-bootstrap version it works). If you use bootstrap 4 - you should add `[panelClass]="bg-primary"`. Also you should change button's font color inside `"accordion-toggle"`
