### ISSUE TITLE
Version 1.1.16-11 does not have function forRoot()

### ISSUE THREAD

**Issue by tutv** [valor-software/ngx-bootstrap#1469]
I updated version to 1.1.16-11 and I was failed when I import module.

```
import {TabsModule, ModalModule} from "ng2-bootstrap";

...
 imports: [
        TabsModule.forRoot(),
        ModalModule.forRoot()
    ],
```

And I found out that they don't have `forRoot()` and I trying to delete function `forRoot()` but it still fails.

```
 imports: [
        TabsModule,
        ModalModule
    ],
```
I've downgraded version to 1.1.16-10 and it work.

**Comment by valorkin** [comment]
seems there are were some issue with typings, fixed in v1.1.17
