### ISSUE TITLE
Tooltips Bootstrap4 Alpha 6 not showing

### ISSUE THREAD

**Issue by vicacid** [valor-software/ngx-bootstrap#1471]
Tooltips in Bootstrap4 Alpha 6 not showing.

**Comment by valorkin** [comment]
they had a breaking changes, a will release v18 with fix today

**Comment by vicacid** [comment]
I see. Thank you.

**Comment by valorkin** [comment]
will be fixed with https://github.com/valor-software/ng2-bootstrap/pull/1485

**Comment by valorkin** [comment]
published v1.2 with update to bs4-alfa.6 and AoT fix
