### ISSUE TITLE
ng2-bootstrap module imports are undefined on child route page refresh

### ISSUE THREAD

**Issue by veliancreate-zz** [valor-software/ngx-bootstrap#1475]

**Comment by valorkin** [comment]
it is more related to router than ng2-bootstrap
especially if your child routes are lazy loaded
please provide more info (versions) of libs
and error stack

**Comment by veliancreate-zz** [comment]
Thanks @valorkin. It looks like it was due to an old dist file not being updated on ng serve after updating angular to 2.4.2. Deleting dist and rebuilding appeared to fix.
