### ISSUE TITLE
Automated build failing after new version (1.1.17)

### ISSUE THREAD

**Issue by Dashue** [valor-software/ngx-bootstrap#1476]
Hey,

Thanks for your continuing work on ng2-bootstrap, it's much appreciated!

We've realized our automated build started to break after the new release. 
1.1.16 is working fine, 1.1.17 gives:

Error on fetch for ng2-bootstrap/sortable.js at file:///<redact>/node_modules/ng2-bootstrap/sortable.js
Error: ENOENT: no such file or directory, open '<redact>/node_modules/ng2-bootstrap/sortable.js'

Do we need to adjust our build, or is this a known issue which will be resolved automatically?
We've fixed our dependency to 1.1.16 for now.

Thanks

**Comment by jitsmaster** [comment]
I am getting the same error too. Looks like ng modules are being treated as individual files instead of loading index.js. Any help is greatly appreciated

**Comment by jitsmaster** [comment]
Work around:

Instead of importing ng2-bootstrap, I import individual modules

```
import { TimepickerModule} from 'ng2-bootstrap/timepicker';
import { Positioning } from "ng2-bootstrap/positioning/ng-positioning";
```

If you use systemjs, make sure also add individual packages:

```
		'ng2-bootstrap/positioning': { main: 'index.js', defaultExtension: 'js' },
		'ng2-bootstrap/timepicker': { main: 'index.js', defaultExtension: 'js' },
```

This workaround works for both JIT and AOT.

Hopefully this help you get on with your project until the team has a final fix.

**Comment by valorkin** [comment]
Thanks ;)
First thing, please check migration notest 16->17 
https://github.com/valor-software/ng2-bootstrap/blob/development/CHANGELOG.md

and please compare to sample repository we have for system.js, guys saying this config works fine for JIT and AOT and event with angular-seed
https://github.com/valor-software/angular2-quickstart/blob/master/systemjs.config.js

**Comment by jitsmaster** [comment]
Thank you for printing out the forRoot part, all I needed to make the module work in root level

**Comment by valorkin** [comment]
@Dashue did it fixed your problem?

**Comment by valorkin** [comment]
drop me a note if it did not helped
