### ISSUE TITLE
Version 1.1.16 Fails when compiling wth the aot compiler "ngc" 

### ISSUE THREAD

**Issue by budcribar** [valor-software/ngx-bootstrap#1480]
Error: Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 7:12 in the original .ts file), resolving symbol Ng2BootstrapConfig.theme in C:/Users/budcr/Desktop/Code/HPSD/SureCheckSPA/node_modules/ng2-bootstrap/components/ng2-bootstrap-config.d.ts, resolving symbol TypeaheadContainerComponent in C:/Users/budcr/Desktop/Code/HPSD/SureCheckSPA/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts, resolving symbol TypeaheadContainerComponent in C:/Users/budcr/Desktop/Code/HPSD/SureCheckSPA/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts

**Comment by valorkin** [comment]
yep, there are very such issue please read migration notes in changelog and update to v1.1.17
