### ISSUE TITLE
Error in carousel component when building using webpack-starter from angularclass

### ISSUE THREAD

**Issue by andreyjkee** [valor-software/ngx-bootstrap#1482]
Hi. I am using starter: https://github.com/AngularClass/angular2-webpack-starter
When i execute command `npm run build:prod` i receive error:

> Error in bail mode: [at-loader] compiled\node_modules\ng2-bootstrap\carousel\carousel.component.ngfactory.ts:34:20
>     Supplied parameters do not match any signature of call target.

**Comment by valorkin** [comment]
Please show how do you call\use carousel
thing is: this is a typescript typecheck issue, and usually it means that it was called incorrectly
ng2-bootstrap should be v1.1.17

**Comment by andreyjkee** [comment]
I use only ModalModule and ToolTip module, i don't call Carousel.
ng2-bootstrap version is 1.1.17

**Comment by andreyjkee** [comment]
I think it is because compiled folder (from aot build) is analyzed by typescript loader, it is a webpack-starter trouble, not ng2-bootstrap
