### ISSUE TITLE
1.1.17 AOT Failing with sortable component

### ISSUE THREAD

**Issue by DanielMcAssey** [valor-software/ngx-bootstrap#1483]
AOT Compilation was working on 1.1.16-11 its now failing when I upgraded to 1.1.17 with the following error:
`Error in bail mode: [at-loader] compiled\node_modules\ng2-bootstrap\sortable\sortable.component.ngfactory.ts:390:44
    Property 'showPlaceholder' is private and only accessible within class 'SortableComponent'.`

**Comment by valorkin** [comment]
thank you, strange that it was not hit by tslint(codelyzer) and my AoT build
