### ISSUE TITLE
Importing Ng2BootstrapModule.forRoot() in SharedModule throw BrowserModule error

### ISSUE THREAD

**Issue by gepisolo** [valor-software/ngx-bootstrap#1486]
I've upgraded some npm packages and after that the Application stopped working complaining: **BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module...** .After some crazy debug (I was NOT trying to import BrowserModule in any other Module), I made a text search in all my node_modules packages, and the only one containing a ref to BrowserModule was in ng2-bootstrap (sortable). So I changed my import from

Ng2BootstrapModule.forRoot()

to

DropdownModule.forRoot()  

(for now I just used dropdows) and the problem is gone.

**Comment by valorkin** [comment]
Thanks for pointing, missed this initially
and BTW using only what you need is a much better approach
issue in SortableModule
