### ISSUE TITLE
Modal Dialog problems with Bootstrap 4 Alpha 6

### ISSUE THREAD

**Issue by caglarturkurka** [valor-software/ngx-bootstrap#1493]
Modal Dialog can not be opened with bootstrap 4 alpha 6.Please tell me how can I solve this problem ? Thanks

**Comment by valorkin** [comment]
add `<script>window.__theme = 'bs4';</script>` on top of index.html body

**Comment by valorkin** [comment]
I need to provide a smarter way of theme switching >.<

**Comment by caglarturkurka** [comment]
Thank you for your attention.I will wait for your new updating about this problem.

**Comment by valorkin** [comment]
Try a hack I have provided above, it works for me :)

**Comment by pdenomme** [comment]
So what's the reason why that hack works?  I was having an issue with the modal not visible until I added that hack.  With it, the modal shows just fine now.

**Comment by valorkin** [comment]
@pdenomme it is not actually a `hack`, this is was a temporary solution to switch themes in ng2-bootstrap
in ng1 it was much easier

**Comment by pdenomme** [comment]
ok, thanks for the info.
