### ISSUE TITLE
Typeahead not appearing with Bootstrap Alpha 6

### ISSUE THREAD

**Issue by slubowsky** [valor-software/ngx-bootstrap#1494]
Looks like even with version 1.2.0 Typeahead not appearing using Bootstrap alpha 6

**Comment by valorkin** [comment]
it is actually working http://valor-software.com/ng2-bootstrap/index-bs4.html#/typeahead
but you need this `<script>window.__theme = 'bs4';</script>` on top of index.html body

**Comment by slubowsky** [comment]
@valorkin. I actually have that already. I've had that forever. The other Alpha 6 problems I noticed are fixed (problems with modals and dropdowns are the ones I saw), but this one is still there. When I look at the demo site I'm still getting alpha 5 so no proof there yet...

![image](https://cloud.githubusercontent.com/assets/270589/21937759/78411a52-d986-11e6-95a9-02d0575c1f8b.png)

If I edit the demo page in developer tools and add a link tag to load alpha 6 the typeahead does stop working once the alpha 6 css is applied.

**Comment by valorkin** [comment]
damn, you are right!

**Comment by valorkin** [comment]
aha, found where it is broken - fixing
any other issues with alfa.6?

**Comment by slubowsky** [comment]
All the ones I've see so far besides this have already been fixed. I'll let you know if I see any others (I'm not doing exhaustive testing, I'm just bumping into problems as I work on my app)
Thanks!

**Comment by valorkin** [comment]
published as v1.2.1 
http://valor-software.com/ng2-bootstrap/index-bs4.html#/typeahead

join slack and drop me a note if something will be urgent
