### ISSUE TITLE
typeahead dropdown doesn't hide on blur when item is hovered over

### ISSUE THREAD

**Issue by hafarey** [valor-software/ngx-bootstrap#1495]
I updated from 1.1.16 to 1.2.1 and encountered this new behavior.  It can be reproduced on the current demo site (reproducible as of 13 January 2017).

**Steps**
1.  On the typeahead page of the ng2-bootstrap demo site, go to the *Static array* section and enter `new`
(A few state names should appear in the dropdown.)

![image](https://cloud.githubusercontent.com/assets/17915941/21951104/b352db50-d9b6-11e6-8a5a-aa76323fae67.png)

2.  Make sure __not__ to hover the mouse anywhere over the dropdown list.  Then click anywhere outside the input box and the dropdown.
(The dropdown should go away.)
3.  Repeat Step 1.
4.  This time around, hover the mouse cursor over any of the state names in the dropdown.
5.  Click anywhere outside the input box and the dropdown.

**Behaviors**
After Step 5:
* In 1.1.16, the dropdown goes away.
* In 1.2.1, the dropdown does __not__ go away.

I can't find notes on whether the 1.2.1 behavior is intended as designed.  As a user, however, I prefer 1.1.16 behavior as the better one.  Hovering over an item in the typeahead dropdown should not prevent the dropdown from going away on mouse blur.

It seems that in 1.2.1, `TypeaheadDirective.onBlur()`, the `this._container.isFocused` property is returning `true` when the component should no longer be in focus.

**Comment by valorkin** [comment]
Awesome reproduce steps, I have reproduced an issues, so I will be able to fix it fast
Thank you

**Comment by valorkin** [comment]
fix not yet pushed, but demo page is updated
please check: http://valor-software.com/ng2-bootstrap/#/typeahead#static
