### ISSUE TITLE
Errors breaking that ng2-boostrap with a angular2 5min auto

### ISSUE THREAD

**Issue by maissani** [valor-software/ngx-bootstrap#150]
@valorkin moment.js still having 
errors : 
## In console

[0] node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: Cannot re-export name that is not defined in the module.
[0] node_modules/ng2-bootstrap/components/timepicker/timepicker.component.ts(108,5): error TS7027: Unreachable code detected.
## And on browser console:

undefined:1 Uncaught (in promise) TypeError: object is not a constructor(…)
moment:1 Uncaught SyntaxError: Unexpected token <__exec @ system.src.js:1374entry.execute @ system.src.js:3300linkDynamicModule @ system.src.js:2921getModule @ system.src.js:2889(anonymous function) @ system.src.js:2925(anonymous function) @ date-formatter.js:1linkDynamicModule @ system.src.js:2921getModule @ system.src.js:2889(anonymous function) @ system.src.js:2925(anonymous function) @ datepicker-inner.js:1linkDynamicModule @ system.src.js:2921getModule @ system.src.js:2889(anonymous function) @ system.src.js:2925(anonymous function) @ datepicker.js:1linkDynamicModule @ system.src.js:2921getModule @ system.src.js:2889(anonymous function) @ system.src.js:2925(anonymous function) @ datepicker-popup.js:1linkDynamicModule @ system.src.js:2921getModule @ system.src.js:2889(anonymous function) @ system.src.js:2925(anonymous function) @ datepicker.js:1linkDynamicModule @ system.src.js:2921getModule @ system.src.js:2889(anonymous function) @ system.src.js:2925(anonymous function) @ ng2-bootstrap.js:1linkDynamicModule @ system.src.js:2921link @ system.src.js:2764execute @ system.src.js:3096doDynamicExecute @ system.src.js:715link @ system.src.js:908doLink @ system.src.js:569updateLinkSetOnLoad @ system.src.js:617(anonymous function) @ system.src.js:430run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494(anonymous function) @ angular2-polyfills.js:243run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305
angular2-polyfills.js:138 Uncaught SyntaxError: Unexpected token <
    Evaluating http://localhost:3000/moment
    Error loading http://localhost:3000/app/main.js

**Comment by valorkin** [comment]
ok, I will say last time, ng2 is not working with ts 1.8 
If you ask, please read answer
https://github.com/angular/angular/issues/6468

**Comment by valorkin** [comment]
nothing to do with moment.js
