### ISSUE TITLE
Do not display the carousel controls

### ISSUE THREAD

**Issue by sleptsov** [valor-software/ngx-bootstrap#1500]
For carousel controls `<a>` tag have `class="left carousel-control-prev"`, but no controls are shown, no styles. If I remove `-prev` from class, controls have their styles and everything is okay. Same issue on https://valor-software.com/ng2-bootstrap/#/carousel

Why? Only bootstrap/4.0.0-alpha.6 have such `class="left carousel-control-prev"`, and what about lower versions? Or it is bootstrap issue?

ng2-bootstrap version 1.2.1
bootstrap/4.0.0-alpha.4

**Comment by valorkin** [comment]
it is breaking change between alfa.5 to alfa.6
this is why I have to bump from 1.1.* to 1.2.*
https://github.com/twbs/bootstrap/releases
