### ISSUE TITLE
feat(popover): don't show popover if content is undefined

### ISSUE THREAD

**Issue by serddmitry** [valor-software/ngx-bootstrap#1504]
**UPDATE**: it should be like with tooltips, if a content is not defined, it should be displayed

In our app we show popovers if the popover content is present, which is not always the case.
Would be cool to be able to disable popover through a property. As a workaround, I'm using 2 *ngIf - one with popover and one without.

**Comment by valorkin** [comment]
you can control it via `[isOpen]` popover property

**Comment by ersimont** [comment]
Either I don't understand the request or the response. Let me explain my situation, which I thought matches what @serddmitry was requesting:

I have a number of components displayed using `*ngFor`. Some of them should have popovers, some should not, depending on their value (let's call that value `item.popoverText`). Currently if `popoverText` is undefined, the element has a tiny blank popover. Is there a way to disable that, so there is no popover at all in such a case?

**Comment by valorkin** [comment]
aha, ok
@ersimont 
it should be like with tooltips, if a content is not defined, it should be displayed

**Comment by RohanGovande** [comment]
We are currently using popover version 1.6.3 and can't update it fr some other dependencies, do we have any alternative for this that would work in older version.
