### ISSUE TITLE
open Modal triggers route redirect

### ISSUE THREAD

**Issue by benjamindamm** [valor-software/ngx-bootstrap#1506]
I have a strange error. No message is displayed. Since the update from 1.0.6 to 1.2.1, a redirect is triggered when the modal is opened. No consoles message nothing.

Any idea what I can do to get further information about my error?

**Comment by valorkin** [comment]
Modal opener element? If it is <a> than it is expected behavior. I am trying to remove any event changers, like prevent defaults

**Comment by benjamindamm** [comment]
Yes it was the opener element. I didn't looked after that, cause I was properly working before. Please write it down in your changelog.

Thank you for helping.

**Comment by valorkin** [comment]
Thanks
