### ISSUE TITLE
Appending tooltip to body is not working.

### ISSUE THREAD

**Issue by webcat12345** [valor-software/ngx-bootstrap#1510]
I am using tool tip inside table. Here is code.

```
          <td [tooltip]="reason.value"
              container="body">
            {{reasonFieldWrapper(reason.value)}}
          </td>
```

But after running project tooltip is not appending to the body, it is appending to the td.

Here is element tree after rendering.

![element-tree](https://cloud.githubusercontent.com/assets/19761422/21996620/72e6c122-dc2b-11e6-8906-aea23fa0b713.jpg)

**Comment by webcat12345** [comment]
Just solved this issue my self using `<span >` tag inside `<td>`. Like this 
```
          <td>
            <span [tooltip]="reason.value"
            container="body">{{reasonFieldWrapper(reason.value)}}</span>

          </td>
```
But I don't know why it is working and why `<td>` is not working. Anyone please help. Thanks.

**Comment by valorkin** [comment]
It is very interesting! Holder element should not affect logic, hm

**Comment by webcat12345** [comment]
Even if I use `<span>` tag or `<td>` for it, `<tooltip>` is not appending to `<body>`. Is it related with **Component in Angular2**? Why it does not find out `<body>` Correctly?
I use `<span>` tag because it makes table **Stable** when showing tooltip.
If there is anyway to append tooltip to `<body>` please let me know thanks.

**Comment by webcat12345** [comment]
` "ng2-bootstrap": "^1.1.16"`

**Comment by valorkin** [comment]
This is this the issue, please update to ng v2.3+ and latest ng2 bootstrap

**Comment by valorkin** [comment]
closing this, because container="body" was added in 1.2+
if you will have any additional questions drop me a note

**Comment by webcat12345** [comment]
Thank you very much! Its working.

**Comment by valorkin** [comment]
awesome! glad to hear it
it works same way for popovers, and will work for all other `popup` components later

**Comment by webcat12345** [comment]
Cool Stuff. Will definitely use this component.

**Comment by IntelligaiaVivek** [comment]
Hi  tooltip is not appending to the body, As container="body" not working inside <ng-template> 
<ng-template #saasOrdView>
                        <span *ngIf="i.id != 1">
                            <a  container="body" tooltip="This feature is not yet available" placement="left" [isDisabled]="!i.showTooltip" href="javascript:void(0);"
                                class="{{i.disabledLinkClass}}">
                                <i *ngIf="i.ImageIcon" class="{{i.class}}"></i>{{i.label}}
                            </a>
                        </span>
                    </ng-template>

**Comment by GopiAnnan** [comment]
Still its not working with version 1.6.6 as well.

**Comment by valorkin** [comment]
it was so long ago...
latest version is 1.9.3 https://valor-software.com/ngx-bootstrap/#/
and @next version is beta.7 already 
works in both of them http://ngx-bootstrap.surge.sh/#/
