### ISSUE TITLE
Accordion: use of buttons in header

### ISSUE THREAD

**Issue by negberts** [valor-software/ngx-bootstrap#1512]
When we use a button or any other element that has a (click) event in the header, the click event of the accordion has preference over the click event of the sub element. Are we doing anything wrong or is this just not possible?

**Comment by valorkin** [comment]
Actually I want to replace usage of any `<a>` tags in templates
because it forces me to use preventDefault
and leads to issues like yours ;(

**Comment by valorkin** [comment]
pls check v1.2.5

**Comment by negberts** [comment]
Did you try to fix it? Because we can still not use anything like checkboxes or buttons in the accordeon header @valorkin 

Or was your comment meant like: you should not try to do what you want :)

**Comment by bradenclapp** [comment]
@valorkin I am not entirely sure what the fix would be? I don't want to disable the clicking of the header to drop down the accordion but my clicking of my sub element causes it to drop down. 

UPDATE: 
``` 
<a href dropdownToggle  (click)="$event.stopPropagation(); false;" dropdown class="fa-stack fa-lg">

**Comment by valorkin** [comment]
@bradenclapp isolate your events propagation where you don't need it
