### ISSUE TITLE
feat(typeahead): add matching function "Start with"

### ISSUE THREAD

**Issue by rongchaua** [valor-software/ngx-bootstrap#1513]
Hi all,
I would like to ask if we can set any option so that the matching function works by "Start withs" instead of "Contains"?

For example, in the data source of type ahead I have following entries

aaa
bbaaaff
cccadd

If I type "a", all entries will be suggested. I would like to show only "aaa" because it start withs "a" and the others don't.

Thank you.

**Comment by YevheniiaMazur** [comment]
This looks like a part of https://github.com/valor-software/ngx-bootstrap/issues/2514
