### ISSUE TITLE
1.2.2 AOT Failing with sortable component 

### ISSUE THREAD

**Issue by sublime392** [valor-software/ngx-bootstrap#1514]
Property 'items' is private and only accessible within class 'SortableComponent'.

**Comment by Torqode** [comment]
AOT is also failing in the SortableComponent due to the mouseleave event not passing a DragEvent to the event handler.

template:  `(mouseleave)="resetActiveItem()"`

`public resetActiveItem(event: DragEvent): void {
    this.cancelEvent(event);
    this.activeItem = -1;
  }
`

**Comment by valorkin** [comment]
Fixed in v1.2.4
