### ISSUE TITLE
Deprecated tooltipHtml 

### ISSUE THREAD

**Issue by v-gonta** [valor-software/ngx-bootstrap#1518]
Apparently tooltipHtml and other tooltip features have been deprecated.

I was wondering, is this something temporary or permanent? 
What was your reasoning behind removing tooltipHtml and using innerHtml in template instead?

Thank you.

**Comment by valorkin** [comment]
They were replaced with more generic and proper solution
http://valor-software.com/ng2-bootstrap/#/tooltip#dynamic-content

PS: I will think of returning it a bit later
but in general using innerHtml in components is not angular 2 way
and has some restrictions, etc.

**Comment by valorkin** [comment]
If you will have any additional questions, I am usually available in slack
