### ISSUE TITLE
typeahead positioning the dropdownlist

### ISSUE THREAD

**Issue by prakashslm** [valor-software/ngx-bootstrap#1520]
is there any possibility to add a functionality same like html **select** tag position the dropdownlist based on the available height of the window.

thanks,
Prakash

**Comment by valorkin** [comment]
Yes, it is in roadmap
Can not say anything on timeframe unfortunately

But I want to achieve mobile friendly behavior for sure!

**Comment by 1-0-1** [comment]
+1  This is really becoming a problem.
