### ISSUE TITLE
Tooltip/Popover not getting disappeared

### ISSUE THREAD

**Issue by mshanbhag01** [valor-software/ngx-bootstrap#1523]
I have used the ng2-bootstrap tooltip to be shown conditionally as 
<input type="text" tooltip="Name Required" triggers="focus hover" [isDisabled]="!(!name.valid && name.errors.required && (name.dirty || name.touched))"
this works fine when user deletes the text from the input,. But if the error tooltip is open and user starts typing in, the tooltip does not disappear immediately

**Comment by IlyaSurmay** [comment]
Can you clarify this a little bit and provide plunkr/stackblitz with reproduction if this is still relevant?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IlyaSurmay** [comment]
Closed as can't reproduce (v2.0.0-beta.8), will be reopened if we have sample to reproduce
