### ISSUE TITLE
Datepicker - datepickerMode doesn't work

### ISSUE THREAD

**Issue by beabri** [valor-software/ngx-bootstrap#1524]
[datepickerMode]="'year'" displays months and [datepickerMode]="'month'" displays days.
If I use [datepickerMode]="'year'" and click on one month, then windows with days opens, and that's not what I expect.

**Comment by valorkin** [comment]
known issue, duplicate of another issue
working on it

**Comment by beabri** [comment]
Could you please give me the URL of the issue? Thanks.

**Comment by valorkin** [comment]
I am not fixing current version, I already rewrote it from zero. Nearest week I am merging new Typeahead and then new datepicker

**Comment by ilacomp** [comment]
Still not fixed. Could you please provide some info about when this functionality will be fixed?
