### ISSUE TITLE
Tooltip not positioned correctly when loading dynamic content

### ISSUE THREAD

**Issue by emise** [valor-software/ngx-bootstrap#1528]
When I have something like this -

```
<template #tooltipTemplate >
  <div *ngFor="let p of data">
    <i [ngClass]="p.property1" [style.color]=" p.property2"></i>
    <span class="class1">{{p.value}}</span>
  </div>
</template>
```

the tooltip is not positioned at the right place; instead it's shifted over to the right and down. Somehow it's not getting the size of the tooltip until after it opens, so the offsets are wrong.

I am running in hybrid mode; Angular 2 downgraded component on top of Angular 1.4.

**Comment by valorkin** [comment]
it two words it is an issue from ngUpgrade
please check this issue https://github.com/valor-software/ng2-bootstrap/issues/1398

if it will not help you, please create issue in angular repo
and link it to #1398

**Comment by eduardofila79** [comment]
@emise were you able to fix the issue? any hacks? I'm experiencing the same issue.
Greatly appreciated.

**Comment by emise** [comment]
@eduardofila79 I think I ended up abandoning the effort, but if I remember correctly I was able to get kind of a workaround by using CSS to globally position the tooltip.

**Comment by eduardofila79** [comment]
That's what i was thinking on doing.
Thanks!
