### ISSUE TITLE
TypeError in ng2-bootstrap.umd.min.js

### ISSUE THREAD

**Issue by freddiefish** [valor-software/ngx-bootstrap#1531]
Running Angular 2.4.4 and ng2-bootstrap 1.2.6, I have this error. Can anyone tell me what to do? Thank you very much! Fred
```
ng2-bootstrap.umd.min.js:10 Uncaught TypeError: Cannot read property 'Output' of undefined
    at Object.<anonymous> (ng2-bootstrap.umd.min.js:10)
    at t (ng2-bootstrap.umd.min.js:1)
    at Object.t (ng2-bootstrap.umd.min.js:9)
    at t (ng2-bootstrap.umd.min.js:1)
    at Object.i.__decorate.r (ng2-bootstrap.umd.min.js:10)
    at t (ng2-bootstrap.umd.min.js:1)
    at Object.<anonymous> (ng2-bootstrap.umd.min.js:18)
    at t (ng2-bootstrap.umd.min.js:1)
    at ng2-bootstrap.umd.min.js:1
    at ng2-bootstrap.umd.min.js:1
    at ng2-bootstrap.umd.min.js:1
    at ng2-bootstrap.umd.min.js:1
```

**Comment by valorkin** [comment]
That's uncommon, can you provide a Repo so I could reproduce.

PS if you are just starting, switch to angular-cli

**Comment by moutono** [comment]
Found the issue? Im getting the same problem.
ng2-bootstrap.umd.min.js 
JavaScript runtime error: Unable to get property 'Output' of undefined or null reference

**Comment by valorkin** [comment]
need a repo, to reproduce

**Comment by freddiefish** [comment]
here is the repo:
https://github.com/Open-Antwerpen/open-bestuur/tree/isolate-bug

**Comment by Benjman** [comment]
+1

**Comment by negberts** [comment]
Here's a plunker: https://plnkr.co/edit/DepB3f7fVZRI79VRXtOL?p=preview

Edge gives the output error, Firefox something about core_1 is undefined

**Comment by RodrigoMattosoSilveira** [comment]
Hello - I have a very simple [plunker](https://plnkr.co/edit/p4IgPUrbwX1NhlrGPeqq?p=preview) using modal that works with ng2-bootstrap@1.1.16, fails with ng2-bootstrap@1.1.17 and ng2-bootstrap@1.3.3. I did not try with any other versions.

PS.: If you look at the plunker you will notice that app.module imports DatepickerModule which, if removed, causes the plunker to break.

**Comment by freddiefish** [comment]
Any updates on this error? I run Angular 2.4.4. Still get a
`Uncaught TypeError: Cannot read property 'Output' of undefined`
Thank you, Fred

**Comment by valorkin** [comment]
This is your build system issue, I have seen this issue couple of times, bit clean install and update to latest angular usually helps

**Comment by valorkin** [comment]
here is plunker https://plnkr.co/edit/kYUonyMQkoAp4mLvxlsR?p=preview
working fine with 1.3.3
thing is:
- you need to call .forRoot()
- updated version of typescript, zone.js, reflect metadata

**Comment by ttchongtc** [comment]
Still getting the same issue after following your instruction. Here's my package.json.

{
  "version": "1.0.0",
  "name": "opengamelistwebapp",
  "private": true,
  "dependencies": {
    "@angular/common": "2.4.4",
    "@angular/compiler": "2.4.4",
    "@angular/core": "2.4.4",
    "@angular/forms": "2.4.4",
    "@angular/http": "2.4.4",
    "@angular/platform-browser": "2.4.4",
    "@angular/platform-browser-dynamic": "2.4.4",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.4.4",
    "core-js": "^2.4.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "^0.19.37",
    "typings": "^1.3.2",
    "zone.js": "0.8.4",
    "moment": "2.17.1",
    "ng2-bootstrap": "1.4.0"
  },
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-clean": "^0.3.2",
    "gulp-concat": "^2.6.0",
    "gulp-less": "3.3.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-typescript": "^2.13.6",
    "gulp-uglify": "^2.0.0",
    "typescript": "2.2.1"
  },
  "scripts": {
    "postinstall": "typings install dt~es6-shim --global"
  }
}

**Comment by GopiAnnan** [comment]
I do have the same kind issue, but at Runtime, using Angular Cli and ngx bootstrap with .forroot().
