### ISSUE TITLE
(question)Typeahead: fire typeaheadOnSelect when ngModel set with code

### ISSUE THREAD

**Issue by critchie** [valor-software/ngx-bootstrap#1532]
Would there be any issues in making the typeaheadOnSelect event fire if I set ngModel with code?

```
<input type="text"
    name="search"
    class="form-control"
    style="width: 20em;"
    [(ngModel)]="term"
    [typeahead]="filterByName"
    [typeaheadOptionField]="'name'"
    [typeaheadWaitMs]="300"
    (typeaheadOnSelect)="filterByNameOnSelect($event)"
    autocomplete="off">
```

So when I do this:
```
this.term = 'Ritchie';
```

The `filterByNameOnSelect($event)` would get called.

**Comment by valorkin** [comment]
You can use (ngModelChange), it will do the trick

**Comment by critchie** [comment]
ngModelChange fires the event for every single key press which is not the behavior I need.  Also when the user selects an item from the list the ngModelChange event fires twice.  I can only assume the component is setting the model twice behind the scenes.

I have a work around.  But it feels like it would be cleaner if the typeahead component handled it.  Others may disagree.  There would be an issue of what to do if the value is not found in the list.  And what to do if the list is generated async.

The more I think about it, this may not be a typeahead concern and what I did may be the way to handle it.  But it would be worth considering the question: What does the component need to do if the ngModel is set in code?
