### ISSUE TITLE
Error by import { ComponentsHelper } from 'ng2-bootstrap'; has no exported member 'ComponentsHelper'.

### ISSUE THREAD

**Issue by A50** [valor-software/ngx-bootstrap#1533]
Hello! My application uses angular 2.4 and "ng2-bootstrap": "^1.2.6".
After update from ng2-bootstrap 1.1.16 to 1.2.6, i am received the error 

> has no exported member 'ComponentsHelper'.

Please tell me How to fix this error
Thank's

**Comment by hackermanmx** [comment]
I'm having the exact issue, no luck yet.

**Comment by A50** [comment]
@DeeNeon I solved this problem by removing 'ComponentsHelper' and did everything according to the new documentation https://valor-software.com/ng2-bootstrap/#/
each component must be declared in app.module.ts in section
`@NgModule({
    imports: [DropdownModule.forRoot(),ModalModule.forRoot(),TabsModule.forRoot(), ....`

**Comment by valorkin** [comment]
Yep, it is in change log. Migration from 1.1 to 1.2 version.
I have completely rewrote dynamic injection and removed hacky component helper
