### ISSUE TITLE
Extracting templates into separate files

### ISSUE THREAD

**Issue by DanielKucal** [valor-software/ngx-bootstrap#1534]
What do you think about extracting templates into separate .component.html files?
For now when someone i.e. extends any ng2-bootstrap component then it's necessary to copy the whole template (if it's supposed to be used) and some files are getting too big. I could make a PR if you appreciate this idea.

**Comment by valorkin** [comment]
I really appreciate it, but not sure ngc (angular-cli) support this.

**Comment by valorkin** [comment]
I am working on template-loader, it will treat components as templates
it is needed for a lot of things... like separate bs3\bs4 themes
modal service etc

**Comment by IlyaSurmay** [comment]
Done in #2602
