### ISSUE TITLE
Build failed: handler is not a function

### ISSUE THREAD

**Issue by DanielKucal** [valor-software/ngx-bootstrap#1535]
I tried to compile clear copy of development branch, but I've got an error:

> λ npm run build
> 
> > ng2-bootstrap-base@1.2.6 build D:\www\angular2\ng2-bootstrap
> > ngm build -p src --clean
> 
> [02:55:56] Clean dist folders [started]
> [02:55:56] Cleaning dist [started]
> [02:55:56] Cleaning dist [completed]
> [02:55:56] Clean dist folders [completed]
> [02:55:56] Copy md files and license [started]
> [02:55:56] Copy md files and license [completed]
> [02:55:56] Build package.json files [started]
> [02:55:56] Build package.json files [completed]
> [02:55:56] Build projects [started]
> [02:55:56] Building ng2-bootstrap (src) [started]
> [02:56:15] Building ng2-bootstrap (src) [completed]
> [02:56:15] Build projects [completed]
> [02:56:15] Bundling umd version [started]
> [02:56:15] Bundling ng2-bootstrap [started]
> [02:56:16] Bundling ng2-bootstrap [failed]
> [02:56:16] Bundling umd version [failed]
> 
> handler is not a function

Windows 10, node v6.9.4. What's the problem?

**Comment by valorkin** [comment]
Oh, please move this issue to npm-submodules repo. To be honest I have no idea because I don't use windows, I try to investigate on Monday

**Comment by DanielKucal** [comment]
The same on Ubuntu...

> root@c671d0baaf6d:/mnt/www/angular2/ng2-bootstrap# node -v
> v6.9.4
> root@c671d0baaf6d:/mnt/www/angular2/ng2-bootstrap# npm run build
> 
> > ng2-bootstrap-base@1.2.6 build /mnt/www/angular2/ng2-bootstrap
> > ngm build -p src --clean
> 
> [21:59:55] Clean dist folders [started]
> [21:59:55] Cleaning dist [started]
> [21:59:59] Cleaning dist [completed]
> [21:59:59] Clean dist folders [completed]
> [21:59:59] Copy md files and license [started]
> [21:59:59] Copy md files and license [completed]
> [21:59:59] Build package.json files [started]
> [21:59:59] Build package.json files [completed]
> [21:59:59] Build projects [started]
> [21:59:59] Building ng2-bootstrap (src) [started]
> [22:00:29] Building ng2-bootstrap (src) [completed]
> [22:00:29] Build projects [completed]
> [22:00:29] Bundling umd version [started]
> [22:00:29] Bundling ng2-bootstrap [started]
> [22:00:31] Bundling ng2-bootstrap [failed]
> [22:00:31] Bundling umd version [failed]
> 
> handler is not a function

https://github.com/valor-software/npm-submodules/issues/10
