### ISSUE TITLE
Tooltip - Performance

### ISSUE THREAD

**Issue by sapiraz** [valor-software/ngx-bootstrap#1536]
In my app I can often have over 1000 tooltips on my page,
And in the current state, it seems to get really laggy.

Perhaps have a Tooltip service that listens to mouse hover events and displays tooltips wherever you need to instead of creating more and more listeners?

**Comment by valorkin** [comment]
Nice edge case, I will think how to overcome this

**Comment by valorkin** [comment]
BTW I would love to look on this crazy page :D

**Comment by syrianadus** [comment]
any plan for this?

**Comment by valorkin** [comment]
I will get here but not sure when

**Comment by valorkin** [comment]
tried several options, with lazy injection and so on
no reasonable changes in performance

amount of listeners, can not be reduced Unfortunately (at least at the moment)

**Comment by jayparmar** [comment]
I hope thing gets fixed early. :(

**Comment by valorkin** [comment]
performance will be one of the main prios for v2 of ngx-bs
we actually already did improvement to registering event handlers in v1.9.1
but some changes require breaking changes :(

**Comment by jayparmar** [comment]
its ok we have moved to another third party tooltip provider which works well !!

**Comment by IlyaSurmay** [comment]
Is this still actual? Tested it [here](https://stackblitz.com/edit/ngx-bootstrap-stack-dyxact?file=app/app.component.html) with 2000 tooltips, no lags. Closing it for now.

**Comment by jgritten** [comment]
based off llyaSurmay's mock up, i've constructed something close to what im seeing [here](https://stackblitz.com/edit/ngx-bootstrap-tooltip-vs-title).

the difference between when the table is using the tooltip vs a simple title is obvious. Please reopen

**Comment by Neill83** [comment]
In the newest version of ngx-bootstrap it **LAGS** as hell... **PLEASE** reopen

**Comment by beeing** [comment]
Just watched this - the answer is in the video https://youtu.be/Tlmx1PbP8Qw?t=761

Hope this helps
