### ISSUE TITLE
angular-cli bootstrap installation instructions

### ISSUE THREAD

**Issue by Janzelf** [valor-software/ngx-bootstrap#1537]
npm ng-bootstrap -v: 4.0.5
angular-cli: 1.0.0-beta.26
The installation works OK. However subsequent initial ng test fails:
        'alert' is not a known element:
        1. If 'alert' is an Angular component, then verify that it is part of this module.
        2. If 'alert' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. 
("
          {{title}}
        </h1>
        [ERROR ->]<alert type="success">hello</alert>
        "):
I'm still trying to figure out how/where to fix that. Would be nice if one more step could be added to the installation instructions.

**Comment by valorkin** [comment]
Have you added AlertModule.forRoot()?
Into app module imports?

**Comment by Janzelf** [comment]
Yes I did
![image](https://cloud.githubusercontent.com/assets/4957722/22197725/8eaf12f6-e153-11e6-886d-6921e18fd39d.png)

**Comment by Janzelf** [comment]
"ng serve" works out of the box -  with the added bootstrap installation instructions. If then "ng test" is also supposed to work and it doesn't, something else must be broken.

**Comment by tuxlife** [comment]
I add the `AlertModule` to the `app.commponent.spec.ts`. After then works in my case

```
/* tslint:disable:no-unused-variable */

import { TestBed, async } from '@angular/core/testing';
import { AppComponent } from './app.component';
import { AlertModule } from 'ng2-bootstrap';


describe('AppComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [ AlertModule.forRoot() ],
      declarations: [
        AppComponent
      ],
    });
    TestBed.compileComponents();
  });
...
```

**Comment by edencorbin** [comment]
having same issue, was the app.component.spec.ts fix what worked for you, that is not in the docs.

**Comment by valorkin** [comment]
It's not a fix, when you use component inside of a module you should import module which provides desired component, sorry for a tautology, and doesn't matter is it web app module or test bed dynamic module

**Comment by edencorbin** [comment]
Thanks, I got it working, in my case, I followed the "inner" directions and missed the "outer" direction of including the css, oops.

**Comment by Kurara** [comment]
I have the same configuration as @Janzelf  and now I also added it to spec.ts but still, it doesn't work. Please help me :(
