### ISSUE TITLE
Aot Bundle size

### ISSUE THREAD

**Issue by olaf89** [valor-software/ngx-bootstrap#1538]
Hello, while i was investigating my bundle size using aot build version. I noticed that even when using only one module from ng2-bootstrap the whole library is added as well as moment.js. This makes it quite heavy. Is there any way to improve this? For example changing commonjs modules to ES2015 so it can be tree shaken? Or do you have any other advice which would help with this issue?
This is how adding alert module influenced angular2 webpack starter bundle size (aot prod build) : 
![image](https://cloud.githubusercontent.com/assets/11535118/22186202/1e188704-e0f2-11e6-81f3-30c97e18f5eb.png)

**Comment by valorkin** [comment]
yes, it should work
I just checked, and ng core modules switched to es6, so we switch too

**Comment by valorkin** [comment]
waiting for CI to pass...

**Comment by valorkin** [comment]
tests are passing but,
sourcemap-istanbul-instrumenter-loader failed

**Comment by valorkin** [comment]
released as v1.3.0
please try and update me

**Comment by olaf89** [comment]
Hey, wow thanks for such a quick feedback great stuff!
Unfortunately it does not seem to work as i would expect.
When importing only alert Module using angular2-webpack-starter (aot):
version: Bundle size
1.2.6: 126.8kb
1.3.0: 117.96kb
But overall looks like all not used modules are included in bundle.
Screen for 1.3.0:
![ng-bootstrap1 3 0](https://cloud.githubusercontent.com/assets/11535118/22215908/49fcbc04-e19d-11e6-85e0-f1b3cf4d9178.png)

**Comment by ctrl-brk** [comment]
@olaf89 Btw, what software did you use to produce that pic?

**Comment by olaf89** [comment]
@ctrl-brk im using webpack-bundle-analyzer

**Comment by GuskiS** [comment]
Woah, nice tool :O
For me, ng2bs is using only used packages, not sure if it is because of tree shaking or because I'm importing it directly - `... from 'ng2-bootstrap/datepicker'`

**Comment by valorkin** [comment]
@olaf89 please try v1.3.2

**Comment by olaf89** [comment]
Hello, 
@valorkin I tried but when importing from 'ng2-bootstrap' still whole library is included as well as moment.js.

BUT when tring to do it @GuskiS way (by importing from 'ng2-bootstrap/alert') the result is amazing:
not only all not used modules are dropped but also moment.js
Result:
![bs-alert](https://cloud.githubusercontent.com/assets/11535118/22518523/30a0e84a-e8ad-11e6-8d40-bb6771d657f3.png)

**Comment by valorkin** [comment]
This is awesome! Moment is required only by datepicker

**Comment by GuskiS** [comment]
@valorkin Do you plan to remove momentjs in future?

**Comment by valorkin** [comment]
More likely to make it optional
It provides localization, so it is pretty good

**Comment by alexlovato303** [comment]
@valorkin I recently had issues with moment in a webpack build for angular2. If it's included in an eager module webpack for some reason will not produce chunks for lazy routes
