### ISSUE TITLE
Timepicker without chevron doesn't work with bootstrap v4

### ISSUE THREAD

**Issue by Klinton90** [valor-software/ngx-bootstrap#1539]
First of all, thank you for your great job.

In source code of TimePicker you apply `.hidden` class to chevron row to make them hidden. That css class doesn't exist in bootstrap (anymore?).
Probably you can change code to `*ngIf` instead.

**Comment by valorkin** [comment]
@Klinton90 thank you for kind words, I was trying to avoid heavy things like *ngIf
but most probably I will end up doing this
BTW it is good reason for small PR ;)

**Comment by Klinton90** [comment]
Have to learn how to use webpack. Don't have time for that during the week. Will play with that on weekend. Another option will be defining Component level class instead of `*ngIf`
