### ISSUE TITLE
feat(dropdown): make dropdown-toggle class optional

### ISSUE THREAD

**Issue by sumpton** [valor-software/ngx-bootstrap#1540]
**update by @valorkin**:

  should be added option to config, to disable adding of dropdown toggle class

----

Thank you for all your work. We appreciate it.

We have been using Bootstrap 4 for months, but I just was switching our dropdown menus to the ng2-bootstrap dropdown.

It would be great if the component did not add the dropdown-toggle class so that it would remain optional as it is with Bootstrap. I am now need to use an additional class to override.

Thanks again!

**Comment by valorkin** [comment]
@sumpton my bad, I didn't knew that it is optional
dropdown is under a small refactoring to allow `append to body`
after it I think this should be added

**Comment by sumpton** [comment]
That would be terrific.

A design goal might be to have the Angular bit as light as is possible; working with markup that is as close to Bootstraps as is possible, preferably identical. As I understand it, all that needs to change is the "show" class flag -- maybe animation; I don't know how that works. Ideally, most of the time, Bootstrap should be able to change their CSS and markup and not break Angular.
