### ISSUE TITLE
Problems With Tabs Exception Thrown TabsetConfig!

### ISSUE THREAD

**Issue by wuno** [valor-software/ngx-bootstrap#1547]
I ran my app last night and started getting an error,

> 
No provider for TabsetConfig!

After troubleshooting the issue all night I have come for help lol. 

I have a component which I add to my layout file when it's selector is called. 

```
<!-- Aside Menu -->
<application-aside></application-aside>
<!-- End Aside Menu -->

```

Then of course I create the selector,

```
@Component({
    selector: 'application-aside',
    templateUrl: './aside.component.html'
})
export class AsideComponent {
	   constructor( private router: Router, private auth: Auth  ) { }

}

```

This has worked for me for months but now I get this error,

> EXCEPTION: Uncaught (in promise): Error: Error in ./AsideComponent class AsideComponent - inline template:1:4 caused by: No provider for TabsetConfig!

So I do some research and notice we do not have `ng2-tabs` in the app. Only `ng2-bootstrap`. So install `ng2-tabs` thinking maybe an update triggered some issue now so we need tabs module. But then I realize that they have a new version which is called `ngx-tabs`, so I install that. Now after making sure I am importing the correct TabsModule into my app,

app.module.ts
`import { TabsModule }                       from "ngx-tabs";`

The error that I get after adding tabs module is a conflict of `selectors`. But I can not find any reason why this would be happening,

> Unhandled Promise rejection: Template parse errors:
> More than one component matched on this element.
> Make sure that only one component's selector can match a given element.
> Conflicting components: TabsetComponent,Tabset ("<aside class="aside-menu">
>     [ERROR ->]<tabset>
>         <tab>
>             <template tabHeading><i class="fa fa-list"></i>
> "): AsideComponent@1:4 ; Zone: <root> ; Task: Promise.then ; Value: 
> SyntaxError
> __zone_symbol__error
> :
> Error: Template parse errors: More than one component matched on this element. Make sure that only one component's selector can match a given element. Conflicting components: TabsetComponent,Tabset ("<aside class="aside-menu"> [ERROR ->]<tabset> <tab> <template tabHeading><i class="fa fa-list"></i> "): AsideComponent@1:4 at SyntaxError.ZoneAwareError 

I believe now what the problem is, is that there is a conflict between the ng2 or ngx-tabs I added to the project and the ng2-bootstrap which has TabsetComponent inside of it. 

So this raises the question, If we need a way to clear

>  No provider for TabsetConfig

Then I assume we won't have to install the tabs modules which leaves error 2 out of the equation.

Does anyone have any knowledge about issue with tabs, tabsetconfig or tabset? Are we using ngx-tabs or ng2-tabs now? Does it make a difference?

**Comment by valorkin** [comment]
your forgot to call `.forRoot()` in imports
http://valorkin.github.io/ng2-bootstrap/#/tabs

**Comment by wuno** [comment]
Yes you are absolutely right. thanks

For anyone else who has this problem. I was able to solve it without installing the other modules. Evidently you can import tabs from ng-bootstrap. So it looks like this,

```
// Import from ng-bootstrap
import { Ng2BootstrapModule }               from 'ng2-bootstrap';
import { TabsModule }                              from 'ng2-bootstrap';

import { ChartsModule }                           from 'ng2-charts/ng2-charts';

@NgModule({
    declarations: [
        AppComponent,
        HomeComponent
    ],
    imports: [
        TabsModule.forRoot()
    ],
    providers: [ 
        Guard
    ],
    bootstrap: [AppComponent]
})
```

Once I imported from `ng-bootstrap` and added the `.forRoot()` part to the imports everything worked fine. I was also able to remove the extra modules I installed. They were not needed.

**Comment by valorkin** [comment]
BTW Ng2BootstrapModule - remove import of this and it will decrease your app size.
And in latest ng2-charts, you can 
import blabla from 'ng2-charts'

**Comment by wuno** [comment]
@valorkin  I am sorry I just want to clarify what you are saying. You mean I do not need  
`import { Ng2BootstrapModule }               from 'ng2-bootstrap';`

To use Bootstrap in my application? All I need is each individual module? Charts, tabs etc. How would one import the core bootstrap into the app in that case?

**Comment by valorkin** [comment]
Each module has all needed things
