### ISSUE TITLE
DropdownModule undefined in 1.3.0

### ISSUE THREAD

**Issue by manuelfink** [valor-software/ngx-bootstrap#1552]
With update to ng2-boostrap 1.3.0 DropdownModule seems to be undefined causing my angular 2 app to not load anymore. Has the usage changed anyhow?

**Comment by RobertShires** [comment]
I had the same issue. "cannot call forRoot() on undefined". Reverted to 1.2.5.

**Comment by valorkin** [comment]
bundle(build) configuration?

**Comment by valorkin** [comment]
just in case added note to documentation that system.js are not able to serve commonjs modules correctly:
```
// RECOMMENDED (doesn't work with system.js)
import { DropdownModule } from 'ng2-bootstrap/dropdown';
```

**Comment by marcalj** [comment]
Just to be aware of the problem, SystemJS will be supported in newer versions? What we should migrate to?

I'm using SystemJS and don't know if I should migrate to Webpack or not. I'm still with an upgrade from Ng1 and it's kind a crazy nightmare in general... :(

Thanks!

**Comment by valorkin** [comment]
System.js IS supported, just use cjs bundle
import { DropdownModule } from 'ng2-bootstrap'

But please don't use system.js, use angular-cli

**Comment by marcalj** [comment]
Thanks, I'll try to migrate soonish.

**Comment by kmlprtsng** [comment]
I am also getting this issue with angular-cli 1.0.0-beta.24 on a fresh new project. ng2-bootstrap v1.2.6 works fine.  Similar issue for [Marterial 2](https://github.com/angular/material2/issues/2123) caused by `export *`. I was trying to import the `AlertModule` as suggested by the [ng angular-cli getting started guide](https://github.com/valor-software/ng2-bootstrap/blob/development/docs/getting-started/ng-cli.md).

I was getting the following error in Chrome console:

```
Uncaught TypeError: Cannot read property 'forRoot' of undefined
    at app.module.ts:14
    at Object.573 (app.module.ts:22)
    at __webpack_require__ (bootstrap 9425808…:52)
    at Object.462 (src async:7)
    at __webpack_require__ (bootstrap 9425808…:52)
    at Object.838 (.*$:7)
    at __webpack_require__ (bootstrap 9425808…:52)
    at webpackJsonpCallback (bootstrap 9425808…:23)
    at main.bundle.js:1
```

**Comment by valorkin** [comment]
Can you give me a simple Repo to reproduce this issue please?

**Comment by manuelfink** [comment]
I'm using angular-cli and webpack and do have the same problems.

**Comment by valorkin** [comment]
angular-cli .24 or latest? (.26)

**Comment by robbiedhickey** [comment]
FWIW, I was able to resolve this issue by updating my angular-cli package from version 1.0.0-beta.24 to 1.0.0-beta.26.

**Comment by valorkin** [comment]
Good to know, thank you!

**Comment by kmlprtsng** [comment]
Dang! What am I still doing on 1.0.0-beta.24? I thought I had the latest. I'll update the angular-cli.

**Comment by ssljivic** [comment]
With  ng2-bootstrap@1.3.1 and angular-cli@1.0.0-beta.26, I am still getting the error:

`Uncaught TypeError: Cannot read property 'forRoot' of undefined`

The code that produces the error is:

```
import { AlertModule } from 'ng2-bootstrap';
...

@NgModule({
   ...
   imports: [AlertModule.forRoot(), ... ],
    ... 
})
```

**Comment by ssljivic** [comment]
If I use **Ng2BootstrapModule**, the error is not thrown.

**Comment by kmlprtsng** [comment]
Upgrading it to beta.26 worked for me. @ssljivic make sure that you clean your npm cache and follow the steps mentioned here: https://github.com/angular/angular-cli#updating-angular-cli

**Comment by soyersoyer** [comment]
The DropdownModule doesn't work with the bootstrap 4.0.0-alpha.6 version.

**Comment by valorkin** [comment]
@soyersoyer add `<script>window.__theme = 'bs4';</script>` to index.html to enable bs.4 templates
