### ISSUE TITLE
feat(sortable): add support for custom item template

### ISSUE THREAD

**Issue by dlcooper** [valor-software/ngx-bootstrap#1554]
I have a list of cups (complex model) and want a different image for each cup but the API for <bs-sortable/> doesn't seem to support such a concept.  

` <bs-sortable
    [(ngModel)]="itemObjectsLeft"
    fieldName="name"
    itemClass="sortable-item"
    itemActiveClass="sortable-item-active"
    placeholderItem="Drag here"
    placeholderClass="sortable-item"
    wrapperClass="sortable-wrapper"
  ></bs-sortable>

class Cup {
    type:string
    name:string
}
`

Is there a way to do that based on the value of the type property?

Maybe there could be a "template" or "templateRef" Input that would have access to the list item.

Something like:

`
<bs-sortable [(ngModel)]="myCups" templateRef="cupRenderingTemplate"...>
</bs-sortable>
`

**Comment by valorkin** [comment]
yep, need to mark sortable as experimental, some how
adding custom item template would be good

**Comment by valorkin** [comment]
I just made a prototype of this idea, but I need to clarify one thing
please check https://github.com/valor-software/ng2-bootstrap/commit/5ed3ba4a6e7811693f0323151ed82189571cbb0f#diff-456830bd92e54b2e7c01693e0f6654af

is it enough? or item template should include `.sortable-item' `div`?

**Comment by dlcooper** [comment]
This looks like enough for my purposes.  I would expect the component to still own the .sortable-item 'div' not the template.

________________________________

**Comment by dlcooper** [comment]
Any more thoughts on the viability of this?  Or a timeline for incorporating it in the product?


________________________________

**Comment by valorkin** [comment]
I have some urgent things to fix, but tomorrow I hope to get in this

**Comment by dlcooper** [comment]
This is great!

It would nice to have a template parameter to compute whether the item is draggable.  i.e.

`let-draggable="{{isDraggable(item)}}"`

or, you could just call me wrong and make the

> item template should include .sortable-item'div`?

as you suggested earlier.

**Comment by Le0Michine** [comment]
@dlcooper not sure if I understand you correctly, do you want to make some items in sortable container undraggable i.e. they should always keep their positions? If so when 

> item template should include .sortable-item'div`?

won't help because you still will be able to drag other items and it can affect positions of disabled items as well (according to current implementation for sure). Or probably you just want to disable whole container?

**Comment by dlcooper** [comment]
For my application it's ok if an item's position changes in a list as long as it can't leave the list, for example:

"List A"
  Joe
  Bill   (draggable=false)
  Bob

"List B"
  Don
  Jim
  George

as long as Bill can't leave "List A" it doesn't matter for me whether he's first, second or third in the list.

So, if Bill is in a <div draggable="false">Bill</div> I think that does what I am looking for.
________________________________

**Comment by Le0Michine** [comment]
@dlcooper OK, I see. It is added to next PR but not sure how long it will take to approve it, it is quite big.

**Comment by IlyaSurmay** [comment]
Custom template support was added in #1580
