### ISSUE TITLE
Typeahead does not show list on focus when typeaheadMinLength="0" set

### ISSUE THREAD

**Issue by tzielins** [valor-software/ngx-bootstrap#1559]
According to documentation this feature is already supported (when typeaheadMinLength="0", the dropdown should open on click listing available options).

But it does not work for me with version 1.3.1, nor it does on the demo page:
http://valor-software.com/ng2-bootstrap/#/typeahead#forms

(It work if after getting inside the input the backspace is pressed)

**Comment by valorkin** [comment]
there are some kind of change detection issues, I knew about them
should be fixed soon

**Comment by weglarzdamian** [comment]
I've also observed this issue. Workaround for me is:
_[typeaheadMinLength]="0"_
instead of:
_typeaheadMinLength="0"_

**Comment by valorkin** [comment]
`[typeaheadMinLength]="0"` this is `0` as number
and this
`typeaheadMinLength="0"` `0` is a string

it is not workaround, this is how angular @input binding are working

**Comment by bartes** [comment]
@valorkin - I guess the source of this problem is the docs: https://valor-software.com/ngx-bootstrap/#/typeahead . `typeaheadMinLength="0"` is recommended there.

**Comment by valorkin** [comment]
@bartosz nice reason for small PR. 
I have seen your comment in email

**Comment by rcadhikari** [comment]
@valorkin I am still having same issue as I could not show all options (only first 20 items out of 150 are displaying in the dropdown list on foucs). I am using `"ngx-bootstrap": "^2.0.2"`.
Any help would be really appreciated.

**Comment by rcadhikari** [comment]
Never mind, I managed to show all after adding `[typeaheadOptionsLimit]="200"` as additional parameter.
