### ISSUE TITLE
chore(system.js): Unexpected token < including ng2-bootstrap

### ISSUE THREAD

**Issue by mburger81** [valor-software/ngx-bootstrap#156]
Hello,

I try to include your ng2-bootstrap using the angolar.io Quick Start example.

this is my example for app.components without html tag <alert>

import {Component} from 'angular2/core';
import {Alert} from 'ng2-bootstrap/ng2-bootstrap';

@Component({
    selector: 'my-app',
    directives: [Alert],
    template: '......'
})
export class AppComponent { }`

including Alert in the directive I get this error

angular2-polyfills.js:1243 Uncaught SyntaxError: Unexpected token <
    Evaluating http://localhost:3000/ng2-bootstrap/ng2-bootstrap
    Error loading http://localhost:3000/app/main.js

thx
  Michael

**Comment by valorkin** [comment]
this
https://github.com/valor-software/ng2-bootstrap#quick-start
and this
https://github.com/valor-software/angular2-quickstart
should help, 
read the docs :)
