### ISSUE TITLE
Tooltip Template - Docs incorrect

### ISSUE THREAD

**Issue by arimus** [valor-software/ngx-bootstrap#1563]
Reference: https://valor-software.com/ng2-bootstrap/#/tooltip#dynamic-content

The docs state that you would do the following with [tooltip]:

```
<template #tolTemplate>Just another: {{content}}</template>
<button type="button" class="btn btn-warning" [tooltip]="tolTemplate">
  TemplateRef binding
</button>
```

which appears to be incorrect from the code. It should actually be [tooltipHtml] when referencing a template, like so:

```
<template #tolTemplate>Just another: {{content}}</template>
<button type="button" class="btn btn-warning" [tooltipHtml]="tolTemplate">
  TemplateRef binding
</button>
```

p.s. thanks for the great library

**Comment by valorkin** [comment]
thanks for nice words ;)
which version of ng2 are you using?
I have dropped [tooltipHtml] it was used as hack for `innerHtml`
since v1.2+

**Comment by arimus** [comment]
Yeah, I apologize. I know better than to report without a version. And you are correct, once I updated it all got better. 

Previously, I couldn't update due to some of the issues with the newer Angular versions & this library, but it appears that the chain of updated deps is more stable now.

Thanks again!

**Comment by arimus** [comment]
p.s. I know it's always a challenge versioning docs and more of a pain than it's worth sometimes. However, it could be a good add to at least have a clear software version in the docs, so that it'll remind folks that forget they are not on the latest that the docs may not match their code. 

Even better would be listing some older mechanisms and marking deprecated. No need to go back in time for that, but could be an improvement moving forward ;)

**Comment by valorkin** [comment]
Yep, I am thinking about it :)
