### ISSUE TITLE
is there any event to track when modal has shown?

### ISSUE THREAD

**Issue by alifatic** [valor-software/ngx-bootstrap#1566]
is there any event to track when modal has shown?

**Comment by GuskiS** [comment]
http://valor-software.com/ng2-bootstrap/#/modals#modal-directive
Outputs -> `onShown`

**Comment by alifatic** [comment]
@GuskiS  thank u for answering my questiin can u give me a sample code of how to using onshown or other event, sorry im new in angular 2

**Comment by GuskiS** [comment]
```
<div class="modal fade" bsModal #staticModal="bs-modal" (onShown)=''funcInComponent($event)''>
...
</div>
```

**Comment by alifatic** [comment]
thank u so much, it works!
