### ISSUE TITLE
bootstrap@4.0.0-apha.6 modal backdrop class "fade" not removed on show

### ISSUE THREAD

**Issue by osahner** [valor-software/ngx-bootstrap#1572]
and yeah the 

`(<any>window).__theme = 'bs4';`

workaround should be fixed to.

**Comment by valorkin** [comment]
should be some issues in console?
please provide version of ng2-bs, ng and what are you using for bundling

**Comment by osahner** [comment]
closed because it was actually an older Version from bootstrap theme. After update of the include bs to b6 everything is fine (with the workaround)

**Comment by pwalkiewicz** [comment]
I have the same issue with ng2-bootstrap 1.3.3 and bootstrap: ^4.0.0-alpha.6. Project build with angular-cli. Console empty.  @osahner  How did you precisely resolved the issue?

**Comment by pwalkiewicz** [comment]
OK, Seems that I've to use ` (<any>window).__theme ='bs4';` workaround and it's OK now.
