### ISSUE TITLE
Customising bootstrap

### ISSUE THREAD

**Issue by hassanasad** [valor-software/ngx-bootstrap#1577]
Hi - I am pretty sure this might not be the correct place to ask this question, but i dont know where else to ask it.

How can we customize bootstrap (for instance disable its grid system) in my angular2 app? I am using ng2-bootstrap package.

I have an entry in my `angular-cli.json` file:
```
"styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.min.css"
]
```

I dont want to manually remove the entire grid system from that file.

**Comment by valorkin** [comment]
http://getbootstrap.com/customize/
this should help
or you can play with custom BS builds locally

**Comment by GuskiS** [comment]
In my project I load bootstrap with my backend code. Ruby on Rails to be specific. In this way I can customize as I want by changing SASS variables and/or change modules. You can do the same with you backend. Not sure if `angular-cli` support SASS, but you can do it with webpack.

**Comment by hassanasad** [comment]
@valorkin yeah but i usually dont keep the node_modules folder in my git. So when deploying it will get overwritten everytime. 

I guess there is no easy way to do it then.

@GuskiS I dont think angular-cli supports SASS either. (however in case it did, which variable would i use to disable the entire grid in bootstrap?)

**Comment by GuskiS** [comment]
@hassanasad I have custom created bootstrap file, which I import instead of full bootstrap from package(node_modules or ruby gem, doesn't matter).
```sass
// Core variables and mixins
@import "bootstrap/variables"
@import "bootstrap/mixins"

// Reset and dependencies
@import "bootstrap/normalize"
@import "bootstrap/print"
@import "bootstrap/glyphicons"

// Core CSS
@import "bootstrap/scaffolding"
@import "bootstrap/type"
// @import "bootstrap/code"
@import "bootstrap/grid"
// @import "bootstrap/tables"
@import "bootstrap/forms"
// @import "bootstrap/buttons"

// Components
@import "bootstrap/component-animations"
// @import "bootstrap/dropdowns"
// @import "bootstrap/button-groups"
@import "bootstrap/input-groups"
@import "bootstrap/navs"
@import "bootstrap/navbar"
// @import "bootstrap/breadcrumbs"
// @import "bootstrap/pagination"
// @import "bootstrap/pager"
// @import "bootstrap/labels"
@import "bootstrap/badges"
// @import "bootstrap/jumbotron"
// @import "bootstrap/thumbnails"
// @import "bootstrap/alerts"
// @import "bootstrap/progress-bars"
@import "bootstrap/media"
// @import "bootstrap/list-group"
// @import "bootstrap/panels"
@import "bootstrap/responsive-embed"
// @import "bootstrap/wells"
@import "bootstrap/close"

// Components w/ JavaScript
@import "bootstrap/modals"
@import "bootstrap/tooltip"
@import "bootstrap/popovers"
// @import "bootstrap/carousel"

// Utility classes
@import "bootstrap/utilities"
@import "bootstrap/responsive-utilities"
```

**Comment by hassanasad** [comment]
@GuskiS Thanks for sharing your customized file, I will need to install another package for LESS too? I am currently using SCSS with angular-cli

**Comment by GuskiS** [comment]
Not sure, but probably take a look here: https://github.com/twbs/bootstrap-sass
I'm using this one for rails, but it has support also for node :)

**Comment by hassanasad** [comment]
@GuskiS Ah thanks man - this is very helpful :) 

I hope not to bother you any further ( but lets see ;) )

**Comment by valorkin** [comment]
@hassanasad it seems we are done here? ;)

**Comment by hassanasad** [comment]
@valorkin yeah - thanks for the support :)
