### ISSUE TITLE
Pagination component not working with Universal

### ISSUE THREAD

**Issue by ferares** [valor-software/ngx-bootstrap#1578]
**This line on pagination.component:**

this.classMap = this.elementRef.nativeElement.getAttribute('class') || '';

**Seems to break Universal with the following error:**

TypeError: this.elementRef.nativeElement.getAttribute is not a function

**see:** https://github.com/angular/universal-starter#universal-gotchas

**Comment by valorkin** [comment]
do you have a working sample of ng2bs with universal?

**Comment by ferares** [comment]
@valorkin 

https://github.com/ferares/ng2bootstrap-universal-pagination-issue

npm start to run it, it runs on port 3000

It has 2 views:

Home: without pagination - universal works
Issue: with pagination - universal doesn't work

You can check universal is working by viewing the source code deliver to the browser

**Comment by EivindArvesen** [comment]
I have the same problem. It can be fixed with a check to make sure the code only executes on the browser, e.g. `if (typeof window !== 'undefined') ...`.
This has worked for us in many cases.

Could you update ng2-bootstrap pagination to reflect this? Thanks

**Comment by IlyaSurmay** [comment]
Fixed in #2925
