### ISSUE TITLE
system.js error with version 1.3.x

### ISSUE THREAD

**Issue by Bedo81** [valor-software/ngx-bootstrap#1588]
**I use pagination module and I am getting this system.js error with a new version 1.3.x . It was working fine with 1.2.6.**

Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:9000/traceur.js
	Error: XHR error (404 Not Found) loading http://localhost:9000/traceur.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9000/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:9000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:9000/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:9000/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:9000/traceur.js
	Unable to load transpiler to transpile http://localhost:9000/node_modules/ng2-bootstrap/pagination/pagination.module.js
	Error loading http://localhost:9000/node_modules/ng2-bootstrap/pagination/pagination.module.js as "ng2-bootstrap/pagination/pagination.module" from http://localhost:9000/dist/app/app.module.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9000/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:9000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:9000/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:9000/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:9000/traceur.js
	Unable to load transpiler to transpile http://localhost:9000/node_modules/ng2-bootstrap/pagination/pagination.module.js
	Error loading http://localhost:9000/node_modules/ng2-bootstrap/pagination/pagination.module.js as "ng2-bootstrap/pagination/pagination.module" from http://localhost:9000/dist/app/app.module.js

**system.js config:**
```
map: {
      'ng2-table': 'npm:ng2-table',
      'ng2-bootstrap': 'npm:ng2-bootstrap'
    },
    packages: {
      'ng2-table': {main: 'ng2-table.js', defaultExtension: 'js'},
      'ng2-bootstrap': {main: 'index.js', defaultExtension: 'js'}      
    }
```

**app.module.ts imports:**
```
import {Ng2TableModule} from 'ng2-table';
import {PaginationModule} from 'ng2-bootstrap/pagination/pagination.module';
@NgModule({
imports: [
    Ng2TableModule,
    PaginationModule.forRoot(),
]
})
```

**Comment by GuskiS** [comment]
Does `import {PaginationModule} from 'ng2-bootstrap';` work?

**Comment by Bedo81** [comment]
Doesn't work. That's why I imported it as 'ng2-bootstrap/pagination/pagination.module'

**Comment by GuskiS** [comment]
You need to change `'ng2-bootstrap': 'npm:ng2-bootstrap'` for each module. I had something like this, before I switched to webpack:
```js
map: {
//...
      'ng2-bootstrap/modal': 'npm:ng2-bootstrap/modal',
      'ng2-bootstrap/collapse': 'npm:ng2-bootstrap/collapse',
      'ng2-bootstrap/datepicker': 'npm:ng2-bootstrap/datepicker',
      'ng2-bootstrap/popover': 'npm:ng2-bootstrap/popover',
      'ng2-bootstrap/tooltip': 'npm:ng2-bootstrap/tooltip',
      'ng2-bootstrap/positioning': 'npm:ng2-bootstrap/positioning',
      'ng2-bootstrap/component-loader': 'npm:ng2-bootstrap/component-loader',
//...
},
packages: {
//...
      'ng2-bootstrap/modal': { main: 'index.js', defaultExtension: 'js' },
      'ng2-bootstrap/collapse': { main: 'index.js', defaultExtension: 'js' },
      'ng2-bootstrap/datepicker': { main: 'index.js', defaultExtension: 'js' },
      'ng2-bootstrap/popover': { main: 'index.js', defaultExtension: 'js' },
      'ng2-bootstrap/tooltip': { main: 'index.js', defaultExtension: 'js' },
      'ng2-bootstrap/positioning': { main: 'index.js', defaultExtension: 'js' },
      'ng2-bootstrap/component-loader': { main: 'index.js', defaultExtension: 'js' },
//...
}
```

and then `import { PopoverModule } from 'ng2-bootstrap/popover'`

**Comment by Bedo81** [comment]
I changed it but it has same error on v1.3.2.

And even it throws an error on v1.2.6 : 
`No provider for PaginationConfig!`

**Comment by GuskiS** [comment]
@Bedo81 Is it TypeScript compilation error or is it still system.js? If it is system.js, you need to add `PaginationConfig` to systemjs config. I did that with `positioning` and `component-loader`.

**Comment by valorkin** [comment]
Unfortunately System.js doesn't work properly with common.js
so you will have to use bundle, with configuration like this:
https://github.com/valor-software/angular2-quickstart/blob/master/systemjs.config.js
