### ISSUE TITLE
export 'ModalOptions' was not found in 'ng2-bootstrap'

### ISSUE THREAD

**Issue by kambbado** [valor-software/ngx-bootstrap#1590]
I'm using ng2-bootstrap 1.3.2 and I'm noticing this issue now, it was not happening with the previous version.  Do you have an hints?

> WARNING in ./src/app/shared/dialogs/popup.component.ts
> 184:50-62 "export 'ModalOptions' was not found in 'ng2-bootstrap'

This is my import line in my component

`import { ModalDirective, ModalOptions } from 'ng2-bootstrap';`

> Update: updated to ng2-bootstrap@1.4.0-beta.3 and the issue went away

Thank you

**Comment by valorkin** [comment]
I will include in next version fix for it,
I had to switch from `export *` to named exports
and seems I have lost couple of classes to export

**Comment by valorkin** [comment]
please try v1.3.3

**Comment by kambbado** [comment]
I tried the 1.3.3, what is strange is that when I run "ng serve --aot" no warnings are given, but when I removed the "--aot" parameters it outputs the following error

> 184:82-94 "export 'ModalOptions' was not found in 'ng2-bootstrap'

I'm using Visual Studio 2015 as the editor and it's complaining on this line

`import { ModalDirective, ModalOptions } from 'ng2-bootstrap';` 

that

> ng2-bootstraap/index.d.ts is not a module.

I have uninstall and re-installed ng2-bootstrap

Here's my tsconfig.json file
`{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es6", "dom" ],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}

I install ng2-bootstrap@1.4.0-beta.3 and I'm no longer receiving the warning.

I'm stumped, is it my development environment configuration?  Let me know if you need more information or would like me to change something at my end. Anything to help.

Manny 
`

**Comment by valorkin** [comment]
Angular cli versions?
Ts version?
Try to import ng2bs/modals

**Comment by kambbado** [comment]
tsc -v     
Version 2.0.3
ng -v
angular-cli: 1.0.0-beta.28.3
node: 7.5.0
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

Tried to import ng2-bootstrap/modal, produced the same warning

**Comment by valorkin** [comment]
Try ts v2.0.10 and @angular/cli .30

**Comment by valorkin** [comment]
If it will not work, join slack and drop me a link to Repo in DM
