### ISSUE TITLE
prevent collapse/expand on clicking ng2 component within accordion-heading 

### ISSUE THREAD

**Issue by isatriya** [valor-software/ngx-bootstrap#1594]
Suppose i would like to prevent collapse/ expand on clicking another ng2 component/ element that is located within accordion-heading, what is the best practice for doing this ?

**Comment by valorkin** [comment]
component in header preventing a collapse?
should be as simple as `(click)="$event.preventDefatult()"`
not sure it is a good idea, because user could be easily confused

**Comment by timpoulos** [comment]
I fixed this issue by attaching a click event handler to the elements that I do not want to toggle the accordion panel expand/collapse.

``    preventToggle(event: any): boolean {
        event.stopPropagation();
        event.preventDefault();
        return false;
    }``
