### ISSUE TITLE
Multi level dropdown

### ISSUE THREAD

**Issue by ALFRED-Guillaume** [valor-software/ngx-bootstrap#1596]
Is it possible to make a multi level dropdown using ng2-bootstrap ?

I have read the documentation but couldn't an example anywhere.

Thanks in advance.

**Comment by valorkin** [comment]
do you have an example?

**Comment by ALFRED-Guillaume** [comment]
I'm trying to implement something like [that]( http://bootsnipp.com/snippets/featured/multi-level-dropdown-menu-bs3).

**Comment by valorkin** [comment]
I will try to publish new version today
you will see new sample at `/#/dropdowns#nested`
but guys are saying that this feature could de done with css only solution
