### ISSUE TITLE
docs(modal): add documentation for the focus config option for modals

### ISSUE THREAD

**Issue by olingerc** [valor-software/ngx-bootstrap#1597]
Hi,

I tried to apply an autofocus directive to one of my inputs in a modal. The input is focused on modal show animation start but unfocuses on animation finish. Going through the modal code, I realized this is a wanted feature.
Fortunately there is a focus configuration parameter which, when turned to false will prevent the modal from stealing the focus. Thanks to the person who thought of that.

However, this option is not documented on the examples page.

**Comment by ahtshamraziq** [comment]
Only `ModalDirective` implements `ModalOptions.focus`,  `BsModalService` ignores it.
