### ISSUE TITLE
Support for a variety of DatePicker styles

### ISSUE THREAD

**Issue by jdaltonchilders** [valor-software/ngx-bootstrap#1601]
I've been looking at your current [datepicker](http://valor-software.com/ng2-bootstrap/#/datepicker#datepicker-component) and was curious if you had plans to add additional styles such as "Datepicker in a popup".

Examples:
Something like http://fengyuanchen.github.io/datepicker/ or https://ng-bootstrap.github.io/#/components/datepicker.

**Comment by valorkin** [comment]
sure, drop me DM in slack so I can share couple WIP things with new templates and pop up version

**Comment by valorkin** [comment]
I am working on completely new way to provide templates for components
but it could be a breaking change

**Comment by valorkin** [comment]
done in new datepicker
available in v1.9.2
http://valor-software.com/ngx-bootstrap/#/datepicker
