### ISSUE TITLE
(docs) Popover click issue

### ISSUE THREAD

**Issue by BioSin** [valor-software/ngx-bootstrap#1607]
When I click on "Popover on..." (see attachments), right margin disappearing.
<img width="880" alt="screenshot 2017-02-06 15 52 38" src="https://cloud.githubusercontent.com/assets/1442288/22640683/49358ffa-ec86-11e6-94bf-5438c8af30b4.png">
<img width="775" alt="screenshot 2017-02-06 15 53 28" src="https://cloud.githubusercontent.com/assets/1442288/22640684/4939068a-ec86-11e6-979d-e4fcdb6ff30b.png">

**Comment by valorkin** [comment]
I have seen this issue, but didn't have time to figure out why it is happening

**Comment by valorkin** [comment]
can not reproduce anymore
