### ISSUE TITLE
onClose event should be called along with dismissOnTimeout to work on Alert

### ISSUE THREAD

**Issue by ervbsankar** [valor-software/ngx-bootstrap#1610]
Please update the documentation.
without (onClose) event, dismissOnTimeout on Alert is not working.

**Comment by valorkin** [comment]
but it is actually working http://valor-software.com/ng2-bootstrap/#/alerts#dismiss-on-timeout
if issue persists in latest ng2-bootstrap version
please provide plunkr with reproduce
