### ISSUE TITLE
Plans on merging with https://github.com/ng-bootstrap/ng-bootstrap

### ISSUE THREAD

**Issue by vlodko** [valor-software/ngx-bootstrap#1611]
You all are doing a great job, but it would much better if you can combine your efforts and create a single Angular 2 Bootstrap project.

What's your plans on that? Are there any discussions on possible merging ng-bootstrap2 and ng-bootstrap?
We are in the point of choosing UI framework for our Angular 2 application and it's pretty hard to pick one.
Thanks in advance.

**Comment by valorkin** [comment]
@vlodko I can imagine, choose any, both are pretty good
yes, we are discussing merge from time to time,
but no idea when it will be

but this project is not limited by bootstrap core functionality and completely required essentials 
like date range picker (http://valorkin.github.io/ng2-bootstrap/#/datepicker - not for share yet ;) )
or ng2-select will be merged in typeahead
will be added

**Comment by valorkin** [comment]
btw, you can DM in slack if you will have any questions ;)

**Comment by vlodko** [comment]
@valorkin thank for response.
We will probably pick PrimeNG for our needs.
