### ISSUE TITLE
Can't resolve all parameters for TooltipOptions

### ISSUE THREAD

**Issue by GuskiS** [valor-software/ngx-bootstrap#1612]
Just updated to version 1.3.3, but having this error while doing AoT compilation:
`Can't resolve all parameters for TooltipOptions in path/node_modules/ng2-bootstrap/tooltip/tooltip-options.class.d.ts`
I'm not using `TooltipOptions` anywhere. Using webpack 2.2.1, TS 2.1.5, Angular 4.0.beta6.
On JiT works fine.

**Comment by damoqiongqiu** [comment]
Same issue

**Comment by valorkin** [comment]
I will need to replace it with interface or something... strange it was working fine before

**Comment by neilhem** [comment]
The same error with default JIT compilation

**Comment by RomaDotDev** [comment]
Confirm the error for AoT, JiT is fine. 
ng2-bootstrap 1.3.3, Angular 4.0.0 RC1, angular-cli 1.0.0 RC0

**Comment by GuskiS** [comment]
@valorkin This needs a fix because Angular 4 is nearly here.

**Comment by ctrl-brk** [comment]
Works in Angular 2 but not in Angular 4

**Comment by valorkin** [comment]
I took a look, there are not so many breaking changes for devs, but a lot for lib devs :(

**Comment by Iverson** [comment]
I found workaround:
```
import { TooltipModule } from 'ng2-bootstrap/tooltip/tooltip.module'
```
instead of
```
import { TooltipModule } from 'ng2-bootstrap/tooltip'
```
just don't import deprecated `ng2-bootstrap/tooltip/tooltip-options.class.js` which exported automatically from `ng2-bootstrap/tooltip/index.js`

**Comment by ctrl-brk** [comment]
@Iverson I don't import this module anywhere and still get the error.

**Comment by GuskiS** [comment]
@valorkin :+1: When will be new NPM version released?

**Comment by valorkin** [comment]
Updated cli to rc.0
tomorrow I want to release 2 versions
With ng v2 and 4

**Comment by RomaDotDev** [comment]
@valorkin Please note an interesting side effect. 
In my code I use lazy load, AOT compilation and shared factory where init and expose all ng2-bootstrap modules across the app.   

When I import all modules directly as @Iverson suggested
`import { TooltipModule } from 'ng2-bootstrap/tooltip/tooltip.module' `
the size of vendor.bundle.js becomes slightly bigger, but lazy loaded chunks which use shared ng2-bootstrap modules become much smaller.

In result my total AoT tree-shaked, minified and compressed production build is 200kb lighter.

I use Angular 2.4.8, CLI RC0

**Comment by ctrl-brk** [comment]
I'm dying here waiting for the fix :(

**Comment by karlhaas** [comment]
Also waiting for the fix. @valorkin can you tell when the new release will be ready?

**Comment by valorkin** [comment]
https://github.com/valor-software/ng2-bootstrap/releases/tag/v1.4.0

published
