### ISSUE TITLE
Document how to enable Bootstrap 4 style

### ISSUE THREAD

**Issue by dhilgarth** [valor-software/ngx-bootstrap#1619]
To enable Bootstrap 4, adding `<script>window.__theme = 'bs4';</script>` to the end of the body tag is necessary. This isn't documented in the readme

**Comment by valorkin** [comment]
it is not, any idea where to put it?

**Comment by dhilgarth** [comment]
@valorkin : I don't think I understand your question. What are you asking?

**Comment by dietergeerts** [comment]
Ihmo, it would be better is we could set this in some sort of config, or in the forRoot method.

**Comment by valorkin** [comment]
@dietergeerts this is the plan for v2
check this out: https://github.com/valor-software/ng2-bootstrap/blob/development/src/typeahead/typeahead-container.component.ts#L13-L50

I am planning to separate templates from behavior implementation
and add simple template loader stuff
so you can override templates,
and use only templates you need ^_^

**Comment by IlyaSurmay** [comment]
Closing this because the newest version of ngx-bootstrap doesn't need any additional options like `window.__theme = 'bs4'`. 
Old doc that explains how to enable bs4 is here - https://github.com/valor-software/ngx-bootstrap/blob/development/docs/getting-started/bootstrap4.md
