### ISSUE TITLE
chore(dropdown): Don’t auto-apply the "dropdown-toggle" class

### ISSUE THREAD

**Issue by rluba** [valor-software/ngx-bootstrap#162]
**Update**: 
- change default dropdown toggle behavior to not add `dropdown-toggle` class
- expose an option to enable this via options

by @valorkin

---

The `dropdownToggle` directive auto-applies the `dropdown-toggle` class to the element even though this is a purely cosmetic class (it just adds the caret using the `:after` selector). It’s possible to define a popup _without `dropdown-toggle`_ when using Bootstrap 4 directly, but not when using `ng2-bootstrap`.

I’d suggest to stop auto-applying this class since it’s much easier to manually add the class where it’s desired than trying to prevent the directive from applying the class where it’s undesired.

**Comment by valorkin** [comment]
saying simpler,
change default behavior to not applying `dropdown-toggle`
and expose an option to enable it

**Comment by valorkin** [comment]
does it correlates with default https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.2/js/src/dropdown.js behavior?

**Comment by rluba** [comment]
The native Bootstrap JS does not add the `dropdown-toggle` class.

**Comment by jprinaldi** [comment]
+1

**Comment by adrianfaciu** [comment]
Made a small change to optionally add the class. If it fixes the problem, we can merge it.
