### ISSUE TITLE
Dropdown not working on bootstrap 4 Alpha 6

### ISSUE THREAD

**Issue by lumineida** [valor-software/ngx-bootstrap#1620]
Dropdown is not expanding using Bootstrap v4.0.0-alpha.6. According to https://github.com/twbs/bootstrap/issues/20939 on Alpha.6 the class .open was renamed to .show:

"Renamed some .active, all .in, and all .open classes for our JavaScript powered components for more consistent naming. For example, instead it's now .collapse.show instead of .collapse.in and .show > .dropdown-menu instead of .open > .dropdown-menu to better communicate the visibility of elements."

Currently ng2-bootstrap dropdown is still adding the .open class. If I change it manually to .show it is working, so it should be updated.

Thank you.

**Comment by fchiumeo** [comment]
see #1458 and #1553

**Comment by lumineida** [comment]
thanks, closing as this is duplicate
