### ISSUE TITLE
typeaheadMinLength="0" doesn't enable popup on focus

### ISSUE THREAD

**Issue by mrgle** [valor-software/ngx-bootstrap#1627]
Per docs

**When set to 0, typeahead shows on focus with full list of options**

but this isn't currently happening. Poking in the code I see that the check to show on focus compares the value typeaheadMinLength to the number 0, but the property itself is a string (shown in debugger) so the strict equality fails.

```
TypeaheadDirective.prototype.onFocus = function () {
        if (this.typeaheadMinLength === 0) {
            this.typeaheadLoading.emit(true);
            this.keyUpEventEmitter.emit('');
        }
    };
```

I propose the equality check should be modified, or the input parsed to a number on init to enable this functionality.

**Comment by IlyaSurmay** [comment]
Closing in favor of #2845
