### ISSUE TITLE
How can i add multiple date selection?

### ISSUE THREAD

**Issue by sajeetharan** [valor-software/ngx-bootstrap#1628]
How to enable multiple dates selected? say i want to highlight this week dates. How can i style the dates and make them selected?

**Comment by valorkin** [comment]
no way at the moment
but there are a request (issue) and I already have an implementation of 
date range picker
stay tuned :)

**Comment by darkguy2008** [comment]
A year has passed, still tuned in... so, is there progress?

**Comment by JavierOrellanaR** [comment]
bump!

**Comment by aminasya** [comment]
Is it possible to do it now?
