### ISSUE TITLE
chore(datepicker): is mutating date object in day picker

### ISSUE THREAD

**Issue by kraikill** [valor-software/ngx-bootstrap#163]
**Fix**
Date picker should not mutate Date object
It should return new Date instance on each date change in day picker

by @valorkin

---

Click by day has no effect on model. Only works when you select month or year.

**Comment by valorkin** [comment]
@kraikill datepicker is working, but it mutates Date object in day picker part
it should be fixed

**Comment by valorkin** [comment]
@edinfazlic so this issue is about mutating date object by using it methods
like set day or year
each time date is changed new instance of Date object should be returned
in simplest case `return new Date(date)`

**Comment by edinfazlic** [comment]
Created PR. Let me know what you think.
