### ISSUE TITLE
Cannot launch ng2-boostrap Demo 

### ISSUE THREAD

**Issue by axelpcr** [valor-software/ngx-bootstrap#1632]
Hi, I try to launch ng2-bootstrap demo but not working.
I clone valor-software/ng2-bootstrap.
I write npm install & npm start and I have this error :

```
ERROR in Error encountered resolving symbol values statically. Could not resolve ng2-bootstrap/tabs relative to /home/axel/Developpement/Project/ng2-bootstrap/demo/src/app/api-docs/index.ts.,
resolving symbol NgApiDocModule in /home/axel/Developpement/Project/ng2-bootstrap/demo/src/app/api-docs/index.ts,
resolving symbol NgApiDocModule in /home/axel/Developpement/Project/ng2-bootstrap/demo/src/app/api-docs/index.ts

ERROR in ./demo/src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/axel/Developpement/Project/ng2-bootstrap/demo/src'
 @ ./demo/src/main.ts 4:0-74
 @ multi webpack-dev-server/client?http://0.0.0.0:4200/ ./demo/src/main.ts
webpack: Failed to compile.
```

Best Regards

**Comment by SergeyKuryatnick** [comment]
You have missed some steps, that can help:
- clone repo
- npm install
- npm run build
- npm run link
- npm start

enjoy ;-)

**Comment by imribarr-compit** [comment]
Hey, I have the same issue. Following @SergeyKuryatnick's solution did not work for me.

**Comment by SergeyKuryatnick** [comment]
@axelpcr @imribarr-compit 
yep, issue in new version of `@types/jasmine`
We'll lock version of it in new revision.

For now you can manually change version of `@types/jasmine` in package.json
from
"@types/jasmine": "^2.5.41",
to 
"@types/jasmine": "2.5.41"

after this, make clean install and run commands, listed in previous my comment

**Comment by axelpcr** [comment]
Thx :)

**Comment by michaelfaisst** [comment]
@SergeyKuryatnick @valorkin  Missed these steps too and it took a while to find this issue. Maybe a short paragraph in the readme with these steps would help for future people? : )
