### ISSUE TITLE
Permission denied when trying to push changes to branch

### ISSUE THREAD

**Issue by imribarr-compit** [valor-software/ngx-bootstrap#1636]
Hey, I cloned the repository using SSH, created a branch from development branch and for some reason when I push the code to the branch I created, I get:
ERROR: Permission to valor-software/ng2-bootstrap.git denied to imribarr-compit.
fatal: Could not read from remote repository.

Also, I need to mention that committing the code only worked when I bypassed the commit hook.

Thanks.

**Comment by SergeyKuryatnick** [comment]
@imribarr-compit Have you tried to use fork?

**Comment by valorkin** [comment]
Thanks, I will try to merge it soon
