### ISSUE TITLE
Bootstrap 4 and card text

### ISSUE THREAD

**Issue by DouglasWebster** [valor-software/ngx-bootstrap#1637]
The Bootstrap 4 demo of the ratings module does not layout the text correctly in the card block.  It seems that the problem is with including the card and card-block declaration in the same class attribute and then including a tag in the text[(see this plunker).](https://plnkr.co/edit/L1S5Is?p=info) Moving the card declaration to its own section solves this.
 I'm not sure if it is a problem with Bootstrap or Angular but either way it makes the BS4 version of your demo less attractive.

**Comment by valorkin** [comment]
thanks! BTW I will appreciate PR to fix it ;)

https://github.com/valor-software/ng2-bootstrap/tree/development/demo/src/app/components/%2Brating/demos

how to run locally
```bash
npm i
npm run build
npm run link
npm start
```
