### ISSUE TITLE
Hide calender and add calender icon in date picker 

### ISSUE THREAD

**Issue by sanushakya** [valor-software/ngx-bootstrap#1638]
Trying to hide the date picker when we select the date and add icon add calender in right side of date picker. If anyone have any idea how we can do this using this ng2-bootstrap only.

**Comment by valorkin** [comment]
you are speaking about date picker input control
it could be actually done with bootstrap.css mainly
+ something from https://github.com/valor-software/ng2-bootstrap/issues/461
