### ISSUE TITLE
feature(Typeahead): multiple support?

### ISSUE THREAD

**Issue by DethAriel** [valor-software/ngx-bootstrap#1646]
I would love to see multiplicity in TypeAhead, which would essentially allow it to be a tagging component. I believe you've pretty much got all the pieces, so why not, right? :)

**Comment by valorkin** [comment]
actually I am working on, just need to finish with datepicker first ;)

**Comment by valorkin** [comment]
there were same issue before, so just closing for now
join slack or follow me at tweeter to get updates ;)
