### ISSUE TITLE
Carousel not working with angular-cli

### ISSUE THREAD

**Issue by SoftwareAndOutsourcing** [valor-software/ngx-bootstrap#1649]
I found the following issue while integrating a carousel into a new angular-cli project.

Steps to reproduce:

- Install @angular/cli 1.0.0-beta.31.
- Create a new project with `ng new`.
- Install bootstrap as described in https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/include-bootstrap.md.
- Install ng2-bootstrap 1.3.3. with npm.
- Setup the module and copy and paste the 'Dynamic Slides' example from http://valor-software.com/ng2-bootstrap/#/carousel#dynamic into the app.

When running the app, I get an `Expression has changed after it was checked. Previous value: 'undefined'. Current value: '0'.` exception in the browser console. I can provide a sample repository if needed.

**Comment by valorkin** [comment]
I will try to reproduce, BTW this http://valor-software.com/ng2-bootstrap/#/carousel
build with @angular/cli too

**Comment by SoftwareAndOutsourcing** [comment]
I upgraded to @angular/cli 1.0.0-beta.32.3 released yesterday, and I can reproduce the issue with that version.

**Comment by SoftwareAndOutsourcing** [comment]
I'm still able to to reproduce the issue with angular/cli@1.2.0 and ngx-bootstrap@1.7.1 Seems the issue only happens when building the development version, building with `--prod` works fine.

I created a demo repo at https://github.com/SoftwareAndOutsourcing/ngx-bootstrap-cli-carousel-demo. @valorkin could you take a look?

Thanks.
