### ISSUE TITLE
No provider for DropdownDirective

### ISSUE THREAD

**Issue by CodeguruEdison** [valor-software/ngx-bootstrap#1652]
Below code works, while dropdownMenu in same component. but it does not work, if we split dropdownMenu to another component.

`<nav class="navbar navbar-default navbar-static-top">
  <div class="collapse navbar-collapse" id="collapse-navbar">
  <ul class="nav navbar-nav">
    <li *ngFor="let menu of menus;let i = index;let firstItem = first; "  [ngClass]="{ active: firstItem }"   dropdown >
       <a [routerLink]="[menu.navigationPath]"
         dropdownToggle="menu.hasSubMenu"
         role="button" aria-haspopup="true"
         aria-expanded="false">
        <i [ngClass]="menu.iconCssclass"  class="icon-business_center"></i>{{menu.text}}<span [class.caret]="menu.hasSubMenu"></span>
      </a>
     
      <ul dropdownMenu >
        <li>
        asdasd
        </li>
        <li>
          asdasd
        </li>
      </ul>

    </li>
  </ul>

  </div>
</nav>`

if i am trying to  move dropdownMenu (section below )to another component, it throws exception No Provider for dropdowndirective
`<ul dropdownMenu >
        <li>
        asdasd
        </li>
        <li>
          asdasd
        </li>
      </ul>`
![image](https://cloud.githubusercontent.com/assets/10437792/22997121/40d7d0aa-f39f-11e6-86d1-fe7338697d63.png)

**Comment by valorkin** [comment]
`dropdownMenu` should be inside of `dropdown` marked element, like in docs
the reason of such behaviour:
https://github.com/valor-software/ng2-bootstrap/blob/development/src/dropdown/dropdown-menu.directive.ts#L18
