### ISSUE TITLE
feat(datepicker): Add support for disabling weekends

### ISSUE THREAD

**Issue by pgamilde** [valor-software/ngx-bootstrap#1657]
I was looking into the Datepicker component but I can't seem to find an option to disable weekends.
It would be nice to have this.

Thanks

**Comment by guyspr** [comment]
The best way to handle this (in my opinion) would be to allow disabling certain weekdays. That would cover all scenarios, somewhat the same as setting the startingDay

**Comment by valorkin** [comment]
I will keep this in mind,
while working on new datepicker (new style and pop up version)
available in v1.9.0+
check this out: http://valor-software.com/ngx-bootstrap/#/datepicker#examples

**Comment by udaymandava** [comment]
Hi,
Is there an option that I can pass an array of dates and they will be disabled in the calendar

**Comment by RajaPraba** [comment]
When could we expect a release of this feature?

**Comment by ruchitp** [comment]
@valorkin  Guys, any update on this feature.
I really need this ASAP.
If you can give some tentative date of release, I can give it to client.

**Comment by jnels124** [comment]
@valorkin  This seems like basic and critical functionality. I need this functionality and dont mind writing it if needed but there is no communication on here lately. What is the status of this feature?

**Comment by svlada84** [comment]
Do you have any progress for this feature? This is very import part of this control?

**Comment by valorkin** [comment]
Quite easy feature except for date range picker
You can do a PR or we could add to backlog for nearest releases
@domainv can ping Sveta to try to implement it

**Comment by ludmilanesvitiy** [comment]
Already implemented, example here: https://valor-software.com/ngx-bootstrap/#/datepicker#days-disabled

**Comment by ludmilanesvitiy** [comment]
Closed by https://github.com/valor-software/ngx-bootstrap/pull/4491
