### ISSUE TITLE
How can I create element with tooltipHtml programmatically??

### ISSUE THREAD

**Issue by haengjin** [valor-software/ngx-bootstrap#1658]
I should create span element programmatically and attach dom.
for example,
 document.createElement('span');

I want to add tooltipHtml to span element.
in document, when use [tooltip] or [tooltipHtml] in html file, developer use tooltipHtml.

But I have to set '[tooltipHtml]' template property in ts file.
How can I create element with tooltipHtml programmatically??

**Comment by valorkin** [comment]
this should help http://valor-software.com/ngx-bootstrap/#/tooltip#dynamic-html
