### ISSUE TITLE
Using datepicker component as input

### ISSUE THREAD

**Issue by karolisgrinkevicius** [valor-software/ngx-bootstrap#1663]
Hello there!
There is no documentation how to use datepicker component as input. Only inline datepicker is available at the moment as far as I can see. Is it possible to make it work as input?
Thanks.

**Comment by vinothinivenkatesan** [comment]
Is there any solution to enable datepicker in input?

**Comment by alami2010** [comment]
https://github.com/valor-software/ng2-bootstrap/issues/1455
check this , it support input and icon show hide

**Comment by valorkin** [comment]
added documentation for new datepicker,
and how to use it with inputs
available in v1.9.2
http://valor-software.com/ngx-bootstrap/#/datepicker
