### ISSUE TITLE
e2e error

### ISSUE THREAD

**Issue by ctrl-brk** [valor-software/ngx-bootstrap#1665]
Is it working? I have problems with `npm run e2e`
First issue was `SpecReporter is not a constructor` which I fixed by replacing
`require('jasmine-spec-reporter')` to `require('jasmine-spec-reporter').SpecReporter` in `proctractor.conf.js` as stated here: https://github.com/lathonez/clicker/issues/205#issuecomment-270268257
Now I'm getting `Cannot find namespace 'webdriver'`

**Comment by SergeyKuryatnick** [comment]
Hi!
e2e test are not works for now.
They will be fixed after refactoring.
