### ISSUE TITLE
A working Modal project?

### ISSUE THREAD

**Issue by locohost** [valor-software/ngx-bootstrap#1668]
There is not enough documentation here to actually build a working ng2-bootstrap Modal and there is no example project here either. I've been trying to find a working ng2-bootstrap Modal example for quite a while with zero to very little success. Found a couple things on SO, but of course the code is never complete  there and most of the time the plunkers don't work. Is there a working plunker you can point me to? Thank you! :-)

**Comment by GuskiS** [comment]
Have you tried http://valor-software.com/ngx-bootstrap/#/ ?

**Comment by IlyaSurmay** [comment]
http://valor-software.com/ngx-bootstrap/#/modals
There you'll find everything you need to start working with modals.
