### ISSUE TITLE
Dropdown not working with bootstrap 4.0.0 alpha 6 with ng-bootstrap 1.3.3

### ISSUE THREAD

**Issue by martijnbrands1978** [valor-software/ngx-bootstrap#1671]
This css is not working:
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"`

This bootsrap version is working:
`<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"`

With version 4 the dropdown doesn't open, it seems that the css classes not found.
```<div class="btn-group" dropdown>
  <button id="single-button" type="button" class="btn btn-primary" dropdownToggle>
    Button dropdown <span class="caret"></span>
  </button>
  <ul dropdownMenu role="menu" aria-labelledby="single-button">
    <li role="menuitem"><a class="dropdown-item" href="#">Action</a></li>
    <li role="menuitem"><a class="dropdown-item" href="#">Another action</a></li>
    <li role="menuitem"><a class="dropdown-item" href="#">Something else here</a></li>
    <li class="divider dropdown-divider"></li>
    <li role="menuitem"><a class="dropdown-item" href="#">Separated link</a></li>
  </ul>
</div>```

**Comment by kianfang** [comment]
not work +1

**Comment by DouglasWebster** [comment]
I suspect this is because Bootstrap 4 has dropped the automatic loading of glyphicons so the caret icon can not be found.  You need to download the icon set and reference it.

If you are interested it is the same problem as highlighted here **The glyphicon icons can't show with bootstrap4** #1659 where I showed a different way to get over this.

Sorry I can't tell you how to put in the glyphicons but I think it is documented somewhere on the repository..

**Comment by martijnbrands1978** [comment]
For Bootstrap 4 the class to open the dropdwon is "show" instead of "open". When I changed the file dropdown.directive.js ```class.open``` to ```class.show``` it is working.

**Comment by DouglasWebster** [comment]
From my reading of the code I don't think this should be necessary and I haven't had to do it in any of my projects.  It looks as though the dropdown directive checks if the window.__theme has been set to bs4  (or more specifically `window.__theme !=== 'bs4' `) and if so adds the show attribute to the class.  
Have you remembered to let ng2-bootsrap know you are using BS4? .  This can be done, for example, in the main index.html as follows:
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>My App</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>

<body>
  <!-- Enable bootstrap 4 theme -->
  <script>window.__theme = 'bs4';</script>

  <app-root> </app-root>
</body>
</html>
```
Once this is done then an inspection of a the dropdown div show both _open_ and _show_ in the class definition as shown below.
```
<div _ngcontent-mrv-42="" class="col-sm-2 btn-group dropdown show open active" dropdown="">
    <button _ngcontent-mrv-42="" class="btn btn-primary dropdown-toggle" dropdowntoggle="" 
```

Sorry for sending you down the wrong road earlier, although that still applies if you don't have glyphicons installed.

**Comment by martijnbrands1978** [comment]
Yess, when I put this in the index.html ```<script>window.__theme = 'bs4';</script>``` then it works. Thank you for that solution, I doesn't know that is, that anywhere documented? anyway now it works.
