### ISSUE TITLE
TimePicker : [showSpinners]="false" not working

### ISSUE THREAD

**Issue by industrylinq** [valor-software/ngx-bootstrap#1672]
"ng2-bootstrap": "1.3.3",

angular 2.4.8.

showMeridian  is working as expected, however if I try to hide the chevrons by setting showSpinners to false the chevrons are still their.

Although it seems that hidden is actualy added to the chevrons class. 

```
<tr class="text-center hidden" ng-reflect-klass="text-center" ng-reflect-ng-class="[object Object]">
          <td><a class="btn btn-link" ng-reflect-klass="btn btn-link" ng-reflect-ng-class="[object Object]"><span class="glyphicon glyphicon-chevron-up"></span></a></td>
          <td>&nbsp;</td>
          <td><a class="btn btn-link" ng-reflect-klass="btn btn-link" ng-reflect-ng-class="[object Object]"><span class="glyphicon glyphicon-chevron-up"></span></a></td>
          <!--template bindings={
  "ng-reflect-ng-if": "true"
}--><td ng-reflect-ng-class="[object Object]"></td>
        </tr>

```

**Comment by industrylinq** [comment]
I've placed showSpinner within a [hidden] tag instead of within the class and this seems to work perfectly. 


`                    template: "\n    <table>\n      <tbody>\n        <tr [hidden]=\"!showSpinners\" class=\"text-center\" [ngClass]=\"{hidden: !showSpinners || readonlyInput}\">\n 
`

**Comment by Uness77** [comment]
any hack to fix this problem  ? I was thinking about creating a TimePickerComponent but I was wondering if someone got an easier hack

**Comment by carlfarmer** [comment]
I got round this by simply adding the hidden class;

`.hidden {
  display: none;
}`

**Comment by kmaci3k** [comment]
Was the fix released in 1.9.3 version ? If so, it looks like [showSpinners]="false" still does not work.

**Comment by evilstiefel** [comment]
This still does not seem to work with Bootstrap 4.0.0 - [showSpinners]="false" has no effect on the display of arrows.

**Comment by nagos** [comment]
It does not work in bootstrap 4.
[bootstrap migration guide](https://getbootstrap.com/docs/4.0/migration/#responsive-utilities)

> The .hidden and .show classes have been removed because they conflicted with jQuery’s $(...).hide() and $(...).show() methods. Instead, try toggling the [hidden] attribute or use inline styles like style="display: none;" and style="display: block;".

Now you can use workaroudn
`.hidden { display: none; }`

P.S. I made pull request for this. #4197
