### ISSUE TITLE
feat(accordion): add keyboard support

### ISSUE THREAD

**Issue by vinothinivenkatesan** [valor-software/ngx-bootstrap#1675]
Unable to navigate to other accordion panels on tab key press. 
Is there any attribute to enable the functionality of **Tabindex**.

Thanks in Advance.

update: also would be nice to be able to open accordion panels by pressing `enter`

**Comment by 5earle** [comment]
will take a closer look at this

**Comment by jorgebfrr** [comment]
Hi everyone, first of all thanks for this question,
Do you know how I can implement this? 
I cannot see anything related to the changes made so I can use the tabIndex and open the accordian with the enter button
