### ISSUE TITLE
ModalOptions.show property value is ignored

### ISSUE THREAD

**Issue by DethAriel** [valor-software/ngx-bootstrap#1680]
Based on documentation [here](http://valor-software.com/ng2-bootstrap/#/modals#modal-options), if `[options]="{ show: true }"` is provided, then the modal should be shown upon initalization. 
But this value is not even checked anywhere in [modal.component.ts](https://github.com/valor-software/ng2-bootstrap/blob/development/src/modal/modal.component.ts).

So, the option does not work. But it is a really nice one, since it allows to handle modals with `*ngIf` statements instead of `show() / hide()`

**Comment by DethAriel** [comment]
Also, based on https://github.com/valor-software/ng2-bootstrap/blob/development/src/modal/modal-options.class.ts#L26 this option has not really been working ever

**Comment by DethAriel** [comment]
If anyone else is interested, it can be work-arounded like this:

```ts
// place this somewhere, e.g. vendor.ts
import { ModalDirective, modalConfigDefaults } from 'ng2-bootstrap';

const nativeFn = ModalDirective.prototype.ngAfterViewInit;

modalConfigDefaults.show = false;
ModalDirective.prototype.ngAfterViewInit = function(this: ModalDirective) {
  nativeFn.apply(this, arguments);
  if (this.config.show) {
    this.show();
  }
}
```

**Comment by valorkin** [comment]
@DethAriel if you will make it as a PR
I will be very grateful ;)
