### ISSUE TITLE
Focus Trapping Inside Modal

### ISSUE THREAD

**Issue by anupriya1992** [valor-software/ngx-bootstrap#1683]
Hi,
I'm using your modal component and trying to trap the focus inside the modal for our accessibility requirement, but not able to get that work. Can you please guide me how do I fix this issue.
I'm using ng2 bootstrap,version 1.3.3

Thanks

**Comment by kalyan11021980** [comment]
@macroorganizm any update? I have seen u merged something

**Comment by SarikaVanapalli** [comment]
+1

**Comment by yogsadafal** [comment]
@macroorganizm  @SergeyKuryatnick any update on this?  is this feature going to be available soon?

**Comment by valorkin** [comment]
closing in favor of #1819 (duplicate)
