### ISSUE TITLE
Docs not working due to cloudflare issue

### ISSUE THREAD

**Issue by rodsimpson** [valor-software/ngx-bootstrap#1684]
On this page:

http://valor-software.com/ng2-bootstrap/

I get this error:

Error 1014 Ray ID: 335da17b4690587f • 2017-02-23 21:04:32 UTC
CNAME Cross-User Banned
What happened?
You've requested a page on a website that is part of the Cloudflare network. The host is configured as a CNAME across accounts on Cloudflare, which is prohibited by security policy.
What can I do?
If you are interested in learning more about Cloudflare, please visit our website.

**Comment by ruffiem** [comment]
I don't know what's wrong with that (pointing one domain to another?) but it looks like Cloudflare doesn't like it much lol

**Comment by valorkin** [comment]
works fine for me, can you reproduce issue?

**Comment by rodsimpson** [comment]
looks like it is working now
