### ISSUE TITLE
Alert succes styling issue

### ISSUE THREAD

**Issue by ewoutreinders** [valor-software/ngx-bootstrap#1690]
Setup:
- ng2 boostrap version 1.3.3
- bootstrap 4 alpha 6

Seems that styling of alert succes has been changed. Ng2 bootstrap refers to the class 'alert-succes' while it is known in bootstrap 4 alpha 6 as 'alert-success'. This results that succes alerts got no styling. All others works fine (danger, warning etc).

**Comment by valorkin** [comment]
Thing is, I don't control last part of styling :)
So check your code when you setting alert type

**Comment by ewoutreinders** [comment]
Yeah, was indeed a missprint from me :). My bad.

**Comment by valorkin** [comment]
No problem, it's second same issue :)
