### ISSUE TITLE
Angular 4.0.0-rc.1 <template> element is deprecated -> Typeahead not working

### ISSUE THREAD

**Issue by Martin-Luft** [valor-software/ngx-bootstrap#1692]
Since Angular 4.0.0-rc.1:
>The \<template\> element is deprecated. Use \<ng-template\> instead

The result is that you can't click on an item from the result list of the Typeahead component.

**Comment by valorkin** [comment]
I tried today 4.0.0-rc.2
minor changes are needed and it is starting to work
but it is kinda a breaking change
so I can publish it as @beta 
ok?

**Comment by Martin-Luft** [comment]
@valorkin beta ist OK :)

**Comment by conor-mac-aoidh** [comment]
@valorkin Thanks it would be useful to fix this deprecation error! Could you let us know when published? Cheers

**Comment by Martin-Luft** [comment]
@valorkin any news :) ?

**Comment by Martin-Luft** [comment]
@valorkin is working on that and he hopes that he can fix the whole problem this week...

**Comment by slubowsky** [comment]
FYI - Saw elsewhere -  https://github.com/valor-software/ng2-bootstrap/pull/1770 that ng4 beta is already available:
npm i -S ng2-bootstrap@beta

**Comment by valorkin** [comment]
Yes, it is. Unfortunately not compatible with AoT

**Comment by Martin-Luft** [comment]
FYI: 2.0.0-rc.0 fixed this!

**Comment by daBishMan** [comment]
Silly question how do I get the 2.0.0.rc-0 please?

**Comment by valorkin** [comment]
Install @beta

**Comment by keradus** [comment]
there are already 5 pages of issues about this single deprecation. Why you decided to fix it only in next major, that is not released?
It's extra small, could you please fix it with currently released major simply as bugfix? If there are dozens of users asking of this for few months, would be great to give them a smile...
Keep in mind that next, not stable, bc breaking release is not a solution for all users.

cc @valorkin @Martin-Wegner @fchiumeo

**Comment by ctrl-brk** [comment]
@keradus I guess the idea here is that version 1.x is dedicated to Angular 2.x. Angular >= 4 is covered by ngx-bootstrap@next

**Comment by valorkin** [comment]
@keradus when I say @next version, I am literally mean it:
npm install ngx-bootstrap@next
I am trying to solve as a many issues as possible without breaking changes, then merging them in @next version and publishing

**Comment by keradus** [comment]
yet, as `@next` is unstable, as you could see from history of 10 PR and 5 sites of bug report, a lot of ppl are using current release with angular 4 with ease , only encountering that one violation. And while current release is stable, we like to use it. While `@next` release may be nice, it's not there yet, it may or may not contains bc breakers, every time user install `@next` he may end up with a little different version...
is there an issue with updating that deprecation on 1.x line ?

**Comment by valorkin** [comment]
I can't do it in v 1.*
It's a breaking change
So it has to be v2
If only I had statics about ngx-bootstrap users,
Do they use v2 or v4 of angular
