### ISSUE TITLE
Typehead have result when is empty (image)

### ISSUE THREAD

**Issue by axelpcr** [valor-software/ngx-bootstrap#1694]
![untitled](https://cloud.githubusercontent.com/assets/15647420/23380789/7213c57e-fd3c-11e6-9a40-27343ccedc15.png)

Hi,
When I write data into the input and I delete all with backspace listbox is not empty.

It's bug or I d'ont understand documention ?

Best regards

**Comment by IlyaSurmay** [comment]
Perhaps you have `typeaheadMinLength=0`
Please provide plunkr/stackblitz with reproduction if this is still relevant.
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IlyaSurmay** [comment]
Closed for inactivity.
