### ISSUE TITLE
How to generate multi modal in ngFor

### ISSUE THREAD

**Issue by fanttm** [valor-software/ngx-bootstrap#1697]
I want to generate multi modal in ngFor as below:
```
<tr *ngFor="let c of user['cards']">
	<td>{{c.card_type}}</td>
	<td>{{c.card_number}}</td>
	......
	<td>
		<button type="button" class="btn btn-primary" (click)="showModal(c.id)">
			address
		</button>

		<div class="modal fade" bsModal #{{c.id}}="bs-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
	  		<div class="modal-dialog modal-lg">
	    		<div class="modal-content" ng-controller="userController">
			      	<address>
			      		{{c.street}} <span ng-show="c.apt!=null">apt: {{c.apt}}</span><br>
			      		{{c.city}}, <span ng-show="c.state!=null">{{c.state}},</span> {{c.zip}}<br>
			      	</address> 
		    	</div>
	  		</div>
		</div>
	</td>
</tr>
```
But I don't know how to write code to get modal element in showModal. 

By the way, I tried another method that  `(click)="c.id.show()"`, but it will be reported error. How can I modified it?

**Comment by IlyaSurmay** [comment]
You can't create dynamic template variables (see this comment for more info https://github.com/angular/angular/issues/4581#issuecomment-148786554)
As a possible solution you can create one modal and pass your data to it by some method.

**Comment by meetnscorp** [comment]
I was able to make it work by making id on ion-item and trigger on ion-modal same but unique to other ion-datetime withing ngFor,

```
        <ion-item [id]="'startDate-modal-'+i">
        </ion-item>

        <ion-modal [trigger]="'startDate-modal-'+i">
        </ion-modal>
```
