### ISSUE TITLE
Typeahead optionsListTemplate Not Working

### ISSUE THREAD

**Issue by 1-0-1** [valor-software/ngx-bootstrap#1701]
See https://github.com/valor-software/ng2-bootstrap/issues/1557
Issue 1557 is marked as a question but should be a bug since the issue was "fixed" but is still not working.

**Comment by valorkin** [comment]
it is fixed but not yet published
I will be publishing this later today
as 1.3.4

**Comment by valorkin** [comment]
oh, and question mark is a label for me, so I should answer a question or reread issue again ;)

**Comment by 1-0-1** [comment]
Thanks for the fix!  There was no comment in 1557 as to its status outside of the original question and no response to the points made that it wasn't working.  I'm happy now (other than the typeahead drop down not auto positioning when it goes out side the visible window, but that is another thread).
