### ISSUE TITLE
fix(popover): popover with triggers="focus" is not shown at Safari and Firefox

### ISSUE THREAD

**Issue by w3cways** [valor-software/ngx-bootstrap#1702]
`<a class="show-demand" popover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." triggers="focus"><span class="glyphicon glyphicon-plus"></span>{{item.iterationName}}</a>`

It can be show,but it can't dismiss on next click.

When I change "a" label into "button" label, it works.
Anyone notice this issue.

**Comment by Lyoko-Jeremie** [comment]
i use ```triggers="focus"``` in button, it not show. but only remove ```triggers="focus"``` , it work.
```ts
                <template #endTemplate>
                    xxxxxxx
                </template>
                    <button
                        class="form-control btn btn-primary"
                        type="button"
                        [popover]="endTemplate"
                        [popoverTitle]="'xxxxxpopoverTitle'"
                        [placement]="'left'"
                        [triggers]="'focus'"
                    >
                        xxxxxstring
                    </button>
```

and, the demo page dont work too.
http://valor-software.com/ng2-bootstrap/#/popover#dismiss

this may be a bug.
@valorkin

**Comment by Lyoko-Jeremie** [comment]
the same as #1721

**Comment by johaven** [comment]
Is there a temporary solution pending the fix ?

**Comment by valorkin** [comment]
ok, it seems to be as designed (by browsers)
just add `tabindex="1"` to your element
and it works

**Comment by johaven** [comment]
I tried but it doesn't work (on Firefox & Safari).
Google Chrome is ok with or without tabindex.

**Comment by tanmay22** [comment]
Any workaround for firefox?

**Comment by YevheniiaMazur** [comment]
Checked this issue at firefox version 57.0.4 and safari version 11.0.2, issue is not reproduced at demo.
