### ISSUE TITLE
How to use it with webpack?

### ISSUE THREAD

**Issue by gamesover** [valor-software/ngx-bootstrap#1704]
The home page said I need to refer to https://github.com/valor-software/ng2-bootstrap/tree/development/demo for webpack config. However, I did not find any webpack config file there. Kindly advice which exact file I shall look at. Thanks for your advice.

**Comment by valorkin** [comment]
yeah, we were using webpack
now we use webpack from @angular/cli https://github.com/valor-software/ng2-bootstrap/blob/development/docs/getting-started/ng-cli.md
