### ISSUE TITLE
How to style Typeahead options box

### ISSUE THREAD

**Issue by hassanasad** [valor-software/ngx-bootstrap#1705]
Hi, Now i do realize it might be out of scope of this package but i don't know where else to post this question: 

**How do i style the Typeahead options box?** 

Everytime i click in the inspector to inspect its styling it closes and remove the DOM object. I want to make it full length (that of the input box) and probably allow it to open above the input field. Any pointers please?

**Comment by 1-0-1** [comment]
The way that works best for me to be able to inspect the DOM is using Chrome and the Chrome Dev Tools.  As you have noticed, the minute you move from the page the menu goes away.  Here is the trick:
When the menu is open, hover over one of the menu items (not the input box) and then hit the [F8] key.  This will pause the code preventing the menu from going away and allow you to inspect the DOM.

**Comment by hassanasad** [comment]
@1-0-1 thanks man! its a perfect solution :)
