### ISSUE TITLE
Tooltip is not working with bootstrap 4.0.0 alpha 6

### ISSUE THREAD

**Issue by kuzyas** [valor-software/ngx-bootstrap#1708]
With last bootstrap css tooltip is not working
` <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">`
When i change it to alpha 5 or to bootstrap 3 everything works fine
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css">`

**Comment by dessalines** [comment]
I am getting this issue too. I notice the bs-tooltip-container is showing, but not the tooltip. 

EDIT: I can also confirm that the typeahead dropdown element shows up in the dom, but the dropdown isn't showing up.

**Comment by valorkin** [comment]
Try this https://github.com/valor-software/ng2-bootstrap/issues/1619

**Comment by dessalines** [comment]
Yes that did fix it, that's really strange. It would be good to add that to the ng2-bootstrap bs4 docs at the top somewhere, but the docs are down at the moment. http://valor-software.com/ng2-bootstrap/

**Comment by valorkin** [comment]
Guys deployed new version of VS site and forgot to set cname :)
Docs fixed
