### ISSUE TITLE
DataPicker - change only month CallBack

### ISSUE THREAD

**Issue by michalmw** [valor-software/ngx-bootstrap#1711]
Hello,

i need CallBack when user change month (just change navigating to another month).

E.x. on start i see July Month:
--> When user change month to another (next or prev) i need know that + what is now selected month.

Someone can help me?

**Comment by valorkin** [comment]
I will keep it in mind...
for new datepicker (new style and pop up version)
available in v1.9.0+
check this out: http://valor-software.com/ngx-bootstrap/#/datepicker#examples

**Comment by valorkin** [comment]
cleaning issues for roadmap
duplicate of #1153
