### ISSUE TITLE
Consider replacing the function or lambda with a reference to an exported function...

### ISSUE THREAD

**Issue by 1-0-1** [valor-software/ngx-bootstrap#1715]
I'm getting this error on build (angular-cli).  This only happens when I am using the modules in other modules.  I've tried bringing the reference up to app and using forRoot there but it hasn't helped.

Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in ...

**Comment by valorkin** [comment]
Show me your app.module file, it is pretty usually issue, but has nothing to-do with bootstrap

**Comment by 1-0-1** [comment]
If I remove ContactModule (and references to the component), the build is successful.  ContactModule makes use of the Modal component.

app.module

`
/* ANGULAR */
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, Injectable, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { HttpModule, BrowserXhr, JsonpModule } from '@angular/http';

/* 3RD PARTY */
import { SlimLoadingBarModule } from 'ng2-slim-loading-bar';
import { TooltipModule } from 'ng2-bootstrap';

/* APP */
import { routing } from './app.routing';
import { AppComponent } from './app.component';

/* SHARED */
import { ContactModule } from './shared/contact';
import { FooterComponent } from './shared/footer';
import { HeaderComponent } from './shared/header';

/* SERVICES */
import { InsightService, IOService, UserService, PortfoliosService, ProjectService } from './services';

/* ROUTED */
import { HomeComponent } from './home';
import { NotFoundComponent } from './shared/not-found';

@NgModule({
    declarations: [
        AppComponent,
        HeaderComponent,
        FooterComponent,
        HomeComponent,
        NotFoundComponent
    ],
    imports: [
        BrowserModule,
        HttpModule,
        JsonpModule,
        routing,
        ContactModule,
        TooltipModule.forRoot(),
        SlimLoadingBarModule.forRoot()
    ],
    providers: [
        InsightService,
        IOService,
        UserService,
        PortfoliosService, ProjectService
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    bootstrap: [AppComponent]
})
export class AppModule { }
`

contact.module
`
/* ANGULAR */
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';

/* 3RD PARTY */
import { ModalModule } from 'ng2-bootstrap';

/* SERVICES */
import { InsightService, IOService, UserService, EmailService } from '../../services';

/* SHARED */
import { ContactComponent } from './contact.component';
import { FormsElementsModule } from '../formselements';

@NgModule({
    declarations: [
        ContactComponent
    ],
    providers: [
        InsightService,
        IOService,
        UserService,
        EmailService
    ],
    imports: [
        CommonModule,
        ModalModule.forRoot(),
        FormsElementsModule
    ],
    exports: [ContactComponent, FormsElementsModule, CommonModule]
})
export class ContactModule { }
`

formselements.module
`
/* ANGULAR */
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { TooltipModule, TypeaheadModule } from 'ng2-bootstrap';

import { FormsService } from '../../services/forms.service';

/* SHARED */
import { InputComponent } from '../input';
import { TextareaComponent } from '../textarea';
import { FormlabelComponent } from '../formlabel';
import { SelectButtonComponent, SelectxButtonComponent } from '../select-button';
import { PeopleChooserModule } from '../people-chooser';
import { ProjectsChooserModule } from '../projects-chooser';

@NgModule({
    providers: [
        FormsService
    ],
    declarations: [
        InputComponent,
        TextareaComponent,
        FormlabelComponent,
        SelectButtonComponent,
        SelectxButtonComponent
    ],
    imports: [
        CommonModule,
        FormsModule,
        TooltipModule,
        TypeaheadModule.forRoot(),
        ReactiveFormsModule,
        PeopleChooserModule
    ],
    exports: [
        InputComponent,
        TextareaComponent,
        FormlabelComponent,
        SelectButtonComponent,
        SelectxButtonComponent,
        CommonModule,
        FormsModule,
        TooltipModule,
        ReactiveFormsModule,
        PeopleChooserModule,
        ProjectsChooserModule
    ]
})
export class FormsElementsModule { }
`

contact.component.html
`
<div bsModal #modalContact="bs-modal" class="modal fade" id="contactform-modal" role="dialog" tabindex="-1" data-backdrop="static" data-show="false" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">{{title}}</h4>
            </div>
            <form id="contact-form" [formGroup]="form">
                <div class="modal-body">
                    <app-formlabel [for]="controls.body" [forcontrol]="form.controls.body" [value]="controls.body.options.placeholder"></app-formlabel>
                    <app-textarea [(value)]="controls.body.value" [required]="controls.body.required" [options]="controls.body.options" formControlName="body"></app-textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" style="float: left;" class="btn btn-default" (click)="openEmail(false)">
                        Open as Email
                    </button>
                    <button type="button" class="btn btn-default" (click)="closeModal()">
                        Close
                    </button>
                    <button type="button" class="btn btn-primary" (click)="saveModal()" [disabled]="!form.valid">
                        Submit Request
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
`

contact.component.ts
`
import { Component, OnInit, EventEmitter, ViewContainerRef, ViewChild } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

import { ISubscription } from 'rxjs/Subscription';

import { ModalDirective } from 'ng2-bootstrap';
import { TextareaComponent, FormlabelComponent, FormsService } from '../formselements';

import { InsightService } from '../../services';
import { IUser, User } from '../../interfaces';

@Component({
    selector: 'app-contact',
    templateUrl: './contact.component.html',
    styleUrls: ['./contact.component.scss'],
    exportAs: 'bs-modal'
})
export class ContactComponent implements OnInit {
    @ViewChild('modalContact') public modalContact: ModalDirective;

    form: FormGroup;

    private subscriptions: ISubscription[] = [];
    private _buttonResultEmitter: EventEmitter<any> = new EventEmitter();
    private _valid = false;

    private value: string = '';
    private required: boolean = true;

    controls: any = {
        body: {
            value: '',
            required: true,
            options: {
                name: 'body',
                placeholder: '',
                minlength: -1,
                maxlength: -1
            }
        }
    };

    private _currentUser: IUser;
    private _el: string;
    private _recipientName = '';
    private _recipientEmail = '';

    public recipientName = '';
    public recipientEmail = '';

    public title: string = '';
    public subject: string = '';
    public message: string = '';
    public placeholder: string = '';

    constructor(private viewContainerRef: ViewContainerRef,
        private insightService: InsightService,
        private formsService: FormsService,
        private fb: FormBuilder) {
            this.insightService.currentUserObservable.subscribe((currentUser: IUser) => {
                this._currentUser = currentUser;
            });
    }

    ngOnInit() {
        this._el = this.viewContainerRef.element.nativeElement;

        this.form = this.fb.group({
            body: this.controls.body.value
        });

        this.subscriptions.push(this.formsService.registerFormErrors.call(this, this.form, this.controls));
    }

    ngOnDestroy() {
        this.subscriptions.forEach((subscription) => subscription.unsubscribe());
    }

    showModalBox(type: string, detail: any = { title: '', subject: '', placeholder: '' }, to?: IUser) {
        this._buttonResultEmitter = new EventEmitter();

        this.recipientName = to ? to.FullName : this._recipientName;
        this.recipientEmail = to ? to.Email : this._recipientEmail;

        let title: string = detail && detail.title ? detail.title : '',
            subject: string = detail && detail.subject ? detail.subject : '',
            message: string = detail && detail.message ? detail.message : '',
            placeholder: string = detail && detail.placeholder ? detail.placeholder : '';

        switch (type) {
            case 'request':
                title = 'Make a Request';
                placeholder = 'What would you like to request?';
                break;
            case 'issue':
                title = 'Report an Issue';
                placeholder = 'What would you like to report?';
                break;
            case 'feedback':
                title = 'Provide Feedback';
                placeholder = 'What would you like to let us know?';
                break;
            case 'question':
                title = 'Ask a Question';
                placeholder = 'What would you like to ask us?';
                break;
        }
        subject = (subject || title);

        this.title = title;
        this.subject = subject;
        this.message = message;
        this.controls.body.options.placeholder = placeholder;
        this.controls.body.value = '';

        this.modalContact.show();
        
        return this._buttonResultEmitter;
    }

    closeModal() {
        this.modalContact.hide();
        this._buttonResultEmitter.emit(false);
    }

    openEmail() {
        //send to email
        var mailTo = this.getMail();

        var url = 'mailto:' + mailTo.Recipient.Email + '?subject=' + mailTo.Subject + '&body=' + mailTo.Body.replace(/\n/g, '%0A'),
            mailto = window.open(url);

        setTimeout(() => {
            mailto.close();;
            this.closeModal()
        }, 400);
    }

    getMail(forSendMail: boolean = false) {
        //send to email
        let body = this.form.controls['body'].value;
        if (this.message) body = this.message + '\n\n' + body;
        let mailTo = {
            Recipient: this.insightService.environment.production ? { FullName: this.recipientName, Email: this.recipientEmail } : this._currentUser,
            Subject: this.subject,
            Body: forSendMail ? body.replace(/\n/g, '<br />') : body
        };
        
        return mailTo;
    }

    saveModal() {
        if (!this.form.valid) return;

        //send to email
        let mailTo: any = this.getMail(true);

        this.insightService.sendEmail({
            Recipients: [{ Email: mailTo.Recipient.Email, FullName: mailTo.Recipient.FullName }],
            CCRecipients: [],
            Subject: mailTo.Subject,
            Body: mailTo.Body
        });

        this.closeModal();

        this.clear();
    }

    clear() {
        this.form.reset();
    }
}
`

**Comment by valorkin** [comment]
problem is `Calling function 'makeDecorator',`  is a part of angular core
I have seen it couple of times, but was fixing it with clean install
try it too

**Comment by valorkin** [comment]
not sure how I can help with it

**Comment by 1-0-1** [comment]
FYI:  Updating to hopefully help some other poor fool pulling their hair out trying to resolve this.
Found my particular reason why I was getting this error.  This error apparently also happens when there are modules outside of the project folder.  I have a shared project that I keep modules that are being used in multiple projects.  I had an index.ts file in a mirrored directory structure pointing to the modules in the shared folder.  No issues are raised with component type files, but if referencing an @NgModule it would throw this error.
Adding a linked folder (mklink /J in Windows) pointing to the shared folder instead of using exported values in an index.ts file seems to fix the issue.
