### ISSUE TITLE
Updated to ng-cli rc-0 requires change of name to .angular-cli.json

### ISSUE THREAD

**Issue by DouglasWebster** [valor-software/ngx-bootstrap#1717]
With the latest development release you have moved on to@angular/cli 1.0.0-rc.0 whose CHANGELOG states that the angular-cli.json file should be renamed to .angular-cli.json and that the change is reflected in the karma..conf.js file.
You have updated the angular-cli.json to show the changes in the environment as per the CHANGELOG  but have left the file name as required by previous releases and left karma.conf.js unchanged.
At the moment building the package and running the demos both with and without the changes doesn't seem to have any effect. Would it not be prudent to make the changes before it does break the project?

**Comment by valorkin** [comment]
Sure, nice reason for PR

**Comment by valorkin** [comment]
awesome, merged long ago
need to clean issues one day :)
