### ISSUE TITLE
ng2-bootstrap seems not to be activated

### ISSUE THREAD

**Issue by maartenmensink** [valor-software/ngx-bootstrap#172]
I am using the bundles file. 

./node_modules/ng2-bootstrap/bundles/ng2-bootstrap.js

The browser load the file and i see all System.registerDynamic nicely being processed without any js errors but when i try to use a component like Alert. 

My SearchCompoments gets activated and the template is displayed but the alert directive isnt activated. 

my project dependecies

```
"dependencies": {
    "jquery": "2.2.0",
    "angular2": "2.0.0-beta.5",
    "bootstrap": "3.3.6",
    "ng2-bootstrap": "1.0.3",
    "googlemaps": "1.2.0",
    "systemjs": "0.19.20",
    "rxjs": "5.0.0-beta.1"
  }
```

My compoment

```
import {Component,View, OnInit, Injectable, Inject, Output, EventEmitter} from 'angular2/core';
import {CORE_DIRECTIVES, FORM_DIRECTIVES} from 'angular2/common';
import { Alert} from 'ng2-bootstrap/ng2-bootstrap';

@Component({
    selector: 'search-compoment',
})

@View({
    templateUrl: 'SearchComponent.html',
    directives: [ Alert],

})

```

Template

  `<alert dismissOnTimeout="3000">This alert will dismiss in 3s</alert>
`

What am i missing?

Any help is much appreciated

**Comment by valorkin** [comment]
You forgot to add `Alerts` to `directives: [TYPEAHEAD_DIRECTIVES, CORE_DIRECTIVES, FORM_DIRECTIVES],`

**Comment by maartenmensink** [comment]
My bad copied the wrong code from test sample. I had a test sample based on the typeahead but that was causing more issues. So i opted to try with the simplest directive. 

Alert isn't showing/working either. Update the code in my previous post

**Comment by valorkin** [comment]
Sorry did not notice ng2 version
please check this repo
https://github.com/valor-software/angular2-quickstart
as far as I know beta5 is a bit brokean

**Comment by maartenmensink** [comment]
I reverted to beta3 still the same issue. Still no activation of the bundle. 

The weird part is if i put breakpoints in the bundle file it will break a System.register methods. So it looks like things are being register with SystemJS. So what could case the directives being ignored?

**Comment by kieranfraser** [comment]
I'm having the same issue as @maartenmensink. I'm using beta3 and have followed the steps in the quickstart and there still seems to be no activation of ng2-bootstrap.

My index.jade file:
`script(src='dist/lib/ng2-bootstrap.min.js')
      link(
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css",
      rel="stylesheet")

```
  // 2. Configure SystemJS
  script.
      System.config({
          defaultJSExtensions: true,
          packages: {
              dist: {
                  format: 'register',
                  defaultExtension: 'js'
              },
              app: {
                  format: 'register',
                  defaultExtension: 'js'
              }
          },
          map: {
              "moment": "dist/lib/moment",
              "angular2-jwt": "dist/lib/angular2-jwt",
              "ng2-bootstrap": "dist/lib/ng2-bootstrap.min"
          }
      });
```

In my component.ts:

/// <reference path="../typings/browser/definitions/moment/moment.d.ts" />
import {Component} from 'angular2/core';
import {Alert} from 'ng2-bootstrap';

@Component({
    selector: 'dashboard',
    directives: [Alert],
    template: `<alert type="info">ng2-bootstrap hello world!</alert>`
})
.....`

**Comment by valorkin** [comment]
Guys, please check readme
and configuration as simple as here
https://github.com/valor-software/angular2-quickstart/blob/master/index.html

**Comment by kieranfraser** [comment]
hey @valorkin, I've looked through the link you posted and still can't seem to get ng2-bootstrap working in my application. The only difference my app has is I'm using gulp to place the ng2-bootstrap.js file into a public/dist/lib folder instead of referencing from node_modules (as can be seen from the code I posted above). I'm also getting this error:

 Unexpected directive value 'undefined' on the View of component 'AppComponent'

which I think means that even though I'm importing Alert from ng2-bootstrap, it's not picking this up?

**Comment by valorkin** [comment]
you don't need this line in system.js map `"ng2-bootstrap": "dist/lib/ng2-bootstrap.min"`
add link to ng2-bootstrap in html instead

**Comment by valorkin** [comment]
plus this one
`import {Alert} from 'ng2-bootstrap';`
it should be 
`import {Alert} from 'ng2-bootstrap/ng2-bootstrap';`

**Comment by kieranfraser** [comment]
I have tried it but it raises another error saying that no file could be found at
`'ng2-bootstrap/ng2-bootstrap'`
I have mapped `'ng2-bootstrap'` in system.config, so I think the way I have it is correct:
`map: {
              "moment": "dist/lib/moment",
              "angular2-jwt": "dist/lib/angular2-jwt",
              "ng2-bootstrap": "dist/lib/ng2-bootstrap.min"
          }`

**Comment by kieranfraser** [comment]
Perfect, working now. I missed your previous comment:

> you don't need this line in system.js map "ng2-bootstrap": "dist/lib/ng2-bootstrap.min"
> add link to ng2-bootstrap in html instead

Thanks for your help @valorkin !! :)

**Comment by valorkin** [comment]
Awesome! :)

**Comment by valorkin** [comment]
I will close issue if not needed any more, but as a take away
it seems to be hard for new comers to consume 3rd party modules
with system.js

**Comment by imtiaz-emu** [comment]
Is it possible to load all components of `ng2-bootstrap` using `import 'ng2-bootstrap/ng2-bootstrap';` that command in angular2? I'm getting error using this code. @valorkin

**Comment by valorkin** [comment]
@imtiaz-emu you should be able to import all `directives` 
https://github.com/valor-software/ng2-bootstrap/blob/development/ng2-bootstrap.ts#L36
PS: may be array destructuring should be applied, let me check

**Comment by valorkin** [comment]
update, worked for me:
`import ng2b from 'ng2-bootstrap/ng2-bootstrap';`
in
`
@Component({
  selector: 'tabs-section',
  directives: [TabsDemoComponent, ng2b.directives, CORE_DIRECTIVES],`

**Comment by valorkin** [comment]
but I would not recommend to do so
