### ISSUE TITLE
tooltip always visible after mobile touche

### ISSUE THREAD

**Issue by chaouiy** [valor-software/ngx-bootstrap#1720]
when using tooltip and after clicking on a button the tool tip is alwaysvisible. any solutions ?

**Comment by valorkin** [comment]
touch something else?

**Comment by chaouiy** [comment]
can you reformulate your question ?

**Comment by valorkin** [comment]
so if you will try to touch anything else on mobile it is doesn't hides?

**Comment by valorkin** [comment]
I have opened doc http://valor-software.com/ng2-bootstrap/#/tooltip
from mobile and it works fine

**Comment by chaouiy** [comment]
yes it does hide after touching something else. but this is less user friendly

**Comment by valorkin** [comment]
ok, then I didn't understand you :)
what you want to achieve
screen shot could help

**Comment by chaouiy** [comment]
I want it to be hidden after touch (which is hover equivalent on desktop) and disepears right away user stop touching

**Comment by jlberrocal** [comment]
tooltips on mobile are not exactly the best for UX

**Comment by valorkin** [comment]
not you can configure `triggers` options of tooltips as you need

**Comment by prambhan** [comment]
hello all,

I am using carousel from this bootstrap module. Everything works fine, but in mobile devices I am not able to change the slides through touch and slide. Only way to change slides is to click on the arrow? Is there any builtin option or will it work on devices with touch?

Thanks
