### ISSUE TITLE
Popover triggers="focus" On Mozilla Firefox don't work

### ISSUE THREAD

**Issue by stevard6949** [valor-software/ngx-bootstrap#1721]
`<button type="button" class="btn btn-success"
        popover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus."
        popoverTitle="Dismissible popover"
        triggers="focus">
  Dismissible popover
</button>`
This code dont work on Firefox.

**Comment by valorkin** [comment]
closed as duplicate
