### ISSUE TITLE
Error: (SystemJS) global is not defined

### ISSUE THREAD

**Issue by karlhaas** [valor-software/ngx-bootstrap#1723]
We are using SystemJS and build a bundle by telling SystemJS in paths:
`'ng2-bootstrap': 'node_modules/ng2-bootstrap/bundles/ng2-bootstrap.umd.min.js'`

The bundle contains:
```
System.register("ng2-bootstrap/dropdown/dropdown.service.js", ["@angular/core"], function($__export) {
  "use strict";
  var Injectable,
      ALWAYS,
      DISABLED,
      OUTSIDECLICK,
      NONINPUT,
      KeyboardEvent,
      MouseEvent,
      DropdownService;
  return {
    setters: [function($__m) {
      Injectable = $__m.Injectable;
    }],
    execute: function() {
      ALWAYS = 'always';
      $__export("ALWAYS", ALWAYS);
      DISABLED = 'disabled';
      $__export("DISABLED", DISABLED);
      OUTSIDECLICK = 'outsideClick';
      $__export("OUTSIDECLICK", OUTSIDECLICK);
      NONINPUT = 'nonInput';
      $__export("NONINPUT", NONINPUT);
      KeyboardEvent = global.KeyboardEvent;
      MouseEvent = global.MouseEvent;
      DropdownService = (function() {
```

When we load the bundle, we get the following error:
```
Uncaught (in promise) Error: (SystemJS) global is not defined
	ReferenceError: global is not defined
```

Version: 1.4.0

**Comment by karlhaas** [comment]
The error does just occur when using AoT

**Comment by karlhaas** [comment]
The resulting bundle looks like:

```
System.register("ng2-bootstrap/dropdown/dropdown.service.js", ["@angular/core"], function($__export) {
  "use strict";
  var Injectable,
      ALWAYS,
      DISABLED,
      OUTSIDECLICK,
      NONINPUT,
      KeyboardEvent,
      MouseEvent,
      DropdownService;
  return {
    setters: [function($__m) {
      Injectable = $__m.Injectable;
    }],
    execute: function() {
      ALWAYS = 'always';
      $__export("ALWAYS", ALWAYS);
      DISABLED = 'disabled';
      $__export("DISABLED", DISABLED);
      OUTSIDECLICK = 'outsideClick';
      $__export("OUTSIDECLICK", OUTSIDECLICK);
      NONINPUT = 'nonInput';
      $__export("NONINPUT", NONINPUT);


      KeyboardEvent = global.KeyboardEvent;
      MouseEvent = global.MouseEvent;
      DropdownService = (function() {
        function DropdownService() {
          this.closeDropdownBind = this.closeDropdown.bind(this);
          this.keybindFilterBind = this.keybindFilter.bind(this);
        }
```

If I add the folloing code to the bundle:

```
  var global = this || self,
  GLOBAL = global;
```

it works as expected.

As already mentioned the problem just exists when compiling with AoT. In this case not the full ng2-bootstrap bundle is added.

**Comment by karlhaas** [comment]
@valorkin can you please check the comment https://github.com/systemjs/builder/issues/780#issuecomment-285295870 and provide a change?

**Comment by karlhaas** [comment]
Why do you need 

```
/* tslint:disable-next-line */
const KeyboardEvent = (global as any).KeyboardEvent as KeyboardEvent;
/* tslint:disable-next-line */
const MouseEvent = (global as any).MouseEvent as MouseEvent;
```

in https://github.com/valor-software/ng2-bootstrap/blob/development/src/dropdown/dropdown.service.ts

and

```
/* tslint:disable-next-line */
const MouseEvent = (global as any).MouseEvent as MouseEvent;
```
in https://github.com/valor-software/ng2-bootstrap/blob/development/src/dropdown/dropdown-toggle.directive.ts

Also found code like this in

- https://github.com/valor-software/ng2-bootstrap/blob/development/src/rating/rating.component.ts
- https://github.com/valor-software/ng2-bootstrap/blob/development/src/typeahead/typeahead.directive.ts

Could you please remove the global and provide a new version?

**Comment by valorkin** [comment]
it was needed for universal rendering,
because they didn't have Keyboard and Mouse Events

**Comment by karlhaas** [comment]
du you have a suggestion how to fix this?

**Comment by valorkin** [comment]
Replace it with any >.<

**Comment by karlhaas** [comment]
Can you please provide a modified version?

**Comment by valorkin** [comment]
you have found all usages, it is a nice reason for small PR ;)

**Comment by karlhaas** [comment]
https://github.com/valor-software/ng2-bootstrap/pull/1734

**Comment by valorkin** [comment]
removed in latest versions
