### ISSUE TITLE
feat(carousel): add custom template for carousel captions

### ISSUE THREAD

**Issue by Mercality** [valor-software/ngx-bootstrap#1727]
It would be nice to be able to pass a <template></template> to the carousel with a custom styled caption so we can set it at the top, at the sides, at the bottom depending on our apps.

**Comment by valorkin** [comment]
theming is one of the priorities I have
as you can guess supporting bs3 and bs4 templates requires some `magic`
and I want to make it magic less and simple

**Comment by ghost** [comment]
@Mercality you can make it by yourself using CSS styles
