### ISSUE TITLE
fix(timepicker): spinner doesn't fire change event

### ISSUE THREAD

**Issue by leeyikjiun** [valor-software/ngx-bootstrap#173]
The binding for timepicker spinner works but is there a way to get it to fire a change event?

**Comment by valorkin** [comment]
it should bind to ngModel
is it mutating Date object?

**Comment by leeyikjiun** [comment]
The `Date` object is mutated but I'm trying to inform another `Component` that the `Date` object has changed. Sadly, the `ngOnChanges` method only fires on reference change and not mutation. Hence, I want to trigger a `EventEmitter` from the "onChange" method of spinner.

I searched online and they said to implement my own `DoCheck` but the documentation is very limited.

I'm fairly new to Angular2, what's the right way to do what I mentioned above?

**Comment by temokallc** [comment]
Has a workaround been identified for this, I need this ability as well.
