### ISSUE TITLE
[TimePicker] Control icons are not showing

### ISSUE THREAD

**Issue by fxcosta** [valor-software/ngx-bootstrap#1732]
The control icons are not displayed. My project has glyphicons installed.

Angular: 2.4.9
Angular-cli: 1.0.0-rc.1
Node: 6.9.2

**Comment by valorkin** [comment]
could you provide more details?
if so I will reopen issue

**Comment by daniel-van-niekerk** [comment]
Any update on this? Mine also doesn't show.

**Comment by valorkin** [comment]
@daniel-van-niekerk work on demo, so
- which version of Bootstrap are you using?
- have you enabled bs4 theme if you are using bs4?

**Comment by daniel-van-niekerk** [comment]
I'm using Bootstrap v4.0.0-alpha.6

Yes I'm using  `<script>window.__theme = 'bs4';</script>` to enable bootstrap 4.

I've read that bootstrap 4 removed glyphicons and it must be added manually, which I've got from here [http://glyphicons.com/](http://glyphicons.com/).

Its up arrow looks like this: `<span class="glyphicons glyphicons-chevron-up"></span>` whereas the ngx-bootstrap time picker uses `<span class="glyphicon glyphicon-chevron-up"></span>`.

I'm not sure if I'm using the wrong icons or how to enable the ones required by ngx-bootstrap.

**Comment by valorkin** [comment]
try to use this one http://valor-software.com/ngx-bootstrap/assets/css/glyphicons.css
interesting point, most probably bs3 was using older version of icons

**Comment by daniel-van-niekerk** [comment]
Excellent, thank you.
