### ISSUE TITLE
onShown event doesn't fire

### ISSUE THREAD

**Issue by gentios** [valor-software/ngx-bootstrap#1735]
I am trying to catch the event onShow, or onShown, but that is not being fired, because I have a logic which I want to implement onInit, but the onInit is being fired when the template is being loaded so I want to catch the onShow or onShown to implement that logic for example:

I have this directive :` <user-modal [userList]="data" [selectedUserId]="selectedUserId"  (onShown)="handleModal()"></user-modal>`

and when I try to catch the event with handleModal() function, I got nothing not even an alert(1), so this function is not being called in this case. 

Is this an issue, or I am doing a wrong implementation, can someone of you help me out ?

Thanks

**Comment by maxgomes92** [comment]
I think you might have to pass in $event to your handleModal function.

(onShown)="handleModal($event)"

**Comment by gentios** [comment]
@maxgomes92  the modal catched the event on the body.


this issue should be closed
