### ISSUE TITLE
Pagination changing currentPage wrong when clicking on previous index buttons

### ISSUE THREAD

**Issue by mateuswetah** [valor-software/ngx-bootstrap#1737]
I have my pagination set like this, inside my component template:

```
  <pagination [totalItems]="totalItems" 
              (pageChanged)="loadPage(currentPage)" 
              [maxSize]=" maxButtons" 
              class="pagination-sm"
              [boundaryLinks]="true" 
              [rotate]="false"  
              [(ngModel)]="currentPagel"></pagination>
```
Then in my loadPage function I just put a `console.log(this.currentPage)` before doing some _http_ request to update my page info, which doesn't touch on my `currentPage` object, but do change my `totalItems`, even tough it's always to same amount.

What happens is that when clicking on the pagination buttons following the normal order everything goes fine (click on 1, console displays 1; click  on 2, console displays 2...). But if I go back clicking 1, it goes to 3... then if I just go to 5 it goes to 3 and it just messes up more and more ¬¬'

I am sure that `currentPage ` is not being changed in any other part of the code. What seems odd to me is that the index button seems to not be returning proper values...

ng2-bootstrap 1.4.0

My versions:
@angular/cli: 1.0.0-beta.31
node: 7.4.0
os: linux x64
@angular/cli: 1.0.0-beta.31
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/compiler-cli: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8

**Comment by DouglasWebster** [comment]
Have you set the change detection strategy for use elsewhere i.e. in a tabs component?  Pagination doesn't like the change detection strategy being set to OnPush and falls out of step.  I raised this in #1644 and they are aware of the problem and hopefully will fix it in a future update.
To see the effect the change detection strategy has go to the plunker referenced in #1644 and remove the line
`changeDetection: ChangeDetectionStrategy.OnPush,` 
 Once that is done the pagination works O.K.

**Comment by mateuswetah** [comment]
@DouglasWebster, thank you for the answer!

I wasn't using any specific Strategy, and testing the suggested one didn't solved my situation (although you did got it right that I was using Tabs component in my page u.u, should have mentioned that maybe).

BUT, I was able to find a solution to my problem, taking a good look at your Plunker. Now, instead of calling my `loadPage(currentPage)`, passing the  `currentPage` _number_, what I do is first I update this value:
```
...
  (pageChanged)="currentPage = $event.page; loadPage(currentPage);" 
...
```
And damn, that works. I found it weird cause I tought the `[(ngModel)]="currentPage"` was doing that job for me. Am I mistaking something here? I double checked and there's no moment in my code where I would modify the value of currentPage.

_P.S.: I noticed now that in my the Issue description is  `[(ngModel)]="currentPage**l**". I already removed that extra "l", this wasn't the problem._

**Comment by winnemucca** [comment]
@DouglasWebster @mateuswetah I have to ask about the how you are limiting items per page?  I have been able to get the pagination section to show up fine.  However, I am not able to limit the items per page.   I have the pagination selector just below my ***ngFor** repeater.  However, I am geting everything on one page.  No errors and the pagination module was loaded as a Root in `app.module.ts`

   <pagination 
                class="pagination-sm"
                [itemsPerPage]="15"
                [totalItems]="bigTotalItems" 
                [(ngModel)]="bigCurrentPage" 
                [maxSize]="maxSize" 
                [boundaryLinks]="true" 
                [rotate]="false" 
                (numPages)="numPages = $event">
            </pagination>

            maxSize:number = 15;
           bigTotalItems:number = 726;
           bigCurrentPage:number = 1;
           numPages:number = 0;

**Comment by mateuswetah** [comment]
@winnemucca, I didn't needed it, as I do a new _http_ request for a fixed amount of items every time I load a new page. Maybe the guys can come up with the correct solution for ng2-bootstrap, but what you could do is creating two arrays: _totalItemsArray_ and _pageItemsArray._ Your **ngFor**  would loop _pageItemsArray_ and it's content would be updated every time you load a new page, gathering data from _totalItemsArray_. You can adjust the offset based on the current page index and  the number of items per page that you wish.

**Comment by IlyaSurmay** [comment]
@mateuswetah sorry for late response :( `pageChanged` event is fired before the model changes, that's why you were getting old value when you were passing `currentPage` to a function - because at that moment this property wasn't changed yet.
