### ISSUE TITLE
Bootstrap 4 Modal Backdrop has the wrong CSS classes

### ISSUE THREAD

**Issue by cfsean** [valor-software/ngx-bootstrap#1742]
The classes attached to the modal are "modal-backdrop fade in show" when they should be "modal-backdrop fade show". This is causing the backdrop to display completely black.

Changing this line in ng2-bootstrap/src/modal/modal-backdrop.component.ts seems to resolve the issue
```typescript
public set isShown(value:boolean) {
    this._isShown = value;
    this.renderer.setElementClass(this.element.nativeElement, `${ClassName.IN}`, value);
    if (!isBs3()) {
      this.renderer.setElementClass(this.element.nativeElement, `${ClassName.SHOW}`, value);
    }
  }
```

```typescript
public set isShown(value:boolean) {
    this._isShown = value;
    
    if (isBs3()) {
      this.renderer.setElementClass(this.element.nativeElement, `${ClassName.IN}`, value);
    } else {
      this.renderer.setElementClass(this.element.nativeElement, `${ClassName.SHOW}`, value);
    }
  }
```

**Comment by valorkin** [comment]
please check this doc how to enable bootstrap 4 theme in ng2-bootstrap
this is what you was looking at in code ;)
https://github.com/valor-software/ng2-bootstrap/blob/development/docs/getting-started/bootstrap4.md

**Comment by cfsean** [comment]
Issue with black brackground in my app was due to css conflict but the code above is still valid and the "in" class should not be being added to BS4 modal.
