### ISSUE TITLE
Dropdown doesn't work with Bootstrap 4

### ISSUE THREAD

**Issue by grifin85** [valor-software/ngx-bootstrap#1744]
I have
 "bootstrap": "^4.0.0-alpha.5",
"ng2-bootstrap": "^1.4.0"

When I click by button menu doesn't open. I checked in console and saw that class **show** is not added.
For testing I'm using yours example code

**Comment by valorkin** [comment]
hey, we support bootstrap alfa.6
alfa.5 not supported already (5->6) had breaking changes
here is the doc to enable bs4 theme for ng2-bootstrap
https://github.com/valor-software/ng2-bootstrap/blob/development/docs/getting-started/bootstrap4.md
