### ISSUE TITLE
Typeahead Tab does not work as expected

### ISSUE THREAD

**Issue by joeoh1359** [valor-software/ngx-bootstrap#1748]
If the typeahead dropdown is open, and an item is active, then pressing tab should select the item and move to the next field.

Currently it is simply skipping to the next field.

**Comment by davey-h** [comment]
I agree. Was the tab key intentionally not included as a key that selects an option?

**Comment by GitVitor** [comment]
Useful issue

**Comment by brbeaird** [comment]
Agree - this is definitely needed.

**Comment by IlyaSurmay** [comment]
Closing as a duplicate of #2295

**Comment by chubbard** [comment]
Tab SHOULD skip to the next field.  This is confusing users, and causing errors because TAB never commits changes.  This is has been added, and removed several times why does it keep coming back?
