### ISSUE TITLE
Angular 2 Beta 6:  error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.

### ISSUE THREAD

**Issue by rexebin** [valor-software/ngx-bootstrap#175]
Hi, by upgrading to angular 2 beta 6, I got these errors from ng2-bootstrap 1.0.3: 
../node_modules/ng2-bootstrap/components/datepicker/datepicker-popup.ts(28,12): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
../node_modules/ng2-bootstrap/components/datepicker/datepicker-popup.ts(77,12): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
../node_modules/ng2-bootstrap/components/rating/rating.component.ts(77,26): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
../node_modules/ng2-bootstrap/components/tooltip/tooltip-container.component.ts(37,12): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
../node_modules/ng2-bootstrap/components/tooltip/tooltip-options.class.ts(11,12): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
../node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.ts(55,12): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
../node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.ts(136,83): error TS2339: Property 'repeat' does not exist on type 'string'.
../node_modules/ng2-bootstrap/components/typeahead/typeahead-options.class.ts(6,12): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.

I had some complaint from angular 2 too, but by adding 

> /// < reference path="../../node_modules/angular2/typings/browser.d.ts"/>

 to my app root file, all angular2 complaints went away, only the above ng2-bootstrap left.

Is there a work around available please?

Thanks, 

Rex

**Comment by valorkin** [comment]
hey
https://github.com/angular/angular/issues/7033

it is not work around, it is more about typescript stuff
just get use to it :)
if you see something missing try to install it from `typings`
prefer npm ones
PS: ng2-bootstrap not yet updated for beta.6

**Comment by rexebin** [comment]
What typings I need please? Could you kindly give me a little hint to make the errors go away so I could carry on compiling my code?

**Comment by valorkin** [comment]
https://github.com/angular/angular/issues/7033#issuecomment-183249303

```
npm install typings --global
typings install es6-shim --ambient --save
typings install require --ambient --save
```

**Comment by rexebin** [comment]
@valorkin Thank you. Installing Es6-shim and require typings, then

> ///< reference path="../../typings/browser.d.ts"/>

remove the angular brower.d.ts (duplicated definition), my ts are compiling without issues.

**Comment by valorkin** [comment]
awesome, I glad it helped :)

**Comment by StealthyDev** [comment]
Hi, I tried your fix, but it didn't fix my typings errors.

I use SystemJS and few additional information is in the screenshot below:

![ng2-bootstrap](https://cloud.githubusercontent.com/assets/2009963/13463368/ef81fc7a-e059-11e5-902e-f62e012e0ba4.png)

**Comment by StealthyDev** [comment]
thank you, it worked !

**Comment by deepakgd** [comment]
@rexebin  After installing es6-shim and require i am getting error:

```
ERROR in /home/dinesh/dev/angular2-seed-with-gulp/node_modules/angular2/typings/es6-promise/es6-promise.d.ts
(11,15): error TS2300: Duplicate identifier 'Promise'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/node_modules/angular2/typings/es6-promise/es6-promise.d.ts
(42,16): error TS2300: Duplicate identifier 'Promise'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/node_modules/angular2/typings/es6-collections/es6-collections.d.ts
(22,5): error TS2300: Duplicate identifier 'done'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/node_modules/angular2/typings/es6-collections/es6-collections.d.ts
(23,5): error TS2300: Duplicate identifier 'value'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/node_modules/angular2/typings/es6-collections/es6-collections.d.ts
(46,5): error TS2300: Duplicate identifier 'size'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/node_modules/angular2/typings/es6-collections/es6-collections.d.ts
(52,5): error TS2300: Duplicate identifier 'prototype'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/node_modules/angular2/typings/es6-collections/es6-collections.d.ts
(66,5): error TS2300: Duplicate identifier 'size'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/node_modules/angular2/typings/es6-collections/es6-collections.d.ts
(72,5): error TS2300: Duplicate identifier 'prototype'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/node_modules/angular2/typings/es6-collections/es6-collections.d.ts
(88,5): error TS2300: Duplicate identifier 'prototype'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/node_modules/angular2/typings/es6-collections/es6-collections.d.ts
(103,5): error TS2300: Duplicate identifier 'prototype'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/node_modules/angular2/typings/browser.d.ts
(6,14): error TS2300: Duplicate identifier 'PromiseConstructor'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/typings/es6-shim/es6-shim.d.ts
(9,5): error TS2300: Duplicate identifier 'done'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/typings/es6-shim/es6-shim.d.ts
(10,5): error TS2300: Duplicate identifier 'value'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/typings/es6-shim/es6-shim.d.ts
(475,11): error TS2300: Duplicate identifier 'Promise'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/typings/es6-shim/es6-shim.d.ts
(494,11): error TS2300: Duplicate identifier 'PromiseConstructor'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/typings/es6-shim/es6-shim.d.ts
(552,13): error TS2300: Duplicate identifier 'Promise'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/typings/es6-shim/es6-shim.d.ts
(561,5): error TS2300: Duplicate identifier 'size'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/typings/es6-shim/es6-shim.d.ts
(570,5): error TS2300: Duplicate identifier 'prototype'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/typings/es6-shim/es6-shim.d.ts
(581,5): error TS2300: Duplicate identifier 'size'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/typings/es6-shim/es6-shim.d.ts
(590,5): error TS2300: Duplicate identifier 'prototype'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/typings/es6-shim/es6-shim.d.ts
(605,5): error TS2300: Duplicate identifier 'prototype'.

ERROR in /home/dinesh/dev/angular2-seed-with-gulp/typings/es6-shim/es6-shim.d.ts
(619,5): error TS2300: Duplicate identifier 'prototype'.

```

**Comment by rexebin** [comment]
@deepakgd Hi, what I did for the similar errors is this: 
1. install typings: 
   npm install typings --global
   typings install es6-shim --ambient --save
   typings install require --ambient --save
2. at my angular bootstrap ts file, (boot.ts or main.ts etc, where you bootstrap your angular 2 root component), I have a line at the top: 

> /// < reference path="../../typings/browser.d.ts"/>

 and no other reference. Please make sure the relative path to the above brower.d.ts in your typings are correct, it may be different in your project.

Hope the above helps you.

Rex

**Comment by deepakgd** [comment]
Thanks @rexebin .In my project i am using tsd.d.ts. now i did 
`/// < reference path="../../typings/browser.d.ts"/>`

Now its working fine.

**Comment by rexebin** [comment]
@deepakgd Glade you are sorted.

**Comment by Slavrix** [comment]
Hey I've got the same issue here and I've followed the solution here al the way up to getting the error with with the duplicate identifiers.

I added the `/// < reference path="../../typings/browser.d.ts"/>` line to by bootstrap.ts file, but I still get the errors.

I started my project using the angular2-seed project, and it looks like that is where the duplicate is coming from.
The path is correct.

`
/// < reference path="../../typings/browser.d.ts"/>
// @if isProd
import {enableProdMode} from 'angular2/core';
enableProdMode();
// @endif

import {bootstrap} from 'angular2/platform/browser';
import {AppComponent} from './app';

bootstrap(AppComponent);
`
thats my bootstrap.ts file (have I put it in the wrong file?)
This is the whole error.

`[17:14:17] G:/gravity/tpaysite/node_modules/angular2/typings/browser.d.ts(5)
 Duplicate identifier 'PromiseConstructor'.
[17:14:17] G:/gravity/tpaysite/node_modules/angular2/typings/es6-collections/es6-collections.d.ts(21)
 Duplicate identifier 'done'.
[17:14:17] G:/gravity/tpaysite/node_modules/angular2/typings/es6-collections/es6-collections.d.ts(22)
 Duplicate identifier 'value'.
[17:14:17] G:/gravity/tpaysite/node_modules/angular2/typings/es6-collections/es6-collections.d.ts(45)
 Duplicate identifier 'size'.
[17:14:17] G:/gravity/tpaysite/node_modules/angular2/typings/es6-collections/es6-collections.d.ts(51)
 Duplicate identifier 'prototype'.
[17:14:17] G:/gravity/tpaysite/node_modules/angular2/typings/es6-collections/es6-collections.d.ts(65)
 Duplicate identifier 'size'.
[17:14:17] G:/gravity/tpaysite/node_modules/angular2/typings/es6-collections/es6-collections.d.ts(71)
 Duplicate identifier 'prototype'.
[17:14:17] G:/gravity/tpaysite/node_modules/angular2/typings/es6-collections/es6-collections.d.ts(87)
 Duplicate identifier 'prototype'.
[17:14:17] G:/gravity/tpaysite/node_modules/angular2/typings/es6-collections/es6-collections.d.ts(102)
 Duplicate identifier 'prototype'.
[17:14:17] G:/gravity/tpaysite/node_modules/angular2/typings/es6-promise/es6-promise.d.ts(10)
 Duplicate identifier 'Promise'.
[17:14:17] G:/gravity/tpaysite/node_modules/angular2/typings/es6-promise/es6-promise.d.ts(41)
 Duplicate identifier 'Promise'.
[17:14:17] G:/gravity/tpaysite/typings/main/ambient/es6-shim/index.d.ts(10)
 Duplicate identifier 'done'.
[17:14:17] G:/gravity/tpaysite/typings/main/ambient/es6-shim/index.d.ts(11)
 Duplicate identifier 'value'.
[17:14:17] G:/gravity/tpaysite/typings/main/ambient/es6-shim/index.d.ts(476)
 Duplicate identifier 'Promise'.
[17:14:17] G:/gravity/tpaysite/typings/main/ambient/es6-shim/index.d.ts(495)
 Duplicate identifier 'PromiseConstructor'.
[17:14:17] G:/gravity/tpaysite/typings/main/ambient/es6-shim/index.d.ts(553)
 Duplicate identifier 'Promise'.
[17:14:17] G:/gravity/tpaysite/typings/main/ambient/es6-shim/index.d.ts(562)
 Duplicate identifier 'size'.
[17:14:17] G:/gravity/tpaysite/typings/main/ambient/es6-shim/index.d.ts(571)
 Duplicate identifier 'prototype'.
[17:14:17] G:/gravity/tpaysite/typings/main/ambient/es6-shim/index.d.ts(582)
 Duplicate identifier 'size'.
[17:14:17] G:/gravity/tpaysite/typings/main/ambient/es6-shim/index.d.ts(591)
 Duplicate identifier 'prototype'.
[17:14:17] G:/gravity/tpaysite/typings/main/ambient/es6-shim/index.d.ts(606)
 Duplicate identifier 'prototype'.
[17:14:17] G:/gravity/tpaysite/typings/main/ambient/es6-shim/index.d.ts(620)
 Duplicate identifier 'prototype'.`

**Comment by StealthyDev** [comment]
I use SystemJS. Here are my config files. And I have `///<reference path="../typings/browser.d.ts"/>` in my bootstrap.ts. Make sure you have the latest version of Angular2 and TypeScript compiler installed.

`tsconfig.json`

```
{
  "compilerOptions": {
    "target": "ES5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "typings/main.d.ts",
    "typings/main",
    "node_modules"
  ]
}
```

`typings.json`

```
{
  "name": "doc-merge-client-ng2",
  "dependencies": {
    "moment": "github:typed-typings/npm-moment#a4075cd50e63efbedd850f654594f293ab81a385"
  },
  "devDependencies": {},
  "ambientDependencies": {
    "es6-shim": "github:DefinitelyTyped/DefinitelyTyped/es6-shim/es6-shim.d.ts#4de74cb527395c13ba20b438c3a7a419ad931f1c",
    "jquery": "github:DefinitelyTyped/DefinitelyTyped/jquery/jquery.d.ts#470954c4f427e0805a2d633636a7c6aa7170def8"
  }
}
```

Do `typings install` with this file.

**Comment by valorkin** [comment]
Please use latest bootstrap with beta 9

**Comment by rexebin** [comment]
I wrote a blog post regarding a setup for gulp-typescript, which would eliminate typescript compiler errors once for all: [https://pintoservice.wordpress.com/2016/03/29/gulp-typescript-for-angular-2-app/](url)
