### ISSUE TITLE
unable to get pagination to work with bootstrap panels.  

### ISSUE THREAD

**Issue by winnemucca** [valor-software/ngx-bootstrap#1756]
I hate asking this pagination question because it seems straightforward.  However, I have been unable to limit items per page and test out the pagination selector.  I have the component showing up correctly on my page.  Unfortunately all items are on the first page.  

I registered and imported the pagination module directly above the router module

    imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    PaginationModule.forRoot(),
    RouterModule.forRoot(appRoutes)

I literally started with an exact example from the documentation

   <div class="col-md-6">
            <pagination 
                class="pagination-sm"
                [totalItems]="bigTotalItems" 
                [(ngModel)]="bigCurrentPage" 
                [maxSize]="maxSize" 
                [boundaryLinks]="true" 
                [rotate]="false" 
                [itemsPerPage]="itemsPerPage"
                (numPages)="numPages = $event">
            </pagination>
        </div>

Just above the constructor I defined my properties like so

    maxSize:number = 5;
   bigTotalItems:number = 726;
   bigCurrentPage:number = 1;
   numPages:number = 0;
   itemsPerPage: number = 10;

However, items per page is not working.  Am I missing something?  Everything seems to be matching the documentation examples.

**Comment by DouglasWebster** [comment]
Don't know if this will help but the following [plunk](https://plnkr.co/edit/B4TIaIcmvyGYsI8vNGAs?p=preview) shows how to vary the number of pages.  The public `noOfItemsPerPage` variable in the src/app.module.ts file is read by the itemsPerPage attribute and alters the pages shown.  Just change the noOfItemsPerPage value and the number of pages shown should change.  Don't forget that a setting of <1 means that all items are shown on a single page.

**Comment by winnemucca** [comment]
@DouglasWebster I appreciate the plunker.  Not sure if I am following how you can get  setting of <1 if `noOfitemsPerPage` is defined.  I only ask as this would seem to be the issue.  Seemingly if you set the value on the attribute this shouldn't be a problem correct?
