### ISSUE TITLE
No Directive annotation found on Alert

### ISSUE THREAD

**Issue by opsxcq** [valor-software/ngx-bootstrap#176]
Using angular 2.0.0-beta.3, with ng2-bootstrap 1.0.3, while trying to create a simple example with an alert , I got the error message : No Directive annotation found on Alert.

Html:
`<alert type="info">ng2-bootstrap hello world!</alert>`

TS:

```
import {Component} from 'angular2/core';
import {Router, Route, RouteConfig, ROUTER_DIRECTIVES, Location} from 'angular2/router';
import {Alert} from 'ng2-bootstrap/ng2-bootstrap';
import {ROUTES} from './routes';

@Component({
    selector: 'simple-app',
    templateUrl: 'src/app.html',
    directives: [Alert],
    providers: []
})
@RouteConfig(ROUTES)
export class AppComponent {
    location: Location;
    currentPathStr = '';

    constructor(location: Location, router: Router){
        this.location = location;
        this.currentPathStr = '/home';
        router.subscribe((value) => this.currentPathStr = value);
    }
}
```

**Comment by jasonslyvia** [comment]
Hi @opsxcq , I came across this issue too, would you kind enough to tell me how do you solve it?

**Comment by valorkin** [comment]
try this one https://github.com/valor-software/angular2-quickstart

**Comment by benderillo** [comment]
@valorkin @opsxcq So guys, what is the actual reason for the error and how do I solve it without going to the link above and setting up a new project with quickstart repo?
I have pretty large project that uses angular2 and I just brought up ng2-bootstrap. And I am too having the error mentioned here but for the Collapse component.
How do I fix it?

**Comment by jasonslyvia** [comment]
@benderillo  I have to say it's currently unwise to use NG2 in a production app, it's not production ready and filled with hell loads of pitfalls. I've switched to React and Redux pattern and it just works fine.

**Comment by valorkin** [comment]
@benderillo we using webpack for prod and big apps, and no problems
system.js is usually 10-20% bigger than webpack bundles
