### ISSUE TITLE
How to use ng2-bootstrap with webpack ? 

### ISSUE THREAD

**Issue by santoshkt** [valor-software/ngx-bootstrap#1762]
I generated an application using jHipster. So I use webpack for configuration. I can't figure out how to use ng2-bootstrap with webpack. I saw there are few questions here already but none of the responses in them provide clear instructions on what exactly needs to be done. It is very frustrating to not being able to use such a popular library.

**Comment by paulbonner** [comment]
I've been using ng2-bootstrap in a Webpack/Angular project (based on this seed: https://github.com/preboot/angular2-webpack) for a couple of months, and I really haven't had to take any extra steps to make it work.  After doing an npm install per the ng2-bootstrap readme, I included a link to the Bootstrap CSS CDN in my index.html file, and imported the ng2 bootstrap modules I wanted into one of the @NGModules in my project. (I happened to have a SharedComponentsModule for just such a purpose, but AppModule would serve just as well) 

Here are teh changes I made to my NgModule:
1) Import the bootstrap modules:
import { PopoverModule, AlertModule, ModalModule } from 'ng2-bootstrap';

2) Add the bootstrap modules into the @NgModule's imports: section :

imports: [
    AlertModule.forRoot(),
    ModalModule.forRoot(),
   PopoverModule.forRoot(),
   ...
]

3) Add the modules to the NgModule's exports: section:
exports: [
AlertModule,
ModalModule,
PopoverModule,
...
]

That's literally all the setup I had to do, none of which was Webpack specific. I didn't need to do anything else to use the bootstrap components in my templates.

**Comment by santoshkt** [comment]
Thank you for responding. I did similar steps as mentioned but I did not had to export. The biggest mistake I did was that I did not use the directive in the html after all this.

For any one coming to this page from jHipster generated project.

1. Add ng2-bootstrap in package.json
2. Add import 'ng2-bootstrap' in vendor.ts
3. If you are using bootstrap using package.json, import the bootstrap.css location in vendor.css
4. import { SomeModule } from 'ng2-bootstrap'; in app.module.ts
5. Add the imported module into @NgModule imports in app.module.ts but use forRoot for the module.
6. Use the directive from the module in your html files. Please not that directive names are different in ng2-bootstrap and ng-bootstrap.
