### ISSUE TITLE
How to apply custom styling to the pagination component?

### ISSUE THREAD

**Issue by jdeblander** [valor-software/ngx-bootstrap#1766]
I'm using the[ pagination component](http://valor-software.com/ng2-bootstrap/#/pagination#pagination-component) and I want ato apply my own styling to the component. In the documentation is saw there was something like `pageBtnClass` provided but I'm using the following line and it 
```
<pagination class="pull-right-sm" [boundaryLinks]="true" [maxSize]="5" [rotate]="true" 
[itemsPerPage]="values.maxNumberOfRowsPerPage" [totalItems]="values.totalNumberOfRows" 
[ngModel]="values.currentPage [pageBtnClass]="myCustomClass" (pageChanged)="update($event)" 
previousText="&lsaquo;" nextText="&rsaquo;" firstText="&laquo;" lastText="&raquo;"></pagination>
```

This should add the class "**myCustomClass**" to the list in the pagination component. But it seems nothing even is added to the class of every list item.

**Comment by Zak-C** [comment]
I am also finding that I am unable to override the default pagination styles (V2.0.0-rc.0).

**Comment by egkozlov** [comment]
You can use /deep/ feature of Angular https://angular.io/docs/ts/latest/guide/component-styles.html as a workaround.

`/deep/ .page-link {
  color: red !important;
}`
I added it in the wrapper styles file and it changed number color
