### ISSUE TITLE
typeahead with angular 4.0.0-rc.3. Template is depracated in v4

### ISSUE THREAD

**Issue by vovikdrg** [valor-software/ngx-bootstrap#1767]
I am getting an error in typeahead

 "@angular/animations": "^4.0.0-rc.3",
    "@angular/common": "^4.0.0-rc.3",
    "@angular/compiler": "^4.0.0-rc.3",
    "@angular/compiler-cli": "^4.0.0-rc.3",
    "@angular/core": "^4.0.0-rc.3",
    "@angular/forms": "^4.0.0-rc.3",
    "@angular/http": "^4.0.0-rc.3",
    "@angular/platform-browser": "^4.0.0-rc.3",
    "@angular/platform-browser-dynamic": "^4.0.0-rc.3",
    "@angular/platform-server": "^4.0.0-rc.3",
    "@angular/router": "^4.0.0-rc.3",
    "ng2-bootstrap": "^1.4.1",

Error

The <template> element is deprecated. Use <ng-template> instead ("

[ERROR ->]<template [ngTemplateOutlet]="optionsListTemplate || (isBs4 ? bs4Template : bs3Template)"
  [ngOutlet"): TypeaheadContainerComponent@2:0
The <template> element is deprecated. Use <ng-template> instead ("

[ERROR ->]<template #bsItemTemplate let-match="match" let-query="query"><span [innerHtml]="hightlight(match, qu"): TypeaheadContainerComponent@6:0
The <template> element is deprecated. Use <ng-template> instead ("

[ERROR ->]<template #bs3Template>
<ul class="dropdown-menu">
  <template ngFor let-match let-i="index" [ngForOf"): TypeaheadContainerComponent@9:0
The <template> element is deprecated. Use <ng-template> instead ("
<template #bs3Template>
<ul class="dropdown-menu">
  [ERROR ->]<template ngFor let-match let-i="index" [ngForOf]="matches">
    <li *ngIf="match.isHeader()" class=""): TypeaheadContainerComponent@11:2
The <template> element is deprecated. Use <ng-template> instead ("selectActive(match)">
      <a href="#" (click)="selectMatch(match, $event)" tabindex="-1">
        [ERROR ->]<template [ngTemplateOutlet]="itemTemplate || bsItemTemplate" 
          [ngOutletContext]="{item:mat"): TypeaheadContainerComponent@15:8
The <template> element is deprecated. Use <ng-template> instead ("

[ERROR ->]<template #bs4Template >
<template ngFor let-match let-i="index" [ngForOf]="matches">
   <h6 *ngIf="m"): TypeaheadContainerComponent@24:0
The <template> element is deprecated. Use <ng-template> instead ("

<template #bs4Template >
[ERROR ->]<template ngFor let-match let-i="index" [ngForOf]="matches">
   <h6 *ngIf="match.isHeader()" class="d"): TypeaheadContainerComponent@25:0
The <template> element is deprecated. Use <ng-template> instead ("dex" [ngForOf]="matches">
   <h6 *ngIf="match.isHeader()" class="dropdown-header">{{match}}</h6>
   [ERROR ->]<template [ngIf]="!match.isHeader()">
      <button
        class="dropdown-item"
"): TypeaheadContainerComponent@27:3
The <template> element is deprecated. Use <ng-template> instead ("
        (mouseenter)="selectActive(match)"
        [class.active]="isActive(match)">
          [ERROR ->]<template [ngTemplateOutlet]="itemTemplate || bsItemTemplate" 
            [ngOutletContext]="{item:m"): TypeaheadContainerComponent@33:10

**Comment by Martin-Luft** [comment]
Duplicate of https://github.com/valor-software/ng2-bootstrap/issues/1692
