### ISSUE TITLE
timepicker model not updates on direct text input modification

### ISSUE THREAD

**Issue by scopsy** [valor-software/ngx-bootstrap#1769]
When using timepicker and updating the minutes field directly using the text field the model is not updated. Is there away to get the new value (exactly the same when clicking the arrow)

**Comment by temokallc** [comment]
I'm having the same issue, what did you do to fix it?

**Comment by connormcl** [comment]
I'm also having this issue, how did you fix it?

**Comment by SlippySken** [comment]
Same issue here, is there some possibility to get that behaviour?
