### ISSUE TITLE
docs(popover): add detailed description of triggers for popover module

### ISSUE THREAD

**Issue by flea19** [valor-software/ngx-bootstrap#1772]
I'm trying to understand how the triggers work for the popover module but there is not much documentation. I know the default is "click" but I can only guess that this means that on click it simply toggles between hidden and shown. What if I have two triggers, say "focus blur". I would assume this means that popover shows on focus and hides on blur but this is not the case. If I click inside of the popover it closes.

**Comment by valorkin** [comment]
agreed need a doc
just in case, triggers binds only to target (toggle element)
same for tooltips and popover

**Comment by danielordonez** [comment]
Would be nice to see detailed documentation on this feature

**Comment by ghost** [comment]
@flea19 it was added a [section](https://valor-software.com/ngx-bootstrap/#/popover#triggers-custom). I think it will help you. 

`What if I have two triggers, say "focus blur". I would assume this means that popover shows on focus and hides on blur but this is not the case. If I click inside of the popover it closes.`
It means that popover shows if the input element gets focus and popover hides if the input element loses focus (that is by clicking on any item outside input element).
