### ISSUE TITLE
Can't use *ngIf to dynamically add/remove tabs

### ISSUE THREAD

**Issue by Dan203** [valor-software/ngx-bootstrap#1774]
If you add an *ngIf to a tab and then dynamically change the value the *ngIf is watching then the contents of the tab go away, but the header of the tab just keeps getting added over and over. I believe this is because you transclude the "heading" over to an element outside of the element you actually use for the tab contents. 

Not sure if this is possible, but could you also transclude the *ngIf from the tab element over to the header element so that both are hidden/added when the property changes?

**Comment by pradeepgill007** [comment]
Same Issue here.
Tab heading goes on adding, previous heading are not getting removed and new heading goes on adding.

**Comment by shoudaos** [comment]
+1

**Comment by biwano** [comment]
+1

**Comment by manofearth** [comment]
Here is a plunkr: http://plnkr.co/edit/QDKYjJ55gOgiYrWvW6za?p=preview (try to press "Toggle Last Tab" buttons)
Same for *ngFor directive

**Comment by manofearth** [comment]
Some workaround: you can drop out from DOM whole tabset with ngIf, and render it again on next tick. But it is visible for a user - tabset blinks for a moment.

Here is plunkr with workaround: http://plnkr.co/edit/AHkcptOzEgvN7or0mq3H?p=preview

**Comment by jtandrew** [comment]
+1  I will look over the workaround and see if I can get this to work

**Comment by IlyaSurmay** [comment]
Seems to be fixed in 1.8.1
http://plnkr.co/edit/T0aD1BFgxTbCAFJbhvjb?p=preview

**Comment by Dan203** [comment]
No it's not. Try putting an ngif on the first tab. It automatically moves it to the end. What I want is the ability to show/hide tabs anywhere in the list, not just the end. 

Your sample is exactly how it's always worked.

**Comment by zhouxy0809** [comment]
I have the same issue. But i find *ngIf directive make tabs hided when the component variable is  undefined, and hide feature failed when the component variable is true or false.

**Comment by ShadowQueen** [comment]
Same Issue here.
Tab heading goes on adding, previous heading are not getting removed and new heading goes on adding.
