### ISSUE TITLE
Error loading rxjs as "rxjs" from ng2-bootstrap-modal/dist/dialog.component.js

### ISSUE THREAD

**Issue by ToshanP** [valor-software/ngx-bootstrap#1777]
Hi I am trying to use ng2-bootstrap. I am following the example in this plnkr

https://plnkr.co/edit/MB6NnzfhicMyAiMJy6YM?p=preview

I am getting Error loading rxjs as "rxjs" from ng2-bootstrap-modal/dist/dialog.component.js error when I start my application.

Below is my system.config.js

/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'application',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

            //ng2-validation
            'ng2-validation': 'npm:ng2-validation/bundles/ng2-validation.umd.js',

            // devextreme & devextreme deps
            'devextreme': 'npm:devextreme',                
            'jquery': 'npm:jquery/dist/jquery.min.js',     
            'jszip': 'npm:jszip/dist/jszip.min.js',        
            'devextreme-angular': 'npm:devextreme-angular',

            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',

            //bootstrap and ng2-bootstrap-modal
            'ng2-bootstrap-modal': 'npm:ng2-bootstrap-modal',
            'bootstrap': 'npm:bootstrap/dist/js/bootstrap.min.js',
    },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js'
            },
            'devextreme-angular': {
                main: 'index.js',
                defaultExtension: 'js'
            },
            'devextreme': {
                defaultExtension: 'js'
            },
            'ng2-bootstrap-modal': {
                main: 'index.js',
                defaultExtension: 'js'
            }
        }
    });
})(this);

Please help.

Regards

Toshan

**Comment by valorkin** [comment]
we don't have dialog component ;)
