### ISSUE TITLE
Issue TypeError in ng2-bootstrap.umd.min.js still exists

### ISSUE THREAD

**Issue by ttchongtc** [valor-software/ngx-bootstrap#1779]
I keep getting the error below even after trying the solution you suggested in the other issue (that you closed.) I got the latest angular, zone, and reflect-metadata. I also cleaned the project. Same issue.

Uncaught TypeError: Cannot read property 'Output' of undefined
    at ng2-bootstrap.umd.min.js:8
    at Object.<anonymous> (ng2-bootstrap.umd.min.js:8)
    at t (ng2-bootstrap.umd.min.js:1)
    at Object.<anonymous> (ng2-bootstrap.umd.min.js:8)
    at t (ng2-bootstrap.umd.min.js:1)
    at Object.<anonymous> (ng2-bootstrap.umd.min.js:8)
    at t (ng2-bootstrap.umd.min.js:1)
    at Object.<anonymous> (ng2-bootstrap.umd.min.js:8)
    at t (ng2-bootstrap.umd.min.js:1)
    at ng2-bootstrap.umd.min.js:1
    at ng2-bootstrap.umd.min.js:1
    at ng2-bootstrap.umd.min.js:1
    at ng2-bootstrap.umd.min.js:1

Here's my config:

{
"version": "1.0.0",
"name": "opengamelistwebapp",
"private": true,
"dependencies": {
"@angular/common": "2.4.4",
"@angular/compiler": "2.4.4",
"@angular/core": "2.4.4",
"@angular/forms": "2.4.4",
"@angular/http": "2.4.4",
"@angular/platform-browser": "2.4.4",
"@angular/platform-browser-dynamic": "2.4.4",
"@angular/router": "3.0.0",
"@angular/upgrade": "2.4.4",
"core-js": "^2.4.1",
"reflect-metadata": "0.1.10",
"rxjs": "5.0.0-beta.6",
"systemjs": "^0.19.37",
"typings": "^1.3.2",
"zone.js": "0.8.4",
"moment": "2.17.1",
"ng2-bootstrap": "1.4.0"
},
"devDependencies": {
"gulp": "^3.9.1",
"gulp-clean": "^0.3.2",
"gulp-concat": "^2.6.0",
"gulp-less": "3.3.0",
"gulp-sourcemaps": "^1.6.0",
"gulp-typescript": "^2.13.6",
"gulp-uglify": "^2.0.0",
"typescript": "2.2.1"
},
"scripts": {
"postinstall": "typings install dt~es6-shim --global"
}
}

Here's the HTML page:

<!DOCTYPE html>
<html>
<head>
    <base href="/">
    <title>OpenGameList</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/yeti/bootstrap.min.css" rel="stylesheet" integrity="sha384-yxFy3Tt84CcGRj9UI7RA25hoUMpUPoFzcdPtK3hBdNgEGnh9FdKgMVM+lbAZTKN2" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="/css/style.css" media="screen" />

    
    
    <script src="js/shim.min.js"></script>
    <script src="js/zone.js"></script>
    <script src="js/Reflect.js"></script>
    <script src="js/system.src.js"></script>
    
    
    <script src="js/moment.js"></script>
    <script src="js/ng2-bootstrap.umd.min.js"></script>

    
    <script src="systemjs.config.js"></script>
    <script>
        System.import('app').catch(function (err) { console.error(err); });
    </script>
</head>

<body>
    
    <opengamelist>Loading...</opengamelist>
</body>
</html>

**Comment by valorkin** [comment]
compare to this plnkr 
https://plnkr.co/edit/ztxTbQwaM4yLacg42iqt?p=preview

**Comment by valorkin** [comment]
works fine
