### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by ramarro123** [valor-software/ngx-bootstrap#1780]
on the website

https://valor-software.com/ng2-bootstrap/index-bs4.html#/

i read

```
<!-- index.html -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
```

that doesn't make much sense for bootstrap4

can you please update website to avoid misunderstanding on how to use it?

**Comment by valorkin** [comment]
agreed, writing docs is not my strongest side :)

**Comment by valorkin** [comment]
will be deployed in a sec
