### ISSUE TITLE
Popover falls outside viewport

### ISSUE THREAD

**Issue by VivekPMenon** [valor-software/ngx-bootstrap#1781]
Popover is cutting off when its near the edge of screen. Is it something that can be addressed. thanks much.

Our code looks like below. 

`<button  [popover]="popTemplate"
                popoverTitle="Information"
                placement="top"
                container="body">
</button>`

![popover](https://cloud.githubusercontent.com/assets/16230185/24114762/bb006f6c-0d77-11e7-916f-91482ab02406.png)

**Comment by valorkin** [comment]
it is about dynamic and auto positioning,
I remember about it, and there are an issue for it
once it will be implemented all popups will be fixed (because using same base Component loader)

closing as duplicate if you wouldn't mind

**Comment by mrdaliri** [comment]
Any updates?
Is it possible to integrate [`viewport`](https://getbootstrap.com/docs/3.3/javascript/#popovers) functionality from **Bootstrap 3.x**?
