### ISSUE TITLE
Please provide tutorial on date picker

### ISSUE THREAD

**Issue by izooky** [valor-software/ngx-bootstrap#1782]
First off - you are doing a great job thank you!    It would be helpful if you could provide more examples, or a tutorial on the use of the date picker.

Thank you again.

**Comment by valorkin** [comment]
@izooky I working on a new datepicker,
and it will have a lot of samples,
because there are too much of available configuration :D

**Comment by valorkin** [comment]
new datepicker (new style and pop up version)
available in v1.9.0+
check this out: http://valor-software.com/ngx-bootstrap/#/datepicker#examples

a couple of small things and big doc is coming...
too much features...
