### ISSUE TITLE
componentHelper.setRootViewContainerRef() hack does not work with lazy loaded modules

### ISSUE THREAD

**Issue by robbaman** [valor-software/ngx-bootstrap#1785]
We're using lazy loading for many of our modules, but as per the Angular injector design, when modules are lazy loaded, they get their own providers when registered (see [Angular docs on this subject](https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-why-child-injector)).

This means however that while I've used the `componentHelper.setRootViewContainerRef()` function to register the viewContainerRef of the AppComponent with the ComponentHelper service, for the lazy loaded modules a new ComponentHelper is created and thus the `setRootViewContainerRef()` call will have been on the wrong one.

We're using Angular 2.4.5 at the moment and it also seems that the hack that looks for `rootComponent._hostElement.vcRef` also does not work since `_hostElement` is undefined.

**Comment by valorkin** [comment]
it is removed so long time ago...
update to latest and remove any mentions of componentHelper
