### ISSUE TITLE
When using moment-timezone, datepicker show wrong days

### ISSUE THREAD

**Issue by LomoSoftGmbH** [valor-software/ngx-bootstrap#1787]
When you set a different timezone in moment than the local, the datepicker will display wrong day-labels:
![bildschirmfoto 2017-03-21 um 16 30 21](https://cloud.githubusercontent.com/assets/16335174/24155433/1dfc6134-0e54-11e7-8fac-80c1f81a5e09.png)

This is because you use native Date-Objects (which always use the local timezone) mixed with formatting-functionality of moment (extended by using moment-timezone with setup a different timezone than the local one).
To get rid of this bug, convert the moment date in the DateFormatter into a local date like:

return moment(date).local().format(format);

**Comment by valorkin** [comment]
moment usage is completely removed
new datepicker (new style and pop up version)
available in v1.9.0+
check this out: http://valor-software.com/ngx-bootstrap/#/datepicker#examples

**Comment by jjlorenzo** [comment]
I understand moment usage was removed, but I'm having the same error, if  the API returns "2017-10-65" and my local timezone is `GMT-5` the datepicker shows me the day before, so I always had to parse the date object before.
