### ISSUE TITLE
[feature request] Typeahead validation

### ISSUE THREAD

**Issue by nomanbiniqbal** [valor-software/ngx-bootstrap#1789]
In ngModel there should be way in which model only update when user select/match any option from dropdown.
if not match then its add any error .
like stricket mode or something

**Comment by IlyaSurmay** [comment]
You can achieve this behavior now - split `[(ngModel)]` into `[ngModel]` and `(ngModelChange)="handler($event)"`. In this case you'll be catching the new value but the model itself won't change, so it will give you possibility to validate it as you want.
