### ISSUE TITLE
Error: (SystemJS) Cannot read property 'forRoot' of undefined 

### ISSUE THREAD

**Issue by amoldorkar-ezest** [valor-software/ngx-bootstrap#1793]
I am using Angular 2 RC 5 - I am trying to add popover , I have written below code in app module ts file

import {PopoverModule   } from 'ng2-bootstrap/ng2-bootstrap';

@NgModule({
  imports: [PopoverModule.forRoot()]
})

Using this I am getting an error  as below

Error: (SystemJS) Cannot read property 'forRoot' of undefined TypeError: Cannot read property 'forRoot' of undefined at eval (http://localhost:3000/assets/app.module.js:259:149) at execute (http://localhost:3000/assets/app.module.js:270:14) Error loading http://localhost:3000/assets/main.js

**Comment by valorkin** [comment]
wrong import statement
please compare to https://github.com/valor-software/angular2-quickstart/blob/master/systemjs.config.js
and much better to use angular cli with webpack then always painful system.js configurations

**Comment by valorkin** [comment]
should be `import {PopoverModule } from 'ng2-bootstrap'`
