### ISSUE TITLE
Popover with triggers="focus" not working on MacOs

### ISSUE THREAD

**Issue by gilsdav** [valor-software/ngx-bootstrap#1795]
On our projects and on your demo site, the popover with focus trigger doesn't work on Safari and Firefox (MacOsx). But it works on Chrome (MacOsx).

The original popover bootstrap works but not ng2-bootstrap popover.
[https://www.quirksmode.org/dom/events/blurfocus.html](https://www.quirksmode.org/dom/events/blurfocus.html)

> Firefox Mac and Safari and Chrome do not fire the events on radios and checkboxes if the user uses a mouse.

Within my test: On FF Mac, we can see the popover using tab key but not by clicking. On Safari, keyboard doesn't work.

A js fix to be able to handle focus event on button: http://jsfiddle.net/kzfg0pdh/6/

## Temporary fix
On component that directly use popover:
Use this on HTML
`triggers="focus:blur"`
On ts
`ngAfterViewInit() {
    const sels: any = document.querySelectorAll('[triggers]');
    for (let i = 0; i < sels.length; i++) {
        sels[i].addEventListener('click', function() {
            sels[i].focus();
        });
    }
}`

**Comment by valorkin** [comment]
interesting

**Comment by Kanishkaz** [comment]
Having the same issue. Firefox on windows doesn't like the focus trigger.

**Comment by jboothe** [comment]
Same issue here on Mac Chrome, Firefox & Safari.

**Comment by savyasachi-sa** [comment]
Facing the same issue. triggers=focus not working on Firefox Mac

**Comment by liymike** [comment]
Having the same issue on mac with chrome firefox and safari, but works perfectly on windows using Microsoft Edge.
And also works on linux(opensuse) using firefox.

**Comment by scndel** [comment]
The same issue for me with Firefox OSX & Safari on our project. Do you have any idea about potential fix or should we give up your solution ?

**Comment by valorkin** [comment]
ok, it seems to be as designed (by browsers)
just add `tabindex="1"` to your element
and it works

**Comment by gilsdav** [comment]
@valorkin 
Your solution 

> tabindex="1"
 
doesn't work for us. We already have the problem on Safari and Firefox.

Please reopen the issue (or accept my pull request).
Thanks ;)

**Comment by scndel** [comment]
Hi, Gilsdav is damn right, that workaround is useless. You should merge his fix...

**Comment by parasharabh** [comment]
Use <a> instead of <button> and add tabindex="0". This solved the issue for me.

**Comment by ckrandhir** [comment]
tabindex="0" did not solve the problem

**Comment by valorkin** [comment]
Have you tried v3.3.0?

**Comment by ckrandhir** [comment]
no.  is this problem is solved in v3.3.0 ?

**Comment by valorkin** [comment]
positioning service was completely reworked

**Comment by ckrandhir** [comment]
Its better than the previous but still not hiding if I clicking outside the poopover but it is hiding if I am clicking other button for other poopover
