### ISSUE TITLE
bsDatePickerPopup not working

### ISSUE THREAD

**Issue by davidmguerra** [valor-software/ngx-bootstrap#1796]
I copied the example from http://valorkin.github.io/ng2-bootstrap/#/datepicker, but the bsDatePickerPopup directive was not recognized.

The following error is displayed:

Can't bind to 'config' since it isn't a known property of 'button'.

I searched for the definition in the sources but did not find it. I am using version 1.4.2, from 2017-03-17.

**Comment by valorkin** [comment]
it is available only in @next version 
in general valorkin fork is my playground to test next version prior to publishing
