### ISSUE TITLE
Tooltip - Set position dynamically

### ISSUE THREAD

**Issue by sonuait135** [valor-software/ngx-bootstrap#1797]
How can we can set position dynamical based on element position.

**Comment by faouzioudouh** [comment]
Do you mean display the Tooltip in various positions E.g.
Display it above (Default) the element unless there is no enough space in view-port so we display blow the element?

**Comment by sonuait135** [comment]
Yes, do we have any such setting to implement it

**Comment by valorkin** [comment]
not so easy, but planned for later
you can track it here: https://github.com/valor-software/ngx-bootstrap/issues/381
