### ISSUE TITLE
Navbar with dropdown menu

### ISSUE THREAD

**Issue by rvgarimrj** [valor-software/ngx-bootstrap#1800]
When it will be avaiable ?
thank you in advanced

**Comment by Martin-Luft** [comment]
Duplicate of https://github.com/valor-software/ng2-bootstrap/issues/540 and please have a look at my workaround.

**Comment by StaticSpark** [comment]
http://valor-software.com/ngx-bootstrap/#/collapse

**Comment by StaticSpark** [comment]
http://valor-software.com/ngx-bootstrap/#/collapse
