### ISSUE TITLE
Tab Component Not working with angular 4

### ISSUE THREAD

**Issue by madhurakhal** [valor-software/ngx-bootstrap#1806]
The Tab component was working in angular 2 but stops working after angular version upgraded to 4.

**Comment by valorkin** [comment]
Duplicate, check @beta version and stay tuned

**Comment by tarun-sharma** [comment]
I have duplicate with @next version, and Tab component still not working with angular 4

**Comment by cbcolleenb** [comment]
my tabs don't work either in angular 4.. where is the solution to this issue?  i don't understand your comment to check beta.
Colleen

**Comment by valorkin** [comment]
npm I ngx-bootstrap@next
