### ISSUE TITLE
Done: Please add support for Angular 4

### ISSUE THREAD

**Issue by vinothsubramanian** [valor-software/ngx-bootstrap#1807]
Currently when updating to angular 4 we are getting the below warning:

npm WARN ng2-bootstrap@1.4.2 requires a peer of @angular/common@^2.3.1 but none was installed.
npm WARN ng2-bootstrap@1.4.2 requires a peer of @angular/compiler@^2.3.1 but none was installed.
npm WARN ng2-bootstrap@1.4.2 requires a peer of @angular/core@^2.3.1 but none was installed.
npm WARN ng2-bootstrap@1.4.2 requires a peer of @angular/forms@^2.3.1 but none was installed.

**Comment by narainsagar** [comment]
Hello, I'm going to open a PR for this!

**Comment by valorkin** [comment]
It is already available in @beta version

**Comment by St1c** [comment]
I tried the beta, but it seems that it relies on angular RC, but stable is already out there.

<img width="799" alt="screen shot 2017-03-26 at 21 38 43" src="https://cloud.githubusercontent.com/assets/3169082/24334576/b2a4582a-126c-11e7-9b8e-b1a43e98cb24.png">

**Comment by valorkin** [comment]
Ignore this, it is just a peer dependencies

**Comment by Ketec** [comment]
Could simply relax peer dep to >=4.0.0

**Comment by FabienDehopre** [comment]
alos, don't forget to replace `<template>` tags by `<ng-template>`.

**Comment by valorkin** [comment]
I don't want to drop backwards compatibility :(

**Comment by GuskiS** [comment]
Well, I think you should cut a version where you stop worry about Angular2 and focus on Angular4. @valorkin

**Comment by conor-mac-aoidh** [comment]
@valorkin `4.0.0` is out - could you update @beta version to use the stable ng 4 release?

The peer dependency breaks compatibility with `npm shrinkwrap` for those on ng `4.0.0`.

**Comment by valorkin** [comment]
Yep, I will cut down 2 versions tomorrow

**Comment by valorkin** [comment]
With new dropdown and ng v4

**Comment by am-hs** [comment]
Can we use ">2.0.0" instead of "^4.0.0" to avoid this issue in future angular versions?

**Comment by Ketec** [comment]
What about:  "^2.0.0" || ">4.0.0"
So 2 and 4 both are supported, <template> may be deprecated but for now it still works.

**Comment by eestein** [comment]
Adding to @FabienDehopre using ng-template would be nice. The only warning I receive atm is from ng2-bootstrap:

```
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///projx/node_modules/ng2-bootstrap/alert/alert.component.d.ts.AlertComponent.html@1:0
```

Thanks :)

**Comment by Martin-Luft** [comment]
@eestein this is already done in ^2.0.0-rc.0 :)

**Comment by Ketec** [comment]
Do not see tag 2.0.0-rc.0 - latest i see is 1.4.2

**Comment by Martin-Luft** [comment]
@Ketec npm install ng2-bootstrap@2.0.0-rc.0 ;)

**Comment by eestein** [comment]
@Martin-Wegner thanks :) I'll try that

**Comment by GuskiS** [comment]
@Martin-Wegner Where is the branch of 2.0.0? :thinking: 
@valorkin Also, do you plan to change the name of package?

**Comment by Martin-Luft** [comment]
@GuskiS I don't know which branch @valorkin used :/
And renaming is discussed here: https://github.com/valor-software/ng2-bootstrap/issues/1280

**Comment by valorkin** [comment]
ngx-bootstrap will be the new name

**Comment by valorkin** [comment]
v1.6 with relaxed peer dependencies published

**Comment by rerickson1** [comment]
Just tried v1.6 and I can confirm it fixes npm shrinkwrap

**Comment by St1c** [comment]
but it doesn't use \<ng-template\> :)

**Comment by Martin-Luft** [comment]
@St1c this is because @valorkin did not want to break Angular 2 support.

**Comment by valorkin** [comment]
Guilty, things: renaming templates is only 15% of migration for me, internal stuff changed too. So I will have update services too

**Comment by harunurhan** [comment]
why not support Angular 4 properly (with `<ng-template>`) and do a major release? @valorkin

**Comment by valorkin** [comment]
Check @next version in npm

**Comment by ojourmel** [comment]
@next version is only available for `ng2-bootstrap`, not `ngx-bootstrap`. Would it be possible to publish @next for `ngx-bootstrap`?

```
$ npm view ngx-bootstrap dist-tags
{ latest: '1.6.2' }

$ npm view ng2-bootstrap dist-tags
{ latest: '1.6.2', next: '2.0.0-beta.0' }
```

---

*edit as of April 17th*
Looks good!
```
$ npm view ngx-bootstrap dist-tags
{ latest: '1.6.6', next: '2.0.0-beta.2' }
```

**Comment by H--o-l** [comment]
@valorkin Hello ! Can you tell me the branch to use if I want to look at the code or contribute to @next version ?

**Comment by qvidmi** [comment]
+1, @valorkin , can you please share with us where can we find code related to @next version?

**Comment by MacKinley** [comment]
+1 @valorkin, yes please share the source to the @next version. 
I get the ` Cannot call a namespace ('moment')` error with @next version with Angular4 when running AOT compiling and rollup.
Adding `"allowSyntheticDefaultImports": true` as mentioned in [#1556](https://github.com/valor-software/ngx-bootstrap/pull/1556) my tsconfig.json had no effect. Maybe I am doing something wrong there.

I actually use moment in my application directly and solved this issue by using [moment-es6](https://www.npmjs.com/package/moment-es6) [Referenced here](https://stackoverflow.com/a/43847642). I assume doing something similar in the @next version might solve this issue.
