### ISSUE TITLE
[btnRadio] cannot bind to a number.

### ISSUE THREAD

**Issue by gravidThoughts** [valor-software/ngx-bootstrap#1808]
We are using TS enums in our project. The initial binding to object properties (enums or numbers) fails.

I assume this is because the   DefaultValueAccessor in your implementation is for a string.

Is it possible to create a custom directive which will force [btnRadio] to utilize a ValueAccessor based on a number?

**Comment by valorkin** [comment]
Yep

**Comment by cime** [comment]
@valorkin  can you provide an example on how to do this? Thank you.

**Comment by hisham** [comment]
I just ran into this - the default btnRadio implementation does not accept numbers as a value. Kind of annoying when enums are being used. So what's the solution here that involves the least amount of extra code to be written?

**Comment by valorkin** [comment]
Html sample? 10 to 1 you forgot use [] binding, and setting number as a string value

**Comment by hisham** [comment]
Hmm - you are correct. Just needed [] around btnRadio. Here's sample code for others:

```
export enum ChartType {
  line = 1,
  bar,
  area
}
```


`selectedChartType: number = ChartType.area;
`

```
<div class="btn-group" role="group" aria-label="...">
  <label class="btn btn-default" [(ngModel)]="selectedChartType" [btnRadio]="ChartType.bar">Bar Chart</label>
  <label class="btn btn-default" [(ngModel)]="selectedChartType" [btnRadio]="ChartType.line">Line Chart</label>
  <label class="btn btn-default" [(ngModel)]="selectedChartType" [btnRadio]="ChartType.area">Area Chart</label>
</div>
```

**Comment by valorkin** [comment]
:)
