### ISSUE TITLE
Angular 4; Warnings about <template> while bundling the a production build

### ISSUE THREAD

**Issue by ewoutreinders** [valor-software/ngx-bootstrap#1811]
**Versions**
- angular cli 1.0.0
- angular 4.0.0

When I try to bundle the typeahead in my angular application, I receive this warning:

The <template> element is deprecated. Use <ng-template> instead ("

[WARNING ->]<template [ngTemplateOutlet]="optionsListTemplate || (isBs4 ? bs4Template : bs3Template)"
  [ngOutlet"): ng:///../ng2-bootstrap/typeahead/typeahead-container.component.d.ts.TypeaheadContainerComponent.html@2:0

Seems that the template element in the typeahead should be renamed to ng-template :). It only occurs btw with a production build, not a dev build.

EDIT: also see in the chrome console a warning about AlertComponent
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///AlertModule/AlertComponent.html@1:0

Seems that this bug is also related to #1805

**Comment by valorkin** [comment]
Available in @beta version

**Comment by sanyooh** [comment]
sorry to ask but i have version 1.9.3 and still have this warning. your link to beta gets me to a Github User Account. can you tell me when it will be fixed or if it is fixed, which version or update do i need?

**Comment by fchiumeo** [comment]
ngx-bootstratp@1.9.3 support angular 2 and angular 4
ngx-bootstrap@next suport only angular 4+ and not warning template

**Comment by zuo305** [comment]
Sorry. What is ngx-bootstrap@next?? So now it is not support angular 5?

**Comment by valorkin** [comment]
Just install latest now, @next means npm tag
