### ISSUE TITLE
Dropdown menu and keyboard navigation only works with <a> tag.

### ISSUE THREAD

**Issue by wawyed** [valor-software/ngx-bootstrap#1815]
Is there any reason why it couldn't work with buttons or any other tabbable element?

Currently the code only looks for a tags: https://github.com/valor-software/ng2-bootstrap/blob/v1.4.2/src/dropdown/dropdown.directive.ts#L159

**Comment by GuskiS** [comment]
Have you set `tabIndex`? It is hard to help without example.

**Comment by wawyed** [comment]
No, button is a tabbable element already.

**Comment by valorkin** [comment]
@wawyed this is solved in v1.6.0

**Comment by valorkin** [comment]
and please, read change log it has breaking changes for dropdowns

**Comment by wawyed** [comment]
@valorkin Hmm, how is deprecating the option fixing it? Is there no keyboard navigation anymore then?

**Comment by valorkin** [comment]
It will get back soon
