### ISSUE TITLE
feat(datepicker): add functionality of applying array of enabled dates to the datepicker component

### ISSUE THREAD

**Issue by scottwio** [valor-software/ngx-bootstrap#1821]
I have an array of enabled dates that I want to apply to the date picker component. Currently there only seems to be an Input for dateDisabled which does the exact opposite or what I am after. Is there a way to get ng2-bootstraps datepicker to only enable a set of dates from an array?

**Comment by gardecki** [comment]
+1

**Comment by gardecki** [comment]
is far as I remember it was possible to pass dateDisabled as a function in angular 1.x uib-datepicker. it was super useful as my use case was to enable single week/month days depending on another field for the whole date picker timeline. for now it is obviously impossible even with requested dateEnabled property (infinite array of dates?)
please consider adding dateDisabled/Enabled as function as it covers all possible use cases
