### ISSUE TITLE
clickOutiside (using nativeElement.contains) and datepicker incompatable

### ISSUE THREAD

**Issue by pnahtanoj** [valor-software/ngx-bootstrap#1823]
Using nativeElement.contains to test for clicking outside datepicker doesn't properly register component hierarchy.

https://plnkr.co/edit/jnZuCcAZNrIktjaqUg8B?p=preview

**Comment by sivasunken** [comment]
+1
for dev - is it possible to have the event emitted before the template is changed?

**Comment by valorkin** [comment]
done right in 
new datepicker (new style and pop up version)
check this out: http://valor-software.com/ngx-bootstrap/#/datepicker#examples
