### ISSUE TITLE
fix(sortable): two sortables with the same model infinitely loop rather than erroring out

### ISSUE THREAD

**Issue by terrac** [valor-software/ngx-bootstrap#1828]
I noticed that if you give two sortables with the same model they infinitely loop rather than erroring out

**Comment by valorkin** [comment]
interesting, can you provide a pease of code to reproduce
sounds as edge case issue to me

**Comment by IlyaSurmay** [comment]
Please provide plunkr/stackblitz with reproduction if this is still relevant.
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IlyaSurmay** [comment]
Reproduced - https://stackblitz.com/edit/ngx-bootstrap-prnjez?file=app%2Fapp.component.html (incomment a section with second sortable and the tab will freeze and take 1GB+ of RAM)

**Comment by daniloff200** [comment]
Looks like, that's not Sortable issue, but, Angular one
I see reports about that long ago, and looks like, that was not fixed properly

https://github.com/angular/angular/issues/11097
https://github.com/angular/angular/issues/24642

The workarounds are:
- always return **the same instance ** of the property
- Replace`   [(ngModel)]="getter/setter" `with  `[ngModel]="property" (ngModelChange)="onChange($event)"`
