### ISSUE TITLE
How to create a modal programmatically?

### ISSUE THREAD

**Issue by eestein** [valor-software/ngx-bootstrap#1830]
I'm sorry if this has been answered already, I did search but couldn't find it... 

I'm trying to migrate from `ng-bootstrap`, but I just hit a road block...
Using `ng-bootstrap` I was able to retrieve my modal's instance by:

```typescript
let modal: NgbModalRef = this.modalService.open(this.config.createModal);
let modalInstance: BaseModal = modal.componentInstance as BaseModal;
```

Where `this.config.createModal` is my custom modal component.

I couldn't find in the docs (specially in the demos) something similar for `ng2-bootstrap`.

Could anyone shed some light here? Is it possible? If so, how can I do this? If not, are there any workarounds?

Thank you.

**Comment by valorkin** [comment]
modal service is coming soon

**Comment by eestein** [comment]
@valorkin cool, thanks. Not to be a pain here, but do you have any ETA?

**Comment by valorkin** [comment]
First thing is to land v2 with new datepicker
Then I can land modal service

**Comment by eestein** [comment]
@valorkin thanks :)

**Comment by tommueller** [comment]
Any news on the ETA on this?

**Comment by IlyaSurmay** [comment]
Work is in progress  #2047

**Comment by eestein** [comment]
@valorkin @IlyaSurmay Awesome! Which version will this be in and when will it be out?

Thanks! :D

**Comment by valorkin** [comment]
@eestein one PR to go https://github.com/valor-software/ngx-bootstrap/pull/2058
than heavy testing and ready for publish
most probably tomorrow v1.8.0

**Comment by eestein** [comment]
@valorkin that's great, thank you! :)

@IlyaSurmay great work! Thanks!
