### ISSUE TITLE
Minor version bump introducing breaking change

### ISSUE THREAD

**Issue by psaussure** [valor-software/ngx-bootstrap#1838]
Hello, 

I was working on several projects yesterday and during one update ng2-bootstrap went from 1.4.2 to 1.6.0. I was surprised to see in changelog this version (and the previous one too) both includes breaking changes. 

Is that intended, and of course, do you use semver base for versionning? If not, forget about my issue.

Why then not to bump a major version? So our `package.json` configured as `^1.4.2` wold not cause the project to be broken with a minor version bump.

http://semver.org/

> MINOR version when you add functionality in a backwards-compatible manner

Thanks for explainations and have a good day guys.

**Comment by valorkin** [comment]
Seems I will have to make a major bumps,
things is I am on way to completely rewrite:
- datepicker
- typeahead (merge ng2-select) 
- tabs
- pagination
- and several more
- introduce modal service loader
- change the way switching between bs3 and bs4 is currently workin

**Comment by valorkin** [comment]
so I am afraid to have v10 in the middle of the summer
if it is ok, I can go this way

**Comment by Martin-Luft** [comment]
Windows 10, ngx-bootstrap v10 :P

**Comment by psaussure** [comment]
I see... Is there any way you work on separate BETA versionning during your development of new features. Using maybe beta or RC. And when everything you plan for next major release is complete, then release a final version. 

For example:
`2.0.0-beta` --> `2.0.0-beta.2` --> `2.0.0-beta.x` --> `2.0.0`

**Comment by jtandrew** [comment]
@valorkin So should I try and use ng2-select instead of typeahead?  I am having issues with typeahead working for my use case.

**Comment by valorkin** [comment]
It is not actively supported at the moment

**Comment by jtandrew** [comment]
Just to verify **typeahead** is not actively supported? Right?  If so then I will have to figure out another method.  Thanks!

**Comment by valorkin** [comment]
ng2-select is not actively supported, it will be merged in Typeahead soon

**Comment by psaussure** [comment]
Was my issue hijacked by typeahead?

What do you think about the beta naming until every breaking change is final? Then push to 2.0.0?

**Comment by Martin-Luft** [comment]
The point is, that @valorkin is already using beta versions :)

**Comment by psaussure** [comment]
Great new. Work on all new future features (with potential breaking changes) in a 2.0.0-beta version is perfect. Thanks for confirmation.

**Comment by Martin-Luft** [comment]
@psaussure hmm don't speak too soon because I meant that @valorkin was using beta versions since months and therefore before you started this issue ;)

**Comment by valorkin** [comment]
In 2 I am dropping ng v2 support, and releasing new datepicker. @next is already usable btw

**Comment by valorkin** [comment]
Sorry, again. should not happen again
