### ISSUE TITLE
Dropdown autoClose value overriden by default on init

### ISSUE THREAD

**Issue by AmlaPeter** [valor-software/ngx-bootstrap#1840]
When using:

```typescript
<div class="btn-group" dropdown [autoClose]="false">
```

The autoClose property setter is called prior to ngOnInit, meaning the value is then overridden by the default from the config.

ng2-bootstrap 1.6.0

**Comment by jiann4321** [comment]
Auto close is not working for me either. I set the autoClose value to false and it is not working

**Comment by sturchaninov** [comment]
seems possible to set autoClose in module import:
BsDropdownModule.forRoot({autoClose: false})

**Comment by jiann4321** [comment]
But I need this config dynamically based on my dropdown :( Please help!

**Comment by tkd-hgoertz** [comment]
@jiann4321 As temporary workaround you can set the autoClose property to false very dirty in the private _state object of BsDropdownContainerComponent which was returned from onShow output of the dropdown directive. I know its ugly.

**Comment by Anirudh-Konduri** [comment]
@jiann4321 did you find any workaround for this ?
