### ISSUE TITLE
optionsListTemplate

### ISSUE THREAD

**Issue by learnuser521** [valor-software/ngx-bootstrap#1841]
It would be good to have an example for the optionsListTemplate implementation. I know there is one for the typeaheadItemTemplate.  I am having a hard time trying to get it to work or I am not very sure if the optionsListTemplate is not working. I tried 

template #bsItemTemplate let-model="item" let-index="index">
  <h5> {{model}} </h5>
</template>

<template #bs4Template>
  <template ngFor let-match let-i="index" [ngForOf]="matches">
    <h6 *ngIf="match.isHeader()" class="dropdown-header">{{match}}</h6>
    <template [ngIf]="!match.isHeader()">
      <button class="dropdown-item" (click)="selectMatch(match, $event)" (mouseenter)="selectActive(match)" [class.active]="isActive(match)">
          <template [ngTemplateOutlet]="itemTemplate || bsItemTemplate" 
            [ngOutletContext]="{item:match.item, index:i, match:match, query:query}"></template>
      </button>
    </template>
  </template>
</template>

<input [(ngModel)]="selected" [typeahead]="states" [optionsListTemplate]="bs4Template" [typeaheadMinLength]="0" class="form-control">

**Comment by felimartina** [comment]
@learnuser521
Did you ever get this to work? Do you have an example? I don't see any in the documentation

**Comment by learnuser521** [comment]
@felimartina 
no I did not. I built one on my own with some modifications done to the dropdown to work as a typeahead.
