### ISSUE TITLE
'dropup' new attribute should be listed in the breaking changes of the v1.6.0

### ISSUE THREAD

**Issue by alaindeurveilher** [valor-software/ngx-bootstrap#1842]
I think that the dropup new attribute to make a dropdown opened up, should be listed among the breaking changes of the v1.6.0/v1.5.0:

**Before**:

```html
<button class="... dropup" dropdown>
```

**Now**:

```html
<button class="... dropup" dropdown dropup>
```

**Comment by valorkin** [comment]
Small PR to change log would be nice

**Comment by zaiddabaeen** [comment]
And for those who are stuck with v1.6.6+ with Dropups, that's how it should go:

```
<button class="... " dropdown [dropup]="true">
```
