### ISSUE TITLE
Dropdown failed to run init.

### ISSUE THREAD

**Issue by hailg** [valor-software/ngx-bootstrap#1848]
Hi, I'm using:

* @angular/cli: 1.0.0
* node: 7.5.0
* os: darwin x64

For now, I can't start using the dropdown component as it throwing the error as the image attached.
 
<img width="915" alt="screen shot 2017-03-31 at 6 19 28 pm" src="https://cloud.githubusercontent.com/assets/731508/24546665/ea8c8da4-163e-11e7-93d4-757d336b38d8.png">

This is my component html:

```html
<div class="jumbotron vertical-center" style="background-color: #fff;">
  <div class="container" style="text-align: center;">
      <div class="btn-group" dropdown>
        <button dropdownToggle type="button" class="btn btn-primary dropdown-toggle">
          Button dropdown <span class="caret"></span>
        </button>
        <ul *dropdownMenu class="dropdown-menu" role="menu">
          <li role="menuitem"><a class="dropdown-item" href="#">Action</a></li>
          <li role="menuitem"><a class="dropdown-item" href="#">Another action</a></li>
          <li role="menuitem"><a class="dropdown-item" href="#">Something else here</a></li>
          <li class="divider dropdown-divider"></li>
          <li role="menuitem"><a class="dropdown-item" href="#">Separated link</a>
          </li>
        </ul>
      </div>
  </div>
</div>
``` 

Is it something wrong with my code or this is a bug?

**Comment by nielsvanlooy** [comment]
I'm having the same issue. There seem to have been some big changes to the dropdown last night, so i'm guessing this might be a bug

**Comment by psaussure** [comment]
See #1838 for explaination: v1.6.0 introduced breaking change. You can see it in changelog. Solution: use 1.4.2 or any version prior breaking change. Alternate solution: change your code to replace module name according to changelog.

**Comment by MarioGruda** [comment]
I have replaced the modulename and I iuse the templatesyntax '*dropdownMenu' but still have the problem.

`import { BsDropdownModule } from 'ng2-bootstrap/dropdown';`

`BsDropdownModule.forRoot(),`

```html <div class="btn-group pull-right" dropdown>
<button id="split-button" type="submit" class="btn btn-primary" [disabled]="searchForm.invalid">Suchen</button>
<button type="button" class="btn btn-primary dropdown-toggle-split" [disabled]="searchForm.invalid" dropdownToggle>
 <span class="caret"></span>
 <span class="sr-only">Suchen</span>
</button>
<ul class="dropdown-menu" *dropdownMenu role="menu">
    <li role="menuitem"><a class="dropdown-item">TEST</a></li>
    <li role="menuitem"><a class="dropdown-item">TEST</a></li>
    <li role="menuitem"><a class="dropdown-item">TEST</a></li>
    <li role="menuitem"><a class="dropdown-item">TEST</a></li>
</ul>
</div> 
```


EDIT1: dropdown changed to bsdropdown and dropdownToggle changed to bsdropdownToggle fixed the problem. Maybe the examples should be changed --> https://valor-software.com/ng2-bootstrap/#/dropdowns 

EDIT2: I thought I fixed the problem yesterday with my changes (see EDIT1), but the dropdownMenu still does not work. Only the "filter-error" disappeared. I had to change line 85 - 87 in \node_modules\ng2-bootstrap\dropdown\bs-dropdown.directive.js" 
to this:
```js
 this._subscriptions.push(this._state
            .isDisabledChange
            .subscribe(function (value) { if (value === true) { this.hide(); } }));
```

for a temporary fix.

Thanks

**Comment by johnlee** [comment]
@MoiraG thanks for your suggestion! Would be great if they could get this fix applied. Its difficult for me to hack this into all my environments...

**Comment by krokerke** [comment]
@johnlee already merged in a better version https://github.com/valor-software/ng2-bootstrap/pull/1836

**Comment by valorkin** [comment]
will be published in a sec
