### ISSUE TITLE
question(typeahead): is it possible only allow typeahead selection from list

### ISSUE THREAD

**Issue by hassanasad** [valor-software/ngx-bootstrap#1849]
Is it possible to only allow input selection from the typeahead list ?

I have a case where i need some additional data stored before passing it onto the server API. For that if a user clicks an option from the typeahead list, i save the entire object and then later use it. However, i was wondering if there is a way to somehow not take arbitrary inputs.

**Comment by tarusin** [comment]
@hassanasad 
There's no need to open an issue here if you want to ask a general question. 
Use <a href="https://stackoverflow.com/questions/tagged/ngx-bootstrap">StackOverflow</a> or <a href="https://ngx-slack.herokuapp.com/">Slack</a> instead
