### ISSUE TITLE
Dropdown style broke after upgrade to the new BsDropdown component

### ISSUE THREAD

**Issue by wtospit** [valor-software/ngx-bootstrap#1851]
Hi, I've just updated my app to new version of ng2-bootstrap and changed the DropdownModule to BsDropdownModule everything seems smooth except the dropdown's style was changed.

I'm using dropdown-menu-right class so the dropdown child should align right of the parent but it's not.

Before
![image](https://cloud.githubusercontent.com/assets/22524260/24558342/046c9f9a-1665-11e7-87b6-775115ee44d9.png)

After
![image](https://cloud.githubusercontent.com/assets/22524260/24558287/d49009c4-1664-11e7-93dd-3ccdecf873c7.png)

And the code is like below

```
<ul class="nav navbar-nav ml-auto">
    <li class="nav-item dropdown" dropdown >
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" dropdownToggle>
       <i class="fa fa-user" aria-hidden="false"></i>
        <span class="hidden-md-down">{{getUser()}}</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right" *dropdownMenu aria-labelledby="simple-dropdown">
        <!--<a class="dropdown-item" href="#"><i class="fa fa-user"></i> Profile</a>-->
        <a class="dropdown-item" id="logoutButton" (click)="logout()" href="#"><i class="fa fa-lock"></i> Logout</a>
      </div>
    </li>
</ul>
```

**Comment by ctrl-brk** [comment]
For me dropdown background became transparent in 1.6.1

**Comment by jiann4321** [comment]
Add the placement attribute in the dropdown directive. Please refer to the document

**Comment by wtospit** [comment]
I'll try, thanks.

**Comment by wtospit** [comment]
I've added placement="bottom right", and it's working now
Thanks a lot @jiann4321

**Comment by mravenash** [comment]
On Navbar collapse the dropdpwn menu still looks broken. 
![dorpdownonnavbarcollapse](https://cloud.githubusercontent.com/assets/14627280/24661814/6bbcf942-1921-11e7-9faf-5e08e501c2c1.PNG)


Following the  HTML snippet:

![html snippet](https://cloud.githubusercontent.com/assets/14627280/24662507/39d613d0-1923-11e7-8d4c-e13a0f30a440.PNG)

`<ul class="nav navbar-nav navbar-right">
        <li class="nav-item">
          <a class="nav-link" href="javascript:void(0)">
            <div  style="position: initial!important">
            <div dropdown class="dropdown">
              <div dropdownToggle class="dropdown-toggle">
                Profile
                <b class="caret"></b>
              </div>
              <ul  *dropdownMenu class="dropdown-menu bs-dropdown-container" >
                <li><a (click)="showUserProfileModal()">My Profile</a></li>
                <li class="divider"></li>
                <li><a (click)="logOut()">Logout</a></li>
              </ul>
            </div>
              </div>
          </a>
        </li>
      </ul>`
