### ISSUE TITLE
No space beetween accordion groups

### ISSUE THREAD

**Issue by AGrzes** [valor-software/ngx-bootstrap#1854]
In pure bootstrap there is a space between panels in panel-group implemented by css rule

    .panel-group .panel + .panel {
        margin-top: 5px;
    }
But in ng2-bootstrap each panel is wrapped in accordion-group tag so the rule does not apply eliminating space between groups.

Example - good - bootstrap v3.3.7 + angular-ui-bootstrap 2.2.0 + angular 1.5.8
![old](https://cloud.githubusercontent.com/assets/1086454/24579111/29910a2e-16ef-11e7-93fb-1eb44036e730.png)

Example - bad - bootstrap v3.3.7 + ng2-bootstrap 1.6.0 + angular 2.4.9
![new](https://cloud.githubusercontent.com/assets/1086454/24579124/7c2feda4-16ef-11e7-9be2-78eaf2b07db7.png)

**Comment by artemvfrolov** [comment]
maybe it's fixed in #2014
