### ISSUE TITLE
Angular4 Update deprecated template tag

### ISSUE THREAD

**Issue by touqeershafi** [valor-software/ngx-bootstrap#1855]
I'm getting template warning because angular deprecated `template` tag and now it uses `ng-template`

```
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///AlertModule/AlertComponent.html@1:0
```

**Comment by Martin-Luft** [comment]
@touqeershafi already fixed in 2.0.0-rc.0

**Comment by bogacg** [comment]
@Martin-Wegner since package name changed to `ngx-bootstrap`, I can't reach through npm a version ` 2.0.0-rc.0` now.

**Comment by Martin-Luft** [comment]
@bogacg with ngx-bootstrap please use 2.0.0-beta.1 :)
