### ISSUE TITLE
dropdown placement="right" or any other is not working.

### ISSUE THREAD

**Issue by nidhi-sengar** [valor-software/ngx-bootstrap#1859]
I am using ng2-bootstrap dropdown and in parent div i used "dropdown" directive with placement="right" but it is not working. Please provide solution why it is happening

**Comment by valorkin** [comment]
it is a placement of a dropdown menu container, and not of dropdown menu itself
it is complicated a bit, but please check docs carefully

**Comment by meherett** [comment]
@valorkin 
Thanks!

**Comment by bhaskerchari** [comment]
The docs are not clear and it nowhere mentions for dropdown container however we can get some understading after seeing sample examples and is very confusing and as per the docs it says something as below:

placement | Type: string
Placement of a popover. Accepts: "top", "bottom", "left", "right"

Probably the docs should be updated properly and also it would be good if docs can mention the difference between dropup and placement properties.

Infact I believe we should have all these similar options to be able to position even the dropdown based on those 4 values which makes perfect sense in few cases.
