### ISSUE TITLE
Ng2-bootstrap naming

### ISSUE THREAD

**Issue by pjmagee** [valor-software/ngx-bootstrap#1861]
Just wondering since angular4 is out now, if we should have a name like NgBootstrap and make versioning based off the major releases of angular? so  NgBootstrap:  "2.0.0" for Angular2 and NgBootstrap: "4.0.0" for Angular 4 etc?

**Comment by Martin-Luft** [comment]
Duplicate of https://github.com/valor-software/ng2-bootstrap/issues/1280
