### ISSUE TITLE
Dropdown style broke after upgrade to the new BsDropdown component after Navbar Collapse

### ISSUE THREAD

**Issue by mravenash** [valor-software/ngx-bootstrap#1862]
On Navbar collapse the dropdpwn menu still looks broken.

![dorpdownonnavbarcollapse](https://cloud.githubusercontent.com/assets/14627280/24664285/43cc9d78-1928-11e7-8017-cb317ac3701b.PNG)

Following the HTML snippet:

html snippet:

![html snippet](https://cloud.githubusercontent.com/assets/14627280/24664297/4c3f8c36-1928-11e7-8d2f-08ef85a47470.PNG)

`<ul class="nav navbar-nav navbar-right"> <li class="nav-item"> <a class="nav-link" href="javascript:void(0)"> <div style="position: initial!important"> <div dropdown class="dropdown"> <div dropdownToggle class="dropdown-toggle"> Profile <b class="caret"></b> </div> <ul *dropdownMenu class="dropdown-menu bs-dropdown-container" > <li><a (click)="showUserProfileModal()">My Profile</a></li> <li class="divider"></li> <li><a (click)="logOut()">Logout</a></li> </ul> </div> </div> </a> </li> </ul>`

**Comment by valorkin** [comment]
Placement should be bottom left, plus you need to style dropdown menu

**Comment by mravenash** [comment]
Placement bottom right looks correct when the navbar is not collapsed. The dropdown menu shows on the bottom right of the navbar, as shown below.
![dropdownwhennotcollapsed](https://cloud.githubusercontent.com/assets/14627280/24668174/fbb7bebc-1933-11e7-9327-0ffb9915a3f9.PNG)
 
The issue is that when we collapse navbar, dropdown menu goes out of the navebar. Dropdown module comes with few inline element styles causing the issue. If  I get rid of "position:absolute" then it works as expected when navbar is collapsed and not collapsed. 
![dropdownbootstrap](https://cloud.githubusercontent.com/assets/14627280/24668536/4145c216-1935-11e7-8fae-f41f0673afa9.PNG).
