### ISSUE TITLE
Dropdown: not showing when click 

### ISSUE THREAD

**Issue by gercarino** [valor-software/ngx-bootstrap#1866]
Hi guys, 

I put in a [plnkr ](https://plnkr.co/edit/Ro5eP2?p=preview)the main set up as I currently have it on my app, but  basically I'm not able to see the dropdown menu appear when clicked, I have same configuration as in the example and also tried to use  `DropdownModule.forRoot()`, on `NgModule` to import this.  I took same html markup as it is on Dropdown [documentation ](http://valor-software.com/ng2-bootstrap/index-bs4.html#/dropdowns#usage) but not able to make it work. 

Is there something wrong on my side or could be a bug? 

NOTE: `Config.js` frozen, please comment line 34 ( `ng2-bootstrap/ng2-bootstrap': 'npm:ng2-bootstrap/bundles/ng2-bootstrap.min.js',` ) on the plnkr to see example working.

Thanks

**Comment by valorkin** [comment]
for some reason https://unpkg.com/ng2-bootstrap@beta/bundles/ng2-bootstrap.umd.js
`Not found: package ng2-bootstrap@beta`

but `https://unpkg.com/ng2-bootstrap@2.0.0-beta.0/bundles/ng2-bootstrap.umd.js`
works as expected

it could be unpkg doesn't support tags?

check this one https://plnkr.co/edit/ztxTbQwaM4yLacg42iqt?p=preview

**Comment by valorkin** [comment]
I have fixed issues with for Root and BsDropdownModule, etc.

**Comment by gercarino** [comment]
I upgraded to a higher version and followed your changes, it's working properly. Thanks for your quick response.

**Comment by valorkin** [comment]
Awesome
