### ISSUE TITLE
css reference for ng2-bootstrap target bootstrap v4

### ISSUE THREAD

**Issue by byunru** [valor-software/ngx-bootstrap#1867]
why https://valor-software.com/ng2-bootstrap/index-bs4.html# still reference 
"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
instead of css from v4 ?
"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"

**Comment by valorkin** [comment]
it should have both

**Comment by valorkin** [comment]
added
