### ISSUE TITLE
chore(typeahead): add support typeaheadMinLength = "0" in Typeahead

### ISSUE THREAD

**Issue by hongbo-miao** [valor-software/ngx-bootstrap#187]
There is an API of Typeahead in ng2-bootstrap.

> typeaheadMinLength (?number=1) - minimal no of characters that needs to be entered before typeahead kicks-in. Must be greater than or equal to 1.

Right now, it should be greater than or equal to 1. Please support 0. So when the input gets focus, it will show automatically.

Like [angular-ui](https://angular-ui.github.io/bootstrap/) supports this. And one demo using 0 works well.

> typeahead-min-length $  (Default: 1) - Minimal no of characters that needs to be entered before typeahead kicks-in. Must be greater than or equal to 0.

Thanks

**Comment by tzielins** [comment]
A useful feature to present the default options.

**Comment by valorkin** [comment]
good feature, will be done
