### ISSUE TITLE
tooltip custom style won't work when 'container="body"'

### ISSUE THREAD

**Issue by Phota16** [valor-software/ngx-bootstrap#1872]
Inside template wrote  tooltip="Filter options" placement="right" container="body" 
  and defined style  in component js file
 styles: [`
    :host >>> .tooltip-inner {
      background-color: #009688;;
      color: #fff;
      max-width:50px;
    }
    :host >>> .tooltip .tooltip-arrow {
      border-bottom-color: #009688;;
    }
  `]
it's wont show the style, but if i remove  'container="body"' then it works.
how to use custom style for tooltip?

**Comment by valorkin** [comment]
yep, custom wrapper class is planned

**Comment by valorkin** [comment]
will be implemented as a part of https://github.com/valor-software/ngx-bootstrap/issues/1395
