### ISSUE TITLE
Drop down is not working in header

### ISSUE THREAD

**Issue by vasu592** [valor-software/ngx-bootstrap#1873]
I am updated angular-cli version, i am changing dropdown to *dropdown to fix "Noprovider for template ref!" error. but its not showing header part in my application

<header class="app-header navbar">
    <button class="navbar-toggler mobile-sidebar-toggler hidden-lg-up" type="button">&#9776;</button>
    <a class="navbar-brand" href="#"></a>
   
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item dropdown" *dropdown (onToggle)="toggled($event)">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
                dropdownToggle>
                <i class="icon-bell"></i> <span class="badge badge-pill badge-danger">5</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" *dropdownMenu aria-labelledby="simple-dropdown">
                <a class="dropdown-item" href="#"><i class="fa fa-envelope"></i> You have 4 videos to Validate</a>
                <a class="dropdown-item" href="#"><i class="fa fa-trophy"></i> Need to Declare winners for week 34</a>
            </div>
        </li>
        <li class="nav-item dropdown" *dropdown (onToggle)="toggled($event)">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
                dropdownToggle>
                <img src="assets/img/avatars/6.jpg" class="img-avatar" alt="admin@tfc.com">
                <span class="hidden-md-down">Super Admin</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" dropdownMenu aria-labelledby="simple-dropdown">
                <a class="dropdown-item" href="#"><i class="fa fa-key"></i> Change Password</a>
                <a class="dropdown-item" href="#"><i class="fa fa-lock"></i> Logout</a>
            </div>
        </li>
    </ul>
</header>

**Comment by aliyeysides** [comment]
@vasu592 what version of ngx-bootstrap are you using?

**Comment by den-wis** [comment]
For Bootstrap 4
.open>.dropdown-menu {
  display: block;
}

**Comment by valorkin** [comment]
there are were an issue with Bootstrap 4 and dropdowns
it is already fixed and published
don't forget to enable bs4 theme via
`<script>window.__theme = 'bs4';</script>`
