### ISSUE TITLE
Angular 4.0.1 ng-template update in TypeaheadContainerComponent

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#1874]
Hi Guys, I'm using latest angular stable release 4.0.1 and it seems that <template> tag is going to be deprecated in future releases. I've noticed that one of your components are running the old template tag

Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("

[WARNING ->]<template [ngTemplateOutlet]="optionsListTemplate || (isBs4 ? bs4Template : bs3Template)"
  [ngOutlet"): ng:///TypeaheadModule/TypeaheadContainerComponent.html@2:0

Is there a way you can fix that checking the angular version used and switching with one template or another in order to avoid this warning on my app?

Otherwise I think I'll need to try to avoid the warning in some other way.

Thanks.
Bruno

**Comment by TomMuehlegger** [comment]
See #1811 and #1805.
