### ISSUE TITLE
Override PaginationConfig

### ISSUE THREAD

**Issue by eronalves** [valor-software/ngx-bootstrap#1875]
Hi, I need to override PaginationConfig from PaginationModule to change all labels for my app.

My app is large and has many modules and submodules to separate domains, if I override in a specific module using providers is working very well.

```
export function paginationConfigFactory() {
        return new MyPaginationConfig();
}

const providers = [
  {
    provide: PaginationConfig,
    useFactory: paginationConfigFactory,
    deps: []
  }
  
```

In this way I need to override in each module, if I try to override only in my AppModule is not working.

It's working when override Http from angular/core.

Is there some way to override a provider for all my modules?

**Comment by valorkin** [comment]
sure, let me guess, you are calling forRoot in child modules, but you should not
if you will remove unnecessary forRoot calls,
config override will work from module

in v2 all .forRoot will accept config

**Comment by valorkin** [comment]
if I didn't guessed correctly drop me a note please
