### ISSUE TITLE
How to upgrade to the appropriate version with angular4  ?

### ISSUE THREAD

**Issue by Christian-Yang** [valor-software/ngx-bootstrap#1876]
**Please forgive me, I am a novice. Want to ask a question.**

**How to upgrade to the appropriate version with angular4  ?**

**I mean，I can upgrade to angular4 by executing the following command:**

npm install @angular/{common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router,animations}@latest typescript@latest --save

**Then what command to do to upgrade ngx-bootstrap ?**

npm install ng2-bootstrap@latest --save  ??

**Or any other command ？？**

Looking forward to your help, thanks!

extra information：
npm WARN ng2-bootstrap@1.1.5 requires a peer of @angular/common@2.0.0 but none was installed.
npm WARN ng2-bootstrap@1.1.5 requires a peer of @angular/compiler@2.0.0 but none was installed.
npm WARN ng2-bootstrap@1.1.5 requires a peer of @angular/core@2.0.0 but none was installed.
npm WARN ng2-bootstrap@1.1.5 requires a peer of @angular/forms@2.0.0 but none was installed.

package.json；
"dependencies": {
                          "ng2-bootstrap": "^1.1.5",
                           }

![aaaa](https://cloud.githubusercontent.com/assets/25613332/24791031/29a3bfbe-1bab-11e7-8d6a-021989c99fa1.jpg)

**Comment by valorkin** [comment]
1. lib was renamed to ngx-bootstrap
2. read changelog carefully there were breaking changes
3. npm i ngx-bootstrap@latest -S
