### ISSUE TITLE
Close dropdown on route change

### ISSUE THREAD

**Issue by davidloiret** [valor-software/ngx-bootstrap#1877]
Is there a way to close dropdown on route change? 
If not it would be nice to have this feature.

**Comment by valorkin** [comment]
make a PR to call hide in ngOnDestroy method
or make a composite component
with selector `[dropdown][closeOnRouteChange]`
and there call .hide on route change

**Comment by davidloiret** [comment]
Composite component make more sense. Thanks.

**Comment by jyotisingh144** [comment]
is there any example of this resolution available on stackblitz
