### ISSUE TITLE
Collapsed navbar menu does not popup when clicked

### ISSUE THREAD

**Issue by otabekgb** [valor-software/ngx-bootstrap#188]

**Comment by valorkin** [comment]
Please provide plunker or repo, and reproduce info
ng2-bootstrap doesn't have navbar or popups components as for now

**Comment by valorkin** [comment]
closing because not enough info to reproduce

**Comment by szh** [comment]
Any plans to add the navbar component?

**Comment by valorkin** [comment]
yeap

**Comment by Martin-Luft** [comment]
Can you tell us about your plans please? And why is this issue closed? The bootstrap-navbar-example does not work with ng2-bootstrap: http://getbootstrap.com/components/#navbar The mobile menu is not collapsed when clicked.

**Comment by valorkin** [comment]
navbar is not yet part of ng2-bootstrap, but planned to be added

**Comment by caranzojason** [comment]
valorkin any update?

**Comment by ghost** [comment]
Why has no attention been paid to issues regarding the navbar? Has development slowed down or something? Does anybody know of any alternatives to this framework that actually include basic features such as the navbar?

**Comment by valorkin** [comment]
I was on vacation, we upgraded to ng2 final, now adding metadata for ng cli
compatibility, and tech requirements to all modules, in nearest time all
components will be rewritten

**Comment by ghost** [comment]
That's awesome! I look forward to trying it out, and thanks for the update.

**Comment by coreboarder** [comment]
Wondering what is the status of this? Examples from Bootstrap appear to still not work.

**Comment by Martin-Luft** [comment]
@coreboarder  https://github.com/valor-software/ng2-bootstrap/issues/540

**Comment by alexinasra** [comment]
hi .. i was able to fix this with this solution using ngStyle
```
<button class="navbar-toggler navbar-toggler-right"
              type="button"
              (click)="toggleCollapse()"
              [attr.aria-expanded]="!isCollapsed">
  <span class="navbar-toggler-icon"></span>
</button>
<div id="navbar-navigation-menu"
        class="collapse navbar-collapse"
        [ngbCollapse]="isCollapsed"
        [ngStyle]="{display: isCollapsed ? 'block' : 'none'}">
  ...
</div>
```

**Comment by marcodelgatto** [comment]
Same for me: I had to force the visibility of the menu as @alexinasra did, otherwise the menu doesn't get shown,

**Comment by marcodelgatto** [comment]
As a simpler workaround you can add this to your css:

`.dropdown.open .dropdown-menu {
  display: block;
}`

**Comment by winnemucca** [comment]
@alexinasra do you have a repo that you can share or something such as a jsbin?

**Comment by Martin-Luft** [comment]
@winnemucca please see https://github.com/valor-software/ng2-bootstrap/issues/540#issuecomment-272884775
