### ISSUE TITLE
Alert component still uses <template>

### ISSUE THREAD

**Issue by dimitrijuchtmans** [valor-software/ngx-bootstrap#1880]
'Issue' can't be clearer than the title.

https://github.com/valor-software/ngx-bootstrap/blob/development/src/alert/alert.component.ts

This causes stuff like this to happen
![image](https://cloud.githubusercontent.com/assets/6793282/24797974/0140ecc0-1b94-11e7-8912-3cff3c5ab772.png)

**Comment by valorkin** [comment]
and it is ok for v1
it is breaking change and will be available in v2

**Comment by valorkin** [comment]
beta of v2 available under @next tag in npm
