### ISSUE TITLE
How to prevent accordion toggle if click on a button in heading

### ISSUE THREAD

**Issue by psaussure** [valor-software/ngx-bootstrap#1881]
Hi there. Not really an issue but a maybe useful case for some users and maybe a feature request.

In my accordion heading, along with title of accordion, I want to put some action buttons on the right. So they are available even if the accordion is collapsed. 

I used, in pure bootstrap 3, to only put the toggle event only on some parts of my panel headind. 
**But in ngx-bootstrap, the whole heading acts like the toggler.**

**How to prevent, if the click occurs on a button, the accordion toggling? Or better, how to make only some part of `<div accordion-heading>` to trigger the toggle action?**

**Comment by valorkin** [comment]
event stopPrapagation should help 
something like
`(click)="$event.stopPrapagation(); onClick()"`

**Comment by psaussure** [comment]
The fact is the `(click)` event on my button is toggled after accordion toggling.

My example code: 

```html
<accordion-group>
   <div class="accordion-heading row" accordion-heading>
	   <span class="col-6"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> Panel Name 1</span>
	   <span class="ml-auto">                        
		   <div class="btn-group" role="group" aria-label="Action buttons">
			   <a class="btn btn-secondary btn-sm"
                                (click)="$event.stopPropagation(); lgModal.show()">
                                  <i class="fa fa-play" aria-hidden="true"></i>
                          </a>
			   <a class="btn btn-secondary btn-sm" href="#">
                                  <i class="fa fa-file" aria-hidden="true"></i>
                          </a>
		   </div>
	   </span>
   </div>
   This content is in the content of accordion.
</accordion-group>
```

In this case the `lgModal.show();` is never called.

**Comment by valorkin** [comment]
use buttons not `<a>`

**Comment by psaussure** [comment]
Ok I had a typo. It works properly. Thanks.
