### ISSUE TITLE
How to localize Datepicker?

### ISSUE THREAD

**Issue by ianfdk** [valor-software/ngx-bootstrap#1882]
Hi, I'm having trouble setting the locale on the Datepicker.

Setting the locale on my global moment object `moment.locale('fr')` works throughout my project, but doesn't impact the Datepicker.

I tried messing around in the ngx-bootstrap src files and adding `moment.locale('fr')` in `datepicker/date-formatter`. It worked.

So it seems like the Datepicker is using a different moment than I am.

Is there a proper way to access the Datepicker's moment / replace it with one I provide? If not, would you be interested in a contribution that adds this feature?

Thanks!

**Comment by akarabach** [comment]
You must import locale in app.component
`import 'moment/locale/fr';`

Added this in **app.component**
`moment.locale('fr')`

It's worked for me

**Comment by ianfdk** [comment]
Thanks! That sent me on the right track. 

I just updated to the most recent version of the library and it worked.
