### ISSUE TITLE
Time overwriting

### ISSUE THREAD

**Issue by fikretkurtiiev** [valor-software/ngx-bootstrap#1883]
I'm trying to insert date and time pickers into one [popup](http://prntscr.com/etm8pl), it works good, but if TIME is changing and after that DAY changing, time resets to 00:00.

Why it always changes time to 00:00?
Could it set time which was before the date was changed?

Thanks

**Comment by valorkin** [comment]
I will need a sample to reproduce

**Comment by fikretkurtiiev** [comment]
Just now found [plunker](https://plnkr.co/edit/FMhxwnmn62CldtDAFvT5?p=preview)
Try there just change date and you will see hours and seconds in zero 00:00

**Comment by valorkin** [comment]
yeah, it is

**Comment by valorkin** [comment]
closing in favor of https://github.com/valor-software/ngx-bootstrap/issues/1961
thanks :)
