### ISSUE TITLE
dropdown not work with routerLinkActive in the same component cause multiple onInit are called

### ISSUE THREAD

**Issue by jjlorenzo** [valor-software/ngx-bootstrap#1885]
sorry for not having time right now for more details, basically the `routerLinkActive` directive trigger a view update that calls again the dropdown onInit and this second run it isn't handled properly, I see duplicated dom and the events doesn't works, this only happens on router navigation 

## call 1
![call 1](https://cloud.githubusercontent.com/assets/48272/24828089/9ee131f6-1c1b-11e7-9e48-771e126980e5.png)

## call 2
![call 2](https://cloud.githubusercontent.com/assets/48272/24828088/9ee0d864-1c1b-11e7-8b47-e92743d0a214.png)

**Comment by jjlorenzo** [comment]
duplicated dom elements
![dom](https://cloud.githubusercontent.com/assets/48272/24828115/12d82024-1c1c-11e7-9661-2a9263ed215e.png)

If I set container="body" it works but I like the inline styles

**Comment by valorkin** [comment]
Thanks for note, I was not expecting ngOnInit run twice, can you check one thing: is ng on destroy is called in between?

**Comment by jjlorenzo** [comment]
not, I checked this trying to make some cleanup without luck because it isn't called twice, the component doesn't get destroyed, (forgive my lack off knoledge) is like gets inspected again for changes.
I can confirm that if in the router I disable(returning at method start)  `RouterLinkActive.update` it works, look at the picture, my guess is that line 129 is the one that cause the twice call.

![screen shot 2017-04-08 at am 6 18 54](https://cloud.githubusercontent.com/assets/48272/24828479/b77ae29a-1c23-11e7-9c4b-29dcd6c34735.png)

**Comment by valorkin** [comment]
It seems to me that it is router activate issue, but I will provide a hack anyway

**Comment by jjlorenzo** [comment]
thanks!
​

**Comment by valorkin** [comment]
@jjlorenzo please create an issue in angular repo and link it here
in meanwhile I will do a hack to block this behavior 

plunker with reproduced issue will be required

**Comment by razvanmitre** [comment]
Do you have a link to the issue on the angular repo?

**Comment by jjlorenzo** [comment]
maybe this https://github.com/angular/angular/issues/15925 or https://github.com/angular/angular/issues/6782
