### ISSUE TITLE
How to create a Popover that doesn't get dismiss when mouse over container. 

### ISSUE THREAD

**Issue by ronwang01** [valor-software/ngx-bootstrap#1890]
This is a non-bug issue. 
How do I create a popover that doesn't get dismiss when I mouse over the popover container but still dismiss when the mouse leave the container or the target element?

**Comment by valorkin** [comment]
This is why popover on outside click, doesn't merged yet.
There are basically no simple way, 
Only via disable hide event and closing it on your own

**Comment by ronwang01** [comment]
Is there a way to grab the nativeElement of the popover container so I could use it to add a listener to the Renderer? 

I tried doing the following in ngOnInit, but it doesn't seem to work.
`this.popover.onShown.subscribe(next => {this._renderer.listen(next.content.elementRef.nativeElement), "mouseenter", this.somefunction);
});`

**Comment by jyun5000** [comment]
This is how I made this work. 

In this example I have 3 popovers. By adding in a click event on the popover tag, and passing the `$event` to the method, it can now determine which popover needs to stay open, and then close the rest. 

### HTML CODE
```
<template #templatepop>
    <div class="popoverwindow" id="popovers.1">
        <a class="link">link 1</a>
        <a class="link">link 2</a>
        <a class="link">link 3</a>
    </div>
</template>
<div class="popovers" id="poplink.1" [ngbPopover]="templatepop" placement="bottom" (click)="closeOtherPopovers($event)">
    i am a popover element click me 
</div>

<template #templatepop>
    <div class="popoverwindow" id="popovers.2">
        <a class="link">link 1</a>
        <a class="link">link 2</a>
        <a class="link">link 3</a>
    </div>
</template>
<div class="popovers" id="poplink.2" [ngbPopover]="templatepop" placement="bottom" (click)="closeOtherPopovers($event)">
    i am a popover element click me 
</div>

<template #templatepop>
    <div class="popoverwindow" id="popovers.3">
        <a class="link">link 1</a>
        <a class="link">link 2</a>
        <a class="link">link 3</a>
    </div>
</template>
<div class="popovers" id="poplink.3" [ngbPopover]="templatepop" placement="bottom" (click)="closeOtherPopovers($event)">
    i am a popover element click me 
</div>
```

### code in component
```
closeOtherPopovers($event) {
    // get all popover link/button elements.
    let pops = document.getElementsByClassName('popovers');

    // finds all open popover elements
    let popoverwindow = document.getElementsByClassName('popoverwindow');

    // initial container for open popover windows. 
    let listOfOpenWindows = [];

    // get all the open windws.
    for (let f in popoverwindow) {
        if (popoverwindow.hasOwnProperty(f)) {
            listOfOpenWindows.push(popoverwindow[f].id.split('.')[1]);
        }
    }

    // go and close all other popovers.
    for (let i in pops) {
        if (pops.hasOwnProperty(i)) {
            let specialNumber = pops[i].id.split('.')[1];
            if (listOfOpenWindows.indexOf(specialNumber) > -1) {
                if (pops[i].id !== $event.target.id) {
                    document.getElementById(pops[i].id).click();
                }
            }
        }
    }
}

```

**Comment by jcphlux** [comment]
I created different solution based on what @jlee5000 came up with because I am loading 1000's of rows of data with a popover on each row and did not want to iterate over all of then to check for popovers.
`
private activePopover: any = null;
closeOtherPopovers(event: any) {
        var target = event.target || event.srcElement || event.currentTarget;
        if (this.activePopover !== target) {
            if (this.activePopover !== null)
                this.activePopover.click();
            this.activePopover = target;
        } else if (this.activePopover === target) {
            this.activePopover = null;
        }
    }
`

**Comment by jcphlux** [comment]
I am just trying to be helpful not sure this will help anyone but I have created a solution that solved my problem. This solution is using a 100ms timeout so that if needed an even can cancel the closing of the  popover by calling cancelBlurTimeout. If it is dismissed from a blur event it is also gives focus back to any element that was clicked to trigger the blur.

html
```
<button popover="I am a popover" (click)="popoverClick($event)" (blur)="popoverBlur($event)">Open Popover</button>
```

In the component I add this.
  ```
    private activePopover: any = null;
    private blurTimeout: any = null;

    popoverBlur(event: any) {
        var blurEl = event.target || event.srcElement || event.currentTarget;
        var target = event.relatedTarget;
        ithis.cancelBlurTimeout();
        this.blurTimeout = setTimeout((blurEl, target) => {
            if (this.activePopover === blurEl) {
                blurEl.click();
                target.focus();
            }
        },100, blurEl, target);
    }

    popoverClick(event: any) {
        var target = event.target || event.srcElement || event.currentTarget;
        if (this.activePopover !== target) {
            if (this.activePopover !== null)
                this.activePopover.click();            
            this.activePopover = target;
            this.cancelBlurTimeout();
        } else if (this.activePopover === target) {
            this.activePopover = null;
        }
    }

    cancelBlurTimeout() {
        if (this.blurTimeout !== null) {
            clearTimeout(this.blurTimeout);
            this.blurTimeout = null;
        }
    }
```
