### ISSUE TITLE
whether typeahead-editable feautre is available ?

### ISSUE THREAD

**Issue by ravirajhalli** [valor-software/ngx-bootstrap#1894]

**Comment by ravirajhalli** [comment]
We had a feature disabling typeahead as mentioned in UI Bootstrap
![ta](https://cloud.githubusercontent.com/assets/12980882/24952361/d3067640-1f94-11e7-9a06-1840eaab72b3.png)

Is this available in present version or not?

**Comment by IlyaSurmay** [comment]
No, this isn't supported.

**Comment by maurei** [comment]
It is mentioned in https://github.com/valor-software/ngx-bootstrap/blob/development/src/typeahead/typeahead.directive.ts#L107 that it is on the todo-list. is there any update on this feature? I will try to implement it myself and make PR, couldn't find any work being done on this. Would like to be sure that there indeed is no development on this feature yet
