### ISSUE TITLE
DropDown - event about change of state is not fired

### ISSUE THREAD

**Issue by TomasPlatzer** [valor-software/ngx-bootstrap#1895]
I have version 2.0.0-beta.2 . On http://valor-software.com/ngx-bootstrap/#/  I can see that there are two ouput methods for the dropdown - onShown and onHidden, but non of them seems to work. Also in example I can see (isOpenChange)="toggled($event)", but this does not work either and it is not in api reference

**Comment by mlamothe** [comment]
Sounds like a duplicate of #1886

**Comment by valorkin** [comment]
Yep, duplicate
