### ISSUE TITLE
Unable to use referenced dom element while using dropdown directive

### ISSUE THREAD

**Issue by maxailloud** [valor-software/ngx-bootstrap#1897]
Using dropdown directive and at the same using a referenced dom element in it is not possible currently.

Here is a part of my code:

```javascript
<ul *dropdownMenu class="dropdown-menu" aria-labelledby="picker">
        <li>
            <input type="text" name="search" class="form-control" placeholder="Type in an Organisation name" [(ngModel)]="search"
                   (click)="clickOnSearchField($event)" #searchField>
        </li>
</ul>
```

In this situation the `#searchField` variable is not available:

```javascript
@ViewChild('searchField') searchField: ElementRef;
```

Removing the `dropdownMenu` directive makes the variable available and the dropdown is still working.

Maybe I forgot something, it was working great before updating to the new version.

Hope it can help, ask me if you need more information.

**Comment by spongessuck** [comment]
Not sure if its related, but when I try to show a custom component in a dropdown, nothing happens when I click on the dropdown toggle.

It looks like a regression; it works in 1.6.1, but does not in 1.6.2+.

**Comment by trimeyko** [comment]
actual, doesn't work in 1.9.3, were fine in 1.6.6 with inline display

**Comment by valorkin** [comment]
`@ViewChild('searchField')` should not work, `dropdownMenu` content is detached from init
because it's a template, so this is `as designed by angular` behavior 

question is, why do you need this?

**Comment by maxailloud** [comment]
I need it in order to add a listening event on it, so i can know when someone is typing something in the text field.

**Comment by valorkin** [comment]
than use `(change)` or what you need event listener

**Comment by maxailloud** [comment]
I did that, but for a better UX I am using RxJs [debounceTime](https://www.learnrxjs.io/operators/filtering/debouncetime.html) operator, and that one is used over a native HTML element, aka the text field.

**Comment by valorkin** [comment]
That's interesting interpretation, but add regular event listener and emit value on Observable in component.
And reuse all your rxjs code
