### ISSUE TITLE
warning message template in alert, datepicker, rating, typeahead

### ISSUE THREAD

**Issue by Valerika** [valor-software/ngx-bootstrap#1900]
Please, fix errors.
Thank's.

![screenshot from 2017-04-13 19-40-28](https://cloud.githubusercontent.com/assets/15037937/25014800/efc60f46-2081-11e7-81fc-83d0ee9f6e6a.png)

**Comment by Martin-Luft** [comment]
For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.6.X because it would break Angular 2 support. You can use `"ngx-bootstrap": "2.0.0-beta.2"` or `npm install ngx-bootstrap@next`

**Comment by Valerika** [comment]
Thank's @Martin-Wegner !!!!
