### ISSUE TITLE
Add support for ng-template since the template tag is deprecated

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#1910]
Ng4 no longer supports the template tag, so I'd suggest to change it to the ng-template tag in /bundles/ngx-bootstrap.umd.js

**Comment by Martin-Luft** [comment]
For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.6.X because it would break Angular 2 support. You can use `"ngx-bootstrap": "2.0.0-beta.2"` or `npm install ngx-bootstrap@next`
