### ISSUE TITLE
The <template> element is deprecated. Angular v 4.0.2 

### ISSUE THREAD

**Issue by derrickh1980** [valor-software/ngx-bootstrap#1913]
I'm getting a warning in the browser console after updating to Angular 4.0.2. Here is the warning:

Template parse warnings:
The html template element is deprecated. Use ng-template instead.
(I had to type this out because the pasted html error was messing with message.)

I went through and changed all of the template tags inside the ngx-bootstrap folder and the warning went away. 

Is there an update specifically for Angular v4 that addresses this issue?

Thanks,
Derrick

**Comment by Martin-Luft** [comment]
For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.6.X because it would break Angular 2 support.

**Comment by derrickh1980** [comment]
Thank you for the response. I'm unable to find the beta version you mentioned. Would you mind pointing me in the right direction to find the beta version or give me the installation instructions for it? 
Thanks,
Derrick

**Comment by derrickh1980** [comment]
After some digging I was able to find it.

2.0.0-beta.1

**Comment by Martin-Luft** [comment]
You can use `"ngx-bootstrap": "2.0.0-beta.2"` or `npm install ngx-bootstrap@next`
