### ISSUE TITLE
fix(accordion): accordion [isOpen] flag is not working correctly with setting it to false per code

### ISSUE THREAD

**Issue by mschneid0207** [valor-software/ngx-bootstrap#1917]
Hello together,

the isopen flag of the accordion is working fine as long as I manage it per code.
For example a toggle button who sets the accordion flag.
But when I open/close it per mouse click than the accordion component doesn´t  react  any longer to my boolean value.  Instead it holds the last state. 

Example:
1. set the flag isAccordionOpen to false per code and display accordion => all is working fine, accordion is closed (when true then it is open)
2. mouse click to open the accordion => working fine, accordion is open
3. hidding accordion
4. display accordion again and set the flag to false per code again =>accordion is unfortunately open

`<accordion>
                            <accordion-group #group [isOpen]="isAccordionOpen">
                                <div accordion-heading>
                                    Opening Hours
                                </div>
                                <div class="openingHours">
                                    <div [innerHTML]="periods"> </div>
                                </div>
                            </accordion-group>
                        </accordion>`

Is that a bug or my fault!

Thanks a lot for your help.
Markus

**Comment by lafiza** [comment]
onOpen and onClose is getting called but glyphicon is not changing for the single click.

` <accordion-group id="accgrp3" (onOpen)="isopen3=isopen3" (onClose)="isopen3=!isopen3" >          <accordion-heading > 
            CCC            
            <i class="{{(!isopen3) ? ('pull-left glyphicon ng-scope glyphicon-chevron-right'):('pull-left glyphicon ng-scope glyphicon-chevron-down')}}" ></i>            
            </accordion-heading>
      <p>Splits:</p>
    </accordion-group>`

Advise pls

**Comment by IlyaSurmay** [comment]
`isOpen` supports two-way binding now so it should be fine, please recheck. Closed for now.
