### ISSUE TITLE
[pagination] feature proposal: one way input for page number

### ISSUE THREAD

**Issue by tdesvenain** [valor-software/ngx-bootstrap#1920]
We'd like to be able to set default page number without need of ngModel. This allows us to set initial page number value without FormsModule and without using a ViewChild

**Comment by valorkin** [comment]
could be worth to try

**Comment by BenevidesLecontes** [comment]
@valorkin another issue related to this, is that i can't change the model value without firing the `(pageChanged)` event. Use case:
![image](https://user-images.githubusercontent.com/1839361/26896359-d033fe6a-4b9a-11e7-8227-b7a72cc76c88.png)
I have an settup like in the image above when i click in the number page and the ngModel is updated the `(pageChanged)` is fired twice and my http service is called twice too. I think the `(pageChanged)` needs to be called only when the user click on the number.

**Comment by IlyaSurmay** [comment]
Sorry for silly question, but what is preventing you from using `[ngModel]="currentPage"` instead of `[(ngModel)]="currentPage"` ?

**Comment by valorkin** [comment]
Seems we need here something similar to bsValue in datepicker

**Comment by valorkin** [comment]
Added to roadmap
