### ISSUE TITLE
Accordion not working

### ISSUE THREAD

**Issue by dustyraven** [valor-software/ngx-bootstrap#1922]
ngx-bootstrap version 1.6.6

After copy-paste from http://valor-software.com/ngx-bootstrap/#/accordion

Error: Template parse errors:
'accordion-group' is not a known element:
1. If 'accordion-group' is an Angular component, then verify that it is part of this module.
2. If 'accordion-group' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

setup:
@angular/cli: 1.0.0
node: 6.10.2
os: linux x64
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2

**Comment by valorkin** [comment]
you forget to import module, check usage part:
http://valor-software.com/ngx-bootstrap/#/accordion#usage

**Comment by NeodymiumMan** [comment]
I am also getting this error.
I am using  ngx-bootstrap:1.7.1, angular 4.1.1
I have tried importing AccordionModule from ngx-bootstrap and ngx-bootstrap/accordion in the AppModule. The module imports includes AccordionModule.forRoot().
I am also getting an error regarding the closeOthers property, which may be related.

**Comment by NeodymiumMan** [comment]
Never mind, got it. I am using a SharedModule, which provides all of my common resources. AppModule imports the SharedModule, and all sub-modules import the SharedModule. In order to get this working, I had to import the AccordionModule in the SharedModule. Good info for anyone else using this method!

**Comment by johanroug** [comment]
@NeodymiumMan
I am using a shared module also. What I did was add, accordion to my shared module, but also add it to exports
```
imports: [
    CommonModule,
    RouterModule,
    FormsModule,
    ModalModule.forRoot(),
    AccordionModule.forRoot()
  ],
  exports: [
    CommonModule,
    FormsModule,
    AccordionModule,
```

**Comment by upspackageman** [comment]
I'm not using a shared module. Do I have to?
