### ISSUE TITLE
Datepiker: datepickerMode don't set 'year'-mode

### ISSUE THREAD

**Issue by alexeibostan** [valor-software/ngx-bootstrap#1925]
This is my code:
<datepicker [(ngModel)]="_dt"
              [showWeeks]="false"
              [datepickerMode]="'year'"
              [startingDay]="1"
              [yearColLimit]="4"
              (selectionDone)="onDateSelected($event)">

In this configuration the datepicker starts in month visualization, it start on year mode if set minMode to 'year'.

**Comment by eyerean** [comment]
Cannot reproduce, works fine with `[datepickerMode]="'year'"` without having to set the `minMode`. Make sure you're using the latest version.

**Comment by valorkin** [comment]
@eyerean thanks

**Comment by SujiNivedita** [comment]
I'm using the BsDatepickerModule. datepickerMode does not work on my bsDatepicker input element.
Can you please help
