### ISSUE TITLE
Template element is deprecated.

### ISSUE THREAD

**Issue by joshvanallen** [valor-software/ngx-bootstrap#1929]
Hello,
According to the build process in Angular CLI 1.0, the template element is now deprecated.
If this is already on the radar to fix, go ahead and close this. I just want to make sure that this is brought up.

Thanks!

**Comment by Martin-Luft** [comment]
For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.6.X because it would break Angular 2 support. You can use `"ngx-bootstrap": "2.0.0-beta.2"` or `npm install ngx-bootstrap@next`
