### ISSUE TITLE
Upgrade <template> to <ng-template> for Angular 4+

### ISSUE THREAD

**Issue by craig-o-curtis** [valor-software/ngx-bootstrap#1930]
Running angular-cli@v1.0.0, ng-bootstrap@^1.6.6

<template> is deprecated, slows compilation time, get warning in console:

`core.es5.js:3033 Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("="slider" aria-valuemin="0" [attr.aria-valuemax]="range.length" [attr.aria-valuenow]="value">
      [WARNING ->]<template ngFor let-r [ngForOf]="range" let-index="index">
        <span class="sr-only">({{ index < "): ng:///RatingModule/RatingComponent.html@2:6`

**Comment by ctrl-brk** [comment]
For Angular 4 use ngx-bootstrap@next

**Comment by Martin-Luft** [comment]
For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.6.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.2" or npm install ngx-bootstrap@next
