### ISSUE TITLE
If first day of month is in datesDisabled, the whole Month is disabled when going to month selection

### ISSUE THREAD

**Issue by SnezanaDichevska** [valor-software/ngx-bootstrap#1932]
On date picker, when the dates for datesDisabled are  the first day of the month, if you go to month selection, the whole month is disabled.

![download 2](https://cloud.githubusercontent.com/assets/4194546/25374594/4ad04f80-299e-11e7-88ec-a6ce8979dc02.png)

- datesDisabled are colored with red.

![e26f390f9f0f4166846da1bc595a9243](https://cloud.githubusercontent.com/assets/4194546/25374632/74b1395e-299e-11e7-9d7c-c91480d35b1a.png)

**Comment by valorkin** [comment]
new datepicker doesn't have such issue
available in v1.9.2
http://valor-software.com/ngx-bootstrap/#/datepicker

**Comment by SachinsMishra** [comment]
I am using ```ngx-bootstrap:8.0.0``` but the issue still present

https://stackblitz.com/edit/ngx-daterangepicker

**Comment by hardikchopra242** [comment]
@SachinsMishra Facing this same issue in v7.1.2, do you know any workaround?
