### ISSUE TITLE
Upgrading from ng2 to ngx - autoClose not supported?

### ISSUE THREAD

**Issue by DanielBogdanBRT** [valor-software/ngx-bootstrap#1937]
from ng2 we used  
`autoClose="outsideClick"`
for our dropdowns but in ngx it seems to not work

http://valor-software.com/ngx-bootstrap/#/dropdowns
you have `[autoClose]="false"` but it doesn't cover our use case.

ultimately the goal is to have users be able to click inside the menu and it to not close the menu, and for them to close outside the menu and it close the menu. is there a way to do this (ie with stopPropagation or having to deal with event listening)

**Comment by paesku** [comment]
There are a couple of issue related to the broken dropdown eg #1886

**Comment by valorkin** [comment]
@DanielBogdanBRT autoclose was removed in v1.6 in order to get back in later version
with support for all dynamic components

**Comment by valorkin** [comment]
closing as duplicate

**Comment by kernwig** [comment]
Duplicate of what issue @valorkin? I'd like to subscribe that issue so that I can know when I can to again to upgrade from v1.4.x.

BTW: Completely changing dropdown should have bumped the major version. :-(

**Comment by valorkin** [comment]
Yeah, I know sorry for it again.
#1933

**Comment by sergeushenecz** [comment]
when approximately we will see this feature?

**Comment by Valery-vs** [comment]
+1
