### ISSUE TITLE
Modal delay on closing

### ISSUE THREAD

**Issue by rokkuci** [valor-software/ngx-bootstrap#1938]
What can be issue?
In demo i see normal modal, but when included in my angular 2 project, on modal close it delays for ~100ms?

**Comment by valorkin** [comment]
there are delay for animation, and you can't remove it
but you actually should be able to
added to roadmap

**Comment by AmirSavand** [comment]
Reopen this because I notice modal close by `modal.close()` has a delay. It wasn't like this before. But if you press `Esc` or click on the backdrop it closes instantly like normal like always.

**Comment by stas-karmanov** [comment]
Could you fix it asap please?  It's very urgent for my project.

**Comment by pavankjadda** [comment]
You can set `animation: false` to fix this

```
   modalConfig = {
        animated: false,
        keyboard: false,
        backdrop: true,
        ignoreBackdropClick: true,
        class: 'modal-lg'
    };

```

**Comment by uberchris2** [comment]
@pavankjadda But I don't want to disable animations, I just don't want the delay.

**Comment by pavankjadda** [comment]
Makes sense, #5861 should fix this
