### ISSUE TITLE
Â character in pager 'Next' and 'Previous' buttons and pager buttons inheriting bootstrap box shadow on active state.

### ISSUE THREAD

**Issue by royporter7** [valor-software/ngx-bootstrap#1939]
When leaving the 'Next' and 'Previous' text as default on the Pager component, there is an odd artifact next to the arrow icons, as seen in the attached image. Perhaps this may be a problem only on my end, and I'm open to suggestions as to why it may be so.

![pagination artifacts](https://cloud.githubusercontent.com/assets/6437024/25461485/ae680bc0-2b2c-11e7-856f-f9488e94d875.PNG)

I was able to work around this by overriding the 'Next' and 'Previous' text by specifying them through the nextText and previousText inputs.

Additionally there is a box shadow on the pager buttons when clicking the button. (See attached image)

![box shadow](https://cloud.githubusercontent.com/assets/6437024/25461643/790f38f8-2b2d-11e7-8d6f-9d584f641697.PNG)

Similarly, you can override the active state of Bootstraps 'btn' class - but I suggest removing the btn class from these elements entirely as they're not necessarily.

**Comment by valorkin** [comment]
I am afraid it is something on your end
does it works fine for you on demo page: http://valor-software.com/ngx-bootstrap/#/pagination
?

**Comment by srinigowda** [comment]
could be the same as #1997

**Comment by valorkin** [comment]
closing for no updates
