### ISSUE TITLE
Correct Radio button group markup documentation required for reactive forms

### ISSUE THREAD

**Issue by roscopeeco** [valor-software/ngx-bootstrap#1940]
Can someone please provides the correct html markup and typescript example to use radio buttons groups in ReactiveForms?

I am running v1.6.6 and cannot get button groups to work with reactive forms?

https://github.com/ng-bootstrap/ng-bootstrap/pull/1299/files

I have tried using markup from the above link but with no luck. Also looked at #1023 but that is closed even though this is not working (or documented incorrectly.

thanks

**Comment by pantonis** [comment]
same problem here

**Comment by valorkin** [comment]
added, will be released in v1.7.2
