### ISSUE TITLE
Don't manipulate typeahead-container with inline styles

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#1942]
The typeahead-container's inline styles cause a lot of undesired side effects.

`<typeahead-container class="dropdown open" style="position: absolute; display: block; top: 84px; left: 13px;">...</typeahead-container>`

1) Beside the fact, that inline style should be avoided in general, there is no obvious reason to add them in this case. Typeahead would work anyway (as you can see in the standard bsdropdown component, too).

2) In particular, setting "left" and "top" properties **periodically** is driving me crazy. It's causing jumping of the dropdown in edge cases. Or if you have a CSS animation on that element, it looks like flickering.

3) It's even not possible to set the option list to 100% input width. See here: #190. This issue would be easily fixable with CSS without having those periodical inline style refreshes.

**Comment by ghost** [comment]
Obsolet, found workaround.

**Comment by martinmanzo** [comment]
Hi @KatzeKahn, could you share the workaround?

**Comment by ghiscoding** [comment]
@KatzeKahn @martinmanzo 
I'm also having this flickering, so I'm also interested in the workaround
