### ISSUE TITLE
Tooltip tests are skipped

### ISSUE THREAD

**Issue by junglebarry** [valor-software/ngx-bootstrap#1944]
Sorry if this is the wrong place to file this, but I was browsing the tests and noticed that [all of the tests for `tooltip` are skipped](https://github.com/valor-software/ngx-bootstrap/blob/development/src/spec/tooltip.directive.spec.ts#L29).   There was no commentary around this in the code to indicate whether this was deliberate, so I thought I'd raise an issue for visibility.

**Comment by valorkin** [comment]
thx, back online now
