### ISSUE TITLE
How do you delete a tab completely when a condition is false

### ISSUE THREAD

**Issue by DBereznak** [valor-software/ngx-bootstrap#1946]
On the app that I am developing, I have a mobile menu that has a standard menu, and a admin menu. I have set each one on a tab. However I don't want the admin nav to show if user is not logged in as a admin. I tried to put a *ngIf="loggedIn" on the Admin tab, while it did hide the admin menu, the actual tab was still visible. Right now I have two menus the one with tabs and one without tabs, and I put a *ngIf on each menu to check if user is logged in. I was hoping there was a way just to hide the Admin tab, instead of having 2 different menus.

**Comment by valorkin** [comment]
tab, menu... what components are you really using and what you want to hide?

**Comment by IlyaSurmay** [comment]
Closing for no updates.
