### ISSUE TITLE
Dropdown List issue

### ISSUE THREAD

**Issue by robinmaple** [valor-software/ngx-bootstrap#1948]
Ng4 and ng2-bootstrap, copied over the demo code and the dropdown list doesn't expand on click. Not sure this is is the same as issue 1886. 

Thanks!

**Comment by damiandennis** [comment]
Also experiencing issues with the dropdown, seems to be causing some major issue, I have 100 of them on a page and it barely functions. No issues when I was on 2.4...

**Comment by damiandennis** [comment]
actually it seems like when you have more than one in a single component, it goes crazy and freezes up the page.

**Comment by damiandennis** [comment]
Yeah its the large number of dropdowns on the page causing the issue, I converted to a simple click toggle and now the issue has disappeared, seems to work ok for a small number of dropdowns, Add about 500 to a page and you will see what I mean.

**Comment by valorkin** [comment]
@robinmaple this issues is fixed in latest version
but ng2-bootstrap was renamed to ngx-bootstrap
so please update your code and issue will go away

**Comment by valorkin** [comment]
@damiandennis I knew about this, I will try to minimize this issue
