### ISSUE TITLE
The <template> element is deprecated. Use <ng-template> instead 

### ISSUE THREAD

**Issue by on3al** [valor-software/ngx-bootstrap#1952]
AlertModule is using deprecated template tag.

**Comment by Martin-Luft** [comment]
Please search for same issues before opening a new one...

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.6.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.2" or npm install ngx-bootstrap@next
