### ISSUE TITLE
Template Deprecation warning for Alert Component

### ISSUE THREAD

**Issue by pderks** [valor-software/ngx-bootstrap#1953]
Version of Angular: 4.0.3
Version of ngx-bootstrap: 1.6.6

**Current Behavior:**
With versions 4.x.x of Angular the alert component gives the following compiler warning:

The template element is deprecated. Use ng-template instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///C:/**/node_modules/ngx-bootstrap/alert/alert.component.d.ts.AlertComponent.html@1:0

**Expected Behavior:**
template tag is converted to ng-template and no warning is shown for Angular versions 4.x.x

**Comment by fchiumeo** [comment]
please, please search before creating new issues
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues
