### ISSUE TITLE
fix(carousel): unable to update  carousel with dynamic values

### ISSUE THREAD

**Issue by Anurag-Sing** [valor-software/ngx-bootstrap#1954]
hi,
    I'm iterating carousel slider with 5 values and interval of 2000 millisecond. After every interval of 10000 millisecond i'm updating the value of iterator but i'm unable to see the updated value in slider. Neither any error in console.
Please help.

here is my code:
.ts

  private summaries: Array;

  //random 5 elements will be stored here
  private carouselOutPutArray: Array<any> ;

  private timer;
  
  // Subscription object
  private sub: Subscription;

  constructor(private router: Router) {
    this.summaries = [
      {'name': 'Anurag', id: 1},
      {'name': 'dibyendu', id: 2},
      {'name': 'Paresh', id: 3},
      {'name': 'Sumit', id: 4},
      {'name': 'skanda', id: 5},
      {'name': 'sourav', id: 6},
      {'name': 'bhushan', id: 7},
      {'name': 'dhirappa1', id: 8},
      {'name': 'dhirappa2', id: 9},
      {'name': 'dhirappa3', id: 10},
      {'name': 'dhirappa4', id: 11},
      {'name': 'dhirappa5', id: 12},
      {'name': 'Vaibhav', id: 13}
    ];
  }

  private populateCarouselOutput(count: number): void {
    let tmp = this.summaries.slice();
    this.carouselOutPutArray = new Array();

    let ret = [];

    for (let i = 0; i < count; i++) {
      let index = Math.floor(Math.random() * tmp.length);
      let removed = tmp.splice(index, 1);
      // Since we are only removing one element
      ret.push(removed[0]);
    }
    this.carouselOutPutArray = ret;
    console.log('final output ', this.carouselOutPutArray)
  }

  public ngOnInit(): void {

    this.timer = Observable.timer(0,10000);
    // subscribing to a observable returns a subscription object
    this.sub = this.timer.subscribe(()=> this.populateCarouselOutput(5));
  }

  ngOnDestroy(){
    console.log("Destroy timer");
    // unsubscribe here
   this.sub.unsubscribe();

  }

.html

    <carousel [noPause]="true" [interval]=2000>

      <slide *ngFor="let summary of carouselOutPutArray ">
        <div>
          <h2>{{summary.name}}</h2>
        </div>
      </slide>
    </carousel>

**Comment by bgpedersen** [comment]
I fought with this for some time. Using the activeSlideIndex removes the error, but then the slide was stuck at position 0. To fix this, I put *ngIf on the slide, forcing it to re-render, and setting my slideshow to null when updating, and inserting setTimeout with 0, and only after this, setting the updated slide in here.

HTML
```
<carousel [interval]="system.carouselInMilliseconds"
  *ngIf="system"
  [(activeSlide)]="activeSlideIndex">
  <slide *ngFor="let item of system.News; let index = index"
    class="animated"
    [ngClass]="{'slideInRight': index === activeSlideIndex, 'slideOutLeft': index !== activeSlideIndex}"
    [routerLink]="['/news', item.id]">

    <div class="cover-img"
      [ngStyle]="{'background-image': 'url(' + item.image.path + ')'}">
    </div>

    <div class="cta-txt font-poppins">
      <h2 class="truncate">{{item.Headings.text}}</h2>
      <span>{{system.translations.news.subtitle}}</span>
    </div>
  </slide>
</carousel>
```

COMPONENT
```
systemEventListener() {
    // on system updated emitted, update this components system data
    this.systemSub = this.dataService.systemUpdated.subscribe(response => {
      this.logger.log('SharedCarouselComponent: systemEventListener response: ', response);
      // system must reset to avoid changeError in slider and system set in timeout to work
      this.system = null;
      this.activeSlideIndex = 0;

      setTimeout(() => {
        this.system = response;
        this.logger.log('SharedCarouselComponent: systemEventListener this.system: ', this.system);
      }, 0);

    });
  }
```

**Comment by IlyaSurmay** [comment]
Please provide plunkr/stackblitz with reproduction if this is still relevant.
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IlyaSurmay** [comment]
4+ months without updates, closing.
