### ISSUE TITLE
Timepicker Seconds Field

### ISSUE THREAD

**Issue by touqeershafi** [valor-software/ngx-bootstrap#1957]
- [x] Feature Request

## Current Behavior:
Currently timepicker does not have seconds field.

## expected Behavior
It should have seconds field as well, with `up` `down` arrow.

**Comment by paesku** [comment]
Yes, this Feature is currently missing. Would like to see this as well.
👍

**Comment by conan747** [comment]
I could use a minute:seconds kind of timepicker, where the minutes can be >60.
