### ISSUE TITLE
<template> deprecation warning with bsModal on ng4.x

### ISSUE THREAD

**Issue by fergusg** [valor-software/ngx-bootstrap#1958]
Since upgrading my app to ng4, bsModal gives the following compilation error:
```
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): 
ng:///portal/node_modules/ng2-bootstrap/alert/alert.component.d.ts.AlertComponent.html@1:0

```

**Comment by Martin-Luft** [comment]
Please search for same issues before opening a new one...

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.6.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.2" or npm install ngx-bootstrap@next
