### ISSUE TITLE
template element is deprecated, use ng-template instead

### ISSUE THREAD

**Issue by mkokotovich** [valor-software/ngx-bootstrap#1959]
When building my project that uses ngx-bootstrap with Angular 4, I see the following warning:

The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
<div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///tmp/build_f01f908405d1f17d7e65f750833deb24/front_end/node_modules/ngx-bootstrap/alert/alert.component.d.ts.AlertComponent.html@1:0

It's just a warning, but seems like something that should be fixed at some point.

**Comment by Martin-Luft** [comment]
Please search for same issues before opening a new one...

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.6.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.2" or npm install ngx-bootstrap@next

**Comment by mkokotovich** [comment]
Sorry, if you can believe it I actually did try to search, but now that I think of it I might have been only searching open issues. Thanks for the explanation.
