### ISSUE TITLE
Tab headings don't display wrapped text correctly

### ISSUE THREAD

**Issue by mkokotovich** [valor-software/ngx-bootstrap#1960]
I have an angular project that uses tabs. When the text in the headings needs to wrap (on mobile, primarily) it can cause the tab heading to appear detached from the tab content.

See example:
![tab_heading_wrap_problem](https://cloud.githubusercontent.com/assets/14296374/25720233/cbeffde2-30d1-11e7-9389-1ea2c1a88413.png)

I found I can manually (and temporarily) fix it by setting the height on the heading to 100%:

![tab_heading_set_height_100](https://cloud.githubusercontent.com/assets/14296374/25720231/cbed1870-30d1-11e7-906e-d716a0c9605d.png)

![tab_heading_wrap_fixed](https://cloud.githubusercontent.com/assets/14296374/25720232/cbed1b68-30d1-11e7-989a-0d0f8c7fa451.png)

I'm not sure the best place to actually put this, though, I can't seem to find any stylesheets that could be modified. Hopefully someone more familiar with this area would know where to set that.

Thanks!

**Comment by mkokotovich** [comment]
Any thoughts on this? This is an eye-sore when loading my page on mobile.

**Comment by IlyaSurmay** [comment]
This is more related to bootstrap than ngx-bootstrap. We don't modify bootstrap stylesheet, so for that kind of issues you may need to add your own styles.
