### ISSUE TITLE
feat(datepicker): don't change time of date

### ISSUE THREAD

**Issue by touqeershafi** [valor-software/ngx-bootstrap#1961]
- [x] Bug Report

## Current Behavior
When ever user selects date from `datepicker` it also changes the time of that `ngModal` before changing the date initial value is: `Fri May 05 2017 13:30:12 GMT+0500 (PKT)` after when user selects date `ngModel` value changes to `Fri May 05 2017 00:00:00 GMT+0500 (PKT)`

## Expected Behavior
it should maintain the time of `ngModel`  when ever user selects date.

**Comment by valorkin** [comment]
please check it
in new datepicker (new style and pop up version)
check this out: http://valor-software.com/ngx-bootstrap/#/datepicker#examples

**Comment by IlyaSurmay** [comment]
Closing for no updates.

**Comment by Keksdroid** [comment]
When I pick a date on a null value, the time should be 00:00:00 though. Not the case in v2.0.2, it just adds the current time.

**Comment by rolandpeelen** [comment]
Agreed. What is the status on this? I noticed when changing the date if there is no date it just sets the current time?
