### ISSUE TITLE
DatePicker activeDateChange event not getting fired

### ISSUE THREAD

**Issue by CodingDK** [valor-software/ngx-bootstrap#1962]
Hello.

The output event `activeDateChange` is not geting fired right now. I think this is a bug

My code looks like this:
`<datepicker [(ngModel)]="model.date" [showWeeks]="true" [startingDay]="1" (activeDateChange)="hideDatePickerPopup()"></datepicker>`

If I use the `selectionDone` event it's works, but my "popup" will disappear before my `model.date` is set.

I used version: 2.0.0-beta.2

**Comment by djindjic** [comment]
same behavior in my case
