### ISSUE TITLE
Create a contribution guideline and leave contact info

### ISSUE THREAD

**Issue by SnezanaDichevska** [valor-software/ngx-bootstrap#1965]
Please make a contribution guideline so that contributors have a convention to follow. Thanks in advance!

**Comment by SnezanaDichevska** [comment]
I want to make a pull request where the disabling of the month in datepicker is fixed

**Comment by valorkin** [comment]
just pushed by @IlyaSurmay

**Comment by FrancescoBorzi** [comment]
I believe we should reference it from the README.md, see https://github.com/valor-software/ngx-bootstrap/pull/3067
