### ISSUE TITLE
Angular 4 Template Warning

### ISSUE THREAD

**Issue by chelhan** [valor-software/ngx-bootstrap#1967]
The \<template> element is deprecated. Use \<ng-template> instead.

**Comment by Martin-Luft** [comment]
Please search for same issues before opening a new one...

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.6.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.2" or npm install ngx-bootstrap@next

**Comment by chelhan** [comment]
@Martin-Wegner : Thanks for quick response. I performed wrong search in open issues. Sorry for inconveniences caused.
