### ISSUE TITLE
Error resolving values statically

### ISSUE THREAD

**Issue by psaussure** [valor-software/ngx-bootstrap#1968]
Error encountered by building app with `ng build --prod` under CLI 1.0.1 and Angular 4.0.3:

> ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in C:/project/node_modules/ngx-bootstrap/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in C:/Uproject/node_modules/ngx-bootstrap/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in C:/project/node_modules/ngx-bootstrap/node_modules/@angular/core/core.d.ts

Do you know how to fix this? I can't build my solutions due to this error in ngx-bootstrap. 

Using ngx-bootstrap `1.6.6`

**Comment by valorkin** [comment]
it happens from time to time, I don't know the real reason for it
and it happens to me not only with ngx-bootstrap
usually fixed with clean install
