### ISSUE TITLE
No Tooltip Functionality

### ISSUE THREAD

**Issue by queejie** [valor-software/ngx-bootstrap#1969]
We have tried everything to get tooltips to show, but we get no result at all when hovering.  We are importing TooltipModule and using TooltipModule.forRoot().  We have bootstrap 4 styles loading.  Pasting any button example from the demo page into our html template results in a button with no tooltip at all.  We can see the bs-tooltip-container appearing in the inspector when we hover, but nothing appears.  We've tried setting the z-index, display, width and height of bs-tooltip-container so we can be sure it isn't a style, but still do not see anything.  Do you have any idea what we might be doing wrong?

**Comment by nielswitte** [comment]
I've had a similar problem and found that the css opacity was 0.
