### ISSUE TITLE
'show' class not added to modal and backdrop

### ISSUE THREAD

**Issue by dushkostanoeski** [valor-software/ngx-bootstrap#1971]
I'm implementing a modal that is shown depending on a boolean value in a service. I ran into the #810 issue and made it 'work' except that the modal and the backdrop are missing the 'show' class. I have the same issue with both 1.6.6 and 2.0.0beta.2. I'm using angular 4.1.0 and bootstrap 4.0.0-alpha.6

Here's the component and service code:

	import { Injectable } from '@angular/core';
	import { BehaviorSubject } from 'rxjs/BehaviorSubject';

	@Injectable()
	export class SpinnerService {

		private active = new BehaviorSubject<boolean>(false);
		spinnerObservable = this.active.asObservable();

		show(): void {
			this.active.next(true);
		}

		hide(): void {
			this.active.next(false);
		}
	}

	import { Component, AfterViewInit, ViewChild } from '@angular/core';
	import { SpinnerService } from '../core/shared/spinner.service'
	import { ModalDirective } from 'ngx-bootstrap/modal';

	@Component({
		selector: 'app-spinner',
		templateUrl: 'spinner.component.html'
	})
	export class SpinnerComponent implements AfterViewInit {

		@ViewChild('staticModal')
		staticModal: ModalDirective;

		constructor(private service: SpinnerService) {
		}

		ngAfterViewInit(): void {
			this.service.spinnerObservable.subscribe(active => {
				active ? this.staticModal.show() : this.staticModal.hide();
			});
		}
	}

	<div #staticModal="bs-modal" aria-hidden="true" aria-labelledby="staticModalLabel" bsModal class="fade modal" role="dialog" tabindex="-1">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title pull-left">Please wait</h4>
				</div>
				<div class="modal-body">
					<div class="align-middle text-center">
						<i class="fa fa-5x fa-fw fa-spin fa-spinner"></i>
						<span class="sr-only">Please wait</span>
					</div>
				</div>
			</div>
		</div>
	</div>

The generated code in browser has the 'in' class added but not 'show'

	<app-spinner>
		<div aria-hidden="false" aria-labelledby="staticModalLabel" bsmodal="" class="fade in modal" role="dialog" style="display: block;" tabindex="-1">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title pull-left">Please wait</h4>
					</div>
					<div class="modal-body">
						<div class="align-middle text-center">
							<i class="fa fa-5x fa-fw fa-spin fa-spinner"></i>
							<span class="sr-only">Please wait</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</app-spinner>

Current workaround I'm using to show the modal only is 
    
    [ngClass]="{'show': service.active | async }"

**Comment by slubowsky** [comment]
Did you add <script>window.__theme = 'bs4';</script> to you html? That's currently required when using bootstrap 4

**Comment by dushkostanoeski** [comment]
My app component code looked like this

    @Component({
        selector: 'body',
        templateUrl: 'app.component.html'
    })
    export class AppComponent {
    }

    <app-spinner></app-spinner>
    <router-outlet></router-outlet>
    <script>window.__theme = 'bs4';</script>

I moved the script tag inside the `index.html` body and this fixed the modal, but not the backdrop. The modal appears now, but the backdrop still doesn't have the `show` class

    <bs-modal-backdrop class="modal-backdrop fade in" ng-version="4.1.0"></bs-modal-backdrop>

**Comment by dushkostanoeski** [comment]
I nested the `app-spinner` inside a div and this made the backdrop show as well. Don't know if this is a bug or not, but shouldn't the backdrop appear no matter where the modal is?

**Comment by jlberrocal** [comment]
@dushkostanoeski i'll highly recommend you to set that script in your index.html
