### ISSUE TITLE
Timepicker does not expose any Output events

### ISSUE THREAD

**Issue by ranvari** [valor-software/ngx-bootstrap#1973]
I am trying to use the timepicker component.  But it does not expose any explicit Output events for changes like the datepicker. In the examples there is (change) being used but this does not fire when using the arrow buttons. It only fires when the input is directly changed. The only thing that works is ngModelChange which is not what I want, because it fires right away without user interaction. 

Is there a workaround?

**Comment by valorkin** [comment]
`<timepicker ngModel (ngModelChange)="onChange($event)"></timepicker>`
is the best workaround we could get

**Comment by valorkin** [comment]
mentioned issues is fixed in #2058

**Comment by felimartina** [comment]
thanks @valorkin that helped.
