### ISSUE TITLE
Question about multiple popovers in child component

### ISSUE THREAD

**Issue by hbweb** [valor-software/ngx-bootstrap#1974]
I'm trying to create multiple popover buttons via *ngFor and each popover button is a part of a child component. 

Main template

```
<h1> Hello All </h1>
<div *ngFor="let item in items; let i=index ">
 <my-custom-list-item [prop]="someVal" [index]="i"></my-custom-list-item>
</div>
```

In my 'my-custom-list-item' child component

```
<ng-template #releasePopover>
  <another-content-comp [content]="content"></another-content-comp>
 <button type="button" (click)="pop.hide()">Close</button>
</ng-template>

<button type="button" #pop="bs-popover" [popover]="releasePopover">Open {{index}}<button>
```

Above code won't work since templateRef is repeated itself multiple time on the DOM and popover get confused. 

How can we approach this case study?

Thanks

**Comment by hbweb** [comment]
Another approach that I've tried is to bring `<ng-template>..</ng-template>` template block to the main template so all popover button can share one single templateRef.. However, by doing this  templateRef would be accessible from child component ..aahhh!!!

**Comment by valorkin** [comment]
> Above code won't work since templateRef is repeated itself multiple time on the DOM and popover get confused.

this should be reported to angular as an issue, btw
IMHO when you have #templateRef scoped to your component all should work fine

**Comment by IlyaSurmay** [comment]
Works ok [here](https://plnkr.co/edit/xNSiBpUw6o2mD9VwW0mw?p=preview), last versions of ngx-bootstrap and angular are used, please take a look. Closing this issue for now.

**Comment by doczoidberg** [comment]
this does not work with angular 6+
