### ISSUE TITLE
select inside popover is not working

### ISSUE THREAD

**Issue by brihaspati** [valor-software/ngx-bootstrap#1977]
I am trying to show a list of select options inside the popover, and I tried the dynamic html way by giving the [innerHtml] property a string value containing the select as below. But its not displaying it as a select option at all. It is showing it as just a string. looking for help

**component class**
public content: string = `<select><option>First</option><option>Second</option></select>`;

**html**
<template #popoverFilter>
    <div [innerHtml]="content"></div>
</template>

<button type="button" class="btn btn-default btn-secondary" [popover]="popoverFilter"
 placement="bottom">
  filter
</button>

![image](https://cloud.githubusercontent.com/assets/3582818/25998939/dc30dc38-3740-11e7-93ea-dac5524ecef2.png)

**Comment by valorkin** [comment]
because angular sanitizes your html
check samples here:

**Comment by valorkin** [comment]
http://valor-software.com/ngx-bootstrap/#/popover#dynamic-content

**Comment by valorkin** [comment]
if you will need help jump to ngx slack
