### ISSUE TITLE
how to import bootstrap in aot with webpack

### ISSUE THREAD

**Issue by moslemezati** [valor-software/ngx-bootstrap#1978]
I read many articles but none of them do not mention how to add bootstrap in aot except one that use rollup.

**Comment by Martin-Luft** [comment]
In `vendor.ts` just insert: `import 'bootstrap/dist/css/bootstrap.css';`

**Comment by moslemezati** [comment]
thanks I added in styleUrls and also I use less-loader to load less it works.
