### ISSUE TITLE
pageChanged fire on ngModel !=1

### ISSUE THREAD

**Issue by euprogramador** [valor-software/ngx-bootstrap#1980]
in pagination component, when currentPage is 2 or high, pageChanged is fired without page change.

**Comment by IlyaSurmay** [comment]
Please provide plunkr/stackblitz with reproduction if this is still relevant.
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IlyaSurmay** [comment]
Closed as can't reproduce (tested with ngx-bootstrap@2.0.0-beta.8), will be reopened if we have sample to reproduce
