### ISSUE TITLE
feat(google closure): add google closure compiler support

### ISSUE THREAD

**Issue by vforv** [valor-software/ngx-bootstrap#1988]
Is it possible to implement this lib with closure(https://github.com/angular/closure-demo) ?

I tried but get this error:
http://stackoverflow.com/questions/44100512/how-to-implement-google-closure-and-ngx-bootstrap

Any idea?

**Comment by banjankri** [comment]
I think using ng-packagr (https://github.com/dherges/ng-packagr) to produce bundles should be enough to have that covered, as it uses tsickle to annotate bundles for closure compiler.

This could greatly simplify your setup as I can see you are doing all the packaging yourselves.
