### ISSUE TITLE
LazyLoad tab-content in tabset

### ISSUE THREAD

**Issue by tommueller** [valor-software/ngx-bootstrap#1989]
Hi,

any chance to add a feature to only load the tabs content on selecting the tab?

Thanks
Tom

**Comment by tommueller** [comment]
Found a way, as simple as an ```*ngIf``` on the first wrapping element within the tab

**Comment by MaZderMind** [comment]
@tommueller Hi! Which condition did you use on the `*ngIf`? I think this is such a common case, that it would be good to have an example in the docs for it.

**Comment by thys-unomena** [comment]
Hi @MaZderMind 

One way is to check if the tab index is active:

*ngIf="staticTabs.tabs[1].active"
