### ISSUE TITLE
Modal not shown with bootstrap4

### ISSUE THREAD

**Issue by mastropinguino** [valor-software/ngx-bootstrap#1990]
Hi all,
I tried to open a sample modal dialog but nothing was shown.
The DOM is changed but nothing is display.

My setup is the following:
- node v7.5.0
- Angular4 (4.1.2)
- ngx-bootstrap (1.6.6)
- bootstrap (4.0.0-alpha.6)

My code is:

```html

      <button type="button" class="btn btn-primary" (click)="childModal.show()">Open child modal</button>

      <div bsModal #childModal="bs-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title pull-left">Child modal</h4>
              <button type="button" class="close pull-right" aria-label="Close" (click)="hideChildModal()">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              I am a child modal, opened from parent component!
            </div>
          </div>
        </div>
      </div>
    </div>
```

By inspecting the DOM I found that bootstrap4 changed the class name when modal is shown (from .modal.fade.in (bootstrap < 4) to .modal.fade.show (in bootstrap4)

Currently I patched my app with the following code, but I'm hoping for a definitive fix in the library.

```ts
// app.module.ts

/** FIXUP for ngx-bootstrap/modal**/
import { ClassName } from 'ngx-bootstrap/modal/modal-options.class';
ClassName.IN = 'show';
```

Thanks !!

**Comment by slubowsky-course** [comment]
Did you add this to your HTML?
```
<!-- Enable bootstrap 4 theme -->
<script>window.__theme = 'bs4';</script>
```
Thats currently required for v4

**Comment by mastropinguino** [comment]
Thanks @slubowsky-course .
I removed my hack and inserted your snippet, and now the modal works like a charm.

I think that issue could be closed.

Thanks a lot!
