### ISSUE TITLE
Problem with AOT compilation

### ISSUE THREAD

**Issue by sergeushenecz** [valor-software/ngx-bootstrap#1993]
I have used tab component  and build the command ng build --prod --aot and I am getting errors 
![image](https://cloud.githubusercontent.com/assets/7217517/26350841/83c3b004-3fbd-11e7-8766-684278be3eb1.png)

Can you explain what happened?

version  "ng2-bootstrap": "1.6.3",
verrsion  angular cli: "1.0.0",

**Comment by vovikdrg** [comment]
@sergeu90  Can you provide better error descriptions? because this information is useless.

I am using same version and no problems at all. 

BTW. ng build --prod  by default will enable aot so no needs to specify it

**Comment by sergeushenecz** [comment]
I updated library and this fixed my problem
