### ISSUE TITLE
Unexpected character [Â]  [closed ? false :Â (lazy ? selected : true)]

### ISSUE THREAD

**Issue by srinigowda** [valor-software/ngx-bootstrap#1997]
Getting errors when angular-cli prod build is done with --aot=false 

![ng2-bootstrap-error](https://cloud.githubusercontent.com/assets/44777/26404132/66b76176-40ae-11e7-95e1-ca789ed0e45c.png)

**Comment by valorkin** [comment]
searched all over src, there are not such *ngIf condition in ngx-bootstrap

**Comment by IlyaSurmay** [comment]
No updates, closing.
