### ISSUE TITLE
[Request] Dynamic modal

### ISSUE THREAD

**Issue by x1unix** [valor-software/ngx-bootstrap#1998]
Please add feature to allow to create dynamic modal windows throw TypeScript code, like ng-bootstrap at angular 1.x

**Comment by larryspace** [comment]
+1

I was trying to achieve this for a long time, has not found the right way.

Now do this:

`const modalComponentFactory = this.componentFactoryResolver.resolveComponentFactory(ModalComponent);
        const _componentRef = this.modal.createComponent(modalComponentFactory);
        _componentRef.instance['_componentRef'] = `_componentRef;`

`this._componentRef.destroy();`

But now stuck in a place, do not know how to create a modal window to the body node, and how to achieve the modal window component of the transfer

**Comment by IlyaSurmay** [comment]
Work is in progress  #2047
