### ISSUE TITLE
Datepicker with inputControl

### ISSUE THREAD

**Issue by jkumawat** [valor-software/ngx-bootstrap#200]
Hello Guys, 

I have looked at the library and used date-picker from ng2-bootstap but unfortunately i want to show date-picker on input click only and hide it after selection. 

I have gone through documentation but didn't find any example to use it with Input control. 

Any guidance or tips on this??

Issue: On Setting showWeeks to false -- not triggering visibility. Weeks are always visible.

**Comment by madhav5589** [comment]
Would like to have the same feature.

**Comment by midnightriot** [comment]
This would be great to have. There is a datepicker-popup directive, (version 1.0.2-beta.1)but I can't get it to work and there isn't any documentation for it.

**Comment by project707** [comment]
+1 The popup method is the only really useful format for many apps that don't have a ton of space or aren't centered around the datepicker itself in some way. Generally all you have room for is a date field, but you need the picker for ease of use, consistency, formatting, etc..

**Comment by zcsongor** [comment]
+1

**Comment by leonhardt** [comment]
+1

**Comment by sanjayjha** [comment]
I am also looking for popup datepicker on input click. I saw at some place it is not yet implemented. Any specific date for implementation?

**Comment by valorkin** [comment]
this is one to one with #273 
closing this one

**Comment by sanjayjha** [comment]
So is this resolved? If yes can I get an example to use this feature?

**Comment by valorkin** [comment]
@sanjayjha I just closed duplicated issues

**Comment by sanjayjha** [comment]
Thanks, do we have a tentative date for this feature?

**Comment by sanjayjha** [comment]
I used ng2-datepicker but have following issues:

popup component not getting located relatively,
Always shows current date though date value is past date
not able to change date format to mm/dd/yyyy.

**Comment by kemmis** [comment]
bump.

I too would use this if it was a popup and not inline.

**Comment by valorkin** [comment]
join slack to follow up updates: https://www.hamsterpad.com/chat/ng2

**Comment by somzJosf** [comment]
Try this. 
   `<input type="text" [ngModel]="dt" (focus)="showDatePicker = true">
    <div *ngIf="showDatePicker" style="position: absolute; z-index:10; min-height:290px;">
    <datepicker [(ngModel)]="dt" [minDate]="minDate" [showWeeks]="true"></datepicker>
  </div>`

**Comment by vishalgajjar** [comment]
Guys, I tried this and I am able to get the datepicker on calendar icon clock 

`<div class="input-group" dropdown dropdown-append-to-body>
<input type="text" class="form-control input-sm" name="inputBeginDate" [(ngModel)]="effectiveBeginDate"  />
<span id="btn-append-to-body" type="button" class="input-group-addon fa fa-calendar" dropdownToggle></span>
<div class="dropdown-menu" role="menu" aria-labelledby="btn-append-to-body">
<datepicker name="test"  [showWeeks]="false" [(ngModel)]="effectiveBeginDate"></datepicker>
</div></div>`

CSS:

`datepicker{
position: absolute;
    z-index: 1001;
}
datepicker .btn{
    padding: 5px !important;
    padding-left: 10px !important;
    padding-right: 10px !important;
}
datepicker .btn .text-muted{ line-height: inherit !important;}
datepicker .well
{border: 3px solid #2b669a !important;}`

only issue is that I don't know how the get "MM/dd/yyyy" date format. if anyone knows then let me know please .

**Comment by VirendraWankhede** [comment]
Is there any way to auto correct date for input field using ng2 date picker ?

**Comment by sanjaygohil** [comment]
Use pipe in Textbox for date Format. its work for me.
like this  **value="{{date | date:'MM/dd/yy'}}"** 
`<input type="text" class="form-control " name="inputBeginDate" value="{{date | date:'MM/dd/yy'}}" />`

BUT I have problem in datepicker popup closed when  user click on navigation arrow and also in month  header 
i used this code 

```
<div class="input-group" dropdown dropdown-append-to-body>
                <input type="text" class="form-control " name="inputBeginDate" value="{{date | date:'MM/dd/yy'}}"  />
                <span class="input-group-addon" dropdownToggle><i class="fa fa-calendar"></i></span>
                <div class="dropdown-menu" role="menu" aria-labelledby="btn-append-to-body">
                    <datepicker name="test" [showWeeks]="false"  [(ngModel)]="date" ></datepicker>
                </div>
            </div>
```

Please let me know if anyone know about this issue.
Thanks

**Comment by alanhe421** [comment]
+1

**Comment by ghost** [comment]
Any update on popup thing?? Are you able to achieve?

**Comment by razorcd** [comment]
+1

**Comment by gokhancelik** [comment]
+1

**Comment by sergeushenecz** [comment]
Any update on popup thing?? Are you able to achieve?

**Comment by arnoldjair** [comment]
+1

**Comment by joncaris** [comment]
+1

**Comment by GoldenTao** [comment]
I've got this working with the autoClose input. `[autoClose]="'outsideClick'"`  I think that is the best you can do at this stage.

In your example... 

```
<div class="input-group" dropdown dropdown-append-to-body [autoClose]="'outsideClick'">
    <input type="text" class="form-control " name="inputBeginDate" value="{{date | date:'MM/dd/yy'}}"  />
    <span class="input-group-addon" dropdownToggle><i class="fa fa-calendar"></i></span>
    <div class="dropdown-menu" role="menu" aria-labelledby="btn-append-to-body">
        <datepicker name="test" [showWeeks]="false"  [(ngModel)]="date" ></datepicker>
    </div>
</div>
```

**Comment by Vnuuk** [comment]
@sanjaygohil you solution is great!

**Comment by aamir-munir** [comment]
[autoClose]="'outsideClick'" not working for me it close it whenever working on the datetime control.
any suggestion please?

**Comment by rrohitesh** [comment]
i am facing a issue in customizing the ng2-datepicker past dates back-ground color. As i see in the .css only current and selected dates selectors  is there. There is no .css selector for the past dates. Does anybody know how we can change the color of background for past dates.

**Comment by VirendraWankhede** [comment]
Hi,
You can disable the past date according to your date object date. It
automatically change your past date colour.
Thanking you

**Comment by rrohitesh** [comment]
I'm not getting how or which property should I use for this .If I'm trying to access date:DataModel I'm getting day, formatted, momentObj,month and year only I'm not able to find out by using this how we can get the color style for past dates

**Comment by rrohitesh** [comment]
If I'm trying to access date:DataModel I'm getting day, formatted, momentObj,month and year only I'm not able to find out by using this how we can get the color style for past dates

**Comment by msms007** [comment]
@sanjaygohil you solution is great! however, clicking on the month navigation buttons close the popup.

**Comment by tatokhorava** [comment]
Hi all. If you use closing  function on outside click and your popup keeps closing when you click month or year, thats because in outside click directive you probably making check like this this._elementRef.nativeElement.contains(targetElement) - and problem here is that that when this event is triggered that element is already removed from dom, as the view of popup changes so, you  should write something like this: const clickedInside = this._elementRef.nativeElement.contains(targetElement) || !document.contains(targetElement); - its not perfect solution but it will work :)

**Comment by JoseRCayetano** [comment]
@tatokhorava could you write a sample code?plase

**Comment by tatokhorava** [comment]
@JoseRCayetano I can copy my code, I think you will find it useful :) 
first of all I've implemented the clickOutside directive, I made some correction there, here it is:
`
import { Directive, ElementRef, Output, EventEmitter, HostListener } from '@angular/core';

@Directive({
    selector: '[clickOutside]'
})
export class ClickOutsideDirective {
    constructor(private _elementRef: ElementRef) {
    }

    @Output()
    public clickOutside = new EventEmitter();

    @HostListener('document:click', ['$event.target'])
    public onClick(targetElement:any) {
        const clickedInside = this._elementRef.nativeElement.contains(targetElement) || !document.contains(targetElement);
        if (!clickedInside) {
            this.clickOutside.emit(null);
        }
    }
}
`


then you have to use it in your html something like this:
`<div class="form-group " style="position:relative; width:150px; margin-left:20px; float:left;" (clickOutside)="returnDate.hidden = (returnDate.hidden ? returnDate.hidden : true)">
                    <div class="row" style="margin-bottom: 0;">
                        <div class="input-group col-sm-6" style="margin-bottom:0px;"><label for="dpInputReturnDate">{{ 'COMMON.DateTo' | translate:param }}</label></div>
                    </div>
                    <div class="row">
                        <div class="input-group col-sm-12" style="width: 150px;">
                            <input style="" class="form-control" name="dpInputReturnDate" placeholder="To Date" type="text" value="{{priceFilterToDate | date:'dd.MM.yyyy'}}" readonly>
                            <span class="input-group-addon glyphicon-calendar glyphicon" style="cursor:pointer; top:0;" (click)="returnDate.hidden = !returnDate.hidden"></span>
                            <div class="datePickerBoxNg2-bootstrap" [hidden]="true" #returnDate>
                                <datepicker [(ngModel)]="priceFilterToDate" [minDate]="minDate" [showWeeks]="true" name="dpreturnDate" (selectionDone)="returnDate.hidden = true"></datepicker>
                            </div>
                        </div>
                    </div>
                </div>
`

**Comment by pegaltier** [comment]
Here is plunker : https://embed.plnkr.co/2Z8ntAMAWI5vZVN08tIe/

**Comment by jacob-duong** [comment]
Hi all, it's work for me:

**templete.html**
`<div class="col-md-9" #datepickerE>`
              `<input type="text" class="form-control" (focus)="isShowDatepicker = true">`
              `<div class="popover-datepicker" *ngIf="isShowDatepicker">`
                `<datepicker formControlName="shippingDate" [minDate]="currentDate" [showWeeks]="true"
                            [dateDisabled]="dateDisabled" (selectionDone)="isShowDatepicker = false"></datepicker>`
              `</div>`


**component.ts**

`@Component({`
`  selector: 'my-form',`
`  host: {`
`     '(document:click)': 'onClick($event)',`
`  },`
`  templateUrl: './templete.html',`
`})`
`export class MaterialForm implements OnInit {`
`  @ViewChild("datepickerE") datepickerE: ElementRef;`
`  public isShowDatepicker: boolean = false;`

`onClick(event) {`
`    if (!this.datepickerE.nativeElement.contains(event.target)) {`
`      this.isShowDatepicker = false;`
`    }`
`  }`
`}`
