### ISSUE TITLE
feat(typeahead): change onChange event handler from keyup to keydown

### ISSUE THREAD

**Issue by hshn** [valor-software/ngx-bootstrap#2000]
In some languages, choosing what I typed by hitting enter key with IME.
With that languages, an active match will be selected unexpectedly when choosing it.

> IME
> https://en.wikipedia.org/wiki/Input_method

`ng-bootstrap`'s typeahead seems to be worked I expected. 

From two different implementations, I found a difference of key event `keyCode` between `keyup` and `keydown` events.

| events | enter key | enter key (choosing a conversion) |
| --- | --- | --- |
| `keyup` | keyCode: 13 | keyCode: 13 |
| `keydown` | keyCode: 13 | keyCode: 229 | 

So, `onChange($event)` event handler should be bound to host `keydown` events IMO.
What do you think about?

**Comment by tarusin** [comment]
@hshn we'll investigate it and make changes if necessary.

**Comment by daniloff200** [comment]
@hshn not sure, what issue here is? 
We're used keydown in typeahead, but, not for onChange, but onBlur.

**Comment by hshn** [comment]
@daniloff200 While filtering choices by inputting characters, an unexpected `onChange($event)` was triggered in some non-english environment, which was Japanese one.

We hit enter key when we're converting ascii chars into other chars, and we do this while filtering choices.
That was the situation the unexpected behavior was happen, but I'm not sure if it's still being happen, because I haven't used this for a long time. This issue was made more than 2 years ago.

**Comment by daniloff200** [comment]
Yeah, that's pretty old one, we're now trying to clean up all the issues, close some outdated stuff, or, try to pick something, and fix / implement

Okay, I'm gonna close it for now, in case of any issues, feel free to drop any comment here for me, or, create a new issue, and tag me
@hshn
