### ISSUE TITLE
[WARNING ->]<template [ngIf]="!isClosed">

### ISSUE THREAD

**Issue by office-work-account** [valor-software/ngx-bootstrap#2003]
> The <template> element is deprecated. Use <ng-template> instead ("
> [WARNING ->]<template [ngIf]="!isClosed">
>   <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///home/dev/angular-reboot-2/Exchange-ng-2-Today-master-build/exchange-ng2/node_modules/ngx-bootstrap/alert/alert.component.d.ts.AlertComponent.html@1:0
> Warning: Can't resolve all parameters for AuthorizationError in /home/dev/angular-reboot-2/Exchange-ng-2-Today-master-build/exchange-ng2/src/app/_services/error-authorization.ts: (?, ?). This will become an error in Angular v5.x

Small fix - and when Angular 5 on Horizon all will be happy and don't disappointed :)

**Comment by fchiumeo** [comment]
please, please search before creating new issues
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues

npm i ngx-bootstrap@next

**Comment by Martin-Luft** [comment]
For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.6.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.2" or npm install ngx-bootstrap@next
