### ISSUE TITLE
Dropdown Toggle Firing Twice When Clicked - Bootstrap 4 Alpha 6

### ISSUE THREAD

**Issue by murrihys** [valor-software/ngx-bootstrap#2012]
I'm trying to use a basic dropdown like so...

`<div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown button
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
        </div>
    </div>`

But it wasn't working.  So I googled around and added this to my index...

`<script>window.__theme = 'bs4';</script>`

Still nothing.  Thinking I wasn't including something correctly, I placed a breakpoint in the bootstrap.js at the first line in the dropdown toggle....

`Dropdown.prototype.toggle = function toggle() {
      if (this.disabled || $(this).hasClass(ClassName.DISABLED)) {`

To my surprise, I was actually hitting this breakpoint.  To my greater suprise I was hitting this breakpoint twice.  With one click, it opens the dropdown, only visibile because of hitting the breakpoint a second time, and when I continue it toggles the dropdown closed.  So in actuality it is toggling every time I click it, but it is toggling twice so fast that it opens and closes before I can see it, seeming to not work at all.

Is this a known issue or is there a fix for this?

Edit - This is only happening in my Visual Studio 2017 / Durandal solution.  This does not happen when I debug a regular text edited Durandal solution

**Comment by valorkin** [comment]
which version of ngx-bootstrap are you using?
this `.hasClass(ClassName.DISABLED)` code was removed old time ago
