### ISSUE TITLE
Dynamic tab creation using typescript

### ISSUE THREAD

**Issue by giridharkl** [valor-software/ngx-bootstrap#2013]
Hi,
I am new to Angular 2. I have started using ngx-bootstrap in my sample project. I could create the static tabs easily. I am searching for an example for adding new tabs dynamically to the existing tabset. If you could post an example that would be of great help.
Thanks
Giridhar

**Comment by valorkin** [comment]
hey, it there for a while
http://valor-software.com/ngx-bootstrap/#/tabs#dynamic

in your case maybe you need ngFor on initially empty array
or initially hidden tabs
