### ISSUE TITLE
ToolTipDirective - creating a seperate typescripts folder in outDir mentioned in tsconfig

### ISSUE THREAD

**Issue by srivch** [valor-software/ngx-bootstrap#202]
When i use ToolTipDirective in my angular 2 component and save the file in Visual Studio 2015, it creates the components.js file in a "typescripts" folder in the outDir mentioned in tsconfig. Is there a specific reason a "typescripts" folder is being created? and how to avoid the same?

**Comment by valorkin** [comment]
@srivch it seems to be a question to TS or VS
