### ISSUE TITLE
How to hide text-muted buttons 

### ISSUE THREAD

**Issue by chinra02** [valor-software/ngx-bootstrap#2020]
How to hide button that has a  span that has text-muted class,  for example Feb 30th .
On Feb moth I want see only dates from 1 to 28 and rest of all needs to be hidden.
Let me know is there a way to do this right now?

**Comment by valorkin** [comment]
sounds like css question not related to ngx-bootstrap
please provide more concrete details
which component do you use?

**Comment by chinra02** [comment]
This is related to Date Component and Lets say on Feb month we don't have 30, So i Only want to see dates from 1 to 28. But right now it shows 29 to 31 as it continues to next month when you click. So i want to hide all those buttons.

**Comment by valorkin** [comment]
Ok, now I understand you

**Comment by IlyaSurmay** [comment]
Your question is related to old version of datepicker that isn't supported now. Take a look at the [new datepicker](https://valor-software.com/ngx-bootstrap/#/datepicker#basic) and create a new issue if this is still relevant.
