### ISSUE TITLE
Error TS2307	Cannot find module 'moment'. ..node_modules\ng2-bootstrap\components\datepicker\date-formatter.ts	1	Active

### ISSUE THREAD

**Issue by otabekgb** [valor-software/ngx-bootstrap#203]
package.json:
{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.3",
    "systemjs": "0.19.20",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "zone.js": "0.5.14",
    "moment": "^2.11.2",
    "ng2-bootstrap": "1.0.3"
  },
  "devDependencies": {
    "typescript": "1.7.5"
  }
}

**Comment by project707** [comment]
This is happening to me as well and I'm not attempting to import anything related as far as I know, just TAB_DIRECTIVES.

**Comment by project707** [comment]
@otabekgb I had to:
`# tsd install moment --save`
and add this at the top of the component calling the directive I needed
`///<reference path="../../../../typings/moment/moment.d.ts" />`

**Comment by valorkin** [comment]
Please check readme and use typings, tdd is deprecated
