### ISSUE TITLE
Change padding of a tabset component

### ISSUE THREAD

**Issue by g-guth** [valor-software/ngx-bootstrap#2035]
Im using the tabset component like:

            <tabset #tabs class="tabbable-line">
                 <tab heading="Create">
                    <app-create (onSave)="save($event)"></app-create>
                 </tab>
           </tabset>

When  it renders, theres a div with a class .tab-content and a default padding, i cannot change the padding of this class in my component even if i set this on the component.css file:

           .tab-content {
             padding: 0 0 0 0 !important
           }

Is there a way to change this?

**Comment by pnocera** [comment]
try
:host /deep/ .tab-content {
         padding: 0 0 0 0 !important
       }
