### ISSUE TITLE
Mark ng2-bootstrap package as deprecated

### ISSUE THREAD

**Issue by Nolanus** [valor-software/ngx-bootstrap#2041]
How about marking the `ng2-bootstrap` npm-package as [deprecated](https://docs.npmjs.com/cli/deprecate) to avoid users not noticing the name change to `ngx-bootstrap`?

**Comment by valorkin** [comment]
it is... for a long time
but npm@5 doesn't show deprecation message :(

**Comment by valorkin** [comment]
@Nolanus just in case I tried again, but no luck
`npm view ng2-bootstrap` confirms that it is deprecated
