### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by ldtung** [valor-software/ngx-bootstrap#2050]
Hello,

I've got this warning when using ngx-bootstrap with Angular 4:
The <template> element is deprecated. Use <ng-template> instead ("
  </thead>
  <tbody>
    [WARNING ->]<template ngFor [ngForOf]="rows" let-rowz="$implicit" let-index="index">
      <tr *ngIf="!(datePicke"): ng:///e/e.html@38:4

It comes from datepicker/daypicker.component.ts which is still using <template>.
Is it possible to change from <template> to <ng-template> in order to remove the warning ?

Thank you.

**Comment by BellaMay95** [comment]
I'm getting the template element deprecated error too, usually mine comes from the Alert module or the Typeahead module. Basically, change any 'template' HTML elements to 'ng-template'.

**Comment by valorkin** [comment]
you can use `ngx-bootstrap@2` it is alfa but has no warnings
