### ISSUE TITLE
accordion styling

### ISSUE THREAD

**Issue by datruq** [valor-software/ngx-bootstrap#2051]
Hi, I'm using the accordion component of ngx-bootstrap , and I want to change the background-color, but after trying differents ways to change it, none of them worked.

I have tried
**CSS**

1) .panel-group .panel .panel-heading {
    background-color: blue;
}

2)  .panel-group>.panel>.panel-heading {
     background-color: blue;
 }

3) div.panel-heading>.card-header {    
        background-color: red !important;
}

4) accordion-group>.panel>.panel-heading {
    background-color: blue;
    color: white;
}

5) .customClass {
    .panel-heading {
        background-color: red !important;
    }
}

btw, sorry for my bad english

**Comment by valorkin** [comment]
this should help http://valor-software.com/ngx-bootstrap/#/accordion#styling

**Comment by arlamaeen** [comment]
Hi @valorkin I tried your example for the the accordion styling with the link above but still no luck. It doesn't change the css. Is there an issue?

**Comment by datruq** [comment]
Hi @arlamaeen, in my case the problem was that I changed the component css (app.component.css), and what you need to change is the global css (styles.css).

I hope this can help you.

**Comment by fventurini** [comment]
> this should help http://valor-software.com/ngx-bootstrap/#/accordion#styling

There are not example nor documentation about css o scss classes I can use-
Where can I find any?
