### ISSUE TITLE
Use ng-template isteand template

### ISSUE THREAD

**Issue by yanai101** [valor-software/ngx-bootstrap#2053]
in alret component - you have template - and the angular cli warning about it... when i try to compile to prod.

thanks

**Comment by leomayer** [comment]
not only in alert - in the datepicker component as well

**Comment by fchiumeo** [comment]
please, please search before creating new issues
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues

npm i ngx-bootstrap@next

**Comment by yanai101** [comment]
sorry :)

**Comment by joye-ramone** [comment]
Same for Typeahead component.
