### ISSUE TITLE
Angular 4.2.2 warnings on AOT compile for Alert Component

### ISSUE THREAD

**Issue by d1820** [valor-software/ngx-bootstrap#2068]
Alert component needs to be updated:  

The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): 
node_modules/ngx-bootstrap/alert/alert.component.d.ts.AlertComp
onent.html@1:0

**Comment by ctrl-brk** [comment]
Using version 1.x?
Use ngx-bootstrap@next

**Comment by d1820** [comment]
Yes on stable version 1.7.1.

**Comment by fchiumeo** [comment]
please, please search before creating new issues
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues

npm i ngx-bootstrap@next

**Comment by d1820** [comment]
Already filed
