### ISSUE TITLE
Async example is not working on version 1.7.1

### ISSUE THREAD

**Issue by michalzfania** [valor-software/ngx-bootstrap#2073]
Hi, 
I am trying to implement the "async typeahead" in my code.
But the basic example from the site is not working. 
1. Observable is only called on the first letter I type.
I am refering to this code:
![image](https://user-images.githubusercontent.com/24540398/27168320-da6cbdb8-51ad-11e7-8408-478bacdb1076.png)
2. When observable is called, the loading sign appears and the options dropdown do not appear

Versions used:
"@angular": "4.0.2",
"bootstrap": "3.3.7",
"ngx-bootstrap": "1.7.1",

**Comment by valorkin** [comment]
works on demo page, so should work for you
please provide plunkr

**Comment by rwilliams-scottlogic** [comment]
The demo page is using Angular 2.4.10, this issue is using 4.0.2.

I have the same issue with 4.2.4, using ngx-bootstrap 1.8.1.

I get ExpressionChangedAfterItHasBeenCheckedError

**Comment by valorkin** [comment]
ngx bs v1.9.0
ng v4.3.5
deployed to http://valor-software.com/ngx-bootstrap/#/typeahead#async
works fine
