### ISSUE TITLE
[daypicker]-The <template> element is deprecated.

### ISSUE THREAD

**Issue by shawnwang5** [valor-software/ngx-bootstrap#2076]
The code in daypicker.component.js,
```
<template ngFor [ngForOf]=\"rows\" let-rowz=\"$implicit\" let-index=\"index\">
```
The <template> element is deprecated. Use `<ng-template>` instead.

**Comment by ghost** [comment]
Im getting the same issue on version 1.7.1 of ngx-bootstrap

```
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
  </thead>
  <tbody>
    [WARNING ->]<template ngFor [ngForOf]="rows" let-rowz="$implicit" let-index="index">
      <tr *ngIf="!(datePicke"): ng:///DatepickerModule/DayPickerComponent.html@38:4
```

**Comment by DavidSnipp** [comment]
I also see this in alert:

`The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed"><div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): `

**Comment by fchiumeo** [comment]
please, please search before creating new issues
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues

npm i ngx-bootstrap@next

**Comment by shawnwang5** [comment]
Understand.
