### ISSUE TITLE
What's the point of all this work if you're not using the shadowdom?

### ISSUE THREAD

**Issue by dankahle** [valor-software/ngx-bootstrap#209]
This project feels like a temporary solution, i.e. the permanent solution will take the shadowdom into account (Component.encapsulation = ViewEncapsulation.Native). This project falls flat on its face in light of that as the bootstrap css is incapable of penetrating the shadowdom, especially since ::shadow and /deep/ have been deprecated by google. What's the point of all this work then? I'll be the first to admit: I don't have a clue as to what the solution will be, though angular2 material gives a glimpse, though it's a stagnant project that uses ViewEncapsulation.None of all things. I'm frustrated with the current state of angular2 theming, there doesn't seem to be any clear solution.

**Comment by valorkin** [comment]
It is to early to speak about shadow dom usage while it is not so widely supported
I would rather say, that it should be optional if you want to
More or less things will became more clear when angular2 will be released

Please close an issue if I had answered your question
If it was just a `soul scream` I get it, I was thinking how I can `force` shadow dom
and actually it is possible but it requires more complicated build process
