### ISSUE TITLE
AOT, RollUp - CANNOT_IMPORT_ITSELF

### ISSUE THREAD

**Issue by diegofal** [valor-software/ngx-bootstrap#2093]
I am getting this error: 

`{ Error: A module cannot import itself
    at error (C:\Users\Diego\Documents\npl360-web-app\node_modules\rollup\src\utils\error.js:2:14)
    at Module.error$1 [as error] (C:\Users\Diego\Documents\npl360-web-app\node_modules\rollup\src\Module.js:303:2)
    at C:\Users\Diego\Documents\npl360-web-app\node_modules\rollup\src\Bundle.js:415:15
  code: 'CANNOT_IMPORT_SELF',
  pos: 115,
  loc:
   { file: 'C:\\Users\\Diego\\Documents\\npl360-web-app\\dist\\tmp\\node_modules\\ngx-bootstrap\\dropdown\\bs-dropdown-container.component.ng
factory.js',
     line: 3,
     column: 0 },
  frame: '1: import * as i0 from \'@angular/core\';\n2: import * as i1 from \'ngx-bootstrap/dropdown/bs-dropdown-container.component\';\n3: i
mport * as i2 from \'./bs-dropdown-container.component.ngfactory\';\n   ^\n4: import * as i3 from \'ngx-bootstrap/dropdown/bs-dropdown.state\
';\n5: const styles_BsDropdownContainerComponent = [];' }`

I am using angular-seed. For some reason, the generated code is importing itself, so we end up having this error.

I am importing things in my app as suggested:

`import { BsDropdownModule } from 'ngx-bootstrap/dropdown';`

Any thoughts? 
```

**Comment by sebek64** [comment]
Duplicate of https://github.com/angular/angular/issues/17389. Downgrade to angular 4.1 should fix it, until a proper solution is made in angular 4.2 branch.

**Comment by diegofal** [comment]
Thank you @sebek64, I wasn't aware this was the cause of the problem.
Closing now
