### ISSUE TITLE
Typeahead: Is container="body" not working?

### ISSUE THREAD

**Issue by 1-0-1** [valor-software/ngx-bootstrap#2095]
I've specified container="body" for typeahead (ngx-bootstrap: 1.7.1) but it isn't attaching to body.  Instead it is attaching inline which is messing with the layout.

**Comment by renaud-dev** [comment]
Hello,
Can your try with square brackets and single quote ? 
`[container]="'body'"` is working for me on 1.6.6 and 1.7.1
Regards

**Comment by 1-0-1** [comment]
No, doesn't work for me.
Is the container param ignored if it is in a modal?

**Comment by renaud-dev** [comment]
Tried it on my project (typeahead in bsModal) and both working on 1.6.6 and 1.7.1.
Maybe you should do a plunker to get more people help. 
Good luck

**Comment by IlyaSurmay** [comment]
`container="body"` works as it should. You can check it [here](https://plnkr.co/edit/8AcdWg2VrBBdDWVztAVk?p=preview). Open webtools, type state name in field, inspect dropdown with suggestions and you'll see that `typeahead-container` is appended to the `body`
