### ISSUE TITLE
Typeahead: fires valueChanges for reactive form control on item selection

### ISSUE THREAD

**Issue by rottingcorpse** [valor-software/ngx-bootstrap#2096]
Given:
single formcontrol with typehead attached (async):

`<input [typeahead]="locations"  typeaheadAsync="true" typeaheadMinLength="3" formControlName="locationSearch" typeaheadWaitMs="500" typeaheadOptionsLimit="10" typeaheadOptionField="location">`

#
```
this.locations = this.locationSearchForm.controls['locationSearch']
    .valueChanges
    .switchMap(query => this._someService.search(query)

```

When typing a query, works just fine, someService cancels api requests, BUT, when value is selected from dropdown, valueChanges firing again with selected value, which isn't a desired outcome.

**Comment by Alex-Torres** [comment]
Having same problem.

**Comment by IlyaSurmay** [comment]
Please provide plunkr/stackblitz with reproduction if this is still relevant
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IlyaSurmay** [comment]
Closing as works as expected.

**Comment by amiram** [comment]
@rottingcorpse @Alex-Torres I tried the same thing and all requests to server are canceled. What did you mean by saying that it is fine? How did you get it to work?
