### ISSUE TITLE
Pager Component "boundaryLinks" property does nothing

### ISSUE THREAD

**Issue by DBosley** [valor-software/ngx-bootstrap#2097]
The pager component has a "boundaryLinks" property to control weather or not it shows first/last buttons. It doesn't do anything.

**Comment by DBosley** [comment]
@IlyaSurmay This is part of the "Pager" not "pagination"

not sure if there are separate labels for it

**Comment by fazelmk** [comment]
Having the same issue. Any workaround or fix for this?

**Comment by DBosley** [comment]
@fazelmk I read the source for Pager, the `boundaryLinks` property isn't hooked up.
No workarounds exist yet except to build it yourself...

**Comment by IlyaSurmay** [comment]
Pager is just two buttons - Previous and next so boundaryLinks property is redundant for it.
