### ISSUE TITLE
Publish ES5 Version of Package

### ISSUE THREAD

**Issue by kooshywoosh** [valor-software/ngx-bootstrap#2101]
In trying to use this package as part of a meteor-angular setup, but ngx-bootstrap causes the browser to throw an error ```Uncaught SyntaxError: Unexpected token import```. Meteor doesn't transpile anything in the node_modules folder down to ES5, because they expect that package would already be shipped with some es5 dist

Related issue: https://github.com/meteor/meteor-feature-requests/issues/6

**Comment by valorkin** [comment]
Hey, we already do (in the same way as angular core modules are shipped)

I am not sure how to help with it,
`main` field in package.json is pointing to es5 umd version of package https://unpkg.com/ngx-bootstrap@1.7.1/bundles/ngx-bootstrap.umd.js

`module` field to `es6` module format
so if they are consuming the wrong field, or should transpile it some how...
