### ISSUE TITLE
Tabs: Loading Component Dynamically

### ISSUE THREAD

**Issue by RoshanRoyal** [valor-software/ngx-bootstrap#2116]
Want to load a component inside tab instead of content.

**Comment by RoshanRoyal** [comment]
Can it be done like this?

<tabset>
   <tab heading="Shows Component">
      <my-loadable-component></my-loadable-component>
   </tab>
</tabset>
And loadable-component will load its content dynamically. Just theoretic answer, I didn't try it.

**Comment by IlyaSurmay** [comment]
This will work if you already know which component is going to be placed as a content
```
<tabset>
    <tab heading="Tab">
      <your-component [someInputProp]="someVariable"></your-component>
    </tab>
</tabset>
```

**Comment by RoshanRoyal** [comment]
I want to load the tab at runtime creating a dynamic component.

**Comment by bobwiller** [comment]
@RoshanRoyal, any luck finding a solution for this?

**Comment by xino1010** [comment]
@RoshanRoyal @bobwiller 

when you load dynamically components, save in array **ComponentFactory** and use in template:

![image](https://user-images.githubusercontent.com/7092367/52800770-bb6be880-307c-11e9-8a2b-261379cf094b.png)

![image](https://user-images.githubusercontent.com/7092367/52800708-a1320a80-307c-11e9-9899-43beb364e4ea.png)

![image](https://user-images.githubusercontent.com/7092367/52800750-af802680-307c-11e9-8098-b5b8e467d50c.png)

![image](https://user-images.githubusercontent.com/7092367/52800818-d5a5c680-307c-11e9-9624-fbfa80f8c7ab.png)
