### ISSUE TITLE
The <template> element is deprecated

### ISSUE THREAD

**Issue by vrudikov** [valor-software/ngx-bootstrap#2118]
```
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:.../node_modules/ngx-bootstrap/alert/alert.component.d.ts.AlertComponent.html@1:0
```

**Comment by fchiumeo** [comment]
please, please search before creating new issues
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues

npm i ngx-bootstrap@next

**Comment by vrudikov** [comment]
Sorry :( I tried, but didn't find any related words in search results. My
fault

**Comment by vrudikov** [comment]
Solved. Please close the issue
