### ISSUE TITLE
Dynamic changes of the locale for datepicker

### ISSUE THREAD

**Issue by devfomichov** [valor-software/ngx-bootstrap#2143]
Hi! I have an issue.
When I dynamic change the locale for datepciker, I can change the language only if clicked on date and calling selectionDone event.

ngOnInit() {
        this.translate.onLangChange.subscribe(event => {
            this.local_key =  event.lang.toLowerCase();
            moment,locale(this.local_key);
        });
    }

Thank you for your time.

**Comment by eyerean** [comment]
It works. The datepicker has to be closed when the language is changed.

```
import {TranslateService, LangChangeEvent} from '@ngx-translate/core';
import * as moment from moment;

constructor(private translate: TranslateService){}

ngOnInit() {
    moment.locale(this.translate.currentLang);
    
    this.translate.onLangChange.subscribe((event: LangChangeEvent) => {
      this.currentLang = event.lang;
      moment.locale(event.lang);
    });
}
```

**Comment by valorkin** [comment]
read more about localizations
available in new datepicker
starting from v1.9.2
http://valor-software.com/ngx-bootstrap/#/datepicker
