### ISSUE TITLE
Changelog for version 2.0.0-beta

### ISSUE THREAD

**Issue by vaidd4** [valor-software/ngx-bootstrap#2144]
Hi,

Is it possible to add a Changelog entry for the 2.0.0-beta.x versions ?

I was searching for it but don't see any branch or bump commit related to the beta version. Is it possible to have some infos on that ?

Thanks

**Comment by rkrisztian** [comment]
Maybe here? https://github.com/valor-software/ngx-bootstrap/blob/ngv4/CHANGELOG.md

**Comment by vaidd4** [comment]
@rkintzi Yup, he added it only few days ago. Thanks !

**Comment by ptrzyna** [comment]
I can't find the change log

**Comment by fchiumeo** [comment]
https://github.com/valor-software/ngx-bootstrap/blob/development/CHANGELOG.md
