### ISSUE TITLE
Typeahead problems when migrating from Angular 4.1.0 to 4.1.1

### ISSUE THREAD

**Issue by ubarevicius** [valor-software/ngx-bootstrap#2146]
We use ngx-bootstrap@next, thus beta.2 version. Our project was upgraded from 4.0.3 to 4.2.3 angular, and typeahead seems not to be opening suggestion list anymore. We checked that it works fine on 4.1.0 and breaks on 4.1.1 angular.

_container property in typeahead directive is undefined and I suppose it has something to do to loading container component of typeahead. I hope you can reproduce the issue from this description, let me know if you need more information.

Thanks

**Comment by BBaysinger** [comment]
Have you since tested this in Angular 4.2 or 4.3?

**Comment by ubarevicius** [comment]
4.2.3 yes (did not work), 4.3 and following 4.2 releases not yet.

**Comment by ubarevicius** [comment]
Thanks, tested - everything seem to work in beta.6
