### ISSUE TITLE
package.json typings

### ISSUE THREAD

**Issue by brian428** [valor-software/ngx-bootstrap#215]
Looks like the typings property in package.json should be removed? (Or, "ng2-bootstrap.d.ts" needs to be added?)

**Comment by valorkin** [comment]
now there 

```
 "main": "ng2-bootstrap.js",
  "typings": "ng2-bootstrap.d.ts",
```

more interesting why are you asking about?
Am I missed some info?
Can you share if so

**Comment by brian428** [comment]
Just asking because the TypeScript compiler can use the typings field in package.json to load typings for npm modules. https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages.

**Comment by valorkin** [comment]
yes, this is why I have added it 
https://github.com/valor-software/ng2-bootstrap/blob/master/package.json#L21

**Comment by brian428** [comment]
Right but the point is that you don't have an ng2-bootstrap.**d.ts** file. You have an ng2-bootstrap.ts file, but not ng2-bootstrap.d.ts. Unless you have that file somewhere else in the project that I'm not seeing?

**Comment by valorkin** [comment]
build it :)

**Comment by valorkin** [comment]
generated files are excluded from git
if it is answers your question, please close an issue :)

**Comment by brian428** [comment]
Hmm I'm not sure if we're miscommunicating. I'm not saying you **have** to build a d.ts file. I'm just telling you that the current package.json is wrong, because it says there is a d.ts file but that file doesn't exist. So you either want to add the d.ts file, or you want to remove the typings property from package.json.

**Comment by valorkin** [comment]
not sure how to explain it better
.d.ts files `are generated`
and excluded from git
but present in npm package
and if you working with ng2-bootstrap locally 
they are present after typescript build

**Comment by brian428** [comment]
Ah, I follow now. The piece I didn't realize is that you don't have this file in your repository but you do have it in the npm package. I didn't realize that you have things in the npm package that aren't in the source repo. Thanks.

**Comment by valorkin** [comment]
:D
