### ISSUE TITLE
为什么大批量的报这种错误求解？

### ISSUE THREAD

**Issue by xiaoman627** [valor-software/ngx-bootstrap#2159]
e ngx-bootstrap/tabs relative to D:/projectts/ngx-bootstrap-development/demo/sr
c/app/api-docs/index.ts., resolving symbol NgApiDocModule in D:/projectts/ngx-b
ootstrap-development/demo/src/app/api-docs/index.ts, resolving symbol NgApiDocM
odule in D:/projectts/ngx-bootstrap-development/demo/src/app/api-docs/index.ts

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/app.component.ts (
3,23): Cannot find module 'ngx-bootstrap/utils'.

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/api-docs/index.ts
(13,28): Cannot find module 'ngx-bootstrap/tabs'.

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/common/main-menu/m
ain-menu.component.ts (3,23): Cannot find module 'ngx-bootstrap/utils'.

ERROR in ./demo/src/app/app.component.ts
Module not found: Error: Can't resolve 'ngx-bootstrap/utils' in 'D:\projectts\n
gx-bootstrap-development\demo\src\app'
 @ ./demo/src/app/app.component.ts 3:0-44
 @ ./demo/src/app/app.module.ts
 @ ./demo/src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./demo/src/main.ts

ERROR in ./demo/src/app/common/main-menu/main-menu.component.ts
Module not found: Error: Can't resolve 'ngx-bootstrap/utils' in 'D:\projectts\n
gx-bootstrap-development\demo\src\app\common\main-menu'
 @ ./demo/src/app/common/main-menu/main-menu.component.ts 3:0-44
 @ ./demo/src/app/app.module.ts
 @ ./demo/src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./demo/src/main.ts

ERROR in ./demo/src/app/api-docs/index.ts
Module not found: Error: Can't resolve 'ngx-bootstrap/tabs' in 'D:\projectts\ng
x-bootstrap-development\demo\src\app\api-docs'
 @ ./demo/src/app/api-docs/index.ts 8:0-48
 @ ./demo/src/app/app.module.ts
 @ ./demo/src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./demo/src/main.ts

**Comment by xiaoman627** [comment]
W

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/common/main-menu/m
ain-menu.component.ts (3,23): Cannot find module 'ngx-bootstrap/utils'.

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/components/+accord
ion/demos/config/config.ts (2,33): Cannot find module 'ngx-bootstrap/accordion'
.

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/shared/shared.modu
le.ts (4,28): Cannot find module 'ngx-bootstrap/tabs'.

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/components/+accord
ion/demo-accordion.module.ts (5,33): Cannot find module 'ngx-bootstrap/accordio
n'.

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/components/+alerts
/demos/config/config.ts (2,29): Cannot find module 'ngx-bootstrap/alert'.

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/components/+alerts
/demo-alert.module.ts (4,29): Cannot find module 'ngx-bootstrap/alert'.

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/components/+button
s/demo-buttons.module.ts (5,31): Cannot find module 'ngx-bootstrap/buttons'.

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/components/+carous
el/demos/config/config.ts (2,32): Cannot find module 'ngx-bootstrap/carousel'.

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/components/+carous
el/demo-carousel.module.ts (5,32): Cannot find module 'ngx-bootstrap/carousel'.


ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/components/+collap
se/demo-collapse.module.ts (5,32): Cannot find module 'ngx-bootstrap/collapse'.


ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/components/+datepi
cker/demo-datepicker.module.ts (5,34): Cannot find module 'ngx-bootstrap/datepi
cker'.

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/components/+dropdo
wn/demos/config/config.ts (2,34): Cannot find module 'ngx-bootstrap/dropdown'.

ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/components/+dropdo
wn/demo-dropdown.module.ts (5,34): Cannot find module 'ngx-bootstrap/dropdown'.


ERROR in D:/projectts/ngx-bootstrap-development/demo/src/app/components/+modal/
demos/child/child.ts (2,32): Cannot find module 'ngx-bootstrap/modal'.

**Comment by IlyaSurmay** [comment]
If you're trying to run our demo locally, run `npm run test` after `npm i` to perform some preparing operations. Then run `npm run demo.serve`
