### ISSUE TITLE
Modal, add possibility to append to body

### ISSUE THREAD

**Issue by Filini** [valor-software/ngx-bootstrap#2160]
Please, add the option to append the modal to body, so that the modal div can be placed anywhere in the page.

Thanks for your good work

**Comment by marco-gagliardi** [comment]
Pretty fundamental feature, currently it's impossible to define a modal in a component that - in turn - can be dynamically included inside another modal

**Comment by valorkin** [comment]
Modal service merged and is under testing
new release will be today, latest tomorrow

**Comment by valorkin** [comment]
in v1.8 added modal service, it adds modals to body
http://valor-software.com/ngx-bootstrap/#/modals#service-component

**Comment by marco-gagliardi** [comment]
Hi, what's the intended way to pass data to a modal component opened through a service?

**Comment by IlyaSurmay** [comment]
@marco-gagliardi whel the next version of ngx-bootstrap will be released you'll be able to get an instance of component in modal and work with it as you want.
```
const modalRef = this.bsModalService.show(ModalContentComponent);
modalRef.content.title = "Your title"
```

**Comment by marco-gagliardi** [comment]
cool, thank you! 
BTW, it would be nice to be able to pass data to the component *before* the actual show method gets called on it (thus allowing it to do some initialization before the rendering moment of the modal lifecycle)

**Comment by marco-gagliardi** [comment]
Hi @IlyaSurmay is the feature to pass data to the modal (opened as a component by  ModalService) already available? Can you provide an example of how to pass complex data (say an object) to the component?

It would be nice to be able to do something like this:

```
let payload = {id: this.item.id, title: "Edit this item"};
const modalRef =  this.modalService.show(AddModalComponent, {
      class: 'modal-big modal-lg', data: payload
    });
```

**Comment by IlyaSurmay** [comment]
@marco-gagliardi PR with this feature is already created #2600
