### ISSUE TITLE
<template> deprecated -> use <ng-template>

### ISSUE THREAD

**Issue by pbuhrmann** [valor-software/ngx-bootstrap#2161]
Using angular CLI and compiling to prod "ng build --prod"

```
[WARNING ->]<template [ngIf]="!isClosed">
<div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///C:/PENRIQUE/Soflex/soflex-git.sala-situacion/node_modules/ngx-bootstrap/alert/alert.component.d.ts.AlertComponent.html
```

**Comment by fchiumeo** [comment]
please, please search before creating new issues
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues

npm i ngx-bootstrap@next
