### ISSUE TITLE
The <template> element is deprecated. Use <ng-template> instead (" [WARNING ->]<template [ngIf]="!isClosed">

### ISSUE THREAD

**Issue by MikhaelGerbet** [valor-software/ngx-bootstrap#2162]
Hi, i have this warning generated by this file

     ngx-bootstrap/alert/alert.component.d.ts.AlertComponent.html

You can update this by 
    
    <ng-template>

please ?

Else, i submit one PR if you wamt ?

Thx by advance ;)

**Comment by fchiumeo** [comment]
please, please search before creating new issues
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues

npm i ngx-bootstrap@next

**Comment by MikhaelGerbet** [comment]
Oh... i 'm not the first ! Sorry :)

**Comment by MikhaelGerbet** [comment]
solved with 
     `npm i ngx-bootstrap@next`
