### ISSUE TITLE
ng2-bootstrap@1.1.11 requires a peer of @angular/common@~2.0.1 but none was installed

### ISSUE THREAD

**Issue by rogueRabbit** [valor-software/ngx-bootstrap#2165]
When I wanted to fix the NPM dependency pack, there was an error. Most of my current packages are dependent on the angular version of 2.1.1. How can you solve this problem? Please help me
![image](https://user-images.githubusercontent.com/14859823/27777037-f5676306-5fe1-11e7-821e-378af1de7c07.png)

**Comment by valorkin** [comment]
1. ng2-bootstrap is renamed to ngx-bootstrap
2. you really should update to at least ng v2.3+
3. it is just a peer dependency warnings, it could work just fine
