### ISSUE TITLE
bug(datepicker): min date `sticks` to current date

### ISSUE THREAD

**Issue by valorkin** [valor-software/ngx-bootstrap#217]
Chrome 46
Steps to reproduce:
1. go to bs4 version http://valor-software.com/ng2-bootstrap/index-bs4.html#datepicker
2. press `min date` button
3. press any `date` on picker

Actual result:
- selected date becomes min date
  Expected:
- should not affect min date

Could be related to #163

**Comment by edinfazlic** [comment]
Created fix: https://github.com/valor-software/ng2-bootstrap/pull/293
