### ISSUE TITLE
Question : Typeahead optionsListTemplate with table view

### ISSUE THREAD

**Issue by codertube** [valor-software/ngx-bootstrap#2170]
I want to show results of the type ahead search in **tabular format** and **_not_as list drop down_**. i followed following - (https://github.com/valor-software/ngx-bootstrap/issues/1557) 

I'll will be searching against 3 coulmn values in table and that part is taken care using filters. I'm not sure about displaying search results in tables and how events like 'click on a row' in table etc can be handled using typeahead plugin.Also i see i would need to do lot of styling for displaying data in proper tabular format, will typeahead plugin's css work smoothly with custom css which i'll be having for tables?

I have below template - 

```
<ng-template #customItemTemplate>
    <div class="col-lg-12 sb-ir-popover-table-div sb-ir-popover-table-layout">
          <table class="table-hover table-striped">
			<thead>
				<th class="sb-ir-popover-table-th">name</th>
				<th class="sb-ir-popover-table-th">region</th>
			</thead>
              <tr>
			<td>{{state.name}}</td> // I get error here - ERROR TypeError: Cannot read property 'name' of undefined(…)
			<td>{{state.region}}</td>
	     </tr>
          </table>
    </div>
  </ng-template>
```
How do i get hold of 'state.name' / 'region' or search result 'state' objects in custom template?
my input is like this - 

```
<input [(ngModel)]="asyncSelected"
         [typeahead]="dataSource"
         (typeaheadLoading)="changeTypeaheadLoading($event)"
         (typeaheadNoResults)="TypeaheadNoResults($event)"
         (typeaheadOnSelect)="typeaheadOnSelect($event)"
         typeaheadOptionsLimit="15"
         [optionsListTemplate]="customItemTemplate"
         placeholder="Locations loaded with timeout"
         class="form-control">

```
Earlier I was using following - 

Input - 
`typeaheadOptionField="combined"`
It's this 'combined' which was getting displayed as options and now I want to change that options to tabular form with original columns.

Component - 
```
public statesComplex: any[] = [
    {id: 1, name: 'Alabama', region: 'South'}, {id: 2, name: 'Alaska', region: 'West'}, {
      id: 3,
      name: 'Arizona',
      region: 'West'
    },
    {id: 4, name: 'Arkansas', region: 'South'}];

public constructor() {
    this.dataSource = Observable
      .create((observer: any) => {
        // Runs on every search
        observer.next(this.asyncSelected);
      })
      .mergeMap((token: string) => this.getStatesAsObservable(token));
  }

public getStatesAsObservable(token: string): Observable<any> {
return Observable.of(
      this.statesComplex.filter((state: any) => {
        state['combined'] = state.name+'--->'+state.region;
         return state.combined.toLowerCase().indexOf(token.toLowerCase()) > -1;
      })
    );
}

```
This worked fine, but i wanted tabular display without ' --->' .
In above mentioned link, I see following method calls - 
```
[class.active]="isActive(match)"
(mouseenter)="selectActive(match)"
(click)="selectMatch(match, $event)"
```

wanted to check if I would need to override all method calls (including above ones) with custom implementation to support events for tabular display of data.

**Comment by codertube** [comment]
i  missed for loop in custom template and after adding that I'm able to get all state values in tabular format. But its not filtering as and when i type. What attribute/methods should I use so that i can get filtered results. As posted earlier I've a filter in constructor which was working fine as long as results was in dropdown view. 

I've following now in custom template - 

```
              <tr *ngFor='let state of statesComplex'>//missed this for loop earlier
			<td>{{state.name}}</td>
			<td>{{state.region}}</td>
	     </tr>
```

I see following attribute being used in reference link - 

`typeahead="item as item.title + ' (' + item.name + ')' for item in data | filter:{title:$viewValue}"`

will this help for filtering? Can you please explain what's  $viewValue and how i can use my already existing filter logic here. Also I've doubts if I need to mandatorily use below lines in custom template so that it displays filtered results there.

```
<template ngFor let-match let-i="index" [ngForOf]="matches">
<template [ngTemplateOutlet]="itemTemplate || bsItemTemplate"
                                                          [ngOutletContext]="{item:match.item, index:i, match:match, query:query}" style="color: black;">
```
does match here has filtered results?

**Comment by mahpah** [comment]
@codertube how can you use click, mouseenter, or class.active on each option item?

**Comment by hocine15** [comment]
Any good solution for this question or any link to see how to display the ngx-bootstrap typeahead in a tabular way ?
