### ISSUE TITLE
<template> element is deprecated

### ISSUE THREAD

**Issue by jcebidanes** [valor-software/ngx-bootstrap#2177]
If run command

 "ng build --prod --bh /project/"

This is WARNING is show

```
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///C:/Users/jcebidanes/project/node_modules/ngx-bootstrap/alert/alert.component.d.ts.AlHash: c06588a906b9dad178d4
```
"@ angular/core": "^4.0.1",
"ngx-bootstrap": "^1.6.6",
"@ angular/cli": "1.1.3",

**Comment by fchiumeo** [comment]
please, please search before creating new issues
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues

npm i ngx-bootstrap@next
