### ISSUE TITLE
Submenu feature in BsDropdown

### ISSUE THREAD

**Issue by prassanaj** [valor-software/ngx-bootstrap#2178]
Any plans to support submenu's in BsDropdown.  I use it for Nav panel in my project and looking to implement submenus.  Please let me know if theres a better way to do it while I use ngx-bootstrap.

**Comment by valorkin** [comment]
http://valor-software.com/ngx-bootstrap/#/dropdowns#nested

but it is better to make submenus with css only
google it for your bootstrap version
