### ISSUE TITLE
Typeahead stops working when error in Observable sequence

### ISSUE THREAD

**Issue by thib92** [valor-software/ngx-bootstrap#2180]
When using the Typeahead directive with an Observable as a source, if the Observable throws an error (which mine does when receiving no result from the API), the Typeahead will stop looking for results with further typing.

Current solution : catching the error and returning an empty array.

I don't know if this is a bug on your end or if this is just supposed to be as it is right now.

**Comment by valorkin** [comment]
typeahead is just a UI component, it should not handle errors
returning an empty array on API resp error is a right approach
your application should handle error in some way
