### ISSUE TITLE
Alert Module has deprecated template tags

### ISSUE THREAD

**Issue by venkateshwarv** [valor-software/ngx-bootstrap#2186]
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->] template [ngIf]="!isClosed">
  div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///C:/Phabricator/v3GA/node_modules/ngx-bootstrap/alert/alert.component.d.ts.AlertComponent.html@1:0

**Comment by fchiumeo** [comment]
please, please search before creating new issues
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues

npm i ngx-bootstrap@next
