### ISSUE TITLE
modal backdrop repeats and never removed

### ISSUE THREAD

**Issue by lazaro3487** [valor-software/ngx-bootstrap#2189]
Hello everyone, I have a  modal component used in 2 pages, when navigate from page 1 to page 2 and a model is opened on page2, the backdrop component is repeted like this:

```
<bs-modal-backdrop class="modal-backdrop in"></bs-modal-backdrop>
<bs-modal-backdrop class="modal-backdrop in"></bs-modal-backdrop>
```

After hide the modal, one backdrop is removed but the other remains?

Is there any way to fix this issue?

Regards.

**Comment by valorkin** [comment]
fixed in v1.8 (will be released later today)
at least doesn't reproduce anymore

**Comment by valorkin** [comment]
published

**Comment by lazaro3487** [comment]
thanks for your response, the backdrops are removed in 1.8 release, however the backdrop html tag is repeated for each page navigation. Is there any way to fix that?

**Comment by closca** [comment]
+1

**Comment by valorkin** [comment]
Repeated html tag exists for directives, but not for modal service
