### ISSUE TITLE
hide() on button triggers form submit

### ISSUE THREAD

**Issue by shooby83** [valor-software/ngx-bootstrap#2194]
if you place a modal inside a form and you close it with a close button, which is firing the hide() event, the form gets submittet.

temporary fix: $event.preventDefault() on the close button

**Comment by IlyaSurmay** [comment]
if you use `<button type="button"></button>`, it shouldn't submit the form. Default type of button is submit, so you have to specify it manually

**Comment by IlyaSurmay** [comment]
No updates here, closing.
