### ISSUE TITLE
Template element is deprecated, use ng-template instead.

### ISSUE THREAD

**Issue by simmondsdt** [valor-software/ngx-bootstrap#2195]
I am using angular 4 and have only imported ngx-bootstrap datepicker into my app module, please update this.
core.es5.js:3054 Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
  </thead>
  <tbody>
    [WARNING ->]<template ngFor [ngForOf]="rows" let-rowz="$implicit" let-index="index">
      <tr *ngIf="!(datePicke"): ng:///DatepickerModule/DayPickerComponent.html@38:4

**Comment by fchiumeo** [comment]
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues

npm i ngx-bootstrap@next

**Comment by DanielKucal** [comment]
Doesn't make sense, why isn't it included in main branch and npm package?

**Comment by DanielKucal** [comment]
@fchiumeo @Martin-Wegner It doesn't make sense for me, why isn't it included in main branch and npm package?
