### ISSUE TITLE
Multiselect feature for dropdown

### ISSUE THREAD

**Issue by madhav5589** [valor-software/ngx-bootstrap#2207]
Hello, is there multiselect feature available for the dropdowns ? If not, can you add as a feature ? I think it will be very handy.

Thanks.

**Comment by valorkin** [comment]
dropdowns !== select
what I mean, dropdowns is just a tool to render popup lists
not more, all depends on how you handle dropdown item click

**Comment by valorkin** [comment]
BTW you can always drop more questions in slack
