### ISSUE TITLE
bug(demo): dropdown button auto closes

### ISSUE THREAD

**Issue by agrahamlincoln** [valor-software/ngx-bootstrap#221]
Noticed this on the [docs page](http://valor-software.com/ng2-bootstrap/index-bs4.html#dropdowns) and I did not have the time to test this on my own. (Is it possible to use ng2-bootstrap in plunker?) But when you open the Button Dropdown, it opens and immediately closes.

This occurs on both BS3 & 4 in the docs. The dropdown does work, but only if you use the "Toggle Button Dropdown" button.

**Comment by valorkin** [comment]
Yeap, for some reason it started to auto close,
but strange things that `Action` dropdown works fine
