### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by nellyigiebor** [valor-software/ngx-bootstrap#2210]
Hi,

How do I load component into modal body?

<div bsModal #childModal="bs-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title pull-left">Child modal</h4>
        <button type="button" class="close pull-right" aria-label="Close" (click)="hideChildModal()">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <app-childComponent></app-childComponent>  // I'm getting errors...
      </div>
    </div>
  </div>
</div>

Thanks in advance.

**Comment by valorkin** [comment]
@nellyigiebor later today, we should release v1.8 with modal service
demos in docs should help

**Comment by valorkin** [comment]
modal service adds modal to body
http://valor-software.com/ngx-bootstrap/#/modals#service-component
