### ISSUE TITLE
Dropdown doesn't work inside components mounted using router-outlet

### ISSUE THREAD

**Issue by kvanbere** [valor-software/ngx-bootstrap#2212]
Say you have some component with
```
<router-outlet></router-outlet>
```

Any components mounted around or above this component in the hierarchy work fine, but components that get mounted within `router-outlet` don't i.e. they don't add the classes necessary for dropdowns to appear and disappear. No error is generated.

The components within register `(click)` events and such fine, but `ngx-bootstrap` isn't hooking them to process the directives properly or something? Sorry don't really know how it works under the hood.

With ng2 and bootstrap 4. Other dropdowns on page work fine.

**Comment by kvanbere** [comment]
OK, if you came here via Google, this is the solution.

All of the documentation says that you should add i.e. `BsDropdownModule` to the `imports:` section of your `module.ts` at the top level of your project, *but it does not mention* that you must add it for every `@NgModule` that you intend to use the `ngx-bootstrap` controls with [1]. This fixed it for me.

So, for example, if your router is broken out into a separate `@NgModule`, you need to add all the bootstrap things there too in order to get anything inside to receive the `ngx-bootstrap` hooks.

**This issue should be for modifying the documentation so this is less confusing ...**

[1] https://stackoverflow.com/a/39599976

**Comment by kvanbere** [comment]
@IlyaSurmay perhaps it would be better now to modify the label to documentation, or if you don't think the documentation needs updating, just close ..

**Comment by valorkin** [comment]
@kvanberendonck this is how `@NgModule` works, most probably I will add some generic docs
like: how to do shared modules and so on, but this issue is mostly because of lack of docs about `NgModules`

Thanks for pointing
