### ISSUE TITLE
Dynamic Tab removal

### ISSUE THREAD

**Issue by giridharkl** [valor-software/ngx-bootstrap#2213]
Hello,
I using Tabs Component and creating dynamic tabs from an outer component. Inside the tab I have a cancel button which is used for closing the tab. I could remove the contents from the tab. However the Tab(x) remains in the UI. Does this require some way to refresh the UI after a tab is removed? Please let me know.

Thanks
Giridhar

**Comment by IlyaSurmay** [comment]
You're saying that you're creating dynamic tabs from an outer component. When you remove tab content you also have to remove that tab object in your outer component if I get you correctly.

**Comment by giridharkl** [comment]
Hi,
Thanks for your inputs. I could use an event emitter from child to parent and in parent i wrote the following code to remove tab content and tab. May be useful for someone!
`onTabCancel(e) {
    debugger;
    var t = this.globals.taskTabs.findIndex(x => x.id == e);
    this.globals.taskTabs.splice(t, 1);
    this.staticTabs.tabs.splice(t+1, 1);
    if(this.staticTabs.tabs.length == 1) {
      //Home tab
      this.staticTabs.tabs[0].active = true;
    }
    else {
      this.staticTabs.tabs[t].active = true;
    }
  }
`
I don't know if there is a better way to achieve this.
