### ISSUE TITLE
Carousel not working with angular-cli in development mode

### ISSUE THREAD

**Issue by SoftwareAndOutsourcing** [valor-software/ngx-bootstrap#2222]
This is continuation of #1649 which was closed as it was not reproducible. Now I include a sample repo and a bit more detailed instructions so it's easier to do.

Steps to reproduce:

- Install angular/cli 1.2.0
- Create a new project with `ng new`.
- Install bootstrap as described in https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/include-bootstrap.md.
- Install ngx-bootstrap 1.7.1. with npm.
- Setup the module and copy and paste the 'Dynamic Slides' example from http://valor-software.com/ng2-bootstrap/#/carousel#dynamic into the app.

When running the app in development mode (`ng serve` without `--prod`) I get an `Expression has changed after it was checked. Previous value: 'undefined'. Current value: '0'.` exception in the browser console.

A sample repo following the steps above is at https://github.com/SoftwareAndOutsourcing/ngx-bootstrap-cli-carousel-demo.

**Comment by IlyaSurmay** [comment]
Add default value to activeSlideIndex, this should fix the error.
`public activeSlideIndex: number = 0;`
We'll update the demo soon.

**Comment by bgpedersen** [comment]
I fought with this for some time. Using the activeSlideIndex removes the error, but then the slide was stuck at position 0. To fix this, I put *ngIf on the slide, forcing it to re-render, and setting my slideshow to null when updating, and inserting setTimeout with 0, and only after this, setting the updated slide in here.

HTML
```
<carousel [interval]="system.carouselInMilliseconds"
  *ngIf="system"
  [(activeSlide)]="activeSlideIndex">
  <slide *ngFor="let item of system.News; let index = index"
    class="animated"
    [ngClass]="{'slideInRight': index === activeSlideIndex, 'slideOutLeft': index !== activeSlideIndex}"
    [routerLink]="['/news', item.id]">

    <div class="cover-img"
      [ngStyle]="{'background-image': 'url(' + item.image.path + ')'}">
    </div>

    <div class="cta-txt font-poppins">
      <h2 class="truncate">{{item.Headings.text}}</h2>
      <span>{{system.translations.news.subtitle}}</span>
    </div>
  </slide>
</carousel>
```

COMPONENT
```
systemEventListener() {
    // on system updated emitted, update this components system data
    this.systemSub = this.dataService.systemUpdated.subscribe(response => {
      this.logger.log('SharedCarouselComponent: systemEventListener response: ', response);
      // system must reset to avoid changeError in slider and system set in timeout to work
      this.system = null;
      this.activeSlideIndex = 0;

      setTimeout(() => {
        this.system = response;
        this.logger.log('SharedCarouselComponent: systemEventListener this.system: ', this.system);
      }, 0);

    });
  }
```
