### ISSUE TITLE
(docs) Link to github source code throws 404

### ISSUE THREAD

**Issue by aravindfz** [valor-software/ngx-bootstrap#2224]
Go to this [URL](http://valor-software.com/ngx-bootstrap/#/modals) Click on the link icon.

It throws 404.

**Comment by valorkin** [comment]
thanks

**Comment by aravindfz** [comment]
@valorkin Can I fix this and raise a PR if so to which branch should I raise PR master or development?

**Comment by valorkin** [comment]
Thanks for proposal ;)
fixed and deployed
