### ISSUE TITLE
Modals. List of actual issues

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#2239]
Modal issues:
Were planed to be fixed in new release:
~~https://github.com/valor-software/ngx-bootstrap/issues/2210~~ - How to load component into modal body - example was added to demo
~~https://github.com/valor-software/ngx-bootstrap/issues/2160~~ - Modal, add possibility to append to body - Illya will answer, how to do it. Now we have this posibility
https://github.com/valor-software/ngx-bootstrap/issues/1819 - Focus coming out of Modal - not implemented for now. Probably will be implemented later
~~https://github.com/valor-software/ngx-bootstrap/issues/2189~~ - modal backdrop repeats and never removed - need clarify (was planned to be fixed in this release)

z-index:
~~https://github.com/valor-software/ngx-bootstrap/issues/890~~ - Trigger Modal using Routing
~~https://github.com/valor-software/ngx-bootstrap/issues/1462~~ - Modal appearing backdrop non editable
~~https://github.com/valor-software/ngx-bootstrap/issues/758~~ - Modal within flexbox structure

Need clarifying:
~~https://github.com/valor-software/ngx-bootstrap/issues/1145~~ - Angular Universal : this.document.body.removeChild is not a function
~~https://github.com/valor-software/ngx-bootstrap/issues/2164~~ - Viewchild lgModal is undefined
~~https://github.com/valor-software/ngx-bootstrap/issues/2137~~ - Modal keeps body class `modal-open` on after closing, causing scrollbars to disappear
~~https://github.com/valor-software/ngx-bootstrap/issues/2090~~ - Is it possible to have different colored backdrops

Planes for future implementations:
https://github.com/valor-software/ngx-bootstrap/issues/731 - request(modals): add an options to append modals to element 
https://github.com/valor-software/ngx-bootstrap/issues/1597 - Document the focus config option for modals
~~https://github.com/valor-software/ngx-bootstrap/issues/1664~~ - Nested modals backdrop behind shows up behind the back-most modal

**Comment by pavan6014** [comment]
Hi Team @YevheniiaMazur @IlyaSurmay @v1ktoryy @daniloff200 
Good to hear solution for #1819, its been pending from long years.
