### ISSUE TITLE
Don't update ngModel or value of input after selection

### ISSUE THREAD

**Issue by pthieu** [valor-software/ngx-bootstrap#2243]
I have a use-case where suggestions have a `type` associated with each item and a different method is invoked based on this type. For a specific `type === 'tag'`, I want to invoke a `search` function but keep the string in the `input` element unchanged.

Currently when you select one of the items in the dropdown, it will replace the string in the input element without `value` of the item you selected. How do I prevent this or override this?

**Comment by valorkin** [comment]
1. Which component do you use?
2. You code sample please
3. Dropdown doesn't update ngModel

**Comment by pthieu** [comment]
@valorkin:
Oh sorry, forgot to give all the proper information.

1. Typeahead component
2. Just the `static array` example on the doc page will do: http://valor-software.com/ngx-bootstrap/#/typeahead 

HTML:
```
<pre class="card card-block card-header">Model: {{selected | json}}</pre>
<input [(ngModel)]="selected"
       [typeahead]="states"
       class="form-control">
```

JS:
```
import { Component } from '@angular/core';
import 'rxjs/add/observable/of';
 
@Component({
  selector: 'demo-typeahead-static',
  templateUrl: './static.html'
})
export class DemoTypeaheadStaticComponent {
  public selected:string;
  public states:string[] = ['Alabama', 'Alaska', 'Arizona', 'Arkansas',
    'California', 'Colorado',
    'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
    'Illinois', 'Indiana', 'Iowa',
    'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
    'Michigan', 'Minnesota',
    'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
    'New Jersey', 'New Mexico',
    'New York', 'North Dakota', 'North Carolina', 'Ohio', 'Oklahoma', 'Oregon',
    'Pennsylvania', 'Rhode Island',
    'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
    'Virginia', 'Washington',
    'West Virginia', 'Wisconsin', 'Wyoming'];
}
```
After selecting any item, it will change the string in the input element.

**Comment by valorkin** [comment]
aha, ok
this 2 links could give general understanding:
https://angular.io/guide/template-syntax#inside-ngmodel
https://angular.io/api/forms/NgModel

idea is:
unwrap `[(ngModel)]` to `(ngModelChange)` and `[ngModel]`,
most probably you will have to use string property in the component or map value
and custom ngModelChange handler (component method)
like `setUppercaseName` in first link

**Comment by valorkin** [comment]
Ping me here on in slack, did it helped?

**Comment by pthieu** [comment]
@valorkin: sorry, haven't tried yet, went off to another feature for the time being; will let you know when I switch back.

**Comment by 1-0-1** [comment]
I'm looking at the same issue.  
We don't want to unwrap ngModel since that works as needed for the typeahead functionality.  The TypeaheadDirective changeModel is updating the value on selectMatch.  It is the selection of the item that we need to de-couple from the model.   I want to keep the value the user entered into the search box but then handle what to do with the selected item myself through typeaheadOnSelect.

**Comment by 1-0-1** [comment]
@valorkin - Can you please reopen this request.

**Comment by valorkin** [comment]
@1-0-1 so how I can help you?

**Comment by 1-0-1** [comment]
The current behavior as defined by TypeaheadDirective changeModel replaces the entry value with the selected item.  I need what the user selects to remain in the entry box and not be replaced by the selected value.  That allows them to return to the entry box and select a different item from the filtered list.

**Comment by MaxiPigna** [comment]
I have the same problem, did you come up with a solution?

**Comment by rafal-marciniak** [comment]
I also have the same issue. How about adding an `event.PreventDefault()` method to the `onSelect` parameter?
