### ISSUE TITLE
Circular Dependency Detected in ngx-bootstrap/modal

### ISSUE THREAD

**Issue by rsrinivasan15** [valor-software/ngx-bootstrap#2244]
The latest version of `ngx-bootstrap` (1.8.0) throws the following error when building with webpack

```ERROR in Circular dependency detected:
node_modules/ngx-bootstrap/modal/bs-modal.service.js -> node_modules/ngx-bootstrap/modal/modal-container.component.js -> node_modules/ngx-bootstrap/modal/bs-modal.service.js

ERROR in Circular dependency detected:
node_modules/ngx-bootstrap/modal/modal-container.component.js -> node_modules/ngx-bootstrap/modal/bs-modal.service.js -> node_modules/ngx-bootstrap/modal/modal-container.component.js```

**Comment by valorkin** [comment]
Webpack version?
Cuz it should resolve circular deps without issues

**Comment by valorkin** [comment]
just tested with angular-cli
works fine
please provide more details
as a side note, webpack v1 is not supported

closing until more details provided,
cuz can not reproduce

**Comment by rsrinivasan15** [comment]
I am using webpack 3. I just noticed that I am using the "circular-dependency-plugin" which is catching that circular dependency (if I take that out, webpack doesn't complain).

On a separate note, from a design point of view, should the circular dependency be revisited and fixed in the future?

**Comment by valorkin** [comment]
Could be, but then I will need injection token and funny line in providers section
