### ISSUE TITLE
Arrow keys navigation not working in dropdown

### ISSUE THREAD

**Issue by himajasuman** [valor-software/ngx-bootstrap#2245]
Unable to navigate in dropdown with arrow keys.

https://plnkr.co/edit/fsXozcjVXpmEdQloy2wI?p=preview

@valorkin I saw few issues similar to this were closed saying that Accessibility is on road map. https://github.com/valor-software/ngx-bootstrap/issues/1966

It would be great if you could provide some information on  road map or some workaround to make it work for now.

**Comment by valorkin** [comment]
Previous implementation was too hacky, had to remove it
And was binded to dropdown items css class

**Comment by himajasuman** [comment]
@valorkin

**Comment by innov-richa76** [comment]
Hi @himajasuman @valorkin - I am also facing the same issue now. Can you please let me know the exact solution for this?
