### ISSUE TITLE
How to use tooltip in ngFor ?

### ISSUE THREAD

**Issue by lishichao1002** [valor-software/ngx-bootstrap#2247]
I have a scene that using tooltip in ngFor.  The sample is as follows.

```xml
<table>
    <tr *ngFor="let row of rows">
        <td>
              <span tooltip=" <img src='{{ row.url }}' />  ">{{row.content}}</span>
        </td>
    </tr>
</table>
```

In order to parse html with tooltip. I have to using `<ng-template></ng-template>` to wrap the html.
So the code like follows.

```xml
<table>
    <tr *ngFor="let row of rows">
        <td>
              <ng-template #popTemplate><img src='{{ row.url }}' /></ng-template>
              <span [tooltip]="popTemplate">{{row.content}}</span>
        </td>
    </tr>
</table>
```

In this way, I got the effect i wanted. But I don't think this is a good way. because there will be many much `<ng-template #popTemplate><img src='{{ row.url }}' /></ng-template>`  in ngFor.

So, my question is how do i deal with tooltip in ngFor ?

![image](https://user-images.githubusercontent.com/13584162/28452478-83e739ac-6e25-11e7-8fbe-cdb7e6649689.png)
![image](https://user-images.githubusercontent.com/13584162/28452492-949d7d10-6e25-11e7-97b9-53190a4548ea.png)

**Comment by valorkin** [comment]
ng template for each is almost unavoidable,
so you did everything correctly

one note
`<ng-template #popTemplate><img src='{{ row.url }}' /></ng-template>`
will be better to be as
`<ng-template #popTemplate><img [src]='row.url' /></ng-template>`

**Comment by lishichao1002** [comment]
thank you very much

**Comment by anup-github** [comment]
Hi, Can we manually trigger this tooltip?
I have tried https://valor-software.com/ngx-bootstrap/#/tooltip#triggers-manual,
but dont know how this will work for `ngFor`. any idea?
