### ISSUE TITLE
Typehead: getValueFromObject() crash in case of null values

### ISSUE THREAD

**Issue by ramael** [valor-software/ngx-bootstrap#2248]
File typeahead-utils.ts, function getValueFromObject(), last row:
   return object.toString()
crash if object is null.
Please add a check for null values, for instance:
   if (!object) return "";

**Comment by valorkin** [comment]
Nice reason for small PR

**Comment by ramael** [comment]
Ok, opened a PR

**Comment by valorkin** [comment]
https://github.com/valor-software/ngx-bootstrap/pull/2249

**Comment by IlyaSurmay** [comment]
Fixed in #2249 
Thanks for PR!
