### ISSUE TITLE
Custom class is not getting applied

### ISSUE THREAD

**Issue by hardikpthv** [valor-software/ngx-bootstrap#2253]
In tabs while setting custom css class is not applying to the tab component.  `<tab heading="Static title" customClass="customClass">Static content</tab>`
http://valor-software.com/ngx-bootstrap/#/tabs#styling

**Comment by valorkin** [comment]
@hardikpthv it is applying, but seems we did not add something special for it
```
<div class="tab-content">
  <tab customclass="customClass" heading="Static title" class="tab-pane">Static content</tab>
  <!--template bindings={}--><tab class="tab-pane">
    Dynamic content 1
  </tab><tab class="tab-pane active">
    Dynamic content 2
  </tab>
</div>
```

**Comment by hardikpthv** [comment]
@valorkin as of now solved it by setting `encapsulation: ViewEncapsulation.Native`.
