### ISSUE TITLE
Tooltip: Error when opening tooltip using isOpen property

### ISSUE THREAD

**Issue by Agamnentzar** [valor-software/ngx-bootstrap#2257]
Opening tooltip using `[isOpen]` property is causing following error

Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'tooltip in tooltip-top top undefined'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?

Also "undefined" class is being added to tooltip if `containerClass` is not specified

**Comment by jcairney** [comment]
@IlyaSurmay  Question about this: Is isOpen meant to be used to open the tooltip as described above?  The block comment for the property suggests it is read only, which defies convention for @Input properties in Angular.  I haven't been able to confirm it is ReadOnly by looking at the minified source.
