### ISSUE TITLE
datepicker's selectionDone doesn't work @1.8.0

### ISSUE THREAD

**Issue by eyerean** [valor-software/ngx-bootstrap#2260]
It is working on `ngx-bootstrap 1.7.1` , updated to `1.8.0` and `selectionDone` stopped working.

**Comment by MoxFulder** [comment]
+1

**Comment by Guutong** [comment]
+1

**Comment by MuJianning** [comment]
[datepicker-inner.component.ts] @CodingDK committed with @valorkin on 18 Jul.
