### ISSUE TITLE
Can't bind to 'ngModel' since it isn't a known property of 'timepicker'

### ISSUE THREAD

**Issue by ebakunin** [valor-software/ngx-bootstrap#2263]
I upgraded from v1.7.1 to 1.8.0 and got the following error:

Can't bind to 'ngModel' since it isn't a known property of 'timepicker'

My original code worked fine. Did the import process or something else change during the timepicker rewrite?

**Comment by IlyaSurmay** [comment]
Have you imported `FormsModule` or `ReactiveFormsModule`to your NgModule?

**Comment by valorkin** [comment]
@ebakunin timepicker was upgraded to work with reactive and regular forms
so you need to import FormsModule or ReactiveFormsModule
on your own
