### ISSUE TITLE
Modal service: return promise with corresponding event

### ISSUE THREAD

**Issue by davidloiret** [valor-software/ngx-bootstrap#2268]
Using the modal service it's not possible to know the 4 events `OnShow, OnShown, OnHide, OnHidden`
To solve this issue the `modalService.show()` should return a promise with the corresponding event.

**Comment by IlyaSurmay** [comment]
Modal service events are in progress right now #2272

**Comment by Disane87** [comment]
Ans Updates on this? As I see there is no chance to get the events in v3.2 and v3.3.

This seems to be merged but not released?
