### ISSUE TITLE
No provider for TimepickerActions

### ISSUE THREAD

**Issue by artdias90** [valor-software/ngx-bootstrap#2270]
Since 1.8.0 I have a problem with the new timepicker. 
`inline template:57:16 caused by: No provider for TimepickerActions! at ViewWrappedError.ZoneAwareError`
Is it somehow dependent on Redux now? If so, can you update the documentation http://valor-software.com/ngx-bootstrap/#/timepicker ?

**Comment by IlyaSurmay** [comment]
Could you provide more precise info about how to reproduce this one? I generated new cli project with ngx-bootstrap@1.8.0 and timepicker works just fine.

**Comment by valorkin** [comment]
in 99% this issue means, that you forgot to call `.forRoot()` of timepicker module

drop me a note if this didn't helped
