### ISSUE TITLE
angular-seed example is out dated

### ISSUE THREAD

**Issue by mavogel** [valor-software/ngx-bootstrap#2271]
Thanks for the nice lib and setup examples. I guess the doc for the angular-seed is outdated.

## setup
- Similar to #2259
- using [angular-seed@facd075](https://github.com/mgechev/angular-seed/commit/facd07577735ba61b50c2e7443db18415175aa04)

## steps
I had to install `jquery` to prevent `bootstrap.js requires jquery.js` error
```bash
npm install --save ngx-bootstrap bootstrap jquery
```

resulted in
```json
"bootstrap": "^3.3.7",
"jquery": "^3.2.1",
"ngx-bootstrap": "^1.8.0",
```

Add additional dep:
```ts
// Add `NPM` third-party libraries to be injected/bundled.
this.NPM_DEPENDENCIES = [
  ...this.NPM_DEPENDENCIES,
  // {src: 'lodash/lodash.min.js', inject: 'libs'},
  { src: 'jquery/dist/jquery.min.js', inject: 'libs' },
  { src: 'bootstrap/dist/js/bootstrap.min.js', inject: 'libs' },
  { src: 'bootstrap/dist/css/bootstrap.min.css', inject: true }, // inject into css section
  { src: 'bootstrap/dist/css/bootstrap-theme.min.css', inject: true }, // inject into css section
  { src: 'bootstrap/dist/css/bootstrap-theme.min.css.map', inject: true }, // inject into css section
];
```

**home.module.ts**
```ts
import { AlertModule } from 'ngx-bootstrap/alert';

@NgModule({
  imports: [HomeRoutingModule, SharedModule, AlertModule.forRoot()],
  declarations: [HomeComponent],
  exports: [HomeComponent],
  providers: [NameListService]
})
```

**Error**
```
GET 
http://localhost:5555/node_modules/ngx-bootstrap/bundles/ngx-bootstrap.umd.min.js/alert 
404 (Not Found)
```

Can you tell me how to fix that issued or maybe with other version of ngx-bootstrap doesnt' have this error? Thanks in advance

**Comment by valorkin** [comment]
I am specially mentioning in docs
that `import { AlertModule } from 'ngx-bootstrap/alert';` will not work with system.js
```
// RECOMMENDED (doesn't work with system.js)
import { AlertModule } from 'ngx-bootstrap/alert';
// or
import { AlertModule } from 'ngx-bootstrap'
```
better to use angular-cli

**Comment by mavogel** [comment]
Alright @valorkin  so you're [complete install guide](https://github.com/valor-software/ngx-bootstrap/blob/development/docs/getting-started/angular-seed.md) for the angular is not correct any more right? The seed does not recommend to use angular-cli and it uses system.js
Coming back to my question
> Can you tell me how to fix that issued or maybe with other version of ngx-bootstrap doesnt' have this error?

So is the answer that ngx-bootstrap does not work with the seed any more? 
So would you mind updating the docs or remove them. I'd really like to use your lib but outdated docs are frustrating.

**Comment by valorkin** [comment]
As I said, update your module import to
import { AlertModule } from 'ngx-bootstrap'
