### ISSUE TITLE
daypicker.component deprecation warning.

### ISSUE THREAD

**Issue by pickaneym** [valor-software/ngx-bootstrap#2277]
Daypicker.component deprecation warning.

![image](https://user-images.githubusercontent.com/29157221/28578013-4b50c730-710d-11e7-856c-11511103e647.png)

**Comment by non4me** [comment]
https://github.com/valor-software/ngx-bootstrap/pull/2075

**Comment by valorkin** [comment]
use @next version of ngx-bootstrap
