### ISSUE TITLE
request : background-color progress bar

### ISSUE THREAD

**Issue by johaven** [valor-software/ngx-bootstrap#2278]
It would be cool to have the possibility to customize the background color :)

**Comment by IlyaSurmay** [comment]
You can easily customize colors by adding a css class to progressbar
https://plnkr.co/edit/olzoNp6A78lhSCbOZnWn?p=info

**Comment by shekhar94** [comment]
I found following description for 'value' attribute for progressbar.
current value of progress bar. Could be a number or array of objects like {"value":15,"type":"info","label":"15 %"}
But while using it I passed the value as follows

<progressbar max="100" [value]="[{'value':15,'type':'success','label':'15 %'}, {'value':15,'type':'danger','label':'15 %'}]" [striped]="true" [animate]="true"><i></i></progressbar>

but it is not giving me a progressbar with success and danger together. Am I doing something wrong please guide?
