### ISSUE TITLE
Typeahead option to pop results above input

### ISSUE THREAD

**Issue by greggbjensen** [valor-software/ngx-bootstrap#2281]
I am using the typeahead at the bottom of a page, and I would like the option to have results pop above the input, instead of down as they go off the page.  Is this available?

**Comment by lucianojs** [comment]
I needed something similar, but not being able to enter new values. I ended up using another component. Ng2-select

Your feature its same Input Datalist from HTML5. https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist
