### ISSUE TITLE
template is deprecated in Angular 4

### ISSUE THREAD

**Issue by marcelgood** [valor-software/ngx-bootstrap#2288]
The template selector is deprecated in Angular 4 and was replaced with ng-template. Currently getting warnings on the console for every use of template. I was gonna submit a PR replacing template with ng-template everywhere, but then noticed that the library is still being built against Angular 2.x, so the tests fail. Are there plans to bring it up to Angular 4.x, so we can fix this?

**Comment by fchiumeo** [comment]
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues

npm i ngx-bootstrap@next

**Comment by marcelgood** [comment]
Thanks. Sorry, I searched open issues and didn't find anything. My bad.
