### ISSUE TITLE
whether typeahead-tooltip feature is available ?

### ISSUE THREAD

**Issue by geetikasharma26** [valor-software/ngx-bootstrap#2289]
Is there a way to show dynamic tooltips for typeahead feature?

**Comment by geetikasharma26** [comment]
To describe my requirement further, I dynamically want to have tool tips on the drop down suggestions for typeahead. I couldn't find any way to do that for the dropdown items displayed as a part of typeahead suggestions. Is there any way to do that?

**Comment by IlyaSurmay** [comment]
check this out #2323 
https://plnkr.co/edit/Ltzzp28ssFPPOwlRN7WT?p=preview
