### ISSUE TITLE
chore(build): add systemjs bundles

### ISSUE THREAD

**Issue by ludohenin** [valor-software/ngx-bootstrap#23]
Would be very nice to have a `dist` folder with a bundled file build with systemjs (register).

**Comment by valorkin** [comment]
@ludohenin unfortunately I am not really familiar with bundling with system.js
but it works with system.js anyway
https://github.com/pkozlowski-opensource/ng2-play/pull/34

**Comment by ludohenin** [comment]
I'll try to propose you something.
Btw I also got it working here [https://github.com/ludohenin/angular2-seed-ng2-bootstrap](https://github.com/ludohenin/angular2-seed-ng2-bootstrap). The things is that it's not as straight forward as adding a script tag in the html document.

**Comment by valorkin** [comment]
In this question I agree with redux guys:

> If you don’t yet use npm or a modern module bundler, and would rather prefer a single-file UMD build that makes Redux available as a global object, you can grab a pre-built version from cdnjs. We don’t recommend this approach for any serious application, as most of the libraries complementary to Redux are only available on npm.

https://www.npmjs.com/package/redux

but I was planning to add bundled version later, not prio, If you have an idea how I can do I will gladly apply it to all modules https://github.com/valor-software/ng2-plans :)

**Comment by ludohenin** [comment]
Yeah agree with you.
interesting (long) discussion [https://github.com/angular/angular/issues/4278](https://github.com/angular/angular/issues/4278) about this topic.

**Comment by valorkin** [comment]
I suppose soon we will see some common approach to building\bundling modules
so we can use it

**Comment by ludohenin** [comment]
Making a quick custom build (with system at least) isn't that hard. I think it's fine like this.
If I had to distribute bundles, I would do cjs only, one with full deps (ng2 + deps), and one with just the lib. Can be convenient for quick trial, prototype. The example integration with angular2-seed is basically the lib alone.

**Comment by sirwolfgang** [comment]
This would be very nice in at least some form of docs. The official ng2 starting tutorial uses systemjs.

**Comment by valorkin** [comment]
published new version with system.js bundles https://www.npmjs.com/package/ng2-bootstrap#quick-start
