### ISSUE TITLE
tabs not working in modals opened as component from service

### ISSUE THREAD

**Issue by marco-gagliardi** [valor-software/ngx-bootstrap#2312]
It seems like TabsModule is not working when the tabset is included in a modal that is opened as a component from BsModalService (The tabs are correctly rendered, but clicking on another tab different from the opened one has no effect.)

**Comment by IlyaSurmay** [comment]
Fix is already in dev branch, next version will be released today.

**Comment by rajeshdlabz** [comment]
for my current project iam building a component which involves a tabset to be put inside a modal, and i need to programmatically switch between tabs,

i added the tabset to modal and it gets rendered perfect, but when i access the component  
@ViewChild("configTabset")
  configTabset: TabsetComponent;

it gives me undefined, 

**Template**
```
<ng-template #configModal>
  <div class="modal-header">
    Test
  </div>
  <div class="modal-body">
    <tabset #configTabset>
      <tab heading="Tab 1">
            Tab 1
      </tab>
      <tab heading="Tab 2">
            Tab 2
      </tab>
      <tab heading="Tab 3">
            Tab 3
      </tab>
    </tabset>
  </div>
 <div class="modal-footer">
    <button type="button" class="btn btn-success pull-right" (click)="next()"> Add Component</button>
  </div>
</ng-template>
```

**Component** 
```
export class FDComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild("configTabset")
    configTabset: TabsetComponent;
  next(){
   this.configTabset.tabs[2].active = true;
  }
}
```

**im very new to angular, and i know you have marked it as closed, but im stuck with this issue for quite a while now, please help**

**thanks in advance**
