### ISSUE TITLE
Can't disable radio buttons

### ISSUE THREAD

**Issue by rdicroce** [valor-software/ngx-bootstrap#2314]
The [disabled] attribute is ignored for radio buttons.

There was an issue about this previously, and a fix was applied, but only for checkbox buttons.

**Comment by IlyaSurmay** [comment]
Can't reproduce this. https://plnkr.co/edit/0RaljKJen6R06v0fz3tl?p=preview
Looks like the newest version of ngx-bootstrap works just fine with `[disabled]` attribute

**Comment by rdicroce** [comment]
Just played with your example. disabled works, [disabled] does not. It has to be [attr.disabled]. Would be nice if the documentation mentioned that.

**Comment by IlyaSurmay** [comment]
in case of `[disabled]` Angular thinks that this is component's input. So you should use ` [attr.disabled]="true"` or `disabled`
