### ISSUE TITLE
Modal Component OnHidden Subscribe

### ISSUE THREAD

**Issue by rodrigospinola** [valor-software/ngx-bootstrap#2318]
> this.modalService.onHidden.subscribe( 
  result => {
	console.log("check")
	this.load()
  }, error => console.log(error));

To Hidden Component i use  "this.bsModalRef.hide();" in component Child.
First this return "check".
Second this return "check","check".
Third  this return "check","check","check".
.....

Have other Method to close correctly?

**Comment by rodrigospinola** [comment]
close

**Comment by wkjesus** [comment]
have you fix the problem ? @rodrigospinola
