### ISSUE TITLE
Selected Dropdown not visible

### ISSUE THREAD

**Issue by arunattupurath** [valor-software/ngx-bootstrap#2319]
Used the Simple DropDown first example in my Angular4 Application.

When I select an option in the dropdown , it does not stay selected .

Checked the Demo Page. The demo page http://valor-software.com/ngx-bootstrap/#/dropdowns 
cannot be used to check this behaviour. Since you are using on clicking on anchor tag the page goes to homepage.
App.module.ts has the BsDropdownModule and BsDropdownModule.forRoot() in imports. Not sure what is wrong.

**Comment by IlyaSurmay** [comment]
Dropdowns aren't supposed to keep selected item.What you're talking about is a [Select component](https://github.com/valor-software/ng2-select) and it's slightly different from dropdowns.
