### ISSUE TITLE
dropdown autoClose doesn't work when using isOpen

### ISSUE THREAD

**Issue by raghu-romp** [valor-software/ngx-bootstrap#2321]
Hi Team,

Thanks for your contributions for this great component library. 

I understand that when using isOpen to show/hide drop-down, I am in-charge of maintaining the state. But I was expecting that autoClose=true should set the value of isOpen to false when clicking outside the dropdown.

I am not sure if this should be tagged as bug or enhancement. But please advise if this should be raised as an enhancement.

Regards.

**Comment by slubowsky** [comment]
See https://github.com/valor-software/ngx-bootstrap/issues/1933
Waiting for this to be fixed as well. Hope it gets fixed soon

**Comment by IlyaSurmay** [comment]
Works on latest version (2.0.0-beta.8), so closing.

**Comment by udit003** [comment]
I does not work on version 2.15.12 , please fix this.
