### ISSUE TITLE
npm install --save VS --save-dev

### ISSUE THREAD

**Issue by hassanasad** [valor-software/ngx-bootstrap#2322]
Hi, I recently installed a package [Swiper wrapper](https://github.com/zefoy/ngx-swiper-wrapper) which recommends installing package as a **devDependency**. I inquired from the author of the package why not simple **dependency** and he says:

> Usually you compile your app into one or multiple js files. Of course there can be situation when its needed as normal dependency, but when it comes to Angular apps I think the normal case is that this is only needed as dev dependency.

So i was wondering if this applies for ngx-bootstrap too?

**Comment by IlyaSurmay** [comment]
In both cases you'll have ngx-bootstrap in your bundle so technically it doesn't matter (if you're developing a front-end project, not a npm library). But according to npm's semantics, **dependency** is more preferable.
Great article on this topic https://www.linkedin.com/pulse/npm-dependencies-vs-devdependencies-daniel-tonon
