### ISSUE TITLE
feature to display dynamic tooltip for typeahead results (Typeahead module) 

### ISSUE THREAD

**Issue by geetikasharma26** [valor-software/ngx-bootstrap#2323]

**Comment by IlyaSurmay** [comment]
I think that you can achieve the effect you want without any lib changes. Just use [custom item template](http://valor-software.com/ngx-bootstrap/#/typeahead#item-template) and there you go.
```
<template #customItemTemplate let-model="item">
  <h5 tooltip="Tooltip text">{{model}}</h5>
</template>
```
Just don't forget to include TooltipModule to your NgModule.
Plunkr https://plnkr.co/edit/Ltzzp28ssFPPOwlRN7WT?p=preview
