### ISSUE TITLE
Accordion Styling

### ISSUE THREAD

**Issue by noush225** [valor-software/ngx-bootstrap#2324]
Hi!
I want to style the accordion component as explained [here](http://valor-software.com/ngx-bootstrap/#/accordion#styling), but it does not work at all.

Any help on this?
Thanks (Sorry for my bad english)

**Comment by IlyaSurmay** [comment]
Hi. What exactly doesn't work? I think the demo is quite straightforward:

1. Add your css class to `accordion-group`
2. Write css rules for this class like this 
```
.panel.customClass {
  background-color: #5bc0de;
  color: #fff;
}
```
If this doesn't help you, create a simple repo or plunkr so we'll be able to help you

**Comment by noush225** [comment]
I did but the CSS doesn't apply. this is my component.html code:
[here](http://pasted.co/c6cd218c)

my component.ts:
[here](http://pasted.co/2fe9d48d)

and my css : 
[here](http://pasted.co/68f3448f)

**Comment by IlyaSurmay** [comment]
to deal with angular's view encapsulation, you have to write your styles with `:host >>>` if you're using an external stylesheet for a component.
```
:host >>> .card.customClass,.card.customClass .card-header,.panel.customClass {
background-color: #5bc0de;
color: #fff;}
:host >>> .panel.customClass .panel-body {
background-color: #337aa7;
}
```
Or you can add your styles to global stylesheet or add `encapsulation: ViewEncapsulation.None` to your component definition.
We'll probably update the demo to make this moment clear

**Comment by noush225** [comment]
Thank you!
