### ISSUE TITLE
Issue with angular 4, 

### ISSUE THREAD

**Issue by jinnabaalu** [valor-software/ngx-bootstrap#2326]
These are the versions i am using, created application with angular-cli 1.2.6

"angular/animations": "4.3.2",
    "angular/common": "4.0.0",
    "angular/compiler": "4.0.0",
    "angular/core": "4.0.0",
    "angular/forms": "4.0.0",
    "angular/http": "4.0.0",
    "angular/platform-browser": "4.0.0",
    "angular/platform-browser-dynamic": "4.0.0",
    "angular/platform-server": "4.3.2",
    "angular/router": "4.0.0",
    `"bootstrap":` "4.0.0-alpha.6",
    "core-js": "2.4.1",
    "font-awesome": "4.7.0",
    "ngx-bootstrap": "^1.8.1",
    "rxjs": "5.4.1",
    "zone.js": "0.8.14"

getting the template deprecated error when i am building the application

![image](https://user-images.githubusercontent.com/11784253/28786437-d4f71db2-7636-11e7-9c3a-0f7c9a8cde32.png)

**Comment by fchiumeo** [comment]
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues

npm i ngx-bootstrap@next

**Comment by jinnabaalu** [comment]
Still i am facing another issue. with accordian
node_modules/ngx-bootstrap/accordion/accordion.config.js:1
(function (exports, require, module, __filename, __dirname) { import { Injectable } from '@angular/core';

updated the package to npm i ngx-bootstrap@next --save, but facing an issue.

**Comment by jinnabaalu** [comment]
i have tried using the other module, same error with other module. How to import them? is there any format change to import them?

**Comment by fchiumeo** [comment]
what is you configuration in tsconfig ?

**Comment by jinnabaalu** [comment]
my tsconfig.json

{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  },
  "angularCompilerOptions": {
      "genDir": "./dist/ngfactory",
      "entryModule": "./src/app/app.module#AppModule"
  }
}

**Comment by fchiumeo** [comment]
ngx-bootstrap compile ok, the problem is in src/server.ts

**Comment by Martin-Luft** [comment]
For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.X.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.2" or npm install ngx-bootstrap@next
