### ISSUE TITLE
Angular 4 Modal

### ISSUE THREAD

**Issue by llmdev** [valor-software/ngx-bootstrap#2327]
`has no exported member 'BsModalService'.`

Erro Angular 4

**Comment by micahng** [comment]
I have the same issue. And also,

has no exported member 'BsModalRef'.

**Comment by micahng** [comment]
I had the same issue and I just installed the module again.

npm install ngx-bootstrap --save

**Comment by IlyaSurmay** [comment]
Maybe you have `package-lock.json` where ngx-bootstrap is locked to some old version?

**Comment by edl7878** [comment]
same issue here and no lock file in project

**Comment by edl7878** [comment]
well,re-check it again.
package-lock.json is not in project folder.
for me on windows it's in user's document folder,and there are several package-lock.json files other places
delete them an re install @next version 
and solved the problem.

**Comment by ghost** [comment]
I'm having the same problem. Already on version `2.0.0-beta.2` and deleted my `package-lock.json` file, still no luck.

**Comment by IlyaSurmay** [comment]
@next version wasn't updated, so it doesn't have BsModalService. We're working on it and probably @next with BsModalService included will be released by the end of this week.

**Comment by ghost** [comment]
@IlyaSurmay Thank you very much!
