### ISSUE TITLE
Warning during build. Please avoid <templete> and use ng-templete  or ng-container

### ISSUE THREAD

**Issue by hari-scancafe** [valor-software/ngx-bootstrap#2332]
![ngx-bootstrap_warning](https://user-images.githubusercontent.com/22441767/28826116-7692ebba-76e6-11e7-9535-7d8f7fe9bcf8.png)

**Comment by Martin-Luft** [comment]
Please search for same issues before opening a new one...

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.X.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.2" or npm install ngx-bootstrap@next
