### ISSUE TITLE
When including ng2-bootstrap.min.js I get a "System is not defined" error

### ISSUE THREAD

**Issue by jkyoutsey** [valor-software/ngx-bootstrap#234]
Edit: If I install via npm do I need to include the script or is it all in the module?  I may just be misinterpreting the instructions.

`<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ng2-bootstrap/1.0.5/ng2-bootstrap.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>`

Console output (Chrome latest):
`Uncaught ReferenceError: System is not defined(anonymous function) @ accordion.component.js:1`

I'm using the AngularClass webpack starter component from here (3.0):
https://github.com/angularclass/angular2-webpack-starter

**Comment by mikekidder** [comment]
@jkyoutsey From looking at the angular2-webpack-starter, you dont include the scripts.  This is handled by the **webpack** builders when you have done below into your project

```
 npm install ng2-bootstrap --save
 # Install typings from NPM. Ambient typings will not help
 typings install moment --save
```

The cdn script giving the error is using **systemjs**.

**Comment by jkyoutsey** [comment]
Thanks!
