### ISSUE TITLE
Not able to make the first accordion group open when there are multiple accordion groups

### ISSUE THREAD

**Issue by brihaspati** [valor-software/ngx-bootstrap#2349]
I have an accordion on which ngFor is applied and I need the first accordiongroup to be open by default on load of the accordion. In order to accomplish that, I need to make the isOpen property of that accordion group as TRUE. However how do I make it? I tried using ViewChildren, but if I try to access it inside AfterViewInit, its undefined. Need help here

**Comment by valorkin** [comment]
Check source code of this example
pay attention to isOpen property
```js
<accordion>
  <accordion-group heading="Static Header, initially expanded"
                   [isOpen]="status.isFirstOpen"
```
http://valor-software.com/ngx-bootstrap/#/accordion#disabled
