### ISSUE TITLE
Adding ids to tabs in HTML

### ISSUE THREAD

**Issue by GabrielSiq** [valor-software/ngx-bootstrap#2353]
Hi,

I'm working on a solution that mixes ngx-bootstrap tabs and the unrelated [ngx-contextmenu](https://github.com/isaacplmann/ngx-contextmenu) component. I've implemented a 'Close All' button, that calls a function that clears all tabs. This is done through functions called when clicking elements in the interface so for the Close All we have:
```
<tabset #dynamicTabs (contextmenu)="onContextMenu($event, null)">
  <tab *ngFor="let tab of tabs"
       [heading]="tab.title"
       [active]="tab.active"
       (select)="tab.active = true"
       (deselect)="tab.active = false"
       [disabled]="tab.disabled"
       [removable]="tab.removable"
       (removed)="removeTabHandler(tab)"
       [id]="tab.id">
  </tab>
</tabset>

<context-menu #tabMenu>
  <ng-template contextMenuItem (execute)="closeAllTabs()">
    Close All
  </ng-template>
  <ng-template contextMenuItem (execute)="closeAllButCurrent($event)">
    Close All But Current
  </ng-template>
</context-menu>
```

```
closeAllTabs() {
    this.tabs = [];
  }

```
Now, for the Close All Tabs but Current, I was thinking about the following approach:
```
closeAllTabsButCurrent($event : MouseEvent) {
    // get id of the tab under the mouse from the MouseEvent
    // create new list with the element from this.tabs that matches said id, marked as active and assign the new one element list to this.tabs
  }
```
Unfortunately I haven't been able to assign an id that reflects in the HTML of any of the tab elements. Is there a way to add this id? Do you have any suggestions on how to implement that in a more effective way? 
Thanks!

**Comment by IlyaSurmay** [comment]
You can set an id by using this approach `[attr.id]="tab.id"`
But this will only add ids to tab elements, `<li>` elements will remain the same.
About your actual task, you can close all tabs except active in this way
```
closeAllTabsButCurrent() {
   const activeTabIndex = this.tabs.map((i) => {return i.active}).indexOf(true);
   this.tabs = [this.tabs[activeTabIndex]];
}
```

**Comment by GabrielSiq** [comment]
Thanks! 

So, that example I solved using a similar approach:
`this.tabs = [this.tabs.find(item => item.active === true)];`

But now I'm not trying to close all but the active, the function name might have been a little misleading, I wanna close all but the one that's below the cursor when I click. If I don't have an id in the HTML to identify the tab from the MouseEvent, I'm not sure how to implement that.
