### ISSUE TITLE
How to invoke popover from div?

### ISSUE THREAD

**Issue by KellenHe** [valor-software/ngx-bootstrap#2355]
`<div type="button" class="ti-info-alt" popover="Hello world" style="cursor: pointer; position: absolute; right: 3px; top: 3px; color: red;"></div>`
like this, it can not works.

`<button type="button" class="ti-info-alt" popover="Hello world" style="cursor: pointer; position: absolute; right: 3px; top: 3px; color: red;"></button>`
it is ok

how to invoke  popover from div ?

thanks

**Comment by IlyaSurmay** [comment]
Couldn't reproduce this, works ok here - https://plnkr.co/edit/8cH50keR9QwpxjVVLTwF?p=preview

**Comment by IlyaSurmay** [comment]
No updates, closing.

**Comment by KlausSchade** [comment]
the plunkr you provided works fine 
but: when you use the attribute triggers="focus" only the button works and not the div

**Comment by KellenHe** [comment]
thanks, i see.
