### ISSUE TITLE
Child Modal backdrop to cover parent modal

### ISSUE THREAD

**Issue by hassanasad** [valor-software/ngx-bootstrap#2362]
I am trying to figure out a way to cover the parent modal with backdrop produced by Child Modal. Is it possible somehow?

Perhaps this issue is also related #2331

**Comment by valorkin** [comment]
hey, nope, we were struggling to avoid such behaviour :)

**Comment by valorkin** [comment]
what you can do is add backdrop inside of parent modal on your own :)
