### ISSUE TITLE
Reopen:  Class 'MiniStore<T>' incorrectly extends base class 'Observable<T>

### ISSUE THREAD

**Issue by FabienDehopre** [valor-software/ngx-bootstrap#2366]
I create a new issue about ` Class 'MiniStore<T>' incorrectly extends base class 'Observable<T>` directly related to #2261 which was closed a bit early (in my opinion).
I still have the exact same issue when compiling.
And @valorkin, yes I already updated my rxjs and ngx-bootstrap to the latest version (5.4.2 and 1.8.1 respectively).
As a reminder, the error message is:
```
ERROR in /mnt/c/Users/f.dehopre/devs/Portal/node_modules/ngx-bootstrap/mini-ngrx/store.class.d.ts (8,22): Class 'MiniStore<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => MiniStore<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'MiniStore<R>' is not assignable to type 'Observable<R>'.
        Types of property 'lift' are incompatible.
          Type '<R>(operator: Operator<R, R>) => MiniStore<R>' is not assignable to type '<R>(operator: Operator<R, R>) => Observable<R>'.
            Type 'MiniStore<R>' is not assignable to type 'Observable<R>'.
              Types of property 'lift' are incompatible.
                Type '<R>(operator: Operator<R, R>) => MiniStore<R>' is not assignable to type '<R>(operator: Operator<R, R>) => Observable<R>'.
                  Type 'MiniStore<R>' is not assignable to type 'Observable<R>'.
                    Types of property 'select' are incompatible.
                      Type '<R>(pathOrMapFn: (state: R) => R) => Observable<R>' is not assignable to type 'SelectSignature<R>'.
                        Types of parameters 'pathOrMapFn' and 'paths' are incompatible.
                          Type 'string' is not assignable to type '(state: R) => any'.

ERROR in /mnt/c/Users/f.dehopre/devs/Portal/node_modules/ngx-bootstrap/mini-ngrx/store.class.d.ts (12,5): Class 'Observable<T>' defines instance member property 'select', but extended class 'MiniStore<T>' defines it as instance member function.
```

Someone can help me on this, please?

**Comment by Sparker73** [comment]
I'm running into the same issue.

Two main things happened in my environment, just to give some info. First, I have upgraded my Angular CLI to latest and Angular 2 packages to Angular 4. At first it didn't work but, with patience, I was going error by error and solving one by one and most of them were of two classes, typescript legacy programming syntax and also many many packages were old, so basically correcting syntax and updating old packages as well as removing incompatible ones and finding new ones to replace the functionality was enough.

Ok until there. Everything was working fine with my ng2-bootstrap package and even AOT compilation worked just great.

Today I had the NO-SO-GREAT idea of uninstalling ng2-bootstrap and installed the new ngx-bootstrap. Everywhere in the web says the old package was renamed to ngx-bootstrap but I don't think that the only change was a "package rename". I'm just offering my bad experience as a reference to this issue.

If there is something I can do to sole it it would be great, I don't know if going back to the old repo (ng2-bootstrap) would work again but I'll try. Thanks for reading.

**Comment by Morpheous7** [comment]
Did you ever solve this issue? It's been a year. I just encountered the very same thing and I am looking for answers. Thanks.

**Comment by constfun** [comment]
Ditto. Not sure why the issue was closed, again.
