### ISSUE TITLE
When I used the jasmine test in angular2, the component used ngx-bootstrap, and then there was a mistake like this. Please help me to see it

### ISSUE THREAD

**Issue by rogueRabbit** [valor-software/ngx-bootstrap#2374]
![image](https://user-images.githubusercontent.com/14859823/29053159-feba4058-7c20-11e7-8d67-0ba2872d9893.png)
![image](https://user-images.githubusercontent.com/14859823/29053179-161663da-7c21-11e7-8a43-63db338b7b23.png)
![image](https://user-images.githubusercontent.com/14859823/29053187-1d967d34-7c21-11e7-9bf5-c4139450418d.png)
![image](https://user-images.githubusercontent.com/14859823/29053225-4c11687c-7c21-11e7-947c-23a86cc4f4cf.png)

**Comment by IlyaSurmay** [comment]
Couldn't reproduce this on the latest version (2.0.0-rc.0). The issue will be reopened if you provide a reproduction.
