### ISSUE TITLE
The <template> element is deprecated.

### ISSUE THREAD

**Issue by alexandresn** [valor-software/ngx-bootstrap#2378]
The following warning is happenen:

```
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///AlertModule/AlertComponent.html@1:0
```

**Comment by Martin-Luft** [comment]
Please search for same issues before opening a new one...

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.X.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.4" or npm install ngx-bootstrap@next
