### ISSUE TITLE
fix(collapse): IE 10: Can't bind to 'hidden' since it isn't a known native property

### ISSUE THREAD

**Issue by AndreyKotofotoff** [valor-software/ngx-bootstrap#238]
Hello!
IE 10!

Template parse errors:
Can't bind to 'hidden' since it isn't a known native property ("true">
            <span [ngTransclude]="tabz.headingRef">{{tabz.heading}}</span>
            <span [ERROR ->][hidden]="!tabz.removable">
              <span (click)="$event.preventDefault(); removeTab(tabz);" c"): Tabset

Help, please.

**Comment by valorkin** [comment]
will this help? https://github.com/valor-software/ng2-bootstrap/issues/193

**Comment by edinfazlic** [comment]
At the moment, yes #193 can be used, but as a very short solution.

But as it is something in ng2-bootstrap I suggest that we redo it.

**Comment by valorkin** [comment]
agreed, *ngIf?

**Comment by AndreyKotofotoff** [comment]
*ngIf

**Comment by matthewvalimaki** [comment]
With `Chrome 49` and `Angular 2.0.0-beta.9` I'm getting `Can't bind to 'collapse' since it isn't a known native property` with the example from http://valor-software.com/ng2-bootstrap/#collapse.

Same problem or something else?

**Comment by valorkin** [comment]
Last time when I have seen such issue, is when I forgot to add directive to component's declaration

**Comment by valorkin** [comment]
just to keep in mind 
https://www.tjvantoll.com/2013/01/09/html5-hidden-attribute-browser-support/
