### ISSUE TITLE
Changing styles in the Carousel - anyone able to help out?

### ISSUE THREAD

**Issue by MicaelaLV** [valor-software/ngx-bootstrap#2381]
Hi there!

I'm trying to use the carousel to render some images but I can't manage to change the control's styles. Like the color/background & stuff like that. CSS doesn't work and I didn't find any styles in the node-modules to change. Can Someone help me out please?

Thank you so much!

**Comment by IlyaSurmay** [comment]
You can style carousel via css on a component or app level. 
Here https://plnkr.co/edit/T8bggAQ0oBxhnEVXAP7C?p=preview you'll find component level styling, global styling isn't much different.

**Comment by chris93007** [comment]
Anyway to change it without host?
