### ISSUE TITLE
typeahead subscription

### ISSUE THREAD

**Issue by danielGz** [valor-software/ngx-bootstrap#2382]
I just stumbled upon some question when thinking about any possible memory leak in my application:
Since the typeahead `Observable ` is provided we never get a chance to unsubscribe from it as the subscription happens inside the directive code, should we need to worry about this? 

I implemented my own solution and so far it seems that no negative secondary effects were caused:
```
 protected asyncActions(): void {
    this.typeaheadSubscription=this.keyUpEventEmitter
      .debounceTime(this.typeaheadWaitMs)
      .mergeMap(() => this.typeahead)
      .subscribe(
        (matches: any[]) => {
          this.finalizeAsyncCall(matches);
        },
        (err: any) => {
          console.error(err);
        }
      );
  }
```

and inside `ngOnDestroy` : 
```
public ngOnDestroy(): any {
    this._typeahead.dispose();
    this.typeaheadSubscription.unsubscribe();    
  }
```

**Comment by valorkin** [comment]
or like here https://github.com/valor-software/ngx-bootstrap/blob/31cba418a13674917e0fcfba2419c7f27c660ba1/src/dropdown/bs-dropdown-toggle.directive.ts#L50-L62

anyway, you are right and this is
a good reason for small PR :)

**Comment by danielGz** [comment]
Thanks!
