### ISSUE TITLE
Cannot match any routes. URL Segment Error when clicking on button to open Popup. Error showing on browser console tab.

### ISSUE THREAD

**Issue by megrajkiran09** [valor-software/ngx-bootstrap#2384]
1. File Name: app-routing.module.ts
import { NgModule } from '@angular/core';
import { RouterModule, Router} from '@angular/router';
import { FirstAppComponent } from './first-app/first-app.component';
import { LoginComponent } from './login/login.component';

const APP_ROUTES = [
    { path:'', redirectTo:'first-app', pathMatch:'full' },
    { path:'first-app', component:FirstAppComponent },
    {path:'login-app', component: LoginComponent}
    ];

@NgModule({
 imports:[RouterModule.forRoot(APP_ROUTES, {useHash: true})],
 exports:[RouterModule],
 providers:[]
})
export class AppRoutingModule { }
---------------------------------------------------------
2. File Name: app.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { BsModalService } from 'ngx-bootstrap/modal';
import { AppComponent } from './app.component';
import { FirstAppComponent } from './first-app/first-app.component';
import { LoginComponent } from './login/login.component';
import {ModalModule,BsModalRef } from 'ngx-bootstrap';
import { Routes, RouterModule } from '@angular/router';
import { AppRoutingModule } from './app.routing.module';

@NgModule({
  declarations: [ AppComponent, FirstAppComponent, LoginComponent ],
  imports: [ BrowserModule,ModalModule.forRoot(),AppRoutingModule ],
  providers: [BsModalService],
  bootstrap: [AppComponent],
  entryComponents: [FirstAppComponent,LoginComponent]
})
export class AppModule { }
---------------------------------------------------------
3. File Name: first-app.component.html
<h1>First App Component</h1>
<button routerLink="login-app" type="button" (click)="showPoppup()">Open Popup</button>
---------------------------------------------------------
4. File Name: first-app.component.ts
  constructor(private modalService: BsModalService) { }
  showPoppup() {
    this.bsModalRef = this.modalService.show(LoginComponent);
    this.bsModalRef.content.title = 'Login Form';
  }
---------------------------------------------------------
5. File Name: login.component.html
<div class="modal-header">
      <h4 class="modal-title pull-left">{{title}}</h4>
      <button type="button" class="close pull-right" aria-label="Close" (click)="bsModalRef.hide()">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <form>
        Username: <input type="text" />
        Password: <input type="text"/>
        <button type="submit">Submit</button>
      </form>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" (click)="bsModalRef.hide()">Close</button>
    </div>
---------------------------------------------------------
6. app.component.html
<router-outlet></router-outlet>

Error:
![reroute-error](https://user-images.githubusercontent.com/30847444/29099503-7247c686-7c6b-11e7-9829-e3099664b8c5.PNG)

**Comment by megrajkiran09** [comment]
can you please explain me  where I am doing wrong. 
I don't want to append the login-app path to parent url. my requirement is to have URL as localhost:4200/#/first-app.  it should show first app component, when i click on button , popup should appear on screen without any errors in console and should not append login-app path to the URL.

**Comment by IlyaSurmay** [comment]
Please create a plunkr or sample repository so we can take a look a this.

**Comment by megrajkiran09** [comment]
Created sample repository 
https://github.com/megrajkiran09/Modal-Demo.git

**Comment by megrajkiran09** [comment]
I resolved the issue on my own. closing this now. Thanks.
Solution: Just added routerLink="." in html
