### ISSUE TITLE
alert.component.ts uses <template> instead of <ng-template>

### ISSUE THREAD

**Issue by newerik** [valor-software/ngx-bootstrap#2387]
Just a small warning what I noticed during the last build of my project (using ngx-bootstrap):
```
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
```
Affected file:
https://github.com/valor-software/ngx-bootstrap/blob/development/src/alert/alert.component.ts

**Comment by IlyaSurmay** [comment]
Please search for same issues before opening a new one...

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.X.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.3" or npm install ngx-bootstrap@next

**Comment by hussainwali74** [comment]
wtf every asshole gives a link with no solution "please search for same issues before .."
