### ISSUE TITLE
warning generated due to incorrect promise usage in bs-dropdown.state.js

### ISSUE THREAD

**Issue by jimmymain** [valor-software/ngx-bootstrap#2391]
I am getting the following warning

> bluebird.js:1542 Warning: a promise was created in a handler at http://localhost:44400/ts/vendor.js?v=680pfQDhy0sSDj6Ql0ZtqAk3_Y5k12KnUck3PMpIzYw:40264:29 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (http://localhost:44400/ts/vendor.js?v=680pfQDhy0sSDj6Ql0ZtqAk3_Y5k12KnUck3PMpIzYw:23033:10)
    at new BsDropdownState (http://localhost:44400/ts/application.js?v=LC19q2wJycinzYH4tvVdXIvHb4HvR-C8irr-H_wNlf8:16:29)

The code causing the problem (i suspect) is:

```
this.dropdownMenu = new Promise(function (resolve) {
    _this.resolveDropdownMenu = resolve;
});
```

I am not sure how to resolve the warning?
Any suggestions, and I will happily jump in and help.

**Comment by valorkin** [comment]
@jimmymain unfortunately I am not familiar with bluebird warnings, and trying to avoid using promises :)
according to this http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

```
this.dropdownMenu = new Promise(function (resolve) {
    _this.resolveDropdownMenu = resolve;
   return _this.resolveDropdownMenu;
});
```
should fix an issue,
nice reason for small PR :)
