### ISSUE TITLE
remove node_modules/angular2 from the distributed pkg

### ISSUE THREAD

**Issue by ludohenin** [valor-software/ngx-bootstrap#24]
Having angular2 here again (obviously present in the app) messes up the typings ref (duplicate in this case) when using `tsd link`.

**Comment by valorkin** [comment]
Make sense

**Comment by valorkin** [comment]
@ludohenin published as 0.44.4

**Comment by ludohenin** [comment]
Checked and confirm it works perfectly. Thanks.
