### ISSUE TITLE
BsModalService.show() error attachView of undefined

### ISSUE THREAD

**Issue by bmcockman** [valor-software/ngx-bootstrap#2403]
I get an error when trying to show a modal.

TypeError: Cannot read property 'attachView' of undefined
    at ComponentLoader.webpackJsonp.../../../../ngx-bootstrap/component-loader/component-loader.class.js.ComponentLoader.show (vendor.bundle.js:19572)
    at BsModalService.webpackJsonp.../../../../ngx-bootstrap/modal/bs-modal.service.js.BsModalService._showBackdrop (vendor.bundle.js:21508)
    at BsModalService.webpackJsonp.../../../../ngx-bootstrap/modal/bs-modal.service.js.BsModalService.show

**Comment by IlyaSurmay** [comment]
Could you create a plunkr or sample repository?

**Comment by bmcockman** [comment]
Sorry I haven't had time to set up some sample code just yet but I've found out that it occurs because I was injecting the BsModalService into an ErrorHandler. When doing this the backdrop component loader has an undefined ApplicationRef causing the error. I'm guessing the error handler is loaded before the application ref is created.

**Comment by valorkin** [comment]
@WildSlinkys yep, BsModalService injected into not directive or component or service,
will not work... it needs access to DOM specific providers, which are not available in services
