### ISSUE TITLE
bsDatePickerPopup does not work in an input-group

### ISSUE THREAD

**Issue by leomayer** [valor-software/ngx-bootstrap#2404]
```
import {BsDatePickerModule} from 'ngx-bootstrap/datepicker2';
@NgModule({
  imports: [    BsDatePickerModule, ....]})
```
	<div class="input-group" [ngClass]="{'has-error':isInValid}" >
          <input class="form-control" style="float:none" #inputField 
	          [(ngModel)]="internalDateString" (input)="inputChanged()" /> 
	    <div class="input-group-addon" (click)="clearDate()" *ngIf="allowEmpty" >
	        <span class=" glyphicon glyphicon-remove" aria-hidden="true"></span>
	    </div>
	    <div class="input-group-addon datepickerCLS" dropdown>
	        <button dropdownToggle bsDatePickerPopup  [config]="config" [(bsValue)]="bsValue" type="button" class="glyphicon glyphicon-calendar datepickerCLS" aria-hidden="true">
	        </button>
	    </div>
	</div>

Somehow the popup does not appear in the same style as in example - [it looks ](https://ibb.co/gW9PSF)*ugly* and not keeping the alignments :-(
Any hints how to fix it and how to use it _properly_ with an input-group?

**Comment by valorkin** [comment]
yay, how did you found it :)
it was hidden experiment >.<
which we use in prod for half of year
check this out:
http://valor-software.com/ngx-bootstrap/#/datepicker#examples
in v1.9.0

**Comment by valorkin** [comment]
pay attention, there are additional css

**Comment by chadxsmith** [comment]
when pasting the css from `bs-datepicker.css ` into my component's css file, the style is not appearing. any ideas?

**Comment by valorkin** [comment]
Add styles to your html, not component
It is reusable styles, scoping them will not work as you see

**Comment by marcelinne** [comment]
@valorkin , please, would you give as an example how to do it? after add as documentation the styles are not working for bs-datepicker for me too. Thanks in advance.

As this way is not working too:
```
<style>
.bs-datepicker {
  display: inline-block;
  vertical-align: top;
  min-width: 279px;
  min-height: 250px;
.
.
.
</style>
<pre>{{bsRangeValue}}</pre>
<input type="text"
       value="{{ bsRangeValue[0] | date:'yMd'}} - {{ bsRangeValue[1] | date:'yMd'}}"
       bsDaterangepicker [(bsValue)]="bsRangeValue">
<span style="display: inline-block">
  <button class="btn btn-success" (click)="drp.toggle()">Date Range Picker popup</button>
  <bs-daterangepicker #drp [(bsValue)]="bsRangeValue" placement="right" style="display: block"></bs-daterangepicker>
</span>

```

**Comment by valorkin** [comment]
I am adding styles to angular cli config, styles section

**Comment by leomayer** [comment]
You mean to add it to the HTML tag directly? But isn't that quite a lot? Or
you mean to add it to a CSS-file?

Am 25.08.2017 8:50 PM schrieb "Dmitriy Shekhovtsov" <
notifications@github.com>:

**Comment by valorkin** [comment]
Same way you are adding bootstrap css

**Comment by samipadwani** [comment]
Can anyone tell me how to use BsDatePicker with its selector i.e <bs-datepicker>. i dont want to use it with <input> tag..

**Comment by valorkin** [comment]
Dont use it, its crap, i will remive it shortly

**Comment by valorkin** [comment]
Selector as component
