### ISSUE TITLE
<template> element is deprecated Angular warning for an Alert

### ISSUE THREAD

**Issue by vadi2** [valor-software/ngx-bootstrap#2406]
Using an `<alert>` produces the following warning on latest Angular:

```
core.es5.js:2933 Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///AlertModule/AlertComponent.html@1:0
```

**Comment by IlyaSurmay** [comment]
#2387 
Please search for same issues before opening a new one...

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.X.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.3" or npm install ngx-bootstrap@next

**Comment by vadi2** [comment]
Thanks, that worked.
