### ISSUE TITLE
Collapse Accordion in code

### ISSUE THREAD

**Issue by dmanjava** [valor-software/ngx-bootstrap#2408]
Hi,

I have a unique situation were we have to have two modal on after another.  The first modal has an accordion showing a list of items which can be quite long.  When the user clicks an item in the list in the accordion a detail modal comes up.

My question is how can I collapse the accordion from another components click?  Is there a method on accordion to collapse or did I miss it?

Thanks in advance.
Darnell

**Comment by IlyaSurmay** [comment]
Hi
http://valor-software.com/ngx-bootstrap/#/accordion#dynamic
You can toggle accordion by manipulating its input property `[isOpen]`

**Comment by dmanjava** [comment]
Great thanks all set.
