### ISSUE TITLE
selectionDone is not fired up.

### ISSUE THREAD

**Issue by pyatetskiy** [valor-software/ngx-bootstrap#2409]
I am trying to work with datepicker component. The  onSelectionDone  event handle in a sample below never called. onActiveDateChange is called on month change and on initial set up. I there a way to get notification when user clicks on a date (I thought that when selectionDone should be fired).

<datepicker
        (selectionDone) = "onSelectionDone($event)"
        (activeDateChange) = "onActiveDateChange($event)"
></datepicker>

Thank you,
Alex

**Comment by IlyaSurmay** [comment]
Which version of ngx-bootstrap are you using?

**Comment by pyatetskiy** [comment]
I have "ngx-bootstrap": "~1.8.0", in my package.json file.

**Comment by pyatetskiy** [comment]
So I think it's 1.8.1

**Comment by pyatetskiy** [comment]
It was 1.8.0. I just updated to 1.8.1 is called. 
Thank you!
