### ISSUE TITLE
Uncheckable radio buttons still checkable

### ISSUE THREAD

**Issue by seyfert** [valor-software/ngx-bootstrap#2411]
The uncheckable attribute for radio buttons is not working.  See the demo:
http://valor-software.com/ngx-bootstrap/#/buttons#radio

You are able to select the green buttons even though they have the uncheckable attribute.

Also, when a radio button is uncheckable should it be also have the disabled class?

**Comment by mkoczka** [comment]
This is the desired behavior. The uncheckable attribute doesn't mean it cannot be checked. (that's disabled button). It means that this radio group can be unchecked by clicking on the active option. I pushed the PR that clarify this behavior in the documentation.
