### ISSUE TITLE
Compatibilty bootstrap 4 Beta

### ISSUE THREAD

**Issue by johaven** [valor-software/ngx-bootstrap#2413]
Dropdowns no longer working since Beta 4.

**Comment by penkin** [comment]
Having the same issue, created a blank project to test and see that dropdowns don't display at all. There are no error shown in the console so unfortunately no valuable info I can add.

**Comment by fchiumeo** [comment]
ngx-bootstrap need add the class show in dropdown-menu to working with beta

**Comment by valorkin** [comment]
Error? Angular version? Is bs4 theme for ngx-bootstrap enabled?

**Comment by penkin** [comment]
I checked now in my test app and it's definitely working now. Thanks guys.

Uses the following packages:

    "@angular/animations": "^4.3.5",
    "@angular/common": "^4.3.5",
    "@angular/compiler": "^4.3.5",
    "@angular/core": "^4.3.5",
    "@angular/forms": "^4.3.5",
    "@angular/http": "^4.3.5",
    "@angular/platform-browser": "^4.3.5",
    "@angular/platform-browser-dynamic": "^4.3.5",
    "@angular/router": "^4.3.5",
    "bootstrap": "^4.0.0-beta",
    "core-js": "^2.4.1",
    "ngx-bootstrap": "^1.9.0",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"

@tr0llslay3r make sure you have `<script>window.__theme = 'bs4';</script>` in your `index.html`

**Comment by tr0llslay3r** [comment]
ok well i have to tests again,

i have     "@angular/core": "^4.2.4", and all other angular stuff 4.24 too.

**Comment by tr0llslay3r** [comment]
works :)
i just forgot to import BsDropdownModule in my new test -.-

thank you guys! awesome project!

**Comment by danmarklagman** [comment]
> I checked now in my test app and it's definitely working now. Thanks guys.
> 
> Uses the following packages:
> 
> ```
> "@angular/animations": "^4.3.5",
> "@angular/common": "^4.3.5",
> "@angular/compiler": "^4.3.5",
> "@angular/core": "^4.3.5",
> "@angular/forms": "^4.3.5",
> "@angular/http": "^4.3.5",
> "@angular/platform-browser": "^4.3.5",
> "@angular/platform-browser-dynamic": "^4.3.5",
> "@angular/router": "^4.3.5",
> "bootstrap": "^4.0.0-beta",
> "core-js": "^2.4.1",
> "ngx-bootstrap": "^1.9.0",
> "rxjs": "^5.4.2",
> "zone.js": "^0.8.14"
> ```
> 
> @tr0llslay3r make sure you have `<script>window.__theme = 'bs4';</script>` in your `index.html`

Cool! Still works in 2020 🥇
