### ISSUE TITLE
Template deprecated on Datepicker

### ISSUE THREAD

**Issue by Ivaneyko** [valor-software/ngx-bootstrap#2415]
The <template> element is deprecated.

**Comment by IlyaSurmay** [comment]
Please search for same issues before opening a new one...

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.X.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.3" or npm install ngx-bootstrap@next

**Comment by tucq88** [comment]
So you can't use <datepicker></datepicker> any more ? :(
