### ISSUE TITLE
The <template> element is deprecated. Use <ng-template> instead

### ISSUE THREAD

**Issue by redaikidoka** [valor-software/ngx-bootstrap#2416]
The Alert Component is still using <template> instead of <ng-template>

```core.es5.js:2933 Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///AlertModule/AlertComponent.html@1:0
```

**Comment by fchiumeo** [comment]
please, please search before creating new issues
https://github.com/valor-software/ngx-bootstrap/search?utf8=%E2%9C%93&q=ng-template&type=Issues

npm i ngx-bootstrap@next

**Comment by IlyaSurmay** [comment]
#2406 
#2387

**Comment by redaikidoka** [comment]
So to be fair I did search for a bunch of versions of the text I submitted.
