### ISSUE TITLE
Cannot set default button when ChangeDetectionStrategy.OnPush is set

### ISSUE THREAD

**Issue by bobwiller** [valor-software/ngx-bootstrap#2420]
I am trying to use a radio button group in a dumb component. If I copy & paste the radio button sample from https://valor-software.com/ngx-bootstrap/#/buttons everything works fine.  However, if you set changeDetection: ChangeDetectionStrategy.OnPush in the @Component() the control still works EXCEPT it will no longer select the initial/default radio button. So using the example code, there is no button selected by default - is this a bug or does something else need to be set?

Thanks,
Bob

**Comment by valorkin** [comment]
could be an issue

**Comment by IlyaSurmay** [comment]
Fixed in 2.0.0-beta.8
