### ISSUE TITLE
Nested Modals in Custom Control

### ISSUE THREAD

**Issue by olcaolgun** [valor-software/ngx-bootstrap#2421]
Hi,

I have a problem with nested modals. When i define a modal.component for my custom control and open this modal.component from another modal (which is including my custom control), "child modal" is appearing inside the first modal's frame.

I want to display modals seperately. How can i solve this problem?

Normally, modals are defined in html page with seperate div's. But when modal is defined in a custom control, it is processed inside the first model's div tag. 

I wrote an example for modal behaviour inside the custom control below:
https://plnkr.co/edit/h6HP98MnQhnCtsVVbUwL?p=preview

**Comment by IlyaSurmay** [comment]
Are you sure that this issue belongs to ngx-bootstrap? I don't even see Angular in your plunkr, just pure bootstrap 4 with its js plugin

**Comment by olcaolgun** [comment]
You are right Ilya. Sorry this issue is related with bootstrap 4. Code is working properly with ngx-bootstrap. Sorry.
