### ISSUE TITLE
ngx-bootstrap 1.8.1 incompatible with angular/compiler-cli 4.0.0

### ISSUE THREAD

**Issue by shoebsd31** [valor-software/ngx-bootstrap#2422]
previously I had, 

**component** : bsModal
**ngx-bootstrap** : 1.7.1
**angular/compiler-cli** : 4.0.0.

I want to use BsModalService  and BsModalRef which does not exist in ngx-bootstrap version 1.7.1.

I have upgraded the **ngx-bootstrap version to 1.8.1** , but then I think it is not compatible with angular/compiler cli version 4.0.0.

I get an error : 
![cli error](https://user-images.githubusercontent.com/5415085/29363584-ebcdc11a-8290-11e7-83ea-5553e2bfcc5d.JPG)

My package.json looks like this : 
![pkj](https://user-images.githubusercontent.com/5415085/29363763-76dfaa20-8291-11e7-847e-ccd95eae65f7.JPG)

Can you please help me with this issue. I just need to open the modal from component using bsModal

**Comment by fchiumeo** [comment]
delete package-lock and node_module and reinstall all

**Comment by shoebsd31** [comment]
I tried both, didn't help. If you create a new angular-cli application and install ngx-bootstrap later on, you get this error : 

![a2-clie_error](https://user-images.githubusercontent.com/5415085/29364445-b9b01568-8293-11e7-9a31-12e9d77a3be2.JPG)

**Comment by shoebsd31** [comment]
![a2-clie_error](https://user-images.githubusercontent.com/5415085/29364475-d1d0969a-8293-11e7-882b-5b18d7513605.JPG)

I tried both, it didn't help either. I accidentally closed this issue, so re-opened it. 
ngx-bootstrap (current version) clearly doesn't work with angular-cli latest version

**Comment by fchiumeo** [comment]
your problem is with installation of packages, not ngx-bootstrap
ps: why use old version of angular/cli

**Comment by shoebsd31** [comment]
Thanks for your help.
I have upgraded angular/cli version and it worked.
