### ISSUE TITLE
feat(timepicker): showMinutes flag check in timepicker component

### ISSUE THREAD

**Issue by pythonist33** [valor-software/ngx-bootstrap#2430]
Sometime we might need to have hours with Meridian displayed 
Adding new flag called showMinutes to enable/disable Minute box will be helpful
Could anyone validated this issue and add your suggestions on this... I already implemented that functionality on my local referring case of showSeconds

Thank you note :+1: For implementation showSeconds functionality

**Comment by fhuschle** [comment]
I can take a look at this.
