### ISSUE TITLE
Re-throw click event when clicked inside the modal

### ISSUE THREAD

**Issue by yzdedream** [valor-software/ngx-bootstrap#2443]
When clicked inside a modal now the container eats the event so other components inside the modal could not receive the event. For example a dropdown won't be to close itself when clicked outside the dropdown and inside the modal. 

https://github.com/valor-software/ngx-bootstrap/blob/5dd456b8767724fb708662c6552f00b0cfa53fe1/src/modal/modal-container.component.ts#L31

**Comment by IlyaSurmay** [comment]
Could you provide some example please? On 1.9.2 scenario with dropdown works just fine.
Closing it for now.

**Comment by yzdedream** [comment]
It turns out my dropdown didn't have a dropdownToggle.
After adding a invisible toggle it closes fine.
`<div dropdownToggle></div>`

Thanks
