### ISSUE TITLE
Typeahead container not visible

### ISSUE THREAD

**Issue by lucifer-AM** [valor-software/ngx-bootstrap#2464]
I am implementing Static array typleahead in angualr 2 app inside a table td but I am not able to see the typeahead-container which can be seen in the inspector but not visible on DOM. Please help.!!!!

HTML:- 

`<td><input [(ngModel)]="selected" [typeahead]="states" class="form-control"></td>`

TS:-

`public selected:string;
  public states:string[] = ['Alabama', 'Alaska', 'Arizona', 'Arkansas',
    'California', 'Colorado',
    'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
    'Illinois', 'Indiana', 'Iowa',
    'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
    'Michigan', 'Minnesota',
    'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
    'New Jersey', 'New Mexico',
    'New York', 'North Dakota', 'North Carolina', 'Ohio', 'Oklahoma', 'Oregon',
    'Pennsylvania', 'Rhode Island',
    'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
    'Virginia', 'Washington',
    'West Virginia', 'Wisconsin', 'Wyoming'];
`

**Comment by eyerean** [comment]
Does the typeahead work if it is outside the table? Maybe the cell's margins are not big enough?

**Comment by valorkin** [comment]
@lucifer-AM set `container="body"`
it should help, if not - drop me a note, I will reopen issue
