### ISSUE TITLE
Tab: customClass doesn allow multiply class

### ISSUE THREAD

**Issue by sshurin** [valor-software/ngx-bootstrap#2467]
Hi, 
My code is .... [customClass]="getStyles()"
getStyles returns "hide" or "hide invalid". In case "hide invalid" I get error "The token provided ("hide invalid") contains HTML space characters, which are not valid in tokens." because of splitting classes by space.
This is because in beta 4, for customClass setter you use this.renderer.setElementClass which does not allow multiply classes separated by space.
How can i continues using multiply classes for customClass?

**Comment by valorkin** [comment]
you can do a really small PR
which will check that customClass is not empty string
split by `" "`
and call `setElClass` for each
nice reason for small PR :)
