### ISSUE TITLE
popover should have some feature like tootip's 'popupDelay'/'fadeDuration'

### ISSUE THREAD

**Issue by turnerguo** [valor-software/ngx-bootstrap#2469]
seems tooltip and popover components should be merged into one component, just need some customisation is enough.

**Comment by valorkin** [comment]
@turnerguo I took a bit different approach,
I have made Component loader, which is used for all dynamic components
tooltips, popovers, dropdowns, typeahead, modals, datepicker....
and yes, all of them will have animation and delayed show
just released 1.9.0
there are will be one more release next week for ng v2
and I will be moving to ng v4 completely
what will allow me to enable animation ;)
