### ISSUE TITLE
import ngx-bootstrap error?

### ISSUE THREAD

**Issue by lfrong82** [valor-software/ngx-bootstrap#2472]
`  "dependencies": {
    "@angular/animations": "^4.3.0",
    "@angular/common": "^4.3.0",
    "@angular/compiler": "^4.3.0",
    "@angular/core": "^4.3.0",
    "@angular/forms": "^4.3.0",
    "@angular/http": "^4.3.0",
    "@angular/platform-browser": "^4.3.0",
    "@angular/platform-browser-dynamic": "^4.3.0",
    "@angular/router": "^4.3.0",
    "@angular/service-worker": "^1.0.0-beta.16",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "intl": "^1.2.5",
    "jquery": "^3.2.1",
    "moment": "^2.18.1",
    "ngx-bootstrap": "^1.8.1",
    "rxjs": "^5.4.2",
    "systemjs": "0.20.14",
    "zone.js": "0.8.12"
  }`

`    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
      {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      {src: 'bootstrap/dist/js/bootstrap.min.js', inject: 'libs'},
      {src: 'bootstrap/dist/css/bootstrap.min.css', inject: true},
      {src: 'bootstrap/dist/css/bootstrap-theme.min.css', inject: true},
      {src: 'bootstrap/dist/css/bootstrap-theme.min.css.map', inject: true},    
    ];

let additionalPackages: ExtendPackages[] = [
    {
      name: 'ngx-bootstrap',
      path: 'node_modules/ngx-bootstrap/bundles/ngx-bootstrap.umd.min.js'
    },
    {
      name: 'ngx-bootstrap/*',
      path: 'node_modules/ngx-bootstrap/bundles/ngx-bootstrap.umd.min.js'
    },
    {
      name:'moment',
      path:'node_modules/moment',
      packageMeta:{
        main: 'moment.js',
        defaultExtension: 'js'
      }
    }];

    this.addPackagesBundles(additionalPackages);`

error message:
http://localhost:5555/node_modules/ngx-bootstrap/bundles/ngx-bootstrap.umd.min.js/alert Failed to load  resource: the server responded with a status of 404 (Not Found)
localhost/:64 Error: Fetch error: 404 Not Found
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1503394977606:1478:13
    at ZoneDelegate.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1503394977609:391:26)
    at Zone.run (http://localhost:5555/node_modules/zone.js/dist/zone.js?1503394977609:141:43)
    at http://localhost:5555/node_modules/zone.js/dist/zone.js?1503394977609:818:57
    at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1503394977609:424:31)
    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1503394977609:191:47)
    at drainMicroTaskQueue (http://localhost:5555/node_modules/zone.js/dist/zone.js?1503394977609:584:35) Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues

**Comment by valorkin** [comment]
@lfrong82 each component docs page has a note
that system.js is not able to import from `ngx-bootstrap/alerts` or any other submodule
so
1. use imports from `'ngx-bootstrap'` while using system.js
2. best option: merge to angular-cli
