### ISSUE TITLE
fix(collapse): switching CSS property when use CollapseModule.

### ISSUE THREAD

**Issue by lazy-detourer** [valor-software/ngx-bootstrap#2473]
I used CollapseModule like the following URL:

http://valor-software.com/ngx-bootstrap/#/collapse

And I confirmed that the 'CSS display Property' switches to 'block' and 'none'.
But in my case, it want to be another like 'inline-block' or 'table' when shown.
'none' is okay. It is exactly what I want.
But 'block' is not. How can I change to another value?

**Comment by valorkin** [comment]
no easy way, but you can `#col="bs-collapse"` and `col.display="'inline-block'"`
