### ISSUE TITLE
Modals. Error TypeError: Cannot read property 'nativeElement' of null when modal opens

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#2477]
**WTR**
1. Open modal page at ngx-bootstrap demo
2. Open Console
3. Click on any Open Modal button where modal opens from service
4. Look at console

**Actual result**
Error TypeError: Cannot read property 'nativeElement' of null when modal opens shows in console when modal shows. Screenshot attached
![modals](https://user-images.githubusercontent.com/27342505/29568983-c3a37922-875a-11e7-9371-e55735248e15.jpg)

**Expected result**
There are no errors in console.

**Comment by khoying** [comment]
This same issue is occurring with version 2.0.0-beta.4

**Comment by valorkin** [comment]
Next version not yet updated, to sync with 1.9.1
I am finishing datepicker, and will release next version update next week
