### ISSUE TITLE
Bootstrap 3. Pagination/Pager. In time of clicking "Previous" and "Next" buttons standard button appears under them

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#2479]
**WTR**
1. Open page Pagination in ngx-bootstap demo.
2. Select view in bootstrap 3
3. Open Pager example
4. Click on Previous and Next buttons

**Actual result**
Standard button appears under Previous and Next button in time of clicking on them

**Expected result**
No button appears under other buttons

**Comment by IlyaSurmay** [comment]
Fixed in #2940
