### ISSUE TITLE
chore(typeahead): Watermark text for Autocomplete

### ISSUE THREAD

**Issue by ps2goat** [valor-software/ngx-bootstrap#248]
I believe the original ng-bootstrap supported showing autocomplete text (first matching result) as a watermark in the input.  Can this get implemented in ng2-bootstrap?

**Comment by valorkin** [comment]
not sure I have seen what are talking about
so please provide a link to sample please :)

**Comment by sqwk** [comment]
@ps2goat Do you mean the HTML property `placeholder`? You can bind to that with ng2 using square brackets if you want to make it dynamic.
