### ISSUE TITLE
feat(modals) add unit test opening ng modal window

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#2492]
Hello guys! I need the unit test for opening the ngx-bootstrap modal window. But when I try it gives me a bunch of errors about undefined config, and backdrop property. And when I put this property, it gives another errors. Can you give a hint how to unit or maybe you know how test opening modal window function? I will be really appreciate for any help!

**Comment by grant-osborne** [comment]
If you're looking for a workaround, we've been using a stubbed service. 

If you want to work with the `BsModalRef` that is returned, you will need to stub that out as well.

```
@Injectable()
class StubbedModalService {
  public show(): void { }
}

beforeEach(async(() => {
imports : [ ],
declarations: [ ],
provides: [ 
     // Use stubbed implementation to avoid https://github.com/valor-software/ngx-bootstrap/issues/2492
        { provide: BsModalService, useClass: StubbedModalService },
]
}));

beforeEach(() => {
    fixture = TestBed.createComponent(SourceListComponent);
    component = fixture.componentInstance;

    // Injects our stubbed service - use these spys if you want to ensure that the modal
    // is invoked; if you have logic that relies on the BsModalRef you will need to mock that
    // and return it here as well.
    stubbedModalService = fixture.debugElement.injector.get(BsModalService);
    showSpy = spyOn(stubbedModalService, 'show').and.returnValue(undefined);
});
```

**Comment by dontboyle** [comment]
Do you have to do something different if your "live" module imports the ModalModule and uses ModalDirective in the component. The above doesn't seem to do anything in the setup described. the unit tests still seeing backdrop errors..


EDIT:

I fixed my problem with 

.ts 


	@ViewChild('modal') modal: ModalDirective;

.html

    `<div bsModal #modal="bs-modal" (onShown)="onShown()" class="modal lynnco-medium-modal fade" tabindex="-1" role="dialog"
    aria-labelledby="modal" aria-hidden="true" [config]="{backdrop: 'static'}">`
		
.spec.ts

     `

       import { ModalOptions } from 'ngx-bootstrap';

	beforeEach(() => {
		fixture = TestBed.createComponent(RejectModalComponent);
        component = fixture.componentInstance;
        //setup

		********component.modal.config = new ModalOptions();**********

		component.order = MockDtoData.OrdersSearchDto;
		component.show();
		fixture.detectChanges();
	});`

**Comment by ghiscoding** [comment]
Testing with Jest, I can do it by stubbing just the functions I want (instead of the class like @grantus mentioned earlier). My code looks like this

```ts
describe('Test Component', () => {
  const modalServiceStub = {
    onHide: new EventEmitter(),
    show: jest.fn(),
  };

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        NoteModalComponent,
      ],
      providers: [
        BsModalRef,
        { provide: BsModalService, useValue: modalServiceStub }
      ],
      imports: [
        ReactiveFormsModule,
        TooltipModule.forRoot()
      ]
    }).compileComponents();

    // then create the component
    fixture = TestBed.createComponent(NotesModalComponent);
    component = fixture.debugElement.componentInstance;
  });

  it('should click on "Add Note" and expect the modal window to be called', fakeAsync(() => {
    component.currentNotes = [note];
    const spy = jest.spyOn(modalServiceStub, 'show');
    spy.mockReturnValue(undefined);

    fixture.detectChanges();
    const addButton = fixture.debugElement.nativeElement.querySelector('button.btn-add-note');
    expect(addButton).not.toBeNull();
    addButton.click();
    tick();

    fixture.detectChanges();
    expect(spy).toHaveBeenCalledWith(AddEditNoteModalComponent, expect.any(Object));
  }));
```

The only problem I still have is that I also use the `onHide` from the ModalService and that just doesn't work, it's always `undefined` in the Test but it works correctly in the Component
```ts
export class MyComponent {
  openAddModalWindow(noteId?: string) {
    const initialState = { id: this.id, noteId };
    this.bsModalRefAddNote = this.modalService.show(AddEditNoteModalComponent, { initialState });

    // THIS LINE BREAKS MY TEST
    this.subscriptions.push(
      this.modalService.onHide.subscribe(() => this.getNotesAsync(false))
    );
  }
```
in the mean time I just wrap the line with a check and that makes my test happy and my component still works
```ts
if (this.modalService.onHide && this.modalService.onHide.subscribe) {
   this.subscriptions.push(
     this.modalService.onHide.subscribe(() => this.getNotesAsync(false))
   );
}
```
Does anyone know how to test that piece properly?
I tried to stub with Jest with `onHide: new EventEmitter()` and/or `onHide: jest.fn()` but it always says that `this.modalService.onHide` is undefined.
