### ISSUE TITLE
feat(timepicker): remove inline styling

### ISSUE THREAD

**Issue by ebakunin** [valor-software/ngx-bootstrap#2496]
The text inputs in the timepicker have inline styling. This makes it impossible to customize the look and feel of the component. Can the inline style be removed?

**Comment by valorkin** [comment]
@ebakunin they must be removed

**Comment by ebakunin** [comment]
@valorkin, I meant will Valor be removing the inline styling sometime in the future?

**Comment by valorkin** [comment]
Yes, they will
