### ISSUE TITLE
Type 'Timer' is not assignable to type 'number'.

### ISSUE THREAD

**Issue by be4code** [valor-software/ngx-bootstrap#25]
I've got version 0.44.3:
ng2-bootstrap/components/carousel/carousel.ts(145,7): error TS2322: Type 'Timer' is not assignable to type 'number'.

**Comment by valorkin** [comment]
yes, I have seen this thing, but it is not relevant to `ng2-bootstrap`,
some of typings defining `setInterval` return value type as `Timer`,
what is obviously wrong, and should be `number`
only question is: `who provides broken type definition`?

**Comment by valorkin** [comment]
@be4code so what starter are you using?

**Comment by be4code** [comment]
I'm using https://github.com/mgechev/angular2-seed but they told me how to use ng2-bootstrap with the seed.

**Comment by valorkin** [comment]
ok, I have found it: https://github.com/borisyankov/DefinitelyTyped/blob/master/node/node.d.ts#L36-L39

**Comment by ludohenin** [comment]
Maybe you can just force the type `(<number>yourVar)` where using it ?

**Comment by valorkin** [comment]
published as 0.44.5
@ludohenin please try

**Comment by ludohenin** [comment]
@valorkin didn't fixed the compiler error. But this did: `private currentInterval:NodeJS.Timer;` (line 56 of carousel.ts)

**Comment by valorkin** [comment]
but then all will have to install node tsd even if they use ng2-bootstrap from .net
do you have a branch where I can reproduce this issue?

**Comment by ludohenin** [comment]
Yeah I know and it's a problem ... [here](https://github.com/ludohenin/angular2-seed-ng2-bootstrap) is the branch

**Comment by valorkin** [comment]
@ludohenin fixed in 0.44.6, setInterval type doesn't worse to force ppl use tsd :)

**Comment by valorkin** [comment]
please approve and I am closing this issue

**Comment by ludohenin** [comment]
Works like a charm :)
I think you can close that one.
Thanks.

**Comment by valorkin** [comment]
Write to me if anything :)
can you create a gh-pages for your repo?
so I can include it ng2-bootstrap readme

**Comment by ludohenin** [comment]
~~[https://ludohen.github.io/angular2-seed-ng2-bootstrap](https://ludohen.github.io/angular2-seed-ng2-bootstrap)~~
[http://ludohenin.github.io/angular2-seed-ng2-bootstrap](http://ludohenin.github.io/angular2-seed-ng2-bootstrap)

**Comment by ludohenin** [comment]
I found this while roaming :). This how Timer issue is handled in ng2 source.
https://github.com/angular/angular/blob/master/modules/angular2/src/core/facade/async.ts#L10-L17

**Comment by valorkin** [comment]
cool, looks good
