### ISSUE TITLE
Modal BsModalRef export issue

### ISSUE THREAD

**Issue by giridharkl** [valor-software/ngx-bootstrap#2507]
Hi,

I am trying to use BsModalRef as per the examples provided. However I get the following error while compiling. What could be missing, please let me know.

ERROR in C:../confirm-modal/confirm-modal.component.ts (2,10): Module '"C:../node_modules/ngx-bootstrap/modal/modal-options.class"' has no exported member 'BsModalRef'.

Thanks
Giridhar

**Comment by valorkin** [comment]
that's strange...
`@Injectable()  class BsModalRef {`
hopefully you are importing it from `ngx-bootstrap/modal`
and using angular-cli

please provide more details about your configuration,
drop a note to slack when it will be

**Comment by giridharkl** [comment]
Upgraded ngx-bootstrap to 1.9, it works now thank you :)

**Comment by khoying** [comment]
I am having the same issue, but I am using the beta version:  2.0.0-beta.2,  It looks like their have been some major changes to the modal module.  Are there some examples or documentation for this version.

**Comment by khoying** [comment]
I upgraded to version 2.0.0-beta.4 and that fixed me problem.

**Comment by thomasjiangcy** [comment]
I'm using version 2.0.0-beta.6

It's been moved to `bs-modal-ref.service.ts` [here](https://github.com/valor-software/ngx-bootstrap/blob/31c5f62a48560d4372f0043241829a27e5f3deb6/src/modal/bs-modal-ref.service.ts)

So `import { BsModalRef } from 'ngx-bootstrap/modal/bs-modal-ref.service';` would work

**Comment by valorkin** [comment]
Don't use deep imports, if we forgot to export something from index files, it's an issue
But internal could change anytime

**Comment by gauravv7** [comment]
for "ngx-bootstrap": "^1.9.3":
import { BsModalRef } from 'ngx-bootstrap/modal/modal-options.class';

**Comment by neethu-george** [comment]
i have the same issue .for  "ngx-bootstrap": "^5.3.2",
how can i resolve this?

**Comment by daniloff200** [comment]
what version of Angular do you use, @neethu-george  ?

**Comment by Rahul-Geeks** [comment]
I am using Angular 5 and getting the same issue.
![ngx-bootsrap error and ng version](https://user-images.githubusercontent.com/42366136/131639381-97c66ec8-fdcc-4b3e-8c58-d47c919183c1.PNG)
