### ISSUE TITLE
In bootstrap 4 typeahed component classes not same as in bootstrap 3 typeahed 

### ISSUE THREAD

**Issue by Kratika7** [valor-software/ngx-bootstrap#2509]
I need to use bootstrap 4 and i am not getting same look and feel for typeahead as in bootstrap 3.

In **bootstrap 3**, there are ul tags inside typeahead container and classes are applied as in below image: 
![typeahed bs3](https://user-images.githubusercontent.com/22292879/29670113-51c23e92-8903-11e7-9bbd-54165ac26002.PNG)
Its html is as: 
![image](https://user-images.githubusercontent.com/22292879/29670300-e24de3c6-8903-11e7-87fc-ab05434bd351.png)

But in **bootstrap 4**, buttons are there inside typeahead container and so the classes are not applied as they were in bootstrap 3.
![typeahed bs4](https://user-images.githubusercontent.com/22292879/29670112-51bae1d8-8903-11e7-922d-ac8f7b1f797d.PNG)
Its html is: 
![image](https://user-images.githubusercontent.com/22292879/29670342-09fb035e-8904-11e7-9bd8-935309df48a1.png)

**Comment by valorkin** [comment]
Have you enabled bs4 theme for ngx bootstrap as described in docs?
Most probably not :)

**Comment by Kratika7** [comment]
@valorkin Thanks for the update. 
We have already enabled bootstrap 4 theme  as " window.__theme = 'bs4'; " which is also described in the docs. That didn't solved the issue either.
Could you please let u know if we are missing something.

**Comment by willy-wonka-git** [comment]
"window.__theme = 'bs4'; " didn't help me to get b4.

How to recompile with correct parameter? Or better ask you for special release only Bootstrap4?

I use 
@angular: 4.3.6
@angular/cli: 1.3.2
node: 6.9.5
ts: 2.3.4

**Comment by willy-wonka-git** [comment]
I replace all functions with isBs3() to return false, but i'm noob and don't know how to compile correctly

**Comment by valorkin** [comment]
Ngx bs version?

**Comment by igniteram** [comment]
I am facing the exact error, anyone came with a solution? is it the version issue? kinda stuck in it.
