### ISSUE TITLE
ModalBackdropComponent Multiplies

### ISSUE THREAD

**Issue by Sevenhero** [valor-software/ngx-bootstrap#2513]
I created a ModalDialog and everything works fine.
I just noticed because of an extension for Chrome (called Augury) everytime a Modal opens a 
new ModalBackdropComponent is created.

![error](https://user-images.githubusercontent.com/25794672/29685121-c47ff7ba-8914-11e7-9eb3-b8e175ef315a.PNG)

**Comment by valorkin** [comment]
This is interesting hint, I am not using augury and was not able to reproduce this issue.
Try to disable it and check DOM
