### ISSUE TITLE
Sortable Module not working

### ISSUE THREAD

**Issue by santosmken** [valor-software/ngx-bootstrap#2515]
Why is the Sortable module is not working even I imported the module for it and already exported it? Even the style doesn't show, it was just a plain text of  array.

**Comment by valorkin** [comment]
It's experimental module, which is extremely hard to use now
It will be split in several more small and simple to use.

As for now only docs can help, or you can ask in slack

**Comment by santosmken** [comment]
I think last week its working on my local machine. The time when I check it, it's not working anymore. I imported/ exported the Module for under the app, even shared and core module of my application but nothing works.

**Comment by dbrezoev** [comment]
Is there any progress here ? I came across the same issue. Is it resolved somehow ?
