### ISSUE TITLE
Moment is not a function DateFormatter

### ISSUE THREAD

**Issue by manuelCorredor** [valor-software/ngx-bootstrap#252]
Hi, Iḿ having a lot of trouble with moment js, I have already installed moment js as a dependency and installed the typings too (ambient and dev).

My code works fine (I'm not using the datepicker component), but sadly I get the next error:

TypeError: moment is not a function at DateFormatter.format

I've already read and follow the instructions in the main page and also in:

http://stackoverflow.com/questions/35166168/how-to-use-moment-js-library-in-angular-2-typescript-app

my system.js config look like this :

System.config({
transpiler: 'typescript',
typescriptOptions: { emitDecoratorMetadata: true },
packages: {
"app": {
"defaultExtension": "ts"
},
"node_modules/ng2-bootstrap": {
"defaultExtension": "ts"
},
},
map: {
moment: 'node_modules/moment/moment.js'
},
paths: {
"ng2-bootstrap/ng2-bootstrap": "node_modules/ng2-bootstrap/ng2-bootstrap"
}
});

can you help me ?

**Comment by valorkin** [comment]
known issue, will be fixed in terms of #324

**Comment by HJHorst** [comment]
I got it working by changing the first line of date-formatter.ts from
`import * as moment from 'moment';`
to
`import moment from 'moment';`

**Comment by BjornMelgaard** [comment]
Have the same issue when import DatepickerModule,  "ng2-bootstrap": "^1.1.5", moment: 2.15.0, project was generated by angular-cli 1.0.0-beta.14, angular 2.0.0

angular-cli.json (that`s all configuration)
```
.....
"scripts": [
  "../node_modules/jquery/dist/jquery.js",
  "../node_modules/bootstrap/dist/js/bootstrap.js",
  "../node_modules/moment/moment.js"
],
```
