### ISSUE TITLE
[Datepicker]Can't bind to 'bsValue' since it isn't a known property of 'input'.

### ISSUE THREAD

**Issue by BluesPeter** [valor-software/ngx-bootstrap#2522]
when i use datepicker, i have this error
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import {NavbarComponent} from './navbar/navbar.component';
import {DatepickerModule} from "ngx-bootstrap";
import {FormsModule} from "@angular/forms";

@NgModule({
  declarations: [
    AppComponent,
    NavbarComponent
  ],
  imports: [
    BrowserModule,
    DatepickerModule.forRoot(),
    FormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

<input type="text"
       value="{{ bsValue | date:'yMd'}}"
       bsDatepicker `[(bsValue)]="bsValue">]

public bsValue: any ;

**Comment by Hesesses** [comment]
having the same error

**Comment by nicogrimm** [comment]
Same error for me

**Comment by valorkin** [comment]
Pay attention to docs, you need to import BsDatepickerModule.forRoot()

**Comment by Hesesses** [comment]
![image](https://user-images.githubusercontent.com/2721970/29773252-2a80225e-8c05-11e7-98ca-70c8ee8096d0.png)

?

**Comment by valorkin** [comment]
http://valor-software.com/ngx-bootstrap/#/datepicker#examples
`BsDatepickerModule is activily developed but you can use it already`

**Comment by BluesPeter** [comment]
when i include BsDatepickerModule, the datepicker  shows,but it has none css,like this
![image](https://user-images.githubusercontent.com/28881358/29800910-4500e1f0-8c9f-11e7-9e16-c6997a30a5f9.png)
how can i include the bs-datepicker.css

**Comment by Hesesses** [comment]
@BluesPeter If you are using angular cli, insert the css path on styles section inside .angular-cli.json file. 

How did you get the datepicker working? I am just getting errors:

```
import { BsDatepickerModule } from 'ngx-bootstrap/datepicker';

@NgModule({
  imports: [BsDatepickerModule.forRoot(),...]
})
export class AppModule(){}

<input type="text"
       value="{{ bsValue | date:'yMd'}}"
       bsDatepicker [(bsValue)]="bsValue">

- - - - - - - - - -

ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'bsValue' since it isn't a known property of 'input'. ("type="text"
                     value="{{ bsValue | date:'yMd'}}"
                     bsDatepicker [ERROR ->][(bsValue)]="bsValue">
```

**Comment by BluesPeter** [comment]
@Hesesses  which version ngx-bootstrap do you use, you must use version 1.9.1,and you must also 
 imports DatepickerModule.forRoot()

**Comment by Hesesses** [comment]
@BluesPeter i'm using 1.9.1 and I have tried to import both together and separately, but nothing seems to work =/

*Update*
Got it working, I had forgot to export it on my shared module 🙈

**Comment by valorkin** [comment]
I will add this to FAQ one day
90% issue like this:
- forgot to import
- forgot forRoot
- forgot to import in child\lazy module
- forgot to export from shared module
:)

**Comment by EyaRhouma** [comment]
@BluesPeter  how did you include the bs-datepicker.css ?? I'm having the same problem

**Comment by wwyeong** [comment]
same here. where to load those missing class.

`<bs-datepicker-view ng-reflect-months="[object Object]" ng-reflect-options="[object Object]">
    <div class="bs-datepicker bs-timepicker theme-green">
      <div class="bs-datepicker-head">
        <bs-datepicker-navigation-view ng-reflect-month="[object Object]">
    <button class="previous" style="visibility: visible;"><span>‹</span>
    </button>
    <button class="current"><span>September</span>
    </button>
    <button class="current"><span>2017</span>
    </button>
    <button class="next" style="visibility: visible;"><span>›</span>
    </button>
  </bs-datepicker-navigation-view>
      </div>
      <div class="bs-datepicker-body">
        <bs-datepicker-month-view ng-reflect-month="[object Object]" ng-reflect-options="[object Object]">
    <table class="days weeks" role="grid">
      <thead>
      <tr>
        <th></th>
        <th aria-label="weekday">Su
        </th><th aria-label="weekday">Mo
        </th><th aria-label="weekday">Tu
        </th><th aria-label="weekday">We
        </th><th aria-label="weekday">Th
        </th><th aria-label="weekday">Fr
        </th><th aria-label="weekday">Sa
        </th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td class="week"><span>35</span>
        </td>
        <td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]" class="is-other-month">27</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]" class="is-other-month">28</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]" class="is-other-month">29</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]" class="is-other-month">30</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]" class="is-other-month">31</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">1</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">2</span>
        </td>
      </tr><tr>
        <td class="week"><span>36</span>
        </td>
        <td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">3</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">4</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">5</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">6</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">7</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">8</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">9</span>
        </td>
      </tr><tr>
        <td class="week"><span>37</span>
        </td>
        <td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">10</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">11</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">12</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">13</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">14</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">15</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">16</span>
        </td>
      </tr><tr>
        <td class="week"><span>38</span>
        </td>
        <td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">17</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">18</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">19</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">20</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">21</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">22</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">23</span>
        </td>
      </tr><tr>
        <td class="week"><span>39</span>
        </td>
        <td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">24</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">25</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">26</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">27</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">28</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">29</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]">30</span>
        </td>
      </tr><tr>
        <td class="week"><span>40</span>
        </td>
        <td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]" class="is-other-month">1</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]" class="is-other-month">2</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]" class="is-other-month">3</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]" class="is-other-month">4</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]" class="is-other-month">5</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]" class="is-other-month">6</span>
        </td><td role="gridcell">
          <span bsdatepickerdaydecorator="" ng-reflect-day="[object Object]" class="is-other-month">7</span>
        </td>
      </tr>
      </tbody>
    </table>
  </bs-datepicker-month-view>
      </div>
    </div>
  </bs-datepicker-view>`

**Comment by wwyeong** [comment]
same here. where to load those missing class

`<bs-datepicker-view ng-reflect-months="[object Object]" ng-reflect-options="[object Object]">
    <div class="bs-datepicker bs-timepicker theme-green">
      <div class="bs-datepicker-head">`

**Comment by valorkin** [comment]
bs-datepicker.css should be included same way you include bootstrap.css

**Comment by EyaRhouma** [comment]
i still don't see how :(   i added  "/datepicker/bs-datepicker.css" to .angular-cli.json like @Hesesses  mentioned ( because i'm using angular-cli ) 
![1](https://user-images.githubusercontent.com/30112743/30021842-9f6d8592-9160-11e7-97b9-abb76dc71e09.PNG)
 but i didn't add any styleUrl in the component that i'm using  
![2](https://user-images.githubusercontent.com/30112743/30021935-022183be-9161-11e7-8d83-0f521150e1c3.PNG)
should i add a styleUrl ??

**Comment by Hesesses** [comment]
I have this on .angular-cli.json

```
"styles": [
    "../node_modules/bootstrap/dist/css/bootstrap.css",
    "../node_modules/ngx-bootstrap/datepicker/bs-datepicker.css",
    "styles.scss"
],
```

**Comment by BluesPeter** [comment]
![image](https://user-images.githubusercontent.com/28881358/30022244-24255be8-919d-11e7-9c73-8be0f46b35f1.png)
@EyaRhouma 
I use like this,and i have solved this problem

**Comment by EyaRhouma** [comment]
@Hesesses  @BluesPeter  thannnks so much 💃  the path "../node_modules/ngx-bootstrap/datepicker/bs-datepicker.css" worked for me

**Comment by valorkin** [comment]
@Hesesses @BluesPeter thanks! :)

**Comment by subhashissarangi** [comment]
Angular 6: 

step 1: npm install ngx-bootstrap@4 --save
step 2: In ./src/styles.css
			@import '~bootstrap/dist/css/bootstrap.min.css';
			@import '~open-iconic/font/css/open-iconic-bootstrap.css';
step 3: in app.module.ts
 import { BsDatepickerModule } from 'ngx-bootstrap'; and addit to imports array
@NgModule({
  declarations: [ ],
imports: [
           BsDatepickerModule.forRoot()
]
