### ISSUE TITLE
Warning on alert component

### ISSUE THREAD

**Issue by mihaivarga** [valor-software/ngx-bootstrap#2524]
Hello,

There is a warning message about template being deprecated when using angular-cli (I have v. 1.3.2).

The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng://ngx-bootstrap/alert/alert.component.d.ts.

**Comment by valorkin** [comment]
Use @next version of ngx bootstrap, it has ng-templates

**Comment by valorkin** [comment]
Or ignore this warning it doesn't affect anything
