### ISSUE TITLE
How to prevent focusing on elements out of the modal

### ISSUE THREAD

**Issue by megrajkiran09** [valor-software/ngx-bootstrap#2526]
I am showing a modal using modalService.show method.

this.modalService.show(LoginComponent);

1 . when I do tabbing for accessibility , I want to prevent focusing on elements which are outside of the modal.
how can i fix it?
2. When I do tabbing for accessibility , I want to set focus on close icon. it's not working for my font awesome icon for closing popup.

Can you please help me on these 2 issues? Thank You.

**Comment by megrajkiran09** [comment]
any updates on this ?

**Comment by IlyaSurmay** [comment]
Closing as a duplicate of #1819
