### ISSUE TITLE
Modal Backdrop  is covering modal content

### ISSUE THREAD

**Issue by gate3** [valor-software/ngx-bootstrap#2527]
hi nice library. I have an issue. I'm using the modal component. But the backdrop is blocking me from interacting with the modal's content

**Comment by valorkin** [comment]
There are some z-index issues, (search in issues here )
And Try bs modal service

**Comment by valorkin** [comment]
Have you tried?

**Comment by gate3** [comment]
Hi, I decided to go with templates instead.  Thanks

**Comment by nellyigiebor** [comment]
hi,

I'm having the same problem.
What's the solutions to this please ??

I'm trying to use BsModalService  to show component as a modal but having this problem "Modal Backdrop is covering modal content".

Thanks in advance

**Comment by IlyaSurmay** [comment]
It would be nice to see a plunkr or sample repo with demo.

**Comment by akshatgandhi** [comment]
I don't know how to pass 'template' parameter (template: TemplateRef<any>) required to open from html to component if we are not using button click. Want to open modal from component after one http call. Thanks.

**Comment by IlyaSurmay** [comment]
@akshatgandhi [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) is the best place for questions like your one.

To open a modal from template, create a template in `ng-template` tag, get it in your component using ViewChild and then you'll be able to pass it as an argument in `show()` method of ModalService
