### ISSUE TITLE
bsDatepicker in reactive forms

### ISSUE THREAD

**Issue by suiaing** [valor-software/ngx-bootstrap#2528]
Can anybody help in using reactive forms for the bsDatepicker?

The demo of bsDatepicker uses two-way data-binding.

I try to add formControlName="inputdate" in the <input /> but fail to get the  value of inputdate.

**Comment by valorkin** [comment]
bsDatepicker, doesn't have control value accessor at the moment
but it is planned for this week

**Comment by NodeMirai** [comment]
I need this feature : )! Thank you for your great comonent!

**Comment by valorkin** [comment]
@NodeMirai thanks for feedback,
support for reactive forms added in PR https://github.com/valor-software/ngx-bootstrap/pull/2562
we need to test it properly and ready for release
