### ISSUE TITLE
clicking font awesome icon used inside the popover button is not opening the popover.

### ISSUE THREAD

**Issue by jainanuj0812** [valor-software/ngx-bootstrap#2529]
I have this code to open the popover,

```
<button  id="btn-filter" [popover]="avgStlmntFilterTemplate" placement="bottom" #pop="bs-popover">
            <i class="fa fa-filter"></i> <!-- Clicking to this icon not opens the popover -->
            Filter
</button>

<template #avgStlmntFilterTemplate>
    ---
</template>
```

I have tried to open the popover by registering the open method of the popover on click event of the icon, but not get any success.

**Comment by valorkin** [comment]
I will have to investigate this
it could be an issue

**Comment by jainanuj0812** [comment]
@valorkin 

For now I have added the below CSS which make it works for me

```
 #btn-filter:before {
        content: "\f0b0";
        font-family: FontAwesome;
}
```

I have put the content code for the filter icon instead of using the OOTB class available for the filter in Font Awesome library.

**Comment by IlyaSurmay** [comment]
Works fine here https://plnkr.co/edit/bmHTO2pQbs84nVk2NSTw?p=preview
Closing it for now.
