### ISSUE TITLE
feat(modal): initialize and create all component variables before OnInit

### ISSUE THREAD

**Issue by nbelyh** [valor-software/ngx-bootstrap#2530]
When you create a popup like this (using newly implemented #2047 - modal service)

``` typescript
    this.bsModalRef = this.modalService.show(ModalContentComponent);
    this.bsModalRef.content.title = 'Modal with component';
```
It seems that it assigns variable (title) **after** the popup is created. If this popup contains other components itself, that take that variable as an input parameter, this may cause things to be broken in our case :(

Is it possible to initialize all variables in the component being created **before it is rendered first time**?
I  am probably asking exactly for the same feature we had in ng-boostrap (angular-js), something like "resolve" parameter for "show()" function that resolves all arguments when creating the dialog (set them after creating the component, but before adding it to the DOM / showing it)? Something like:

``` typescript
    this.bsModalRef = this.modalService.show(ModalContentComponent, {
       resolve: {
           title: () =>  'Modal with component'
        }
    });
```

**Comment by valorkin** [comment]
modal service will be upgraded in ngx-bs v2
as for now I would rather made this resolve,
not as second param of `show`
but rather chain it
`this.modalService.resolve({some}).provide({}).show()`

**Comment by valorkin** [comment]
resolve and provide optional of course

**Comment by valorkin** [comment]
or huge configurable second param(
