### ISSUE TITLE
Not compatible with Angular 5.0.0-beta.5

### ISSUE THREAD

**Issue by slubowsky** [valor-software/ngx-bootstrap#2531]
Neither version 1.9.1 nor version @next (currently 2.0.0-beta.4) work with Angular 5.0.0-beta.5. When run, get many errors due to usage of deprecated properties.

First error (of many):
```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" -->
<ng-template [ngTemplateOutlet]="optionsListTemplate || (isBs4 ? bs4Template : bs3Template)"
  [ERROR ->][ngOutletContext]="{matches:matches, itemTemplate:itemTemplate, query:query}"></ng-template>

<!-- de"): ng:///TypeaheadModule/TypeaheadContainerComponent.html@3:2
...
```

**Comment by valorkin** [comment]
it's not compatible
this week we will drop support of v2, and can move to v4 and v5 support

**Comment by valorkin** [comment]
ngx-bs compatible with v5 should be available next week (+-1)

**Comment by harunurhan** [comment]
@valorkin did you mean that, ngx-bootstrap@2.0.0 (non-beta version) will be released and become the default, instead of `@next` ?

**Comment by valorkin** [comment]
A lot of refactoring and testing will be done in next 2 weeks, I don't want to publish any kind of regression

**Comment by isaacrlevin** [comment]
hey @valorkin any update on this? Don't want to rush but was curious if the code you are working on is commited anywhere.

**Comment by StellaCh** [comment]
Thanks for your work @valorkin ! When should we anticipate the fix?

**Comment by valorkin** [comment]
I already setup CI to check @next version compatibility,  now only need to fix it :)

**Comment by valorkin** [comment]
Tests are passing BTW
