### ISSUE TITLE
Unable to set active slide dynamicly

### ISSUE THREAD

**Issue by AntonLebiodkin** [valor-software/ngx-bootstrap#2533]
https://pastebin.com/JFJ43Qtn
^ Example with my carousel
For example if `activeSlideIndex` is 2, it anyway force to open first slide.

**Comment by IlyaSurmay** [comment]
Setting active slide is possible via this binding `[(activeSlide)]="activeSlideIndex"`, and I don't see this kind of code in your example. Try to use some code from [here](https://valor-software.com/ngx-bootstrap/#/carousel#dynamic)

**Comment by sangwin** [comment]
So I was working with this and no matter what `activeSlideIndex` I gave it was showing it from 0th index.

Then I did some adjustments and now its working fine.

I did following steps :
1. Get array of images and loop them with silde.
2. Set activeSlideIndex (It will be default 0)
3. After slider has been loaded make `activeSlideIndex` = index (Any number) using setTimeout

` setTimeout(() => {
this.activeSlideIndex = 3;
              }, 1000);
`

This will work fine.

**Comment by SouquieresAdam** [comment]
I confirm this issue,
Slide component has an initialization that force the first element (0) to be selected when the carousel il initialized, so the activeSlideIndex is ignored and cannot be used as initialization value.

The only way to resolve this is to wait for an angular life cycle before setting our initialization value.
`setTimeout(() => { this.activeSlideIndex = 3; }, 0);`

Waiting 0 ms ensure that all child component has finish their initialization and then we can set our wished initialization value after this bad SlideComponent behaviour.

This issue looks valid to me. It should be reopened.
The Slide component ngOnInit behaviour may be moved in CarouselComponent afterViewInit
