### ISSUE TITLE
Cannot use versions above 1.8.1 - RTE initializing

### ISSUE THREAD

**Issue by filipefreitas82** [valor-software/ngx-bootstrap#2535]
I'm getting this RTE if I try to use version 1.9.0 and 1.9.1
1.8.1 works fine.

Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.es5.js:1690)
    at compiler.es5.js:15382
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (compiler.es5.js:15365)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (compiler.es5.js:26795)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (compiler.es5.js:26768)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (compiler.es5.js:26697)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone (core.es5.js:4536)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule (core.es5.js:4522)
    at Object.../../../../../src/main.ts (main.ts:15)

**Comment by fchiumeo** [comment]
how import ngx module ?
show appmodule

**Comment by valorkin** [comment]
ng -v ?
and please show you app module

**Comment by filipefreitas82** [comment]
ng -v:

`@angular/cli: 1.3.2
node: 6.11.2
os: darwin x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6`

app.module

`import {BrowserModule} from "@angular/platform-browser";
import {NgModule, LOCALE_ID} from "@angular/core";
import {FormsModule} from "@angular/forms";
import {HttpModule, RequestOptions, Http} from "@angular/http";
import {
  AlertModule, CollapseModule, ModalModule, BsDropdownModule, TabsModule, DatepickerModule,
  TimepickerModule, ButtonsModule, TooltipModule
} from "ngx-bootstrap";
import {AppRoutingModule} from "./app-routing.module";
import {SessionService} from "services/session.service";
import {AppComponent} from "./app.component";
import {LoginComponent} from "components/session/login/login.component";

@NgModule({
  declarations: [
    AppComponent,
    LoginComponent,
    DatexPipe
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    AlertModule.forRoot(),
    ButtonsModule.forRoot(),
    ToastyModule.forRoot(),
    AppRoutingModule,
    NgUploaderModule,
    BsDropdownModule.forRoot(),
    CollapseModule.forRoot(),
    ModalModule.forRoot(),
    TooltipModule.forRoot(),
    ChartsModule,
    TabsModule.forRoot(),
    NgxDatatableModule,
    SelectModule,
    DatepickerModule.forRoot(),
    TimepickerModule.forRoot(),
    ClickOutsideModule,
    BrowserAnimationsModule,
    AutoCompleteModule,
    DndModule.forRoot(),
    CalendarModule,
    SharedModule
  ],
  providers: [
    {provide: LOCALE_ID, useValue: "pt-PT"},
    SessionService,
    NavigationService,
    ConfigService,
    ServiceHelpersService,
    AppRoutes,
    UtilService
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}
`

**Comment by valorkin** [comment]
Can you add modules one by one to imports, to figure out which one is failing

**Comment by valorkin** [comment]
Just in case import from "" will not work,
You need to provide path

**Comment by filipefreitas82** [comment]
Paste cut it out, I have it fine.
I'll let you know once I catch the module.

**Comment by valorkin** [comment]
Any updates?

**Comment by filipefreitas82** [comment]
I created a new project just to test this because the project I'm using is too complex.

In the new project, with all of these modules (AlertModule, CollapseModule, ModalModule, BsDropdownModule, TabsModule, DatepickerModule, TimepickerModule, ButtonsModule, TooltipModule), everything works fine.

**Comment by valorkin** [comment]
@filipefreitas82 actually, you can put breakpoint in this file after imports
and check value of each one
for some reason I have forgot about this way :)

**Comment by filipefreitas82** [comment]
It is breaking on the first ngx module imported, in my case AlertModule.

compiler.es5.js
```
var /** @type {?} */ importedModuleSummary = _this.getNgModuleSummary(importedModuleType);

if (!importedModuleSummary) {
      _this._reportError(syntaxError("Unexpected " + _this._getTypeDescriptor(importedType) + " '" + 
      stringifyType(importedType) + "' imported by the module '" + stringifyType(moduleType) + "'. 
      Please add a @NgModule annotation."), moduleType);

      return;
}
```

where importedModuleType is:
```
importedModuleType: ƒ AlertModule()
forRoot
:
ƒ ()
arguments
:
(...)
caller
:
(...)
length
:
0
name
:
"AlertModule"
prototype
:
{constructor: ƒ}
__proto__
:
ƒ ()
[[FunctionLocation]]
:
alert.module.js:12
[[Scopes]]
:
Scopes[3]
```

I don't see any breaking changes when updating from 1.8.1 to 1.9.0

**Comment by valorkin** [comment]
alert modules wasn't touched for months thats for sure

**Comment by IlyaSurmay** [comment]
Closing for no updates.
