### ISSUE TITLE
AlertComponent is still using template instead of ng-template. 

### ISSUE THREAD

**Issue by avarndell** [valor-software/ngx-bootstrap#2536]
I just installed 1.9.1

**Comment by devstu** [comment]
Just installed. Angular-CLI, followed the directions. Same issue.

**Comment by ctrl-brk** [comment]
Use ngx-bootstrap@next

**Comment by devstu** [comment]
That worked for me. Thank you.

**Comment by avarndell** [comment]
Thanks.  That worked.
