### ISSUE TITLE
[timepicker]why can't I see the arrow?

### ISSUE THREAD

**Issue by BluesPeter** [valor-software/ngx-bootstrap#2539]
![image](https://user-images.githubusercontent.com/28881358/29853737-2d483fc4-8d74-11e7-9be9-374bbda9d440.png)
The class 'glyphicon glyphicon-chevron-up' does not found in my project ,I do not konw why,but i can click the blank area

**Comment by valorkin** [comment]
1. you are using bs4, please enable theme for it
2. you need to add glyphicon.css (you can use this one) https://github.com/valor-software/ngx-bootstrap/blob/fb2671a44811daecfa052c987b02cac281a8d9d0/demo/src/assets/css/glyphicons.css
