### ISSUE TITLE
Is it possible to get attribute from model within an object?

### ISSUE THREAD

**Issue by santosmken** [valor-software/ngx-bootstrap#2542]
I want to get the name attribute under the dealerInfo that is under the Dealer Model. How can I get it and pass the event as the whole object since I needed the two (2) other attributes of the model?

**Comment by valorkin** [comment]
forgive, but seems this doesn't relates to ngx-bootstrap issues
join slack and ask

**Comment by santosmken** [comment]
What is the Slack domain?

**Comment by valorkin** [comment]
There are a link at 
- readme
- docs
- npm landing pages
