### ISSUE TITLE
New Datepicker Current Month Issue

### ISSUE THREAD

**Issue by touqeershafi** [valor-software/ngx-bootstrap#2543]
New Date picker always shows current month when open. It shows current month from `new Date()`. it should maintain state from `model` when assign to `[(ngModel)]`

**Comment by valorkin** [comment]
new datepicker doesn't have integration with ngModel,
if you will set bsValue it will show current month

just to keep you posted, couple things left before v1.9.2:
-control value accessor
- locales demo
- colors demo
- bs-config demo
