### ISSUE TITLE
Can't bind to 'bsValue' ngx-bootstrap 1.9.1

### ISSUE THREAD

**Issue by juliancuni** [valor-software/ngx-bootstrap#2545]
I am struggling for an hour now to get "**bs-datepicker popup**" working, but no success so far.

Please check my eco system below;

> Angular 2.4.0
> ngx-bootstrap 1.9.1
> bootstrap 3.3.7

My shared.module.ts
```
...............
import { DatepickerModule } from 'ngx-bootstrap/datepicker';
...............

@NgModule({
    imports: [
        ......................
        DatepickerModule.forRoot(),
        ......................
    ],
    providers: [ ],
    declarations: [],
    exports: [
        ......................
        DatepickerModule,
                ......................
    ]
})
```
My some.component.ts

```
export class SomeComponent implements OnInit {
    ...........................
    public bsValue: any;
    ..........................
}
```
My some.component.html

```
<pre>{{bsValue}}</pre>
 <input type="text" value="{{ bsValue | date:'yMd'}}" bsDatepicker [(bsValue)]="bsValue"> 
 <span style="display: inline-block">
        <button class="btn btn-success" (click)="dp.toggle()">Date Picker popup</button>
        <bs-datepicker #dp [(bsValue)]="bsValue" style="display: block"></bs-datepicker>
  </span>
```

I get the error below:

```
EXCEPTION: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'bsValue' since it isn't a known property of 'input'. ("bsValue}}</pre>
                  <input type="text" value="{{ bsValue | date:'yMd'}}" bsDatepicker [ERROR ->][(bsValue)]="bsValue"> 
                  <span style="display: inline-block">
                    <b"): KlientetComponent@142:84
Can't bind to 'bsValue' since it isn't a known property of 'bs-datepicker'.
1. If 'bs-datepicker' is an Angular component and it has 'bsValue' input, then verify that it is part of this module.
2. If 'bs-datepicker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("tn-success" (click)="dp.toggle()">Date Picker popup</button>
                    <bs-datepicker #dp [ERROR ->][(bsValue)]="bsValue" style="display: block"></bs-datepicker>
                  </span>
             "): KlientetComponent@145:39
'bs-datepicker' is not a known element:
```

Am I doing something wrong?

**Comment by pstepinski** [comment]
Looks like you should import module `BsDatepickerModule`, but so far I also have problem with importing  this: https://github.com/valor-software/ngx-bootstrap/issues/2489#issuecomment-326323150

**Comment by valorkin** [comment]
Try clean install
Export is in place for sure 
https://unpkg.com/ngx-bootstrap@1.9.1/index.js

**Comment by valorkin** [comment]
And yes, you should import 
BsDatepickerModule.forRoot()

**Comment by pstepinski** [comment]
Now it works! Thank you for your help

**Comment by valorkin** [comment]
awesome :)

**Comment by juliancuni** [comment]
Well, it was my mistake showing here only DatepickerModule.forRoot(), actually  BsDatepickerModule.forRoot() was imported on my shared module. Anyway. I believe that there is something wrong with my template. So far I've managed to show the BsDatepicker button, but it wont popup the calendar (no errors). So I guess its nothing to do with the ngx package it self. Thank you guys

**Comment by valorkin** [comment]
@juliancuni if you import it in shared module,
you have to export: BsDatepickerModule (without forRoot()) in shared module

**Comment by valorkin** [comment]
@juliancuni there are situation when datepicker is not visible
I will have to investigate it
but it is 100% showing on input[type=button]

**Comment by juliancuni** [comment]
Of course, I did export it. As I said, I am looking through my template (which is build by some other team).
