### ISSUE TITLE
Tab remove with observable modal result

### ISSUE THREAD

**Issue by giridharkl** [valor-software/ngx-bootstrap#2547]
Hi,
I am trying to achieve remove tab function display a confirmation modal before it is removed from the tabset. However the tab gets removed before the modal is shown.

`removeTab(id) {
    this.bsModalRef = this.bms.show(ConfirmModalComponent);
    this.bsModalRef.content.modalTitle = "Cancel Id";
    this.bsModalRef.content.modalBody = "Unsaved data will be lost! Do you want to cancel?"
    this.modalResSubs = this.hs.confirmModalResponseOb.subscribe(
      data => {
        if(data === true) {
          this.onTabCancel(id);
        }
      },
      err => {}
    )
  }`

Please help me to solve this issue.
Thanks
Giridhar

**Comment by valorkin** [comment]
Unfortunately, events not preventable at the moment, so what you can do
Add custom cross icon with click handler which will show modal, if user is OK with closing tab, close it
Preventable action are planned, but it is tricky to implement
