### ISSUE TITLE
bs-daterangepicker - incorrect second month; bs-datepicker - incorrect next month

### ISSUE THREAD

**Issue by andreigc** [valor-software/ngx-bootstrap#2548]
Hello,

I observed that the second month in the bs-daterangepicker - as observed today 31 August - is incorrectly displayed as October(instead of September).
Side note: if I press the next button(from datepicker) once and the back button two times I get the correct two months: August and September.

For the bs-datepicker the problem I noticed is similar - pressing next month displays October and not September.

I think this might be related to the date today - last day of the month.

Regards

**Comment by valorkin** [comment]
Thanks you very much, I will dig this tomorrow

**Comment by valorkin** [comment]
found where it's
fixed, will published in v1.9.2
