### ISSUE TITLE
Modal display animation is not executed completely

### ISSUE THREAD

**Issue by Calligos** [valor-software/ngx-bootstrap#2554]
Hi,
I'm using the modals according to the tutorial like this:

`<div bsModal #lgModal="bs-modal" class="modal fade" tabindex="-1"
	 [config]="getConfig()"
	 (onHide)="onDialogHide()">some content</div>`

Occasionally (probably 1 of 30 times), when the modal's show-function is called, the backdrop is displayed but the modal itself is not shown. My application then is in a state where no action is possible. Without the modal neither a click to the backdrop nor a esc press let's the backdrop disappear.

Using Chrome's developer tools I compared the modal's divs after waiting a few seconds (ensuring all the animations are done) and found that they differ in class and style (and aria):

When the modal is opened correctly, the element looks like this:
`<div _ngcontent-c6="" bsmodal="" class="modal fade in" tabindex="-1" aria-hidden="false" style="display: block;"></div>`

But when the modal 'freezes', the element looks like this:
`<div _ngcontent-c6="" bsmodal="" class="modal fade" tabindex="-1" aria-hidden="true" style="display: none;"></div> `

I'm using the ngx-bootstrap plugin in version 1.8.1

**Comment by valorkin** [comment]
in 2 words, animations are not stable at all,
this is why I was not adding them for a long time :(
try bs modal service instead of directive
it should help

**Comment by IlyaSurmay** [comment]
Closed as unreproduced (2.0.0-rc.0).
