### ISSUE TITLE
Date picker doesn't right-align properly

### ISSUE THREAD

**Issue by FieldMarshallVague** [valor-software/ngx-bootstrap#2555]
Hi there,

Summary of symptom:  Pop-up dropdown is rendering too close to the right hand side of screen and is being cut off.

I'm trying to use the dropdown's right-align class 'dropdown-menu-right' on a date picker, so it appears aligned to the right-hand-side of the input that triggers it.  The problem is that is appears so that its right-most edge is aligned to the left of the input box (without the above class, it appears so that its right-most edge is aligned to the left of the input box).

Here's my code:

`<div *dropdownMenu [ngClass]="{ 'dropdown-menu-right': alignRight }" class="dropdown-menu" role="menu" aria-labelledby="btnClose">`

The generated bs-dropdown-container element (that houses the dropdown) is obviously being absolutely positioned, using some calculation based on the input element's position, but doesn't seem to work.

Is this the right use-case for this dropdown-menu-right class ?  If not, is there another way to make the pop-up appear so that it's not partially off-screen when the input itself is right-align on the screen?  

Cheers :)

**Comment by valorkin** [comment]
ok, sample is here http://valor-software.com/ngx-bootstrap/#/dropdowns#alignment
your code looks fine to me
not sure what date picker does in issue name...

elements positioning is a pain :(
in v1.9.2 will be published `auto` positioning, but it is not really cool
in v2 of ngx-bs I will add completely new dynamic positioning,
to reposition elements so they can fit screen
