### ISSUE TITLE
Type Ahead - typeaheadOptionField - Does this support more than one field

### ISSUE THREAD

**Issue by karthikv-26** [valor-software/ngx-bootstrap#2563]
Suppose my data set is 
[{
  firstName : 'Howard',
  lastName : 'Jones',
},{
  firstName : 'John',
  lastName : 'Faulkner',
}]

For the above data set I can use typeaheadOptionField = "firstName" which will return the list of matching first names.

My requirement is to filter it based on both **firstName** and **lastName**. Any help would greatly be appreciated.

**Comment by karthikv-26** [comment]
I went through the documentation and it doesn't specify anything specific to querying based on multiple arguments. All it specifies is we can provide a function to typeaheadOptionField instead of the name of the key. Can this be clarified please?

**Comment by francarmona** [comment]
I need to filter by more than one property, same as @karthikv-26. I have read the documentation and I see that it is not possible right now. Is there any workaround for getting it? Thank you.

**Comment by francarmona** [comment]
I found a way to get it. I extended TypeaheadDirected for overriding normalizeOption. I added a new @input to my custom directive (typeaheadSearchFields) where you can specify the property names that you want to be used for searching by. An usage example would be:
```html
<input [(ngModel)]="model"
           [customTypeahead]="data"
           (typeaheadOnSelect)="handleSelect($event)"
           [typeaheadSearchFields]="['name', 'description']"
           [placeholder]="placeholder"
           class="form-control">
```
https://gist.github.com/francarmona/9e7d373e80e9cc9afb9c023923093c01

**Comment by JollyKrampus** [comment]
This is not a great solution, but what I ended up doing was having the backend return another property that could be used for the typeaheadOptionsField.

**Comment by gbertoncelli** [comment]
Why is this closed?

**Comment by vvolodin** [comment]
What makes this worse is that currently in 5.5.0 typeahead tries to filter my results from the server using this field, effectively breaking my multiple fields search functionality.

**Comment by pbaukov** [comment]
@vvolodin I haven't used typeaheadOptionsField at all, and my custom async typeahead seems to be broken after upgrading to 5.5.0. Have you managed to solve it somehow maybe?

**Comment by vvolodin** [comment]
Sure, the fix is very simple - downgrade :) `"ngx-bootstrap": "~5.4.0",`
I've checked the source code and this new behavior was introduced in 5.5.0 and it's already fixed in the current development branch, should be fine in the next release. So, again, just avoid using 5.5.0 if you can.

**Comment by daniloff200** [comment]
5.6.0 was released today with **next** tag, so, you can use it :) 

@vvolodin @pbaukov
