### ISSUE TITLE
Webpack issues 

### ISSUE THREAD

**Issue by avarndell** [valor-software/ngx-bootstrap#2564]
All the components I'm using from ngx-boostrap are giving webpack errors

Webpack: 2.5.1
ngx-bootstrap: 2.0.0-beta.4

ERROR in ./$$_gendir/~/ngx-bootstrap/tooltip/tooltip-container.component.ngfactory.ts
    Module parse failed: C:\Projects\AidsReagent\AIDSReagent.Site\$$_gendir\node_modules\ngx-bootstrap\tooltip\tooltip-container.component.ngfactory.ts Unexpected token (12:38)
    You may need an appropriate loader to handle this file type.
    | import * as i1 from 'ngx-bootstrap/tooltip/tooltip-container.component';
    | import * as i2 from 'ngx-bootstrap/tooltip/tooltip.config';
    | const styles_TooltipContainerComponent:any[] = ([] as any[]);
    | export const RenderType_TooltipContainerComponent:i0.RendererType2 = i0.╔╡crt({encapsulation:2,
    |     styles:styles_TooltipContainerComponent,data:{}});
     @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts 10:0-114
     @ ./ClientApp/boot.browser.ts

**Comment by valorkin** [comment]
this is webpack configuration issue,
please compare to (or use angular-cli) they have a pretty good config for bundling angular applications
