### ISSUE TITLE
build breaking with moment.js error.

### ISSUE THREAD

**Issue by kambojankit** [valor-software/ngx-bootstrap#257]
I have a fresh clone of angular2-seed project from @mgechev and i am installing ng2-bootstrap and the typings for moment.js as below:

```
npm install --save ng2-bootstrap
typings install moment --save

```

I also added the following mapping in System Js Configuration:

```
map: {
      moment: 'node_modules/moment/moment.js'
    }
```

But during application start i get the below errors:

> Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/moment.js(…) 

Can you please help me resolve this issue.

**Comment by valorkin** [comment]
hm, I will have to reproduce it
was working fine before
please check your fix against 
system.js version here
https://github.com/valor-software/angular2-quickstart

**Comment by kambojankit** [comment]
@valorkin you can close this issue, there is a PR created and it was tested and working for me. I didn't close this issue, since the PR was open.
