### ISSUE TITLE
Clockpicker

### ISSUE THREAD

**Issue by piernik** [valor-software/ngx-bootstrap#2579]
Will there be a clockpicker module? This is great - https://weareoutman.github.io/clockpicker/

**Comment by valorkin** [comment]
@piernik wasn't planning to include such, sorry

**Comment by piernik** [comment]
Oh... it is so much better than default bootstrap timepicker :/ Maybe You can reconsider??:)

**Comment by valorkin** [comment]
I can add it to roadmap as low prio
but timeframe will be crazy
