### ISSUE TITLE
fix(buttons): btnRadio does not work with reactive forms in versions >1.7.1

### ISSUE THREAD

**Issue by ds82** [valor-software/ngx-bootstrap#2581]
Using btnRadio & reactive forms I can only switch the value of the radio button-group once.

Tested with ngx-boostrap@1.9.1 & angular@4.3.6:
https://stackblitz.com/edit/angular-eck1fy
(You can switch the radio from false to true, but not back)

The bug does not occur in ngx-bootstrap@1.7.1.
Same demo as above with v1.7.1:
https://stackblitz.com/edit/angular-ycuxdq

**Comment by valorkin** [comment]
Interesting, cuz works on demo page
http://valor-software.com/ngx-bootstrap/#/buttons#radio

**Comment by ds82** [comment]
The demo kind of confuses me .. the "reactive form radio button demo" does not use radio buttons; it's more kind of a checkbox button demo (it indeed uses btnCheckbox and not btnRadio).

**Comment by verjik** [comment]
@valorkin, there is only reactive-checkbox example, reactive-radio is missing

**Comment by valorkin** [comment]
lol, true

**Comment by BenjD90** [comment]
Here two Plunkers that show this issue with **btnRadio** :

In ngx-boostrap@1.9.3 : http://plnkr.co/edit/t3tYCPC2Qag0GRQzHJLr
In ngx-bootstrap@1.7.1 : http://plnkr.co/edit/QkxYbbbfbwO07GwcmkdN

I hope one can find a fix or a workaround quickly :)

**Comment by dave0688** [comment]
A Fix for that would be very nice!

**Comment by AndreyYevtukhov** [comment]
still doesn't works(
checked in 2.0.0-rc.0
