### ISSUE TITLE
Can't use groupBy pipe on accordion-group *ngFor

### ISSUE THREAD

**Issue by oferah** [valor-software/ngx-bootstrap#2584]
I'm trying to create multiple accordion-groups using ngFor with groupBy pipe. like that:

`<accordion-group *ngFor="let item of items; groupBy:'itemProperty'" [isOpen]="isOpen">`

I'm getting this error:
`Can't bind to 'ngForGroupBy' since it isn't a known property of 'accordion-group'`
#
is there any solution?

**Comment by IlyaSurmay** [comment]
As far as I know, Angular's ngFor doesn't support optional parameters like `groupBy` out of the box. It was possible with AngularJS's `ng-repeat`.
To be able to use `groupBy` you nave to create a custom pipe, like described here https://stackoverflow.com/questions/37248580/how-to-group-data-in-angular-2
