### ISSUE TITLE
Typeahead within modal closes when scrollbar is clicked

### ISSUE THREAD

**Issue by ctrl-brk** [valor-software/ngx-bootstrap#2588]
Here's a plunker:
https://plnkr.co/edit/r0xqdcLOmGzfEYKc7H8r

Don't click "open modal" button just yet.
Type something (ex: letter a) in the input box, make your browser window small enough so you have a scrollbar on the "run" window. Play with scrollbar - everything works as expected.

Now open the modal window and try the same within it (there's another typeahead control). As soon as you touch the scrollbar control closes (receives blur event)

**Comment by valorkin** [comment]
interesting, how critical is this?

**Comment by ctrl-brk** [comment]
My users require this to be fixed but it can wait for a week or two.
It's interesting why this happens. I actually use my own kind if typeahead, not yours, but the behavior is exactly the same. Blur event received when you click pretty much any scrollbar on the screen.

**Comment by ctrl-brk** [comment]
Any update on this?
Thanks.
