### ISSUE TITLE
Typeahead completion in the middle of input

### ISSUE THREAD

**Issue by vadi2** [valor-software/ngx-bootstrap#2589]
Is it possible to for typeahead completion to still keep matching input after a bit of text has been entered? 

In the examples "al" only raises "Alabama" if it is the only input on the line, and if you type "hello al" no autocompletion comes up.

**Comment by IlyaSurmay** [comment]
Typeahead is searching for a substring user has typed, this is basic algorithm for typeahead, so this isn't possible for now.
