### ISSUE TITLE
Angular CLI AOT warning for alert component (deprecated "template")

### ISSUE THREAD

**Issue by mgroetan** [valor-software/ngx-bootstrap#2590]
When running an Angular CLI build in prod mode, using AOT, the following warning is logged:
Template parse warnings: 
The &lt;template&gt; element is deprecated. Use &lt;ng-template&gt; instead (" 
[WARNING -&gt;]&lt;template [ngIf]="!isClosed"&gt; 
  &lt;div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///[my path]/node_modules/ngx-bootstrap/alert/alert.component.d.ts.AlertComponent.html@1:0

**Comment by fchiumeo** [comment]
ngx-bootstratp@1.9.1 support angular 2 and angular 4
ngx-bootstrap@next suport only angular 4 and not warning template
