### ISSUE TITLE
BsModalRef does not succesfully import to [(ngModel)] on input 

### ISSUE THREAD

**Issue by isener** [valor-software/ngx-bootstrap#2592]
When we use Modal on ngx-bootstrap package, we cannot pass data successfully to edit from input on modal.
Do we have any different way to do it?

**Comment by valorkin** [comment]
can you provide some kind of sample? plnkr maybe?

**Comment by IlyaSurmay** [comment]
Hi, could you reproduce this issue in plunkr/stackblitz?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

Otherwise this issue will be closed.
