### ISSUE TITLE
BsDatepicker: (change) doesn't fire for ngModel

### ISSUE THREAD

**Issue by vhogemann** [valor-software/ngx-bootstrap#2598]
Hi there,

I'm trying to listen for the (change) event while using bsDatepicker, but it never fires. And (bsValueChange) is fired before the ngModel gets updated!

Should I discard ngModel entirelly and just bind [value] and update my controller with the value from (bsValueChange)?

Thanks!

**Comment by IlyaSurmay** [comment]
You can bind to model change using `(ngModelChange)` ,  it's fired after model is changed.

**Comment by valorkin** [comment]
`(ngModelChange)` is fired only for input fields,
and it's designed that `(bsValueChange)` is fired before `ngModelChange`
