### ISSUE TITLE
Cannot find name 'Partial'

### ISSUE THREAD

**Issue by manjureddy7** [valor-software/ngx-bootstrap#2599]
This issue exists.! Please help

i.node_modules/ngx-bootstrap/datepicker/bs-daterangepicker.component.d.ts (45,15): Cannot find name 'Partial'.

ii.node_modules/ngx-bootstrap/datepicker/bs-daterangepicker.component.d.ts (45,15): Cannot find name 'Partial'.

**Comment by IlyaSurmay** [comment]
Closing as a duplicate of #2597

**Comment by eva-Z** [comment]
Have you solved the problem?
