### ISSUE TITLE
【datepicker】how can I use different locales. 

### ISSUE THREAD

**Issue by BluesPeter** [valor-software/ngx-bootstrap#2607]
I use like this

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
**import { defineLocale } from 'ngx-bootstrap/bs-moment';
import { zhCn } from 'ngx-bootstrap/locale';
defineLocale('zh-cn', zhCn);**

@NgModule({
  imports: [
    CommonModule,
    ModalModule.forRoot(),
    PaginationModule.forRoot(),
    RouterModule,
    FormsModule,
    SelectModule,
    SlimLoadingBarModule.forRoot(),
    DatepickerModule.forRoot(),
    BsDatepickerModule.forRoot(),
    TimepickerModule.forRoot(),

  ],
  exports: [
    ComingSoonComponent,
    DatetimeInputComponent,

...

But it can't work
how can I use?

**Comment by BluesPeter** [comment]
when I use bsDaterangepicker,it shows like this
![image](https://user-images.githubusercontent.com/28881358/30257252-3b33d33c-96e3-11e7-8944-5d73c0541f9f.png)
I can't see the left calendar

**Comment by SidekickJohn** [comment]
Hey @BluesPeter 

additionally to the changes you made in the module.ts, you need this tag in your HTML on your input-field:
`[bsConfig]="bsConfig"`
and in your component.ts you need something like this in the constructor:
`this.datepickerLocale = 'zh-cn';`
`this.bsConfig = Object.assign({}, {locale: this.datepickerLocale});`

Maybe that helps!

**Comment by sanka2701** [comment]
In your class:
options: BsDatepickerConfig;

  constructor() {
    defineLocale(de.abbr, de);
    this.options = new BsDatepickerConfig();
    this.options.locale = de.abbr;
  }

imports:
import { BsDatepickerConfig } from 'ngx-bootstrap/datepicker';
import { defineLocale } from 'ngx-bootstrap/bs-moment';
import { de } from 'ngx-bootstrap/locale';


there is updated documentation about this. However I am still fighting on setting the first day of week to Monday. Anybody who could help with that ? Big Thanks

**Comment by BluesPeter** [comment]
@SidekickJohn @sanka2701 thanks very much,I has fixed it
