### ISSUE TITLE
override css property carousel

### ISSUE THREAD

**Issue by roydekleijn** [valor-software/ngx-bootstrap#2608]
Hi ,

I like to override the following CSS property of the carousel.

.carousel-control-next, .carousel-control-prev {
width: auto; // in stead of 15%
}

So, the 2 arrows are positioned differently.

![image](https://user-images.githubusercontent.com/1298389/30249157-f74371ee-9635-11e7-90ae-7647311c0abb.png)

How can this be done?
Thanks,
Roy

**Comment by roydekleijn** [comment]
anyone ?

**Comment by IlyaSurmay** [comment]
This is more related to Bootstrap itself, not ngx-bootstrap, as we don't use any additional styles and fully rely on Bootstrap's stylesheets.
