### ISSUE TITLE
fix(timepicker): TimePicker shows 01:00 if date is undefined and showMeridian is false

### ISSUE THREAD

**Issue by Anzge** [valor-software/ngx-bootstrap#2614]
If  [showMeridian]="false" an empty/undefined date shows 01:00.
If  [showMeridian]="true", no time (only placeholders) is shown , which is the right behavior.

**Comment by ebakunin** [comment]
I can confirm this as I have the same problem, though in my case the time displays: "17:00" (the difference may be related to the timezone). Is there any progress with this defect?

**Comment by ghost** [comment]
@Anzge @ebakunin @ArileK I couldn't reproduce this issue in a new ngx-bootstrap version. Please try a new version or provide a reproduction of this issue.
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts

**Comment by Domainv** [comment]
Closes as outdated
