### ISSUE TITLE
Modal does not show up when on fullscreen mode on an element

### ISSUE THREAD

**Issue by peval27** [valor-software/ngx-bootstrap#2615]
Hi,

I am trying to open a modal dialog on the op of an HTML5 video element while it's fullscreen. It looks like it's now supported in Angular UI's bootstrap [https://github.com/angular-ui/bootstrap/issues/3686](https://github.com/angular-ui/bootstrap/issues/3686). 
Is there a roadmap for this?

Thanks

**Comment by IlyaSurmay** [comment]
This is actually related to #731 so I'm closing it.
