### ISSUE TITLE
feat(timepicker): add possibility of using Timepicker as a popup

### ISSUE THREAD

**Issue by FrancescoBorzi** [valor-software/ngx-bootstrap#2616]
Is it possible to use the Timepicker as a popup ? It would be consistent with the Datepicker popup.

**Comment by ghost** [comment]
here is the example - https://stackblitz.com/edit/ngx-bootstrap-nbtfel?embed=1&file=index.html

**Comment by FrancescoBorzi** [comment]
@svetoldo4444ka that's not what I meant. I meant a way to make it look like the Datepicker. So you have an input, you click on it and the popup will open.

However this is not really important and I personally no longer need it anyway.
