### ISSUE TITLE
Accordion: `isOpen` should be two-way bindable

### ISSUE THREAD

**Issue by steelsojka** [valor-software/ngx-bootstrap#2617]
The accordion-group component should be able to be bound 2 ways, since the `isOpen` state can be modified from inside the component and from outside it. The problem scenario occurs when `isOpen` is bound from outside the component and the user clicks on the accordion. Internally the state is changes, but the binding has not. The change is not communicated back to the parent component.

Instead of the internal state being modified it should emit through an output named `isOpenChange` with the new value. This will sync the states.

This will be a breaking change however since, currently, if the user clicks on a group when `isOpen` is bound they still toggle the open state. This change would only respect the bound value. It would require a 2 way data bind to produce the expected behavior.

**Comment by steelsojka** [comment]
The other alternative is to at least provide an output with the new state to be able to update the parent component. This would be the easiest and non breaking change.

**Comment by CodisRedding** [comment]
Is two-way binding of isOpen for the accordion implemented in 3.3.0? I'm using isOpen in the component and it will not collapse a group except for the first time.
