### ISSUE TITLE
Inline datepicker using the BsDatepickerModule 

### ISSUE THREAD

**Issue by younganakin** [valor-software/ngx-bootstrap#2625]
Hi,

I am using ngx-bootstrap version 1.9.3.
I have tried the examples and they work very well.
Was just wondering....is there an inline format without using input tag in html?

I wanted to use the new version because styling is easy to do.

**Comment by stemyke** [comment]
+1 I need the same use case :)

**Comment by nl-za** [comment]
+1 would also like to know how to do this?
Also, does dateDisabled still work with the new version?

**Comment by szbartnik** [comment]
+1 also think it will be useful

**Comment by GiuseppePiscopo** [comment]
There seems to be a ~~older~~ newer issue already tracking this feature: #2747 .
Although the title seems misleading, reading through it brings to the feature here requested.

**Comment by IlyaSurmay** [comment]
Closing as related to #2747
