### ISSUE TITLE
BsDatepicker position issue

### ISSUE THREAD

**Issue by vrudikov** [valor-software/ngx-bootstrap#2626]
Can't say something else :)
When the browser bottom boundary reached datepicker opens as it is designed, but it's very hard to pick something when you doesn't see it. My proposal is to add logic that will analyze bottom and top borders and datepicker position and will open component in appropriate state
![image](https://user-images.githubusercontent.com/493714/30318790-c00607d2-97b6-11e7-9877-a83ee0747904.png)

**Comment by pgeyman** [comment]
This is especially a problem if you use it in a modal form with a field near the bottom of the screen as you cannot then scroll the page down to see the picker.

**Comment by IlyaSurmay** [comment]
Closing as related to #2796 (datepicker is uisng the same position service).

**Comment by jrpatel1016** [comment]
Hello All,

I am trying to manage ngx-date picker in modal popup at the time of scrolling it's not move with date text box and it's opening always bottom of date picker text box.

Please let me know their any solution for this? or may i make "auto" placement of date picker in modal popup???

![datepicker-bug](https://user-images.githubusercontent.com/43035455/45157126-d1d46500-b1fd-11e8-9d94-2b1c09991b24.jpg)

**Comment by shahrishabhptechnical** [comment]
@jrpatel1016 - You can set container="" in your input field. It will work and position will not be absolute.

**Comment by jrpatel1016** [comment]
> @jrpatel1016 - You can set container="" in your input field. It will work and position will not be absolute.

Thanks for your solution Rishabh. i have tried this for single datepidcker it's working fine. but when i'll trying to use it in date range picker it's breaking ui of date range picker. please you can refer attached screen shot.

![issue-daterange](https://user-images.githubusercontent.com/43035455/49498462-28028400-f891-11e8-9c6b-b778aef697da.jpg)

**Comment by salim007x** [comment]
> @jrpatel1016 - You can set container="" in your input field. It will work and position will not be absolute.

I used this:
```html
<div class="input-group" id="datepickerContainer">
  <div class="input-group-prepend pl-2 pr-4 pre-div date-input d-flex align-items-center">
    <span class="badge badge-pill px-2">Date</span> 
    <span class="ml-3 selected-type ">
      <input type="text" class="form-control" id="date" name="date" placeholder="Select Date"
             [(ngModel)]="selectedDate" bsDatepicker
             [bsConfig]="{ isAnimated: true, dateInputFormat: 'DD-MM-YYYY'}" required
             [container]="'#datepickerContainer'"> <!-- Set container to the ID of the div containing the datepicker -->
    </span>
  </div>
</div>
``` 


and it is now displaying under the container carrying it
