### ISSUE TITLE
feat(datepicker): add possibility of showing only the year and month view

### ISSUE THREAD

**Issue by volodymyro-in6k** [valor-software/ngx-bootstrap#2627]
Hey, I'm looking for an option to switch view mode only to show year and month view.
Is it possible?
Thanks!!!

**Comment by eyerean** [comment]
You should add these properties:

```
[datepickerMode]="'year'"
[minMode]="'month'"
```

EDIT: Sorry that is for the traditional datepicker, have not tested on `bsDatepicker`!

**Comment by felixeu31** [comment]
Do we know when bsDatepicker will allow that feature????

**Comment by volodymyro-in6k** [comment]
Hello @IlyaSurmay, are you going to implement this feature in the nearest future?

**Comment by fegyi001** [comment]
+1 for adding that awesome feature to bsDatepicker!

**Comment by devlin3x** [comment]
+1 for introducing this feature.

**Comment by jakyle** [comment]
+1 for adding this sweet sweet feature

**Comment by dave0688** [comment]
+1 for adding it. Need it as well :)

**Comment by rrambaud** [comment]
+1. Very much needed ;)

**Comment by gauzpan** [comment]
+1 When will the datepicker mode be introduced, my project is stuck because of this.

**Comment by San13** [comment]
I am using ngx bootstrap version 2.0.2. Is the changes already include in it? if yes , please guide me how to use.

**Comment by nvuhung** [comment]
+1 for adding this feature.

**Comment by onrmrt** [comment]
+1

**Comment by lm-ml** [comment]
+1

**Comment by naveendb92** [comment]
I'm still unable to get the year mode only. Kindly anyone help me with this

**Comment by dafik** [comment]
temporary you can use my build of PR https://github.com/valor-software/ngx-bootstrap/pull/3354
until it will be merged

in package.json change:
"ngx-bootstrap": "2.0.2"
to:
"ngx-bootstrap": "dafik/ngx-bootstrap-dist",

**Comment by Pat-Lovelace** [comment]
Any news about your PR @dafik? I've just check your dist and works fine, the only objection would be your ngx-bootstrap version (2.0.2)

**Comment by TreesAndMountains** [comment]
When is this feature expected to be added ?

**Comment by andreyhideki** [comment]
+1

**Comment by andersonferrari** [comment]
+1

**Comment by sirgrigio** [comment]
+1

**Comment by unit147** [comment]
+1

**Comment by kubuntux** [comment]
+1

**Comment by iwantwin** [comment]
+1, need this very much!

**Comment by vitaliikobrin** [comment]
+1

**Comment by nok32** [comment]
+1

**Comment by jatin-Maini** [comment]
+1, need this PR soon

**Comment by teland94** [comment]
+1

**Comment by lupuvlad2000** [comment]
+1

**Comment by mishalmsb** [comment]
+1

**Comment by dsatpute** [comment]
+1

**Comment by Kfir-Miller** [comment]
+1

**Comment by petia83** [comment]
+1

**Comment by TheCodeOne** [comment]
+1

**Comment by peterpobe** [comment]
+1

**Comment by lachskardinal** [comment]
+1

**Comment by khashashin** [comment]
+1

**Comment by sakor** [comment]
+1

**Comment by viniciusvense** [comment]
+1

**Comment by fernandacarvalho** [comment]
+1

**Comment by nerophan** [comment]
+1

**Comment by bjcCin** [comment]
+1

**Comment by monica11** [comment]
+1, need it for very long. Please add it.

**Comment by mgpGit-zz** [comment]
what's the status on this? Would love this!

**Comment by mustafa-walkover** [comment]
This feature required in ngx-bootstrap. Please add it

**Comment by alexander-myltsev** [comment]
Is nightly build with that feature available somewhere?

**Comment by valorkin** [comment]
2 more PRs today and we will publish 3.1.3

**Comment by mohamedmallat40** [comment]
+1 very much needed
