### ISSUE TITLE
Dropdown mouseover trigger doesn't add 'open' class

### ISSUE THREAD

**Issue by pjarts** [valor-software/ngx-bootstrap#2628]
When using the defualt `click` trigger with a dropdown component the element with the dropdown directive toggles an `open` class name whenever the toggle element is clicked on. But when I set `triggers="mouseover"` that doesn't happen. I can see that the dropdown menu gets injected into the DOM, but it is not visible.

The `.dropdown` element doesn't get  an open class when the toggle is hovered in the example below.
```
<div class="dropdown" triggers="mouseover" dropdown>
  <a (click)="false" dropdownToggle>Hover me</a>
  <ul *dropdownMenu class="dropdown-menu">
    <li>foo</li><li>bar</li>
  </ul>
</div>
```
edit. Using Bootstrap 3

**Comment by pjarts** [comment]
```
<div dropdown class="dropdown" 
  triggers="mouseover" 
  [isOpen]="menu.open" 
  (isOpenChange)="toggleOpen($event)">
  <a (click)="false" dropdownToggle>Hover me</a>
  <ul *dropdownMenu class="dropdown-menu">
    <li>foo</li><li>bar</li>
  </ul>
</div>
```
It works when I add `[isOpen]` and `(isOpenChange)` attributes, controlling `menu.open` from the parent component as in your [Manual triggers example](https://valor-software.com/ngx-bootstrap/#/dropdowns). Maybe that's how it should be used?

**Comment by valorkin** [comment]
Nope, it seems to be an issue

**Comment by IlyaSurmay** [comment]
Closing as related to #2677 
For now there's a workaround
```
 <div class="btn-group" dropdown triggers="hover" 
  #dp="bs-dropdown">
  <ul *dropdownMenu class="dropdown-menu" role="menu" 
(mouseleave)="dp.hide()">
```
