### ISSUE TITLE
Typeahead option field method?

### ISSUE THREAD

**Issue by eyerean** [valor-software/ngx-bootstrap#2629]
The documentation states that `typeaheadOptionField` _"Supports nested properties and methods."_
How is a method used?
I tried this: 
`(typeaheadOptionField)="mapTypeaheadField($event)"`
and this:
`typeaheadOptionField="mapTypeaheadField($event)"`

having this:
```
mapTypeaheadField(event){
   console.log('ev', event);
   return 'name';
}
```

and my method is never called.

How can I have a method that returns the correct option field? I see the existing tickets that fixed this but no-one ever mentions how to implement this.

EDIT: Reading [#1434](https://github.com/valor-software/ngx-bootstrap/issues/1434) more carefully I believe there's not a real method that can be passed at the option field.

What I try to accomplish is something like that: 

`typeaheadOptionField="description.find(desc => desc.lang === {{currentLang}}).value"`

So every object in my array is of the format: 
```
{
   code: "string",
   description: [
    {lang: string,
     value: string
    }]
}
```
and I'm searching the `value` property.

If anyone can help it would be nice.

EDIT 2: I tried to make a pipe for it and realized what I was trying wouldn't work. Turns out I'm making a new list out of all the properties I want to use, but I still would like to know if there is (gonna be) a method implemented for the typeahead option field, or at least a better documentation over the existing cases.

**Comment by IlyaSurmay** [comment]
```
(typeaheadOptionField)="mapTypeaheadField($event)"
and this:
typeaheadOptionField="mapTypeaheadField($event)"
```
These bindings are incorrect:
`(typeaheadOptionField)` is binding to an event like `(click)`, 
`typeaheadOptionField` is string setter so you can't pass method as an argument. 
Correct form of binding  if you're using a method is `[typeaheadOptionField]="mapTypeaheadField()"`

**Comment by IlyaSurmay** [comment]
Closing for no updates.

**Comment by undeyio** [comment]
How would you display it as a pipe transformed string?
`{ firstName: 'John', lastName: 'Doe'`
So the typeaheadOptionField would read John Doe

**Comment by Mathachew** [comment]
A real world example would be great for this, because simply showing how to call the method, without giving any insight into how that method works, is useless. No parameter is passed to the method, so how exactly am I to take each object in the array and use it as I need? Like @underwnm noted, I need to concat two separate properties, sometimes it might be three. The only way I can resolve this is by creating a new property that combines the existing ones and use the new property in `typeaheadOptionField` instead of a method.

**Comment by rechl** [comment]
You object needs to have a function
` {
   firstName: 'John',
   lastName: 'Doe', 
  getName: function() { return this.firstName + ' ' + this.lastName}
}
`

Then you can call the function
`typeaheadOptionField="getName()"`
