### ISSUE TITLE
carousel.component.ts(103,11): error TS7030: Not all code paths return a value.

### ISSUE THREAD

**Issue by sschueller** [valor-software/ngx-bootstrap#263]
My tslint (angular2-seed) comes with up with the following error:

`node_modules/ng2-bootstrap/components/carousel/carousel.component.ts(103,11): error TS7030: Not all code paths return a value.`

It appears the function `getSlideByIndex` in `node_modules/ng2-bootstrap/components/carousel/carousel.component.ts` does not always return:

```
  private getSlideByIndex(index:number) {
    let len = this.slides.length;
    for (let i = 0; i < len; ++i) {
      if (this.slides[i].index === index) {
        return this.slides[i];
      }
    }
  }
```

**Comment by valorkin** [comment]
yeap, I am currently working on supporting
tslint and ng2lint

**Comment by valorkin** [comment]
same as #309 
closing this one
