### ISSUE TITLE
how to call modal from parent component using directives

### ISSUE THREAD

**Issue by megrajkiran09** [valor-software/ngx-bootstrap#2633]
There is one thread closed with #624. 
I am using latest version of ngx-bootstrap 1.9.1. can some one give demo for parent and child components using directives with 1.9.1 version. below are htmls for parent and child. 
Need logic for parent.component.ts and child.component.ts.Thank you

parent: <button type="button" class="btn btn-primary" (click)="staticModal.show()">Static modal</button>

Plunker:
http://plnkr.co/edit/RXMQFaC5au57zKib6OaP?p=catalogue

**Comment by IlyaSurmay** [comment]
Get access to a modal from child component using `@ViewChild(ModalDirective)`
Get access to child component from parent component using `@ViewChild(ChildComponent)`
Open a child modal from parent component like this `this.child.modal.show()`
This kind of chaining is not very handy as for me. Think about using modal service instead.

**Comment by megrajkiran09** [comment]
I was using modal service with component. But it is breaking for accessibility for modal title announcement.
I keep hear dialog document , dialog document followed by modal title dialog. I can not use aria-labledby attribute with service component. the dialog container already has role="dialog".
