### ISSUE TITLE
Sortable Component how to know when the item has been changed i tried to bind the OnChange and NgModelChane Event  but does not work

### ISSUE THREAD

**Issue by fahadrehman** [valor-software/ngx-bootstrap#2639]
i am Using the Following Code
 <bs-sortable [(ngModel)]="customAttributes"
                                             [itemTemplate]="itemTemplate"
                                             itemClass="sortable-item"
                                             itemActiveClass="sortable-item-active"
                                             placeholderItem="Drag here"
                                             placeholderClass="placeholderStyle"
                                             (onChange)="changed()"
                                             wrapperClass="sortable-wrapper"></bs-sortable>

Changed() {
        console.log("chnaged");
    }
but in console the event is not fired any help will be highly appreciated

**Comment by IlyaSurmay** [comment]
Hi! I just checked it here https://plnkr.co/edit/0CQJVZxXYUF1vpvNnUIl?p=preview and it works ok. There may be a mistake in your code (in template you're using `changed()`, but in component this function's name is `Changed`)

**Comment by IlyaSurmay** [comment]
Closing for no updates.
