### ISSUE TITLE
fix(drowpdown): Cannot display drowpdown menu

### ISSUE THREAD

**Issue by pedroR** [valor-software/ngx-bootstrap#264]
Hi,
I'm starting to learn Angular2 and I would Like to use ng2-bootstrap. For now I'm trying to dropdown menu.

I already installed with success ng2-bootstrap.

My dependencies on package.json are
`"dependencies": {
    "angular2": "2.0.0-beta.8",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "ng2-bootstrap": "^1.0.5",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "0.19.6",
    "zone.js": "0.5.15"
  },`

And on my DemoComponent I have the following code:

```
import {Component} from "angular2/core";
import {ROUTER_DIRECTIVES} from "angular2/router";
import {DROPDOWN_DIRECTIVES} from "ng2-bootstrap/ng2-bootstrap";

@Component({
    directives: [ROUTER_DIRECTIVES, DROPDOWN_DIRECTIVES],
    templateUrl: '../path/to/demo.component.html'
})

export class DemoComponent {
    private disabled:boolean = false;
    private status:{isopen:boolean} = {isopen: false};
    private items:Array<string> = ['The first choice!', 'And another choice for you.', 'but wait! A third!'];

private toggled(open:boolean):void {
        console.log('Dropdown is now: ', open);
    }

    private toggleDropdown($event:MouseEvent):void {
        $event.preventDefault();
        $event.stopPropagation();
        this.status.isopen = !this.status.isopen;
    }
}
```

On my template file I have the last example dropdown from the examples.

The button is displayed but when I click on it nothing happens.
Can someone points me to a direction to solve this? 

Thanks

**Comment by jayhahn** [comment]
I've also been struggling with the same problem since yesterday. I'm using angular2@2.0.0-beta.0 and ng2-bootstrap@1.0.0-beta.2.

No errors are being thrown.

**Comment by pedroR** [comment]
Yes, just like my case...no errors being thrown :/

**Comment by valorkin** [comment]
After one of ng2 updates it just stopped to work :(

**Comment by valorkin** [comment]
Without errors

**Comment by otabekgb** [comment]
Might be related to #188

**Comment by CarlCui-AI** [comment]
@pedroR Is it still an issue? I'm using beta 8 right now, and dropdown is working just fine.

**Comment by valorkin** [comment]
@CarlCui-AI it was working fine with beta.8 :)
but with beta.9,10,11,12 it doesn't
So it is need to be fixed :)

**Comment by CarlCui-AI** [comment]
@valorkin Gotcha. Still afraid of upgrading further. All the zone issues. ehhh

**Comment by Nolanus** [comment]
I experience that the "Button dropdown" dropdown on the [demo page](http://valor-software.com/ng2-bootstrap/#dropdowns) gets opened but closes right away (Chrome 49). In Safari and Firefox I do not see any dropdown, but I guess it's just "too fast" for the rendering.

Surprisingly I do not experience this behavior in any browser if I download the repo and run the example on the local machine. Then the "Button dropdown" example works as expected. Without the "isOpen" property all dropdowns work fine in all browsers (maybe that's a "workaround" for the time being).

**Comment by valorkin** [comment]
with beta.12 works again (ng2-bootstrap 1.0.8)
