### ISSUE TITLE
Is posible to use BsDatetime on modal?

### ISSUE THREAD

**Issue by orvelin** [valor-software/ngx-bootstrap#2645]
I am working with form on modal and I try to use bs modal but this never show, I  feel that the datepicker is under de modal.

**Comment by vrudikov** [comment]
You are correct. It's because of z-index in the CSS. I got the same issue. I think CSS should be tuned to make it happen. The same thing for me - i need bsDatepicker on modal form

**Comment by orvelin** [comment]
use this @vrudikov  https://www.primefaces.org/primeng/#/calendar

**Comment by vrudikov** [comment]
@orvelin Does it support reactive forms? Displaying on modals? Date objects in model?

**Comment by orvelin** [comment]
yes, it is supports all

**Comment by vrudikov** [comment]
@orvelin YES! AWESOME. The only thing - compatibility with Bootstrap :(

**Comment by vnazar** [comment]
As @vrudikov said, you can use something like this `/deep/ .bs-datepicker {
  z-index: 9999 !important;
}
` for make appear the datepicker pop-up over modal and fix at the moment this problem.

**Comment by orvelin** [comment]
@vrudikov  I added in my project and I didn,t have problems.

**Comment by NenadJovicic** [comment]
Same problem here. When i try to open BsDatePicker in modal, it is under modal

**Comment by NenadJovicic** [comment]
I added this in my styles.css and now it works
@vrudikov 
```
bs-datepicker-container {
  z-index: 9999 !important;
}
```

**Comment by valorkin** [comment]
this z-index staff is so stupid(
closing as duplicate, but we are aware of this ****
will be fixed in nearest releases
