### ISSUE TITLE
Warning, will become error in Angular 5.x

### ISSUE THREAD

**Issue by arsyed04** [valor-software/ngx-bootstrap#2646]
During angular-cli AOT build process:

12% building modules 21/25 modules 4 active ...e\release\assets\fonts\data-table.svg
Warning: Can't resolve all parameters for NgbModalRef in /node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-ref.d.ts: ([object Object], [object Object], [object Object], ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for NgbModalRef in /node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-ref.d.ts: ([object Object], [object Object], [object Object], ?). This will become an error in Angular v5.x

**Comment by IlyaSurmay** [comment]
NgbModalRef is not related to ngx-bootstrap. It's a part of ng-bootstrap, which is maintained by different team.

**Comment by ugurkoysuren** [comment]
@IlyaSurmay : Hey Ilya,

is there anything similar to the "NgbModalRef" in ngx-bootstrap. I'm trying to migrate from ng-bootstrap to ngx-bootstrap.

Thanks in advance.

**Comment by fchiumeo** [comment]
https://valor-software.com/ngx-bootstrap/#/modals#bs-modal-ref
