### ISSUE TITLE
How to adjust auto height when more text come in carousel

### ISSUE THREAD

**Issue by IntelligaiaVivek** [valor-software/ngx-bootstrap#2653]
Is there any way to adjust auto height when more text come in carousel.
![carousel](https://user-images.githubusercontent.com/23469188/30467797-efac5ea0-9a04-11e7-9111-459be593864a.png)

**Comment by IlyaSurmay** [comment]
Carousel slides have auto height by default, is it possible that your css is overwriting this property?
Could you create a plunkr/stackblitz with reproduction?
Starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

Also want to mention that general questions should be asked on StackOverflow https://stackoverflow.com/questions/tagged/ngx-bootstrap

**Comment by IlyaSurmay** [comment]
Closing for no updates.
