### ISSUE TITLE
Saving dates in UTC

### ISSUE THREAD

**Issue by dottodot** [valor-software/ngx-bootstrap#2656]
Not sure if this is a datepicker issue or more general Angular issue but the values I get from the datepicker are something like `Thu Sep 13 2018 00:00:00 GMT+0100 (BST)` but what is sent to my server is `2018-09-12T23:00:00.000Z`. Oddly it looks like the conversion to UTC is done by the Http module.

Is there anyway to set the datepicker to utc?

**Comment by valorkin** [comment]
this is done by JSON.stringify, just try to run `JSON.stringify({date: new Date()})`
a good thing about it is a standart so you can do `new Date("2017-10-02T14:25:05.353Z")`
and set this value to ngModel value related to datepicker
