### ISSUE TITLE
Using deprecated ngOutletContext, Angular 5.x will fail to build

### ISSUE THREAD

**Issue by MrBlaise** [valor-software/ngx-bootstrap#2658]
The `ngOutletContext` is deprecated in Angular 4 and will be removed in Angular 5. Please use
`ngTemplateOutletContext`

https://github.com/angular/angular/blob/master/CHANGELOG.md#deprecated-code

It is used here for example: https://github.com/valor-software/ngx-bootstrap/blob/31c5f62a48560d4372f0043241829a27e5f3deb6/src/sortable/sortable.component.ts (line 42)

Other files I found with ngOutletContext:

- src/typeahead/typeahead-container.component.html
- src/rating/rating.component.html
- src/sortable/sortable.component.ts

**Comment by MrBlaise** [comment]
Created a PR: #2659

**Comment by valorkin** [comment]
Thanks for, at the moment we are working on dropping support of ng 2, and moving to support ng v4 and v5
So PR is just in time :)

**Comment by Anoop-Goudar** [comment]
By replacing ngOutletContext to ngTemplateOutletContext in all files, it worked for me.

**Comment by MrBlaise** [comment]
@Anoop-Goudar That is exactly what this PR did, and it is already merged, so use the latest beta version.

**Comment by Anoop-Goudar** [comment]
@MrBlaise Thanks, I updated the package ngx-bootstrap to 2.0.0-beta.8

**Comment by its-Aman** [comment]
I was using ion2-calendar. It was using ngOutletContext. Replacing it with ngTemplateOutletContext worked for me.
