### ISSUE TITLE
Default position for "auto" placement in tooltip|popover|etc

### ISSUE THREAD

**Issue by cannontechnology** [valor-software/ngx-bootstrap#2661]
Feature: "auto" placement in tooltip|popover|etc. #1111 was closed but does not offer the flexibility that bootstrap does out of the box.

When "auto" is specified, it will dynamically reorient the tooltip. For example, if placement is "auto left", the tooltip will display to the left when possible, otherwise it will display right.

Is there any way to specify "auto bottom"... It appears that it now defaults to "auto right" which does not work in all use cases. In my case I have a very long popover that forces a scroll when opened near the bottom of the page. Having the flexibility to specify the default position i.e. "auto bottom" or "auto top" would be great.

**Comment by seiyria** [comment]
I have a similar case, where most of the time a tooltip for the same component works on the top. However, sometimes it will fall off the left side of the page. In these cases, I'd expect the tooltip to instead go to the right, to stay on the page.

**Comment by cannontechnology** [comment]
Here is a Plunker [https://plnkr.co/edit/sZOf2q?p=preview](https://plnkr.co/edit/sZOf2q?p=preview)

**Comment by cannontechnology** [comment]
I tried this with ng-bootstrap and it works as expected.  See this plunker http://plnkr.co/edit/QxmC4YyyY1ifnHM3vpGf?p=preview

**Comment by kondareddyyaramala** [comment]
Is there any update on this? Also I would like to know if there is any work around for this? Our use would be something like this
![2017-10-31_12-07-36](https://user-images.githubusercontent.com/17446574/32237966-593801fa-be34-11e7-9d8f-721d26de2bef.png)

**Comment by IlyaSurmay** [comment]
Closing as related to #2796
