### ISSUE TITLE
fix(modal): modal from component running both animations, closing then opening.

### ISSUE THREAD

**Issue by beto-rodriguez** [valor-software/ngx-bootstrap#2674]
I am using [Angular 4](https://angular.io/) and [bootstrap material](https://fezvrasta.github.io/bootstrap-material-design/), in my case I am loading my model via component.

When it opens, I get:
![bs bug](https://user-images.githubusercontent.com/10853349/30516320-388ad0e6-9b01-11e7-8e39-81d5d0fda70b.gif)

After debbuging the animations, I noticed it is running both, the closing and opening animation:

![bs bug debug](https://user-images.githubusercontent.com/10853349/30516348-f85cf00c-9b01-11e7-905e-89a4268d53e1.gif)

This also happens in your [site](https://valor-software.com/ngx-bootstrap/index-bs4.html#/modals) (at component), but for some reason, in your site the second animation hides the first one (closing anim).

Am I doing something wrong? this double animation does not exist in Bootstrap, at least I was not able to reproduce only with BS.

Reagards.

**Comment by fungjj92** [comment]
I am also seeing this exact behavior, but I am not using angular material. I am using a template modal.

"bootstrap": "^3.3.7",
"bootstrap-sass": "^3.3.7",
"ngx-bootstrap": "^1.9.3"

**Comment by IlyaSurmay** [comment]
Hi, could you reproduce this issue in plunkr/stackblitz?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by ghost** [comment]
There has been no response. That's why the issue was closed
