### ISSUE TITLE
ModalService using template not destroying components

### ISSUE THREAD

**Issue by s00pa** [valor-software/ngx-bootstrap#2675]
I've noticed that the when using a template for the modalservice, any contained angular components are not destroyed (NgOnDestroy never called). I've adjusted a plunkr from a previous issue's comment (I thought this pertained to that issue but I think it's different) to demonstrate this and also to show the issues it can cause in addition to the memory usage. You'll need to open the console log to see what I mean.

https://plnkr.co/edit/zM4deztXNaZzV8CdQXpA?p=preview

Thanks,
Sean

**Comment by johaven** [comment]
Any news about this bug ?

**Comment by valorkin** [comment]
Fixed witg #3179
