### ISSUE TITLE
There is no directive with "exportAs" set to "bs-modal"

### ISSUE THREAD

**Issue by mfemail8** [valor-software/ngx-bootstrap#2676]
Follow all introduce.
in app.module.ts 
 import { ModalModule } from 'ngx-bootstrap/modal';
 imports: [..., ModalModule.forRoot(), ...]
in html:
 <div class="modal fade" bsModal #staticModal="bs-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">...</div>

**Comment by mfemail8** [comment]
Solved.
All module link the html must import ModalModule

**Comment by ptrzyna** [comment]
Wait, what?!
