### ISSUE TITLE
fix(datepicker): definelocale without additional parameter causes exception

### ISSUE THREAD

**Issue by leomayer** [valor-software/ngx-bootstrap#2693]
`defineLocale(de.abbr)` causes an exception. Looking in the source-code `bs-moment/locale/locales.service.ts` its clear that
```

 export function defineLocale(name: string, config?: LocaleData): Locale {
   if (config === null) {

```
does not help cause `config` is `undefined` Not really a big issue - just thought it might help to report it.

**Comment by valorkin** [comment]
thanks :)
