### ISSUE TITLE
Will ng2-select be merged here? When will a searchable select be available?

### ISSUE THREAD

**Issue by MrBlaise** [valor-software/ngx-bootstrap#2695]
Hey there!

I am using ng2-select which seems to be dead and I read somewhere that you guys working on migrating that codebase here. Will this happen in the near future and if not is there a good alternative?

Thanks!

**Comment by 7185** [comment]
See https://github.com/valor-software/ng2-select/issues/769#issuecomment-326256640
It looks like it's planned, but it probably won't happen before Angular 5 release.

I'm using ng2-select too, but I managed to create something very similar with the `Typeahead` module on my project (I needed to be able to fetch my data through http).

So most of the codebase is actually already here and the best alternative is probably to just use the `Typeahead` module for now.

**Comment by valorkin** [comment]
Yep, it's planned but first we will polish v2 a bit

**Comment by valorkin** [comment]
I am planing to release v2 in december, v2.1 will have select component
