### ISSUE TITLE
Any plan to add support of most used locales in datepicker?

### ISSUE THREAD

**Issue by Swapnil-kumbhar** [valor-software/ngx-bootstrap#2696]
It will be really helpful, if you provide support for most of the locales.
We are looking for urgent support for Slovak ('sk') locale.

**Comment by valorkin** [comment]
@Swapnil-kumbhar you don't need to wait, just check migrate your locale from moment.js to our format,
it's easy and nice reason for small PR

**Comment by valorkin** [comment]
check #2700 for sample
