### ISSUE TITLE
2 modals as components, how to know which one is closed?

### ISSUE THREAD

**Issue by NenadJovicic** [valor-software/ngx-bootstrap#2698]
I want to use 2 different modals as component (ModalComponent1 and ModalComponent2) in same Component (ModalOpenersComponent). I can open them with 
`
bsModalRef: BsModalRef;    
this.bsModalRef = this.modalService.show(ModalComponent1);
`
and
`    this.bsModalRef = this.modalService.show(ModalComponent2);
`
but how to know which one is closed?
Because I want to use method1() in ModalOpenersComponent when ModalComponent1 is closed, and method2() when ModalComponent2 is closed.

And other that could be good, issue alreade made for it, to pass some data after close.

Maybe you should check how [Angular Material 2 Dialog](https://material.angular.io/components/dialog/overview) works like.

**Comment by chubbard** [comment]
Don't reuse this.bsModalRef.  Make them separate references then it's easy to check each reference for null (oh and set them to null when you close respective modals).  Then it's simple.
