### ISSUE TITLE
angular2 is not a dev dependencies?

### ISSUE THREAD

**Issue by ludohenin** [valor-software/ngx-bootstrap#27]
IMO angular2 should be a dependency of this package (not dev one). But of course not distributed :)

**Comment by valorkin** [comment]
https://github.com/valor-software/ng2-bootstrap/blob/master/package.json#L32-L34
what?

**Comment by valorkin** [comment]
and https://github.com/valor-software/ng2-bootstrap/issues/24

**Comment by ludohenin** [comment]
Angular2 needs to be defined as a dependencies (because it's the case) but the package should not have a `node_module/angular2` sub-folder. With npm 3, installation is flat now, I though this node_module folder what intentionally added by you in the distributed package.
If this node_module folder is created at install time, then the question is why (considering npm 3) ?

**Comment by valorkin** [comment]
npm 3 is still not so widely used
and to be honest much slower than npm 2 for now
so it could be or in prod deps and it will be in ng2-bootstrap/node-modules for npm2
and it will be fine for npm3 as flat one

**Comment by ludohenin** [comment]
lets keep as it is.

**Comment by valorkin** [comment]
@ludohenin may be I should add ng2 and all required stuff to `peerDependencies`?
in 2nd it will be installed automaticaly
in 3rd it will raise a warning that it is needed
