### ISSUE TITLE
Reset daterangepicker to default value

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#2701]
Scenario:
We use ngx-bootstrap 1.9.3 (the newest one at this point), and we use new datepicker component (https://valor-software.com/ngx-bootstrap/#/datepicker), not the old one.
We have a date filter that is implemented using bsDaterangepicker. User selects date range, date range gets send to the back end, back end returns some records that correspond to the date range. Problem is implementing reset option for the applied filter. 
We need to set the component to the initial state. Is there a way to do that? If not, can it be implemented?
Note: Setting the _bsValue to something does not work for us, we need the component to be set like it is initially when page is (re)loaded.

Best regards,
Jo

**Comment by valorkin** [comment]
@angularJo you can set bsValue or ngModel value related to datepicker, to previous value
just store it somewhere

**Comment by amorenew** [comment]
@valorkin 
it is not working for me
```
 onRangeValueChange(value: Date[]) {
        this.bsValue=void 0;
  }
```

but if add delay like on alert close it works

```
onAlertClosed(dismissedAlert: AlertComponent) {
    this.bsValue=void 0;
  }
```

**Comment by amorenew** [comment]
I added `setTimeout(()=>this.bsRangeValue=void 0, 0);
`and it works

**Comment by valorkin** [comment]
changing value in the same change detection loop will not give an effect,
triggering change detection cycle should help

**Comment by superliza** [comment]
@amorenew where to send the function call??

**Comment by amrboxit4me** [comment]
@superliza I don't remember that code
