### ISSUE TITLE
Datepicker Locale en-gb does not work

### ISSUE THREAD

**Issue by markpritchett** [valor-software/ngx-bootstrap#2702]
See screenshot below:

https://valor-software.com/ngx-bootstrap/#/datepicker#locales
![image](https://user-images.githubusercontent.com/1267889/30659621-440050e4-9e36-11e7-9f9b-f4842c422239.png)

It should be **20/09/2017**.

**Comment by pgeyman** [comment]
Related issues: #2622, #2694, #2699

**Comment by valorkin** [comment]
yes, duplicate of #2622 and #2694 
fixed with #2360

**Comment by cyberabis** [comment]
Hi, which release version should I pull to get this fix? 

Even in 2.0.0-beta.6, only on clicking the dates the format is right. It's incorrect when the initial value is set or when typing into the input.

**Comment by valorkin** [comment]
Post formatting user input is not part of current implementation, you can do a feature request for it

**Comment by m1t0k** [comment]
Works in 2.0.0-beta.10, but doesn't work in 2.0.0-rc.0.
