### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by khoying** [valor-software/ngx-bootstrap#2703]
First, thank you for your work on ngx-bootstrap.  I am new to Angular and have found it a great complement to Angular and it has been very useful to me.

I am working on a new project for our company and we are a considerable ways out yet to a production deployment.  I had been using the release branch of the code. However, there are some capabilities and upgrades in the v2.x-beta branch that I have needed.  So I am currently using it.  

I am basically gambling that you will be releasing this branch before we do.  I was wondering if you have some rough time lines on that which you could share?  

Our project also has an upcoming need for a DatePicker.  I would like to use the one in ngx-bootstrap.  From following this board, it appears that some ongoing work is being done to fix some issues and get up to par for the v.2.x-beta branch.  I was wondering if you had a rough estimate when that might be available?

Thank you!

**Comment by valorkin** [comment]
v2 beta will be released in 1-2 weeks from now,
just in case we are using our betas in production env without issues

I am holding beta-s to perform several breaking changes...

**Comment by khoying** [comment]
Terrific!  Thank you!
