### ISSUE TITLE
Angular 4, ngx-bootstrap 1.9.3 - Template parse warnings

### ISSUE THREAD

**Issue by kambizalipour** [valor-software/ngx-bootstrap#2704]
I'm getting the following warning:

Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///node_modules/ngx-bootstrap/alert/alert.component.d.ts.AlertComponent.html

**Comment by 7185** [comment]
https://github.com/valor-software/ngx-bootstrap/issues?q=is%3Aissue%20Template%20parse%20warnings

**Comment by Martin-Luft** [comment]
Please search for same issues before opening a new one...

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.X.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.4" or npm install ngx-bootstrap@next
