### ISSUE TITLE
Angular 4 alert template warning

### ISSUE THREAD

**Issue by daviatorstorm** [valor-software/ngx-bootstrap#2710]
`
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template [ngIf]="!isClosed"><div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""):ng:///AlertModule/AlertComponent.html@1:0
`
Tools info:
```
aspnet-prerendering: 3.0.1
webpack: 2.5.1
angular: 4.4.1
@ngtools/webpack: 1.7.1
ngx-bootstrap: 1.9.3
```

**Comment by fchiumeo** [comment]
ngx-bootstratp@1.9.3 support angular 2 and angular 4
ngx-bootstrap@next suport only angular 4 and not warning template

**Comment by Martin-Luft** [comment]
Please search for same issues before opening a new one...

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.X.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.4" or npm install ngx-bootstrap@next

**Comment by daviatorstorm** [comment]
Thanks for answer.
I'll be carefully searching next time.
