### ISSUE TITLE
BsDatePicker is unusable if minDate/maxDate range doesn't include current month.

### ISSUE THREAD

**Issue by chubbard** [valor-software/ngx-bootstrap#2711]
If you set the minDate and maxDate to a date range that doesn't overlap with the current month (for example, a birthday for which you must be 18 or older) you can't scroll back to the valid date range because scrolling between months is disabled.  I think there are 2 issues to consider.  One that the months scrolls are disabled if you are in months that aren't included in the date range which renders the controls unusable.  However, a related issue is that when the control is opened it defaults to show the current month instead of something in the date range, and there are no configuration settings for setting what date to start by default.

**Comment by NenadJovicic** [comment]
you can create some selectedDate that is in your range and bind it with ngModel into datepicker
automatically, when you select some date, it will be binded to your selectedDate
only problem here is if you don't want to have selected date on start

**Comment by chubbard** [comment]
That IS exactly the problem.  I need it to be empty to start.  They are picking a birthday so there is no good default here.

**Comment by valorkin** [comment]
@chubbard view date is in the roadmap

**Comment by valorkin** [comment]
@chubbard view date is in the roadmap
