### ISSUE TITLE
Datepicker stays disabled

### ISSUE THREAD

**Issue by awallat** [valor-software/ngx-bootstrap#2712]
I am using a reactive form for displaying the new datepicker: 

> <input type="text" bsDatepicker formControlName="date" ...>

When I call the disable command on the complete form instead of only the input, then the datepicker is correctly disabled. But when I do call enable on that form again, then the datepicker stays disabled. It should however be enabled again like all other "normal" inputs do.

**Comment by IlyaSurmay** [comment]
It would be nice to see a plunkr or stackblitz example with reproduction of this issue.
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/angular-xsjgdb

**Comment by awallat** [comment]
I created a demo here: https://stackblitz.com/edit/angular-79pucx?file=app%2Fapp.component.html

**Comment by IlyaSurmay** [comment]
Ok, I see it. The will be fixed in the next release.
