### ISSUE TITLE
BsDatepicker not showing

### ISSUE THREAD

**Issue by arjayfuentes** [valor-software/ngx-bootstrap#2716]
I used BsDatepickerModule in my application but it is not showing. I followed all the instructions in the documentation but still no luck. I don't know what's wrong but I know I properly imported it in my application.  

```
`import { BsDatepickerModule } from 'ngx-bootstrap/datepicker';

@NgModule({
	imports: [
        BsDatepickerModule.forRoot()`
```

`	<label>Date Effective</label>
							<input type="text"
							[minDate]="minDate"
							[maxDate]="maxDate"
							#dp="bsDatepicker"
							bsDatepicker>`

as well applying the style in angular-cli.json file.

` "styles": [
        "../node_modules/ngx-bootstrap/datepicker/bs-datepicker.css",
        "styles.css"
      ],`

I'm in angular 2.3
`"dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",`

**Comment by juliancuni** [comment]
Try to import the BsDatepicker style on the style.scss
`@import '../node_modules/ngx-bootstrap/datepicker/bs-datepicker.css';`

**Comment by IlyaSurmay** [comment]
It would be nice to see a plunkr or stackblitz example with reproduction of this issue.
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/angular-xsjgdb

**Comment by spraggler** [comment]
Same issue as above. Done everything according to docs but it doesn't pop up and they are no errors in the console.

See StackBlitz below:
[angular-xsjgdb.zip](https://github.com/valor-software/ngx-bootstrap/files/1404403/angular-xsjgdb.zip)

https://angular-xsjgdb.stackblitz.io

**Comment by IlyaSurmay** [comment]
@spraggler your stackblitz is just copied from our template without any changes.

**Comment by valorkin** [comment]
Hey, I am grooming issues, when reproducible sample with issue will be provided, issue will be reopened

**Comment by nukec** [comment]
same issue here... can't see anything and all included as op mentioned.

**Comment by valorkin** [comment]
We need something reproducible, to track down issue and add it to socs

**Comment by valorkin** [comment]
Docs*

**Comment by nukec** [comment]
@valorkin in my case i put BsDatepickerModule.forRoot() in global app.module.ts, but then I forgot to import same module inside of child module as well. My mistake.

Btw whoever has issues here is a playground plunkr with proper imports and proper module names:
https://plnkr.co/edit/jOqnKkIVNWD63wjSEbuK

**Comment by valorkin** [comment]
This is not workaround, this is how angular DI works. Services (providers) have global visibility and should be imported once (forRoot), but components visibly is scoped to module

**Comment by alex-pokolenko** [comment]
This was related to `z-index` in my case. If the imports are correct, check out the last nodes of the body as the datepicker will be attached there.

**Comment by emrekunt** [comment]
you need to import BrowserAnimationsModule to app.module.ts too.

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

**Comment by basilinjoe** [comment]
> Try to import the BsDatepicker style on the style.scss
> `@import '../node_modules/ngx-bootstrap/datepicker/bs-datepicker.css';`

can't find the css file, instead i found the scss file and am using sass. what to do ?

**Comment by juliancuni** [comment]
@basilinjoe
> > Try to import the BsDatepicker style on the style.scss
> > `@import '../node_modules/ngx-bootstrap/datepicker/bs-datepicker.css';`
> 
> can't find the css file, instead i found the scss file and am using sass. what to do ?

That's exactly what I have wrote. Try to import the BsDatepicker style on the style.scss
Browse node_modules/ngx-bootstrap/datepicker, check if bs-datepicker.css exist, then edit style.scss and put this row
@import '../node_modules/ngx-bootstrap/datepicker/bs-datepicker.css';

PS: my comment witch you referring is 2 years old. I guess things have changed since that time. Anyway give it a try.

**Comment by basilinjoe** [comment]
> @basilinjoe
> 
> > > Try to import the BsDatepicker style on the style.scss
> > > `@import '../node_modules/ngx-bootstrap/datepicker/bs-datepicker.css';`
> > 
> > 
> > can't find the css file, instead i found the scss file and am using sass. what to do ?
> 
> That's exactly what I have wrote. Try to import the BsDatepicker style on the style.scss
> Browse node_modules/ngx-bootstrap/datepicker, check if bs-datepicker.css exist, then edit style.scss and put this row
> @import '../node_modules/ngx-bootstrap/datepicker/bs-datepicker.css';
> 
> PS: my comment witch you referring is 2 years old. I guess things have changed since that time. Anyway give it a try.

Sorry

**Comment by Shyamasish** [comment]
> you need to import BrowserAnimationsModule to app.module.ts too.
> 
> import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

This resolved my issue..thanks a lot

**Comment by bojidaryovchev** [comment]
it also wont open if you pass something that is NOT a valid date to the [bsValue] input - no errors shown - it just doesnt open.. hopefully that helps, it was my problem

**Comment by bojidaryovchev** [comment]
another thing I just found out is that THE ONLY WAY to set the [bsValue] is to set is as a component variable, if it is a get property or something thats not initialized with the component variables it simply doesnt show.. this is a MAJOR issue, is it gonna be fixed any time soon?

**Comment by nehamattani** [comment]
I was facing the same issue with angular 8. Please downgrade and restrict your ngx-bootstrap version to 3.0.0

**Comment by EfratVanso** [comment]
> you need to import BrowserAnimationsModule to app.module.ts too.
> 
> import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

it worked for me. tnx

**Comment by cattlleya** [comment]
> This was related to `z-index` in my case. If the imports are correct, check out the last nodes of the body as the datepicker will be attached there.

Thanks, it solved my issue.

**Comment by ronnyknight45** [comment]
Why is `BrowserAnimationsModule` even required? This adds unnecessary bundle size when the app isn't even using animations.

Using ngx-bootstrap is a real pain I feel. There is no clear cut way to add individual components. We have to add the entire library. Now, the `BrowserAnimationsModule` is required even if the app is not using animations. Devs are far better off using something else.

**Comment by sauliko** [comment]
> This was related to `z-index` in my case. If the imports are correct, check out the last nodes of the body as the datepicker will be attached there.

Can you give and example ? I have popup window as chiled component and my datepicker not opening properly after i saw your comment i checked and its back on popup window

**Comment by Caiwen612** [comment]
Sorry about that, What is the solution for this issue?
