### ISSUE TITLE
bsdatepicker isopen is not working

### ISSUE THREAD

**Issue by cssuresh90** [valor-software/ngx-bootstrap#2717]
hi 

bsdatepicker isopen is not working oniline 
<input class="form-control" placeholder="Datepicker" bsDatepicker [minDate]="minDate" [maxDate]="maxDate" #dp="bsDatepicker" [isOpen]="false">

**Comment by cssuresh90** [comment]
hi all

bsdatepicker isopen is not working on inline
<input class="form-control" placeholder="Datepicker" bsDatepicker [minDate]="minDate" [maxDate]="maxDate" #dp="bsDatepicker" [isOpen]="false">

**Comment by IlyaSurmay** [comment]
Duplicate of #2714
