### ISSUE TITLE
Getting error " SyntaxError: Unexpected token < at eval (<anonymous>) at SystemJSLoader.__exec" 

### ISSUE THREAD

**Issue by sonambhatia** [valor-software/ngx-bootstrap#2718]
Hi ,

I have tried adding this library ngx-bootsrap after installing it i am getting this error again and again , i tried to fix it in systemconfig.js and package .json but no resolution found, please help me . It's little urgent i cant able to include this library to get my result like any  modal pop up, date time picker,carousel etc.

package.json :
  "dependencies": {
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@angular/router": "4.0.2",
    "@ngrx/core": "^1.2.0",
    "@ngrx/store": "^2.2.3",
    "angular-in-memory-web-api": "~0.2.4",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "ng2-carouselamos": "file:node_modules/ng2-carouselamos",
    "ng2-bootstrap": "1.3.0",
    "rxjs": "5.0.1",
    "systemjs": "0.19.40",
    "zone.js": "^0.7.4"
  }
systemconfig.js:

  var map = {
        'app': 'app', // 'dist',
        '@angular': 'node_modules/@angular',
        'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
        'rxjs': 'node_modules/rxjs',
        // ng2-bootstrap
        'moment': 'node_modules/moment',
        'ng2-bootstrap': 'node_modules/ng2-bootstrap',
    };

    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app': { main: 'main.js', defaultExtension: 'js' },
        'rxjs': { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
        // ng2-bootstrap
        'ng2-bootstrap': { format: 'cjs', main: 'bundles/ng2-bootstrap.umd.js', defaultExtension: 'js' },
        'moment': { main: 'moment.js', defaultExtension: 'js' },

**Comment by valorkin** [comment]
In documentation, there special section in getting started about system.js.
Move to angular cli if you are just starting
