### ISSUE TITLE
BSDatepicker - unable to initialise picker date without "selection" event being called

### ISSUE THREAD

**Issue by pgeyman** [valor-software/ngx-bootstrap#2719]
Initialising the date picker popup with a value using bsValue causes the bsValueChange event to occur.

This means that any code listening for the selected value is run when the picker is initialised with a date. I don't think this is the correct behaviour. I think that it should be possible to initialise the picker with a date without it becoming the selected date (or the date appearing in the input)

**Comment by valorkin** [comment]
This is correct behavior, consider using ng model and ngModelChange , bs value change is an event bus allowing to grab even first change

**Comment by pgeyman** [comment]
@valorkin How can I initialise the popup with a date (eg. todays date) and then only get the value selected when not in a form? I cannot use ngmodel and ngModelChange when the directive is not on a form field.
