### ISSUE TITLE
feat(popover): add popover component

### ISSUE THREAD

**Issue by secynic** [valor-software/ngx-bootstrap#272]
I didn't see an open issue for this. Obviously tooltip needs work first.

**Comment by marcalj** [comment]
As tooltip is done, is it easy to implement now?

**Comment by allisonmccarthy** [comment]
Does anyone know if the popover component is being developed atm or anytime soon?

**Comment by sky-coding** [comment]
Sorely missing this component. The alternatives don't seem to work well with bootstrap 4.

**Comment by erashu212** [comment]
@sky-coding : You can try `
npm i ng2-bootstrap-popover` for time being.

Thanks,

**Comment by steveburkett** [comment]
hi there.  @erashu212 i followed the instructions in readme, but get the BroccoliTypeScriptCompiler error: Cannot find module 'ng2-bootstrap-popover'.

**Comment by erashu212** [comment]
@steveburkett : Is it possible for you to create plunker for the same. So I can help you out.

**Comment by steveburkett** [comment]
@erashu212  http://plnkr.co/edit/HBxJBJcWGSiYapg8pZeM?p=preview.  i (seemingly) got past the module not found by prefixing the system-config w/ 'dist'.  but it still doesnt work :(

**Comment by erashu212** [comment]
Hi @steveburkett ,

Can you try this [plunker](http://plnkr.co/edit/vwaESQ?p=preview)

**Comment by DethAriel** [comment]
@valorkin are you accepting PRs for this?

**Comment by jamiec1234** [comment]
Any movement on this?

**Comment by DethAriel** [comment]
Not to my knowledge, no

**Comment by valorkin** [comment]
BTW it is implemented, and will be published today, but without docs
Take a look on source code(it is documented )
https://github.com/valor-software/ng2-bootstrap/blob/feat-new-component-loader/src/popover/popover.directive.ts

**Comment by valorkin** [comment]
Next week release will have huge docs update

**Comment by yossely** [comment]
Hi @valorkin! 
I see the popover component is already available in the _github_ repository and that's great! 
I would like to know when will this new feature be available in the **npm** package?

**Comment by valorkin** [comment]
I can drop beta release,  but docs will be later this week

**Comment by valorkin** [comment]
Added and published, docs on a way
