### ISSUE TITLE
Inline Datepicker

### ISSUE THREAD

**Issue by navneetgarggate6** [valor-software/ngx-bootstrap#2720]
I am using latest code and I would like to know how we can display Inline Datepicker as explained in the old tab?

**Comment by IlyaSurmay** [comment]
Old datepicker doesn't support inline mode, you can only use it as a component  like this `<datepicker [(ngModel)]="date"></datepicker>`. For more info check documentation of datepicker, switch to the `old` tab and look at demo component code.

**Comment by navneetgarggate6** [comment]
I am not using old code I have latest Datepicker setup and I followed the document as well

**Comment by 555ea** [comment]
@IlyaSurmay Are we able to use the new datepicker + daterangepicker without popup, just as old one, but with new features and styles?

**Comment by GiuseppePiscopo** [comment]
@555ea you might want to follow other related issues that are still open: #2625 , #2747
