### ISSUE TITLE
Modal directive: Append to body

### ISSUE THREAD

**Issue by MerlinXLL** [valor-software/ngx-bootstrap#2724]
Hello everyone,

while a modal created through the service is appended to the body, I wish for the possibility to do this with the direcive-method, too.
If any parent element of the modal has the css-property `transform`, the modal is aligned to the said element, and not the viewport. 

For example, adding

`transform: translate(10px, 10px);`

to any parent-element of a modal, results in the following:

![grafik](https://user-images.githubusercontent.com/32279991/30831937-a21d02fa-a249-11e7-9505-ad96bd409d57.png)

As a bonus, the backdrop is in front of the modal, so the modal can't be closed. This bug could be avoided if we had the possibility to append the modal to the body.

Keep up the great work!

**Comment by IlyaSurmay** [comment]
You can switch to using ModalService, it always appends modals to body
