### ISSUE TITLE
Datapicker and Timepicker allow unvalid values

### ISSUE THREAD

**Issue by FrancescoBorzi** [valor-software/ngx-bootstrap#2726]
It would be nice if when the user leaves a field of Datapicker or Timepicker with wrong value, the field automatically resets to empty.

Datapicker already does it under some circumstances (to be precise, it does it when the calendar is still open), however it is still possible to hack it by closing the calendar first and then type something in the field.

Timepicker allow any kind of unvalid values under any circumstances. So you can fill it with numbers greater than 23 or even characters.

**Comment by valorkin** [comment]
I am not sure that view components should have such powers

**Comment by IlyaSurmay** [comment]
I think this kind of validation should be done from the app itself. You can bind to `ngModelChange` and do something when it returns `null`.

**Comment by timaxapa** [comment]
@IlyaSurmay 
I use reactive forms and I don't want to add redundant checks. It will be more comfortable to correcting user inputs than use callbacks or additional valueChanges subscriptions.
Another one issue - inputs don't clear if model becomes null [Plunker](https://plnkr.co/edit/qbYuhRy4XSedgkbN9T08?p=preview)
Sorry, but these issues are my roadblocks now. Thanks.

**Comment by valorkin** [comment]
@timaxapa time\date pickers are UI components, and should no include validation rules
on another hand some validation options could be provided additionally from the box,
but not related to date\time pickers

about setting null it's known issue
