### ISSUE TITLE
Error when compiling (npm "Start" script)   "version": "2.0.0-beta.5", on MAC 10.12.6 Using Netbeans 8.2

### ISSUE THREAD

**Issue by rls1955** [valor-software/ngx-bootstrap#2728]
Have seen this error or similar before with other versions but I could still compile. Have deleted the node_modules and retried npm Install and npm Start script more than once.
Node.js & npm versions:

$ node -v
v8.5.0
 npm -v
5.3.0

Here is the reference to "tabs" in index.ts:
import { TabsModule } from 'ngx-bootstrap/tabs';

ERROR in Error: Error encountered resolving symbol values statically. Could not resolve ngx-bootstrap/tabs relative to /Users/----/Downloads/ngx-bootstrap-development-9/demo/src/app/api-docs/index.ts., resolving symbol NgApiDocModule in /Users/-----/Downloads/ngx-bootstrap-development-9/demo/src/app/api-docs/index.ts, resolving symbol NgApiDocModule in /Users/-----/Downloads/ngx-bootstrap-development-9/demo/src/app/api-docs/index.ts

Below is the npm Install output:

"/bin/bash" "-lc" "\"/usr/local/bin/npm\" \"install\""
npm WARN deprecated chalk@2.0.1: Please upgrade to Chalk 2.1.0 - template literals in this version (2.0.1) are quite buggy.
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated

> fsevents@1.1.2 install /Users/------/Downloads/ngx-bootstrap-development-9/node_modules/fsevents
> node install

[fsevents] Success: "/Users/------/Downloads/ngx-bootstrap-development-9/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.5.3 install /Users/--------/Downloads/ngx-bootstrap-development-9/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/-------/.npm/node-sass/4.5.3/darwin-x64-57_binding.node

> wd@1.4.1 install /Users/------/Downloads/ngx-bootstrap-development-9/node_modules/wd
> node scripts/build-browser-scripts

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/-------/Downloads/ngx-bootstrap-development-9/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> sauce-connect-launcher@1.2.2 postinstall /Users/------/Downloads/ngx-bootstrap-development-9/node_modules/sauce-connect-launcher
> node scripts/install.js || nodejs scripts/install.js

> node-sass@4.5.3 postinstall /Users/-----/Downloads/ngx-bootstrap-development-9/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/-----/Downloads/ngx-bootstrap-development-9/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine
added 1705 packages in 32.589s
Done.
npm notice created a lockfile as package-lock.json. You should commit this file.

**Comment by IlyaSurmay** [comment]
If you're building ngx-bootstrap on local machine, you should follow this doc https://github.com/valor-software/ngx-bootstrap#how-to-build-lib-for-development
Looks like you haven't linked lib to node_modules. Try `npm run link`, and if this doesn't help, try to follow the steps from our doc, link is above.
