### ISSUE TITLE
Sending data to modal through service

### ISSUE THREAD

**Issue by carlhussey** [valor-software/ngx-bootstrap#2733]
I see in the examples that you can pass data to the model component through the service by doing something like `this._bsModalRef.content.name='test';` 

When I try to access this data however, I am always told that content is undefined. 

Is there a way to pass data and have it available in the `ngOnInit` method so that I can use data thats passed in my model logic?

Currently I have to use behavior subjects and have my model subscribe to them so I can pass it data to use which is a pain.

Am I missing something here?

**Comment by IlyaSurmay** [comment]
Hi! We have this in plans, currently fix is waiting for merge here #2600

**Comment by carlhussey** [comment]
Ah thank you, looking forward to it!

**Comment by 3DDario** [comment]
This is a small workaround and should get your work done
```
ngOnInit() {
    setTimeout(() => {
        console.log(this.name)
        // etc
      }, 1);
}
```

Obviously it is not the best solution but it is simple and it works
