### ISSUE TITLE
Datepicker week start 

### ISSUE THREAD

**Issue by aakldey** [valor-software/ngx-bootstrap#2735]
In some countries week starts at monday, not sunday. It would be nice to get a configuration for this

**Comment by userAbhi** [comment]
You can do this by changing dow:0 to dow:1 in
ngx-bootstrap\chronos\locale\locale.defaults.js. in file.

eg:
export var defaultLocaleWeek = {
//dow: 0
dow: 1,
// Sunday is the first day of the week.
doy: 6 // The week that contains Jan 1st is the first week of the year.
};
