### ISSUE TITLE
Datepicker not working inside of Modal Window

### ISSUE THREAD

**Issue by nikunp** [valor-software/ngx-bootstrap#2736]
When using the Datepicker input inside of a modal window the datepicker does not show up in the modal window it shows up inside how would I go about solving this issue?

**Comment by HugoMarteau** [comment]
Hi,
It is caused by the z-index, it has already been notified and a fix will come soon.
By now you can set manually the z-index of the date picker in your styles.css
`/*Date picker container*/
bs-datepicker-container {
    z-index: 3000;
}`

**Comment by valorkin** [comment]
@EvilAlexei @IlyaSurmay what we gonna do?

**Comment by valorkin** [comment]
according to bootstrap.css logic (tooltips, dropdowns, etc.)
datepicker should be z-index: 1080

**Comment by MeMeMax** [comment]
This is still a topic. I am getting the error with version "ngx-bootstrap": "^2.0.4"

**Edit:** Sorry it works with the additional css file which I was missing. But is there a reason why this is so complicated? In most other Modules you just import the element you want and everything is deliviered within it.

**Comment by EvilAlexei** [comment]
Hello @MeMeMax !

I guess you speak about datepicker css file? You need it because there are no datepicker component in original bootstrap and there no styles in bootstrap.css for datepicker. 
Just to be sure, you can find additional info [here](https://valor-software.com/ngx-bootstrap/#/datepicker#basic)
Anyway it's a good point about styles inside component without additional files, we will discuss it :)

**Comment by nivajshakya** [comment]
$(function() {
    $("body").delegate(".datepicker", "focusin", function(){
        $(this).datepicker();
    });
});

**Comment by jrpatel1016** [comment]
Hello All,

I am trying to manage ngx-date picker in modal popup at the time of scrolling it's not move with date text box and it's opening always bottom of date picker text box.

Please let me know their any solution for this? or may i make "auto" placement of date picker in modal popup???

![datepicker-bug](https://user-images.githubusercontent.com/43035455/45157126-d1d46500-b1fd-11e8-9d94-2b1c09991b24.jpg)

**Comment by MajidPro320** [comment]
Hello, use this code 
`$("#lastModifiedDateFilter").daterangepicker({
    parentEl: "#divChooseDossier .modal-body"            
})`

https://stackoverflow.com/questions/17694456/jquery-daterangepicker-not-working-in-modal

**Comment by toof06** [comment]
hello i resolve it with 
        .datepicker{
            z-index: 1100 !important;
        }     
        #ui-datepicker-div {
            width: 30% !important;
        }

**Comment by shubhjhawar** [comment]
My calendar does not show up in angular, even when I added z-index like asked above.
