### ISSUE TITLE
bug(accordion): Click accordion header, then click toggle button, nothing happens

### ISSUE THREAD

**Issue by alexandec** [valor-software/ngx-bootstrap#274]
You can reproduce this problem on the documentation page, in the Accordion section, as follows:
1. Click on the last accordion heading
2. Click the "Toggle last panel" button. Accordion doesn't respond to button click
3. A second click on "Toggle last panel" makes the accordion close as it should

This may just be an issue with the docs, or it may be a deeper underlying issue with the accordion.

---

**Update(valorkin)**
`EXCEPTION: Expression 'isOpen in AccordionDemo@17:2' has changed after it was checked. Previous value: 'true'. Current value: 'false' in [isOpen in AccordionDemo@17:2]`

clicking on `toggle last panel` in not a prod mode throws an exception

**Comment by valorkin** [comment]
fixed starting from beta.12 and ng2-bootstrap v1.0.8
