### ISSUE TITLE
ng --prod build in AOT mode logs a warning for alter module component

### ISSUE THREAD

**Issue by aravindfz** [valor-software/ngx-bootstrap#2745]
ng --prod build in AOT mode logs a warning for alter module component as <`ng-template>` instead of `<template>`
Adding screenshots in few moments

**Comment by IlyaSurmay** [comment]
Please search for same issues before opening a new one...

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.X.X because it would break Angular 2 support. You can use npm install ngx-bootstrap@next
