### ISSUE TITLE
feat(datepicker): BsDaterangepicker and BsDatepicker should be a directive, not component

### ISSUE THREAD

**Issue by pgeyman** [valor-software/ngx-bootstrap#2747]
There is a bug with the Bsdaterangepicker in that if you add the Bsdaterangepicker to an element rather than an input (eg. a button or div) then the directive removes all the child elements of the element it is added to.

If you do the same with Bsdatepicker the element's children are not removed.

**Comment by valorkin** [comment]
yeah, at the moment BsDatepicker (and range picker) is a component,
I was hoping to make it as inline and popup version at the same time
but I were wrong

will be fixed in prior v2 is released

**Comment by pgeyman** [comment]
It works ok for Bsdatepicker though. This works:

```
<div class="input-group"
             bsDatepicker #datePicker="bsDatepicker"
             [triggers]="''"
             (bsValueChange)="onDateSelected( $event )">
            <input #dateInput
                   type="text" class="form-control"
                   id="{{inputId}}"
                   name="{{inputName}}"
                   placeholder="DD-MM-YYYY"
                   [disabled]="disabled"
                   [(ngModel)]="dateValue"
                   (ngModelChange)="onInputChanged( $event )"
                   [textMask]="maskOptions"
                   (focus)="onFocus()"
                   (keydown.tab)="onTabKeyPressed($event)"
                   (keydown.shift.tab)="onTabKeyPressed($event)">
            <span class="input-group-addon" 
                  (click)="onAddonClicked( $event )"><i class="fa fa-calendar"></i></span> 
        </div>
```

But replacing bsDatepicker with bsDaterangepicker causes the input and span to be removed.

(`onAddonClicked` opens the datepicker popup.)

**Comment by valorkin** [comment]
Yes, agreed, it should land shortly

**Comment by valorkin** [comment]
thx @IlyaSurmay 
it's published in beta.10

**Comment by rojagadeesh** [comment]
> It works ok for Bsdatepicker though. This works:
> 
> ```
> <div class="input-group"
>              bsDatepicker #datePicker="bsDatepicker"
>              [triggers]="''"
>              (bsValueChange)="onDateSelected( $event )">
>             <input #dateInput
>                    type="text" class="form-control"
>                    id="{{inputId}}"
>                    name="{{inputName}}"
>                    placeholder="DD-MM-YYYY"
>                    [disabled]="disabled"
>                    [(ngModel)]="dateValue"
>                    (ngModelChange)="onInputChanged( $event )"
>                    [textMask]="maskOptions"
>                    (focus)="onFocus()"
>                    (keydown.tab)="onTabKeyPressed($event)"
>                    (keydown.shift.tab)="onTabKeyPressed($event)">
>             <span class="input-group-addon" 
>                   (click)="onAddonClicked( $event )"><i class="fa fa-calendar"></i></span> 
>         </div>
> ```
> But replacing bsDatepicker with bsDaterangepicker causes the input and span to be removed.
> 
> (`onAddonClicked` opens the datepicker popup.)

Could you please provide full working example
