### ISSUE TITLE
BsModalRef fails to inject when building with angular-cli --build-optimizer flag

### ISSUE THREAD

**Issue by aliyeysides** [valor-software/ngx-bootstrap#2763]
I have a modal being called via service which works fine, but when I build my project using angular-cli **ng build --aot --build-optimizer** flag, it throws this error: 

> Cannot resolve all parameters for 'AModalComponent'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'AModalComponent' is decorated with Injectable.

If I remove the **--build-optimize** flag, everything works as expected. So my question is if we could expect this support/compatibility in the future?

```
export class AComponent implements OnInit {
  public bsModalRef: BsModalRef;

  constructor(public modalService: BsModalService) {
  }

  ngOnInit() {
  }

  public openPreviousModal() {
    this.bsModalRef = this.modalService.show(AModalComponent);
  }

}

export class AModalComponent implements OnInit {
  public title: string;
  public list: any[] = [];

  constructor(public bsModalRef: BsModalRef) {
  }

  ngOnInit() {
    this.title = 'test 1';
  }
}

```

**Comment by IlyaSurmay** [comment]
Which version of ngx-bootstrap are you using? This was fixed in 2.0.0-beta.5, try it.
Please be aware of a few breaking changes there, also 2.* versions no longer support Angular 2 , only 4 https://github.com/valor-software/ngx-bootstrap/blob/development/CHANGELOG.md#200-beta5-2017-09-18
