### ISSUE TITLE
Modal config: show is not working

### ISSUE THREAD

**Issue by santosmken** [valor-software/ngx-bootstrap#2764]
I want not to show the modal when the component is loaded via Modal service but it doesnt work. I already passed the config with the component and still not works. Some other config is working like the 'animate' but the 'show' is not working.

**Comment by valorkin** [comment]
This property leaded to confusion, cuz `show` it is used only by modals registered by directive (will be deprecated most probably)
best option is to open new modal from `ngAfterContentInit`
