### ISSUE TITLE
Angular CLI ng build --prod does not work with ngx-boostrap 1.9.3

### ISSUE THREAD

**Issue by peval27** [valor-software/ngx-bootstrap#2766]
I have converted my Angular (4.2.4) from Angular Seed to Angular CLI. 
`ng serve` works fine, while `ng build --prod` fails due to error found in ngx-boostrap:

> ERROR in ng:///C:/Users/user/Documents/git/website/node_modules/ngx-bootstrap/datepicker/yearpicker.component.d.ts.YearPickerComponent.html (36,11): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in ng:///C:/Users/user/Documents/git/website/node_modules/ngx-bootstrap/accordion/accordion-group.component.d.ts.AccordionPanelComponent.html (7,13): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
  Index signature is missing in type 'string[]'.
ERROR in ng:///C:/Users/user/Documents/git/website/node_modules/ngx-bootstrap/datepicker/daypicker.component.d.ts.DayPickerComponent.html (65,13): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in ng:///C:/Users/user/Documents/git/website/node_modules/ngx-bootstrap/datepicker/daypicker.component.d.ts.DayPickerComponent.html (22,9): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in C:/Users/user/Documents/git/website/src/$$_gendir/node_modules/ngx-bootstrap/datepicker/monthpicker.component.ngfactory.ts (34,42): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in ng:///C:/Users/user/Documents/git/website/node_modules/ngx-bootstrap/datepicker/monthpicker.component.d.ts.MonthPickerComponent.html (35,11): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in ng:///C:/Users/user/Documents/git/website/node_modules/ngx-bootstrap/datepicker/monthpicker.component.d.ts.MonthPickerComponent.html (12,9): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in C:/Users/user/Documents/git/website/src/$$_gendir/node_modules/ngx-bootstrap/datepicker/yearpicker.component.ngfactory.ts (32,46): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in C:/Users/user/Documents/git/website/src/$$_gendir/node_modules/ngx-bootstrap/datepicker/daypicker.component.ngfactory.ts (119,42): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in ng:///C:/Users/user/Documents/git/website/node_modules/ngx-bootstrap/datepicker/yearpicker.component.d.ts.YearPickerComponent.html (13,9): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in C:/Users/user/Documents/git/website/src/$$_gendir/node_modules/ngx-bootstrap/pagination/pager.component.ngfactory.ts (25,42): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in C:/Users/user/Documents/git/website/src/$$_gendir/node_modules/ngx-bootstrap/pagination/pager.component.ngfactory.ts (41,46): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in ng:///C:/Users/user/Documents/git/website/node_modules/ngx-bootstrap/progressbar/bar.component.d.ts.BarComponent.html (3,3): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in ng:///C:/Users/user/Documents/git/website/node_modules/ngx-bootstrap/sortable/sortable.component.d.ts.SortableComponent.html (27,6): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in ng:///C:/Users/user/Documents/git/website/node_modules/ngx-bootstrap/typeahead/typeahead-container.component.d.ts.TypeaheadContainerComponent.html (17,9): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in ng:///C:/Users/user/Documents/git/website/node_modules/ngx-bootstrap/typeahead/typeahead-container.component.d.ts.TypeaheadContainerComponent.html (35,11): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.
ERROR in ng:///C:/Users/user/Documents/git/website/node_modules/ngx-bootstrap/typeahead/typeahead-container.component.d.ts.TypeaheadContainerComponent.html (4,1): Argument of type 'string[]' is not assignable to parameter of type '{ [p: string]: number; }'.

I'm using `@angular/cli": "1.4.3`

**Comment by valorkin** [comment]
could not reproduce with ngx-bootstrap@next
please try

**Comment by peval27** [comment]
I'm now using 2.0.0.-beta5 and I'm seeing the same exact errors.

**Comment by valorkin** [comment]
angular/cli: "1.4.4",
tsc 2.4.2
create a small repo to reproduce please

**Comment by peval27** [comment]
Hi,

I've reproduced the issuing, stripping all the custom code and leaving hopefully only the gist of:
- angular cli
- ngx-boostrap
- some other libraries

https://github.com/peval27/AngularCLINgxBootstrap

thanks,

**Comment by peval27** [comment]
Interesting enough: uninstalling node/npm and installing versions 6.9.5 and 3.10.10 respectively, it's now working
