### ISSUE TITLE
DatePicker - Add more local lang... (Hebrew)

### ISSUE THREAD

**Issue by fadelguy** [valor-software/ngx-bootstrap#2769]
Hi,

Please add hebrew lang local to datepicker.

Thanks!

**Comment by valorkin** [comment]
It's nice reason for small PR,
Use moment.js Hebrew location as a base

**Comment by fadelguy** [comment]
can you please explain me how to do that?

**Comment by valorkin** [comment]
compare any locale from ngx-bootstrap with same locale from moment.js
and you will see how simple it is to add new one

check this PR for example

**Comment by valorkin** [comment]
https://github.com/valor-software/ngx-bootstrap/pull/2700

**Comment by frankben4578** [comment]
i support ypu

**Comment by msarsha** [comment]
@valorkin @fadelguy  Hey!

I have a PR ready, mind if I submit it ?

**Comment by valorkin** [comment]
@msarsha do it :)
I will really appreciate if you will migrate tests too, can be in separate PR

**Comment by msarsha** [comment]
Will do.

**Comment by valorkin** [comment]
@msarsha thanks again :D
