### ISSUE TITLE
Want to disable dates, month and year after particular date.

### ISSUE THREAD

**Issue by rahulgupta20nov** [valor-software/ngx-bootstrap#2780]
Hi,
I want to disable date, month, year from particular dates. 
There have one property is "isDisabled". But this property disable all dates or not.

**Comment by IlyaSurmay** [comment]
Hi!
If I understand you correctly, you need to disable posibility to select any date after some particular one, right? In this case you need to use `maxDate` option.

**Comment by Maulik009** [comment]
No but what if I want to disable whole month in month picker?
