### ISSUE TITLE
ng-content not included in modal template

### ISSUE THREAD

**Issue by Calligos** [valor-software/ngx-bootstrap#2789]
Hi, since the last post (when having problems with the modal directive) I'm using the modal service to display my modals. I use a dialog component that receives several named divs for using different modal contents, inserting the contents via content projection into the ng-contents. But occasionally the ng-contents are not included in the modal... Only reloading the page leads to the content to be shown again until the modal is opened again without content.

dialog.component.html
```
<ng-template #dialogTemplate>
	<div class="modal-header">
		<button type="button" class="close" (click)="hide()" *ngIf="showHide">
			<span>&times;</span>
		</button>
		<h3 class="modal-title"><ng-content select="[app-dialog-title]"></ng-content></h3>
	</div>
	<div class="modal-body">
		<ng-content></ng-content>
	</div>
	<div class="modal-footer">
		<ng-content select="[app-dialog-footer]"></ng-content>
	</div>
</ng-template>
```

dialog.component.ts
```
	@ViewChild("dialogTemplate")
	dialogTemplate: TemplateRef<any>;

	show(): void {
		this.modalRef = this.modalService.show(this.dialogTemplate);
	}
```

The dialog component is called with a set of named divs for the ng-content placeholders.

```
<app-dialog #dialog>
	<div app-dialog-title>Modal title</div>
	<div>
		This is my modal content
	</div>
	<div app-dialog-footer>
		<button class="btn btn-default pull-left"
				(click)="cancelClicked()">Cancel</button>
		<button class="btn btn-primary"
				(click)="okClicked()">OK</button>
	</div>
</p4-dialog>
```

**Comment by IlyaSurmay** [comment]
It would be nice to see a plunkr or stackblitz example with reproduction of this issue.
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-stack?file=app%2Fapp.module.ts

**Comment by Calligos** [comment]
The problem is, the empty modal only appears rarely, probably one of a hundred times... or even rarer. I added a second page since it may only happen after changing pages.

[https://stackblitz.com/edit/modal-problem](https://stackblitz.com/edit/modal-problem)

**Comment by IlyaSurmay** [comment]
Closed for inactivity. Will be reopened if you provide a plunkr/stackblitz with reproduction
