### ISSUE TITLE
z-index of datepicker-modal should be increased

### ISSUE THREAD

**Issue by wladidn** [valor-software/ngx-bootstrap#2790]
### Bug description or feature request:
When opening the new datepicker from a modal (ngx-bootstrap/modal) the datepicker is opening behind the backdrop of the modal and is therefore not accessible. Increasing the z-index solves the problem.

### Plunker/StackBlitz that reproduces the issue:
https://plnkr.co/edit/IzEV45K5uRWeYE5MhdGs?p=preview

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.9.3 (in the plunker example i used 2.0.0-beta.6 because of errors but the problem is the same for 1.9.3)

Angular: 4.4.4

Bootstrap: 4.0.0-beta

**Comment by IlyaSurmay** [comment]
Already merged #2788. This will be incorporated in the next release.
