### ISSUE TITLE
@angular-cli 1.4.4 does not support Typescript 2.4.2, which ngx-bootstrap requires, as a peer dependency

### ISSUE THREAD

**Issue by acoard** [valor-software/ngx-bootstrap#2795]
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: "next", latest version, which is currently 2.0.0-beta5.

Angular: 4.4.0

Bootstrap:^3.3.6

```
> ng --version
@angular/cli: 1.4.4
node: 7.6.0
os: darwin x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/compiler-cli: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/platform-server: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.4
typescript: 2.3.4
```

### Issue Description

When using ngx-bootstrap on a project and running `npm install`, the following error shows up:
```
└── UNMET PEER DEPENDENCY typescript@2.3.4

npm WARN ngx-bootstrap@2.0.0-beta.6 requires a peer of typescript@>=2.4.2 but none was installed.
```

@angular/cli@4.4.3 only supports Typescript <2.4.0.  In [this issue](https://github.com/angular/angular/issues/19287) the Angular team say they will only support Typescript >=2.4.0 in Angular 5, which is currently in the rc phase. Furthermore, they say they're aware of issues with >=2.4.0 which means this isn't an abstract compatibility concern but a real issue.

The ngx-bootstrap project itself uses @angular/cli 1.4.4. As such, it should be compatible with the version of typescript that the @angular/cli requires.

### Desired Behaviour

ngx-bootstrap supports the version of typescript that the latest (non-RC) version of @angular/cli supports.

### Details

Since the Angular team say they're aware of issues with going up to Typescript >2.4.0 with Angular 4, I won't be risking that.  However, I have been using ngx-bootstrap@next for a while with Typescript >2.4.0 without issue.  As far as I understand it, it'll be totally safe to reduce the typescript version and shouldn't introduce any regressions, but you know the code base better than I. :)

Are there any reasons we can't reduce the required version to >= 2.1.0 and <2.4.0?

Thanks,
Adam.

**Comment by valorkin** [comment]
Partial is used for Typeahead, 2.4.0+ will be fine,
Nice reason for PR with peer deps update

Or you can do such issue in ng cli too, cuz they should support all up to 2.5 without warning

**Comment by harunurhan** [comment]
@valorkin I don't think they should support because, angular4 is not compatible with `typescript@>=2.4` as mentioned here.

https://github.com/angular/angular/issues/19287#issuecomment-331250655

**Comment by valorkin** [comment]
that's sucks, ok can you do a small PR and change typescript peer dependency to >=2.3 ?
