### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Ivaneyko** [valor-software/ngx-bootstrap#2797]
Nothing work from documentation. Please, update it

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: @next
Angular: 4.2
Bootstrap: 4.0-beta

**Comment by IlyaSurmay** [comment]
There's not much of information, don't you think? What exactly doesn't work?
Please, be specific when you're reporting about some issue. Provide examples, plunkrs, stackblitz, repos, whatever helps us to find out where the issue is.

**Comment by valorkin** [comment]
@Ivaneyko you just made my day :)
