### ISSUE TITLE
chore(template-url): support or not

### ISSUE THREAD

**Issue by briantopping** [valor-software/ngx-bootstrap#28]
How hard would it be to support `template-url` on `AccordionGroup`? I need it for a project I am working on, the existing template is somewhat complex and is including a lot of unwanted CSS.

I'd be happy to have a go at a PR, just don't know what to do here. Thanks!

**Comment by valorkin** [comment]
Last time I tried, it was working via dynamically created components, but
it will be really slow if used heavily
extending base component and overwriting template was much faster

need to check again

**Comment by briantopping** [comment]
Hmm ok thx. There's a published use case at https://github.com/briantopping/angular2-ng2-bootstrap-sbadmin, you can quickly see the left nav bar is kind of funky due to the `<h4>` that is generated in. https://github.com/briantopping/angular2-ng2-bootstrap-sbadmin/blob/master/app/components/header/sidebar.html is the HTML for that.

**Comment by briantopping** [comment]
I wasn't too successful with this. https://github.com/briantopping/angular2-ng2-bootstrap-sbadmin/blob/e042b841fce3f4567bae5d8ce55b81d4c609bf5d/app/components/header/header.ts#L25-L55 is what I have so far. It should render exactly the same as the master branch. Could I ask for your insight here?

Once that's working, I can clean up the menu. Apologies for the bother.

BTW, have you reported the difficulty in getting the template-url working as an issue to ng2? Seems like ng2-bootstrap is an important test for them!

**Comment by valorkin** [comment]
Thanks for good words, yes some discussions about it, but it was too early
and seems to be out of initial ng2 concept "component all the things"
next week I will have much more time for this project (just to update your expectations timeframe) :)

**Comment by briantopping** [comment]
Sounds good, thanks! 

I created a new project in AngularShowcase org that was set up by @mgechev, so the old repositories listed above no longer work.

**Comment by valorkin** [comment]
After long thoughts about this, I suppose supporting `template-url` is not necessary, because any component can be `extended` and `template` can be overriden.

**Comment by briantopping** [comment]
Yah, I kind of decided to focus on backend for now, give ScalaJS some time to evolve and see if React+ScalaJS can compete when I'm ready for the front end. Or if I get lucky, just task someone else to do it ;)
