### ISSUE TITLE
Multiple dropdowns (menus) stay open at the same time

### ISSUE THREAD

**Issue by ctrl-brk** [valor-software/ngx-bootstrap#2800]
### Bug description or feature request:
I'm using dropdowns as a header menu. Since beta.5 when I click on the other menu the previous one stays open. I can have all my menus open at the same time. That's not happening in beta.4

### Plunker/StackBlitz that reproduces the issue:
It might be a side effect of nested dropdowns.
You can kind of see it here:
https://valor-software.com/ngx-bootstrap/#/dropdowns#nested
Open the dropdown (btw, it will not close when you click outside like others do), hover nested dropdown items and you'll be able to have both of them open.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.6

Angular: 4.4.4

Bootstrap: 3

**Comment by valorkin** [comment]
It was like that from the start, unfortunately, I didn't figured out how to make it ... better
But you can achieve better behavior with css

**Comment by ctrl-brk** [comment]
As I said it doesn't happen in beta.4. Started in beta.5

**Comment by ctrl-brk** [comment]
Here's the plunker. Click on top level menus - you will see the issue.
Change ngx-bootstrap version to 2.0.0-beta.4 and the issue disappears.
https://plnkr.co/edit/OEtnl6?p=preview

**Comment by ctrl-brk** [comment]
Still happening in beta 7

**Comment by valorkin** [comment]
True

**Comment by ctrl-brk** [comment]
Now that's become a real problem. I can't use beta.4 with just released Angular 5 because of the ngOutletContext and I also can't use latest version because of this issue. Which pretty much means that I can't use Angular 5 with current ngx-bootstrap.

**Comment by valorkin** [comment]
It's in the list to fix today, and to be in beta.8

**Comment by valorkin** [comment]
@ctrl-brk found where an issue came and have a fix, just in case I have 2 envs now with ng 4 and 5.
So when we will publish, it should just work :)

**Comment by valorkin** [comment]
Fix published ;)

**Comment by chelaruc** [comment]
Hi guys! Thank you for your work ❤️ . Unfortunately, I still have this issue on v5.3.2. Can you help me?

**Comment by manar-mk** [comment]
Hi, I'm facing the same problem when using `$event.stopPropagation()`. 
I know, it's not an issue, but maybe any ideas how to workaround?

**Comment by aleksandar-pajic-44** [comment]
Any update on this?
