### ISSUE TITLE
Close and reopen modal from its child modal

### ISSUE THREAD

**Issue by FrancescoBorzi** [valor-software/ngx-bootstrap#2807]
### Bug description or feature request:

I'm not sure if this can be already accomplished: I'd like to be able to temporarily close and then reopen a parent modal from its child modal.

My specific use case is described in this question: https://stackoverflow.com/questions/46607217/ngx-bootstrap-close-and-reopen-modal-from-its-child-modal

In case this is not currently possible to achieve, I'd like to request this feature.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: **1.9.3**

Angular: **4.4.4**

Bootstrap: **3.3.7**

**Comment by valorkin** [comment]
Consider each modal is independent, hiding parent content is similar to show loading progress,
Before showing child modal, hide content of parent component with ng if or hidden inside of your template
