### ISSUE TITLE
feat(carousel): add transition to carousel

### ISSUE THREAD

**Issue by mdymel** [valor-software/ngx-bootstrap#281]
There is no transition while slides change.

**Comment by gitdisrupt** [comment]
Any word on this? Seems like all the correct classes are there, but the transition does not work.

**Comment by gitdisrupt** [comment]
To be more specific, there are classes that need to be applied prior to switching the 'active' class. Should be 'prev right' or 'next left' on the upcoming slide before applying 'active', as well as the active slide should get the 'left' or 'right' class depending on direction selected.

**Comment by imalhasaranga** [comment]
Is this fixed now!! I'm having the same issue

**Comment by aepw** [comment]
I'm still having the same issue

**Comment by jjamaral** [comment]
Any updates on that?
Thank you!

**Comment by figuerres** [comment]
I just looked at the bootstrap web sites for V3 and V4 at the demo of the carousel 
and at what I am getting from this package and it looks like some markup is missing or wrong that it needs to make the slide transitions work.
the ol / li in the bootstrap sample is like this
`<ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" data-slide-to="2" class=""></li>
      </ol>
`
but in this package the demo page does not have the data-target and data-slide

I suspect this is part of where it fails to do the effects.
I will try and work  with the code and see if I can make it work like the bootstrap site example and will post back on what I find.

**Comment by dpereverzev** [comment]
Working on resolving this issue. Seems slides need classes like: left, right, next while transition going

**Comment by figuerres** [comment]
it's funny there are multiple samples of carousels and they all seem to have the same missing feature.
also there is another project that his almost the same as this one that seems to say that there is an issues with animations and angular 2 that is blocking them.
see this:
https://github.com/ng-bootstrap/ng-bootstrap/issues/295
also I found this:
http://mlaval.github.io/angular2-bootstrap/
based on the early versions of angular 2 but it has the slide working !
I am trying to update that to the released angular  code and markup but I am really new to the angular and typescript stuff so it's taking a bit of time to learn how to get it working with the changes .
https://github.com/mlaval/angular2-bootstrap
hope that info helps some,....

**Comment by figuerres** [comment]
just a heads up in case anyone is interested that other carousel almost works but something in the changes fro early to release is messing with my trying to make it work
http://mlaval.github.io/angular2-bootstrap/

**Comment by kabsila** [comment]
any update ?

**Comment by valorad** [comment]
Any update on this issue? I tried manually add transition style
`transition: transform .6s ease-in-out, -webkit-transform .6s ease-in-out, -o-transform .6s ease-in-out;`
on `.carousel-item` but it is not working.

**Comment by cristianstu** [comment]
+1

**Comment by felipefialho** [comment]
Is need to add the classes: `next` or `prev` and `left` or `right` after the click for it works.

**Comment by figuerres** [comment]
this will be very nice if we have a release build that works !!

**Comment by Pastafarian** [comment]
+1

**Comment by saostad** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by miloskovacevic** [comment]
+1

**Comment by hG3n** [comment]
+1

**Comment by SergiyPakholchak** [comment]
+1

**Comment by kazafy** [comment]
+1

**Comment by eranation** [comment]
+1

**Comment by KoinBanks** [comment]
+1

**Comment by nbiles** [comment]
+1

**Comment by unix** [comment]
+1
and you can try this [components](https://element-angular.faas.ele.me/others/carousel)

**Comment by bradysheridan** [comment]
+1

**Comment by silencieuxle** [comment]
+1

**Comment by nkrambo** [comment]
+1

**Comment by royalarjun001** [comment]
+1

**Comment by eugene159** [comment]
Nice library. Dynamic tabs are awesome. But without animations for accordion and image carousel I will have to switch back to regular bootstrap that relies on jQuery :(  I really don't want to add jQuery as a dependency to my Angular project, but I have no choice.

**Comment by chungkam** [comment]
**in CSS component i added**
.animated {
    -webkit-animation-duration: 1s;
    animation-duration: 1s;
    -webkit-animation-fill-mode: both;
    animation-fill-mode: both;
 }
@-webkit-keyframes fadeIn {
           0% {opacity: 0;}
           100% {opacity: 1;}
}
 @keyframes fadeIn {
          0% {opacity: 0;}
          100% {opacity: 1;}
  }
 .fadeIn {
          -webkit-animation-name: fadeIn;
          animation-name: fadeIn;
}
**in html i added**
       < carousel >
        < slide **class="animated fadeIn**" >
          < img src="xxx.xx" class="carousel-img" >
       < /slide >
      < / carousel >

it works but the effect look like photo flash..

**Comment by woteska** [comment]
+1

I started to build an Angular 5 app using the newest Bs (first not ngx bs), but I couldn't control the carousel by jQuery. Then I found ngx bs, but the transition is missing of carousel. :/

**Comment by Kikisek** [comment]
Got inspired by @chungkam, added class **animated** to html:
< carousel >
  < slide class="animated" >
    < img >
  < /slide >
< / carousel >

The css looks like this:
slide {
  margin-left: -100%;
}
.animated {
  animation: carouselAnimation 10s ease-in-out infinite;
}
@keyframes carouselAnimation { 
  0% { margin-left: 100%; }
  10% { margin-left: 0%; }
  40% { margin-left: 0%; }
  50% { margin-left: -100%; }
}

Works for me so I hope it will help some of you guys :)

**Comment by jimmymain** [comment]
I see this is on the roadmap now - NB feature. Hope it's done soon...
Tried this: https://www.codeply.com/go/LhLJlldsLN but couldn't get it to work.

**Comment by seblemeur** [comment]
+1

**Comment by navdeep-vdb** [comment]
+1
any update on this???

**Comment by jabberwockie** [comment]
So everyone just have carousels that change images without any kind of transition? Any ways to add any kind of transition so it doesn't seem so... sudden and uncontrolled?

**Comment by esoyke** [comment]
I had to switch to use this one instead due to the lack of transition support: https://github.com/sheikalthaf/ngu-carousel

This one works well so far, very customizable.

**Comment by raugaral** [comment]
why ngb-carousel don't take the css classes at the attribute "class" ??

**Comment by griga** [comment]
To create sliding animation I've came up with next solution

in main `styles.scss` add
``` scss
carousel.slide-animated {
  slide.item {
    animation-duration: 1s;
    animation-fill-mode: both;
    &.active {
      width: 100%;
      animation-name: carouselSlideIn;
    }
    &:not(.active) {
      display: table-cell;
      animation-name: carouselSlideOut;
    }
  }
}

@keyframes carouselSlideIn {
  0% { transform: translateX(100%); }
  100% { transform: translateX(0); }
}
@keyframes carouselSlideOut {
  0% { transform: translateX(0); }
  100% { transform: translateX(-100%); }
}
```
You can use it than in component like:
```html
<carousel class="slide-animated">
  <slide><img src="slide1.jpg"/></slide>
  <slide><img src="slide2.jpg"/></slide>
  <slide><img src="slide3.jpg"/></slide>
</carousel>
```
PS: The single problem left is that slides are always moving from right to left, no matter which arrow you've pressed. I will update answer when/if I resolve this

**Comment by ronjb04** [comment]
i have modified @griga input and added back animation

html
`<carousel (activeSlideChange)="slideChange($event)" >`

ts
`slideIndex: number;
  slideDirection:string = "hold";
  slideChange(event){
    if(this.slideIndex == undefined){
      this.slideDirection = "hold";
    }else if(this.slideIndex < event){
      this.slideDirection = "forward";
    }else{
      this.slideDirection = "back";
    }
    this.slideIndex = event;
  }`

scss
`carousel{
  .item {
    animation-duration: 1s;
    animation-fill-mode: both;
  }
  &.forward{
    .item{
      &.active {
        width: 100%;
        animation-name: carouselSlideIn;
      }
      &:not(.active) {
        display: table-cell;
        animation-name: carouselSlideOut;
      }
    }
  }
  &.back{
    .item{
      &.active {
        width: 100%;
        animation-name: carouselSlideInBack;
      }
      &:not(.active) {
        display: table-cell;
        animation-name: carouselSlideOutBack;
      }
    }
  }
  
  @keyframes carouselSlideIn {
    0% { transform: translateX(100%); }
    100% { transform: translateX(0); }
  }
  @keyframes carouselSlideOut {
    0% { transform: translateX(0); }
    100% { transform: translateX(-100%); }
  }
  @keyframes carouselSlideInBack {
    0% { transform: translateX(-100%); }
    100% { transform: translateX(0); }
  }
  @keyframes carouselSlideOutBack {
    0% { transform: translateX(0); }
    100% { transform: translateX(100%); }
  }
}`

not sure why the code i added is not showing in code format.. anyhow this is working with back and forward slide animation
