### ISSUE TITLE
Cannot create a modal with component using BsModalService

### ISSUE THREAD

**Issue by MostafaAbdlrazek** [valor-software/ngx-bootstrap#2819]
When i try to create a modal with component like the example in the demo, the window got dimmed and nothing appear.

Plunkr Link: https://plnkr.co/edit/SpvKZRFrIGpTa8mZXUBN

ngx-bootstrap:
1.9.3

Angular:
4

Bootstrap:
3.3.7

**Comment by IlyaSurmay** [comment]
Hi! Take a look at console error:
`Error: No component factory found for ModalContentComponent. Did you add it to @NgModule.entryComponents?`
As we mentioned in [demo](https://valor-software.com/ngx-bootstrap/#/modals#service-component), component which you pass as a modal content should be added to `entryComponents` of your `@NgModule`.

Here's fixed plunkr https://plnkr.co/edit/yEmY51Y6dwc5opJyvYn4?p=preview
