### ISSUE TITLE
Angular 4 How could I remove the warning "The <template> element is deprecated. Use <ng-template> instead

### ISSUE THREAD

**Issue by DrewTian** [valor-software/ngx-bootstrap#2820]
After I upgrade to Angular 4, I keep getting the following warning from the console of developer tools.
How could I remove this warning.

Thanks

Template parse warnings:
The <template> element is deprecated. Use <ng -template> instead ("
  </thead>
  <tbody>
    [WARNING ->]<template ngFor [ngForOf]="rows" let-rowz="$implicit" let-index="index">
      <tr *ngIf="!(datePicke"): ng:///DatepickerModule/DayPickerComponent.html@38:4
Console.warn @ console.ts:26

![capture](https://user-images.githubusercontent.com/32710509/31447733-b408f0e0-ae70-11e7-956f-876c35164541.JPG)

**Comment by fchiumeo** [comment]
ngx-bootstratp@1.9.X support angular 2 and angular 4
ngx-bootstrap@next suport only angular 4 and not warning template

**Comment by DrewTian** [comment]
Hi fchiumeo, thanks for the reply.
I am still not very clear how to remove the warning.

Could you please give me more details or steps

Thanks

**Comment by Martin-Luft** [comment]
Please search for same issues before opening a new one...

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.X.X because it would break Angular 2 support. You can use "ngx-bootstrap": "2.0.0-beta.6" or npm install ngx-bootstrap@next :)

**Comment by DrewTian** [comment]
I have run the following, but cannot remove the warning
npm install ngx-bootstrap@next

Here is the message after I run, not helpful
![capture](https://user-images.githubusercontent.com/32710509/31452043-cbbcd642-ae7b-11e7-81c5-52f855e39659.JPG)

**Comment by Martin-Luft** [comment]
@DrewTian your screenshots shows me, that you try to install `ngx-bootstrap@next` and `ng2-bootstrap@1.1.6` what makes no sense and is not possible.
