### ISSUE TITLE
feat(modal): add possibility of dynamic changing class of a modal when using BsModalRef

### ISSUE THREAD

**Issue by Alpha0723** [valor-software/ngx-bootstrap#2824]
I am using BsModalRef to show dialog. In the dialog, I implement a setting guideline step by step, but in each step, I need to set different 'width'. I find I only can pass param {class: 'my-dialog-class'} when calling BsModalRef.show(). So how can I dynamic set different width or class on the dialog in each step?

**Comment by IlyaSurmay** [comment]
ngx-bootstrap doesn't provide this functionality for now :(
Nice reason for a small PR though.

**Comment by polaris327** [comment]
Guys! Any updates on this yet?

**Comment by ghost** [comment]
@Alpha0723 @polaris327 Maybe this [code](https://stackblitz.com/edit/ngx-bootstrap-twrhnj?file=app%2Fapp.component.html) helps you
