### ISSUE TITLE
Cannot change locale with BsDatepicker

### ISSUE THREAD

**Issue by aurerua** [valor-software/ngx-bootstrap#2842]
Trying to use another locale for the new datepicker as described in the docs, this error gets thrown: 

`(SystemJS) Cannot set property 'abbr' of undefined`

The error comes  out of  `defineLocale('de', de);` added to the module. The locale object `de` is undefined when his `abbr` attribute is set...

The issue remains if the import statement is changed from 

`import { de } from 'ngx-bootstrap/locale';`

to

`import { de } from 'ngx-bootstrap';`

(And the editor complains that `ngx-bootstrap/index has no exported member 'de'`.)

Config: 
- ngx-bootstrap@2.0.0-beta.6
- Angular 4 (Angular Seed - megchev)
- Bootstrap 3.3.7

**Comment by aurerua** [comment]
Here is a temporary fix, that works for me:

- Copy file `bs-moment/i18n/de.ts` (found under `/src/` on GitHub or `node_modules/ngx-bootstrap` locally) to your angular app
- import it from there. So, in the module, instead of `import { de } from 'ngx-bootstrap/locale';` do `import { de } from 'path/to/local/flie/de.ts';`

**Comment by IlyaSurmay** [comment]
The issue here is that `ngx-bootstrap/index` doesn't export any locales, they're all exported from `ngx-bootstrap/locale` but SystemJS can't handle this path, so we'll need to additionally export locales in `ngx-bootstrap/index`
