### ISSUE TITLE
Typeahead does not apply existing input text as filter on focus and click when typeaheadMinLength is 0

### ISSUE THREAD

**Issue by esotrope** [valor-software/ngx-bootstrap#2845]
As expected, when typing text into the input, a filtered set of options are presented in the dropdown below. However, when you enter some text, click away, then click (focus) the input again the existing input text is not applied as a filter.

See code in typeahead directive:
```typescript
  @HostListener('click')
  @HostListener('focus')
  onFocus(): void {
    if (this.typeaheadMinLength === 0) {
      this.typeaheadLoading.emit(true);
      this.keyUpEventEmitter.emit('');
    }
  }
```

The behavior I would expect would be coded something like this:
```typescript
this.keyUpEventEmitter.emit(this.element.nativeElement.value);
```

If this is by design I would suggest introducing a flag to make this behavior conditional.
Currently, I am working around this by using the following code in my containing component:

```typescript
@Component({
  selector: '[custom-typeahead]',
  template: `
    <input [typeahead]="options"
           [typeaheadMinLength]="0"
           (focus)="onFocusHotfix()"
           [(ngModel)]="search">
  `
})
export class CustomTypeahead implements OnInit {
  @ViewChild(TypeaheadDirective) typeahead;
  @Input() options: any[];
  @Input() search: string;
  onFocusHotfix(): void {
    this.typeahead.onChange({ target: { value: this.search } });
  }
}
```

**Comment by valorkin** [comment]
Thanks, it's definitely an issue
