### ISSUE TITLE
feat(datepicker): add customClass option to the new version of datepicker

### ISSUE THREAD

**Issue by asaf-paz** [valor-software/ngx-bootstrap#2848]
Hi,
I'm using the legacy version of your datepicker and I'm heavily using the customClass attribute in order to set different classes on different dates according to the input data and I'm using it in inline mode.
I just updated to the latest version and now my legacy datepicker doesnt use momentjs locale as before and it goes back to the EN version.
I don't mind upgrading to the new version of the datepicker, but i cant seem to find a way to use customClass option over there.
Any advise will be highly appriciated.
Thanks.

**Comment by IlyaSurmay** [comment]
Hi!
You're right, `customClass` is not yet implemented in the new datepicker. I'm marking this as a feature request.

**Comment by fegyi001** [comment]
Is there any way that the legacy version of the DatePicker module could use the 'old' moment.js localization? It now says: 'ERROR Error: Missing locale data for the locale "hu".'

**Comment by valorkin** [comment]
Hey, please check locales section https://valor-software.com/ngx-bootstrap/#/datepicker
It should help

**Comment by fegyi001** [comment]
It is for the BsDatepicker, not the legacy Datepicker if I’m correct. How can I achieve the same with the old version?

**Comment by IlyaSurmay** [comment]
@fegyi001 have you tried to manually add moment.js to your project? `scripts` section of `angular-cli.json` or system.js config?

**Comment by valorkin** [comment]
We need to expose date adapter

**Comment by martintro** [comment]
This seems to be the same issue I've reported here? https://github.com/valor-software/ngx-bootstrap/issues/3958
I'll soon do a pull request for that issue.

It sounds like you will need an inline version of the new datepicker as well. I've a issue and pull request for that as well: https://github.com/valor-software/ngx-bootstrap/issues/3955

**Comment by bandhavya** [comment]
any update on this ?
 when will customClass option be available on the bsDatepicker ?

**Comment by bandhavya** [comment]
any update ?

**Comment by martintro** [comment]
@bandhavya Please see my last comment on #3958. "I will try to make a new PR with this functionality as soon as my current inline datepicker PR (#3956) is merged to development branch."
