### ISSUE TITLE
how can i open component on another component with modal

### ISSUE THREAD

**Issue by masoudline** [valor-software/ngx-bootstrap#2850]
Hi,
I read "create new modal component" example and run it successfully. but data is lost and not shown when I want to load component 2 into component1!
i define response for http request at ngOnInit() function!
thanks for your response

**Comment by masoudline** [comment]
+1

**Comment by ctrl-brk** [comment]
It might help if you create a plunker with the problem.

**Comment by masoudline** [comment]
i want open component1 into component 2 with ngx-bootstrap#modal. below codes are modal function's. categories data not loaded when i clicked on modal button
```
  public openModalComponent() {
    this.modalRef = this.modalService.show(CategoryTrashComponent);
  }
```
and trash category codes:
```
ngOnInit() {
    this.getCategories();
  }
  ngOnDestroy(){
    this.subscription.unsubscribe()
  }
  getCategories() {
    this.categoryService.getCategoriesTrashedPaginate(1);
    this.subscription = this.categoryService.allTrashCategories.subscribe(
      (categories: Category[]) => {
        console.log(categories)
        this.categories = categories;
        this.total = this.categoryService.allTrashCategoriesPaginateArray['total'];
        this.perPage = this.categoryService.allTrashCategoriesPaginateArray['per_page']
      }
    )
  }
```
in other word i want load this.getCategories at ngOnInit() function!

**Comment by IlyaSurmay** [comment]
Could you create a plunkr/stackblitz with reproduction? 
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-stack?file=app%2Fapp.module.ts

**Comment by valorkin** [comment]
Most probably it's an angular issue, if on init is not called when component is created dynamically

**Comment by IlyaSurmay** [comment]
Closed for inactivity. Will be reopened if you provide a plunkr/stackblitz with reproduction
