### ISSUE TITLE
AOT Build issues on AngularCLI with BsDatePicker and BsDateRangePicker

### ISSUE THREAD

**Issue by devarg** [valor-software/ngx-bootstrap#2857]
### Bug description:

bs-datepicker-container and bs-daterangepicker are not being able to be built on angular cli using aot, disabling with (--aot=false) seems to bypass the build error but keeps me away from doing AOT on the whole app which is a big issue at least in my case.

```
PS C:\dev\Tooling\app> ng build --prod
Date: 2017-10-17T17:31:44.088Z
Hash: 0aae4d48687f29d34449
Time: 15066ms
chunk {0} styles.f8f3f920a3b1c1de541c.bundle.css (styles) 562 bytes {3} [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes {3} [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.22b7623ed7c5ac6f9a35.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in C:/dev/Tooling/app/src/$$_gendir/node_modules/ngx-bootstrap/datepicker/bs-datepicker.module.ngfac
tory.ts (11,21): Cannot find module './themes/bs/bs-datepicker-container.component.ngfactory'.
ERROR in C:/dev/Tooling/app/src/$$_gendir/node_modules/ngx-bootstrap/datepicker/bs-datepicker.module.ngfac
tory.ts (12,21): Cannot find module './themes/bs/bs-daterangepicker-container.component.ngfactory'.
```

```
PS C:\dev\Tooling\app> ng build --prod --aot=false
Date: 2017-10-17T17:33:19.415Z
Hash: 25edf0c053d4ee9c88cf
Time: 36700ms
chunk {0} polyfills.9b871b71a4f78f0d7678.bundle.js (polyfills) 66.1 kB {4} [initial] [rendered]
chunk {1} main.06134a98b910e2019fac.bundle.js (main) 279 kB {3} [initial] [rendered]
chunk {2} styles.f8f3f920a3b1c1de541c.bundle.css (styles) 562 bytes {4} [initial] [rendered]
chunk {3} vendor.4ed40b01ae7b68d67a89.bundle.js (vendor) 1.55 MB [initial] [rendered]
chunk {4} inline.35bc4656404c75ecbc7e.bundle.js (inline) 1.45 kB [entry] [rendered]
```

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.6
Angular: @angular/*: ^5.0.0-rc.2
Bootstrap: Bootstrap v3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:
typescript: ~2.4.2
angular/cli: ^1.4.7
Node: v6.11.0

**Comment by lucienimmink** [comment]
Also getting an error with AoT; disabling it makes the error go away

ngx-bootstrap: 1.9.3
angular: 5.0.0
angular-cli: 1.5.0

**Comment by lucienimmink** [comment]
ngx-bootstrap 2.0.0-beta.7 does not have the same issue.

**Comment by lucienimmink** [comment]
I'm still busy porting my app over to angular-cli and angular5. (was on angular 2.something with systemjs :P) It's going smooth except for some 3rd party modules.
Have disabled ngx-bootstrap atm since it gave some issues. So maybe it still does require some work, but aot went OK, the bundle was unusable though.
Once I dive more into the issues I had with ngx-bootstrap I'll let you know/make tickets.

**Comment by devarg** [comment]
Wow, apparently .beta7 solves the issue. No more errors or warnings! Successfully migrated to Angular v5.0.0 everything seems to be working fine, I'll let everybody know if I find a breaking change, for now to me this should be closed. 

Thanks all!
