### ISSUE TITLE
Remove TypeScript and @angular/compiler peerDependency

### ISSUE THREAD

**Issue by pschmoek** [valor-software/ngx-bootstrap#2859]
### Bug description or feature request:

ngx-bootstrap is published in JavaScript compiled with ngc.
There is no reason to have `typescript` or `@angular/compiler` as a peerDependency.
ngx-bootstrap does not use `typescript` or `@angular/compiler` - there are no imports present.
The peer dependencies should be removed.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.6

Angular: 4.4

Bootstrap: 3

### Build system: Angular CLI, System.js, webpack, starter seed:

Angular CLI / custom lib using ngc, rollup

**Comment by valorkin** [comment]
js + .d.ts will be compiled with ngc on client side, and there is constructions ( partial classes and components metadata ) which depends on compiler and tsc, so minimal versions added to peer dependencies

**Comment by pschmoek** [comment]
@valorkin 
Of course in most cases ngc will be used. But it is not necessary at all. I think, it is really bad practice to add unnecessary peer dependencies since they pin versions / prevent versions to be used.
Consider someone using only a small part of the library (like we do) or someone trying to use a different `typescript` version. This lead to irritating yarn errors in our project and is completely unnecessary, since nothing is imported from either `typescript` or `@angular/compiler`. I think, the consumer should pin those versions not the library.

For example `@angular/material` and `primeng` both do not add a peer dependency to either `@angular/compiler` or `TypeScript`.

**Comment by valorkin** [comment]
I could agree with you, but `Partial` is used from typescript, and it's available in versions specified in peer dependencies.
In v2 of ngx-bs I could drop dependency to @angular/compiler, cuz it has not breaking changes in v4-5 of angular

**Comment by dackmin** [comment]
This is an issue for me too, as we don't even use `typescript` but `coffeescript` and `webpack`, and still have to see `peer dependency` warnings every time we compile our projects using any module of `ngx-bootstrap`.

**Comment by valorkin** [comment]
Hey, it's removed https://github.com/valor-software/ngx-bootstrap/blob/development/src/package.json
Will be published next week

**Comment by dackmin** [comment]
thanks 🎉
