### ISSUE TITLE
ng2-bootstrap on angular 2.0.0-beta.9

### ISSUE THREAD

**Issue by arturstarodaj** [valor-software/ngx-bootstrap#286]
Can't get ng2-bootstrap to work on -beta.9

my System.config:

 System.config({
        transpiler: 'typescript', 
        typescriptOptions: { emitDecoratorMetadata: true }, 
        packages: {
            'app': {defaultExtension: 'ts'},
            "node_modules/ng2-bootstrap": {  
                defaultExtension: 'js'
            }
        },
        paths: {
            "ng2-bootstrap/ng2-bootstrap":   "node_modules/ng2-bootstrap/ng2-bootstrap"
        }
      });

what I've got in console:

Uncaught SyntaxError: Unexpected token <
    Evaluating http://localhost:3000/moment
    Error loading http://localhost:3000/app/main.ts

**Comment by valorkin** [comment]
@arturstarodaj check readme and issues about moment.js

**Comment by arturstarodaj** [comment]
@valorkin Thanks, That was the answer to my problem.

**Comment by valorkin** [comment]
awesome, closing issue?

**Comment by arturstarodaj** [comment]
closed
