### ISSUE TITLE
customClass on tabs still failing.

### ISSUE THREAD

**Issue by dimitrijuchtmans** [valor-software/ngx-bootstrap#2880]
Using bootstrap 1.9.3, angular 4.4.6

https://plnkr.co/edit/C0r3Gx3FekDlYVYFaV1p?p=preview

I simply want my tab headings to be displayed in red. customClass works for the content of the tab, but it does nothing for the tabs itself.

I refuse to do stuff as Viewencapsulation.NONE

**Comment by IlyaSurmay** [comment]
This is actually an intended behavior of ng-content.
https://github.com/angular/angular/issues/7400
https://github.com/angular/angular/issues/11356

To get this working without using ViewEncapsulation.None, use styles with `:host >>> ` prefix.

plunkr - https://plnkr.co/edit/VNEw6XbQV161qniKinLZ?p=preview
