### ISSUE TITLE
Bug when we click on the components of the datepicker

### ISSUE THREAD

**Issue by xPoposx** [valor-software/ngx-bootstrap#2881]
Hello,
I've created a calendar with datepicker except that when I click on the month to show me the months of the year, the plugin blocks and it will be necessary each time to click on the arrow buttons to display months. Sometimes it unblocks itself after a while and it works properly again. 
Would you please clarify for me the source of this problem please?
![clik on month_blocked](https://user-images.githubusercontent.com/10750004/31771579-ee929b90-b4dc-11e7-9572-a90e979502b0.PNG)
![clik on the arrow to display months_blocked](https://user-images.githubusercontent.com/10750004/31771577-ee294a00-b4dc-11e7-9840-4fb7377c563c.PNG)
![months displayed](https://user-images.githubusercontent.com/10750004/31771578-ee7673f2-b4dc-11e7-9618-b826234e8dc4.PNG)

**Comment by IlyaSurmay** [comment]
Could you create a plunkr with reproduction?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-stack?file=app%2Fapp.module.ts

**Comment by valorkin** [comment]
Issue will be reopened when and if we will have reproduce steps
