### ISSUE TITLE
Modal backdrop in front of model using BS4 sticky-top class

### ISSUE THREAD

**Issue by Gillardo** [valor-software/ngx-bootstrap#2884]
I have created a working example of my problem.  In the realworld, i am using `router-outlets` but i have replicated the issue using a simple component.

The problem is i have a component within a div that uses bootstraps `sticky-top` class.  This is because in the real world i have a nav-bar at the top that stays there when the user scrolls.  If you press the bottom button, you will notice that the modal window appears fine.  But the top button, which is within a `sticky-top` div doesnt.

I am not sure how to fix, if someone could help.  I am sure this must be a bug?

https://plnkr.co/edit/bFNAixws4tzf4dIqyK6E?p=info

**Comment by IlyaSurmay** [comment]
Plunkr throws an error at starup, please fix it

**Comment by Gillardo** [comment]
Sorry no idea what the hell happened there, here is new plunker link, plunkr works in chrome

https://plnkr.co/edit/ICPPBxZJYmEEfr4UgAJi?p=preview

Embedded plunkr
https://embed.plnkr.co/ICPPBxZJYmEEfr4UgAJi/

Button that fails produces this
![image](https://user-images.githubusercontent.com/7406381/31901510-866c80a4-b819-11e7-8293-850a2f491692.png)

Button that works shows correct output
![image](https://user-images.githubusercontent.com/7406381/31901532-93aceab0-b819-11e7-8b33-ead08f7a6996.png)

Here is my app template, as you can see only difference is the stick-top class
```
@Component({
  selector: 'my-app',
  template: `
    <h2>{{name}}</h2>
    
    <div class="sticky-top">
      <div>THIS ONE DOES NOT WORK</div>
      <my-component></my-component>
    </div>

    <div class="mt-3">
      <div>THIS ONE WORKS</div>
      <my-component></my-component>
    </div>
    `
  ,
  providers: []
})
```

Actual component is very basic, as below, modal copied from demo site.
```

@Component({
  selector: 'my-component',
  template: `
    <button class="btn btn-primary" (click)="staticModal.show()">Click this button</button>
    
    <div class="modal fade" bsModal #staticModal="bs-modal" [config]="{backdrop: 'static'}"
     tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title pull-left">Static modal</h4>
            <button type="button" class="close pull-right" aria-label="Close" (click)="staticModal.hide()">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            This is static modal, backdrop click will not close it.
            Click <b>&times;</b> to close modal.
          </div>
        </div>
      </div>
    </div>

    `
  ,
})
export class MyComponent {
  name:string;

  constructor() {
    
  }
}
```

**Comment by Gillardo** [comment]
Any news on this???

**Comment by IlyaSurmay** [comment]
This behavior is inevitable when you use modal directive which creates a modal where its template has been defined. Also sticky-top class has lower z-index than modal classes. A possible workaround here is to use modal service -  both templates and components will work.
A few samples for you:
https://plnkr.co/edit/13epQZU0Yeea9AuQvBJY?p=preview
https://plnkr.co/edit/zT21A6h08Va0o5dgkF9Z?p=preview
