### ISSUE TITLE
fix(dropdown): keyboardNav is not working

### ISSUE THREAD

**Issue by mkjeff** [valor-software/ngx-bootstrap#289]
The demo is static menu item markup, it work.
but, when use ngFor to render menu, item keyboard navigation has no effect.

I have track the call stack, all the same.

``` ts
elems[this.selectedOption].focus(); // not work, when element in template
```

**Comment by mkjeff** [comment]
Okay, I found the problem.
[Which HTML elements can receive focus?](http://stackoverflow.com/questions/1599660/which-html-elements-can-receive-focus)

HTMLAnchorElement/HTMLAreaElement with an **href**

so that if want to implement custom select component with dropdown directive, need use 

``` html
<ul class="dropdown-menu" role="menu" dropdownMenu>
    <li role="menuitem" *ngFor="#item of options">
         <a class="dropdown-item" href="javascript:void(0)" (click)="selectedOption=item">{{item}}</a>
    </li>
</ul>
```

**Comment by valorkin** [comment]
@mkjeff check demo it is working with beta.12

**Comment by mkjeff** [comment]
@valorkin  It is not a bug, please see my reply.

**Comment by valorkin** [comment]
@mkjeff ok, so what should I do? Or it is just an info to keep in mind?
