### ISSUE TITLE
Dropdown not working when inside *ngFor

### ISSUE THREAD

**Issue by Kizmar** [valor-software/ngx-bootstrap#2892]
### Bug description or feature request:
I'm trying to dynamically build navigation with a list of menu items that can have child items. As soon as I try to use the dropdown component inside an `*ngFor`, the `*dropdownMenu` won't display. I've tried SEVERAL variations with no luck.

Boiled down... I can drop simple examples in my app and they work. If I use it to render just one of the menu items and it's children, it works. As soon as I try to `*ngFor` the parent `<li>` (or even the `<ul>` for that matter), the dropdowns stop working with no error.

This does not work...
```
<li dropdown *ngFor="let menuItem of menuItems" (onShown)="onShown()" (onHidden)="onHidden()" (isOpenChange)="isOpenChange()">
  <a href dropdownToggle (click)="false">{{menuItem.name}}</a>
  <ul *dropdownMenu class="dropdown-menu">
    <li *ngFor="let child of menuItem.children">
      <a class="dropdown-item" href="#">{{child.name}}</a>
    </li>
  </ul>
</li>
```
These do work...
```
<li dropdown (onShown)="onShown()" (onHidden)="onHidden()" (isOpenChange)="isOpenChange()">
  <a href dropdownToggle (click)="false">{{menuItems[0].name}}</a>
  <ul *dropdownMenu class="dropdown-menu">
    <li *ngFor="let child of menuItems[0].children">
      <a class="dropdown-item" href="#">{{child.name}}</a>
    </li>
  </ul>
</li>

<li dropdown (onShown)="onShown()" (onHidden)="onHidden()" (isOpenChange)="isOpenChange()">
  <a href dropdownToggle (click)="false">{{menuItems[1].name}}</a>
  <ul *dropdownMenu class="dropdown-menu">
    <li *ngFor="let child of menuItems[1].children">
      <a class="dropdown-item" href="#">{{child.name}}</a>
    </li>
  </ul>
</li>
```

### Versions:
ngx-bootstrap: 2.0.0-beta.3
Angular: 4.3.0
Bootstrap: 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:
https://github.com/MarkPieszak/aspnetcore-angular2-universal

**Comment by IlyaSurmay** [comment]
https://plnkr.co/edit/0CxsM1g8yf5qjvQH2KF9?p=preview
Works fine here. I used the latest version but downgrading to 2.0.0-beta.3 didn't break anything.

**Comment by valorkin** [comment]
Can't reproduce, but could be an issue, please create plunker
Just a note: you can't use 2 template tags (which starts with *) on same element

**Comment by gerardcastell** [comment]
Hi! I'm currently facing the same problem, when I use a ngFor the dropdown doesn't work as expected. Any help?
Kind regards

**Comment by ljacobs-fb** [comment]
Experiencing this issue as well using ngx bootstrap 3.0.1 in an Angular 7 application.

I'm looping through objects and when an object's "Type" equals a certain type I want to display a dropdown button with dynamic options. 

The ngFor loop does not generate the dynamic options when inside the dropdown element. 

However, if I copy the loop outside of the button it generates the options just fine. 

Also, if I remove the dropdown directives from the elements and just let it print "normal html" it will print the options fine as well.
