### ISSUE TITLE
SOLVED BsDatePicker has z-index issues with bootstrap input-group 

### ISSUE THREAD

**Issue by ayotundeoludahunsi** [valor-software/ngx-bootstrap#2894]
In bootstrap, 

input-group .form-control has z-index = 2,

bsDatepicker has z-index=1

So just simply use style property in your template to set input field z-index = 0.

SOLVED.

**Comment by YuZaiShui** [comment]
wow,sounds terrible. If i have to set input z-index = 2, bsDatepicker will work not good.
