### ISSUE TITLE
Date Range Picker not showing the correct months when reopen the range popup

### ISSUE THREAD

**Issue by prasadkadiyala** [valor-software/ngx-bootstrap#2902]
Selected dates are not populating properly.

Suppose Select the date range oct 31, 2017 - Nov 30, 2017.   Again open the date range then it showing the starting month date properly but ending month it is showing as December without having any selection.

![screen shot 2017-10-24 at 11 17 48 am](https://user-images.githubusercontent.com/13884936/31926580-0391d87a-b8ad-11e7-869f-3f2cd531d210.png)
Note:  This issue happens when only the start date is selecting as the 31st of the month.

**Comment by valorkin** [comment]
Thanks, issue is still reproducible
