### ISSUE TITLE
not getting why i get this error when i craete a expandable list

### ISSUE THREAD

**Issue by Tanishkjain** [valor-software/ngx-bootstrap#2903]
To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<ion-list >
  <ion-item>
    [ERROR ->]<expandable></expandable>

    <ion-avatar item-start>
"): ng:///Tab1PageModule/Tab1Page.html@13:4
Error: Template parse errors:
'expandable' is not a known element:

**Comment by IlyaSurmay** [comment]
This is not related to ngx-bootstrap, closing.
