### ISSUE TITLE
(Datapicker) I cann't change language 

### ISSUE THREAD

**Issue by systemdo** [valor-software/ngx-bootstrap#2905]
Hi everybody. My inline datepicker in angular4 don't change the language.
I  used moment js and everything in this world, but nothing happened....

Bootstrap 3
Version  1.9.1

**Comment by IlyaSurmay** [comment]
Could you give a bit more information? plunkr for example
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-stack?file=app%2Fapp.module.ts

**Comment by valorkin** [comment]
Latest versions are working fine, please check docs.
