### ISSUE TITLE
DatePicker : Format and FirstDay

### ISSUE THREAD

**Issue by MatDepInfo** [valor-software/ngx-bootstrap#2906]
ngx-bootstrap@1.9.2
It's is impossible to set the format of the date : for example, I use the locale 'fr' and I want to display the date like this : dd/MM/yyyy. It's impossible for now.
Moreover, the first day in the week is Monday so it will be great if we could change the first day.

**Comment by SidekickJohn** [comment]
@MatDepInfo

1. A part of the formatting Issue is solved with Pull-Request [PR #2630 ](https://github.com/valor-software/ngx-bootstrap/pull/2630) and will be in next Version. It is also handled in this closed Issue [#2611](https://github.com/valor-software/ngx-bootstrap/issues/2611). Maybe you can see if this helps you.
2. The first day of week setting is in the roadmap. Further Info is in Issue [#2622](https://github.com/valor-software/ngx-bootstrap/issues/2622). Concerning the Starting Day I'm actually trying to solve this and provide a Pull Request. Right now I'm not sure how far I get with this though.

**Comment by valorkin** [comment]
Both fixes mentioned above are merged and published
John thanks :)
