### ISSUE TITLE
How to customize DISMISS_REASONS for modal?

### ISSUE THREAD

**Issue by elixiao** [valor-software/ngx-bootstrap#2911]
Can I customize  **DISMISS_REASONS** when using `modal.hide()` by passing params like `model.hide('ajax success')`?

**Comment by IlyaSurmay** [comment]
Hi. This isn't yet supported but you can do it anyway - use `setDismissReason('blablabla')` method of BsModalService. Please be aware that this won't overwrite default dismiss reasons (esc and backdrop click), therefore it will cause the effect you want only when you're closing modal via direct call of its `hide()` method.

**Comment by ghiscoding** [comment]
but if I want to return an object instead of a string, this isn't supported either :(
