### ISSUE TITLE
fix(typeahead): typeaheadLatinize works only if last letter has an accent

### ISSUE THREAD

**Issue by CyrilleGuimezanes** [valor-software/ngx-bootstrap#2912]
Hello,
### Bug description:

I'm using the typehead component. In my suggestion list I have some French words like:
"en cours", "activée", "terminée" and I would like to ignore accent during suggestion. 

I tried to use typeaheadLatinize and I got a strange behavior. 

When I write:
"activé" or "active" => OK  "activée" is suggested
"activée" => OK  "activée" is suggested
but 
"activee" => KO empty suggestion list

Suggestion seem to stop working when you type a letter after an accent.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta4

Angular: 4.4.3

Bootstrap: 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI

Regards,

**Comment by straumat** [comment]
Hi. This is an important feature for us and we know you are busy. But do you think you can give us an approximative delay for a fix ? Tahnk you.

**Comment by apotapcukv** [comment]
Dear CyrilleGuimezanes! 
As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.
