### ISSUE TITLE
Configurable options for using a default header (configurable title) and footer (default buttons OK and Cancel) 

### ISSUE THREAD

**Issue by Varshamathukumalli** [valor-software/ngx-bootstrap#2920]
Can we make a default template for all the popups to reduce the redundancy as most of the popups will have same header and footer and mostly the body will change for each popup, then instead of creating the template with header and footer again wherever required.
Is there a way if we can configure the library to make use of default header and footer templates?

**Comment by IlyaSurmay** [comment]
It's not very clear what you mean, please provide more info. Also, if it's just a general question, it's better to use [slack](https://ngx-slack.herokuapp.com/) for this

**Comment by bhaskerchari** [comment]
@IlyaSurmay ,

I believe her question is more of a below thing:

Is there a way if we can specify a default header and footer for all the popups and making it configurable and only specify body content which will avoid html boilerplate for all the popup's if we use the same header and footer every where?

If required we should be able to override the default header and footer with our own templates whereever required and no override is required whenever it is not required.

I am just thinking if we should have a configurable options such as below:

// Headers Configuration
[useDefaultHeader] = true;
[title] = "My Custom Popup Title"; // I should be able to give my own title eventhough I use default header.

// Footers Configuration
[useDefaultFooter] = true; // When enabled should display default footer buttons lets say 2 buttons Ok and Cancel.

// Also we should have a way if we can customize the default button labels something like below
[okButtonLabel] = "Done";
[cancelButtonLabel] = "Remove";

To take it to next level if we can also customize and configure our default header and footer templates at app level configuration as per my application needs it would be even great. What I mean is if I can tell the lib to use my own templates for header and footer overriding the default one's and which gets used throughout my app.

Thanks,
Bhasker

**Comment by Varshamathukumalli** [comment]
@bhaskerchari ,

This is what i am exactly looking at and thanks for detailing the information.
 
Thanks,
Varsha

**Comment by valorkin** [comment]
Custom templates for components are in roadmap for v2

**Comment by Varshamathukumalli** [comment]
Hi,

We are using v2.0.2 and didn't find that in docs. Is this released or any update on when can this be released?
