### ISSUE TITLE
Datepicker to input alignment

### ISSUE THREAD

**Issue by piotrmalecki** [valor-software/ngx-bootstrap#2922]
Is it possible to move calendar to be properly aligned to input?
![image](https://user-images.githubusercontent.com/3989677/32067287-f80aa02c-ba82-11e7-8822-21d9937b6d08.png)

**Comment by valorkin** [comment]
Please provide your html and styles, or plunker

**Comment by sezer** [comment]
https://valor-software.com/ngx-bootstrap/#/datepicker you can check demo page. Scroll page until any datepicker comes to nearly bottom and open the datepicker. You'll see.

![image](https://user-images.githubusercontent.com/1110304/32445903-384e461e-c318-11e7-9153-0f8f00ed770f.png)

**Comment by valorkin** [comment]
Hm it's centered, but it's correct for default placement value, you could just set it to bottom left

**Comment by valorkin** [comment]
positioning upgrade is a separate topic, but yep, we gonna get there soon

**Comment by Hesesses** [comment]
![image](https://user-images.githubusercontent.com/2721970/37824237-a0c4e634-2e94-11e8-9157-6da7065b6aaa.png)

There is a bug when the datepicker is placed on left / right side of the document and is not fully visible

**Comment by valorkin** [comment]
yep, I know, fix should lend in nearest month
in v3

**Comment by mrjohnr** [comment]
Same problem here.waiting for a fix

**Comment by mrjohnr** [comment]
Hi,tested with v3,but no fix for me,there are additional things to do?

**Comment by mrjohnr** [comment]
any chance so see a fix for that?
