### ISSUE TITLE
Suppress warnings fired off by ngx-bootstrap

### ISSUE THREAD

**Issue by jcoronel94** [valor-software/ngx-bootstrap#2923]
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.9.3

Angular: 4.4.4

Bootstrap: 3.3.7

### Build system:  Angular CLI

Hi, 

Is it possible to suppress warnings that get fired off by ngx bootstrap. For example I am using a datapicker and in the input tag I am directly placing disable which fires off a warning telling me not to do that when using reactive forms. I would just prefer not to see this warnings in the console log. 

I searched https://valor-software.com/ngx-bootstrap/#/ and haven't found anything regarding warnings. It is not a huge issue but an option that I would like to see available, if not already.

Thanks

**Comment by IlyaSurmay** [comment]
Hi.
Are you sure that this issue has something to do with ngx-bootstrap? Because the warning regarding `disabled` attribute with reactive forms is actually an Angular issue (https://github.com/angular/angular/issues/11324)

**Comment by jcoronel94** [comment]
Wow, 

That was really silly of me not to notice. Thanks for pointing that out. I'll refer to the link provided
