### ISSUE TITLE
i18n file-uploader

### ISSUE THREAD

**Issue by alessandrov** [valor-software/ngx-bootstrap#2931]
great modal, very intuitive, except for customizing the language!

Trying to replace those with German and Italian:

Choose File ... No File Chosen

please help

**Comment by IlyaSurmay** [comment]
Are you sure this has something to do with ngx-bootstrap?
Anyway, `Choose File` is predefined text and it's written in browser's language.
There are some tricks though which you can find in google, this one for example https://stackoverflow.com/questions/1944267/how-to-change-the-button-text-of-input-type-file
