### ISSUE TITLE
bsDaterangepicker  displayed values and locales

### ISSUE THREAD

**Issue by damand74** [valor-software/ngx-bootstrap#2932]
Hello,
I'm using date range picker localized for Italian language. It works well except for the displayed values in the input that are showed in English format.
I followed the example of the demo page of the project where the behavior is the same. 
How can I display dates in the localized format?

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.9.3

Angular: 4.3.6

Bootstrap: 3.3.7

**Comment by valorkin** [comment]
Hey, Italian localization located here: https://github.com/valor-software/ngx-bootstrap/blob/development/src/bs-moment/i18n/it.ts

If you see an issue there, please do PR :)
And don't forget to compare with moment.js
