### ISSUE TITLE
onclick datepicker

### ISSUE THREAD

**Issue by alexzatarain** [valor-software/ngx-bootstrap#2935]
hi all , i dont understand how can i catch the event click of the datepicker , i want to close the date picker when a date is selected. also i want to show the datepicker when a click occurs on a input type="text".
there is a way those 2 thing? 

thank you !

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:1.9.3

Angular:2.4.0

Bootstrap:3.3.7

**Comment by IlyaSurmay** [comment]
Now the datepicker provides the exact same functionality as you described - open on input click and close on date select. For example - https://valor-software.com/ngx-bootstrap/#/datepicker#themes

**Comment by alexzatarain** [comment]
hello,  as far as i understand 
<input type="text" class="form-control" bsDatepicker #dp="bsDatepicker" [bsConfig]="bsConfig">
is only working on ngx-bootstrap 2.0 beta+ , or im wrong? because when i use the module bsDatepicker on my app.modules i got an error that says te bstemplate cant be found.

**Comment by IlyaSurmay** [comment]
It also works on ngx bootstrap ^1.9.1. But it's better to use latest versions (1.9.3 and 2.0.0-beta.7)

**Comment by IlyaSurmay** [comment]
> because when i use the module bsDatepicker on my app.modules i got an error that says te bstemplate cant be found

I think this is related to #2854 if you're using System.JS instead of Angular CLI

**Comment by alexzatarain** [comment]
mmm well yeah im using system.JS  , but the problem is not the same ,  is related to the umd file not finding the file  ./bsdatepicker-view.html . i tried to change the path to the theme/bs folder and still got the error.

**Comment by alexzatarain** [comment]
Failed to load bs-datepicker-view.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load bs-datepicker-view.html

**Comment by IlyaSurmay** [comment]
I think it's the same, look at this comment https://github.com/valor-software/ngx-bootstrap/issues/2854#issuecomment-337265598
I can't give you any advice now except moving to Angular CLI :( We'll investigate this issue with missing template and release a fix

**Comment by IlyaSurmay** [comment]
Also using our latest beta (2.0.0-beta.7) fixes the error.

**Comment by alexzatarain** [comment]
yeah i know , but i cant upgrade to angular 4 . and the latest version needs angular 4 :(

**Comment by valorkin** [comment]
Unfortunately we can't support ng v2, cuz we need to support v4 and 5
