### ISSUE TITLE
[question] Angular 5 support

### ISSUE THREAD

**Issue by FrancescoBorzi** [valor-software/ngx-bootstrap#2961]
Is it safe to use ngx-bootstrap 1.x with Angular 5? Or shall I wait for 2.x to be stable?

**Comment by MattiJarvinen** [comment]
So for now 1.x doesn't cut it.

Just noticed date picker template still uses deprecated `<template>` syntax but that's the only thing I found out yet.

**Comment by cipchk** [comment]
getting error vis `ng build -prod`:

```
ERROR in Error at C:/Users/asdf/Desktop/work/ngx-countdown/node_modules/ngx-bootstrap/datepicker/daypicker.component.d.ts.DayPickerComponent.html(53,38):  ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" [ERROR ->]let-rowz="$implicit" let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].sec")
Error at C:/Users/asdf/Desktop/work/ngx-countdown/node_modules/ngx-bootstrap/datepicker/daypicker.component.d.ts.DayPickerComponent.html(53,59):  ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" let-rowz="$implicit" [ERROR ->]let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6].sec")
```

**Comment by mbark** [comment]
@cipchk Using `ngx-bootstrap@2.0.0-beta.7` resolves that

**Comment by FrancescoBorzi** [comment]
is anyone already using the 2.x in production?

**Comment by bogacg** [comment]
I have an app with 2.0.0-beta.7 and today I've tested it with Angular 5. Didn't have any issues so far.

**Comment by valorkin** [comment]
I will publish beta as default today, to avoid such questions :)

**Comment by FrancescoBorzi** [comment]
@valorkin for a production environment, would you recommend to stay with ngx-bootstrap 1.x and angular 4.x until the next ngx-bootstrap becomes stable, or it's better to use the newest even if it's still beta?

**Comment by rsadyhov** [comment]
I'm still getting next error with 2.0.0-beta.8 version:

`ERROR in Error at /Users/rsadyhov/assurance/assurance_se_ui/node_modules/@assurance/user-management/node_modules/ngx-bootstrap/datepicker/daypicker.component.d.ts.DayPickerComponent.html(53,38):  ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" [ERROR ->]let-rowz="$implicit" let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].sec")
Error at /Users/rsadyhov/assurance/assurance_se_ui/node_modules/@assurance/user-management/node_modules/ngx-bootstrap/datepicker/daypicker.component.d.ts.DayPickerComponent.html(53,59):  ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" let-rowz="$implicit" [ERROR ->]let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6].sec")
`

**Comment by valorkin** [comment]
It's better to use beta, cuz we use it in prod :)

**Comment by FrancescoBorzi** [comment]
@valorkin ok, thanks a lot

**Comment by wengera** [comment]
Using angular 4.2 or 5.2, ngx-bootstrap is said to be an invalid install by npm no matter what version of it I use. I'm pulling my hair out because I can't publish my application as the "dotnet publish" command unisntalls "ngx-bootstrap" from my application everytime and then exits saying it can't find "ngx-bootstrap". ngx-boostrap 2.0 says it requires angular 5.2 which I have and it still gets removed by "dotnet publish" every time....

**Comment by valorkin** [comment]
maybe donnet publish has it's own package management control
