### ISSUE TITLE
Issure durring rollup with latest typescript version

### ISSUE THREAD

**Issue by lexon0011** [valor-software/ngx-bootstrap#2967]
Since I updated typescript from 2.3.4 to 2.6.1 I get the following error during angular rollup:

![2017-11-02 20_30_09-issues valor-software_ngx-bootstrap github](https://user-images.githubusercontent.com/16290662/32349075-28426732-c016-11e7-91fe-9d4597275d4e.png)

After rolling back to the previous typescript verison, everything works. Anyone knows why angular rollup in combination with the latest typescript version produce the above error?

**Comment by valorkin** [comment]
God question, but for ng 4 & 5 better to use ts 2.4.2. Not sure that ts 2.6 supported by angular
