### ISSUE TITLE
TABS (select) not fired when it is the first TAB

### ISSUE THREAD

**Issue by cesarZubillaga** [valor-software/ngx-bootstrap#2969]
I need this output to be called on the first render of my component as i need to do several things at this time.

Thanks.

**Comment by IlyaSurmay** [comment]
If you're using a component in tab you can use its `ngOnInit()` to do some operations you need to do.

**Comment by valorkin** [comment]
Triggering events on render would be undesirable, 
Cuz it will trigger changes inside of render cycle, 
Use angular life cycle events, like on init or after content init, to achieve desired behavior
