### ISSUE TITLE
angular 5 problem

### ISSUE THREAD

**Issue by itcozum** [valor-software/ngx-bootstrap#2971]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Bug description or feature request:

I'm trying to use your component in my angular 5 project but getting the below error message 

ERROR in Error at D:/PROJELER/2017/tps-hr/hrWeb/node_modules/ngx-bootstrap/datepicker/daypicker.component.d.ts.DayPickerComponent.html(53,38):  ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" [ERROR ->]let-rowz="$implicit" let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].sec")
Error at D:/PROJELER/2017/tps-hr/hrWeb/node_modules/ngx-bootstrap/datepicker/daypicker.component.d.ts.DayPickerComponent.html(53,59):  ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" let-rowz="$implicit" [ERROR ->]let-index="index">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6].sec")

Any plan soon to support angular 5

Thanks in advance.
Nelly

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-stack?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

**Comment by fchiumeo** [comment]
what version of ngx-bootstrap use?

**Comment by gofreddo** [comment]
+1

**Comment by gofreddo** [comment]
That error is fixed in 2.0.0-beta.8.  

Unfortunately in 2.0.0-beta.8 I now get:

ERROR in client/app/email-compose/email-compose.component.ts(6,10): error TS2305: Module '"/Users/jeffwilde/Projects/cryptototrade/node_modules/ngx-bootstrap/modal/modal-options.class"' has no exported member 'BsModalRef'.
[1] client/app/admin-email-template/admin-email-template.component.ts(16,10): error TS2305: Module '"/Users/jeffwilde/Projects/cryptototrade/node_modules/ngx-bootstrap/modal/modal-options.class"' has no exported member 'BsModalRef'.

**Comment by johaven** [comment]
Try to replace in your code:
```javascript 
import {BsModalRef} from 'ngx-bootstrap/modal/modal-options.class'
```
by
```javascript 
import {BsModalRef} from 'ngx-bootstrap/modal'
```

**Comment by juliusstoerrle** [comment]
Had the same Error, @johaven 's fix worked for me! Thanks.

**Comment by valorkin** [comment]
@johaven thanks:)

**Comment by dnaprawa** [comment]
Had the same Error, after update to version 2.0.0-beta8. @johaven solution works. Thank you !!

**Comment by ghost** [comment]
node_modules/ngx-bootstrap/locale"' has no exported member 'hu'.

**Comment by valorkin** [comment]
Hu not yet published

**Comment by valorkin** [comment]
Tomorrow

**Comment by ghost** [comment]
Thank you.

Is there a way for datepicker to only save date on click and not time. Similar to options in AngularJs? When user is picking his past experience it should not pick time from calendar. Not able to avoid it on rebinding the data and re editing calendar from form. This should happen on html tag i believe and not model.

**Comment by valorkin** [comment]
Datepicker works with raw date objects, plus its planned to add timepicker inside of datepicker

**Comment by ghost** [comment]
I wish there was another date picker with out time in it. There is a problem with 2 way binding which adds up the time and that does not bind on to data tables from the forms in the SPA. It adds up time to other models which is not needed to show.to end users. :(

**Comment by valorkin** [comment]
Bind datepicker to property setter wich will cut of time on save
