### ISSUE TITLE
The pipe 'paginate' could not be found 

### ISSUE THREAD

**Issue by edwinfranco** [valor-software/ngx-bootstrap#2973]
Hello, I have had issues implementing the pagination on angular 4, I was able to set the pagination, getting all the values that I need according to the total records (_in the console_), 

but when I refer the pagination to the table whit this code in the *ngFor  **_| paginate: { itemsPerPage: 50, currentPage: 1 }_** I get an error: 

**_The pipe 'paginate' could not be found._**

I have tried with all the ngx-bootstrap versions and they haven't worked, the same I have tried with many solutions but nothing, I hope all of you can help me.

**Comment by valorkin** [comment]
Hey, pipe paginate is part of https://github.com/michaelbromley/ngx-pagination
Not ngx bootstrap :)
