### ISSUE TITLE
Can not close Parent Modal in Nested Modal pop up

### ISSUE THREAD

**Issue by AbhijitMuke** [valor-software/ngx-bootstrap#2976]
I am having problem with finding parent modal reference in nested modal pop up scenario. Can not close Parent modal pop after closing child modal pop up. Please help.

Please find plunker - [https://plnkr.co/edit/xl5R8gHYuO2aZNVCdcke](https://plnkr.co/edit/xl5R8gHYuO2aZNVCdcke)

**Comment by grzegorz-jazurek** [comment]
@AbhijitMuke problem is in your code because you override `bsModalRef` parent modal reference with reference to new modal. 
Here is plunker which work as you expect: https://plnkr.co/edit/79hdTU1IIO2AWZgoDkFl?p=preview
