### ISSUE TITLE
Dropdown wrong position & incorrect styles

### ISSUE THREAD

**Issue by johaven** [valor-software/ngx-bootstrap#2984]
ngx-bootstrap: 2.0.0-beta.8
Angular: 5.0.0
Bootstrap: 4 Alpha 6
Bug: Dropdown position is shifted to right
Code:
```
<a dropdownToggle href="javascript:void(0)" class="dropdown-toggle">
  ...
</a>
<ul *dropdownMenu class="dropdown-menu">
  <li class="user-header">
   ...
  </li>
...
```
Result with added styles (not required):
<img width="787" alt="capture d ecran 2017-11-06 a 20 36 02" src="https://user-images.githubusercontent.com/5459596/32460683-d7f0f34a-c333-11e7-9ea8-4b15974d81c9.png">

But dropdown direction is not set in code ... ?
```javascript
if (dropdown) {
                _this._renderer.addClass(dropdown, 'show');
                if (dropdown.classList.contains('dropdown-menu-right')) {
                    _this._renderer.setStyle(dropdown, 'left', 'auto');
                    _this._renderer.setStyle(dropdown, 'right', '0');
                }
                if (_this.direction === 'up') {
                    _this._renderer.setStyle(dropdown, 'top', 'auto');
                    _this._renderer.setStyle(dropdown, 'transform', 'translateY(-101%)');
                }
            }
```

**Comment by IlyaSurmay** [comment]
Hi, could you reproduce this issue in plunkr/stackblitz? 
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts
