### ISSUE TITLE
docs(typeahead): edit documentation for typeahead for making it more clear

### ISSUE THREAD

**Issue by MaikeFillmer** [valor-software/ngx-bootstrap#2986]
### Bug description or feature request:
Edit to the Documentation for TypeAhead, specifically the "typeaheadSingleWords" description. It does not make much sense. It currently reads:

"If true the text "exact phrase" here match would match with match exact phrase here but not with phrase here exact match (kind of "google style")."

### Link to the issue:
https://valor-software.com/ngx-bootstrap/#/typeahead

**Comment by 5earle** [comment]
i would like to give this a try
