### ISSUE TITLE
Datepicker : Initial value doesn't take locale format into account

### ISSUE THREAD

**Issue by will421** [valor-software/ngx-bootstrap#2991]
### Bug description or feature request:
When settings the initial value of a datepicker through ngModel, the set format seems to be ignored.
Format is used when selecting a new value.

### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/ngx-bootstrap-datepicker-tpmm9q
I set in app.module the local to 'fr'. But the initial value seems to be format 'en' and it switch to 'fr' when selecting a new value.

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 2.0.0-beta.8
Angular: 4.3.6
Bootstrap: 3.3.7 

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI

**Comment by timaxapa** [comment]
Any updates?

**Comment by leomayer** [comment]
Just stupid q:
Why you are working on an `<input>` instead of `<bs-datepicker>`? At least with this tag I experience no problems

**Comment by jquince** [comment]
@leomayer Because all of the examples in the docs use <input>

**Comment by valorkin** [comment]
working on extracting date adapter, it will cover current use case

**Comment by danieleratti** [comment]
Any update about this issue? It happens also on 'it' locale.
Initially it shows the correct locale but when i write for example 1/12/2017 (1st of December in Italian locale) it becomes 12/1/2017 (12th of January in Italian locale).

**Comment by alessandro-dallatorre** [comment]
Looks like this has been fixed in version 2.0.0-beta9. Thank you so much

**Comment by valorkin** [comment]
Initial value is fixed,
When you manually enter - not for all locales

**Comment by silviodeligios** [comment]
fix this please :'(

**Comment by will421** [comment]
> fix this please :'(

In my case it's fixed since beta.9.
Thank you guys ^^

**Comment by will421** [comment]
> fix this please :'(

In my case it's fixed since beta.9.
Thank you guys ^^

**Comment by valorkin** [comment]
Manual input parse will be merged next week

**Comment by jluc-andrei** [comment]
it work's with the beta.9
but it's not work's with the rc.0

**Comment by yassirh** [comment]
This issue can be reproduced with the 2.0.2 release. Any chance this is going to be fixed soon ?

**Comment by tvbegovic** [comment]
I have the same issue with 2.0.3. Trying to use en-gb (DD/MM/YYYY) format and initial value is in MM/DD/YYYY format. After selecting date in datepicker, I get correct format. Also, if I change date manually and open picker again I get the correct format. Only the first displayed format is wrong.

**Comment by guilhermenass** [comment]
I have the same problem. Any updates?

My initial value is in MM/DD/YYYY instead DD/MM/YYYY.

**Comment by KerriDevine** [comment]
@valorkin I notice this issue is closed, but we are still running into issues with the date format. Should we create a new issue?
