### ISSUE TITLE
fix(popover): popover with custom template crashes in IE

### ISSUE THREAD

**Issue by ashley-hunter** [valor-software/ngx-bootstrap#2994]
### Bug description or feature request:
When I have a popover with a custom template on an input element in IE the browser crashes when I click on input to display popover

### Plunker/StackBlitz that reproduces the issue:
https://plnkr.co/edit/KrBsCONd9ix0wuKISKVy?p=preview

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.9.3 (also tried with 2 beta 8 same issue)

Angular: 4.4.6

Bootstrap: 3.3.6

### Build system: Angular CLI, System.js, webpack, starter seed:
SystemJS

**Comment by IlyaSurmay** [comment]
Very strange one. After investigating I found out that the issue has something to do with css - if you remove `input-group` class from parent div of input, everything will work as it should. Also removing `display: table` property from its css rules also solves the issue. This is a workaround that you can use for now.
