### ISSUE TITLE
fix(datepicker): delete input field date and pick a new date not working

### ISSUE THREAD

**Issue by mrajaraman** [valor-software/ngx-bootstrap#2996]
### Bug description or feature request:
When a date is selected, click on input again (calendar opens), delete the date in the field, now select a date in the calendar. Calendar closes, new date is not updated in the field.

### Plunker/StackBlitz that reproduces the issue:
**https://valor-software.com/ngx-bootstrap/#/datepicker**

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.9.3

Angular: 4.4.3

Bootstrap: 3.3.7

**Comment by valorkin** [comment]
issue is reproducible, not sure it worth to fix
cuz in v2 will be added focus trap for datepicker

**Comment by mrajaraman** [comment]
When is v2 getting released? Thanks.

**Comment by valorkin** [comment]
This year :) my initial plan was to release it a week ago, but you how it happens. I have a bunch of tests to merge and fix locale, there are a bunch of issue cuz locale is a part of config

**Comment by mrajaraman** [comment]
Sure, Thanks, great work!

**Comment by pepemiso16** [comment]
@valorkin , I would like to ask if the new version is now ready? thanks
