### ISSUE TITLE
Currently broken

### ISSUE THREAD

**Issue by ekarlso** [valor-software/ngx-bootstrap#30]
Hi, is the example currently broken?

**Comment by ekarlso** [comment]
I see there's a err when it's Loading

**Comment by valorkin** [comment]
nope, works good
are your browser is supported by angular2? 
https://saucelabs.com/u/angular2-ci
most probably no :)

**Comment by ekarlso** [comment]
Valorkin are you on IRC? :)

**Comment by valorkin** [comment]
https://gitter.im/valor-software/ng2-bootstrap
