### ISSUE TITLE
Continuation of execution

### ISSUE THREAD

**Issue by codehippie1** [valor-software/ngx-bootstrap#3001]
@valorkin : How do we achieve a continue effect? (Via a callback)

E.g. How do we achieve something like this? - https://craftpip.github.io/jquery-confirm/ - See my comments

```
function someFunc() {
var state = some;
$.confirm({
    title: 'Confirm!',
    content: 'Simple confirm!',
    buttons: {
        confirm: function () {
            // Access state here
            $.alert('Confirmed!');
        },
        cancel: function () {
            $.alert('Canceled!');
        },
        somethingElse: {
            text: 'Something else',
            btnClass: 'btn-blue',
            keys: ['enter', 'shift'],
            action: function(){
                $.alert('Something else?');
            }
        }
    }
});
}
```

**Comment by IlyaSurmay** [comment]
If you want to ask a question it's better to use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/)
A simple example for you - https://plnkr.co/edit/iCWEmB77d1QAHXg0ueLE?p=preview (a first modal opens with button inside and when you click on it, first modal closes and the second one opens)
