### ISSUE TITLE
datepicker input is always dirty when ngModel is a non-null value

### ISSUE THREAD

**Issue by JimJafar** [valor-software/ngx-bootstrap#3014]
### Bug description or feature request:

The datepicker component has the isDirty flag set shortly after being loaded when ngModel is not null. 

### Plunkr

https://plnkr.co/edit/odlMZcGA7WzuO75TSeCD?p=preview 

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.9.3

Angular: 4.3.2

Bootstrap: bootstrap-sass 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:

Webpack
[yo angular2-typescript generator](https://github.com/shibbir/generator-angular2-typescript) version 0.8.1.

**Comment by JimSangwine** [comment]
Sorry - this was an implementation issue on our end.

**Comment by mrajaraman** [comment]
We also have the same issue. May I know when it will get fixed?

**Comment by JimJafar** [comment]
This is actually a big problem - it's breaking form validation. Can I help with fixing it if you guys are too busy?

**Comment by IlyaSurmay** [comment]
Sure, that would be awesome :)

**Comment by JimJafar** [comment]
Excellent news, thanks @valorkin !
Sorry - we are in crunch time so I didn't get a chance to look at it.

**Comment by valorkin** [comment]
Will be published this thusday, but you can check here http://ngx-bootstrap.surge.sh/#/datepicker

**Comment by JimJafar** [comment]
Hi @valorkin Will you be publishing a new release with this fix? I'm not trying to rush you - just checking so we can set our release timeline :)

**Comment by valorkin** [comment]
I was planning to do release yestarday, but QA took couple of dayoffs,
so she will test it on Monday, and I will be able to release it

**Comment by JimJafar** [comment]
Fantastic, thank you!

**Comment by ghost** [comment]
@valorkin 
Error
on edit the form, cancel submission with form reset.
display new form, then it displays calendar input as invalid and dirty, but html text boxes seem to work fine.
except that calendar box

**Comment by valorkin** [comment]
@chanakyanet could you provide a sample please?

**Comment by ghost** [comment]
@valorkin 
could not complete the plunk looks like there is some unknown issue, could you please help me run the below.
https://plnkr.co/edit/E64y9HUKdiAHrp1Q79hm?p=preview so i could work it out.

**Comment by mfrieman** [comment]
Was this fix ever released because I'm having the same issue.

**Comment by kobayakid** [comment]
i came across this issue and a possible workaround may be calling markAsPristine() and markAsUntouched() form methods after setting the null value. it might work on some cases.
