### ISSUE TITLE
fix(tabs): after removing all tabs and adding a new one, it isn't marked as active

### ISSUE THREAD

**Issue by panwroblewski** [valor-software/ngx-bootstrap#3018]
Hi,

II have encountered a problem, that I have not found an open issue related to.
I am using dynamic tabs created in *ngFor of a an array. They can me added or removed. When all elements are removed and then start adding tabs no content tabs are created only nav-link for tabs.

Im using "ngx-bootstrap": "1.9.3",

Do you have any ideas?

**Comment by IlyaSurmay** [comment]
After you remove all tabs and add a new one, it isn't marked as active. You need to set its `active` property to `true` manually until we fix it.

**Comment by IlyaSurmay** [comment]
Closed as works as expected. If you're using dynamic tabs, there are two ways to manage their `active` property: don't use `[active]` binding and the first tab will be marked as active (even when all tabs are removed and new ones are added), or manually set `active` property for each tab.
