### ISSUE TITLE
ng2-bootstrap@1.0.7 requires a peer of angular2@2.0.0-beta.9 but none was installed

### ISSUE THREAD

**Issue by ZigaVukcevicDev** [valor-software/ngx-bootstrap#302]
I have tried to install it but I get this error:

`ng2-bootstrap@1.0.7 requires a peer of angular2@2.0.0-beta.9 but none was installed`

These are my dependencies:

```
  "dependencies": {
    "angular2": "^2.0.0-beta.9",
    "es6-module-loader": "^0.17.8",
    "es6-shim": "^0.33.3",
    "ng2-bootstrap": "^1.0.7",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "~0.19.18",
    "zone.js": "0.5.15"
  }
```

What is wrong? Thank you in advance.

**Comment by valorkin** [comment]
This is as designed behavior, to avoid several ng2 versions, check ng2 quick start doc.
Good luck in ng2 lands :)
