### ISSUE TITLE
why "left" gets 15px all the time in typeahead-container

### ISSUE THREAD

**Issue by MahmoudHboubati** [valor-software/ngx-bootstrap#3020]
https://github.com/valor-software/ngx-bootstrap/blob/d97211b69f33ff2d215c2f2fc57f896febc50310/src/typeahead/typeahead-container.component.ts#L28

**Comment by IlyaSurmay** [comment]
`top` and `left` properties are calculated every time and they depend on placement option.
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead
