### ISSUE TITLE
docs(migration): add docs how to migrate from ngx-bootstrap 1.9.x to 2.0.x

### ISSUE THREAD

**Issue by FrancescoBorzi** [valor-software/ngx-bootstrap#3022]
We are currently using ngx-bootstrap 1.9.x in production and would like to migrate to 2.0.x.

Unfortunately there are some breaking changes, especially with the Datepicker component, so the path is not really straightforward. I was wondering if there are some kind of guidelines that we can follow and proceed without breaking our functionalities.

Thanks a lot for your awesome library!

**Comment by valorkin** [comment]
I hope this doesn't an actual issue already )
