### ISSUE TITLE
When datepicker meridian is set to false, the ngModel date i am using starts at 1970 rather than the current time.

### ISSUE THREAD

**Issue by Damie95** [valor-software/ngx-bootstrap#3023]
When using the standard 12 hr format, the year/month/time are correctly initialised to the current date/time.
when switching over to meridian="false", the year/month/time are incorrectly initialised to January in the year 1970 rather than the current date/time.

**Comment by valorkin** [comment]
I suppose issue is about timepicker, not timepicker
please provide reproducible sample,
cuz I can't reproduce this issue with latest version of ngx-bs
thanks in advance
