### ISSUE TITLE
Date setting not happening properly for two Date Picker Control on same page

### ISSUE THREAD

**Issue by srikant21** [valor-software/ngx-bootstrap#3027]
Current Behaviour:-
I am using 2 date picker control on my page.When i click on toggle button of first date and selecting any date it is setting the date for the second Date picker.In no way it is allowing me to set the first Date Picker
Expected Behaviour:-
The Date Picker should set its own date when it clicks on the toggle button.

### Plunker/StackBlitz that reproduces the issue:
https://plnkr.co/edit/DepDNsG9m0n2sl6eujbm?p=preview

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:^1.9.3

Angular:4.2.4

### Build system: Angular CLI, System.js, webpack, starter seed:
Angula Cli

**Comment by IlyaSurmay** [comment]
Your plunkr doesn't even have `BsDatepickerModule`, so it shows nothing. Please fix your plunkr and add some demo that shows this issue, otherwise it will be closed

**Comment by srikant21** [comment]
Please find the perfect plunkr
https://plnkr.co/edit/DepDNsG9m0n2sl6eujbm?p=preview

**Comment by IlyaSurmay** [comment]
You have duplicated template references (`#dp="bsDatepicker"` is used for both datepickers). Changing template variable name for second datepicker will solve this.
https://plnkr.co/edit/FGOcj79X1mx3ZPMBKX6C?p=preview
