### ISSUE TITLE
Typeahead vs. ng2-select

### ISSUE THREAD

**Issue by bobwiller** [valor-software/ngx-bootstrap#3031]
This is probably a question for @valorkin but, according to [#769](https://github.com/valor-software/ng2-select/issues/769), the Typeahead control was supposed to replace the ng2-select control.

My problem is that I was using the "Children" feature (so a parent-child hierarchy in a select box), but it appears that ng2-select is deprecated in favor of this project (which I am also using which is nice).  Ng2-select no longer builds nor does it work in my current project so I am stuck until I find a replacement.

So my question is, does the TypeAhead control support everything ng2-select does, and if not, will it?  And if not, does anyone have suggestions for an alternative?

Thanks,
Bob

**Comment by davidsekar** [comment]
To add : Multiple selection feature is missing in typeahead

**Comment by IlyaSurmay** [comment]
ng2-select was updated so it should build ok.
in Feb we'll probably focus on rewriting typeahead and merging ng2-select into ngx-bs

**Comment by evgenyfedorenko** [comment]
We are using ng2-select in our app but it looks like it is not supported anymore.
We want to update to Angular 9 and ng2-select does not support Ivy.
Is typeahead is something we could use instead? Are there any features which typeahead is missing which are present in ng2-select?

Thank you.
