### ISSUE TITLE
fix(tooltip): tooltips with delay continue displaying even if not hovering after timeout

### ISSUE THREAD

**Issue by Paquan** [valor-software/ngx-bootstrap#3038]
When you have multiple elements with tooltips and the tooltips have a delay, I expect the tooltips to show up after hovering the element for that specific delay time. But I expect that the tooltips don't show up when I stop hovering the element before that time is up.
But in fact the Tooltips show up if I hit them once no matter where my mouse is after that timeout.

See this example: https://stackblitz.com/edit/ngx-bootstrap-4r1ab4

Try to move the mouse really quick over many elements in the table.

ngx-bootstrap: 1.9.3

Angular: 4.3.6

But also tested it with Angular 5 and ngx.bootstrap 2.0.0-beta.8

**Comment by tmowbrey** [comment]
This issue is affecting me as well. I'm not sure how to resolve it.

**Comment by danielordonez** [comment]
Same here, bootstrap 4 beta 2 and ngx bootstrap 2 beta 10
