### ISSUE TITLE
typeaheadScrollable doesn't work

### ISSUE THREAD

**Issue by mikone** [valor-software/ngx-bootstrap#3040]
When i use typeaheadScrollable, i got always the error.
Even with the example in the documentation.

console.js:32 Unhandled Promise rejection: Template parse errors:
Can't bind to 'typeaheadScrollable' since it isn't a known property of 'input'. ("<input [(ngModel)]="selected"
[typeahead]="states"
[ERROR ->][typeaheadScrollable]="true"
[typeaheadOptionsInScrollableView]="5"
class="form-control">
"):

**Comment by IlyaSurmay** [comment]
Which version of ngx-bootstrap are you using?
Also, could you create a plunkr/stackblitz with reproduction?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by mikone** [comment]
Hi @IlyaSurmay the error was mine, please close the issue.
I'am sorry

**Comment by smith-jarvis** [comment]
Hey @mikone  I am getting same error. so what was the wrong in it & what the solution?

**Comment by pzontrop** [comment]
@mikone please elaborate on what exactly was the cause of this error. I also have this problem and have a hard time figuring out what happened. It works without the scrollable but not with.
