### ISSUE TITLE
BsModalRef - cannot convert type

### ISSUE THREAD

**Issue by fadelguy** [valor-software/ngx-bootstrap#3043]
ngx-bootstrap: 2.0.0-beta.8
Angular: 5.0.1
Bootstrap: 3

I have just upgrade my angular 4 to angular 5
and upgrade ngx-bootstrap 1.9.3 to 2.0.0-beta.8

I can open popups from component all working fine, but i geting error message:

> Cannot convert type 'BsModalRef' to type 'BsodalRef': Type BsModalRef declares property 'hide' as field, but type BsModalRef declares it as a method.

I have service that manage all my popups.

import { BsModalRef } from 'ngx-bootstrap/modal/bs-modal-ref.service'

@Injectable()
export class PopupsService {
  constractor(private modalService: BsModalService){}
  
  bsModalRef: BsModalRef;
  
  openDemoPopup(){
     this.bsModalRef = this.modalService.show(demoComponent); -------> here i getting the error.
  }
}

**Comment by IlyaSurmay** [comment]
A plunkr / stackblitz with reproduction would help :)
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by fadelguy** [comment]
here a plunkr:
https://plnkr.co/edit/0D3MIImjwZ2FXEtcY6hH?p=preview
