### ISSUE TITLE
Datepicker - setting model to "null" cause error

### ISSUE THREAD

**Issue by timaxapa** [valor-software/ngx-bootstrap#3044]
### Description
NullReference error on set datepicker model to null in console

### Plunker/StackBlitz that reproduces the issue:
https://plnkr.co/edit/NRHoPqWgNIpCP6r6QEx9?p=preview

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 2.0.0-beta.8
Angular: 4.4.6
Bootstrap: 3

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI: 1.4.9

![image](https://user-images.githubusercontent.com/9010313/32888644-5e86f92c-cae1-11e7-87a0-680a1b9e926e.png)

**Comment by valorkin** [comment]
@timaxapa forget it, it's old datepicker engine
this UI will be added as a theme to new engine shortly

**Comment by valorkin** [comment]
thanks for note, need to mark it as deprecated
