### ISSUE TITLE
fix(dropdown): dropdowns with hover trigger need to be clicked twice for first time appearing at mobile and tablet devices

### ISSUE THREAD

**Issue by orphen92** [valor-software/ngx-bootstrap#3048]
Hi i'm try to make a dropdown  menu on hover.
All works great but when i try my menu on responsive its no working good

For show the dropdownmenu we need to click two times the first time.
I think when i click the first time angular add and remove class imediatly

we have the same comportement on the sample here
https://valor-software.com/ngx-bootstrap/#/dropdowns#nested-dropdowns

try in responsive mode and you can see we need to click two time the first time to show the hover menu

Can you help me please?

this is my code
```html
<ul id="menu-main-menu" class="nav navbar-nav">
        <li #dp="bs-dropdown" dropdown triggers="hover" class="btn-group">
          <a dropdownToggle (click)="false" (mouseleave)="dp.hide()" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
            Consoles
          </a>
          <div *dropdownMenu class="dropdown-menu">
            <ul role="menu">
              <li class="menu-item menu-item-type-custom menu-item-object-custom">
                  Presentation
              </li>
            </ul>
          </div>
        </li>
</ul>
```

**Comment by prinzdezibel** [comment]
If you remove `data-toggle="dropdown"` from your dropdownToggle markup, it will work.

**Comment by idris-rampurawala** [comment]
```
<div class="btn-group" dropdown triggers="hover" 
  #dp="bs-dropdown">
  <ul *dropdownMenu class="dropdown-menu" role="menu" 
(mouseleave)="dp.hide()">
```
Above code snippet will work... I have tried and tested the same.

**Comment by daniloff200** [comment]
Please, use the solution above, that should help
