### ISSUE TITLE
Peer ng2-bootstrap@1.0.7 wants angular2@2.0.0-beta.9

### ISSUE THREAD

**Issue by germanferrero** [valor-software/ngx-bootstrap#307]
When trying:

npm i ng2-bootstrap --save

i get:

npm WARN peerDependencies The peer dependency angular2@2.0.0-beta.9 included from ng2-bootstrap will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency es6-shim@^0.33.3 included from angular2 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency zone.js@0.5.15 included from angular2 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Linux 3.16.0-62-generic
npm ERR! argv "/home/gf/.nvm/versions/node/v4.3.2/bin/node" "/home/gf/.nvm/versions/node/v4.3.2/bin/npm" "i" "ng2-bootstrap"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angular2@2.0.0-beta.11 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer ng2-bootstrap@1.0.7 wants angular2@2.0.0-beta.9

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gf/buenafe/frontend/npm-debug.log

Seems like npm package is not up to date, because in the repo peer dependency is beta 11.

**Comment by valorkin** [comment]
beta.11 has known issues, this is why ng2-bootstrap not yet updated
see here
https://github.com/valor-software/ng2-bootstrap/pull/305
