### ISSUE TITLE
feat(datepicker): provide an option for custom years math

### ISSUE THREAD

**Issue by gdunghi** [valor-software/ngx-bootstrap#3070]
**edited by valorkin**: How can i custom date to buddhist year

Hi . how  can i custom date format to buddhist year
   example : 2017 to 2560

<img width="283" alt="screen shot 2560-11-19 at 15 27 33" src="https://user-images.githubusercontent.com/1131300/32988833-dfd56d06-cd3e-11e7-9406-dcab794328bd.png">

ngx-bootstrap: 1.9.3

Angular: 4

Bootstrap: 4

**Comment by IlyaSurmay** [comment]
Hi. There's no support for custom formats for now.

**Comment by valorkin** [comment]
@gdunghi doesn't momentjs has support for it?

**Comment by daniloff200** [comment]
Looks like, that's done for now, and available in ver 5.5.0
Please, check https://github.com/valor-software/ngx-bootstrap/pull/5470 and  https://github.com/valor-software/ngx-bootstrap/issues/3893
