### ISSUE TITLE
(feat) Timepicker - Set model default value on incorrect input

### ISSUE THREAD

**Issue by timaxapa** [valor-software/ngx-bootstrap#3074]
### Bug description or feature request:
On direct text input with incorrect values set model to default value

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 2.0.0-beta.8
Angular:
4.4.6
Bootstrap:
3
### Build system: Angular CLI, System.js, webpack, starter seed:
Angular-CLI: 1.4

[Demo](https://drive.google.com/open?id=1Z_6NlfpfKMG60VKpKWAc7kaimtlk4tZ5)

**Comment by IlyaSurmay** [comment]
Duplicatre of #2726
