### ISSUE TITLE
ngx-bootstrap is not working for dropdown menu

### ISSUE THREAD

**Issue by kamalakkanni** [valor-software/ngx-bootstrap#3076]
Hi

I would have installed ngx-bootstrap.

added below code in app.module.ts

import { BsDropdownModule } from 'ngx-bootstrap/dropdown'
@NgModule({
  imports: [BsDropdownModule.forRoot(),...]
})
export class AppModule(){}

added below lines app.component.html

<div  class="dropdown" dropdown>
    <a dropdownToggle class="pull-right text-center btn btn-setting dropdown-toggle"  data-toggle="dropdown" aria-haspopup="true" aria- expanded="true"><i class="fa fa-cog"></i></a>
    <ul *dropdownMenu class="dropdown-menu" role="menu" aria-labelledby="menu1">
        <li role="presentation">  <a role="menuitem" tabindex="-1" href="#" data-toggle="modal" data-target="#myModal"><i class="fa fa-cog"></i>Settings</a></li>
    </ul>
</div>
my package.json is

{
 "name": "offline-new",
 "version": "0.0.0",
 "license": "MIT",
 "angular-cli": {},
 "scripts": {
"ng": "ng",
"start": "ng serve",
"test": "ng test",
"pree2e": "webdriver-manager update --standalone false --gecko false",
"e2e": "protractor"
 },
"private": true,
"dependencies": {
"@angular/common": "^2.3.1",
"@angular/compiler": "^2.3.1",
"@angular/core": "^2.3.1",
"@angular/forms": "^2.3.1",
"@angular/http": "^2.3.1",
"@angular/platform-browser": "^2.3.1",
"@angular/platform-browser-dynamic": "^2.3.1",
"@angular/router": "^3.3.1",
"@types/hammerjs": "^2.0.35",
"angular2-drag-scroll": "^1.4.4",
"angular2-fontawesome": "^0.9.3",
"bootstrap": "^3.3.7",
"core-js": "^2.4.1",
"font-awesome": "^4.7.0",
"hammerjs": "^2.0.8",
"jsstore": "^1.2.6",
"ng2-materialize": "^1.3.2",
"ngx-bootstrap": "^2.0.0-beta.8",
"rxjs": "^5.0.1",
"ts-helpers": "^1.1.1",
"zone.js": "^0.7.2"
 },
 "devDependencies": {
"@angular/cli": "^1.5.0",
"@angular/compiler-cli": "^2.3.1",
"@types/jasmine": "2.5.38",
"@types/node": "^6.0.42",
"codelyzer": "~2.0.0-beta.1",
"jasmine-core": "2.5.2",
"jasmine-spec-reporter": "2.5.0",
"karma": "1.2.0",
"karma-chrome-launcher": "^2.0.0",
"karma-cli": "^1.0.1",
"karma-jasmine": "^1.0.2",
"karma-remap-istanbul": "^0.2.1",
"protractor": "~4.0.13",
"ts-node": "1.2.1",
"tslint": "^4.3.0",
"typescript": "~2.0.3"
}
}
I got ./node_modules/ngx-bootstrap/dropdown/bs-dropdown.directive.‌​js 247:16-25 "export 'Renderer2' was not found in '@angular/core' warning error and "Can't resolve all parameters for BsDropdownContainerComponent: ([object Object], [object Obje…, " console error.Pls help me to fix this

**Comment by IlyaSurmay** [comment]
which version of angular are you using? it seems that you have v2 but Renderer2 was added in ng4

**Comment by kamalakkanni** [comment]
Thanks,What I have to do to fix the issue?I am new to angular2.can you pls guide me to make a dropdown working in v2.

**Comment by IlyaSurmay** [comment]
It's better to update your app to Angular 4 or 5, then you'll have latest versions of both Angular and ngx-bootstrap. But if you can't update to Angular 4 for some reason you can use ngx-bootstrap 1.9.3 - this is the last version that supports Angular 2

**Comment by kamalakkanni** [comment]
Thanks.I have updated version by using npm update -D && npm update -S commands(referred https://stackoverflow.com/questions/36597780/how-do-i-correctly-upgrade-angular-2-npm-to-the-latest-version) .Now also I am getting same error.my updated package.json is 
{
  "name": "offline-new",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "@types/hammerjs": "^2.0.35",
    "angular2-drag-scroll": "^1.5.1",
    "angular2-fontawesome": "^0.9.3",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jsstore": "^1.2.7",
    "ng2-materialize": "^1.6.0",
    "ngx-bootstrap": "^2.0.0-beta.8",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "typescript": "^2.6.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/cli": "^1.5.2",
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.92",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "^2.0.10"
  }
}

**Comment by IlyaSurmay** [comment]
post here output from `ng --version`

**Comment by kamalakkanni** [comment]
_                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.2
Node: 6.11.5
OS: win32 x64
Angular: 2.4.10
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic

@angular/cli: 1.5.2
@angular/router: 3.4.10
@angular/tsc-wrapped: 0.5.2
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.2
@schematics/angular: 0.1.5
typescript: 2.6.1
webpack: 3.8.1

**Comment by IlyaSurmay** [comment]
`Angular: 2.4.10` - you have ng2
To update to ng v5, run this
```
npm i @angular/animations@5 \
    @angular/common@5 \
    @angular/compiler@5 \
    @angular/compiler-cli@5 \
    @angular/core@5 \
    @angular/forms@5 \
    @angular/http@5 \
    @angular/language-service@5 \
    @angular/platform-browser@5 \
    @angular/platform-server@5 \
    @angular/platform-browser-dynamic@5 \
    @angular/router@5 \
    @angular/service-worker@5 \
    rxjs@^5.5
```

**Comment by madhuGrMadorwat** [comment]
Hi Similarly I am facing same Issue like I am getting 

ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'ngx-bootstrap/dropdown/bs-dropdown.module' in 'C:\Users\MadOrWat\Desktop\gsipKOtakUI\pro\sameProdGsip\src\app'

![image](https://user-images.githubusercontent.com/43564748/50391526-4bbc3a00-076c-11e9-8c5c-a79f51c19a3a.png)

**Comment by PrasenjitM9** [comment]
Please  **reinstall node_modules** and check it one more time. 
When I looked at your repo it was broken too but after a while, I reinstalled all dependencies and it started working. 
https://github.com/valor-software/ngx-bootstrap/issues/3362#issuecomment-354101043
