### ISSUE TITLE
DatePicker UI visibility issue

### ISSUE THREAD

**Issue by nitinshk1111** [valor-software/ngx-bootstrap#3077]
Hi ,

I am using ngx-bootstrap and doing in the same way the documentation has been provided.
But on  My screen It is showing some thing like below.. 

![capture](https://user-images.githubusercontent.com/19682237/33016636-4a15cffe-ce15-11e7-93ba-c469976bae0c.JPG)
Please help to fix this.

**Comment by IlyaSurmay** [comment]
please, import  datepickers css from `ngx-bootstrap/datepicker/bs-datepicker.css` to your project
