### ISSUE TITLE
ngx-timepicker not binding value in manual Entry

### ISSUE THREAD

**Issue by dharveshmydeen** [valor-software/ngx-bootstrap#3079]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Bug description or feature request:
1)Timepicker not bind value  in manual entry.It is working only in arrow or mouse scroll time entry

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:1.9.3

Angular:4.4.6

"bootstrap-timepicker": "0.5.2",
Bootstrap:

### Build system: Angular CLI, System.js, webpack, starter seed:

I am using Angular CLI@1.0.3

**Comment by timaxapa** [comment]
You can upgrade version to 2.0.0-beta.8 without any code rewriting now (according to timepicker). It hasn't this issue.

**Comment by valorkin** [comment]
@timaxapa thanks!
yes it was fixed

**Comment by monis01** [comment]
Hi,
I am facing similar issue in custom validation case user is able to add wrong time with manual entry and validation function is not working.
e.g. 99:99 
using  2.0.0-beta.8
Thanks
