### ISSUE TITLE
EventEmitter not working in angular2 beta.11

### ISSUE THREAD

**Issue by joehmchan** [valor-software/ngx-bootstrap#308]
I got the following errors in angular2 beta.11. I guess EventEmitter declarations should be strongly typed.

ERROR in node_modules\ng2-bootstrap\components\pagination\pagination.component.ts
(90,3): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<number>'.
  Type '{}' is not assignable to type 'number'.
ERROR in node_modules\ng2-bootstrap\components\pagination\pagination.component.ts
(91,3): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<IPageChangedEvent>'.
  Type '{}' is not assignable to type 'IPageChangedEvent'.
    Property 'itemsPerPage' is missing in type '{}'.
ERROR in node_modules\ng2-bootstrap\components\typeahead\typeahead.directive.ts
(24,3): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<boolean>'.
  Type '{}' is not assignable to type 'boolean'.
ERROR in node_modules\ng2-bootstrap\components\typeahead\typeahead.directive.ts
(25,3): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<boolean>'.
  Type '{}' is not assignable to type 'boolean'.
ERROR in node_modules\ng2-bootstrap\components\typeahead\typeahead.directive.ts
(26,3): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<{ item: any; }>'.
  Type '{}' is not assignable to type '{ item: any; }'.
    Property 'item' is missing in type '{}'.
ERROR in node_modules\ng2-bootstrap\components\dropdown\dropdown.directive.ts
(22,3): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<boolean>'.
  Type '{}' is not assignable to type 'boolean'.
ERROR in node_modules\ng2-bootstrap\components\dropdown\dropdown.directive.ts
(23,3): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<boolean>'.
  Type '{}' is not assignable to type 'boolean'.

**Comment by valorkin** [comment]
this is not the only issues with beta.11
see here, just add this to list
