### ISSUE TITLE
docs(typeahead): add example of using typeahead with optionListTemplate and typeaheadItemTemplate to demo

### ISSUE THREAD

**Issue by Hrishi1990** [valor-software/ngx-bootstrap#3081]
### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 1.8.1
### Build system: Angular CLI, System.js, webpack, starter seed:

Would you please provide some code snippet how to use optionListTemplate and typeaheadItemTemplate collectively to do customization for adding headers for items.

**Comment by IraErshova** [comment]
There is a demo for `typeaheadItemTemplate`
https://valor-software.com/ngx-bootstrap/#/typeahead#item-template

**Comment by apotapcukv** [comment]
Dear Hrishi1990! 
As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.
