### ISSUE TITLE
Locale - uniform way for future ....

### ISSUE THREAD

**Issue by leomayer** [valor-software/ngx-bootstrap#3083]
I see that I can use the locale as defined on the sample page. Since I'm now using Angular5 I experience problems with DatePipes. After following the [description](https://angular.io/guide/i18n#i18n-pipes) everything works fine. 

Is there a chance to use for the `BsDatepickerConfig#locale` just the same way as one would use the LOCALE_ID? Or just by `BsDatepickerConfig#locale=localeDe`?

I know the current implementation is working. Its more a suggestion regarding using the existing framework instead of reinventing the wheel.

**Comment by valorkin** [comment]
@leomayer thanks for, I know about LOCALE_ID
but 2 cons:
- I had to support angular v4 for now >.< 
- I will cut `locale` property to date adapter, cuz it's hard to change locales at the moment :(

**Comment by valorkin** [comment]
thanks for an idea anyway! It will be in the roadmap for v3 (which will support angular 5 and 6)
