### ISSUE TITLE
chore(lint): add tslint(ng2lint) Invalid type on EventEmitter.

### ISSUE THREAD

**Issue by ekarlso** [valor-software/ngx-bootstrap#309]
ERROR in ./~/ng2-bootstrap/components/alert/alert.component.ts
(25,3): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<Alert>'.
  Type '{}' is not assignable to type 'Alert'.
    Property 'type' is missing in type '{}'.

**Comment by valorkin** [comment]
Angular 2 version?
If 11 close issue :)
It is broken

**Comment by ekarlso** [comment]
No I'm getting this on beta9 too, see https://gitlab.com/creator-makerspace/gatekeeper-ui for more info.

**Comment by valorkin** [comment]
OK, I will pull and check what is happening

**Comment by ekarlso** [comment]
Apparantly it's a tslint error : )

Endre

2016-03-22 20:03 GMT+01:00 Dmitriy Shekhovtsov notifications@github.com:

**Comment by valorkin** [comment]
Common dude! I have digged it al over for an issue! :)
I will add ng2lint here this week

**Comment by ekarlso** [comment]
@valorkin you can try to grab my app if you can and see if you get the same error ? 
https://gitlab.com/creator-makerspace/gatekeeper-ui

**Comment by sundriver** [comment]
+1

**Comment by Slavrix** [comment]
+1

**Comment by sundriver** [comment]
+1

**Comment by valorkin** [comment]
should not be an issue now, because npm package contain ts files in special folder

**Comment by valorkin** [comment]
Failed to lint: 50 errors. (749 other errors not shown.)
trololo ...
