### ISSUE TITLE
BsDatepicker - Unable to return to previous month if minDate is the last day in month

### ISSUE THREAD

**Issue by timaxapa** [valor-software/ngx-bootstrap#3102]
### Bug description or feature request:
If minDate equals the last day in month there is no way to return to the previous month if you went to the next month
1.
![image](https://user-images.githubusercontent.com/9010313/33175222-7423805a-d074-11e7-8d48-af9efd3ca83b.png)
2.
![image](https://user-images.githubusercontent.com/9010313/33175275-a30d93c4-d074-11e7-9e9b-7c6f6d79335c.png)

### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-aaxtmt

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 2.0.-beta.8
Angular: 4 or 5
Bootstrap: 3.3.7

**Comment by valorkin** [comment]
I am sure I have seen similar issue
just FYI it will fixed, next week most prob

**Comment by timaxapa** [comment]
Thanks!
