### ISSUE TITLE
Pipe pattern date not working daterangepicker 

### ISSUE THREAD

**Issue by jcebidanes** [valor-software/ngx-bootstrap#3103]
I use patter date to  bsDatepicker and work fine.
```
<input  type="text" class="form-control" formControlName="birthday" bsDatepicker 
[bsConfig]="bsConfig" [(bsValue)]="birthday" value="{{dataNascimento | date:'dd/MM/yyyy - dd/MM/yyyy' }}" />
```
But in bsDaterangepicker not working
```
<input class="form-control" #drp="bsDaterangepicker" bsDaterangepicker [bsConfig]="bsConfig" 
[maxDate]="bsConfig.maxDate" value="{{periodo | date:'dd/MM/yyyy - dd/MM/yyyy' }}" />
``` 

### Erro message

`ERROR Error: InvalidPipeArgument: 'Wed Nov 22 2017 12:50:19 GMT-0200 (Horário brasileiro de verão),Wed Nov 22 2017 12:50:19 GMT-0200 (Horário brasileiro de verão)' for pipe 'DatePipe'`

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.8

Angular: 5.0.0

Bootstrap: 3.3.7

Build system: Angular CLI 1.5.2

**Comment by valorkin** [comment]
haha, if it was so easy :D
daterange picker returns [date1,date2]
and for sure angular date pipe doesn't support it
so use `bsConfig` property and set `rangeInputFormat`

**Comment by jcebidanes** [comment]
I add rangeInputFormat and work, but not while add initial value in dataRangerpicker. 
Only work while I select date manualy.

Same problem this other issue [3087](https://github.com/valor-software/ngx-bootstrap/issues/3087)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.9

Angular: 5.0.0

Bootstrap: 3.3.7

Build system: Angular CLI 1.5.2

**Comment by valorkin** [comment]
There are common issue with initial format, should be fixed next week
