### ISSUE TITLE
`bsDaterangepicker` zIndex Issue while using it within a modal

### ISSUE THREAD

**Issue by sarfarazansari** [valor-software/ngx-bootstrap#3105]
### Bug description or feature request:
Am confused we can consider this issue in both modes (bug or feature request)
Scenario: While using `bsDaterangepicker` within a Modal you’ll face, the z-index issue.
So it would be cool If I can pass `z-index` in `bsDaterangepicker`. 
Otherwise, I’ve to handle it via `CSS`.
let me know What you guys think?

### Reference Image:
![image](https://user-images.githubusercontent.com/3416989/33203159-284e95c8-d125-11e7-8896-07b33505c5bb.png)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.9.3

Angular: 4.3.6

Bootstrap: NA

### Build system: Angular CLI, System.js, web pack, starter seed:
NA

### Solution:
We can be fixed, it via two ways.
1. setting the default value to `bs-datepicker.css`. more than `bsModal` value.
2. We can provide a input value which will set dyanmic zIndex to bsDateRangePicker `:host`.
I can do it but just let me suggest By which way I can do?

**Comment by valorkin** [comment]
Hey, please check witg latest v2+ , i am sure we were fixing it

**Comment by valorkin** [comment]
Yes, its fixed in latest versions https://github.com/valor-software/ngx-bootstrap/blob/development/src/datepicker/bs-datepicker.scss#L509
