### ISSUE TITLE
bsDatepicker.show() submits form

### ISSUE THREAD

**Issue by Punkiebe** [valor-software/ngx-bootstrap#3109]
### Bug description or feature request:
When calling the method 'show' of the bsDatepicker it submits the form where it's in!
On my project the submit goes to an other page, so we even don't see the popup.
On the plunker it open's the datepicker, but you can see in the console log that he call the onSubmit() method, the same way as if you would click on the submit button.

### Plunker/StackBlitz that reproduces the issue:
https://plnkr.co/edit/dgVrBJgoTORLZQHXu5WF

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: ngx-bootstrap@2.0.0-beta.8

Angular: 4.4.6

Bootstrap: 4

### Build system: Angular CLI, System.js, webpack, starter seed:
angular-cli

**Comment by IlyaSurmay** [comment]
Add `type="button"` to `<button>` tag. It's better to specify buttons type if you use it in forms because if type isn't specify, browser treats it as submit button.
Fixed plunkr - https://plnkr.co/edit/DtmApbYqfLpFCOkvy1eg?p=preview
