### ISSUE TITLE
Manual Entry Not Working when i build Host a project in angular 4

### ISSUE THREAD

**Issue by dharveshmydeen** [valor-software/ngx-bootstrap#3111]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Bug description or feature request:
Manual Entry Not Working when I build a Project in angular 4 and Host it in server.
It is working only in my local server

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:2.0.0-beta.8

Angular:4.4.6

Bootstrap:

**Comment by valorkin** [comment]
Please be more specific, manually entry where what, what is expected result, sample to work with.
Closing until more details will be provided
Our CD for universal https://ngx-universal.herokuapp.com
