### ISSUE TITLE
Pagination component does not assume custom texts

### ISSUE THREAD

**Issue by gandarez** [valor-software/ngx-bootstrap#3114]
Pagination component ignores all custom texts I set and always assume the default English language.

```html
<div class="row">
    <div class="col-xs-12">
      <pagination 
        [totalItems]="totalItems"
        [itemsPerPage]="itemsPerPage"
        [maxSize]="maxSize"
        [boundaryLinks]="true"        
        [firstText]="Primeira"
        [lastText]="Ultima"
        [nextText]="Proxima"
        [previousText]="Anterior"
        [(ngModel)]="currentPage"
        (pageChanged)="pageChanged($event)">
      </pagination>
    </div>
  </div>
```
![image](https://user-images.githubusercontent.com/782854/33268753-77d029da-d365-11e7-81ed-faf48919145b.png)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.8
Angular: 4.4.6
Bootstrap: 4.0.0-beta.2

**Comment by IlyaSurmay** [comment]
This kind of binding `[lastText]="Ultima"` won't work because  Angular thinks that `lastText` is `this.Ultima` in your component. 
Correct way is `lastText="Ultima"` or `[lastText]="'Ultima'"`

**Comment by gandarez** [comment]
You rock @IlyaSurmay! many thanks!

**Comment by andreagosto** [comment]
Is possible to change the text in the numbered buttons? I would like to set some dates
