### ISSUE TITLE
DataPicker throw these errors TypeError: Cannot call a class constructor without |new| and ERROR CONTEXT DebugContext_

### ISSUE THREAD

**Issue by DarioLondon** [valor-software/ngx-bootstrap#3118]
I am trying to add datepicker in my form ,  and I followed the example on ngx-bootstrap page , but I keep having a weird error. Other components works fine (I.e Dropdown ) .
I have contacted the slack community and @valorkin suggested to open an issue.

Here the link of the repo I am using and where the error occurs 
https://github.com/DarioLondon/inamob_WebApp.git

The error that I see are these : 
<img width="1658" alt="screen shot 2017-11-27 at 15 16 04" src="https://user-images.githubusercontent.com/10201109/33284044-9b35243a-d3a5-11e7-90e4-954ba0058b0e.png">
<img width="953" alt="screen shot 2017-11-27 at 15 15 52" src="https://user-images.githubusercontent.com/10201109/33284045-9b4fb3f4-d3a5-11e7-9d81-7607b405cf86.png">

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.9

Angular: 5.0.3

Bootstrap:4.0.0-beta.2

### Build system: Angular CLI, System.js, webpack, starter seed: Angular CLI

**Comment by valorkin** [comment]
closing in favour of https://github.com/valor-software/ngx-bootstrap/issues/3134

there a workaround 
change tsconfig target to es5
