### ISSUE TITLE
please remove: Peer ng2-bootstrap@1.0.7 wants angular2@2.0.0-beta.9

### ISSUE THREAD

**Issue by born2net** [valor-software/ngx-bootstrap#312]
please remove: Peer ng2-bootstrap@1.0.7 wants angular2@2.0.0-beta.9
and set to .11

**Comment by valorkin** [comment]
1. Beta.11 doesn't work properly
2. Peer dependencies are good, they are giving a hint about ng2 version to use, but you can ignore it :)

Why should we remove it?

**Comment by born2net** [comment]
ok tx
