### ISSUE TITLE
Ratings Component throws template error for Angular CLI 1.4.9 & 1.5.0 but works on StackBlitz

### ISSUE THREAD

**Issue by web-snake** [valor-software/ngx-bootstrap#3121]
### Bug description or feature request:
I followed the simple examples in the documentation for the Ratings modules and set up my App using the isntallation instructions here: https://github.com/valor-software/ngx-bootstrap/blob/development/docs/getting-started/bootstrap4.md. My code works the StackBlitz evironment with same version of ngx-bootstrap, but not in my app with fresh installs under either Angular CLI 1.4.9 or 1.50 but otherwise the same dependency versions as the working StackBlitz app. Other ngx-bootstrap components work fine. I created a GitHub repo reproducing the error:
https://github.com/web-snake/ngx-bootstrap-ratings-test
I get a template parse error:
compiler.es5.js:1694 Uncaught Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'rating'. (")" translate="previous">Prev</button>
          <div class="ratings">
          <rating [max]="max" [ERROR ->][(ngModel)]="rate" ></rating>
          <b>(<i>Rate:</i> {{rate}})</b>
        </div>
"): ng:///AppModule/PhotoModalComponent.html@34:30
    at syntaxError (compiler.es5.js:1694)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (compiler.es5.js:12791)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (compiler.es5.js:26994)
    at compiler.es5.js:26913
    at Set.forEach (<anonymous>)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (compiler.es5.js:26913)
    at compiler.es5.js:26800
    at Object.then (compiler.es5.js:1683)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (compiler.es5.js:26799)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (compiler.es5.js:26728)

### Plunker/StackBlitz that reproduces the issue:
My StackBlitz example works:
https://stackblitz.com/edit/ngx-bootstrap-ratings-xyf9ab
I created an environment using Angular CLI 1.4.9 using the same source code that reproduces the issue:
https://github.com/web-snake/ngx-bootstrap-ratings-test

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: ngx-bootstrap@1.9.3 
( I also tried ngx-bootstrap@2.0.0-beta.8, which had the same issue ) 

Angular: @angular/core@4.4.6 

Bootstrap: bootstrap@4.0.0-beta.2 

### Build system: Angular CLI, System.js, webpack, starter seed:
@angular/cli": "1.4.9"  ( 1.5.0 also had the same issue )

**Comment by valorkin** [comment]
9 to 1 you forget to import forms module

**Comment by web-snake** [comment]
The reason I didn't import it is because that's not in the documentation: 
https://valor-software.com/ngx-bootstrap/#/rating
Can you add that. Its not obvious. I'm not using it in a form.

**Comment by valorkin** [comment]
You are using ngModel, it is a form

**Comment by web-snake** [comment]
I see, I didn't know you always needed forms for ngModel.
But that doesn't resolve the issue.
It doesn't throw a template error but it doesn't render the ratings either.
https://github.com/web-snake/ngx-bootstrap-ratings-test
It works fine under the StackBlitz environment with the same code
https://stackblitz.com/edit/ngx-bootstrap-ratings-xyf9ab?file=app%2Fapp.component.ts
You closed this issue, should I open a new one?

**Comment by valorkin** [comment]
What is new issue?

**Comment by valorkin** [comment]
Issue closed cuz its obvious and not related yo ngx bootstrap

**Comment by web-snake** [comment]
Its the same code with the Forms Module import.
The Ratings don't render under Angular CLI while they do in StackBlitz
The FormsModule import wasn't related,
this seems to be, unless I'm doing something else stupid

**Comment by web-snake** [comment]
But it is a different issue, its not throwing the template error
