### ISSUE TITLE
The datepicker should display the month of [minDate] by default when opened.

### ISSUE THREAD

**Issue by JimJafar** [valor-software/ngx-bootstrap#3123]
### Bug description or feature request:

When [minDate] is set dynamically (e.g. when bound to another datepicker's ngModel value) to a future date, opening the datepicker shows only greyed out dates and the user must navigate to the correct month before they can pick a date.

There is another problem here - when [minDate] is dynamically set to a date near the end of the year (e.g. December 30th 2017) it is not possible to navigate using the > button (selecting the month by name still works). This part of the bug is not reproducable in my plunkr - has it been fixed in the unpkg.com version?

### Plunker/StackBlitz that reproduces the issue:

[https://plnkr.co/edit/VPVQvEqu3bLwNxpsMbxx?p=preview](https://plnkr.co/edit/VPVQvEqu3bLwNxpsMbxx?p=preview)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.9

Angular: 5.0.1

Bootstrap: bootstrap-sass 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:

webpack

**Comment by valorkin** [comment]
similar to #2711

**Comment by valorkin** [comment]
to sum up:
- if view date is provided (bsValue|ngModel) it should be shown
- if view date is not provider:
  - if minDate>currentDate (default view value), show minDate
  - if maxDate<currentDate(default view value) show maxDate

**Comment by JimJafar** [comment]
Thanks @valorkin !
