### ISSUE TITLE
fix(typeahead): Typeahead with typeaheadMinLength 0 and placeholder requires two clicks for selecting an item in IE

### ISSUE THREAD

**Issue by AndersWinther-Dahl** [valor-software/ngx-bootstrap#3124]
### Bug description or feature request:
When using a typeahead with default values (typeaheadMinLength=0) IE will not let you choose an item without clicking twice

### Plunker/StackBlitz that reproduces the issue:
Can be recreated in IE11 with the "Reactive forms"-example on
https://valor-software.com/ngx-bootstrap/#/typeahead
Click inside the input field and click on one of the items that shows (don't type anything). The first click gets ignored, the second click chooses the item.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: v2.0.0-beta.8 

Angular: Same as demo-page

Bootstrap: 4

Best regards,
Anders Winther-Dahl

**Comment by royporter7** [comment]
For me, the first click on a typeahead with typeaheadMinLength=0 on IE11 simply does not make the HTTP call whatsoever.

But yes, I too can confirm that there is issues with typeahead behavior and IE11.

**Comment by snimelius** [comment]
I'm using a temporary fix to get around this:
Add a blank space in the model then trim the model..

`
if (document.documentMode) {
            this.model+= " ";
            this.model.trim();
        }
`

**Comment by Oliver-Piorun** [comment]
This bug is crucial for our project. Is there an ETA for this? Or the typeahead fixes in general. Or even better: A temporary workaround? I don't know how to apply the workaround by @snimelius . We are using reactive forms btw.

Greetings!

**Comment by panyann** [comment]
Still doesn't work, please look into this. It's also important for our project.

**Comment by arunadhumal18** [comment]
For me, the first click on a typeahead with typeahead MinLength=0 on IE11 is working but when i am changing the value second time, typeahead list is not getting hided on one click need to click twice and after that list is not getting opened on focus when typeahead field is empty.

**Comment by scotteby** [comment]
Noticed same issue, where it needs two clicks to select in IE11 when minlength=0.

Has anyone found a workaround?

**Comment by panyann** [comment]
@scotteby The workaround is to place a space character in the input if the browser is IE. It's hideous and a little bothersome to implement, but it works.

**Comment by scotteby** [comment]
Thanks @panyann, I saw that comment earlier but didn't realize what it was saying. You are right, it's a little rough, but it does work.

**Comment by cmakohon** [comment]
Having this exact same issue. Would love it to be fixed soon. Weird that taking the placeholder out resolves the issue.

**Comment by sarimj** [comment]
How can ngx-bootstrap team underestimate this issue. It is really a big and clear issue?

**Comment by apotapcukv** [comment]
Hi, @AndersWinther-Dahl! We can’t reproduce the issue now to check if it has been fixed or not. If you still can, please do it at https://stackblitz.com/edit/angular-ivy-de1elj?file=tsconfig.json/ and share with us, or please add a recorded video.

**Comment by AndersWinther-Dahl** [comment]
@apotapcukv we've stopped supporting IE in the mean time. Maybe someone else can confirm that the issue is fixed.

**Comment by apotapcukv** [comment]
Dear AndersWinther-Dahl! 
As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.
