### ISSUE TITLE
Typeahead: LatinMap not well defined

### ISSUE THREAD

**Issue by mihaivarga** [valor-software/ngx-bootstrap#3126]
https://github.com/valor-software/ngx-bootstrap/tree/development/src/typeahead

LatinMap used to be 'string'=>'string' now it is string=>'string'

Triggers errors on older browsers. 

Please advise.

**Comment by valorkin** [comment]
great reason to do a small PR
don't forget to add tslint disable rule on top of file

**Comment by valorkin** [comment]
@mihaivarga ?

**Comment by mihaivarga** [comment]
Yes

**Comment by mihaivarga** [comment]
@valorkin I am trying to make a push but I get error when doing so:

Push failed: Failed with error: unable to access 'https://github.com/valor-software/ngx-bootstrap.git/': The requested URL returned error: 403

**Comment by valorkin** [comment]
@mihaivarga make fork, push to your fork, create PR

**Comment by mihaivarga** [comment]
Done.
