### ISSUE TITLE
getting error: EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on Tooltip

### ISSUE THREAD

**Issue by born2net** [valor-software/ngx-bootstrap#313]
has anyone seen this:

getting error: EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on Tooltip

both on .10 and .11 of ng2

![capture](https://cloud.githubusercontent.com/assets/5090936/13970564/caa5b098-f046-11e5-8aaf-3751e089c389.PNG)

regards

Sean

**Comment by valorkin** [comment]
Mangle: true? :)

**Comment by born2net** [comment]
no, its off with no uglifying....

**Comment by mburger81** [comment]
@valorkin 

same issue as #311 

problem is on beta.10 and 11
ng2-bootsrap 1.0.7 seems not to be compatible to beta 10 and 11, I saw in our commits you upgraded it to beta11 can you release it on npm?

**Comment by born2net** [comment]
ok will wait for .12... tx

**Comment by valorkin** [comment]
@mburger81 yes I can, but there some issues
read here https://github.com/valor-software/ng2-bootstrap/pull/305
and fixing them is problematic because of mentioned ng2 issue

**Comment by mburger81** [comment]
@born2net 
sorry probably I wrote false, the problem in this case is not beta.10 and beta.11 but the compatibility from ng2-bootstrap to this libraries.

@valorkin
perhapse you can release a ng2-bootstrap 1.0.8 beta and I will check if the two things I need will work there. For I have to use beta.11 to get it work on last angular2-webpack-starter and so I had to remove ng2-bootstrap and disable your dropdown directives.
thx

**Comment by valorkin** [comment]
@mburger81 you can install from github via npm actually
just do `npm i -S valor-software/ng2-bootstrap`

**Comment by born2net** [comment]
it's ok I will wait for next release... not a showstopper for me...

**Comment by mburger81** [comment]
@valorkin okay that worked! Now i'm able to use last angular2-webpack-starter with last ng2-bootstrap, I had and still have severe problems on last versions of zone webpack using my app ...

I opened you a bug for the dropdown directive under beta.11 #316

thx again

**Comment by valorkin** [comment]
np

**Comment by born2net** [comment]
I am all of a sudden getting 
No Directive annotation found on Dropdown
I guess my library has updated to latest version, any known issue with this?

**Comment by born2net** [comment]
ok found the issue

```
"npm:ng2-bootstrap@1.0.7": {
      "angular2": "npm:angular2@2.0.0-beta.9",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "moment": "npm:moment@2.12.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "zlib": "github:jspm/nodelibs-zlib@0.1.0"
    },
```

jspm was pointing to beta 0.9 on ng2
