### ISSUE TITLE
Passing data to modal doesn't seem to work

### ISSUE THREAD

**Issue by dottodot** [valor-software/ngx-bootstrap#3131]
I have the following to open my modal

```
 openEditLineItem(line_item: LineItem) {
    this.bsModalRef = this.modalService.show(LineItemEditComponent, {
      class: 'modal-lg'
    });
    this.bsModalRef.content.order = this.order;
    this.bsModalRef.content.line_item = line_item;
  }
```
and my LineItemEditComponent has 

```
  public order: Order;
  public line_item: LineItem;
```
however when trying to use the content in my components it's always undefined.

Is there something I'm missing as the documentation suggests this is all that it required.

**Comment by IlyaSurmay** [comment]
In the current implementation, the data you passed to modal component won't be available in `ngOnInit()` or `constructor`. The fix isn't merged yet (#2600) but it will be, then passed data will be available in `ngOnInit()`. Now you can call some method in your modal content component after passing data to perform some operations.
So now it should be something like this:
```
this.bsModalRef.content.order = this.order;
this.bsModalRef.content.line_item = line_item;
this.bsModalRef.content.doSomeOperationsWithData();
```

Also, you can do it in a little hacky way by wrapping `ngOnInit()` content in `setTimeout` but I wouldn't rely on this very much.

**Comment by dottodot** [comment]
OK thanks, are there any workarounds for getting update data back out and to the parent without using a service?

**Comment by IlyaSurmay** [comment]
`EventEmitter` could be enough for this. Create EventEmitter in modal content component, subscribe on it in parent and pass your data

**Comment by falvarezco** [comment]
Could you give an example of that EventEmitter approach ?? thanks

**Comment by stiofand** [comment]
Can you also give an example of this ngOnInit example, as with current documentation one can pass in the data via initialState, yet I have not seen one working example of this (even the documentation example doesn't work). 

Using the example above, in NgOnInit supposes the values for the reference need to be gotten somewhere.

```
this.bsModalRef.content.order = this.order;
this.bsModalRef.content.line_item = line_item;
this.bsModalRef.content.doSomeOperationsWithData();
```

So where so this.order etc come from assuming this is in the modal ngInit and not the class using the service?

in My example I have a class which uses the modalService, passing in my Modal Component with an initial State.

```
 onClick(org: Types.OrganizationTreeDto): void {
        this.modalService.show(OrganizationTreeEditComponent, {
            initialState: {
                selectedOrganization: {...org}
            }
        });
```
The OrganizationTreeEditComponent contains the template for the modal. Debugging showa initialState is formed with the right values before its passed into the modalService. However, when the modal opens, initialState (inc selectedOrganization) is undefined.

Following the advice above on onInit, my  OrganizationTreeEditComponent looks like this. (Assuming all modules, imports and annotations are correct

```
....
export class OrganizationTreeEditComponent implements OnInit{

    selectedOrganization: Types.OrganizationTreeDto;

    constructor(public bsModalRef: BsModalRef){}

    ngOnInit(){
        this.bsModalRef.content.selectedOrganization = this.selectedOrganization;
    }
}

```
However, this does absolutely nothing, it doesn't matter if I pass in a simple String or the object you see.

So either the documentation is wrong, or there is a bug. Any examples would be well appreciated

**Comment by sgentile** [comment]
Just seeing this - I'm having same issue.   The problem is the component needs to be able to pass data as well as modal settings.   It need to be able to support something like:

```
this.bsModalRef = this.modalService.show(LineItemEditComponent, {
      class: 'modal-lg',
      data: inputData
    });
```

or a third property

```
const initialSettings = {
  data:inputData
}
this.bsModalRef = this.modalService.show(LineItemEditComponent, {initialSettings}, {
      class: 'modal-lg'
    });
```

**Comment by ricardosobrado** [comment]
You can do something like:

const initialState = {
        title: 'Hello window',
      };

const modalConfig = {
        backdrop: true,
        ignoreBackdropClick: true,
      };

const modalParams = Object.assign({}, modalConfig, { initialState, class: 'modal-lg' });

this.modalService.show(template, modalParams);
