### ISSUE TITLE
fix(datepicke)r: bs-datepicker dies after abusive use of enter or space keys 

### ISSUE THREAD

**Issue by SidekickJohn** [valor-software/ngx-bootstrap#3133]
### Bug description:
A fellow colleague just killed the datepicker by an abusive use of the "enter" and "spacebar" keys on his keyboard. 

### How?
Get focus on the button that opens/toggles the datepicker.
Repeatedly hit "enter" and "spacebar" **fast**.
After quite some time the datepicker stops showing up and is dead from there on. 

### Where to see?
Can be reproduced in the recent documentation aswell.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: **2.0.0-beta.8**

**Comment by valorkin** [comment]
hahaha this one is nice!
this will not be fixed soon cuz as soon we release v2 we will add focus trap on datepicker
and this issue will be fixed

but in free time I will research how does this happen
