### ISSUE TITLE
fix(timepicker): 11:59PM to 12:00AM pushes the "date" a day forward and vice-versa

### ISSUE THREAD

**Issue by todthomson** [valor-software/ngx-bootstrap#3139]
Updating the `<timepicker>` "minutes" from 11:59PM to 12:00AM (i.e. forwards across the day boundary) moves the "date" (day) component of the `Date` instance forward by one day e.g. from Dec 1 2017 to Dec 2 2017.

The same thing happens in reverse - i.e. updating the `<timepicker>` "minutes" from 12:00AM to 11:59PM (i.e. backwards across the day boundary) moves the "date" (day) component of the `Date` instance backwards by one day e.g. from Dec 1 2017 to Nov 30 2017.

The same thing does not happen when updating the "hours" of the `<timepicker>` which leads me to believe that this is a bug. In any case I would presume (perhaps incorrectly) that the job of a "time picker" is to update only the "time component" of the `Date` object, not the date as well.

#### 11:59PM to 12:00AM

1. Go to https://valor-software.com/ngx-bootstrap/#/timepicker
1. Use the keyboard/mouse to set the time to 11:59PM.
1. Confirm that the `Date` output is today.
1. Use the mouse to click on the "up arrow" against the "minutes".
1. Note that the `Date` is now tomorrow.

#### 12:00AM to 11:59PM

1. Go to https://valor-software.com/ngx-bootstrap/#/timepicker
1. Use the keyboard/mouse to set the time to 12:00AM.
1. Note you may encounter this bug https://github.com/valor-software/ngx-bootstrap/issues/3132
1. Confirm that the `Date` output is today.
1. Use the mouse to click on the "down arrow" against the "minutes".
1. Note that the `Date` is now yesterday.

### Thoughts

I'm presuming that there's a "special case" in the "hours" that when the "hours" is 23 or 0 it will subtract/add rather than "overflow" into the next/previous day. Probably what we need here is special case for the minutes as well...

### Work Arounds

I'm working around this at the moment by binding the `[(ngModel)]` to a `get/set` which tracks the "old value" and then combining that with `(ngModelChange)` to re-apply the original date with the new time using `moment` and assigning a new `Date` instance with the combined old date + new time, e.g.

```JavaScript
onNgModelChanged(): void {
    if (moment(this._oldDateTime).startOf('day').isSame(this._dateTime) === false) {
        this._dateTime = this.combine(this._oldDateTime, this._dateTime);
    }
}

private combine(date: Date, time: Date): Date {
    return new Date(date.getFullYear(),
        date.getMonth(),
        date.getDate(),
        time.getHours(),
        time.getMinutes(),
        time.getSeconds(),
        time.getMilliseconds());
}
```

### Environment versions

ngx-bootstrap: `2.0.0-beta.9`
Angular: `4.4.6`
Bootstrap: `3.3.7`
Angular CLI: `1.4.9`

**Comment by alpavlove** [comment]
```
ngOnInit() {
        this.control = new FormControl();

        this.control.valueChanges
            .takeUntil(this.itIsDestroyed)
            .do((value) => {
                const momentValue = moment(value);
                let result = this.formatDateForBackend(value);

                if (this.ifHasPreviousValueAndDifferent(momentValue) && this.isNextDaySelected(momentValue)) {
                    const newDate = momentValue.add(1, 'days');

                    result = this.formatDateForBackend(newDate);

                    this.control.patchValue(result, { emitEvent: false });
                } else if (this.ifHasPreviousValueAndDifferent(momentValue) && this.isPreviousDaySelected(momentValue)) {
                    const newDate = momentValue.subtract(1, 'days');

                    result = this.formatDateForBackend(newDate);

                    this.control.patchValue(result, { emitEvent: false });
                }

                this.propagateChange(result);

                this.previousValue = result;
            })
            .subscribe();
    }

    private isNextDaySelected(momentValue): boolean {
        const difference = momentValue.clone().diff(moment(this.previousValue));

        return difference < 0 && Math.abs(difference) > this.twentyOneHours;
    }

    private isPreviousDaySelected(momentValue): boolean {
        const difference = momentValue.clone().diff(moment(this.previousValue));

        return difference > 0 && Math.abs(difference) > this.twentyOneHours;
    }

    private ifHasPreviousValueAndDifferent(momentValue) {
        return !isEmpty(this.previousValue) && !moment(this.previousValue).isSame(momentValue);
    }
```

**Comment by yadimon** [comment]
by line 102 (https://github.com/valor-software/ngx-bootstrap/blob/development/src/timepicker/timepicker.utils.ts#L102)
there is limitation for hours. To not to switch the Date.
The minutes and seconds schould switch the hours, but not the date.
Cannot give a PR with solution now :/
But maybe this info helps to fix it.

**Comment by ghybs** [comment]
Hi,

While the Timepicker is mainly used to input a time only, and we could expect the developer to discard the "date" part of the JavaScript `Date` object that is used as model, it is true that the behaviour is not consistent between the hours (which currently implement a fix, as pointed out by https://github.com/valor-software/ngx-bootstrap/issues/3139#issuecomment-454502516) and minutes / seconds.

Furthermore, there **is** a case where the date part is important: if the developer hooks the _same_ model `Date` to a Datepicker _as well_, i.e. if they are expecting the full `Date` object to be input by the user (including date and time parts):
https://stackblitz.com/edit/ngx-bootstrap-hwlysd?file=app%2Fapp.component.html

In the above example, changing the hours across midnight does not change the date in the Datepicker.

On the contrary, using the minutes or seconds to cross midnight **does** change the date in the Datepicker.

**Comment by amu2211** [comment]
Is it possible to make it as option, please :) It is good option if you want to create date time picker
