### ISSUE TITLE
fix(tooltip): if host element was removed via click, tooltip will persist

### ISSUE THREAD

**Issue by sentjurv** [valor-software/ngx-bootstrap#3142]
There are two modules ( BsDropdownModule and﻿ PopoverModule) which I use together. I want to show tool-tip for each options at the drop-down.

![image](https://user-images.githubusercontent.com/34152247/33470041-5ada6db2-d677-11e7-8fbb-6c8928a37a51.png)

But after pressing on the any option (for example "First") an additional tool-tip at the left top corer ﻿shows.

![image](https://user-images.githubusercontent.com/34152247/33470067-8666235e-d677-11e7-8c51-aa61889c69b0.png)

Also I found that if I pass placement="left" the issue wasn't reproduced.

![image](https://user-images.githubusercontent.com/34152247/33470158-de581112-d677-11e7-9680-9cd3da0b547e.png)

**Comment by sentjurv** [comment]
`<div>
    <label id="lblReportType" class="h2">Select value</label>
    <div class="btn-group" dropdown>
        <button dropdownToggle type="button" class="btn btn-default dropdown-toggle">
            <span class="name">Choose</span>
            <span class="caret"></span>
        </button>
        <ul *dropdownMenu class="dropdown-menu" role="menu">
            <li>
                <a [popover]="'Tooltip'" triggers="hover" placement="right" container="body" class="dropdown-item">First</a>
                <a [popover]="'Tooltip'" triggers="hover" placement="right" container="body" class="dropdown-item">Seconde</a>
            </li> 
        </ul>
      </div>
    <div class="dashed-rule"></div>
</div>`

**Comment by valorkin** [comment]
it's not additional, seems host element got destroyed
but tooltip didn't
it could be a tricky issue

**Comment by ghost** [comment]
@sentjurv I couldn't reproduce this issue (I used 3.1.1 version of ngx-bootstrap) Please, use the newest version or provide a reproduction of this issue.
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts
