### ISSUE TITLE
bug(dropdown): on cancel a dropdown under angular2 beta.11

### ISSUE THREAD

**Issue by mburger81** [valor-software/ngx-bootstrap#316]
Just to notify this bug,
on click outside a open drop-down for cancelling got this error

![image](https://cloud.githubusercontent.com/assets/3778892/13993233/c44fbe80-f11f-11e5-86e6-e78c95b19781.png)

**Comment by valorkin** [comment]
yeap, https://github.com/valor-software/ng2-bootstrap/pull/305

**Comment by mburger81** [comment]
@valorkin @born2net beta.12 is out

**Comment by valorkin** [comment]
updating to beta.12 fixed it

**Comment by mburger81** [comment]
confirmed, bug closed on beta.12 using ng2-bootstrap master,
i don't know if it works on ng2-boostrap@1.0.7

thx

**Comment by valorkin** [comment]
before releasing next version bunch of fixes is required
https://github.com/valor-software/ng2-bootstrap/milestones/beta.12
