### ISSUE TITLE
typeahead: How to detect if option-list is shown?

### ISSUE THREAD

**Issue by flensrocker** [valor-software/ngx-bootstrap#3175]
I found the property `isTypeaheadOptionsListActive` inside the typeahead-directive, but sadly, it is not changed. Are there plans to support this?

My usecase: On `keypress.enter` I want to set the focus to the next input of the form, if the list is not shown.

**Comment by IlyaSurmay** [comment]
There's a `_container` property in typeahead directive that is undefined if option list is hidden.

**Comment by flensrocker** [comment]
It's only undefined before the first open. If it is hidden after it was shown, the `_container` is defined.

**Comment by flensrocker** [comment]
Ok, it's set to `null` on hide, not `undefined`.

**Comment by hridayeshgupta** [comment]
how to access _container property from my code?

**Comment by ghiscoding** [comment]
It's too bad that the Typeahead doesn't have any flag to know when it's open or hidden. I managed to do it with few extra code but really wish a flag would exist for that. 

Here's what I've done in the View (notice the 3 events used)
```html
<input #typeaheadInput autocomplete="off"
        class="form-control typeahead-input"
        formControlName="item"
        (typeaheadOnBlur)="isOpen = false"
        (typeaheadLoading)="isOpen = true"
        (typeaheadOnSelect)="onTypeaheadSelected($event)" />
```
and in the Component
```ts
class MyClass {
  isOpen = false;
  selectedItem: Item;

  onTypeaheadSelected(tm: TypeaheadMatch): void {
    this.isOpen = false;
    if (tm && tm.item) {
      this.selectedItem = tm.item;
    }
  }
}
```

It works but wow so many pieces of code to get to know 1 flag.
