### ISSUE TITLE
fix(package): updating to beta.12

### ISSUE THREAD

**Issue by valorkin** [valor-software/ngx-bootstrap#318]
Here will be a list of issues needed to be fixed before 
publishing ng2 with beta.12

see here https://github.com/valor-software/ng2-bootstrap/milestones/beta.12

**Comment by born2net** [comment]
please update npm as its still pointing to old 0.9 on npm 
tx

**Comment by valorkin** [comment]
@born2net may be issues need to be fixed first?

**Comment by born2net** [comment]
seems so far so good with 0.12, but will do more testing over the weekend

**Comment by valorkin** [comment]
@born2net check the milestone mentioned in issue description

**Comment by born2net** [comment]
ok

**Comment by valorkin** [comment]
published as v1.0.8

**Comment by born2net** [comment]
sweet!

**Comment by valorkin** [comment]
quick fix for animation in 1.0.9

**Comment by valorkin** [comment]
beta.13 published
