### ISSUE TITLE
fix(datepicker): datepicker overlap header, when you scroll up page

### ISSUE THREAD

**Issue by EvilAlexei** [valor-software/ngx-bootstrap#3181]
### Bug description or feature request:

Datepicker overlap header, when you scroll up page

### Screenshot
http://joxi.net/5md1Kd1SvnzNp2

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: v2.0.0-beta.8

Angular: 4.3.6

Bootstrap: v4.0.0-beta.2

### Build system: Angular CLI, System.js, webpack, starter seed: 

Angular CLI

**Comment by YevheniiaMazur** [comment]
Fixed in pr https://github.com/valor-software/ngx-bootstrap/pull/3016
