### ISSUE TITLE
fix(accordion): custom HTML example for accordion broken on small resolution (bs3)

### ISSUE THREAD

**Issue by EvilAlexei** [valor-software/ngx-bootstrap#3184]
### Bug description or feature request:
Bootstrap 3, small resolution or very long text in header. 
Can be reproduced in demos on screens 360px or less,
examples with added custom html inside headers, like "Some HTML here".

### Screenshot
http://joxi.net/p27ZpWZU0peYGm

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: v2.0.0-beta.8

Angular: 4.3.6

Bootstrap: 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed: 
Angular CLI

**Comment by YevheniiaMazur** [comment]
Fixed in pr https://github.com/valor-software/ngx-bootstrap/pull/3016
