### ISSUE TITLE
fix(carousel): slide labels cropped on small resolutions

### ISSUE THREAD

**Issue by EvilAlexei** [valor-software/ngx-bootstrap#3185]
### Bug description or feature request:
Demos for: optional captions, configuring defaults.
Second slide label text is cutted by slide

### Screenshot
http://joxi.ru/DrlKxvKc4Qa90A

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: v2.0.0-beta.8

Angular: 4.3.6

Bootstrap: v4.0.0-beta.2

### Build system: Angular CLI, System.js, webpack, starter seed: 
Angular CLI

**Comment by YevheniiaMazur** [comment]
Fixed in pr https://github.com/valor-software/ngx-bootstrap/pull/3016
