### ISSUE TITLE
fix(datepicker): small field for date output in demo for theme on small resolutions

### ISSUE THREAD

**Issue by EvilAlexei** [valor-software/ngx-bootstrap#3186]
### Bug description or feature request:
small field for date output in demo for theme on small resolutions

### Screenshot
http://joxi.net/KAg5RZ5hgkp9jm

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: v2.0.0-beta.8

Angular: 4.3.6

Bootstrap: v4.0.0-beta.2

### Build system: Angular CLI, System.js, webpack, starter seed: 
Angular CLI

**Comment by YevheniiaMazur** [comment]
Fixed in pr https://github.com/valor-software/ngx-bootstrap/pull/3016
