### ISSUE TITLE
feat(datepicker): add possibility of keeping current date always highlighted regardless of the selected date

### ISSUE THREAD

**Issue by Kenny333** [valor-software/ngx-bootstrap#3192]
As title, I have trouble to create a date picker, I want to always highlight today's date when I open the calendar, but not show today's date inside the text box, instead, I want to show the placeholder like "Please Select a Date" inside the input box by default. 
Ideally: when it's loaded, it shows placeholder "Please Select a Date" in the box, when I open the calendar, today's date will be highlighted(let's say 12/04/2017), and then I select a date( let's say 12/10/2017), close the calendar, now inside the input box, it will show 12/10/2017, if I open the calendar again, two dates should be highlighted, today's date(12/04/2017) always highlight and the date I just selected(12/10/2017).
If anyone has any idea about this issue, please share, Thank you.

**Comment by IlyaSurmay** [comment]
I think what you asking for is to be able to pass an array of dates and classes that will be appended to them.

**Comment by alexdevmotion** [comment]
This feature would be nice.

**Comment by psined1** [comment]
If I may please, to the OP request I would like to add a shortcut button within a calendar popup to jump to current date. This is a very frequent use case in many business applications. Thanks.

**Comment by ajasmm86** [comment]
Team Any Updates on this issue?

**Comment by weijyewang** [comment]
+1

**Comment by VitaliyKim** [comment]
+1

**Comment by tvbishan** [comment]
Any updates on this? @valorkin @IlyaSurmay

**Comment by oscarnascimento** [comment]
+1

**Comment by amtprajapati** [comment]
any alternative solution for this?

**Comment by amtprajapati** [comment]
+1

**Comment by GustavoAmerico** [comment]
+1

**Comment by fralewsmi** [comment]
+1

**Comment by Jav83** [comment]
+1

**Comment by Provson** [comment]
+1

**Comment by Filini** [comment]
+1

**Comment by Vonahz** [comment]
+1

**Comment by Provson** [comment]
Any update ?

**Comment by ghost** [comment]
+1 current date highlighted

**Comment by grigoreme** [comment]
+1

**Comment by Provson** [comment]
Any update ?

**Comment by valorkin** [comment]
Added in #4062 will be released this week

**Comment by Provson** [comment]
you rock !!

**Comment by thari119** [comment]
is this supported in angular 5?
