### ISSUE TITLE
ReferenceError: webpackJsonp is not defined (when using live-server not webpack-dev-server)

### ISSUE THREAD

**Issue by GaloisGirl** [valor-software/ngx-bootstrap#32]
I started an app as recommended in https://angular.io/docs/ts/latest/quickstart.html (with the 'npm init -y' and package.json and everything). I am therefore not using webpack-dev-server, but live-server.

Then I did "npm install --save ng2-bootstrap".

I added to my index.html: (script src="../node_modules/ng2-bootstrap/build/angular2-bootstrap.js")
I get "ReferenceError: webpackJsonp is not defined".

**Comment by valorkin** [comment]
you are referencing files builded by webpack
so nothing strange

**Comment by GaloisGirl** [comment]
Sorry, I'm new to all these webpack and SystemJS and all the other stuff.
I got it to work thanks to this example: https://github.com/valor-software/ng2-play

**Comment by valorkin** [comment]
awesome!
