### ISSUE TITLE
feat(datepicker): add date range picker

### ISSUE THREAD

**Issue by sschueller** [valor-software/ngx-bootstrap#320]
I would like to see a version of this https://github.com/dangrossman/bootstrap-daterangepicker in this package. Is that something that would be considered?

I would think ideally it would be built out of the datepicker component already present.

**Comment by valorkin** [comment]
Yes yes I want it too :)
In nearest plans update to beta .12 
Write roadmap
Split into weekly releases and push push push :)

**Comment by henninga** [comment]
Have you made any progress on this? 

This feature looks interesting and might use it as well. At the minimum this is what we need, https://bootstrap-datepicker.readthedocs.org/en/latest/markup.html#date-range

**Comment by valorkin** [comment]
In new version I working on it will be included

**Comment by seandsky** [comment]
Mark, my project is blocking here:)

**Comment by valorkin** [comment]
@seandsky join https://www.hamsterpad.com/chat/ng2 to participate in beta testing

**Comment by seandsky** [comment]
Thanks a lot @valorkin , I will join & try beta version after finish other modules in my project:)

**Comment by CameronFraser** [comment]
What is the status of this enhancement? Anything I can do to help?

**Comment by valorkin** [comment]
Implemented, need some last tweaks and docs. And ready to be merged

**Comment by michaeljota** [comment]
Hi! Did you merged this already?

**Comment by ngonam22** [comment]
Hello, any news about this feature?

**Comment by francosioquim** [comment]
In new version I working on it will be included

---

**Comment by valorkin** [comment]
It's implement, will be merged soon

**Comment by ngonam22** [comment]
Should we create a date range picker looks like this? with 2 panel of month
http://www.daterangepicker.com/

**Comment by vcernomschi** [comment]
Just wondering if there are any updates with date range picker

**Comment by ismcagdas** [comment]
Hi, 

Is there any progress on this ?

**Comment by valorkin** [comment]
Yes, but not so fast as I was expecting :(

**Comment by ismcagdas** [comment]
No problem, I can wait :), 
You are doing a great job, thanks for your great effort.

**Comment by skix123** [comment]
Hi, any updates?

**Comment by brada1703** [comment]
Any update?  :)

**Comment by brada1703** [comment]
@skix123 - It looks like it's up: http://valor-software.com/ngx-bootstrap/#/datepicker

**Comment by valorkin** [comment]
added :)
new datepicker (new style and pop up version)
available in v1.9.0+
check this out: http://valor-software.com/ngx-bootstrap/#/datepicker#examples

**Comment by skix123** [comment]
Range datapicker - amazing! 💯
