### ISSUE TITLE
(change) and (input) do not work on datepicker input

### ISSUE THREAD

**Issue by FrancescoBorzi** [valor-software/ngx-bootstrap#3200]
### Bug description or feature request:

I'd like to trigger a callback every time my Datepicker `<input>` is changed.

The following does not work:

```
<input
  (change)="onDateChange()"
  [formControlName]="'startDate'"
  bsDatepicker
  value="{{ form.get('startDate').value | date:'yyyy-MM-dd' }}"
>
```

Also the following does not work:
```
<input
  (input)="onDateChange()"
  [formControlName]="'startDate'"
  bsDatepicker
  value="{{ form.get('startDate').value | date:'yyyy-MM-dd' }}"
>
```

the only way I can do it, currently is registering the following inside my `ngOnInit()`:

```
this.form.get('startDate').valueChanges.subscribe(() => {
  this.onDateChange();
});
```

but I think it would be nice if also `(change)` or `(input)` worked like the normal `<input>`s do.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: `2.0.0-beta.9`

Angular: `5.0.5`

Bootstrap: `3.3.7`

### Build system: Angular CLI:

```
Angular CLI: 1.5.4
Node: 8.9.1
OS: linux x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1
```

**Comment by valorkin** [comment]
Remove binding to value, plus you can use ngModelChange or bsValueChange events

**Comment by IlyaSurmay** [comment]
Closing for no updates.

**Comment by apbedi** [comment]
I am using bsValueChange with formcontrol  in manipulating start date n end date. But in manipulation start date changes with end date. I just wanted the selected date in formcontrol
