### ISSUE TITLE
Ng2-Tooltip Error

### ISSUE THREAD

**Issue by baonguyenyam** [valor-software/ngx-bootstrap#321]
Hi All!

I included ng2-bootstrap Tooltip, but when i hover to link the tooltip show error & can not close 
![untitled](https://cloud.githubusercontent.com/assets/3025550/14023808/c0531c2e-f218-11e5-83a2-2011bebadbd0.png)

pls, help me, thanks!

**Comment by valorkin** [comment]
this issues is listed here https://github.com/valor-software/ng2-bootstrap/issues/318
and will be fixed with next release
as for now you can use angular2 beta.9
with 10 and 11 bootstrap will not work (both of them have some issues)

**Comment by baonguyenyam** [comment]
thanks
