### ISSUE TITLE
The modal is not loading the content

### ISSUE THREAD

**Issue by trinhdh** [valor-software/ngx-bootstrap#3241]
I am able to integrate ngx-bootstrap for my project without any issue. Build without any error.
Except the content is not loaded to the modal. (Please see the attachment image)

i am only see the gray backdrop background
Angular and ngx-bootstrap is newest version. 

    "ngx-bootstrap": "^2.0.0-beta.11",
    "@angular/core": "^5.1.0",

Thanks for any hint.

![screen shot 2017-12-08 at 9 03 18 pm](https://user-images.githubusercontent.com/3796012/33791546-46631520-dc5b-11e7-8541-dca440a86c6f.png)

**Comment by IlyaSurmay** [comment]
Could you provide a plunkr/stackblitz with reproduction?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

For now, it seems like ng-template or modal content component's template is empty.

**Comment by IlyaSurmay** [comment]
Closed for inactivity. Will be reopened if you provide a plunkr/stackblitz with reproduction
