### ISSUE TITLE
Datepicker/locales : Regression beta10 ->  beta11

### ISSUE THREAD

**Issue by will421** [valor-software/ngx-bootstrap#3245]
### Bug description or feature request:
On beta10, date format from locale is used
It's not the case on beta 11.

### Plunker/StackBlitz that reproduces the issue:
This project is set with locale as 'fr' : 
https://stackblitz.com/edit/ngx-bootstrap-datepicker-tpmm9q

You can see the difference when switching dependencies between these 2 versions
ngx-bootstrap@2.0.0-beta.10
ngx-bootstrap@2.0.0-beta.11

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 2.0.0-beta.10/11
Angular: 4.4.6
### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI

**Comment by will421** [comment]
OK for me !

**Comment by valorkin** [comment]
@will421 sorry for it, changelog is generated via changelog cli, have no idea why it skipped it
