### ISSUE TITLE
feat(datepicker): trigger="focus" doesn't update model on selection

### ISSUE THREAD

**Issue by simonaberry** [valor-software/ngx-bootstrap#3251]
https://stackblitz.com/edit/angular-gwezha

if you set the triggers to focus, the model is not being set when a date is selected

**Comment by IlyaSurmay** [comment]
This happens because focus event is triggered before click. So when you click on some date, input loses focus and datepicker hides without reacting on click.

As a workaround you can use something like this https://stackblitz.com/edit/angular-cq49ks?file=app/app.component.html

**Comment by rkulinski** [comment]
This workaround is not so good (if you use tab to unfocus component stays there). What you could do is bind some method to blur event `(blur)=close($event)`. Then in `close` method you could check if `event.relatedTarget` exists and if you're not clicking buttons inside datepicker:
```
  close(event) {
    if (event.relatedTarget) {
      if (event.relatedTarget.parentNode.nodeName !== 'BS-DATEPICKER-NAVIGATION-VIEW') {
        this.datepicker.hide();
      }
    }
  }
```
So, when you click on datapicker `event.relatedTarget` value is null - you let datapicker itself to handle  closing else you close picker "manually"

I know that this is a weird solution but at least it works. I think the good solution would be to have some kind of event in directive which would tell if I clicked calendar or no -> I mean some kind of "inside blur". But I guess there're many ways to approach this problem.
