### ISSUE TITLE
feat(typeahead): Add option not to select first when using typeahead component

### ISSUE THREAD

**Issue by vixriihi** [valor-software/ngx-bootstrap#3261]
### feature request:

I could use a input in typeahead to disable autoselecting the first element from options

Something like @Input() typeaheadAutoSelectFirst = true so that it wouldn't break any existing implementations

**Comment by vixriihi** [comment]
Ah there seems to be a pr already for this #1833.

**Comment by IlyaSurmay** [comment]
Closed as a duplicate of #1281

**Comment by Rajanusa** [comment]
Can any one explain how to implement not to select first by default.
I found someone suggested to override select event.
please suggest how to avoid selecting the first  when user is not selecting that.
