### ISSUE TITLE
Do name events without the prefix on

### ISSUE THREAD

**Issue by BagumEpmak** [valor-software/ngx-bootstrap#3266]
According to Angular style guide p.05-16:
"do name events without the prefix on".
https://angular.io/guide/styleguide#dont-prefix-output-properties

Component event names with angular style violation:
AlertComponent
onClose
onClosed

BsDatepickerDirective
onHidden
onShown

BsDaterangepickerDirective
onHidden
onShown

BsDropdownDirective
onHidden
onShown

ModalDirective
onHidden
onHide
onShow
onShown

PopoverDirective
onHidden
onShown

RatingComponent
onHover
onLeave

SortableComponent
onChange

TooltipDirective
onHidden
onShown

**Comment by valorkin** [comment]
yes, I know
but I don't agree with this rule
sorry

**Comment by BagumEpmak** [comment]
I suppose that I didn't explain my thoughts. Event naming approach in ngx-bootstrap is inconsistent.
There are number of events with "on-" prefix and number of events without it.  Sometimes one component or directive use different event naming styles. For example TooltipDirective:
onHidden
onShown 
tooltipChange
tooltipStateChanged

BTW if you are using components from various libraries with different naming styles it also looks weird.

**Comment by valorkin** [comment]
Some components was developed by me, some don't
If you will take a look at roadmap label https://github.com/valor-software/ngx-bootstrap/labels/roadmap
We are planning to bring demos, events, configs, components and directives selectors to consistency in naming and implementation.
Plus v2 to v3 will be focused on testing and adding things, like animation, which I could not add cuz in v1 I had to support ng 2.

Thanks for pointing it out anyway, and I completely agreed with you :)

If you can add your ideas to roadmap  issues as comments, I will highly appreciate it
