### ISSUE TITLE
Is there is a way to use  timepicker in  reactive form ?

### ISSUE THREAD

**Issue by Dhiva03** [valor-software/ngx-bootstrap#3269]

**Comment by Dhiva03** [comment]
**how to change the  CSS of timepicker .bs-timepicker-field{ width: 50px; }**

**Comment by IlyaSurmay** [comment]
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

**Comment by IlyaSurmay** [comment]
here's an example of what you asking https://plnkr.co/edit/EDCKYCGI992gvRactVW0?p=preview . In fact, changing timepicker's css isn't harder than changing any other component's styles. Write your css in file loaded in global scope or use `ViewEncapsulation.None`/`::ng-deep`

**Comment by Dhiva03** [comment]
Okay buddy Thanks ..@IlyaSurmay ..
