### ISSUE TITLE
fix(dropdown): Anchor based dropdown does not close if triggers is set

### ISSUE THREAD

**Issue by robdunnwinning** [valor-software/ngx-bootstrap#3287]
### Bug description or feature request:
The Dropdown on an anchor does not close when triggers is set in the HTML. Removing the triggers="click" will allow the dropdown to function normally.

The dropdown will open as normal, however clicking either on the dropdown or outside will not do anything. It seems the DOM is changing but simply adding the open class instead of removing it.

### Plunker/StackBlitz that reproduces the issue:

Plunkr: https://plnkr.co/edit/kWGWUM7MA1U7pK8XyzdO?p=preview

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.11

Angular: 5.1.1

Bootstrap: 3

### Build system: Angular CLI, System.js, webpack, starter seed:

webpack

**Comment by tarusin** [comment]
@robdunnwinning 
The example in the Plunker does not work. Please fix it.
Also, you can use another starter template:
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by ghost** [comment]
There has been no response. That's why the issue was closed
