### ISSUE TITLE
fix(progressbar demo): autoscroll top doesn't work after navigating from another demo page bottom

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3290]
### Bug description:
- Go to any page
- Scroll page down
- Go to Progressbar page
- See, that page is displayed not from top

![scrollissue](https://user-images.githubusercontent.com/27342505/33993437-366123be-e0df-11e7-8f62-ea8e3a43e839.gif)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-11.beta and older versions

Angular: all supported versions

Bootstrap: 3rd and 4th

**Comment by EvilAlexei** [comment]
Closed because of braking changes, added to timepicker aggregation issue #3265
