### ISSUE TITLE
fix(popover demo): popovers with triggers: 'focus' config are not shown at firefox browser

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3292]
### Bug description:
- Open Firefox browser
- Go to popover demo page
- Scroll to examples with using popovers with  triggers: 'focus' config (dismiss on next click and configuring defaults examples)
- Click on button to see popover

![popovernotshownissue](https://user-images.githubusercontent.com/27342505/33995081-79825446-e0e5-11e7-881d-881306c37766.gif)

**Comment by EvilAlexei** [comment]
On latest firefox version (57.0.4) not reproducible
