### ISSUE TITLE
fix(timepicker demo): cursor at input field appears, even if edit possibility is disabled on firefox

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3293]
### Bug description:
- Open Firefox browser
- Go to Timepicker demo page
- Scroll down to Disabled example and click on Enable/Disable input button
- Click into input for disabled Timepicker

![timepickerdisabledissue](https://user-images.githubusercontent.com/27342505/34000107-01c8aaa8-e0f5-11e7-8e21-a1d007bd0893.gif)
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: all supported

Angular: all supported

Bootstrap: all supported

**Comment by EvilAlexei** [comment]
Closed because of braking changes, added to timepicker aggregation issue #3265
