### ISSUE TITLE
fix(tooltip demo): tooltip with focus trigger doesn't appear for Safari browser

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3294]
### Bug description or feature request:
- Open ngx-bootstrap demo at Safari browser
- Go to tooltip demo page
- Scroll down to Dismiss on next click example
- Click on button (or use tab for moving  focus on it)
- See, that tooltip doesn't appear
#### Expected result:
Tooltip appears and continue displaying while "Dismissible tooltip" button is focused

![tooltipdoesntappearissue](https://user-images.githubusercontent.com/27342505/34000532-3e5b11a8-e0f6-11e7-8473-75973d1bc1c7.gif)
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: all supported

Angular: all supported

Bootstrap: all supported

**Comment by YevheniiaMazur** [comment]
At latest Firefox issue is not reproducing. I'll edit or close it after checking at latest Safari

**Comment by artolshansky** [comment]
Button haven't focus event in Safari ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus))
And in original bootstrap the same issue

**Comment by Domainv** [comment]
It's safari issue

**Comment by ckrandhir** [comment]
its not working for chrome in ios
