### ISSUE TITLE
Unable to set the label of button dropdown with bootstrap

### ISSUE THREAD

**Issue by innov-richa76** [valor-software/ngx-bootstrap#3296]
Hi, 

I am following the below code to get the button dropdown. The dropdown is coming fine but i am unable to change the label on top of the button based on the selected option. Can you please suggest me where I am going wrong.

<div class="btn-group" dropdown>
  <button dropdownToggle type="button" class="btn btn-primary dropdown-toggle">
    Button dropdown <span class="caret"></span>
  </button>
  <ul *dropdownMenu class="dropdown-menu" role="menu">
    <li role="menuitem"><label><input class="dropdown-item" type="radio" name="optradio">Action</label></li>
    <li role="menuitem"><label><input class="dropdown-item" type="radio" name="optradio">Another action</label></li>
    <li role="menuitem"><label><input class="dropdown-item" type="radio" name="optradio">Something else here</label></li>
    </li>
  </ul>
</div>

### Versions of ngx-bootstrap, Angular, and Bootstrap: 

ngx-bootstrap:

Angular: Angular 4

Bootstrap: Bootstrap 3.0

**Comment by IlyaSurmay** [comment]
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead.
So you want to change text in button based on what you've clicked on in dropdown?

**Comment by innov-richa76** [comment]
Yes I want to change the label of the button based on what you've clicked on in dropdown. Please suggest.

**Comment by innov-richa76** [comment]
Here is the plunker with the requirement code for button dropdown:

https://plnkr.co/edit/MlG2p1O4cpDQqKCEM3Yi?p=preview
