### ISSUE TITLE
fix(demo datepicker): when date- or datepangepicker popup is open, page under it still scrollable at mobile devices

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3300]
### Bug description:
- Open ngx-bootstrap demo at mobile device or mobile simulator
- Go to datepicker demo page
- Open any date- or daterangepicker popup
- Scroll page

#### Expected result:
Two cases were proposed: 
- Close datepicker popup when scroll started
- Lock scroll while datepicker popup is opened

![datepickerscrollissue](https://user-images.githubusercontent.com/27342505/34037854-f088b000-e192-11e7-8236-96f0c2569a94.gif)
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: all supported

Angular: all supported

Bootstrap: all supported

**Comment by mridul16g** [comment]
I am still facing this issue

**Comment by raideltorres** [comment]
same for me here, still facing this issue and not only in mobile or in a modal, if the datepicker is inside any scrollable container this will happen.
