### ISSUE TITLE
fix(datepicker): on mobile platform date- and daterangepicker appears right above output, no possibility to enter or edit it manually

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3301]
### Bug description:
- Open ngx-bootstrap demo at mobile device or mobile simulator
- Click on any field with output data from datepicker

![datepickeroutputissue](https://user-images.githubusercontent.com/27342505/34038622-a5688fe8-e195-11e7-86ce-6acbff0933da.gif)
- At mobile device cursor appears above datepicker popup
![cursorabovepopup](https://user-images.githubusercontent.com/27342505/34107181-e98d71b4-e403-11e7-8389-02717200571a.jpg)
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: all supported

Angular: all supported

Bootstrap: all supported

**Comment by daniloff200** [comment]
Not reproducible anymore
