### ISSUE TITLE
fix(demo): console errors appears at demo on Safari browsers

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3305]
### Bug description:
- Open demo at Safari browser
- Open console
### Expected result
Error messages shouldn't appear

![consoleerrorssafari](https://user-images.githubusercontent.com/27342505/34049939-d8d08c6a-e1c1-11e7-9062-8b093f208e10.png)
### Versions of Angular, and Bootstrap:

Angular: all supported

Bootstrap: all supported

**Comment by artolshansky** [comment]
In the current version there are no errors 
![public version](https://user-images.githubusercontent.com/14160094/35623244-8e0b6d16-0693-11e8-9a5e-4e0dafa5a07b.png)
![development branch](https://user-images.githubusercontent.com/14160094/35623247-90752ce0-0693-11e8-8fad-ddb667d35eae.png)

**Comment by YevheniiaMazur** [comment]
Checked at Macbook Pro (mid 2012), Safari version 11.0.2, issue stops reproducing.
