### ISSUE TITLE
ngx-bootstrap/select with keyboard supporting

### ISSUE THREAD

**Issue by abelardolg** [valor-software/ngx-bootstrap#3308]
### Bug description or feature request:
The ngx-bootrstrap/select should be able to look for an item while I am typing it.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.1

Angular: 5

Bootstrap: 4

**Comment by valorkin** [comment]
in the roadmap ;)

**Comment by danielnieto** [comment]
sorry to comment on a closed issue but I'm not able to find the ngx-bootstrap/select module, is it there already? where can I find documentation about it?
