### ISSUE TITLE
Make a Empty Timepicker

### ISSUE THREAD

**Issue by dharveshmydeen** [valor-software/ngx-bootstrap#3309]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Bug description or feature request:
Hi,
I have used latest ngx-bootstrap.I have used timepicker in my project.How to empty the time picker.I assigned variable type as any.I need to empty the time picker in certain action

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:latest version 

Angular:4.4.0

Bootstrap:

**Comment by IlyaSurmay** [comment]
This was added in 2.0.0-beta.9, just set a model value to null.
Here's a plunkr with an example https://stackblitz.com/edit/ngx-bootstrap-pk2v6k?file=app/app.component.html
