### ISSUE TITLE
fix(demo popover): for bootstrap 4 popovers with triggers: 'focus' flickers in time of second click at Safari

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3314]
### Bug description:
- Open ngx-bootstrap demo at Safari browser
- Open Popover demo page and click on Bootstrap 4 button in top of left side navigation menu
- Choose example with popovers, that used triggers: 'focus' (Dismiss on next click or Configuring defaults examples)

#### Expected result:
Popovers with triggers: 'focus' shouldn't react on second click

![popoverflickerissue](https://user-images.githubusercontent.com/27342505/34113816-9fb79dd8-e419-11e7-8a5c-a6d167f7891b.gif)
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: all supported

Angular: all supported

Bootstrap: 4

**Comment by artolshansky** [comment]
Not actual in current version or in my laptop

Checked at Macbook Pro (mid 2012), Safari version 11.0.2, issue stops reproducing.

**Comment by YevheniiaMazur** [comment]
@olshansky, at Macbook Air (2017) with macOS v10.13.11, Safari v11.0.3 (and, also I rechecked this issue before updating, at Safari 11.0.2) this issue still reproducing. Trigger focus still don't work, as it expected

**Comment by aldus25** [comment]
Trigger on focus is not working as expected. It seems that the focus is not lost when blur outside.

**Comment by aldus25** [comment]
Hey folks, I solved this issue using fastclick.js library. It seems that IOS delays the execution of click events 300ms. Hope it works for you too!
