### ISSUE TITLE
Typeahead is flickering

### ISSUE THREAD

**Issue by Oliver-Piorun** [valor-software/ngx-bootstrap#3315]
### Bug description:
When focusing the typeahead input with ([typeaheadMinLength]="0") the list that will be shown is flickering sometimes.

### Plunker/StackBlitz that reproduces the issue:
The issue also exists in the current typeahead examples:
https://valor-software.com/ngx-bootstrap/#/typeahead#reactive-forms

I recommend using **Google Chrome** to reproduce this issue. The problem does not occur that often in IE11 and Firefox. Focus and leave the typeahead input constantly to see whats up. Info: I think the effect is even bigger if you use a larger list.

Greetings

**Comment by valorkin** [comment]
I suppose main condition is delay in getting data

**Comment by Oliver-Piorun** [comment]
Were you able to reproduce the issue? If yes, do you know how to deal with that?

Greetings

**Comment by IlyaSurmay** [comment]
https://github.com/valor-software/ngx-bootstrap/blob/development/src/typeahead/typeahead.directive.ts#L231 - here's the reason, `show()` method is called twice because of `focus` and `click` triggers. I think this will be fixed in the next release.

**Comment by Oliver-Piorun** [comment]
@valorkin @IlyaSurmay Thank you!
