### ISSUE TITLE
fix(demo): add IE and safari shims

### ISSUE THREAD

**Issue by johan13** [valor-software/ngx-bootstrap#333]
I am having trouble getting the typeahead component to work on IE11. After the first keystroke I get an an unhandled exception that says `SyntaxError: Expected ';'`.

Additionally, [valor-software.com/ng2-bootstrap](http://valor-software.com/ng2-bootstrap/) fails to load on IE11. It halts with multiple errors in the console with the "Loading..." message still showing.

What is that status of IE support? Is it supposed to work?

**Update**: blocked by https://github.com/angular/angular/pull/7864 or https://github.com/angular/angular/pull/6944

**Comment by valorkin** [comment]
yes, it is supposed to work

**Comment by valorkin** [comment]
please try to run https://github.com/valor-software/angular2-quickstart
as far as I understood angular2 not working in IE without IE specific shims
and date\time related stuff not working in Safari without `intl` polyfill

So I should add them to demo

**Comment by johan13** [comment]
The quickstart works fine. I have the shims in my app.

I am using typeahead and pagination from ng2-bootstrap. Pagination works in
all browser and Typeahead works in all browsers except IE.

I have started to look into the problem but I haven't got anywhere. The
problem appears when angular tries to eval a function named
ChangeDetector_TypeaheadContainerelementoptionsthiselementelementthis_matchesObjectassign_0.
There is a syntax error somewhere in the eval:ed string.

**Comment by valorkin** [comment]
Can you please check, is Object.assign is defined in IE?
if not it could be a root of an issue

**Comment by johan13** [comment]
Yes it is:
[image: Inline image 1]

I think the problem is the "name" property of the TypeaheadContainer
component gets a bad value for some reason. All other components have the
correct name, even the Typeahead component. But the TypeaheadContainer has
the function name plus some of its definition:

[image: Inline image 2]

[image: Inline image 3]

These values are from a breakpoint on line 22968 of angular2.dev.js in beta
12. I don't know if I'm making any sense at all. I will keep digging for a
little longer...

/ Johan

**Comment by johan13** [comment]
shims_for_IE.js has a shim for function.name. This shim works fine, but at
some point the name-shim appears to be replaced by a different
implementation that doesn't work.

I don't know if this is done by ng2-bootstrap or angular2 or something else
yet...

/ Johan

**Comment by johan13** [comment]
I found the bug. It is in angular's IE shim. I will send a pull request to
them!

**Comment by valorkin** [comment]
Great to here! Please add a link to issue in angular 2 so we can track a progress here

**Comment by johan13** [comment]
PR: https://github.com/angular/angular/pull/7864

**Comment by valorkin** [comment]
except Intl
