### ISSUE TITLE
"Shown" Notification on Component

### ISSUE THREAD

**Issue by jamiewastin** [valor-software/ngx-bootstrap#3339]
I am using the `BsModalService` to display a modal with a component, as demonstrated in the [official documentation](https://valor-software.com/ngx-bootstrap/#/modals#service-component).

I would like to add a callback within the component to be notified when the modal is shown. However, there does not seem to be any mechanism to subscribe for this on the injected `BsModalRef`.

I intend on using this notification to be able to set the focus on an `<input />` box on my modal.

**Comment by featured14** [comment]
You can achieve this by using `BsModalService`
For example:

```
import { BsModalService, BsModalRef } from 'ngx-bootstrap';
...
constructor(private modalService: BsModalService) { }
...
openModal() {
  this.bsModalRef = this.modalService.show(MyModalComponent);
  this.modalService.onShown.subscribe(() => {
     // do something
  })
}
```

You can also check all the events emitted by the service `onShow`, `onShown`, `onHide`, `onHidden`.

**Comment by jamiewastin** [comment]
@ABD-dev - How can I access my component from this callback? In your code sample my reference of `this.bsModalRef` does not afford me any access to the underlying rendered component.

**Comment by featured14** [comment]
As far as I know, it is not possible to directly do that. You have the option to leverage a service, send something and subscribe on the other side (in the modal component).  
Roughly, have a subscription in the component which house the modal, and trigger the "emitter" in the onShown subscriber. :)

**Comment by IlyaSurmay** [comment]
You can use `ngOnInit` or `ngAfterViewInit` in your component.

**Comment by jamiewastin** [comment]
@IlyaSurmay  - Adding a breakpoint to a `ngAfterViewInit` method highlights the fact that the components have not been added to the document (i.e. I cannot see them on the page) before this methods is invoked. I believe this is why my call to focus() is not having the desired effect.

**Comment by IlyaSurmay** [comment]
@jamiewastin I think that you can wrap `focus()` in `setTimeout(()=>{...}, 0)`. ugly workaround but it should help for now

**Comment by valorkin** [comment]
@jamiewastin we are working on the second version of modal service, where you will be able to access component inside of modal and a lot of other nice things :)
