### ISSUE TITLE
Make Angular 2 dependency more relaxing

### ISSUE THREAD

**Issue by sonicoder86** [valor-software/ngx-bootstrap#334]
Currently the Angular 2 version is hardcoded and it permits repositories using it to upgrade to new versions as soon as possible and test it with new versions.
Dependency can be similar to ng2-translate's: 

```
"peerDependencies": {
  "angular2": ">= 2.0.0-beta.0",
  "es6-promise": ">= 3.0.2",
  "es6-shim": ">= 0.33.3",
  "reflect-metadata": ">= 0.1.2",
  "rxjs": ">= 5.0.0-beta.0",
  "zone.js": ">= 0.5.10"
}
```

Is it acceptable? If so i would make a PR.

**Comment by valorkin** [comment]
Can you guarantee that future versions will not broke bootstrap functionality?
 I am not, until tested.
When ng2 will be released, dependencies will be relaxed a bit
Plus it is just peed devs, you can ignore warning
But at least bootstrap is honest, and giving a warning :)

**Comment by sonicoder86** [comment]
No i can not guarantee, but at least it gives users of the library the ability.to upgrade and not make a hard dependency on it without error messages.
Or the other solution maybe to remove it from peerdeps, is it ok?

**Comment by sonicoder86** [comment]
M yintention is to include it in my starter project https://github.com/blacksonic/angular2-es6-starter
And as a new version comes out i want to upgrade.

**Comment by valorkin** [comment]
are you using npm3? than it is just a warning hint
I am completely with you about updating just in time
but for now even not all ng2 version a working
for example I had to skip 10 and 11

**Comment by sonicoder86** [comment]
Using npm2 to be usable with node 4.x branch also

**Comment by sonicoder86** [comment]
Stating incompatible versions in readme and be more relaxing?

**Comment by valorkin** [comment]
Percent of users reading readme is low, really low. Update to npm 3 and don't 
bother yourself with node 4. In April will be released node 6 LTS.
