### ISSUE TITLE
BsLocaleService problem  Trying to import

### ISSUE THREAD

**Issue by fventurini** [valor-software/ngx-bootstrap#3345]
### Bug description:
BsLocaleService problem

Trying to import
import { BsDatepickerConfig, BsLocaleService } from 'ngx-bootstrap/datepicker';

but no success with BsLocaleService

"...node_modules/ngx-bootstrap/datepicker/index"' has no exported member 'BsLocaleService'.

Is there some suggestion or tricks or something bugged?

### Versions of ngx-bootstrap, Angular, and Bootstrap:

"@angular/cli": "1.3.2"

  "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "angular-confirmation-popover": "^3.2.0",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.7.1",
    "core-js": "^2.4.1",
    "ng2-charts": "^1.6.0",
    "ng2-cookies": "^1.0.12",
    "ng2-pagination": "^2.0.2",
    "ngx-bootstrap": "^1.9.3",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"

**Comment by anshu2212** [comment]
@fventurini There is no BsLocaleService in ngx-bootstrap 1.9.3 . it was introduced in 2.0.0.beta-11 .
please change the doc version from right corner(for desktop view ) to refer to doc for the 1.9.3.
I also did the same mistake , that i later realized.

**Comment by valorkin** [comment]
@anshun2122 thats correct
We will update versioning dropdown
CC Alex, please add note to roadmap

**Comment by fventurini** [comment]
Thanks @anshu2212  @valorkin 
Merry Xmas
