### ISSUE TITLE
Datetime picker

### ISSUE THREAD

**Issue by muralimnmcse** [valor-software/ngx-bootstrap#3347]
### Bug description or feature request:

Whether we have any dateandtime picker like in the sample http://eonasdan.github.io/bootstrap-datetimepicker/

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.10

Angular: 5

Bootstrap: 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:
#

**Comment by valorkin** [comment]
If you will check source code, you will see it there
But we decided to focus on releasing solid v2
Closing as duplicate feature request

PS it will be done for sure :)

**Comment by maxyharr** [comment]
Is there any update on this being added soon? Would love a DateTimePicker.
