### ISSUE TITLE
date should highlight today date but binding should be DB date?

### ISSUE THREAD

**Issue by siva563** [valor-software/ngx-bootstrap#3351]
Hi Team, Need small help.

Actually I am getting data from DB like below 
```
data = [{
 date:''"01/10/2013",
name:"Name"
}
]
```
data is binding correctly but when i open the calendar today should be highlight, any way to do it.

**Comment by IlyaSurmay** [comment]
For now there's no possibility to highlight today or any specific day, this will be added in future releases.

**Comment by IlyaSurmay** [comment]
Closing as a duplicate of #3192
