### ISSUE TITLE
fix(modal): BsModalService cannot instantiate the component from lazy-loaded module.

### ISSUE THREAD

**Issue by zzJinux** [valor-software/ngx-bootstrap#3353]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Bug description or feature request:
BsModalService internally uses ComponentFactoryResolver, and BsModalService is designed to be provided to the root injector.
For current latest version (5.1.2) of angular, The CFR from the root cannot instantiate the component from lazy-loaded module. (See angular/angular#14324)

BsModalService should be able to handle this situation. By either adding a parameter that accepts CFR  or implementing intermediate service which can retrieve proper CFR. (as used in [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/modal/modal.ts#L53))

### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/ngx-bootstrap-playground-mtwpzg

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-rc.0

Angular: 5.1.2

Bootstrap: n/a

**Comment by zzJinux** [comment]
I found that this issue is duplicate of valor-software/ngx-bootstrap/issues/2356.
Should I close this?

**Comment by IlyaSurmay** [comment]
Yep, it's a duplicate of #2356
