### ISSUE TITLE
 BsModalService's enter key event how to solve multiple problems?

### ISSUE THREAD

**Issue by elpmisu** [valor-software/ngx-bootstrap#3356]
When I create a modal with BsModalService, Enter key will create multiple modal

**Comment by elpmisu** [comment]
How can I solve this problem？

**Comment by IlyaSurmay** [comment]
That's happening because modal doesn't focus its root element so button remains focused and pressing enter is triggering function that shows modal. This will be fixed in future release, meanwhile, you can manually focus something in modal after it's shown.
