### ISSUE TITLE
BsDropdownModule - Dropdown not working/opening with --prod switch

### ISSUE THREAD

**Issue by sjardine** [valor-software/ngx-bootstrap#3362]
ngx-bootstrap: 2.0.0-rc.0
Angular: 5.1.2
Bootstrap: 3.3.7
Angular CLI: 1.6.2

[ngx-bootstrap-dropdown.zip](https://github.com/valor-software/ngx-bootstrap/files/1588018/ngx-bootstrap-dropdown.zip)

The attached file contains a basic project generated with `ng new` then add bootstrap (3.3.7) and ngx-bootstrap (2.0.0-rc.0).

The example dropdown does not work when starting with `ng serve --prod` but works with `ng serve`

**Comment by IlyaSurmay** [comment]
Please reinstall node_modules and check it one more time. When I looked at your repo it was broken too but after a while, I reinstalled all dependencies and it started working. Perhaps some dependency was broken.

**Comment by sjardine** [comment]
Strange....  I tried that before I created the issue.  It's working now.  Thanks!
