### ISSUE TITLE
Cannot resolve all parameters for 'l'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'l' is decorated with Injectable

### ISSUE THREAD

**Issue by miran9819** [valor-software/ngx-bootstrap#3363]
While opening modal i am getting this error.

The same modal opens in development mode but when i build in production mode i get this error while opening the modal

Code
`
 
   import { Component, Inject , OnInit } from '@angular/core';
   import { DataTableModule } from 'primeng/components/datatable/datatable';
   import { SharedModule } from 'primeng/components/common/shared';
   import { ClientModalComponent } from './clients-modal/client-modal.component';
   import { BsModalService } from 'ngx-bootstrap/modal';
   import { BsModalRef } from 'ngx-bootstrap/modal/modal-options.class';

   @Component({
      selector: 'app-clients',
      templateUrl: './clients.component.html',
      styleUrls: ['./clients.component.scss']
    })

   export class ClientsComponent implements OnInit {

       bsModalRef: BsModalRef;
       constructor(@Inject(BsModalService) private modalService) {}

    openClientModal() {
         this.bsModalRef = this.modalService.show(ClientModalComponent, {class: 'modal-lg'});
         console.log(this.bsModalRef);
         this.bsModalRef.content.title = 'New Client';
       }

     ngOnInit() { }
    }
 

`

**Comment by IlyaSurmay** [comment]
Have you tried to inject bsModalService as it's shown in demo?
```
import { BsModalService } from 'ngx-bootstrap/modal';
...
constructor(private modalService: BsModalService) {}
```

Also you don't have a type annotation for bsModalService

**Comment by miran9819** [comment]
yes i tried that also but stilll not working.
it works in development mode, when i do a build in production mode i get this error

**Comment by miran9819** [comment]
This my Plunker file
https://plnkr.co/edit/74O9JvbgQpLcontOjhkV?p=preview


Unable to reproduce issue in plunker

As i said it works in development mode but fails in production mode

**Comment by miran9819** [comment]
Works Fine in dev mode

![screen shot 2017-12-27 at 6 26 41 pm](https://user-images.githubusercontent.com/25218346/34382263-97e139c2-eb33-11e7-9a13-9f87c117b517.png)

Get error in production mode

![screen shot 2017-12-27 at 6 24 28 pm](https://user-images.githubusercontent.com/25218346/34382190-3dc268f8-eb33-11e7-8413-bb4d52ff2fa7.png)
please build this code in production mode

**Comment by IlyaSurmay** [comment]
I copied code from plunkr to new clean angular cli project and it worked fine. Could you create a small repo with reproduction?

**Comment by miran9819** [comment]
It worked in ^2.0.0-rc.0 , i was using 1.9.3 where i was getting this error so i re-installed the latest modues 

thnx for the support
