### ISSUE TITLE
Error while building the app in production version

### ISSUE THREAD

**Issue by thecodeguru360** [valor-software/ngx-bootstrap#3364]
[BUG] Error while building the app in production version. ( ng build --dev is working )

ERROR in Error at /Users/laeeqahmed/Documents/weed-backend/node_modules/ngx-bootst
rap/datepicker/daypicker.component.d.ts.DayPickerComponent.html(53,38):  ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" [ERROR ->]let-rowz="$implicit" let-index="ind
ex">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].sec")
Error at /Users/laeeqahmed/Documents/weed-backend/node_modules/ngx-bootstrap/datep
icker/daypicker.component.d.ts.DayPickerComponent.html(53,59):  ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" let-rowz="$implicit" [ERROR ->]let-index="ind
ex">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6].sec
")

### I am not using datePicker anywhere in my project

here is my app.module.ts

`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { LocationStrategy, HashLocationStrategy } from '@angular/common';

import { AppComponent } from './app.component';

// Import containers
import {
  FullLayoutComponent,
  SimpleLayoutComponent
} from './containers';

const APP_CONTAINERS = [
  FullLayoutComponent,
  SimpleLayoutComponent
]

// Import components
import {
  AppAsideComponent,
  AppBreadcrumbsComponent,
  AppFooterComponent,
  AppHeaderComponent,
  AppSidebarComponent,
  AppSidebarFooterComponent,
  AppSidebarFormComponent,
  AppSidebarHeaderComponent,
  AppSidebarMinimizerComponent,
  APP_SIDEBAR_NAV
} from './components';

const APP_COMPONENTS = [
  AppAsideComponent,
  AppBreadcrumbsComponent,
  AppFooterComponent,
  AppHeaderComponent,
  AppSidebarComponent,
  AppSidebarFooterComponent,
  AppSidebarFormComponent,
  AppSidebarHeaderComponent,
  AppSidebarMinimizerComponent,
  APP_SIDEBAR_NAV
]

// Import directives
import {
  AsideToggleDirective,
  NAV_DROPDOWN_DIRECTIVES,
  ReplaceDirective,
  SIDEBAR_TOGGLE_DIRECTIVES
} from './directives';

const APP_DIRECTIVES = [
  AsideToggleDirective,
  NAV_DROPDOWN_DIRECTIVES,
  ReplaceDirective,
  SIDEBAR_TOGGLE_DIRECTIVES
]

// Import routing module
import { AppRoutingModule } from './app.routing';

// Import 3rd party components
import { BsDropdownModule } from 'ngx-bootstrap/dropdown';
import { TabsModule } from 'ngx-bootstrap/tabs';
import { ChartsModule } from 'ng2-charts/ng2-charts';
import { PageComponent } from './page/page.component';
import { LoginComponent } from './login/login.component';
import {ToastModule} from 'ng2-toastr/ng2-toastr';
import { CookieModule } from 'ngx-cookie';
import { FormsModule, ReactiveFormsModule } from "@angular/forms";
import { HttpClientModule, HttpClient } from '@angular/common/http';
import { DatabaseService } from "app/database.service";
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { ProductComponent } from './product/product.component';
import { NotificationComponent } from './notification/notification.component';
import { ReportedComponent } from './reported/reported.component';
import { SocketService } from "app/socket.service";
import { AngularMultiSelectModule } from 'angular2-multiselect-dropdown/angular2-multiselect-dropdown';
import { NgxDatatableModule } from '@swimlane/ngx-datatable';
import { ModalModule } from 'ngx-bootstrap';
import { ConfirmationPopoverModule } from 'angular-confirmation-popover';

@NgModule({
  imports: [
    BrowserModule,
    AppRoutingModule,
    BsDropdownModule.forRoot(),
    TabsModule.forRoot(),
    ChartsModule,
    ToastModule.forRoot(),
    CookieModule.forRoot(),
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule,
    BrowserAnimationsModule,
    AngularMultiSelectModule,
    NgxDatatableModule,
    ModalModule.forRoot(),
    ConfirmationPopoverModule.forRoot({
      confirmButtonType: 'danger' // set defaults here
    })
  ],
  declarations: [
    AppComponent,
    ...APP_CONTAINERS,
    ...APP_COMPONENTS,
    ...APP_DIRECTIVES,
    PageComponent,
    LoginComponent,
    ProductComponent,
    NotificationComponent,
    ReportedComponent
  ],
  providers: [{
    provide: LocationStrategy,
    useClass: HashLocationStrategy
  },DatabaseService,SocketService],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
`

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.9.3

Angular: 5.0.1

Bootstrap: 4.0.0-beta.2

**Comment by IlyaSurmay** [comment]
Update to latest version `2.0.0-rc.0` and try again. 1.x.x doesn't support angular 5

**Comment by thecodeguru360** [comment]
Thanks, its building now!
