### ISSUE TITLE
fix(system.js): directive annotation issues in angular2.min.js bundle

### ISSUE THREAD

**Issue by keathmilligan** [valor-software/ngx-bootstrap#337]
Doing some testing with a simple starter app that displays a datepicker. It works fine if i use the unminified angular2.js or angular2.dev.js, but if I use angular2.min.js, I get "EXCEPTION: No Directive annotation found on e".

**Comment by valorkin** [comment]
Set mangle false if not helping, please provide plunker or repo link

**Comment by valorkin** [comment]
ok, I have tried with github.com/valor-software/angular2-quickstart
there are some issues indeed
not sure is it in angular2 or in ng2-bootstrap

**Comment by alexandrehebert** [comment]
A similar problem appears when i upgrade from 1.0.11 to 1.0.13 and with angular 2.0.0-beta.15.
I use https://github.com/AngularClass/angular2-webpack-starter.

" Error: Uncaught (in promise): No Directive annotation found on Dropdown "

**Comment by valorkin** [comment]
It could be not so similar, this is system.js only issue
