### ISSUE TITLE
docs(dropdown): dropdowns placement doesn't affect anything if dropdown is shown inline

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#3370]
### Bug description or feature request:

Placement of a popover doesn't work when it is set to "top"

### Plunker/StackBlitz that reproduces the issue:

https://valor-software.com/ngx-bootstrap/#/dropdowns#triggers-manual

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: latest

Angular: 4

Bootstrap: 4

**Comment by IlyaSurmay** [comment]
`placement` doesn't affect anything if dropdown is shown inline (without `container="body"`). We'll add this info in docs, thanks!

**Comment by bhaskerchari** [comment]
placement doesn't seem to effect anything even if dropdown is not shown inline (with container="body" is set).
