### ISSUE TITLE
Template parse errors: 'slide' is not a known element

### ISSUE THREAD

**Issue by bschauhan** [valor-software/ngx-bootstrap#3377]
![screenshot from 2018-01-01 16-41-33](https://user-images.githubusercontent.com/6029025/34467280-b270b74e-ef12-11e7-99ec-be46c68d847f.png)

**## Version Details:**

Angular CLI: 1.6.3
Node: 6.10.3
OS: linux x64
Angular: 5.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

angular/cli: 1.6.3
angular/language-service: 4.4.6
angular-devkit/build-optimizer: 0.0.36
angular-devkit/core: 0.0.22
angular-devkit/schematics: 0.0.42
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.9.3
schematics/angular: 0.1.11
schematics/schematics: 0.0.11
typescript: 2.6.2
webpack: 3.10.0

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.9.3

Angular: 5.0.5

Bootstrap: 3

**Comment by IlyaSurmay** [comment]
Not much info here :( now it seems that you're trying to use carousel but you haven't imported CarouselModule
Please provide more info or this issue will be closed.

**Comment by valorkin** [comment]
hey

you forgot to import `CarouselModule` in `MyAccountModule`

**Comment by StanislawVictorovich** [comment]
@angular-devkit/schematics
