### ISSUE TITLE
fix(demo): left sidebar is not fully visible on small screens

### ISSUE THREAD

**Issue by smnbbrv** [valor-software/ngx-bootstrap#3383]
### Bug description or feature request:

Cannot see Typeahead sidebar menu item on Mac 13 inches in Demo. The sidebar is not scrollable; at first I really thought it is not supported anymore

**Comment by 1-0-1** [comment]
Is this about the documentation page @ https://valor-software.com/ngx-bootstrap/#/getting-started?  The scrollbar is off the screen in the left hand panel and so I can't scroll to the last item in the list.

**Comment by valorkin** [comment]
there are should be scroll bar
plus there are a filter on top

**Comment by 1-0-1** [comment]
Yes, the scroll bar is there, but the sizing for the left panel is off such that the end of the scroll bar is not visible.
If you know what you are looking for, yes you can filter.  But for a new user who is looking to see what there is, this doesn't work.
![image](https://user-images.githubusercontent.com/5114396/34836733-ae34f3b4-f6ad-11e7-9000-6150ed3713b3.png)
