### ISSUE TITLE
How to get Input values from nested component modal

### ISSUE THREAD

**Issue by hellodpk** [valor-software/ngx-bootstrap#3403]
Hi 
For some requirement I have to nested component modal in my project. It is working but the problem is I cannot get input values from the nested component modal.

[Demo](https://stackblitz.com/edit/angular-nested-component-modal-ngx-bootstrap-not-working?file=app/app.component.ts)

Here I am getting  the value from the first modal (firsrt name )but I am not getting the value from the nested component(last name) to form full name.

I can find that I can pass data to nested modal like

` this.modalRef.content.title = 'Modal with component';`

So this title I can see this title in the nested modal.

 I think that there should some way to get input values from the nested modal back to the parent component.

**Comment by IlyaSurmay** [comment]
There's no need to duplicate your question here if you already asked it on SO https://stackoverflow.com/questions/48102400/how-to-get-input-values-from-nested-component-modal-ngx-bootstrap-using-angular
