### ISSUE TITLE
Convert GMT to ISO date format

### ISSUE THREAD

**Issue by Arpanx** [valor-software/ngx-bootstrap#3408]
`bsStart: Date = new Date();
@Input() item: {  timeStart: string };

ngOnInit() {
        this.bsStart = new Date(this.item.timeStart);
}

onChangeDatePickerStart(event: any) {
        this.item.timeStart = this.toISO(event);
}

toISO(event: any) {
        const re = /0[0-9]00/gi;
        const str = String(event);
        const res = str.replace(re, '0000');
        const d = new Date(res);

        return d.toJSON();
        // Wed Feb 28 2018 00:00:00 GMT+0200 (Eastern Europe Standard Time)
        // 2018-02-28T00:00:00.000Z
}
`
<input type="text" class="form-control"  #dp="bsDatepicker" bsDatepicker [(ngModel)]="bsStart" 
(bsValueChange)="onChangeDatePickerStart($event)">

NOTE:   My version, has not tested in real work yet. Works only for single-valued TimeZone

**Comment by IlyaSurmay** [comment]
Sorry, I don't quite understand, is this an issue or an enhancement?

**Comment by Arpanx** [comment]
I just shared my decision. Can someone come in handy. Or someone will make or tell a more beautiful solution.

**Comment by IlyaSurmay** [comment]
There's a method for this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
