### ISSUE TITLE
question(datepicker): Inline calendar click event

### ISSUE THREAD

**Issue by ulric4690** [valor-software/ngx-bootstrap#3410]
Hi,

I am implementing **inline calendar** but I am facing certain issues.

I want to add tooltip on the click of date. Since the HTML content inside  the calendar is refreshing, so it is not possible to add ngx-tootlip (If any one can help me to add existing tooltip component will be helpful). So I decided to create the Tooltip component.

In existing inline date picker there are 2 click event out which I am using **selectionDone**. For tooltip I need position of particular date which I am calculating when "active" class is added on date. Now the problem I am facing is in finding the position of particular click. Since the"active" class has been added using ngClass and **click** event has been emitted using **@output**. So in this case Click event is broadcast first and then active class has been added using ngClass.

So can you please help me with this 2 issue.

Thanks in advance.

Regards,
Mangesh

**Comment by Domainv** [comment]
close as outdated
