### ISSUE TITLE
feat(modal): add declaration of checkScrollbar in modal

### ISSUE THREAD

**Issue by yiibryan** [valor-software/ngx-bootstrap#3411]
In npmjs package, the bs-modal.service.d.ts do not declare  checkScrollbar function.

I can not call it by "this.modalService.checkScrollbar();"

**Comment by IlyaSurmay** [comment]
This method is marked as internal so compiler doesn't add it to `.d.ts` https://github.com/valor-software/ngx-bootstrap/blob/development/src/modal/bs-modal.service.ts#L144

Why would you need to call it directly?

**Comment by yiibryan** [comment]
Os: windows 7, browser: chrome 63.0.3239.108

When I use it to load a modal by 
this.modalService.show(HelloComponent, {'class': 'modal-hello'});

I use the service method in https://valor-software.com/ngx-bootstrap/#/modals.

The body scrollbar disappear. But the body css style "padding-right:0". 

It did not work like the example. In example, it added padding-right:17px to body.

The layout will move right about 17px.(padding-right is not working as I hope.)

I need keep the content layout fixed when hiding the body scrollbar .

**Comment by IlyaSurmay** [comment]
Could you provide a reproduction via plunkr/stackblitz? 
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by yiibryan** [comment]
Please check https://stackblitz.com/edit/ngx-bootstrap-a6c476. 
It is source code.
https://ngx-bootstrap-a6c476.stackblitz.io/test
You can check the page with product issue. 

Please pay attention to the scroll bar & table column at right side of page.

**Comment by IlyaSurmay** [comment]
Well, in your example you don't have bootstrap.css included and this causes the issue with the scrollbar. if you add bootstrap.css as I did [here](https://stackblitz.com/edit/ngx-bootstrap-4avc5d?file=main.ts) it works as expected.

**Comment by yiibryan** [comment]
What's reason cause this issue?

I only want to use the ngx-bootstrap without bootstrap.min.css.

I want to confirm where cause the issue.

So, I can add extra css/sass style to my css file to avoid this issue.

why did bootstrap.min.css effect the ngx-bootstrap function?

**Comment by yiibryan** [comment]
Please check https://valor-software.com/ngx-bootstrap/#/modals

API section, search "checkScrollbar", it shows us it is a public method.

But I can not call it in my project. No function with "checkScrollbar" support.

**Comment by IlyaSurmay** [comment]
Bootstrap css has `modal-open` class which affects overflow settings of page. If you're not including bootstrap.css, you don't have those styles and this causes the issue. If you don't want to include bootstrap.css you can just copy everything with `.modal-open` and it should work ok

**Comment by yiibryan** [comment]
I checked the _modal.scss in bootstrap.
And found the solution by adding 
// Measure scrollbar width for padding body during modal show/hide
.modal-scrollbar-measure {
  position: absolute;
  top: -9999px;
  width: 50px;
  height: 50px;
  overflow: scroll;
}
