### ISSUE TITLE
Testing is fail on Travis CI but pass on my machine

### ISSUE THREAD

**Issue by tumit** [valor-software/ngx-bootstrap#3414]
Hi everyone,

I'm try to [add Thai locale support for datepicker](https://github.com/valor-software/ngx-bootstrap/pull/3409) (follow step of this post [added Turkish locale support for datepicker ](https://github.com/valor-software/ngx-bootstrap/pull/2700) )

but i found problem when Travis CI say this [PR testing is fail](https://travis-ci.org/valor-software/ngx-bootstrap/builds/326088838?utm_source=github_status&utm_medium=notification)  

> ERROR [karma]: Error: Module not found: Error: Can't resolve 'markdown-loader'

but it looking good on my machine so How can I fix this problem ?

**Comment by IlyaSurmay** [comment]
Hi! We're working on this right now

**Comment by IlyaSurmay** [comment]
Should be fixed with #3416

**Comment by tumit** [comment]
@IlyaSurmay Thanks very much. It look OK already
