### ISSUE TITLE
Bootstrap dateRange picker - prevent user from entering characters

### ISSUE THREAD

**Issue by experionakash** [valor-software/ngx-bootstrap#3415]
Hi,
I'm using bsDaterangepicker (`"ngx-bootstrap": "^1.9.3"`) with angular 4.

I need to prevent the user from entering date values rather than selecting through the date picker. 

I found that when entering characters in date range picker, its breaks. please see the attachment
![bsdate issue](https://user-images.githubusercontent.com/23092972/34725081-e8f66a98-f575-11e7-99b1-78069475b18a.PNG)

**Comment by IlyaSurmay** [comment]
Could you create a plunkr/stackblitz with reproduction?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by experionakash** [comment]
The issue is there in the demo (https://valor-software.com/ngx-bootstrap/old/1.9.3/#/datepicker).
when I entered some characters in the date range picker field, then its breaks as shown in the attachment.
![screenshot 131](https://user-images.githubusercontent.com/23092972/34730759-5465ca84-f586-11e7-8585-236c320545ec.png)

**Comment by valorkin** [comment]
hey, this should solve your issue: https://www.w3schools.com/tags/att_input_readonly.asp

**Comment by shuklashaishav** [comment]
@valorkin  Thank you that did the trick.
