### ISSUE TITLE
feat(daterangepicker):  add date validity validation

### ISSUE THREAD

**Issue by hugonne** [valor-software/ngx-bootstrap#3417]
If you mark the input for the Daterangepicker as required in your HTML, then type some random text and press Tab to move to the next input, Daterangepicker will remove that "bad" text (as expected), but the input itself will still be valid (ng-valid class gets injected by Angular). 

Initial state:
![image](https://user-images.githubusercontent.com/22403732/34729407-2fe4a4fa-f522-11e7-9a87-69b3089af805.png)

Invalid text entered:
![image](https://user-images.githubusercontent.com/22403732/34729426-3f224fb2-f522-11e7-8d8f-8ad5307a7923.png)

After control looses focus:
![image](https://user-images.githubusercontent.com/22403732/34729439-4ada2cf8-f522-11e7-8d23-7164b3495494.png)

**Comment by pradeepmay13** [comment]
Hi,
I am unable to validate using custom validator on datepicker while entering junk data it returns Invalid Date.
For Blank input field validation is working fine as shown in figure
![datepicker](https://user-images.githubusercontent.com/12856995/39035661-799cb1c6-4498-11e8-8ddb-cf19210a2dd4.JPG)

But when i am entering character or junk data it returns Invalid date but i am unable to apply angular validation. Please help
![datepicker2](https://user-images.githubusercontent.com/12856995/39035660-79629298-4498-11e8-80d5-9bc7f5ebf186.JPG)

**HTML Code for This**

<input type="text" class="form-control" name="rrf_temp_tenure_from_date" formControlName="rrf_temp_tenure_from_date" placeholder="From Date" bsDatepicker [bsConfig]="{ dateInputFormat: 'DD-MM-YYYY', containerClass:'theme-dark-blue' }">
                            </div>
                                <div *ngIf="rrfForm.controls['rrf_temp_tenure_from_date'].touched && !rrfForm.controls['rrf_temp_tenure_from_date'].valid " class="text-danger">
                                    <span *ngIf="rrfForm.controls['rrf_temp_tenure_from_date'].hasError('required') "> 
                                        From Date is required                                 
                                    </span> 
                                    <span *ngIf="!rrfForm.controls.rrf_temp_tenure_from_date.hasError('required') && rrfForm.controls.rrf_temp_tenure_from_date.hasError('invalidDate')">Please Enter Valid Date</span>
                                </div>

**TS file code**
this.rrfForm.get('rrf_temp_tenure_from_date').setValidators([Validators.required, ValidationService.dateValidator]);

**Service function**

static dateValidator(control) {
        if (control.value.match(/^(0[1-9]|1\d|2\d|3[01])\.(0[1-9]|1[0-2])\.(19|20)\d{2}$/)) {
            return null;
        } else {
            return { 'invalidPassword': true };
        }
    }

**Getting Error on Console :**
![image](https://user-images.githubusercontent.com/12856995/39035919-7a80c004-4499-11e8-810e-18dfb1f7d6f6.png)

**Comment by valorkin** [comment]
Added

**Comment by pradeepmay13** [comment]
@valorkin what is the solution could you please explain?
