### ISSUE TITLE
Error with Angular2 / Ionic2

### ISSUE THREAD

**Issue by giagar5** [valor-software/ngx-bootstrap#342]
With latest ionic2 (angular2 - beta6), I get this error:

node_modules\ng2-bootstrap\components\carousel.ts:1
import {Slide} from './carousel/slide.component';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

Any idea?

Thanks, J5

**Comment by valorkin** [comment]
Issue is for sure with compiler, not with ionic or bootstrap
