### ISSUE TITLE
Refusing to install ng2-bootstrap as a dependency of itself

### ISSUE THREAD

**Issue by GTamara** [valor-software/ngx-bootstrap#343]
I try to install ng2-bootstrap with
npm install --save ng2-bootstrap

then I get the following message:
npm ERR! Linux 3.19.0-56-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "ng2-bootstrap"
npm ERR! node v5.4.0
npm ERR! npm  v3.5.3
npm ERR! code ENOSELF

npm ERR! Refusing to install ng2-bootstrap as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/t/ng2-bootstrap/npm-debug.log

[npm-debug.log.txt](https://github.com/valor-software/ng2-bootstrap/files/194987/npm-debug.log.txt)
npm-debug.log file is attached

Thank you in advance.

**Comment by valorkin** [comment]
This is expected, if you try to install ng2-bootstrap in ng2-bootstrap folder :)
