### ISSUE TITLE
fix(build): isBs3() function not work properly with chrome + unzoom + windows

### ISSUE THREAD

**Issue by FightTheWar** [valor-software/ngx-bootstrap#3446]
### Bug description or feature request:
isBs3() function not work properly with chrome in some situation
You can try the example whith Chrome browser, unzoom to 50% and reload the page
First the function return true, the after relaod it will be false

The problem come from utils/theme-provider.js
In _guessBsVersion() you test rect.top === 0
But with unzoom this test can be true with Bootstrap 3 + chrome

### Plunker/StackBlitz that reproduces the issue:
https://plnkr.co/edit/ZFXpDBBcOegQyKjByMEi?p=preview

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 2.0.0-rc.0
Angular: 5.1.2
Bootstrap: 3.3.7
Chrome version 63.0.3239.132

**Comment by IlyaSurmay** [comment]
Works fine on my machine 
![qtlydtwhsko4set3oi_ula](https://user-images.githubusercontent.com/18414330/34877721-e4dba428-f7af-11e7-8dcc-1c70562ce27d.png)
modified plunker with bigger font - https://plnkr.co/edit/5xc2i4DpnEAbAnvqYwnp?p=preview

**Comment by valorkin** [comment]
@IlyaSurmay did you cleaned local storage before testing? :)

**Comment by valorkin** [comment]
ok, I can not reproduce it too

**Comment by valorkin** [comment]
@IlyaSurmay need to try on windows

**Comment by FightTheWar** [comment]
Hello, I confirm, it occurs only under windows
