### ISSUE TITLE
Typeahead breaks on error codes 404, 500, etc.

### ISSUE THREAD

**Issue by phildaniels** [valor-software/ngx-bootstrap#3451]
The typeahead component stops functioning after encountering an http error code. I would argue that after an error code, ESPECIALLY a 404, if the user backspaces and starts typing again, the component should continue to function.  Unless I've encountered a bug, I think this qualifies as a feature request

**Comment by valorkin** [comment]
I am sure for 100% that typeahead should not know about existence of http module
but I could agree that typeahead should be error prone

I would suggest filter out wrong responses from hitting typeahead
