### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by xyrintech** [valor-software/ngx-bootstrap#3457]
I need material design for the app, I am trying to use this library https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design and I believe this is the only library for doing so. 

When I setup this library the layout breaks.

Is this something compatible to work with?

**Comment by DavidRnR** [comment]
Hi @xyrintech!

I think is not a good practice mix bootstrap & material.

Anyway _Angular Material_ is official. Here more info https://material.angular.io/guide/getting-started

To install it in your proyect run:

`npm install --save @angular/material @angular/cdk`
