### ISSUE TITLE
fix(build): Angular 5.2 ngc build produces node_modules folder with missing js files

### ISSUE THREAD

**Issue by AllNamesRTaken** [valor-software/ngx-bootstrap#3458]
### When building the generated node_modules folder is missing .js files referenced in the factories.
This problem is also described [here](https://stackoverflow.com/questions/47453407/how-to-use-third-party-components-in-angular-5-with-aot). Since the imports are re-written to relative paths but the original js files are omitted, bundling using e.g. rollup fails.

### Reproduction
- compile using ngc

ngx-bootstrap: 2.0.0-rc0

Angular: 5.2.0

Bootstrap: 3

**Comment by valorkin** [comment]
how to reproduce?

you mean: you have cloned ngx-bs and cannot start it?

**Comment by IlyaSurmay** [comment]
Please provide a repo with reproduction.

**Comment by AllNamesRTaken** [comment]
As Requested:
[my repo](https://github.com/AllNamesRTaken/ngx-test)

It doesnt do anything, just compiles.
