### ISSUE TITLE
NgbDropdown works only after page refresh/Re-route

### ISSUE THREAD

**Issue by roeehershko** [valor-software/ngx-bootstrap#3459]
This is pretty weird behavior but normally, its working
i use the dropdown module, it doesnt work when when i use angular manually redirect function:

```
router.navigate(['/']);
```

to a page which uses ngbDropdown, it starts to work again after page refresh or pressing "back" and "forward" in the browser

**Comment by IlyaSurmay** [comment]
ngbDropdown is a part of ng-bootstrap, not ngx-bootstrap
