### ISSUE TITLE
Full Module with Angular 5

### ISSUE THREAD

**Issue by DavidRnR** [valor-software/ngx-bootstrap#3460]
Hi everyone!

I've using ngx-bootstrap for a long while. In the project (_Angular 4_) that I'm working we use Ng2BootstrapModule. A Module with all bootstrap-modules like you can see in *ngx-bootstrap@2.0.0-beta.2*.

I decided to upgrade to _Angular 5_. So I got errors about ngx-bootstrap.

I updated ngx-bootstrap to **2.0.0-rc.0**. Now Angular 5 is working but I had to import every module (Alert, Modal, etc) to every module where ngx-bootstrap is needed.

So I searched for a complete module with all ones, but **there is not one**.

I created a new one (All is working fine now):

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AccordionModule, AlertModule,
         ButtonsModule, CarouselModule, CollapseModule,
         BsDropdownModule, 
         ModalModule,
         PaginationModule,
         PopoverModule,
         ProgressbarModule,
         RatingModule,
         SortableModule,
         TabsModule,
         TimepickerModule,
         TooltipModule,
         TypeaheadModule } from 'ngx-bootstrap';


@NgModule({
    declarations: [],
    imports: [ 
        CommonModule,
        AccordionModule,
        AlertModule,
        ButtonsModule,
        CarouselModule,
        CollapseModule,
        BsDropdownModule,
        ModalModule,
        PaginationModule,
        PopoverModule,
        ProgressbarModule,
        RatingModule,
        SortableModule,
        TabsModule,
        TimepickerModule,
        TooltipModule,
        TypeaheadModule.forRoot()
     ],
    exports: [
        AccordionModule,
        AlertModule,
        ButtonsModule,
        CarouselModule,
        CollapseModule,
        BsDropdownModule,
        ModalModule,
        PaginationModule,
        PopoverModule,
        ProgressbarModule,
        RatingModule,
        SortableModule,
        TabsModule,
        TimepickerModule,
        TooltipModule,
        TypeaheadModule
    ],
    providers: [],
})
export class NgXBootstrapModule {}
```

Do you think you can implement something like this directly in the library? 

Thanks!

**Comment by IlyaSurmay** [comment]
`Ng2BootstrapModule` was removed in one of the previous releases. If you import it and use only a few of components then you end up with increased bundle size, so it's been decided to keep modular approach instead of `all-in-one`. But you still can use a shared module (like your `NgXBootstrapModule`) if you need to import a lot of modules at once, this is a standard practice.
