### ISSUE TITLE
angular-cli + ng2-bootstrap build error

### ISSUE THREAD

**Issue by adam-tychoniewicz** [valor-software/ngx-bootstrap#347]
Project setup with https://github.com/angular/angular-cli
package.json contains: "ng2-bootstrap": "^1.0.7"

When tryiyng to import any directive im my app.ts file, and while running ng-build, error occured
![screenshot from 2016-03-30 10-51-23](https://cloud.githubusercontent.com/assets/7754206/14141996/22337da8-f683-11e5-8b87-7ef3d56dbfaa.png)

**Comment by adam-tychoniewicz** [comment]
If it could help, in broccoli-typescript.js you can try/catch on fs.linkSync (_outputFile method).
This fix build issue, but why we need that only in ng2-bootstrap library with angular-cli?

**Comment by valorkin** [comment]
not sure where the issue is
but please try with the latest version

**Comment by adam-tychoniewicz** [comment]
Now problem is gone :)
Thank you very much :)

**Comment by valorkin** [comment]
awesome! closing :)
