### ISSUE TITLE
Modal will hide after any click if application is compiled on production mode 

### ISSUE THREAD

**Issue by cae5ar** [valor-software/ngx-bootstrap#3489]
### Bug description:
Modal will hide after any click if I compile application on prod mode ; I added **onHidden** handler and had seen that `dismissReason` was "ESC". I checked it on different browsers, modal behaviour was the same on either Chrome and Safari.  Adding `keyboard:false` option to config solve this problem. 
Unfortunately, I can't set up the project at stackblitz.com to compile on production mode with aot compiler. I used the samples from [valor-software.com](https://valor-software.com/ngx-bootstrap/#/modals).

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-rc.0

Angular:  v5.2.1

Bootstrap: v3.3.7

### Build system: 
Angular CLI 1.6.2

**Comment by ctrl-brk** [comment]
Have you tried setting backdrop?

`<div bsModal [config]="{backdrop:'static'}">`

**Comment by valorkin** [comment]
@ctrl-brk heeey, glad to see you again :)

**Comment by cae5ar** [comment]
@ctrl-brk Yep, I did. Modal will close even if I click on modal body.

**Comment by ctrl-brk** [comment]
That doesn't happen for me. Could you create a plunker?

**Comment by IlyaSurmay** [comment]
If you can't create a plunkr, please provide a repo with reproduction

**Comment by smdev15** [comment]
Have you found a resolution for this issue? I have the exact same problem. Using similar approach from  valor-software.com, modals work fine when using System.js and JIT compilation. However, AOT and production build causes the modals to hide whenever clicked anywhere on modal body. The dismissReason returns "esc".

**Comment by smdev15** [comment]
Let me try to setup a repo where you can play with it. Doesn't seem to be a System.js issue - because it works exactly how it is supposed to when built and loaded with System.js; the problem is when I do AOT compilation with ngc.

**Comment by valorkin** [comment]
System.js prod build could cut some extra js for example :(
And in terms of aot extra js could be a part of html,

Thanks in advance for repo

**Comment by kmet-mykhailo** [comment]
I have the same problem.

Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 2.0.0-rc.0
Angular: v5.2.1
Bootstrap: v3.3.7
It happens only in ptod mode
./node_modules/.bin/ng build --prod --aot=false
