### ISSUE TITLE
Beta release to support angular2 - beta 12

### ISSUE THREAD

**Issue by sasidhar** [valor-software/ngx-bootstrap#349]
@valorkin We recently updated our main application's angular version from beta 9 to beta 12. But the currently available ng2-bootstrap NPM package still need angular2 - beta 9 as the peer dependency.

Because of different peer dependencies between different beta versions of angular, it is difficult to try out ng2-bootstrap's latest code.

If we have a release may be like 1.0.8.beta, with angular 2 beta 12 as the peer dependency (I already see this in the package.json) we can start using this and contribute to ng2-bootstrap while working on our application.

Please see if this can be possible.

**Comment by Growiel** [comment]
Make it beta.13 please.

**Comment by valorkin** [comment]
Beta 12 in testing - will published today
Beta 13 has only one change, if not broken will published too

**Comment by valorkin** [comment]
published

**Comment by sasidhar** [comment]
Thanks @valorkin

**Comment by Growiel** [comment]
Seems like it was published for beta.12 only. Any issues if I just change the package.json to beta.13 ?

**Comment by valorkin** [comment]
@Growiel update for beta.13 will be today
only breaking change in 12->13 is ng-content select 
was changed
