### ISSUE TITLE
fix(daterangepicker): "NullInjectorError: No provider for BsDaterangepickerConfig!"

### ISSUE THREAD

**Issue by zzJinux** [valor-software/ngx-bootstrap#3503]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Bug description or feature request:

`BsDaterangepickerConfig` is omitted from the providers of `BsDatepickerModule`, and from the `index.ts`.

### Plunker/StackBlitz that reproduces the issue:

https://plnkr.co/edit/ROgHqDflWO2gbOPxDqWi?p=preview

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0

Angular: latest

Bootstrap: 3.3.7

**Comment by valorkin** [comment]
Are you importing module with .forRoot() ?

PS it there https://unpkg.com/ngx-bootstrap@2.0.0/datepicker/datepicker.module.js

**Comment by valorkin** [comment]
It's indeed missing from index.ts thanks

**Comment by zzJinux** [comment]
Doc says `DatepickerModule` is old api. I'm using `BsDatepickerModule` now.
There is no `BsDaterangepickerConfig` in https://unpkg.com/ngx-bootstrap@2.0.0/datepicker/bs-datepicker.module.js

**Comment by valorkin** [comment]
Yayk, thanks a lot, I have injected it in a wrong place :)

**Comment by valorkin** [comment]
hey, fixed, https://travis-ci.org/valor-software/ngx-bootstrap/builds/331206114
this will publish 2.0.1 with @next tag
in 20-30 minutes

**Comment by valorkin** [comment]
Published, not yet marked as latest

**Comment by zzJinux** [comment]
I'm currently using workaround by providing `BsDaterangepickerConfig` manually, however, I'm glad that quickly fixed.

**Comment by valorkin** [comment]
Install v2.0.1 it has fix
