### ISSUE TITLE
Just updated app and am now getting Uncaught (in promise): Error: StaticInjectorError(AppModule)[BsDaterangepickerDirective -> BsDaterangepickerConfig]:

### ISSUE THREAD

**Issue by lonekawboy** [valor-software/ngx-bootstrap#3505]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

**Comment by valorkin** [comment]
Fixed in 2.0.1, its on npm
But not marked as latest

**Comment by lonekawboy** [comment]
Thanks much! Already have it updated and it is working great.

Paul Potter
paul@crantrak.com
608-343-3241

________________________________

**Comment by valorkin** [comment]
Awesome :)
