### ISSUE TITLE
Cannot read property of subscribe of undefined

### ISSUE THREAD

**Issue by jfaquinojr** [valor-software/ngx-bootstrap#3508]
This code below is working
```
<button type="button" class="btn btn-primary" (click)="staticModal.show()">Create template modal</button>

<div class="modal fade" bsModal #staticModal="bs-modal" [config]="{backdrop: 'static', keyboard: false}" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title pull-left">Static modal</h4>
                <button type="button" class="close pull-right" aria-label="Close" (click)="staticModal.hide()">
          <span aria-hidden="true">&times;</span>
        </button>
            </div>
            <div class="modal-body">
                <add-user></add-user>
            </div>
        </div>
    </div>
</div>
```

## Problem 
adding this event from UserComponent breaks it:
`<add-user (onCancel)="staticModal.hide()"></add-user>`

This code is not working:

```
<button type="button" class="btn btn-primary" (click)="staticModal.show()">Create template modal</button>


<div class="modal fade" bsModal #staticModal="bs-modal" [config]="{backdrop: 'static', keyboard: false}" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title pull-left">Static modal</h4>
                <button type="button" class="close pull-right" aria-label="Close" (click)="staticModal.hide()">
          <span aria-hidden="true">&times;</span>
        </button>
            </div>
            <div class="modal-body">
                <add-user (onCancel)="staticModal.hide()"></add-user>
            </div>
        </div>
    </div>
</div>
```

Finally, here is add-user
```
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
@Component({
    selector: 'add-user',
    templateUrl: './add-user.component.html',
    styleUrls: ['./add-user.component.css']
})
export class AddUserComponent implements OnInit {
    @Output() public onCancel?: () => void; // EventEmitter
    constructor() { }
    ngOnInit() { }
}
```

### Plunker/Stackblitz
I cant upload the code to stackblitz or even plunker using the ngx-bootstrap startup code. The code above breaks it. Here is my attempt: Warning, it crashes on chrome (aw snap), and edge

https://stackblitz.com/edit/ngx-bootstrap-ycb4b3?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:
2.0.1

Angular:
4.2.5

Bootstrap:
3.3.7

RxJS:
5.5.6

### Build system: Angular CLI, System.js, webpack, starter seed:
dotnet new angular

webpack.vendor.js
const treeShakableModules = [
    'angular/animations',
    'angular/common',
    'angular/compiler',
    'angular/core',
    'angular/forms',
    'angular/http',
    'angular/platform-browser',
    'angular/platform-browser-dynamic',
    'angular/router',
    'zone.js',
    'rxjs'
];
const nonTreeShakableModules = [
    'bootstrap',
    'bootstrap/dist/css/bootstrap.css',
    'es6-promise',
    'es6-shim',
    'event-source-polyfill',
    'jquery',
    './assets/css/winstrap.css',
    'ngx-bootstrap'
];

**Thanks in advance**

**Comment by jfaquinojr** [comment]
Error logs:
https://pastebin.com/2mCBfWv4

**Comment by IlyaSurmay** [comment]
For general questions please use StackOverflow.
In your example, it looks like you're trying to use an EventEmitter that isn't defined 
Try to replace this ` @Output() public onCancel?: () => void;` with ` @Output() public onCancel: EventEmitter<any> = new EventEmitter()`

**Comment by jfaquinojr** [comment]
Holy moly, its right under my nose. i can't believe the solution was that simple.

Thank you kind sir!
