### ISSUE TITLE
Can't find docs to use Modals in V1.6.6

### ISSUE THREAD

**Issue by MarkAdell** [valor-software/ngx-bootstrap#3509]
I think there are breaking changes for Modals

Index.ts in V1.6.6 (the version in my project)

```
export { ModalBackdropComponent, ModalBackdropOptions } from './modal-backdrop.component'; 
export { ModalOptions } from './modal-options.class'; 
export { ModalDirective } from './modal.component'; 
export { ModalModule } from './modal.module';
```

Index.ts in V2.0.0
```
export { BsModalRef } from './bs-modal-ref.service';
export { ModalBackdropOptions } from './modal-backdrop.options';
export { ModalContainerComponent } from './modal-container.component';
export { ModalBackdropComponent } from './modal-backdrop.component';
export { ModalOptions } from './modal-options.class';
export { ModalDirective } from './modal.directive';
export { ModalModule } from './modal.module';
export { BsModalService } from './bs-modal.service';
```
And for all the versions that the docs are covering (V1.8.1 to V2.0.0) `BsModalService` and `BsModalRef` are required.

**Comment by valorkin** [comment]
Somewhere there was added .forRoot() to all modules,
So I could introduces services without breaking changes.

ModalRef is for ModalService.

The only reason to use v1, if you are on angular v2.

Dropdowns had a breaking change, it was my mistake.
And .forRoot() was added to all modules,
Except this all should be fine
