### ISSUE TITLE
Possible TypeaheadContainerComponent typo

### ISSUE THREAD

**Issue by Oliver-Piorun** [valor-software/ngx-bootstrap#3518]
### Bug description or feature request:
Possible typo:
Function 'hightlight(match: TypeaheadMatch, query: any): string' should be named 'highlight' if I am not wrong.

### Version of ngx-bootstrap:
ngx-bootstrap: 2.0.1

Greetings

**Comment by IlyaSurmay** [comment]
Nice reason for a small PR :)
