### ISSUE TITLE
(request) Better import documentation

### ISSUE THREAD

**Issue by robvaneck** [valor-software/ngx-bootstrap#3519]
Hi,

I've found the import documentation a bit short. I'm used to only importing 1 module, which contains the whole thing. Like for instance

```
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
```

For people with largers apps (multiple Angular Modules) it's handy to import the ngx-bootstrap modules to your SharedModule and export it so all your sub modules can use ngx-bootstrap. And in every module, you import shared.module.

```
...

import { AlertModule } from 'ngx-bootstrap/alert';
import { TypeaheadModule } from 'ngx-bootstrap/typeahead';
import { ModalModule } from 'ngx-bootstrap/modal';
import { BsDropdownModule } from 'ngx-bootstrap/dropdown';
import { PopoverModule } from 'ngx-bootstrap/popover';
import { TooltipModule } from 'ngx-bootstrap/tooltip';
import { CollapseModule } from 'ngx-bootstrap/collapse';

...

@NgModule({
  imports: [
    CommonModule,
    ReactiveFormsModule,
    AlertModule.forRoot(),
    TypeaheadModule.forRoot(),
    ModalModule.forRoot(),
    BsDropdownModule.forRoot(),
    PopoverModule.forRoot(),
    TooltipModule.forRoot(),
    CollapseModule.forRoot(),
  ],
  declarations: [
  ],
  providers: [
  ],
  exports: [
...
    AlertModule,
    TypeaheadModule,
    ModalModule,
    BsDropdownModule,
    PopoverModule,
    TooltipModule,
    CollapseModule,
  ]
})
export class SharedModule { }
```

**Comment by IlyaSurmay** [comment]
Hi! Shared Modules are common and widely used practice so I'm not sure we need to say something about it in the documentation.

**Comment by robvaneck** [comment]
Ok, maybe not in the docs if you don't find it necessary, but I'm sure this github url will help someone. 

Shared modules aren't that clear for beginners I can imagine. Not many examples online with multiple modules and how to share dependencies. And since ngx-bootstrap is more than 1 line to import, it think its logical to use shared module (if you know how to use it).

**Comment by IlyaSurmay** [comment]
We used to have a shared module called `Ng2BootstrapModule` but we removed it in some of the previous releases to avoid the situation when a user has increased bundle size due to importing everything. Maybe we should add a little guide how to create a SharedModule with ngx-bootstrap's modules. Nice reason for a small PR btw ;)

**Comment by robvaneck** [comment]
Ok sweet! I love the separate imports btw. Keeping it clean.

**Comment by kuncevic** [comment]
@IlyaSurmay  I think from pips who being using `material2` for a while that is clear as `material2` has that bit documented. For other folks I think it should be clear as well - so it should be documented. And yes I agree that shared moudles are a common pracitces, but anyway.

~~@borriej any reason you doing~~
~~`import { BsDropdownModule } from 'ngx-bootstrap/dropdown';`~~
~~`import { AlertModule } from 'ngx-bootstrap/alert';`~~

~~as I find out that `{ BsDropdownModule, AlertModule, ...} from 'ngx-bootstrap';` works just fine, but wonder if it will affect the treeshaking in a bad way~~

UPDATE:
just checked the bundles with `webpack-bundle-analyzer` using `import { xxx } from 'ngx-bootstrap/xxx';` and `import { xxx } from 'ngx-bootstrap';`  - can see any difference in bundles size.  
 
So `import { xxx } from 'ngx-bootstrap/xxx';` make sense but `material2` team somehow achieved `import { xxx } from '@angular/material';` imports from '@angular/material' not bringing anything exept `xxx`.   
Wonder why `ngx-boostrap` can't do the same?

**Comment by valorkin** [comment]
@kuncevic material uses not documented bundler unfortunatelly, so we are using our own.
We have a PR with similar build structure, lets move conversation there
