### ISSUE TITLE
(bug) Slow performance with > 100 Typeahead's  

### ISSUE THREAD

**Issue by robvaneck** [valor-software/ngx-bootstrap#3520]
[x] Bug - Slow performance with lot's of Typeahead's

Hi,

I moved from ng-bootstrap to ngx-bootstrap, because ng-bootstrap was really slow with multiple typeahead's. On ng-bootstrap this was caused by host click listeners per typeahead to close the typeahead, so it stacked all these listeners on top of each other.

Now, I've tried ngx-bootstrap with a large Reactive Form Array using 2 typeahead's per row. So I have  50 rows, thus 100 typeahead's. The performance is better than ng-bootstrap, but it is getting a bit slow.  For example typing fast: 'klsdfjkldsjfssdlfds' will give visible lag of characters being slowly rendered in the input.

Is there a similar performance issue here? using host click events to close the typeaheads?

Can we fix this?

Is there a  (hacky) work around for me?

Thanks!

**Comment by robvaneck** [comment]
Addition: with 100 rows -> 200 typeahead's, it's really terrible. 

I am using timeout ms "300" ... pagination isn't really an option for me, since there are watchers that re-calculate row.

**Comment by IlyaSurmay** [comment]
100 typeaheads on a page seems like an edge case to me. We're using `@HostListener` for events like input, focus, blur etc. Btw, outside click listener is attached only when typeahead is opened, so it's definitely not the reason.

**Comment by robvaneck** [comment]
Im trying virtual-scroll to solve the performance now ;)

**Comment by robvaneck** [comment]
Hi @IlyaSurmay i've created a stackblitz because Im kind of stuck 
https://stackblitz.com/edit/angular-ngx-bootstrap-typeahead-laggy

The performance lags when having multiple typeahead components. 

What can we do to prevent this?

**Comment by valorkin** [comment]
I am working on a new way for attaching components, there are similar issues for all dynamic components. Closing this one to keep track of issues
