### ISSUE TITLE
Problem with latest ngx-bootstrap.umd.js (version 2.0.1) on SystemJS build

### ISSUE THREAD

**Issue by lroitman** [valor-software/ngx-bootstrap#3523]
### Bug description or feature request:
Latest version (2.0.1) has problems running with SystemJs. 
When we upgraded to the latest ngx-bootstrap our app stopped loading. Here is the stacktrace: 
```
zone.js:672 Unhandled Promise rejection: TypeError: Cannot read property '@angular/core' of undefined
	    at webpackUniversalModuleDefinition (http://localhost:3000/node_modules/ngx-bootstrap/bundles/ngx-bootstrap.umd.js!transpiled:14:51)
	    at execute (http://localhost:3000/node_modules/ngx-bootstrap/bundles/ngx-bootstrap.umd.js!transpiled:15:9)
	Error loading http://localhost:3000/app/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: TypeError: Cannot read property '@angular/core' of undefined
	    at webpackUniversalModuleDefinition (http://localhost:3000/node_modules/ngx-bootstrap/bundles/ngx-bootstrap.umd.js!transpiled:14:51)
	    at execute (http://localhost:3000/node_modules/ngx-bootstrap/bundles/ngx-bootstrap.umd.js!transpiled:15:9)
	Error loading http://localhost:3000/app/main.js null

```
We finally found a workaround for SystemJS to work by including ngx-bootstrap/index.js instead of umd:
```
    var map = {
        ...
        'ngx-bootstrap':                    'npm:ngx-bootstrap',
        ...
   }
    var packages = {
         ...
        'ngx-bootstrap':                    { main: './index.js', defaultExtension: 'js' },
         ...
   }
```
but we are wondering if this is the valid workaround

### Plunker/StackBlitz that reproduces the issue:
While we couldn't reproduce the issue in plunker, we noticed quite a slow-down in the performance of version 2.0.1 vs. 2.0.0-rc.0
Here is the plunker that uses ngx-bootstrap@2.0.0-rc.0, it works
https://plnkr.co/edit/COmbYWtfgY085xrFXNP5?p=preview
Here is the plunker that uses latest ngx-bootstrap, it takes the script about a minute to produce the result, with several prompts from the browser to end unresponsive scripts.
https://plnkr.co/edit/iIgbUXQvLQoKStZ0w2di?p=preview

I am not sure if this relates to the original problem, but apparently something strange is going on with the latest ngx-bootstrap.umd.js 

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.1

Angular: 5.2.1

Bootstrap: 3

### Build system: Angular CLI, System.js, webpack, starter seed:
SystemJS

**Comment by IlyaSurmay** [comment]
If you can't reproduce the issue via plunkr, create a github repo that reproduces it, that would help a lot.

**Comment by IlyaSurmay** [comment]
I see that you're using different system.js config in your plunkr. here's a plunkr https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview  that uses much simpler config and the app loading takes about a few seconds. Could it be related to your system.js config?

**Comment by chrisbmoore** [comment]
I didn't get the same error as you, but I had to reference "ngx-bootstrap/bundles/ngx-bootstrap.umd.**min**.js" to get it to work in SystemJS. "ngx-bootstrap.umd.js" and "index.js" didn't work for me.

**Comment by lroitman** [comment]
@IlyaSurmay @chrisbmoore That helped! Thank you very much for your help.

Should I close the issue or you guys would do it?
