### ISSUE TITLE
how to set datepicker show by default when open form

### ISSUE THREAD

**Issue by bvshivaji** [valor-software/ngx-bootstrap#3527]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

**Comment by IlyaSurmay** [comment]
There was a similar question on StackOveflow https://stackoverflow.com/questions/48096215/how-can-i-keep-the-bsdatepicker-from-the-ngx-bootstrap-always-open

**Comment by IlyaSurmay** [comment]
Closing for no updates.

**Comment by rrohitesh** [comment]
@bvshivaji  hey you got your answer i have to achieve same functionality can you please help me.
