### ISSUE TITLE
[progressbar] ExpressionChangedAfterItHasBeenCheckedError if value > max

### ISSUE THREAD

**Issue by seza443** [valor-software/ngx-bootstrap#3528]
### Bug description or feature request:
Using ProgressBar, if I set a value higher than the max value, Angular throw a ExpressionChangedAfterItHasBeenCheckedError exception.

### Plunker/StackBlitz that reproduces the issue:
https://plnkr.co/edit/n6Ntb3gje6nxYPHM6CHw?p=preview

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.1

Angular: 4.3.5

Bootstrap: 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:
Webpack: 3.6.0

**Comment by IlyaSurmay** [comment]
For some reason I can only reproduce this in your plunkr :(

**Comment by seza443** [comment]
Hu, weird because I just forked your "starter templates" plunkr and added very basic code into it :crying_cat_face:

**Comment by IlyaSurmay** [comment]
I know, but locally I don't see any errors (CLI/angular seed) :( 
Stackblitz also works ok with that (https://stackblitz.com/edit/ngx-bootstrap-6iadur?file=app/app.component.html)

**Comment by seza443** [comment]
The problem just come from the fact that the ProgressBar component change the value to 100%.
What is the reason behind this behavior ?
I guess it is to avoid showing a bar that is bigger than the maximum space (?)

However, I've just put a workaround by setting the [value] input to the max value if it is bigger :wink:

**Comment by IlyaSurmay** [comment]
The value of progressbar can't be bigger than its max value (which is pretty obvious IMHO), so if you wan't it to be bigger, then changing `max` dynamically seems like a workaround :)
