### ISSUE TITLE
Angular5 Alert Bug - "No provider for TemplateRef"

### ISSUE THREAD

**Issue by Kurara** [valor-software/ngx-bootstrap#3542]
_### Bug description or feature request:_
There is an error importing **AlertModule** when loadChildren is used. The same code with **BsDropdownModule** works. The error is: 

The error says:
ERROR Error: StaticInjectorError[TemplateRef]: 
  StaticInjectorError[TemplateRef]: 
    NullInjectorError: No provider for TemplateRef!

_### Plunker/StackBlitz that reproduces the issue:_
[stackblitz.com/edit/angular-s4mmq4](stackblitz.com/edit/angular-s4mmq4)

_### Versions of ngx-bootstrap, Angular, and Bootstrap:_
"ngx-bootstrap": "1.9.3",
"bootstrap": "4.0.0-beta.2",
"angular": "5.0.1",

**Comment by Kurara** [comment]
@IlyaSurmay  I have just seen you tagged it with "needs: reproduce" but I provided a stackblitz. Is it not enought?

**Comment by IlyaSurmay** [comment]
Stackblitz is broken, can you fix it? I get `Maximum call stack size exceeded `

**Comment by Kurara** [comment]
I let you the code here: https://embed.plnkr.co/Lk3lXWZszG6yRcmD0lw8/ but it's not working as I can't import ngx-bootstrap to config.js Maybe it's not posible or maybe I don't know how to do it. But at least you can copy the code and use in your enviroment.

**Comment by Kurara** [comment]
I found the problem: https://github.com/valor-software/ngx-bootstrap/blob/development/src/alert/alert.component.html should change the tag `<template>` for `<ng-template>` Here the doc changes:

angular 2: http://devdocs.io/angular~2/api/common/index/ngif-directive
angular 5: http://devdocs.io/angular/api/common/ngif

**Comment by IlyaSurmay** [comment]
Any version newer than `1.9.3` uses ng-template. So please update to the latest version, `2.0.2`

**Comment by Kurara** [comment]
Sorry, maybe I went to the code in github of the branch **master** https://github.com/valor-software/ngx-bootstrap/blob/master/src/alert/alert.component.ts, so I tought it was the code of version 2.0.2. I didn't now the branch I should see was develop :P

**Comment by BBenQi** [comment]
@Kurara thanks, i have soved my issue,by changing the tag <template> for <ng-template>

**Comment by ziaKhan1995** [comment]
> Stackblitz is broken, can you fix it? I get `Maximum call stack size exceeded `

remove function recursion
