### ISSUE TITLE
Timepicker: Placeholders are not editable

### ISSUE THREAD

**Issue by TomONeill** [valor-software/ngx-bootstrap#3544]
The Timepicker has placeholders in the inputs (HH, MM, SS) that are hardcoded in the template. HH, MM and SS are not valid in the language I'm developing for, so I need to be able to turn those off.

Could you look into the possibility of changing the placeholders manually or perhaps turn them off entirely?

Thank you in advance.

https://github.com/valor-software/ngx-bootstrap/blob/development/src/timepicker/timepicker.component.html

**Comment by urstrulykkr** [comment]
Hi @daniloff200 
I would like to work on this issue.

**Comment by daniloff200** [comment]
@urstrulykkr  looks like, we have a PR from @fhuschle  already.

**Comment by urstrulykkr** [comment]
@daniloff200 , Can you please assign me to any beginner level hacktoberfest issue?
Thanks in advance :)

**Comment by daniloff200** [comment]
@urstrulykkr you can try to pick https://github.com/valor-software/ngx-bootstrap/issues/5401 , I added a description, what has to be done, so, I think it's good to go! 
Feel free to ask any questions in this issue, if you have any
