### ISSUE TITLE
modal with independent URL and component ?

### ISSUE THREAD

**Issue by chaouiy** [valor-software/ngx-bootstrap#3557]
It would be great to be able to create modals that have separate URL in a standalone component that doesn't depend on the context of any parent

**Comment by IlyaSurmay** [comment]
Could you explain a bit more what do you want? Now I'm having difficulties with understanding this `modal with URL` concept

**Comment by chaouiy** [comment]
Imagine you need to redirect to the modal from another component, Is this possible if the modal doesn't have a URL. In ngx-bootstrap demo opening a modal doesn't change the URL which means that It hasn't a unique URL !

**Comment by ctrl-brk** [comment]
It's not clear what you asking for. In the first post you require separate URL but in the next one no URL.
To open a modal by URL just add a part to your component's url as a parameter and call yourmodalref.show() when this part is present.
