### ISSUE TITLE
dropdown hide function 

### ISSUE THREAD

**Issue by qwe852147** [valor-software/ngx-bootstrap#3568]
How to call hide function of dropdown ?
There only said dropdown has this function but not example to show it.

I use autoClose =true and preventDefault function and  stopPropagation function  to do closed outside.
This method let me can click item to call other function example customize click.

But dropdown  can not auto closed after list item click function .

I want to use hide function close it by myself to solve this problem.

**Comment by IlyaSurmay** [comment]
Here's an [example](http://plnkr.co/edit/3iYwa1wuYBaDWZJdH8qb?p=preview) of `hide()` function usage. We'll add this to docs later

**Comment by qwe852147** [comment]
Thanks, closed this issue
