### ISSUE TITLE
Date range picker issue

### ISSUE THREAD

**Issue by nileshpatil-dev** [valor-software/ngx-bootstrap#3576]
I am facing issue with date range picker. When I change year of to date calendar it automatically changes from calendar too and this giving wrong impact to the users.

**Comment by IlyaSurmay** [comment]
Could you provide a reproduction of this issue?
Plunkr starter template: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

**Comment by IlyaSurmay** [comment]
2+ months without updates, closing.
