### ISSUE TITLE
Dropdown component is not rendered to right place after upgrade ngx-bootstrap from 1.9.3 to 2.0.2

### ISSUE THREAD

**Issue by lazaro3487** [valor-software/ngx-bootstrap#3577]
Hello everyone. After upgrade ngx-bootstrap from 1.9.3 to 2.0.2, the dropdown component is not rendered to right place. To solve the problem I need to append this styles (style="right: 0; left: auto"), but that is defined in the core of ngx-bootstrap dropdown bot never executed.

Angular version: 4.2.2
ngx-bootstrap: 2.0.2
bootstrap: 3 (lastest version)
Angular CLI build system

Any help to solve this? 

Regards.

This is my dropdown:

<div dropdown class="btn-group" placement="bottom right">
                                    <button dropdownToggle type="button" class="btn btn-default dropdown-toggle">
                                        <i class="fa fa-list m-r-xs"></i>
                                        <span class="caret m-t-n-xxs"></span>
                                    </button>

                                    <ul *dropdownMenu class="dropdown-menu dropdown-menu-right" role="menu">
                                        <ng-container *ngFor="let rowActionButton of configuration.rowActionButtons">
                                            <ng-container *ngIf="rowActionButton.isDisabled && rowActionButton.isDisabled(row); else actionFieldBlock">
                                                <li class="disabled" role="menuitem">
                                                    <a>
                                                        <i *ngIf="rowActionButton.icon" class="fa {{rowActionButton.icon}}" aria-hidden="true"></i>
                                                        {{rowActionButton.tooltipI18nKey | i18n}}
                                                    </a>
                                                </li>
                                            </ng-container>

                                            <ng-template #actionFieldBlock>
                                                <li role="menuitem">
                                                    <a class="dropdown-item" (click)="rowActionButton.onClick(row)">
                                                        <i *ngIf="rowActionButton.icon" class="fa {{rowActionButton.icon}}" aria-hidden="true"></i>
                                                        {{rowActionButton.tooltipI18nKey | i18n}}
                                                    </a>
                                                </li>
                                            </ng-template>
                                        </ng-container>
                                    </ul>
                                </div>

**Comment by IlyaSurmay** [comment]
Could you provide a reproduction of this issue?
Plunkr starter template: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

**Comment by lazaro3487** [comment]
Thanks for the answer.

I tested this on plunker but works as expected however it does not work on my app.

Is there any other way to check that?

Regards.

**Comment by IlyaSurmay** [comment]
You can provide a link to a repository that reproduces the issue. Is it possible that your app has some specific styles for dropdowns?

**Comment by IlyaSurmay** [comment]
2+ months without updates, closing.
