### ISSUE TITLE
fix(typeahead): pressing enter submits form when choosing element

### ISSUE THREAD

**Issue by fkowal** [valor-software/ngx-bootstrap#359]
`<form><input [(ngModel)]="someField" typeahead... required></form>`

when i hit enter to select an active element in the typeahead dropdown
the (submit) event on the form before the ngModel is populated with the selected item's data

**Comment by manuelCorredor** [comment]
Can you pls release this patch? I'm using this on a form and I really need this fix

Thanks

**Comment by valorkin** [comment]
OK, I will do it later today

**Comment by manuelCorredor** [comment]
Thank you very much

**Comment by manuelCorredor** [comment]
Sorry,  me again @valorkin, I'm looking forward to hear from you :)

**Comment by valorkin** [comment]
almost there https://github.com/valor-software/ng2-bootstrap/pull/388
