### ISSUE TITLE
Change month position when maxDate is today

### ISSUE THREAD

**Issue by biosis21** [valor-software/ngx-bootstrap#3595]
Hi!
I would like to suggest an improvement.
When a user has maxDate is today, do not show unavailable date month.
![1](https://user-images.githubusercontent.com/6310176/35591287-15bc2b7e-0612-11e8-8405-00b07be1c712.png)

**Comment by treeskar** [comment]
I also recommend to display only one "calendar-view" if minDate's month number equals to maxDate's month number.
