### ISSUE TITLE
tooltip from a templateRef does not hide when the template content is cleared. 

### ISSUE THREAD

**Issue by panmanphil** [valor-software/ngx-bootstrap#3596]
### Bug description or feature request:
when you use a straight text value for a tooltip, the code will hide() when that value is not truthy:
```
 ngOnInit(): void {
    this._tooltip.listen({
      triggers: this.triggers,
      show: () => this.show()
    });
    this.tooltipChange.subscribe((value: any) => {
      if (!value) {
        this._tooltip.hide();
      }
    });
  }
```

This never happens when the value is a template ref defined like
```
<input .... [tooltip]="myTemplate' ..../>
<ng-template #myTemplate>
{{aTooltipMessage}}
</ng-template>
```
the "value" parameter will not be null so you end up with a tiny arrow pointing at the field with nothing in it. This is a simplified example of what I was trying to do but I think illustrates the point. There needs to be some other logic when the tooltip is based on a template reference. 

### Versions of ngx-bootstrap, Angular, and Bootstrap:
Angular 4.4.6
ngx-bootstrap:2.0.2
Bootstrap:3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular ng, webpack

**Comment by valorkin** [comment]
As you  can see tooltip can not guess context of template, but you can disable tooltip by using isDisabled option, when aTooltipMessage is empty

**Comment by jgraffin** [comment]
I had the same issue. Thank you, it worked!
