### ISSUE TITLE
datepicker is not closing with modal same time when modal close

### ISSUE THREAD

**Issue by bvshivaji** [valor-software/ngx-bootstrap#3597]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

**Comment by IlyaSurmay** [comment]
Could you explain a bit more? This issue doesn't make much sense now

**Comment by bvshivaji** [comment]
i have used ngx-bootstrap datepicker inside ngx-bootstrap modal 
but now issue is when close modal first modal closed later few seconds datepicker closed

**Comment by IlyaSurmay** [comment]
Please provide a reproduction of this issue. You can use our plunkr / stackblitz templates (links are in the first post)

**Comment by bvshivaji** [comment]
date picker should be show in inline mode and whithout click open button it
should open by default
 when open form 
how to do same in new version
https://valor-software.com/ngx-bootstrap/#/datepicker

**Comment by bvshivaji** [comment]
by default i want to show datepicker like
https://valor-software.com/ngx-bootstrap/#/datepicker

**Comment by IraErshova** [comment]
Close issue because of inactivity and lack of information
