### ISSUE TITLE
JS Size will increase if you include both BS3 and BS4 templates in the code

### ISSUE THREAD

**Issue by mohammedzamakhan** [valor-software/ngx-bootstrap#36]
Don't you think you should use better approach for separate BS3 and BS4 templates?

https://github.com/valor-software/ng2-bootstrap/blob/master/components/carousel/carousel.ts#L13-L32

**Comment by valorkin** [comment]
Unfortunately there no way for now to separate templates from code like in ng1 with `$templateCache`
But yes, I am aware of this issue and looking for solution
