### ISSUE TITLE
fix(alerts): after dismissing alert are not removing from DOM 

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3608]
### WTR
- Go to Alerts demo page
- Scroll down to any alert with dismissible option (Dismissing demo or Dismiss on timeout)
- Find alert in DOM
- Dismiss alert (or wait time, after what it dismissed)
- Look at DOM again
- Add new alert
- Repeat steps 3-6 several times
![alertnotremoved](https://user-images.githubusercontent.com/27342505/35634968-b31743d8-06b5-11e8-9919-c9993119fe3d.gif)
![multiplealertsatdom](https://user-images.githubusercontent.com/27342505/35635687-a60d95f0-06b7-11e8-8f96-6a959cc0d0c4.jpg)

### Expected result
All alerts after dismissing are removed from DOM

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: all supported

Angular: all supported

Bootstrap: all supported

**Comment by martibenj** [comment]
Is there some update about this issue ? Will it be released ?

**Comment by valorkin** [comment]
I suppose it's already published
