### ISSUE TITLE
Tag Input component

### ISSUE THREAD

**Issue by baderbuddy** [valor-software/ngx-bootstrap#362]
I wrote a component to do input for tags, similar to this jquery one http://xoxco.com/projects/code/tagsinput/example.html it relies on your typeahead component, it would just require some work to bubble up properties from the typeahead to be inputs to the component. After I'm finished would you be interested in a pull request to merge it into this project? Even though it's not strictly bootstrap it is a nice ng2 component that uses bootstrap.

**Comment by valorkin** [comment]
like this? https://github.com/valor-software/ng2-select

**Comment by baderbuddy** [comment]
Yeah pretty much, except the code I wrote made use of the ng2-bootstrap typeahead to be able to query a web service for results. It looked like that ng2-select only worked with a static list of components. Also I made use of bootstrap button styling to differentiate values from the autocomplete or manually typed ones.
