### ISSUE TITLE
Add [typeahead] directive selector prefix

### ISSUE THREAD

**Issue by anjmao** [valor-software/ngx-bootstrap#3623]
Hi,
I'm developing dropdown select called `ng-select` and there is one issue https://github.com/ng-select/ng-select/issues/224
It looks like there is `typeahead` [directive](https://github.com/valor-software/ngx-bootstrap/blob/development/src/typeahead/typeahead.directive.ts#L32) which use selector as `[typeahead]` and this collides with `ng-select` input called `typeahead`.

Is it possible to solve this problem without changing prefix of valor-software typeahead directive? In any way it is a good practice to add prefix to such directives.

**Comment by andjiev** [comment]
@IlyaSurmay Seems like this isn't fixed. I have the same problem.

**Comment by kunovskis** [comment]
I have the same problem. Error limited.map is not a function in console.

**Comment by valorkin** [comment]
@anjmao it will have a prefixed version in next major version (with angular 6)
and removed in next+1 major version (with angular 7)
so it will be easier to prefix input it `ng-select`

**Comment by markleusink** [comment]
Have the same issue. Did the PR already make it into a release?

**Comment by bogdan-melov** [comment]
I have a console error cuz of this. Please fix it

**Comment by williamverdolini** [comment]
Why this issue is closed?
The PR is not in master, but even if it will be merged, the PR will no fix the issue, cause "the [typeahead] selector still exists" as the author has written

Please reopen it

**Comment by g3344** [comment]
Did anyone find an answer to this?  Running into the same issue

**Comment by mtgleeson** [comment]
I'm hitting the same issue - any fix? 
I'm using ngx-bootstrap 6.2.0 and @ng-select/ng-select 6.1.0.
