### ISSUE TITLE
Unable to close tooltip by code

### ISSUE THREAD

**Issue by YugasVasyl** [valor-software/ngx-bootstrap#3625]
I have a very specific bug with tooltips in firefox, and I can easily fix it, but I need to know how can I close the tooltip by code. I almost found a needed part of code:
```
<div            [tooltip]="popTemplate"
                   triggers="mouseenter:mouseleave"
                   #pop="bs-tooltip">
```

```
@ViewChild('pop') pop: any;

public hide() {
  this.pop._tooltip.hide();
}
```
So with `hide()` method I can hide tooltip when I need it, the problem is that `this.pop` is a reference to the first element with a tooltip, but I have a few. How can I get access to any of elements with a tooltip? Or is there any other way to close tooltip?
Thanks.

**Comment by IlyaSurmay** [comment]
Please, don't open an issue here if you want to ask a general question. It's better to use  [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead.
To get a reference to all tooltips, use `@ViewChildren(TooltipDirective) tooltips: QueryList<TooltipDirective>;` Then you'll be able to close all tooltips using forEach.
Example - https://stackblitz.com/edit/angular-mdkngd?file=app/basic.html
