### ISSUE TITLE
fix(typeahead): Clicking an item does not raise the typeaheadOnSelect event

### ISSUE THREAD

**Issue by johan13** [valor-software/ngx-bootstrap#363]
Repo steps:
- Go to http://valor-software.com/ng2-bootstrap/
- Type "A" in the typeahead field labelled "Asynchronous results" (Static array works the same way.)
- Click e.g. "Alaska" in the suggestions.

Result: The suggestions list disappears, but the typeaheadOnSelect is not raised and the input field is empty.
Expected: That the typeaheadOnSelect event is raised just as it would be if I'd hit enter.

**Comment by johan13** [comment]
I got the same result on Mac Chrome, Mac Firefox and Windows IE11.

**Comment by rbaarsma** [comment]
+1

**Comment by koodikindral** [comment]
currently a blocker

**Comment by koodikindral** [comment]
Seems that #351 did break this, blur event seems to override select event callback for some reason.

**Comment by slintes** [comment]
ups, sorry for introducing this bug with my blur event commit. I noticed it today myself, seems I always selected by pressing enter before...

**Comment by fkowal** [comment]
Hi made a fix using a different approve. https://github.com/valor-software/ng2-bootstrap/pull/398 Which one makes more sense ?
