### ISSUE TITLE
Accordion group backupground

### ISSUE THREAD

**Issue by lonekawboy** [valor-software/ngx-bootstrap#3649]
I'm attempting to change the background color of open accordion group headers and not having any luck with following your documentation using panelClass. Using Angular 5 and Bootstrap 4.

Thanks in advance!

Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

**Comment by IlyaSurmay** [comment]
Could you provide a reproduction of this issue? Also, take a look at this https://valor-software.com/ngx-bootstrap/#/accordion#styling

**Comment by learnuser521** [comment]
I have a sample here: https://stackblitz.com/edit/ngx-bootstrap-3887x5
When the styles are applied on the app level css (style.css) it works but does not work when the styles are applied at the component level.

**Comment by IlyaSurmay** [comment]
When you use component level styles, they're only applied to the content of that component, so all nested components will ignore those styles. You need to use app level styles or `::ng-deep`

Example - https://stackblitz.com/edit/ngx-bootstrap-69afad?file=app/app.component.css
