### ISSUE TITLE
tooltips on pseudo after content

### ISSUE THREAD

**Issue by alireza-saberi** [valor-software/ngx-bootstrap#3665]
### feature request:
I have a tooltips on a question mark in my design.  Former developer decided to put ? mark into css after pseudo class. Now, I was to show the tooltips when user hover on ? mark.
How is that possible with the current configuration?

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:^1.8.0

Angular: 4

Bootstrap: 3.7

**Comment by IlyaSurmay** [comment]
Nope and I don't think this is going to be implemented because a directive can be only applied to an actual html tag and `:before` or `:after` are inaccessible from js.
