### ISSUE TITLE
docs(datepicker): decompose Basic demo

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#3669]
1.remove presetting dates for datepicker and daterangepicker (basic section)
2. add demo for presetting date by bsValue, [(ngModel)] (initial-date-state)
Closes #3340

**Comment by ghost** [comment]
Estimate : 4h

**Comment by ghost** [comment]
effort1: easy(hours)

**Comment by EvilAlexei** [comment]
Closed by #3673
