### ISSUE TITLE
fix(build): system.js bundles are missing source maps

### ISSUE THREAD

**Issue by sqwk** [valor-software/ngx-bootstrap#367]
For servers that do not have mod_deflate enabled, the source map for `bundles/ng2-bootstrap.min.js` cannot be loaded.

**Comment by matthewrk** [comment]
I've just installed on windows and don't have the ng2-bootstrap.min.js.map file. Did this fix include the file in the default build?

**Comment by justinmchase** [comment]
Can we get a new release with these map files included? Its causing errors on our site. Would be greatly appreciated, thanks!

**Comment by valorkin** [comment]
added
