### ISSUE TITLE
How to use bsdatepicker as an element just like datepicker

### ISSUE THREAD

**Issue by justforuse** [valor-software/ngx-bootstrap#3676]
bsdatepicer has some awesome features, but is there any way to use it as element not as a directive with input? I do not think it is a good way to define it as directive. because component could be more extendable

**Comment by juicyarts** [comment]
im also interested in this. Is there a straight implementation like the old `<datepicker></datepicker>` one?

**Comment by ctrl-brk** [comment]
You can always create your own component with `<input type="text" bsDatepicker>`. Directive is perfect when you need control on the input field.

**Comment by valorkin** [comment]
There are was a lot of issues with dynamic datepicker positioning if used as component.
But inline version will be landed soon
