### ISSUE TITLE
Issue in ng serve while running application

### ISSUE THREAD

**Issue by nithintel** [valor-software/ngx-bootstrap#3684]
webpack: Failed to compile.
ERROR in node_modules/ng-window/src/BootstrapWindowContainer.ts(335,30): error TS2558: Expected 2-3 type arguments, but got 1.
node_modules/ng-window/src/WindowConfig.ts(5,25): error TS2307: Cannot find module '@angular/common/src/facade/lang'.
node_modules/ng-window/src/WindowsInjetor.ts(12,25): error TS2307: Cannot find module '@angular/common/src/facade/lang'.

**Comment by IlyaSurmay** [comment]
ng-window isn't a part of ngx-bootstrap
