### ISSUE TITLE
feature (popver) template isOpen on #ref

### ISSUE THREAD

**Issue by robvaneck** [valor-software/ngx-bootstrap#3691]
Hi,

[x] Feature: I would like to reference a #popover and then use the property isOpen so I can render icons on a button

```
<span containerClass="popover-notification"
      [popover]="mileagePopoverContent"
      #popMileage="bs-popover"
      placement="top"
      class="has-cursor"
      [outsideClick]="true">Toggle popover

    <icon [name]="'chevron-up'" [class]="'icon-16'" *ngIf="#popMileage.isOpen"></icon>
    <icon [name]="'chevron-down'" [class]="'icon-16'" *ngIf="!#popMileage.isOpen"></icon>

</span>

```

**Comment by IlyaSurmay** [comment]
Isn't this possible with the current version? just remove `#` from ngIf expressions and it should work fine
Example - https://stackblitz.com/edit/angular-4azanu?file=app/triggers-manual.html

**Comment by IlyaSurmay** [comment]
Btw, there's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead
