### ISSUE TITLE
Old Inline DatePicker in Popover and Outsideclick functionality 

### ISSUE THREAD

**Issue by anil-kk** [valor-software/ngx-bootstrap#3704]
**Problem Description** 
Combination of Popover, Old DatePicker Inline, TimePicker and Outside click functionality is not working as expected. A little odd behavior.

When I used old Inline DatePicker in custom Popover, there is this odd functionality, custom popover template is closed when I select a date or try to change year or month. It looks like **outsideclick** is triggered even when the **click is inside the popover content** specially when I clicked(selected) date or try to change month or year.

**The reason for this odd behavior**, my guess, it is usage of ng-template in DOM that causes the odd behavior, here the parentNode is null for DOM generated by ng-template, so it will be hard to determine, if it is clicked outside or inside a specific container. Outside click functionality is provided by traversing through parent nodes of clicked target element and find a match to decide if clicked outside or inside. (or traversing through child nodes of custom element where outsideclick is configured and find a match to decide if clicked outside or inside)

If there is no proper control over date picker functionality, it is hard to use this component together with other components, for example, use case, if I want to use a custom popover, In the beginning, I want the users to select date (might also need to change year or month) from this popover and later select time, one after the other. But this can not be achieved with existing components behavior.

**Comment by IlyaSurmay** [comment]
Could you provide a reproduction of this issue?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by anil-kk** [comment]
@IlyaSurmay 

I reproduced the issue, please visit the below links. Try to select a date, month or year when **outsideclick** is active for **popover**, when this is disabled, components work as expected, but they behave different when outsideclick is active for popover.

[**Issue Preview**](https://ngx-bootstrap-datetime.stackblitz.io)
[**Issue Editor**](https://stackblitz.com/edit/ngx-bootstrap-datetime)

**Comment by IlyaSurmay** [comment]
Hi! I investigated this a bit - you're right about ng-template, but the second part of the reason is ngFor, that redraws all rows on date select. Locally I fixed this by applying `trackBy` to ngFor inside datepicker's template, but we don't support this datepicker anymore so I don't know if this fix is going to land in the following releases.

@valorkin what do you think?

**Comment by anil-kk** [comment]
@IlyaSurmay Thanks for the update. Hope to see changes in further releases as it is a popular repository

**Comment by anil-kk** [comment]
@IlyaSurmay @valorkin  can you please provide me any updates regarding the issue status. I can help you with contribution if required.

**Comment by valorkin** [comment]
Easy fix is to add stop propagation on click inside of template used for popover content
