### ISSUE TITLE
How to show only month in bsDatepicker popup instead of date? 

### ISSUE THREAD

**Issue by suraj-karale** [valor-software/ngx-bootstrap#3705]
How to show only month in bsDatepicker popup instead of date?

**Comment by IlyaSurmay** [comment]
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

Closed as a duplicate of #2627

**Comment by suraj-karale** [comment]
<input type="text" name="startDate" class="form-control" bsDatepicker [datepickerMode]="'year'" [minMode]="'month'" ngModel/>

#2627 this issue is not understandable. can you please help me in above code?

**Comment by MatiasPipo** [comment]
On View:
<input 
            bsDatepicker
            (onShown)="onOpenCalendar($event)">

On Component:

onOpenCalendar(e) {
    if (this.formatoMesAnio) {
      e.setViewMode('month');
    
      e.monthSelectHandler = (event: CalendarCellViewModel): void => {
        e.value =  event.date;
        return;
      };
    }
  }


It´s manually and work for me !!!
