### ISSUE TITLE
In mobile can´t define size of Daterangepicker an not show all

### ISSUE THREAD

**Issue by apicito** [valor-software/ngx-bootstrap#3706]
In a responsive web application the Daterangepicker is not shown complete in mobile devices of 5 ".
How can I change the size of the popup window?

**Comment by IlyaSurmay** [comment]
You can overwrite datepicker's styles. Example - https://stackblitz.com/edit/angular-7rxmuq?file=styles.css

**Comment by apicito** [comment]
Fine. Thanks IlyaSurmay.

`.bs-datepicker-container {

  padding: 0 !important;

}

.bs-datepicker-multiple {

  padding: 0px !important;

  margin: 0px !important;

  height: 240px !important;

}

.bs-datepicker-body {

  padding: 0px !important;

  margin: 0px !important;

}

.bs-datepicker-head {

  height: 30px !important;

  padding: 0px !important;

}`
