### ISSUE TITLE
AlertModule StaticInjectorError(AppModule)[NgIf -> TemplateRef]:

### ISSUE THREAD

**Issue by ArunAshokan89** [valor-software/ngx-bootstrap#3715]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

### Build system: Angular CLI, System.js, webpack, starter seed:

Upgraded Angular 4 to 5

Alert module has been imported in sharedmodule....
import { AlertModule } from "ngx-bootstrap";

if i remove alert element from html page it will fine.

<alert [type]="alertType">{{alertMessage}}
</alert>
	

![screenshot_2](https://user-images.githubusercontent.com/13496911/35932781-a5177d58-0c5e-11e8-82e9-234ff58dd050.jpg)

**Comment by IlyaSurmay** [comment]
Closed because you asked this question on StackOverflow as well -https://stackoverflow.com/questions/48679822/ngx-bootstrap-alertmodule-issue
