### ISSUE TITLE
Datepicker. Add placement "bottom-left"

### ISSUE THREAD

**Issue by ctrl-brk** [valor-software/ngx-bootstrap#3721]
Would be nice to have it aligned to the left and bottom sides of the input. Right now bottom is center aligned.

**Comment by IlyaSurmay** [comment]
This is possible in the current implementation.
`<input  placement="bottom left" bsDatepicker>`
Example - https://stackblitz.com/edit/angular-xoobax?file=app/custom-format.html (you may need to make the preview wider than 786px to avoid applying styles for mobile devices)

**Comment by winnemucca** [comment]
> This is possible in the current implementation.
> `<input placement="bottom left" bsDatepicker>`
> Example - https://stackblitz.com/edit/angular-xoobax?file=app/custom-format.html (you may need to make the preview wider than 786px to avoid applying styles for mobile devices)

@IlyaSurmay 

I need to be able to move the top and left positioning a little more than the default behavior that comes with `placement="bottom left" `.  I see the role and absolute positioning on https://github.com/valor-software/ngx-bootstrap/blob/development/src/datepicker/themes/bs/bs-datepicker-container.component.ts.   However, I am unable to locate how the `pixels ` are being set. Would you be able to point me in that direction?

**Comment by Victor716** [comment]
<input placement="bottom left" bsDatepicker> doesn't work in the latest version
