### ISSUE TITLE
feat(modal): Temporarily Hide Modal

### ISSUE THREAD

**Issue by juliusstoerrle** [valor-software/ngx-bootstrap#3724]
### feature request:

I would like to hide my modal temporarily by the parent component until some calculations are done and depending on he result close or re-show the modal.

Maybe this is possible already by combining some show/hide methods of the BsModalService? , but I haven't found anything in the docs?

Thanks for all your work on this amazing package! Let me know if you need anything :)

**Comment by IlyaSurmay** [comment]
This isn't supported in the current implementation. You can hide modal and then show it again with the new data, but this is going to be a new instance of modal.

**Comment by juliusstoerrle** [comment]
@IlyaSurmay thanks for your reply! If you don't think this feature fits in your roadmap / package, feel free to close it. I will just use a flag for my use case.
