### ISSUE TITLE
Alert is not populating once its closed

### ISSUE THREAD

**Issue by kmanikandanmca2008** [valor-software/ngx-bootstrap#3727]
Hi,
Alert component is not working as expected.
Problem:
-------------
Alert is displayed first time and next time if i try to make it open its failing.
we  are setting isSuccess is true  as per the guidance of (recreate alert after dismissal #3470) issue id.
Also randomly appearing and closing.

template:
--------------
```
<alert *ngIf="isSuccess" [(isOpen)]="isSuccess" type="success" dismissOnTimeout="1000" dismissible="true">
    <strong>
        <span [innerHtml]="alertMsgContent"></span>
    </strong>
</alert>
```

**Comment by IlyaSurmay** [comment]
Please provide a reproduction of this issue. Starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

Also take a look at this - https://stackoverflow.com/questions/48589984/show-hide-ngx-boostrap-alert/48620596#48620596

**Comment by IlyaSurmay** [comment]
2 months without updates, closing.
