### ISSUE TITLE
Present date is not highlighted clearly when another date is selected from old datepicker

### ISSUE THREAD

**Issue by anil-kk** [valor-software/ngx-bootstrap#3734]
@valorkin 

When relative issues are searched, I see that the  #3127 is closed. But I think this issue needs to be addressed further. (may be, issue #3127 might night be related to this issue if the current and present date context is different)

The present date is not highlighted properly when other date is selected, only text is muted like any other date from other previous or next month when **Bootstrap v4.0.0** is used.

I checked the [code/markup/logic](https://github.com/anil-kk/ngx-bootstrap/blob/c0318ea8d318bf9ee99c859d95886b7429c7f9e7/src/datepicker/daypicker.component.ts#L67).  `text-info` class is added based on bootstrap version  . I guess it will be better to highlight current date for all bootstrap versions.
The logic for highlighting the present date needs improvements.

[**Issue Preview**](https://ngx-bootstrap-datetime.stackblitz.io)
[**Issue Editor**](https://stackblitz.com/edit/ngx-bootstrap-datetime)

**Comment by gschauhan** [comment]
+1

**Comment by dave0688** [comment]
+1

**Comment by mstivali** [comment]
+1

**Comment by andkh** [comment]
+1

**Comment by ludmilanesvitiy** [comment]
For now you have 2 options to higlight any date in datepicker:
1) https://valor-software.com/ngx-bootstrap/#/datepicker#today-class
2) https://valor-software.com/ngx-bootstrap/#/datepicker#date-custom-classes
