### ISSUE TITLE
docs(modal): add styling for output for Events, Confirm Window and Modal events example 

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3736]
### Bug description:
- Go to modals demo page
- Choose Bootstrap 4 styles
- Scroll down to Events, Confirm Window or Modal events example
- Fire events, that should be displayed in output
- Look at output syling

![outpoutslooksliketext](https://user-images.githubusercontent.com/27342505/36026732-0d4c24da-0da1-11e8-99f7-3ac08976bd35.jpg)

###Expected result 
Class card card-block card-header should be added inside <pre></pre> tags for all outputs

**Comment by 5earle** [comment]
i would like to give this a try. can you tell me how to locate the files after cloning the repo?

**Comment by YevheniiaMazur** [comment]
Close issue due to https://github.com/valor-software/ngx-bootstrap/pull/3976
