### ISSUE TITLE
Popover content is outside view in mobile

### ISSUE THREAD

**Issue by anil-kk** [valor-software/ngx-bootstrap#3739]
Popover content is outside of view. Please check the image below.

I was using demo from  [ngx-bootstrap documentation.](https://valor-software.com/ngx-bootstrap/#/popover)

 I also had same kind of issue in my application.

![image](https://user-images.githubusercontent.com/1368407/36031614-9df1e8ee-0dab-11e8-99d1-2f89822f5087.png)

**Comment by ghost** [comment]
I am facing this issue as well, have u found a fix?

**Comment by anil-kk** [comment]
Not yet, unfortunately, I got busy with other things.
I guess it is possible to fix it at our end with our own CSS. But a proper fix from ngx-bootstarp will be much better.

**Comment by IlyaSurmay** [comment]
Hi! Now popovers don't take page boundaries into account, this is common for all dynamic components like popovers, tooltips, dropdowns, etc.

Closed as a duplicate of #2998

**Comment by anil-kk** [comment]
Thanks for time and update.

**Comment by eagor** [comment]
@IlyaSurmay what's the motivation for that?
if `container` is set to 'body', values for `left` shouldn't be negative, imho.
