### ISSUE TITLE
Daterangepicker: can select a two month date range only

### ISSUE THREAD

**Issue by sherlock1982** [valor-software/ngx-bootstrap#3745]
Daterangepicker.

1. Select January in left picker
2. Select December in right picker

Actual behavior:
Left picker will change to November.

Expected behavior:
Stay on January

The same with years.
Can be seen [here](https://valor-software.com/ngx-bootstrap/#/datepicker)

**Comment by IlyaSurmay** [comment]
Couldn't reproduce this in the latest version. If you select December after January, datepicker will reset the selection and set December as the first month.
![datepicker](https://user-images.githubusercontent.com/18414330/36201504-d38c38c0-1188-11e8-8628-9decf9bbeaa7.gif)

**Comment by sherlock1982** [comment]
Yes now I see. 
Thanks. I also checked other pickers. It seems they work in the same way,

**Comment by sherlock1982** [comment]
Also when I open datepicker again it shows me two months near start date. While it could be nice to see start to the left and end to the right. 

This is also confusing imho.
