### ISSUE TITLE
Datepicker - Should be able to select a date from early next month without changing months

### ISSUE THREAD

**Issue by Swellenator** [valor-software/ngx-bootstrap#3746]
### Bug description or feature request:
If today is 28th Feb and I can only select future dates, I want to choose 1st March. However I have to click on the move to next month button before I can do anything. Currently next month's dates are all disabled.

It would be better if I could click 1st March whilst in the month of February, and have it automatically switch to showing March. This is how most date pickers work. It would save a click.

### Plunker/StackBlitz that reproduces the issue:
You can see the issue on the official demo: https://valor-software.com/ngx-bootstrap/#/datepicker

**Comment by gastonelhordoy** [comment]
This will definitely improve usability requiring less clicks to achieve the desired effect.
