### ISSUE TITLE
Datepicker i18n (French) change messages errors

### ISSUE THREAD

**Issue by Paul75** [valor-software/ngx-bootstrap#3747]
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.2

Angular: 5.0.4

Bootstrap: 4.0.0

### Build system: Angular CLI,:

My problem esi it works for French language but messages is not translate ?

For exemple : 'Invalid date' not translate to 'Date invalide'.

Thanks

**Comment by IlyaSurmay** [comment]
Closed as a duplicate of #3513
