### ISSUE TITLE
Timepicker max value is ignored if it's set above 23:00.

### ISSUE THREAD

**Issue by avramz** [valor-software/ngx-bootstrap#3751]
As mentioned in the title, max value seems to be ignored if the max value time is set above 23:00.
Example is shown in the link below.

StackBlitz: https://stackblitz.com/edit/angular-2hlezi

ngx-bootstrap: 2.0.2

Angular: 5.0.0

Bootstrap: 4.0.0

Build system: Angular CLI

**Comment by RanadeepPolavarapu** [comment]
I'll take this.

**Comment by daniloff200** [comment]
Cool! Thanks @RanadeepPolavarapu

**Comment by sakshamtaneja21** [comment]
i would look at this
