### ISSUE TITLE
TABS fired select event

### ISSUE THREAD

**Issue by Sir-J** [valor-software/ngx-bootstrap#3755]
TABS fired select event if I allocated value in input. 

"ngx-bootstrap": "^2.0.2",

**Comment by IlyaSurmay** [comment]
Please provide a reproduction of this issue.
You can use one of the starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by runeabrahams1** [comment]
@IlyaSurmay  Reprod:
https://plnkr.co/edit/uL5wXt3W1nKsBYusR2Z4?p=preview

Just select the text in the input-field. This will trigger the (select) output of the tab, as can be seen by the console print

**Comment by Sir-J** [comment]
When going to be fix this bug?

**Comment by apiscevs** [comment]
Any update on this bug?

**Comment by JayFialkowski** [comment]
According to [this issue](https://github.com/angular/angular/issues/23603) on Angular's repo, this is expected behavior of angular. `(event)` listeners will listen for `@Output()` events and DOM events. Components should avoid using DOM event names. `(select)` should probably be renamed to something like `(tabSelect)`

**Comment by clabough** [comment]
I also believe that if they change the event name to something else, that this would fix this issue.  Until then, put this in the event(s) that the (select) triggers.

> (select)="doThisOnSelect($event)

> doThisOnSelect(ev?: any)
> {
> if (!(ev instanceof TabDirective)) return;
> ...
> }

**Comment by seanforyou23** [comment]
Had same issue in version `^3.0.0`, @clabough recommendation fixed it for me.

**Comment by globallpoints** [comment]
Same issue here! Isn't there any different event for that?

**Comment by grubeninspekteur** [comment]
FYI, if someone else stumbles upon it: Together with [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1386418) (nsLayoutUtils::GetNearestScrollableFrame) the browser tab may crash if child elements of the tab are removed in the (select) callback.

**Comment by sgentile** [comment]
I'm also having this issue - please provide a fix, even if just a rename!!!

**Comment by sgentile** [comment]
thank you @clabough - your fix worked for me as well

**Comment by johnfrades** [comment]
Awesome, @clabough  solution worked. Thanks!

**Comment by Y4SHVINE** [comment]
@clabough solution worked for me as well Thank you !!!! 👍 👍
