### ISSUE TITLE
fix(datepicker): for ng2 beta

### ISSUE THREAD

**Issue by heziqiang** [valor-software/ngx-bootstrap#38]
I found DatePicker in the Directives menu, but nothing in detail.
Do you have any plan to add it,  or go further, add the DateTimePicker?

**Comment by valorkin** [comment]
It is there but need to be fixed

**Comment by amanwebdev** [comment]
Anyone working on this issue? I want to take it up and also what fixes the DatePicker component needs?

**Comment by valorkin** [comment]
@amansharma0091 at least make it working :)
no one is currently working on it
I would say mental model is wrong
but as first step I will appreciate if it at least will throw any errors :)

**Comment by amanwebdev** [comment]
I've updated the code to beta 1 and it's working. Will make a pull request soon.
Mental model is wrong? In what ways? What should be the correct model?

**Comment by valorkin** [comment]
Awesome waiting for it! :)
