### ISSUE TITLE
Unable to set init date for datepicker

### ISSUE THREAD

**Issue by papayaglobal** [valor-software/ngx-bootstrap#380]
Hi,

The initial date for datepicker is always today, tried 2 options:
1. setting the initial date with ngModel `<datepicker [(ngModel)]="dt"></datepicker>`
2. using initDate `<datepicker initDate="dt"></datepicker>`

When using both ``<datepicker  [(ngModel)]="dt" initDate="dt2"></datepicker>` the following error was thrown:

```
EXCEPTION: TypeError: this.activeDate.getFullYear is not a function in [activeDate in DatePicker@1:22]
```

**Comment by edinfazlic** [comment]
I just tried to reproduce your issue but I was unsuccessful. What I did is, I used the [demo](http://valor-software.com/ng2-bootstrap/) (Datepicker) provided, and added:
`public initDt:Date = new Date(this.dt.getFullYear(), this.dt.getMonth(), this.dt.getDate() + 1);`
to the datepicker-demo.ts@17, and changed datepicker-demo.html@18 to:
`<datepicker [(ngModel)]="dt" [initDate]="initDt" [minDate]="minDate" [showWeeks]="true"></datepicker>`

Works fine. Could you please try to do it like this and get back with the result ?
Thanks.

**Comment by papayaglobal** [comment]
Thanks @edinfazlic.
Was just a syntax issue: forgot the brackets around initDate
