### ISSUE TITLE
Typeahead not working with async calls

### ISSUE THREAD

**Issue by Steven-Garcia** [valor-software/ngx-bootstrap#3802]
### Bug description or feature request:

  I have an implementation of typeahead that follows the guidelines, however, fails to pick the value from an async call, I've tested with local variables and REST calls to no positive results

### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-zmrhv7?file=app%2Fapp.component.html

In the Stackblitz option it makes a REST call which fails to bring in a list of results, however brings a response with a property name, which fails to be displayed in the dropdown but is displayed in the pre tag with the json pipe

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.2

Angular: 5.1.0

Bootstrap: 4

### Build system: Angular CLI, System.js, webpack, starter seed:

Webpack

**Comment by Steven-Garcia** [comment]
Any feedback on this?

**Comment by Oliver-Piorun** [comment]
@Steven-Garcia 

Your stackblitz is working for me.

Greetings

**Comment by Steven-Garcia** [comment]
Hi @Oliver-Piorun  thank you for your comment

The stackblitz isn't displaying the expected behaviour, please note that locations is defined as an array of 4 elements, but when typing a value in the typeahead I expect it to display only one because it should call the `searchSites()` async method, which awaits `searchAllSitesFromGeoNamesAPI()`.  This last method basically manipulates the array in an attempt to fake a REST call which would dinamically manipulate an array.  And it fails to do so, displaying the array as it was defined when loading the component instead of displaying one single element, which is what it's expected to do

**EDIT:** I had made some changes following some guidance from a question in SO that I'd forgotten about, however unsuccessful. 

I've put the app back to its original state, where it displays the array in the pre tag after starting to type, but fails to load the results in the typeahead dropdown (Please note that the REST call will fail because of mixed content, but that doesn't affect the manipulation of the array, which in both result and error cases, gets filled with the same values)

**Comment by bunnyvishal6** [comment]
Why async data into [typeahead] is not working. Is it intended to work with observables? I'm using reactive forms.
```
        const newSub = new Subject();
        field.suggestions = newSub.asObservable();
        field.suggestions.subscribe(v => console.log(v));
        formcontrol.valueChanges.debounceTime(1000).distinctUntilChanged().subscribe(text => {
            this.http.post(field.suggestionsUrl, { text: text }).subscribe(
                response => {
                    console.log(response);
                    if (response.keywords) {
                        newSub.next(response.keywords.map(k => k.name));
                    }
                }
            );
        });
```

And here is the html
```

<input type="text" 
[attr.placeholder]="field.displayName" [formControlName]="field.fieldName"
 minlength="{{field.minLength}}" maxlength="{{field.maxLength}}"
 pattern="{{field.pattern}}" class="form-control text-primary"
 [typeahead]="field.suggestions" [typeaheadScrollable]="true" [typeaheadOptionsInScrollableView]="10" />
```

**Comment by amiram** [comment]
I made it working. Look on this example: https://stackblitz.com/edit/ngx-bootstrap-1nrqhh
I have to use map instead of switchMap, and set the typeaheadasync to true. Actually this was supposed to work with switchMap. Maybe the typeahead can't handle it.

**Comment by Axinet** [comment]
Looks like the problem is [in line 158](https://github.com/valor-software/ngx-bootstrap/blob/development/src/typeahead/typeahead.directive.ts#L158) where even if typeahead is an Observable (this.typeahead.constructor.name returns Observable) the condition in the if returns false so typeaheadasync **is not set to true**.
After forcing [typeaheadasync]="true" in template typeahead started working. Probably documentation should mention setting typeaheadasync or automatic check must be improved.

**Comment by zt1983811** [comment]
@amiram Your example no longer worked. the dropdown does not show when I am typing, it is only show afterI delete all the word I typed. Do you have a fix for update?
