### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when using variables inside ng-template with ModalModule

### ISSUE THREAD

**Issue by BarrMan** [valor-software/ngx-bootstrap#3809]
### Bug description or feature request:
1. Calling `BsModalService.show` inside `ngOnInit` on an `ng-template` located in the view. - works
2. Adding a variable on the scope of the component and inside the `ng-template`. - works
3. Wrapping the whole component tag with `*ngIf` causes `ExpressionChangedAfterItHasBeenCheckedError` exception to throw.

I've found a workaround:
`Calling window.setTimeout(() => {
this._bsModalService.show(this.template);
});`

### Plunker/StackBlitz that reproduces the issue:
Plunkr: https://plnkr.co/edit/ppGeFBYPhHVXFZML16u1?p=preview

*This sample was produced using the default plunkr starter project.

**Comment by IlyaSurmay** [comment]
Hi! That's an old one - https://github.com/angular/angular/issues/15634
Angular throws this error if you're creating a view during a change detection hook.
`setTimeout` and `Promise.resolve(null).then(() => [...})` are workarounds for this.
