### ISSUE TITLE
research(tooltips): responsiveness

### ISSUE THREAD

**Issue by 8lane** [valor-software/ngx-bootstrap#381]
It would be great if the tooltip placement could be adjusted depending on the space available. My tooltips are placed on the left but on mobile they hang off the screen. See attachment.
<img width="238" alt="screen shot 2016-04-06 at 16 14 52" src="https://cloud.githubusercontent.com/assets/456966/14321915/0dc9b220-fc13-11e5-8759-1d892de4c64d.png">

**Comment by valorkin** [comment]
thing is tooltips is using bootstrap classes,
so most probably no
but I will check

**Comment by DaSchTour** [comment]
As I know placement of bootstrap tooltips is calculated in JS. It doesn't depend on CSS.

**Comment by valorkin** [comment]
position service, yes
it takes in account host, target and tooltip elements
but not context

**Comment by valorkin** [comment]
@tctc91 can you raise an issue in bootstrap repo?

**Comment by IlyaSurmay** [comment]
Closing in favor of #2796
