### ISSUE TITLE
Tabs do not render in IE9

### ISSUE THREAD

**Issue by lucasa** [valor-software/ngx-bootstrap#3814]
### Bug description or feature request:

The /Tabs component is working ok at recent browsers versions, but it do not render when using the Internet Explorer 9.

Are there any pollyfills to support "ngx-bootstrap/tabs" on IE9?

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.9.3

Angular: 4.4.4

Bootstrap: 3.3.7

**Comment by valorkin** [comment]
I am not even sure angular is working in IE9.
But if it is - add polyfils recommended to angular
