### ISSUE TITLE
 docs(modal): add demo for modal window with one tooltip and one popover in the body of the modal

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#3817]
Need to add demo for modal window with one tooltip  and one popover in the body of the modal  ( as an example) .

related to #3258

**Comment by ghost** [comment]
effort1: easy(hours)

**Comment by YevheniiaMazur** [comment]
@svetoldo4444ka , please, edit description to this issue, not everything is clear:
1) It is not closing aggregation issue, it is related to it
2) Please, provide more information about demo: what part of modal (body, header, etc, if it'll contain multiple elements (as written) - how many)
