### ISSUE TITLE
Collapse nested inside tabs

### ISSUE THREAD

**Issue by rob-myers** [valor-software/ngx-bootstrap#383]
For the following, it seems that "Tab2 Content" is not displayed when Tab2 is clicked on.

``` html
<tabset>
    <tab heading="Tab1">
        <div [collapse]="false">
            Tab1 Content
        </div>
    </tab>
    <tab heading="Tab2">
        <div [collapse]="false">
            Tab2 Content
        </div>
    </tab>
</tabset>
```

Likewise if Tab2 is initially active, then "Tab1 Content" is not displayed.

**Comment by valorkin** [comment]
@rob-myers so what is the question?
please let us continue chat in slack https://www.hamsterpad.com/chat/ng2
