### ISSUE TITLE
refactor(dropdown): use rxjs pipeable operators pattern

### ISSUE THREAD

**Issue by leo6104** [valor-software/ngx-bootstrap#3841]
https://github.com/valor-software/ngx-bootstrap/blob/7346a5a0027d86ccbd144a23fa6d54e548d33fea/src/dropdown/bs-dropdown.directive.ts#L179

After rxjs 5.5.2, rxjs recommend to use rxjs/operators/filter not Observable.filter. 
Please read https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md 

this subscription should be implemented like this.
```
import { filter } from 'rxjs/operators/filter';

...

    // hide dropdown if set disabled while opened
    this._subscriptions.push(
      this._state.isDisabledChange
        .pipe(filter((value: boolean) => value))
        .subscribe((value: boolean) => this.hide())
    );
```

**Comment by leo6104** [comment]
Is there any plan to upgrade peerDependency of rxjs version to 5.5.x?
Current support version is up to 5.4.3. 
https://github.com/valor-software/ngx-bootstrap/blob/development/package.json#L76

**Comment by rolaveric** [comment]
Heads up that this issue is going to be a blocker for Angular 6 (Now in rc.0) as it uses RxJS v6 which no longer supports `rxjs/add/*` imports.

**Comment by valorkin** [comment]
Already landed in ngv6 branch
