### ISSUE TITLE
docs(dropdown): issue in Nested dropdowns demo. Nested dropdowns appear one before one

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#3851]
Dropdown demo (Nested dropdowns section):
### Bug description:
Nested dropdowns appear one before one

### Steps to reproduce:
  - go to Nested dropdowns section
  - open dropdown in this section
   - when we hover on the item in dropdown, which has nested dropdown and then hover on another item, which also has nested dropdown - open both nested dropdown

### Actual result: 
![joxi_screenshot_1519143943378](https://user-images.githubusercontent.com/21618857/36435891-8548a9f4-166b-11e8-8233-6212de36b144.png)

### Expected result:
Only one dropdown should be opened

### Versions of ngx-bootstrap, Angular, and Bootstrap:
all version

**Comment by ghost** [comment]
effort2: medium(days)

**Comment by crh225** [comment]
Duplicate of #3703

**Comment by Giroxes** [comment]
triggers="mouseover mouseleave"
