### ISSUE TITLE
Progress bar striped state cannot be toggled

### ISSUE THREAD

**Issue by mheppner** [valor-software/ngx-bootstrap#3864]
### Bug description or feature request:

The striped state for progress bars can only be set when they are initialized. Toggling the state on or off through a model has no effect. 

### Plunker/StackBlitz that reproduces the issue:

Plunkr: https://plnkr.co/edit/Zm32hV72yUvMEFItD0M9?p=preview

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.2

Angular: 5.2.5

Bootstrap: 4.0.0

### Build system: Angular CLI, System.js, webpack, starter seed:

angular-cli 1.7.0

**Comment by eh1160** [comment]
This is also true for the animate input.
