### ISSUE TITLE
Timepicker: Setting [showSpinners] has no effect

### ISSUE THREAD

**Issue by soernt** [valor-software/ngx-bootstrap#3868]
### Bug description or feature request:
Bug:
Setting the Timepicker [showSpinner]="false" has no effect - The spinner arrows are allways visible.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.2

Angular: 5.2.4

Bootstrap:4.00

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI,

**Comment by IlyaSurmay** [comment]
Please provide a reproduction, otherwise this issue will be closed
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by soernt** [comment]
Close it. Works as documented.

**Comment by lmichailian** [comment]
@soernt how you resolve this ?

**Comment by s00pa** [comment]
setting to false adds a "hidden" class but doesn't have CSS for the class to set display: none
Can workaround by adding a base CSS of: .hidden {display: none;}
