### ISSUE TITLE
investigate(tooltips): ChangeDetectionStrategy breaks fixture.detectChanges()

### ISSUE THREAD

**Issue by 8lane** [valor-software/ngx-bootstrap#387]
I've included the tooltips directive within my component but it's breaking my tests due to the change detection strategy being set to onPush. 

Is there a reason why this directive forces us to change the changeDetection strategy?

**Comment by valorkin** [comment]
`this.cdr.detectChanges();` maybe using `this.cdr.markForCheck();` will help
but should be investigated

**Comment by valorkin** [comment]
removed a while ago
