### ISSUE TITLE
Datepicker: inline and miltidate

### ISSUE THREAD

**Issue by alexandrali** [valor-software/ngx-bootstrap#3892]
Are there any possibilities to create an inline multidate datepicker? Maybe you are planning to implement it in the next version?

Something like this:
![image](https://user-images.githubusercontent.com/14372066/36776168-e1783d2e-1c75-11e8-9fb3-a0bc832b2d15.png)

**Comment by ludmilanesvitiy** [comment]
Inline datepicker is already implemented: https://valor-software.com/ngx-bootstrap/#/datepicker#inline-datepicker
Custom dates class is already implemented also: https://valor-software.com/ngx-bootstrap/#/datepicker#date-custom-classes
