### ISSUE TITLE
DateRangePicker is not formatting display date based on dateInputFormat

### ISSUE THREAD

**Issue by aaabidunique** [valor-software/ngx-bootstrap#3895]
DateRangePicker is not formatting display date based on dateInputFormat provided in bsConfig whereas it is working for DatePicker.
I have created the plunkr url for the same 

Plunkr: https://plnkr.co/edit/HGJHKXRZZAiPdoXoZfp9?p=preview

Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 2.0.2
Angular: 5.2.6
Bootstrap: 3.3.7

**Comment by learnuser521** [comment]
Use rangeInputFormat 

https://github.com/valor-software/ngx-bootstrap/blob/7c53bf9121d4801af1403e2978cd3533612c31e5/src/datepicker/bs-datepicker.config.ts#L40

**Comment by aaabidunique** [comment]
Thanks for the info.
Btw, it's better to mention this config on the official website https://valor-software.com/ngx-bootstrap/#/datepicker
