### ISSUE TITLE
Dates from ngx-bootstrap/datepicker with reactive forms are not propagated from the FormControl to the source object.

### ISSUE THREAD

**Issue by BBaysinger** [valor-software/ngx-bootstrap#3898]
### Bug description or feature request:

Dates from ngx-bootstrap/datepicker with reactive forms are not propagated from the FormControl to the source object. 

### Plunker/StackBlitz that reproduces the issue:

https://plnkr.co/edit/kYgkJMH78QWn9Ya8WEyK?p=preview

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.2

Angular: 5.2.6

Bootstrap: 4.0.0

### Build system: Angular CLI, System.js, webpack, starter seed:

Angular CLI### Bug description or feature request:

Dates from ngx-bootstrap/datepicker are not propagated from the FormControl to the source object.

### Plunker/StackBlitz that reproduces the issue:

https://plnkr.co/edit/kYgkJMH78QWn9Ya8WEyK?p=preview

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.2

Angular: 5.2.6

Bootstrap: 4.0.0

### Build system: Angular CLI, System.js, webpack, starter seed:

Angular CLI

**Comment by ctrl-brk** [comment]
I'm not sure it should. How does the form know about your object? You need to get values from the form and assign it yourself.

**Comment by BBaysinger** [comment]
Yeah... I realized that. Forgot I had that hooked up in my project behind the scenes. Actually the problem was my object traversion I used to copy the data over was tripping on those fields being set to a Date object. All I needed to do was catch those, and do `JSON.parse(JSON.stringify(date));` on them. You can close this. Thanks for you time.
