### ISSUE TITLE
parse error when importing Timepicker (ng2+webpack+ts)

### ISSUE THREAD

**Issue by lorenjerickson** [valor-software/ngx-bootstrap#39]
Hi,
This seems pretty basic, but I have created a simple component that references the Timepicker directive from ng2-bootstrap.  

```
...
import {Timepicker} from 'ng2-bootstrap/ng2-bootstrap';

@Component({
  selector: 'project-datetime', 
  directives: [CORE_DIRECTIVES, FORM_DIRECTIVES, ROUTER_DIRECTIVES, Timepicker],
  styles: [ . . . ],
  template: . . . 
})
export class ProjectDateTime { 
  tpconfig: any;
  constructor() {
    this.tpconfig = {
      hstep: 1, mstep: 1, ismeridian: false
    };
  }
}
. . .
```

And the relevant fragment from the template for the component:

```
. . . 
    <div class="form-group">
      <label for="" class="control-label col-sm-3">Time</label>
      <div class="col-sm-6">
        <timepicker [(ng-model)]="datetime.time" [hour-step]="tpconfig.hstep" [minute-step]="tpconfig.mstep" [show-meridian]="tpconfig.ismeridian"></timepicker>
      </div>
    </div>
. . .
```

When my component attempts to import Timepicker from ng2-bootstrap, I get a module parse error.  I installed ng2-bootstrap as directed:  npm install --save ng2-bootstrap.  My project is based on the angular2+webpack+typescript starter.  I am running under angular2 alpha46.  Typescript version is 1.6.2.  I assume the same error would be given trying to load any other directive from ng2-bootstrap.  Any idea why this is failing?

ERROR in ./~/ng2-bootstrap/ng2-bootstrap.ts
Module parse failed: /home/loren/Source/c4/c4-project-config/node_modules/ng2-bootstrap/ng2-bootstrap.ts Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| export \* from  './components/accordion/accordion';
| export \* from  './components/alert/alert';
| export \* from  './components/buttons/button-radio';
 @ ./src/app/components/project/datetime/datetime.ts 15:22-60

**Comment by valorkin** [comment]
Remove node_modules/ng2-bootstrap from ts-loader igore

**Comment by mshahin364** [comment]
@valorkin How can i solve this problem? Could you help me?

ERROR in d:\RnD.2016\Angular2\productive-in-angular2-fast-book\Example_Project\n
ode_modules\ng2-bootstrap\components\timepicker\timepicker.ts
(112,5): error TS7027: Unreachable code detected.

ERROR in d:\RnD.2016\Angular2\productive-in-angular2-fast-book\Example_Project\n
ode_modules\angular2\src\facade\promise.d.ts
(1,10): error TS2661: Cannot re-export name that is not defined in the module.

ERROR in ./~/ng2-bootstrap/ng2-bootstrap.ts
Module build failed: Error: Could not find the following rules specified in the
configuration:
sort-object-literal-keys
    at Object.loadRules (d:\RnD.2016\Angular2\productive-in-angular2-fast-book\E
xample_Project\node_modules\tslint\lib\ruleLoader.js:29:15)
    at Linter.lint (d:\RnD.2016\Angular2\productive-in-angular2-fast-book\Exampl
e_Project\node_modules\tslint\lib\tslint.js:24:44)
    at Object.lint (d:\RnD.2016\Angular2\productive-in-angular2-fast-book\Exampl
e_Project\node_modules\tslint-loader\index.js:63:23)
    at Object.module.exports (d:\RnD.2016\Angular2\productive-in-angular2-fast-b
ook\Example_Project\node_modules\tslint-loader\index.js:151:8)
 @ ./src/app/components/app.ts 13:22-60
