### ISSUE TITLE
People keep referring to ng2-bootstrap

### ISSUE THREAD

**Issue by jamalsoueidan** [valor-software/ngx-bootstrap#391]
Hello,

I choose to use bootstrap in my application, and I need to use the **list-group**, but It's not yet implemented in ng2-bootstrap.

Some people say if we use bootstrap directly it will break the virtual dom, but I don't understand how this would happened.
http://stackoverflow.com/questions/35529540/angular-2-component-inside-bootstrap-popover

Anyway, the problem with angular2 and bootstrap is that directive element tag breaks the css.

```
<ul class="list-group">
        <items *ngFor="#city of cities" >(render items)</items>
</ul>
```

Something like the above wouldn't work, since the items tag will render with the rest of the html, and things would not look good in the browser.

How can I solve this to create simple list-group in angular2?

Thank you

**Comment by valorkin** [comment]
@jamalsoueidan can you give a link to bootstrap's list-group source code?
