### ISSUE TITLE
Modal takes a long time to open (over a minute) in internet explorer 11

### ISSUE THREAD

**Issue by fortesl** [valor-software/ngx-bootstrap#3915]
Angular: 5.0.2
Bootstrap: 3.0.0
ngx-bootstrap: 2.0.2

Modal works fine in Chrome but hangs in internet explorer 11.

This is the call to modalService from component.ts:
        _this.modalRef = this.modalService.show(
            template,
            Object.assign({}, { backdrop: true }, { class: 'modal-dialog-custom-profile' })
        );_

With html:
<button type="button" class=" fa fa-th-large pickerIcon  no-padding-bottom" value="Open Selector" (click)="openModal(template)"></button>
<ng-template #template>
</ng-template>

Thank you!

**Comment by BenevidesLecontes** [comment]
I'm having this issue as well.
Angular 5.2.7
ngx-bootstrap 2.0.2
bootstrap 3.3.7

**Comment by fortesl** [comment]
Solved the issue by reducing the number of DOM elements for #template when internet explorer is detected. Not ideal but worked for me for now
