### ISSUE TITLE
Multiple triggers for opening and closing the tooltip

### ISSUE THREAD

**Issue by sharatbaradia** [valor-software/ngx-bootstrap#3916]
https://valor-software.com/ngx-bootstrap/#/tooltip#triggers-custom

For example, when we do:
triggers="mouseenter:click"
It mean that tooltip will be displayed when we hover/put the mouse there and disappear when clicked.

Is it possible to specify two events for which tooltip should disappear?

Example, I want to display the tooltip when I hover on it and then make it disappear either when I click on it or remove the mouse from there. Something like mentioned below, Any ideas?

**triggers="mouseenter: mouseleave click"**

Example

```
<ng-template #popTemplate>
                    <div class="tooltip-renderer">Created By: {{creator}} <br/>
                         Created On: {{crDateTime | date:'short'}} <br/>
                         Revised By: {{revisor}} <br/>
                         Revised On: {{revDateTime | date:'short'}} <br/>
                    </div>
</ng-template>

<span [tooltip]="popTemplate" placement="right" container="body" triggers="mouseenter: mouseleave click">{{params.value}}</span>
```

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 2.0.0-beta.11
Angular: v4.0.3

**Comment by 5earle** [comment]
whats wrong with  triggers="mouseenter: mouseleave click" ?

**Comment by sharatbaradia** [comment]
@5earle triggers="mouseenter: mouseleave click" - doesn't work

**Comment by liuyiffan** [comment]
@koolhuman try this way. "mouseenter:mouseleave mouseenter:click"

**Comment by apotapcukv** [comment]
Dear sharatbaradia! 
As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.
