### ISSUE TITLE
how can container="body" and containerClass work together?

### ISSUE THREAD

**Issue by youngpink** [valor-software/ngx-bootstrap#3920]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Bug description or feature request:
I write a component, and use tooltip in my component.
I need to let tooltip wider, and not hidden by other DOM. 
So I use container="body", then tooltip is no longer hidden by other DOM.
But its width setting in customClass does not work (the default tooltip style is applied, but customClass's css does not work). 
I guess I did a wrong usage of customClass. Can anyone knows?

### plunker:

https://plnkr.co/edit/Eij9SrXC18Sfoh1cogy5?p=info

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.6.6

Angular: 2.4.9

Bootstrap: 4.0.0-alpha.5

**Comment by IlyaSurmay** [comment]
You have a typo in a binding name `conyainerClass="customClass"`, correct one in `containerClass="customClass"`. Also you haven't used `/deep/` for `.customClass` in your stylesheet.
Working example - https://plnkr.co/edit/VTZzbaiCucHMGTC72miH?p=preview
