### ISSUE TITLE
tooltip animations

### ISSUE THREAD

**Issue by MetaiR** [valor-software/ngx-bootstrap#3935]
it looks like tooltip animations not working even with `true` value of tooltipAnimation (it's true by default)  (tested on your documents site).

I used tooltip with normal html and bootstrap stylesheet and js and had a fade-in and fade-out animation. but in your (and also in what I have been used it) they suddenly appear and disappear without any animations.

**Comment by IlyaSurmay** [comment]
tooltipAnimation is deprecated and it doesn't do anything. Animations will be added later to all components

**Comment by IlyaSurmay** [comment]
Closed as related to #801

**Comment by MetaiR** [comment]
@IlyaSurmay I couldn't find any help or guidance on the issue you mentioned.
could u please give me at least another clue?

**Comment by IlyaSurmay** [comment]
@MetaiR animation isn't yet implemented in tooltip, so there's no guide actually. I just redirect all animation requests to one single issue.
