### ISSUE TITLE
Clear values in daterange picker

### ISSUE THREAD

**Issue by jagdishpatil222** [valor-software/ngx-bootstrap#3938]
I want to clear values in daterange picker. Currently I am using this code.
`
  reset(){
    this.upCommingAptSearchForm.patchValue({dateRange: null});

  }`

This function called on clear button. 

When I click on clear button the field of daterangepicker got reset but It holds the last selected values. I want to clear whole date picker with selected values.

**Comment by Joklogh** [comment]
Hi @jagdishpatil222 
You can reset values of the daterangepicker by two-way data binding.
Example : https://stackblitz.com/edit/angular-7ihmu8
Sorry for bad styling :) Let me know if this resolves your issue.

**Comment by Joklogh** [comment]
Hi @jagdishpatil222 
You can clear values by two-way data binding in template. Then if you want to clear values, simply assign to the variable `null`.
See example : https://stackblitz.com/edit/angular-ngx-bootstrap-gfz33k
