### ISSUE TITLE
Support for inline datepicker with the new styles

### ISSUE THREAD

**Issue by martintro** [valor-software/ngx-bootstrap#3955]
I need a inline datepicker with the new styles to get uniformed look in the application.

I've already added support for this in my forked repo and will soon do a pull request to this issue.

**Comment by shyamal890** [comment]
+1

**Comment by alexborghesi** [comment]
I have this issue too! Please upvote!

**Comment by ishworthapaliya** [comment]
+1

**Comment by seasquawks** [comment]
yes please...+1

**Comment by experionakash** [comment]
Any updates on this?

**Comment by toanhd** [comment]
feel like there will be no inline datepicker

**Comment by martintro** [comment]
It looks like it will be released in version 3.1.5. The PR has status ready for merge now :). FYI. Planned date for 3.1.5 seems to be 17 January
