### ISSUE TITLE
feat(datepicker): Style/mark individual dates in datepicker

### ISSUE THREAD

**Issue by martintro** [valor-software/ngx-bootstrap#3958]
I need functionality in the datepicker to style individual dates, like in the old datepicker (customClass). I could submit a pull request if we first can agree of the approach to solve it.

One suggestion is to add an array of dates with according css class to DatepickerRenderOptions and then use it in BsDaysCalendarView. What do you think?

**Comment by alexborghesi** [comment]
Sounds like a good solution! Need this.

**Comment by Adam-Sehlin** [comment]
I miss the same feature, need this for an ongoing project.

**Comment by Lanzen92** [comment]
Would be great!

**Comment by pavinthan** [comment]
great work @martintro, please make this available in master, or please describe how to achieve the feature with current system

**Comment by martintro** [comment]
@pavinthan I will try to make a new PR with this functionality as soon as my current inline datepicker PR (#3956) is merged to development branch.

**Comment by martintro** [comment]
This is not closed yet, because the commit was reverted in the pull request. Could you open this one again?

**Comment by martintro** [comment]
@pavinthan Now the pull request is made. I hope we can get a release with this as soon as possible :)
