### ISSUE TITLE
Allow tool tips on the tabs

### ISSUE THREAD

**Issue by ubiqs** [valor-software/ngx-bootstrap#3963]
### Feature Request

We have a requirement to add tooltip to a tab.
Earlier we were using basic bootstrap tabs so it works directly by adding "title".
We also used Telerik ToolTip (jquery) on top of it.

We are upgrading our code and using ngx-bootstrap tabs.
I tried adding "title" tag to it and its not working.

It would be great feature if ngx-tooltip can be applied on the tabs

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.2

Angular: 4.3.1

Bootstrap: 3

### Build system: 
WEbpack

**Comment by IlyaSurmay** [comment]
This is possible in current implementation, just use `tabHeading` directive and add tooltip to its content. 
```
 <tabset>
    <tab>
      <ng-template tabHeading>
        <span tooltip="tooltip text">tooltip here</span>
      </ng-template>
     asasas
    </tab>
  </tabset>
```
Example - https://stackblitz.com/edit/angular-5zczk9?file=index.html . Now tooltip is shown only when you hover over the text, you can easily change this via css (reset the padding of `<a>` and set padding for `a > span`)

**Comment by Ashanmg** [comment]
> This is possible in current implementation, just use `tabHeading` directive and add tooltip to its content.
> 
> ```
>  <tabset>
>     <tab>
>       <ng-template tabHeading>
>         <span tooltip="tooltip text">tooltip here</span>
>       </ng-template>
>      asasas
>     </tab>
>   </tabset>
> ```
> 
> Example - https://stackblitz.com/edit/angular-5zczk9?file=index.html . Now tooltip is shown only when you hover over the text, you can easily change this via css (reset the padding of `<a>` and set padding for `a > span`)

Thanks. This worked for me.
