### ISSUE TITLE
ngModel not updated on date selection

### ISSUE THREAD

**Issue by rashnk** [valor-software/ngx-bootstrap#3967]
When i select a date it is showing the previous one in console.log()

ngx-bootstrap:  2.0.2   

Angular: 5

Bootstrap: 4

Build system: Angular CLI, 

```
<input class="form-control" (ngModelChange)="validateDates()" bsDatepicker [(ngModel)]="mydates.date1" >
<input class="form-control" (ngModelChange)="validateDates()" bsDatepicker [(ngModel)]="mydates.date2" >

 validateDates() {
    console.log(this.mydates.date1); //here it is not showing the selected date, but previous one 
    console.log(this.mydates.date2);
    console.log('date checking ');
    if (this.mydates.date1 > this.mydates.date2) {
      console.log('date is wrong');
      
    }
  }
```

**Comment by IlyaSurmay** [comment]
Could you provide a reproduction of this issue?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by ghost** [comment]
There has been no response. That's why the issue was closed
