### ISSUE TITLE
typeahead: if auto selected an item, the others are not visible

### ISSUE THREAD

**Issue by fegyi001** [valor-software/ngx-bootstrap#3968]
### Bug description or feature request:
I experienced the following: I set the items of an autocomplete component. Then immidiately I select the first one as the selected value, since I want to set an initial value for this specific typeahead field. If I do so, the auto-selected item is visible, but all the other items cannot be seen, the dropdown shows nothing else than the auto-selected item.

Here is the template: 
``` html
<ng-template #template let-model="item" let-index="index">
  <div [style.font-weight]="model.name === selected?.name ? 'bold' : 'normal'">{{model.name}}</div>
</ng-template>
<form [formGroup]="myForm">
  <p class="input-group">
    <input formControlName="itemData" [typeahead]="items" [value]="selected.name" [typeaheadOptionField]="'name'" (typeaheadOnSelect)="typeaheadOnSelect($event)"
      class="form-control" [typeaheadMinLength]="0" [typeaheadWaitMs]="0" placeholder="Válasszon megjelenítési módot..." (focus)="selectAllContent($event)"
      [typeaheadItemTemplate]="template">
    <span class="select-arrow"></span>
  </p>
</form>
```

Here is the component logic:
``` typescript

export class AdatStyle {
    constructor(public name: string, public value: string, public visible: boolean) { }
}

@Component({
  selector: 'bt-utca-adatlayer',
  templateUrl: './utca-adatlayer.component.html',
  styles: []
})
export class UtcaAdatlayerComponent implements OnInit {
  items: any[];
  myForm: FormGroup;
  selected: AdatStyle = null;

  constructor(private utcaService: UtcaService, private fb: FormBuilder) {
    this.myForm = fb.group({
      itemData: ['']
    });
  }

  ngOnInit() {
    this.items = [
      new AdatStyle('Egységes megjelenítés', 'bunWsp:adatPontStyle', true),
      new AdatStyle(
        'Közeli pontok összevonása',
        'bunWsp:adatPontClusterStyle',
        true
      ),
      new AdatStyle('Hőtérképes megjelenítés', 'bunWsp:heatmap', true),
      new AdatStyle('Nincs megjelenítés', 'bunWsp:adatPontStyle', false)
    ];
    this.selected = this.items[0];
    this.utcaService.adatStartStyle = this.selected;
    this.utcaService.selectedAdatStyle.next(this.selected);
  }

  typeaheadOnSelect(e: TypeaheadMatch): void {
    this.selected = new AdatStyle(e.item.name, e.item.value, e.item.visible);
    this.utcaService.selectedAdatStyle.next(this.selected);
  }

  selectAllContent($event) {
    $event.target.select();
  }
}
```
With the 2.0.0-rc.0 version of ngx-bootstrap, everything works just fine.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.2

Angular: 5.2.8

Bootstrap: 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI

**Comment by rbrewington** [comment]
This functionality changed as a result of another issue (see: https://github.com/valor-software/ngx-bootstrap/issues/2845)

We were sort of relying on this functionality as well and have avoided updating the bootstrap package for lack of a work around. 

We're looking at potentially forking the codebase and reverting that change, but it would be way better to have access to a flag as the OP from the linked issue above suggested.

**Comment by rbrewington** [comment]
We've moved forward with a fork for now, but would love if this was incorporated at some point so we don't have to constantly rebase it after each release.

**Comment by Liahus3003** [comment]
Is this issue resolved ?

**Comment by rbrewington** [comment]
Anything more I need to do to get this PR looked at? We'd really like to not depend on our forked project.

**Comment by rbrewington** [comment]
If anyone is still looking for a way to do this, you can extend the directive instead of using a fork:
```javascript
import { HostListener, Directive, Input } from '@angular/core';
import { TypeaheadDirective } from 'ngx-bootstrap';

@Directive({
  selector: '[custom-typeahead]',
})
export class CustomTypeahead extends TypeaheadDirective {
  @Input() typeaheadShowAllOnFocus: boolean;

  @HostListener('focus')
  onFocus(): void {
    if (this.typeaheadShowAllOnFocus) {
      if (this.typeaheadMinLength === 0) {
        this.typeaheadLoading.emit(true);
        this.keyUpEventEmitter.emit('');
      }
    } else {
      super.onFocus();
    }
  }
}
```

**Comment by lentschi** [comment]
@rbrewington 
Thanks this basically works!

Interestingly I had to add a setter to forward the data to the base class:

```typescript
@Input('custom-typeahead')
set customTypeahead(data: any) {
  this.typeahead = data;
}
```

Maybe this wasn't required on earlier angular versions (I'm using angular 8)?

**Comment by rbrewington** [comment]
@lentschi I haven't had to do that, but I'm also still using 4.2.0, so maybe that's the result of an ngx-bootstrap update. 🤷‍♀ 
Glad you got it working, tho!

**Comment by Santoshah** [comment]
> @rbrewington
> Thanks this basically works!
> 
> Interestingly I had to add a setter to forward the data to the base class:
> 
> ```ts
> @Input('custom-typeahead')
> set customTypeahead(data: any) {
>   this.typeahead = data;
> }
> ```
> 
> Maybe this wasn't required on earlier angular versions (I'm using angular 8)?

can you help me with stackbliz demo.

**Comment by rbrewington** [comment]
@Santoshah You shouldn't need to do anything special anymore, as this feature appears to already exist in the current version of ngx-bootstrap (v6.0.0).

```html
<input
  [(ngModel)]="selected"
  [typeahead]="typeaheadOptions"
  [typeaheadMinLength]="0"
/>
```
Stackblitz: https://stackblitz.com/edit/typeahead-all-options-qsmxd

**Comment by rbrewington** [comment]
@Domainv @valorkin This issue could probably be closed.

**Comment by valorkin** [comment]
> @Domainv @valorkin This issue could probably be closed.

Thank you!
