### ISSUE TITLE
Need id for Carousel

### ISSUE THREAD

**Issue by bhartiuma** [valor-software/ngx-bootstrap#3969]
### Bug description or feature request: 

Need id for carousel previous and next buttons

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0

Angular: 5.0.0

Bootstrap: 4.0.0

### Build system: 

Angular CLI

**Comment by IlyaSurmay** [comment]
Could you explain why do you need them? Native Bootstrap carousel's buttons don't have `id` attribute so we didn't add them either. If you need to access them via css, use class selectors `.carousel-control`

**Comment by bhartiuma** [comment]
Yeah. In css we can access it with this selector. But actually I need it for automation testing.

**Comment by IlyaSurmay** [comment]
I guess you can use these selectors in testing as well, just scope them to a component, like `my-demo-component .carousel-control`
