### ISSUE TITLE
ng test failed :  If 'accordion-group' is an Angular component, then verify that it is part of this module.

### ISSUE THREAD

**Issue by rashnk** [valor-software/ngx-bootstrap#3984]
Trying to run unit test
`ng test` returned error  If 'accordion-group' is an Angular component, then verify that it is part of this module.
 
How to fix this ?

ngx-bootstrap: 2.0.2

Angular: 5

Bootstrap: 4

Build system: Angular CLI,

**Comment by valorkin** [comment]
Don't foegwt to import accordion module into test bad, or add no schema error
