### ISSUE TITLE
docs(datepicker): edit description for Forms demo example (delete missprint, make it more clear)

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3989]
### Bug description:
now description for Forms datepicker demo example contains missprint (`2 object` instead of `2 objects`) and is not enough clear (it would be better to add type of objects for daterangepicker)
![formsdpdescr](https://user-images.githubusercontent.com/27342505/37412149-08bad09e-27ad-11e8-83a0-8d41edd3f925.jpg)

### Steps to reproduce
- Go to Datepicker demo page
- Scroll down page to Forms demo example
- Read Example's description

**Comment by EvilAlexei** [comment]
Closed by PR #3988
