### ISSUE TITLE
accordion: isOpen does not work with first click

### ISSUE THREAD

**Issue by brosenberger** [valor-software/ngx-bootstrap#399]
_Actions:_
- go to example @ http://valor-software.com/ng2-bootstrap/#accordion
- expand the last item by clicking the accordion component
- close the last item by clicking the button on top

_Expected:_
- the accordion component closes instantly after clicking the button

_Result:_
- closing works on the second click on the close button

_Version info:_
angular2 v2.0.0-beta.14
bootstap v4.0.0-alpha.2
ng2-bootstrap v1.0.11

**Comment by thejewdude** [comment]
I want to add that the button only toggles visibility on first click if the current state of visibility is consistent with the result of the last time it toggled the visibility.

**Comment by valorkin** [comment]
It is actually working, but it is a one way binding from status.open to isOpen
but fixed anyway, thanks :)

**Comment by calvinKG** [comment]
When are you pushing the next release to fix this bug ?
