### ISSUE TITLE
Tabs: Loading Component Dynamically

### ISSUE THREAD

**Issue by r3z0** [valor-software/ngx-bootstrap#400]
How would you load dynamically a component within a tab?

**Comment by viskin** [comment]
Can it be done like this?

``` html
<tabset>
   <tab heading="Shows Component">
      <my-loadable-component></my-loadable-component>
   </tab>
</tabset>
```

And loadable-component will load its content dynamically. Just theoretic answer, I didn't try it.

**Comment by valorkin** [comment]
@r3z0 what do you mean? 
let us continue chat in https://www.hamsterpad.com/chat/ng2
