### ISSUE TITLE
Timepicker: wrong time in reactive form variable from that being shown in the html inputs

### ISSUE THREAD

**Issue by joelmuskwe** [valor-software/ngx-bootstrap#4002]
When i use the timepicker the time being captured when i use reactive forms is 2hrs ahead of that being caputured in the reactive form.
![ngx](https://user-images.githubusercontent.com/5989937/37466675-0cd332ec-2867-11e8-9c5a-7f1f4aa57540.PNG)

Example on plunker

Plunkr: https://plnkr.co/edit/qd4GxM7GJuVNryNmkeSR?p=preview

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.3

Angular: 5

Bootstrap: 4

Angular CLI: 1.7.2

**Comment by MarcoBatista** [comment]
I have the same problem, in the model I have 2018-04-17T12:28:55.130Z but in time picker shows 13:28

Angular 5
Bootstrap 4
ngx-bootstrap: 2.0.4

**Comment by danielfoord** [comment]
I don't think this is a bug. The plunker is using the 'json' pipe on the output, instead one should use the 'date' pipe with a format:

Stackblitz: https://stackblitz.com/edit/angular-btg2mu

![Screenshot 2019-10-13 at 22 34 07](https://user-images.githubusercontent.com/4738017/66722052-a01ecc00-ee09-11e9-8f1e-160b5b4d881d.png)

Edit: The json pipe shows the date time in the [UTC format according to ISO_8601](https://en.wikipedia.org/wiki/ISO_8601). While the date pipe will show the time in the browser's time zone.
