### ISSUE TITLE
Modal and Component

### ISSUE THREAD

**Issue by lonekawboy** [valor-software/ngx-bootstrap#4024]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Bug description or feature request:

It seems that with Angular the use of Components is the way to go for modals. I'm attempting to utilize this modal with a parent component calling a child component for the modal to add an item. I cannot find any example of how I would get indication back to the parent component that the user has "added" an item. Any example of this usage? Thanks much!

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

**Comment by IlyaSurmay** [comment]
Create an `EventEmitter` in your modal component and subscribe to it.
Here are few similar questions. Please please search for duplicates (opened and closed) and StackOverflow questions before opening an issue here
https://stackoverflow.com/questions/47702033/passing-data-from-the-child-modal-to-the-parent/47711617#47711617 
https://stackoverflow.com/questions/49261541/subscribe-to-changes-from-modal-component-in-ngx-bootstrap-modal/49274540#49274540
