### ISSUE TITLE
Angular 5 - Modals - class property in html not working

### ISSUE THREAD

**Issue by MarcoLeko** [valor-software/ngx-bootstrap#4027]
### If i bind a custom class  property in the config block ('modal-lialog-centered'), no visual changes apper, but the setting the backdrop to false works^^

![image](https://user-images.githubusercontent.com/15436327/37595930-cccaf70e-2b7a-11e8-833d-077013256f72.png)

and if i add the classes in the div **modal-dialog**  the whole application starts to freeze. My angular-cli pretty much looks like: 
`      "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "styles.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/tether/dist/js/tether.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js"
      ],`

and the achievement-modal comp looks like: 

`import { Component, ViewChild } from '@angular/core';
import { ModalDirective } from 'ngx-bootstrap';

@Component({
  selector: 'app-achievement-modal',
  templateUrl: './achievement-modal.component.html',
  styleUrls: ['./achievement-modal.component.css']
})
export class AchievementModalComponent {

  @ViewChild('childModal') childModal: ModalDirective;

  open() {
    this.childModal.show();
  }
}`
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.3

Angular: ^5.0.0

Bootstrap: bootstrap4.0.0-v.3 beta

**Comment by DanilAgafonov** [comment]
According to Bootstrap Docs you shoul put `.modal-dialog-centered` to `.modal-dialog` element. See: https://getbootstrap.com/docs/4.0/components/modal/#vertically-centered

But you are trying apply this class to wrong element.

You should investigate freezing in case if you put `.modal-dialog-centered` to `.modal-dialog` element and stop trying to apply this class through config.
