### ISSUE TITLE
TooltipConfig to add delay option

### ISSUE THREAD

**Issue by beeing** [valor-software/ngx-bootstrap#4029]
Currently TooltipConfig only support 3 options but not delay. We looking at adding delay to TooltipConfig at global level.

Thanks!

**Comment by beeing** [comment]
Hi, is this to be added soon?

**Comment by samu** [comment]
The same problem exists with the popover: there is no way to set a delay.

**Comment by stasagv** [comment]
it would be cool to set delay globally

**Comment by fynnfeldpausch** [comment]
Any progress on this issue?
