### ISSUE TITLE
How to create a unit test for bsDatepicker?

### ISSUE THREAD

**Issue by hmendezm** [valor-software/ngx-bootstrap#4031]
### Bug description or feature request:
I have tried for 4 days to write a unit test. This component in Angular 5 has a bsDatepicker with ngmodel. it looks like 
```
  <input type="text"  name="istartDate" class="form-control" placeholder="end date"
                        [(ngModel)]="startDate" bsDatepicker/>
```
If I removed the bdDatepicker attribute the unit test works but when I add the bsDatePicker stop working.  Do you have an example in how I can write an unit test for html components that include ngx-bootstrap components?

Unit TEST
```
beforeEach(() => {
        fixture = TestBed.createComponent(DataFilterComponent);
        component = fixture.componentInstance;

        applyBtnEl = fixture.debugElement.query(By.css("#btnAplyFilter"))
            .nativeElement;

        startDateEl = fixture.debugElement.query(
            By.css('input[name="istartDate"]')
        );
              fixture.detectChanges();
        fixture.whenStable();
    });
  it(
        "should set filter to user inputs",
        fakeAsync(() => {
            fixture.detectChanges();
            const date = new Date();

            const expectedStartDate = moment(
                date.getUTCMonth() +
                    "/" +
                    date.getUTCDate() +
                    "/" +
                    date.getUTCFullYear()
            ).format("L");

            // set the ngModel with a random value to test custom filter by range of dates
            // set the ngModel for startDate
            sendInput(startDateEl.nativeElement, expectedStartDate)
                .then(() => {
                    return sendInput(
                        startDateEl.nativeElement,
                        expectedStartDate
                    );
                })
                .then(() => {
                    click(applyBtnEl);
                    fixture.detectChanges();
                  console.log(component.startDate);
                });

    );
 /**
    * This function set the value to an input control
    * @param inputElement the inputElement to set value
    * @param text Value to set to the inpuElement
    */
    function sendInput(inputElement: any, text: string) {
        inputElement.value = text;
        inputElement.dispatchEvent(new Event('input'));
        fixture.detectChanges();
        return fixture.whenStable();
    }
```

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: ^11.2.0

Angular: 5

Bootstrap: 4

### Build system: Angular CLI, System.js, webpack, starter seed: 
angular CLI

**Comment by hmendezm** [comment]
Hi Guys, does someone has an answer to my question? I really need to fix the unit test. any help I really will appreciate.

**Comment by tomas031** [comment]
I have same issue, ngx-bootstrap version 2.0.2. and angular 5.2.9

Tests failing with error: "Can't bind to 'bsConfig' since it isn't a known property of 'input'."

I has imported 
import { BsDatepickerModule } from 'ngx-bootstrap/datepicker';

beforeEach(async(() => {
    TestBed.configureTestingModule({
        ...
      imports: [
        ...
        BsDatepickerModule.forRoot()
      ],
}).compileComponents();

**Comment by dantullis** [comment]
Works for me if I use the following import:
`import { BsDatepickerModule } from 'ngx-bootstrap';`

**Comment by radiumrasheed** [comment]
can someone provide a way to mock this component instead of importing it
