### ISSUE TITLE
Typeaheads' optionsListTemplate does not provide full component context

### ISSUE THREAD

**Issue by bytelabsco** [valor-software/ngx-bootstrap#4036]
### Bug description or feature request:

**Bug** When using Typeahead's optionsListTemplate option, the full component context is not passed into the specified template.  Instead only matches, itemTemplate and query are passed in.

This means you can't replicate basic functionality that the default template provides (such as selecting an item, highlighting the active item, etc) without duplicating the existing logic into your own component.

I believe this should be able to be easily resolved by modifying typeahead-container.component.html and changing:
` [ngTemplateOutletContext]="{matches:matches, itemTemplate:itemTemplate, query:query}"`

to
`[ngTemplateOutletContext]="this"`

### Versions of ngx-bootstrap:
ngx-bootstrap:
2.0.3

**Comment by ghost** [comment]
@bytelabsco thanks, but Typeahead's optionsListTemplate option was implemented in this [pr](https://github.com/valor-software/ngx-bootstrap/pull/4751)
Closed as duplicated issue #3081.
