### ISSUE TITLE
docs(modal): update description for Modal events demo

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#4047]
### Issue description:
At Modal events demo names of events are not placed inside `code` tag

### Steps to reproduce
- Go to Modals demo page
- Scroll down to Modal events demo at Directive examples section
- Look at description to demo from second step

#### Actual result:
Events' names are not marked as code at description to demo
![modaleventsdescr](https://user-images.githubusercontent.com/27342505/37709233-3f19aa60-2d12-11e8-9808-7b4ba969366c.jpg)

#### Expected result:
Events' names are placed inside `code` tag

**Comment by stiofand** [comment]
The Component example is also not correct
