### ISSUE TITLE
is:issue is:open No configuration to add header and footer in date picker.how to add header and footer in date picker.I want to add close button in the header and footer button in the footer.

### ISSUE THREAD

**Issue by rajeshbayya** [valor-software/ngx-bootstrap#4053]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

**Comment by IlyaSurmay** [comment]
No need to duplicate your question here if it's already been asked on StackOverflow ( https://stackoverflow.com/questions/49420319/how-to-add-header-and-footer-to-ngx-bootsrap-date-picker-i-want-to-add-close-but ) 
Customization of templates is not yet supported.
