### ISSUE TITLE
bootstrap events

### ISSUE THREAD

**Issue by justinmchase** [valor-software/ngx-bootstrap#407]
I would like to bind to bootstrap events in my angular template but I can't seem to figure it out.

For example I have a modal and would like to do this:

```
<div
  class="modal"
  (shown.bs.modal)="usernameText.focus()">
  <input #usernameText />
</div>
```

But it appears that angular isn't aware of the bootstrap events being fired. It would be pretty sweet if this was possible. Thoughts?

**Comment by valorkin** [comment]
are you sure that event name is correct?
+1 to to list of reasons to migrate bootstrap to ng2
