### ISSUE TITLE
How do I pass a string value to popover template, via popoverContext?

### ISSUE THREAD

**Issue by ShrinivasKattimani** [valor-software/ngx-bootstrap#4070]
<ng-template #popTemplate let-message="message">{{ message }}</ng-template>
<button type="button" class="btn btn-primary"
        [popover]="popTemplate" [popoverContext]="context">
  Open popover with custom context
</button>

The above example from the official website of ngx-bootstrap enforces the  value to be passed to be an object. i.e. context here in the example is an object. What if my context is just a string or number?

**Comment by andrconstruction** [comment]
is anybody knows?

**Comment by nesinervink** [comment]
In template:
`[popoverContext]="getPopoverContent( 'foo' )`

In component:
`public function getPopoverContent( bar ) { return { messsage: bar }; }`

**Comment by valorkin** [comment]
Yes, context is an object. So just pass it as an object

**Comment by Orel-A** [comment]
What if I want access to the context object itself?
