### ISSUE TITLE
bug(demo): Navbar "Toggle navigation" doesn't collapse in demo

### ISSUE THREAD

**Issue by m-abs** [valor-software/ngx-bootstrap#409]
The ng2-bootstrap demo doesn't work correctly on a small screen.
The navbar starts collapse but with the navigation menu open, the menu can't be closed.

See screenshot:
![ng2-bootstrap](https://cloud.githubusercontent.com/assets/1348705/14522603/9c67f1aa-022f-11e6-8f92-6f60a698bd98.png)

**Comment by lunchboxer** [comment]
I can confirm this behavior on Chromium for Android v52 and Firefox for Android v46
