### ISSUE TITLE
No Directive annotation found on DatePicker

### ISSUE THREAD

**Issue by brozorec** [valor-software/ngx-bootstrap#410]
Using `"ng2-bootstrap": "1.0.11"` and `"angular2": "2.0.0-beta.14"` with webpack. When I declare `directives: [DATEPICKER_DIRECTIVES]` in my `@Component` I got this error. Tried with `BUTTON_DIRECTIVES` and had same type of error: `No Directive annotation found on ButtonCheckbox`.

**Comment by valorkin** [comment]
@brozorec please provide repo to reproduce, because works fine with meteor, system and webpack
