### ISSUE TITLE
Responsive CSS Date Range Picker Bootstrap 3

### ISSUE THREAD

**Issue by vswom** [valor-software/ngx-bootstrap#4127]
Hello ,

I just encountered a responsive problem with the Date Range Picker for bootstrap 3 components.

When i zoom -90% 

the responsive is badly managed on bootstrap 3.

thank you for your work.

<img width="772" alt="capture d ecran 2018-03-28 a 11 10 06" src="https://user-images.githubusercontent.com/6407566/38019791-da50c322-3278-11e8-93a5-941c9ca058b0.png">

<img width="779" alt="capture d ecran 2018-03-28 a 11 10 18" src="https://user-images.githubusercontent.com/6407566/38019794-de1cb88a-3278-11e8-83ee-915258736bf3.png">

**Comment by valorkin** [comment]
Fixed in #4891
