### ISSUE TITLE
feature: possibility to show typeahead full list

### ISSUE THREAD

**Issue by rbaarsma** [valor-software/ngx-bootstrap#413]
I would very much like to give users the possibility to view the entire list. Preferably by default on focus and/or with a toggle button next to the input.

Although the show() and hide() functions are public I cannot find a way to access them in my component. Also even if I was able to do so, I'd still have to manually add the matches as all matches for it to work.

A quick solution I came up with is to allow minLength=0 and I coded this into a fork, but I'm not sure if it's the most logical solution and it still does not make it possible to toggle it with a button.

I made a pull request for this solution:
https://github.com/valor-software/ng2-bootstrap/pull/412

**Comment by hongbo-miao** [comment]
@rbaarsma thanks, a nice PR, link to my old [issue](https://github.com/valor-software/ng2-bootstrap/issues/187). Help to close both issues together later.
