### ISSUE TITLE
typeahead selector specificity 

### ISSUE THREAD

**Issue by tomgruszowski** [valor-software/ngx-bootstrap#4136]
Increase the specificity of typeahead control selector (and maybe others). i.e. from `[typeahead]` to `input[typeahead]`.

While NGX has a good typeahead for open ended text, there are other select/typeahead components better suited for replacing the typical select html control (aka select2), they also use the 'typeahead' directive name but are correctly scoped. 

One example is [ng-select](https://github.com/ng-select/ng-select). ngx-bootstrap seems to take a very global selector approach that can perhaps be narrowed.

**Comment by valorkin** [comment]
Typeahead can be used with any element which has custov value accessor implemented
Not related to this issues, but all controls will be namespaced.
