### ISSUE TITLE
Add possibility to use scss instead css for components like bsDatepicker

### ISSUE THREAD

**Issue by viros** [valor-software/ngx-bootstrap#4137]
We are using bootstrap 4 in angular application with our custom theme like described here: [https://getbootstrap.com/docs/4.0/getting-started/theming/](https://getbootstrap.com/docs/4.0/getting-started/theming/ )

It would be great to have possibility to use bsDatepicker.scss instead of bsDatepicker.css. 
In this case if blue theme customized so it will be customized for bsDatepicker.

F.E (It's implemented in ngx-toastr)
```
@import "_variables"; // here we override bootstrap variables/colors
@import "~bootstrap/scss/bootstrap";// import bootstrap that will use new variables/colors
@import "~ngx-toastr/toastr-bs4-alert";// toastr component use themes with customized colors
```

**Comment by IlyaSurmay** [comment]
ngx-bootstrap provides `scss` for datepicker as well as css
`node_modules/ngx-bootstrap/datepicker/bs-datepicker.scss`
