### ISSUE TITLE
Carousel noWrap not working

### ISSUE THREAD

**Issue by TeodorKolev** [valor-software/ngx-bootstrap#4138]
### Bug description or feature request:
Carousel [noWrap]="noWrapSlides" not working

**Comment by IlyaSurmay** [comment]
Works fine here https://stackblitz.com/edit/angular-g2opt5?file=app/basic.html
Could you provide a reproduction of this issue?

**Comment by TeodorKolev** [comment]
My target is to disable looping, not to loop once and stop after that

**Comment by IlyaSurmay** [comment]
https://valor-software.com/ngx-bootstrap/#/carousel#carousel-component
As mentioned in the documentation, if you want to disable autoplay, set `interval` property to `0`
