### ISSUE TITLE
Carousel activeSlide not working

### ISSUE THREAD

**Issue by TeodorKolev** [valor-software/ngx-bootstrap#4139]
### Bug description or feature request:
Carousel [(activeSlide)]="activeSlideIndex" set to 1 produce error
`ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: 1'. Current value: 'ngIf: 0'.`

**Comment by IlyaSurmay** [comment]
Please provide a reproduction via plunkr or stackblitz

Starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by TeodorKolev** [comment]
Here:
https://stackblitz.com/edit/ngx-bootstrap-pefcsa?file=app/app.component.ts

**Comment by StefanNedelchev** [comment]
I confirm the same issue with ngx-bootstrap v4.3.0

**Comment by coffeymatt** [comment]
Not working in 5.1.1
