### ISSUE TITLE
No Directive annotation found on Alert (angular2-meteor1.3)

### ISSUE THREAD

**Issue by hongbo-miao** [valor-software/ngx-bootstrap#414]
For a new meteor 1.3.1 project, I have run those in terminal

> npm init
> meteor add angular2-compilers
> meteor remove blaze-html-templates
> meteor npm install --save angular2-meteor
> meteor npm install --save meteor-node-stubs
> meteor npm install --save bootstrap4-webpack-package
> meteor npm install --save ng2-bootstrap

```
import 'reflect-metadata';
import 'zone.js/dist/zone';
import 'bootstrap4-webpack-package';
import { Component } from 'angular2/core';
import { bootstrap } from 'angular2/platform/browser';
import { Alert } from 'ng2-bootstrap/ng2-bootstrap';

@Component({
  selector: 'app',
  template: `<alert type="info">ng2-bootstrap hello world!</alert>`,
  directives: [Alert]
})
class App { }
bootstrap(App);
```

Right now `bootstrap4-webpack-package` makes Bootstrap 4 works, but ng2-bootstrap still not works.

Since I am using Bootstrap 4, so I also tried to add 

```
import { Ng2BootstrapConfig, Ng2BootstrapTheme } from 'ng2-bootstrap/ng2-bootstrap';
Ng2BootstrapConfig.theme = Ng2BootstrapTheme.BS4;
```

But still not works.

It shows the error:

> EXCEPTION: No Directive annotation found on Alert
> EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on Alert

I am not sure whether this is related with this [issue](https://github.com/meteor/meteor/issues/6037).

I put a demo to reproduce this issue [here](https://github.com/Hongbo-Miao/issue2-ng2-bootstrap). You can download it and run `npm install` first, and then `meteor` in terminal.

How can I use ng2-bootstrap? Thanks

**Comment by valorkin** [comment]
thanks for demo, I will check it :)

**Comment by valorkin** [comment]
![](https://sc-cdn.scaleengine.net/i/0bdb599dcfdd2a6f069bf1728c2eb2ec.png)

just tried from your repo, works fine

**Comment by hongbo-miao** [comment]
@valorkin thanks!!! It seems like my NPM has problem, I uninstall my NPM, and install the new v5.10.1, the problem fixes!

**Comment by valorkin** [comment]
Just use npm 3 to avoid typings issues

**Comment by prasadnpawar** [comment]
@Hongbo-Miao It is still not working for me. I have written the same code and I am using Nodejs V5.11.1 and npm v3.8.9. Can you please tell me what exactly I have to do when I installed this latest version

**Comment by jonathanfishbein1** [comment]
@Hongbo-Miao having a similar issue with the accordion directive

**Comment by hongbo-miao** [comment]
@prasadnpawar @jonathanfishbein1 can you succeed running Meteor 1.3 and Angular 2 RC1 app without ng2-bootstrap?

**Comment by Hongbo-Miao** [comment]
1. Be sue to use `npm install --save @angular/core @angular/common @angular/platform-browser @angular/platform-browser-dynamic @angular/router-deprecated` in Angular RC 1.
2. Be sure to update using new ng2-bootstrap components names. Check here for [new ng2-bootstrap components names](https://github.com/valor-software/ng2-bootstrap/blob/development/CHANGELOG.md#breaking-changes).

**Comment by hongbo-miao** [comment]
I moved the answer to [Meteor forum](https://forums.meteor.com/t/for-people-who-are-following-socially-tutorial/22994) to help people who may meet similar problem.

**Comment by prasadnpawar** [comment]
Thanks @Hongbo-Miao . It worked fine when I did npm install --save @angular/core @angular/common @angular/platform-browser @angular/platform-browser-dynamic @angular/router-deprecated. Also I removed angular2 and I am currently using angular2-meteor-auto-bootstrap.

**Comment by hongbo-miao** [comment]
@prasadnpawar cool!

**Comment by valorkin** [comment]
hey @Hongbo-Miao I really appreciate your help with resolving community issues
I have invited you to ng2-team
Thanks! :)

**Comment by hongbo-miao** [comment]
@valorkin wow, that is awwwwesome!
