### ISSUE TITLE
It is possibile to format date range picker?

### ISSUE THREAD

**Issue by MihaiHoriaPopescu** [valor-software/ngx-bootstrap#4143]
It is possibile to format date range picker? 
I didn't found a method to format the range, and 'MM/DD/YYYY' is not the best format to use.

**Comment by 7185** [comment]
Try `rangeInputFormat` instead of `dateInputFormat`.

**Comment by MihaiHoriaPopescu** [comment]
@7185 Thank you, that works!

**Comment by MihaiHoriaPopescu** [comment]
rangeInputFormat was the right answer
