### ISSUE TITLE
option dayDisabled is not recognize as input property to datepicker

### ISSUE THREAD

**Issue by hardikjain90** [valor-software/ngx-bootstrap#4145]
Hi,
I tried using the option dayDisabled in order to disable the weekends 
but it raises the error as `Can't bind to 'dayDisabled' since it isn't a known property of 'input'`

Eg.
`<input
  type='text'
  class='form-control'
  name='datepickerValueDate'
  readonly='true'
  bsDatepicker
  #dp='bsDatepicker'
  [(ngModel)]='datepickerValueDate'
  [bsConfig]="{ dateInputFormat: 'DD/MM/YYYY' }"
  [dayDisabled]='dayDisabled'>
`

In Component
`dayDisabled = [0, 6]`

Please let me know if something is missing here 
OR issue is required to be resolved 

I am using ngx-bootstrap@2.0.3

Thanks and Regards,
Hardik Jain

**Comment by IlyaSurmay** [comment]
Hi! `dayDisabled` input is a part of the old datepicker implementation. A new one doesn't have a functionality for disabling specific days, there is similar feature request here #1657

**Comment by jorgemv** [comment]
Hello! I can see the dayDisable attribute in the new datepicker component API reference (https://valor-software.com/ngx-bootstrap/#/datepicker#days-disabled), but it's still returning the same error: Can't bind to 'dayDisabled' since it isn't a known property of 'input'. Then, why is this attribute in the new documentation?

**Comment by valorkin** [comment]
Ngx bs version 3.1.3+

**Comment by Avi-E-Koenig** [comment]
So whats the deal here?
Documentation shows option but its not implemented?

anyway my workaround is based on this:
https://stackoverflow.com/questions/47738545/mark-disabled-ng-bootstrap-not-working-with-other-datepickers-examples#answer-47741628
