### ISSUE TITLE
can't use ngx-bootstrap with angular2-meteor project

### ISSUE THREAD

**Issue by boulbrimaOussema** [valor-software/ngx-bootstrap#4146]
I am using ngx-bootstrap in an angular2-meteor project.
when i import the datepicker the app crashes on loading with an error 

![untitled](https://user-images.githubusercontent.com/26189667/38129789-575bbfcc-33f8-11e8-95f7-93b3ad30b0e4.png)

i started this project basing on Urigo/meteor-angular2.0-socially

my package.json `{
  "name": "xx",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "test": "meteor test --driver-package practicalmeteor:mocha",
    "test:ci": "meteor test --once --driver-package dispatch:mocha-phantomjs"
  },
  "dependencies": {
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/router": "3.1.2",
    "angular2-meteor": "0.7.0",
    "angular2-meteor-accounts-ui": "^1.0.0",
    "angular2-meteor-polyfills": "0.1.1",
    "angular2-meteor-tests-polyfills": "0.0.2",
    "bootstrap": "^4.0.0-alpha.3",
    "hammerjs": "^2.0.8",
    "meteor-node-stubs": "0.2.3",
    "meteor-rxjs": "0.4.3",
    "meteor-typings": "1.3.1",
    "ngx-bootstrap": "^2.0.3",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@types/chai": "^3.4.33",
    "@types/mocha": "^2.2.32",
    "chai": "3.5.0",
    "chai-spies": "0.7.1"
  }
}
`

ngx-bootstrap:2.0.3

Angular:2

Bootstrap:4

**Comment by IlyaSurmay** [comment]
I suppose that's happening because of an old version of Angular packages. If you're using any version of ngx-bootstrap that's higher than 2.0.0, you need to have at least Angular 4

1.9.3 is the last version that supports Angular 2
