### ISSUE TITLE
Datepicker and Today date

### ISSUE THREAD

**Issue by igasparetto** [valor-software/ngx-bootstrap#4147]
Hi guys,

There are some things I need to do here I can't find in the docs, so I am raising this ticket.

1. How do I place a "Today" button in the datepicker?
2. Today's date is not highlighted in the popup. It also doesn't have any css class so that I can style it.

Thanks

**Comment by IlyaSurmay** [comment]
Hi!
1. There's no support for custom templates for now.
2. We already have an issue with this request #3192

**Comment by igasparetto** [comment]
Thanks

**Comment by ujjaldey** [comment]
As a workaround for point 1, I took this approach:

Added a button next to date picker:

```
<button class="btn btn-secondary" (click)="selectToday()">
    <i class="fas fa-calendar-day"></i>
</button>
```

In component.ts:

```
  selectToday(): void {
    this.myForm.patchValue({
      date: new Date(),
    });
  }
```

Output:
![image](https://user-images.githubusercontent.com/16843102/52907804-e1270680-32a3-11e9-8eb2-26b2c3b3aa7a.png)

**Comment by fawadtayyab123** [comment]
@ujjaldey  what if I've hundreds of date picker in my application?
