### ISSUE TITLE
How to Hide the tab header?    

### ISSUE THREAD

**Issue by wilson0506** [valor-software/ngx-bootstrap#4155]
How to Hide the tab header?    

as i want to control tab switching outside
<ul class="nav nav-tabs" ng-reflect-klass="nav" ng-reflect-ng-class="[object Object]"> <li class="nav-item active" ng-reflect-ng-class="nav-item,"> <a class="nav-link active" href="javascript:void(0);" id=""> <span></span>  </a> </li><li class="nav-item" ng-reflect-ng-class="nav-item,"> <a class="nav-link" href="javascript:void(0);" id=""> <span></span>  </a> </li> </ul>

**Comment by IlyaSurmay** [comment]
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

There's no special option in tab component that hides tab headers, but you can achieve it with css, just apply `display: none` to `.nav-tabs`

Example - https://stackblitz.com/edit/angular-e5er3u?file=app/basic.html

**Comment by manish-jain-1** [comment]
@IlyaSurmay Above solution hides entire tab component. Looking to hide only one of the tabs based on some condition. Any ideas how to achieve that?
