### ISSUE TITLE
The time of the datepicker is NOT zero,when chose the current Month's day.

### ISSUE THREAD

**Issue by AlphaIX** [valor-software/ngx-bootstrap#4157]
### Bug description or feature request:
The time of the datepicker is NOT zero,when chose the current Month's day.and the time seems like the initial time of the `datepicker` component.
---

### Plunker/StackBlitz that reproduces the issue:
an example:When I initial the `datepicker` in Mar,the date perhaps like this:`2018-03-31 15:37:02`,and then everyday of Mar you chosed may share the same time,for example,when you chose    `Mar 8`,you got this `2018-03-08 15:37:02`.this only occured in initial MONTH,in this situation,it was just in Mar,and in other month,It performed normally,such as `2018-04-13 00:00:00`,time is specified as 0

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:2.0.0-rc.0

Angular:5.0.0

Bootstrap:

**Comment by fralewsmi** [comment]
Adding onto this issue, selecting a date that **is not** the current date and then selecting a date that **is** the current date **will not** give the time, which means that two dates which appear equivalent in the datepicker are actually have different Date values. 
This is especially an issue when comparisons between two date pickers or a date range are used

**Comment by valorkin** [comment]
It's know issue, and written in roadmap.
Date comparison better to do with special method which allow to set precision level
Comparing dates as objects is  no good

**Comment by fralewsmi** [comment]
@valorkin let me know if I can help in any way with this issue, I'd be interested in contributing at some point in the future once I get some spare time :)

**Comment by valorkin** [comment]
most probably I did a mistake when was planning datepicker reducer
you can debug datepicker and point me to a code line, where time is reseted

**Comment by antonsimola** [comment]
Even though this issue is closed, iI'mstill experiencing this issue in 2.0.5. Time is not zero when choosing current month days. It is not the current time either, it is the time the component was initialized or something like that.

**Comment by davyvanlaere** [comment]
Just noticed that when selecting dates with the datepicker, a time is returned. The datepicker only deals with date. In my opinion, it should always return a zero value for time.

**Comment by just4anu** [comment]
Any update on solving why time is returned when selecting a date in datepicker.

**Comment by vuhi** [comment]
still experience this issue in the newest ngx bootstrap!
