### ISSUE TITLE
How to add new locale: Romanian?

### ISSUE THREAD

**Issue by mrjohnr** [valor-software/ngx-bootstrap#4158]
Hi.It is possible to add a new new locale: Romanian? I need it for Datepicker
curently I've edited fr.js and I've changed  months and weekdaysShort

> export var frLocale = {
> ....
>     months: 'Ianuarie_Februarie_Martie_Aprilie_Mai_Iunie_Iulie_August_Septembrie_Octombrie_Noiembrie_Decembrie'
>     weekdaysShort: 'Du_Lu_Ma_Mi_Jo_Vi_Sa'.split('_'),
> ....
> 

thanks

**Comment by IlyaSurmay** [comment]
Add a new file with the locale, test it and create a PR
PR example - #3514

**Comment by valorkin** [comment]
PR is merged, but it will be update cuz it's not 1 to 1 with moment.js
