### ISSUE TITLE
Carousel - Control Prev & Next

### ISSUE THREAD

**Issue by marcocoelho** [valor-software/ngx-bootstrap#4162]
Is it possible to generate Prev and Next directly in HTML without being generated by the component?

Another question is about adjusting Next and Prev through the CSS of the component.
I have a css file with the properties, how do you have to get the prev and next buttons.
More does not take the styles. Is there any way to be done?

**Comment by IlyaSurmay** [comment]
ngx-bootstrap doesn't support custom templates for carousel
you can customize the look of buttons from component's CSS via `::ng-deep` like this
```
::ng-deep .carousel-control-prev, ::ng-deep .carousel-control-next {
      background-color: white;
    }
```

example - https://stackblitz.com/edit/angular-cf1qk6?file=app%2Fbasic.ts

**Comment by filipemansano** [comment]
Example to change only the icon

::ng-deep .carousel-control-next-icon, ::ng-deep .carousel-control-prev-icon {
    background-image: none;
    font-family: 'Font Awesome 5 Free';
    font-weight: 900;
    color: #005598;
}

::ng-deep .carousel-control-prev-icon::before{
    content: "\f104";
}

::ng-deep .carousel-control-next-icon::before{
    content: "\f105";
}

**Comment by hasithak** [comment]
HI,
I am asking this again. Is it possible to generate Prev and Next directly in HTML without being generated by the component?

**Comment by zigang93** [comment]
yeah.. I need add onclick event on prev and next button.. how to do that?

**Comment by RounakDas123** [comment]
Hi I want to know how to shift the position of the prev button towards the left and the next button towards the right??
