### ISSUE TITLE
docs(tabs): add aria-attributes description

### ISSUE THREAD

**Issue by tarusin** [valor-software/ngx-bootstrap#4168]
Add `accessibility` section to`tabs` component. In this section need to add description:
1) what kind aria-attributes and roles you need to use:
- `role= "tablist"`
- `role= "tab"`
- `role= "tabpanel"`
- `aria-controls`
- `aria-selected`
- `aria-labelledby`
2) how you can use them.

**Comment by tarusin** [comment]
effort1: easy(hours)

**Comment by ajpgross** [comment]
Would it be possible to see an example implementation? The anchor element that controls tab switching does not seem to be easily accessible in order to add the necessary "role", "aria-controls", and "aria-selected" attributes. @tarusin @svetoldo4444ka
