### ISSUE TITLE
using wildcard for angular2 peer dependencies

### ISSUE THREAD

**Issue by brosenberger** [valor-software/ngx-bootstrap#417]
currently updating angular2 is not possible (current version beta15) as ng2-bootstrap has the dependency only to beta14.

suggestion:
change 
"peerDependencies": {
    "angular2": "2.0.0-beta.14"
  },
using ~ or ^ for the version in order to make it independantly of the host

**Comment by valorkin** [comment]
ya ya, I know
as soon as angular2 will get out from beta and will not push breaking changes with prerelease versions
