### ISSUE TITLE
Add guide to set bootstrap theme manually

### ISSUE THREAD

**Issue by envil** [valor-software/ngx-bootstrap#4186]
### Bug description or feature request:
The detect bootstrap version util is not reliable, it failed for my project. It took me half a day to realize that I manually can set the version of the bootstrap in the landing component. So maybe we should mention that important information into the installing/setting up guide?

### Plunker/StackBlitz that reproduces the issue:
I cannot reproduce the issue of the failing of the `_guessBsVersion()` function. The project is too complicated so it's too difficult to determine what caused the `_guessBsVersion()` function to fail.

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 2.0.3

Angular: 4.4.6

Bootstrap: 3.3.7

**Comment by envil** [comment]
#4187

**Comment by smiper** [comment]
We experienced the issue with _guessBsVersion() when we had the app-root absolutely positioned to top:0. The function returned bs4 in a bs3 based project. Removed the (unnecessary) positioning and everything started working again.

**Comment by valorkin** [comment]
It's written on the first page of docs actually
https://valor-software.com/ngx-bootstrap/#/getting-started
