### ISSUE TITLE
StackBlitz fails with ngx-bootstrap >2.0.0

### ISSUE THREAD

**Issue by ashley-hunter** [valor-software/ngx-bootstrap#4208]
Since v2.0.0 and higher I cannot use ngx-bootstrap within StackBlitz. I believe this issue is being caused by TypeScript being added as a peer dependency which didn't seem to be there in v1.x.x:

https://unpkg.com/ngx-bootstrap@2.0.3/package.json

- To repro go to the suggested StackBlitz environment: https://stackblitz.com/edit/ngx-bootstrap
- Remove the ngx-bootstrap dependency
- Add a dependency on ngx-bootstrap@2.0.3
- It will prompt you to install TypeScript - doing so will cause the Installing Dependency prompt to spin indefinitely

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.3

Angular: 5.2.9

Bootstrap: 3.3.7

**Comment by ludmilanesvitiy** [comment]
![peek 2018-12-07 13-54](https://user-images.githubusercontent.com/18209841/49646434-adb83800-fa27-11e8-9ced-ba89adc2e48c.gif)
Not Reproducible anymore
