### ISSUE TITLE
unable to set attribute dynamically for ngx-bootstrap datepicker

### ISSUE THREAD

**Issue by yyimam** [valor-software/ngx-bootstrap#4216]
If i am understand right so we need to use attribute "bsDatepicker" in input Element for ngx-bootstrap datepicker. so I want to set its attribute dynamically.

for achieving it i am using [attr.bsDatepicker]="bsDatepicker" but it set attribute in lowercase so datepicker is not working.

![image](https://user-images.githubusercontent.com/26085699/38717180-9ccbf688-3efe-11e8-9beb-139eb736e145.png)

I also tried javascript setAttribute but got same result here is the code

```
isInputElement(elem: HTMLElement | null): elem is HTMLInputElement {
     if (!elem) {
      // null
        return false;
     }
  return (elem.tagName === 'INPUT')
}

setAttribute(id: any ){ 
const elem = document.getElementById(id);
console.log(elem);
if (this.isInputElement(elem)) {
  var att = document.createAttribute("bsDatepicker"); 
  att.value = "bsDatepicker";
  elem.setAttributeNode(att);
  console.log(elem);
} 
}
```

Is there any other way to use datepicker or can i set attribute in camel-case dynamically as ngx-bootstrap datepicker required attribute "bsDatepicker".

**Comment by valorkin** [comment]
It's question not about datepicker, it's about angular. You cant simply by adding attributes add dynamic components. But you can use 2 ng template, with and without datepicker - easy way.
Hard way to write a service to dynamically inject datepicker
