### ISSUE TITLE
Empty Popover being shown when no contents are present 

### ISSUE THREAD

**Issue by coderundebug12** [valor-software/ngx-bootstrap#4227]
<ng-template #popTemplate>
    <div *ngIf="limitAmountinfo.errors == undefined">{{limitAmount}}</div>
    <div *ngIf="limitAmountinfo.errors?.required"><i class="error_icon"></i>Mandatory Field</div>
    <div *ngIf="limitAmountinfo.errors?.Decimal"><i class="error_icon"></i>Decimal Error</div>
    <div *ngIf="limitAmountinfo.errors?.maxlength"><i class="error_icon"></i>Number Length Error</div>
    <div *ngIf="limitAmountinfo.errors?.MKB"><i class="error_icon"></i>Multiplier Error</div>
  </ng-template>
<label for="limiter" [popover]="popTemplate" placement="right" triggers="blur" [isOpen]="visibleControl.limitAmount" (click)="showPopver('limitAmount')">
  <input id="limiter" 
        class="limiter" 
        autocomplete="off"  
        type="text" 
        name="limitAmount" 
        [popover]="limitAmount" 
        placement="right"
        triggers="mouseenter:mouseleave"
        [(ngModel)]="limitAmount" 
        [ngModelOptions]="{updateOn: 'blur'}" 
        appDecimalValidator 
        appMultiplierValidator 
        appNumberLength 
        appFormatNumber 
        required 
        #limitAmountinfo="ngModel">
  </label>

**Comment by valorkin** [comment]
Pop over is not empty cuz value is set ( ngTemplate ref), popover can't see a context and should not.
What I see here, that I should add isDisabled for popovers.

As for this issues, it works as expected
