### ISSUE TITLE
In Bootstrap 4, use Font Awesome in Rating component

### ISSUE THREAD

**Issue by hongbo-miao** [valor-software/ngx-bootstrap#423]
Just a suggestion, in Bootstrap 4, maybe switch to [Font Awesome](https://fortawesome.github.io/Font-Awesome/) for `Rating` component by default?

Or somehow provide a way to let developer choose? Thanks

**Comment by Hongbo-Miao** [comment]
@valorkin [this](https://css-tricks.com/star-ratings/) may help you. This way, no need rely on Font Awesome and Glyphicons.
Because they are just ☆ and ★.

**Comment by Slavrix** [comment]
Not just rating component, datepicker and several others all use glyphicons which aren't included with bootstrap 4.

**Comment by jprinaldi** [comment]
Removable tabs use Glyphicons as well. I'm resorting to Font Awesome on my local copy.

Has any decision been made regarding this matter?

**Comment by valorkin** [comment]
Font Awesome will be used only for BS3 templates
after new datepicker I will provide a better way of templates segregation

**Comment by mlybrand** [comment]
for Rating, you could provide a hook for icon prefix. defaults to glyphicon, but you could set it to fa or opticon or whatever...

**Comment by mlybrand** [comment]
Let me know if you would accept a PR and what you would like to see as a minimum (documentation, test coverage, etc), assuming you would be willing to accept a PR.

**Comment by valorkin** [comment]
fixed :D
