### ISSUE TITLE
Add dateDisabled feature from old date picker to the new date picker

### ISSUE THREAD

**Issue by will-l-h** [valor-software/ngx-bootstrap#4234]
### Bug description or feature request:
I'm not sure why #3418 was closed; it's the same feature (specifying an array of disabled dates) I'm looking for but it isn't implemented in the new datepicker, only in the old one.

**Comment by yomiex** [comment]
@valorkin any status on this?

**Comment by shiwer** [comment]
Actually no, we decided to move to the material library to handle this.
Material also handle ReactiveFormControl, min/max and specific disabled
date, also languages which I found much more handy than for ngx but clearly
doable.

2018-05-05 15:40 GMT+02:00 yomiex <notifications@github.com>:

**Comment by valorkin** [comment]
PR created, we are working on it

**Comment by valorkin** [comment]
Closing as duplicate
