### ISSUE TITLE
Datepicker not setting date

### ISSUE THREAD

**Issue by louisscruz** [valor-software/ngx-bootstrap#424]
On the demo page, the date picker fails to actually set the date. I've tried incorporating it in my own project, and it seems that the problem lies at the `daypicker` level. The date picker successfully sets the year and month, but the day just won't catch. Is there something that I'm missing? Assuming that this is a bug, I'm going to take a look in the next few days and hopefully find a solution.

**Comment by valorkin** [comment]
Thanks in advance :)
You can check latest commits to datepicker (in change log)

**Comment by louisscruz** [comment]
I've taken a look and messed around for a while, but can't seem to find the problem yet. It seems that every function that sets the `activeDate` is doing so appropriately. I must have some misunderstanding about the relationship between `datepicker` and `datepicker-inner`. I can take another look in the next few days, but I'm not so hopeful about fixing this.

**Comment by valorkin** [comment]
May be you can write a failing test case?
Then it will be really fast to fix

**Comment by edinfazlic** [comment]
I think I can help you really fast if you just write the test case :) I am using datepicker in my project, focusing specially on daypicker, and it works fine. It would be really good to remove some not so obvious bugs.

**Comment by louisscruz** [comment]
Here's a quick test case:

### Scenario

Date picker does not set set the value of the date (day of month) when in the `'year'` date picker mode.

### Prerequisite

Use of the date picker directive in the view is as follows:

```
<div style="min-height:290px;">
    <datepicker [(ngModel)]="dateValue" [showWeeks]="false" [datepickerMode]="'year'"></datepicker>
</div>
{{dateValue}}
```

### Steps
1. Select a year (ex. 2017)
   
   Resulting `dateValue`: Sun Jan 01 2017 00:00:00 GMT-0500 (EST)
2. Select a month (ex. March)
   
   Resulting `dateValue`: Wed Mar 01 2017 00:00:00 GMT-0500 (EST)
3. Select a date/day of the month (ex. 15)
   
   Resulting `dateValue`: **Wed Mar 01 2017 00:00:00 GMT-0500 (EST)**

### Expected Result

The expected resulting value for `dateValue` was **Wed Mar 15 2017 00:00:00 GMT-0500 (EST)**

### Comments

There aren't any logged errors. The `onUpdate(event)` and `writeValue(value)` functions appear to be called appropriately when logging the values to the console.

**Comment by CarlCui-AI** [comment]
Same issue. Also, I think it would be very useful if API provides an output binding when a date is selected.

**EDIT**

I was using 1.0.11. Issue was fixed after that.

**Comment by valorkin** [comment]
Thanks for updating on issue!
