### ISSUE TITLE
Change of slide in carousel loses pause on hover setting

### ISSUE THREAD

**Issue by twclarkee** [valor-software/ngx-bootstrap#4243]
When using the carousel component with [onPause] set to false, the carousel correctly pauses when hovered over but when a slide is changed using the next/prev buttons or the indicators this property is reset and the carousel starts to play again until you move your mouse off the carousel and back over it again.

Is there a way to avoid this or keep "isPlyaing" false when clicking through the slide?

FYI Versions of ngx-bootstrap and Angular being used:
ngx-bootstrap: 2.0.3
Angular: 5

**Comment by llysenko** [comment]
Please provide a reproduction via stackblitz

Starter templates:
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts
