### ISSUE TITLE
How to centre ngx date picker in mobile version ?

### ISSUE THREAD

**Issue by jeevanjyothi123** [valor-software/ngx-bootstrap#4245]
In my div I have one div inside that I have two date picker but the issue I am facing is both the date picker is going out of the div when clicking on it.I have given margin-left:8% for mobile version its working fine for one date picker but for other its going more left because the class is same and the class is ngx date picker class that class I am not able to change and also the inline CSS of ngx date picker.

{position: absolute; display: block; top: 131px; left: 49px;} alreday present in inline This thing I am not able to solve .

**Comment by IlyaSurmay** [comment]
Could you provide a reproduction of this issue?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by ghost** [comment]
This issue is still present with latest version. Please see below stackblitz link to reproduce the issue:
https://ngx-bootstrap-pcns6w.stackblitz.io

**Comment by thaboambrose** [comment]
Yes this issue is still there, is it affected by some other parent styles maybe?

**Comment by thaboambrose** [comment]
I see why, it happens when you set a manual width to the date picker input
