### ISSUE TITLE
Selenium Testing - datePicker and timePicker doesn't trigger "onChange" method on value change

### ISSUE THREAD

**Issue by aemmeemme** [valor-software/ngx-bootstrap#4249]
While testing a website using Selenium IDE for Chrome the **datePicker** and **timePicker** fields, once the value is set, doesn't trigger the "onChange" method.
I need to trigger the "onChange" method to validate the fields content.

I've tried to change the value in the fields using both the "**sendKeys**" (sending each character one by one) method and the "**type**" (sending the whole string).

I've tried to do that by clicking on the field before to insert the values and clicking on another field after the typing: the result is the same.

I've tried either to simulate the key-down event of the "tab" key: same result.

_Used versions:
Angular: 4.4.6
ngx-bootstrap: 2.0.3
bootstrap: 3.3.7
jQuery: 3.2.1_

**Comment by sharma-sahil** [comment]
I am also facing the same problem. Is there any solution for this?

**Comment by ludmilanesvitiy** [comment]
@aemmeemme @sharma-sahil After "sendKeys" to the input field, you need to trigger "Enter", in that case your value will be added to the datepicker. Just one note: if the value correct - date will be shown, if no - shown "Invalid date". See examples here https://github.com/valor-software/ngx-bootstrap/pull/4951 - (it's implemented with Cypress, but with Selenium would be similar behaviour)
