### ISSUE TITLE
Typeahead - can't clear input field on select

### ISSUE THREAD

**Issue by Celebes** [valor-software/ngx-bootstrap#425]
I am using async example from showcase. I've set:

```
<input [(ngModel)]="asyncSelected" (typeaheadOnSelect)="asyncSelected = null" ...>
```

and selecting something doesn't clear the input.

**Comment by Gabriel0402** [comment]
+1. And it seems that the ngmodel is bind to the matches, there's no way to clear the text in input

**Comment by Gabriel0402** [comment]
I have a workaround for this situation. Inside changeModel function, we can set valueStr to '' to clear the input box.

**Comment by webdev48** [comment]
@Gabriel0402 can you show what do you mean by changeModel ? I really need it badly

**Comment by Gabriel0402** [comment]
@webdev48 there's a changeModel function inside typeahead directive, change valueStr to '' to clean the input box

**Comment by webdev48** [comment]
can you please tell me the the markup ?

```
<input [(ngModel)]="selected"
           [typeahead]="moduleNames"
           (typeaheadOnSelect)="typeaheadOnSelect($event);"
           [typeaheadOptionField]="'name'"
           (changeModel)="onChange($event)"
           class="form-control">
```

is this okay ? 

and in component 

```
onChange(val){
   val = " ";
}
```

or is it something different ?

**Comment by Gabriel0402** [comment]
no, the workaround is to change the source code.

**Comment by webdev48** [comment]
=| how ? can you guide me please or tell me the code that worked for you ?

**Comment by Gabriel0402** [comment]
actually I copied the src folder from this repo and put it into my src folder and reference the component as usual way.

**Comment by RolfVeinoeSorensen** [comment]
It would be nice to get a fix for this.

**Comment by EmptyCoffin** [comment]
It would indeed

**Comment by selfinterest** [comment]
+1

**Comment by valorkin** [comment]
mm, best way is (ngModelChange)="$event.target.value = ''"

**Comment by IlyaSurmay** [comment]
Also you can get reference to input field via `ViewChild` and clear its value when typeaheadOnSelect is triggered
