### ISSUE TITLE
Tooltip not working on Tab when focused

### ISSUE THREAD

**Issue by mkrishna4u** [valor-software/ngx-bootstrap#4255]
I was trying to put tooltip on tab but not able to put that can be displayed when i focus the tab by tabbing the keyboard. There is a Anchor (<a>) element that is focused but i want that anchor element should have tooltip. We should allow to pass tooltip using <tab> element or any other way so that the tooltip can be displayed when the tab is focused.

The following code does not work when we focus tab by pressing tab key.
```
<tabset>
    <tab>
      <ng-template tabHeading>
        <span tooltip="tooltip text">tooltip here</span>
      </ng-template>
     asasas
    </tab>
  </tabset>
```

Please do these changes and let me know if you need any help.
My suggestion is to pass tooltip params from the <tab> element as @Input param like.
`<tab tabTooltip="AAA" tabTooltipLocation="bottom"></tab>`

Also when we are generating code then anchor <a> element should have aria-label="tabTooltip contents"

Thanks

**Comment by valorkin** [comment]
I remember some crap with spans, try to add tabindex to it
