### ISSUE TITLE
bsDatepicker: How to set first day of week to Monday

### ISSUE THREAD

**Issue by igasparetto** [valor-software/ngx-bootstrap#4269]
I can see many issues open and closed about the matter, but no example around.

Thanks

**Comment by 7185** [comment]
You probably want to use a locale.
See [the documentation](https://valor-software.com/ngx-bootstrap/#/datepicker#locales) for an example

**Comment by igasparetto** [comment]
I only want to change the first day to Monday. Do I have to use the entire locale?

**Comment by igasparetto** [comment]
Done here. Thanks

**Comment by userAbhi** [comment]
You can do this by changing dow:0 to dow:1 in
ngx-bootstrap\chronos\locale\locale.defaults.js. in file.

eg:
export var defaultLocaleWeek = {
//dow: 0
dow: 1,
// Sunday is the first day of the week.
doy: 6 // The week that contains Jan 1st is the first week of the year.
};

**Comment by ameyraut23** [comment]
> You can do this by changing dow:0 to dow:1 in
> ngx-bootstrap\chronos\locale\locale.defaults.js. in file.
> 
> eg:
> export var defaultLocaleWeek = {
> //dow: 0
> dow: 1,
> // Sunday is the first day of the week.
> doy: 6 // The week that contains Jan 1st is the first week of the year.
> };

But after we do a npm install the changes would be overridden, could you please let us know the code configuration, so it wont be replaced on build .
thanks in advance !!
