### ISSUE TITLE
bsDatepicker: Is it possible to keep showing the calendar after a date is selected?

### ISSUE THREAD

**Issue by abbymrs** [valor-software/ngx-bootstrap#4277]
Hi,

Is it possible to keep showing the calendar by making some configs in the component after the user selects a day/date? Thanks.

**Comment by tomaskumpikas** [comment]
More less the same question:- is it possible to open calendar (datepicker) not in a popup window, but as always shown calendar in div?

**Comment by valorkin** [comment]
Inline datepicker version is in PR and will land soon.
You can add onHide event listener and trigger show() method.
There are no way to prevent closing datepicker

But I will think about it, could be added later

**Comment by izikf89** [comment]
i do what valorkin write and is work fine but i must add show() function in setTimeout() like: 
`    setTimeout(() => {        
      this.dataPicker.show()
    }, 0);`
