### ISSUE TITLE
tab does not hide

### ISSUE THREAD

**Issue by dolphinsd** [valor-software/ngx-bootstrap#4278]
when using [hidden]="true" tab content is hidden but tab heading is not

**Comment by ebicoglu** [comment]
this is the topic
https://forum.aspnetboilerplate.com/viewtopic.php?f=5&t=11180&sid=987e8e47390fd2a536beb1f4c991376a

**Comment by valorkin** [comment]
Hidden true is a hide by css actually, via attr selector.
You can provide custom html template for tab heading, and hide it in same way.

As a note:
- current tabs implementation is an old crap, and it will be rewritten :)
- you can disable or remove tabs
