### ISSUE TITLE
Ellipses in Pagination

### ISSUE THREAD

**Issue by sga-girdhari** [valor-software/ngx-bootstrap#4286]
Do we have any option to show ellipses in pagination?

Right now we have `maxSize` option which will control how many page link you want to show, if you don't provide any `maxSize` it will show all page links.

**Comment by valorkin** [comment]
It's seems logical.
Can you provide a sample as a separate feat request issue

**Comment by sga-girdhari** [comment]
Sure

**Comment by praveenbalajis** [comment]
hi is there any feature implemented to show the ellipses?
