### ISSUE TITLE
Backdrop enable 

### ISSUE THREAD

**Issue by sraveen123** [valor-software/ngx-bootstrap#4288]
I need to do my work in background though modal is open for this,  I have done changes in our global css.

```
.modal-backdrop {
  display: none;
}

.modal-open .modal {
  width: 300px;
  margin: 0 auto;
}
```
 
but I want to effect this to particular modals not to all. Do we have any feature for this, instead of applying styles on global  ?

**Comment by valorkin** [comment]
you can actually disable backdrop via options of `show` method
https://valor-software.com/ngx-bootstrap/#/modals#service-disable-backdrop

**Comment by sraveen123** [comment]
@valorkin any help from your side  ?
