### ISSUE TITLE
NPM update version to 2.0.4

### ISSUE THREAD

**Issue by jfernandeze** [valor-software/ngx-bootstrap#4289]
Hi

If you try to install de new version of ngx-bootstrap the npm.org donwload de version 2.0.3:

if you try `npm i ngx-bootstrap@2.0.4`  the npm donwload de version 2.0.3, in fact https://registry.npmjs.org/ngx-bootstrap/-/ngx-bootstrap-2.0.4.tgz has de version 2.0.3 too

jose

**Comment by valorkin** [comment]
I am afraid it's npm issue. PS latest version is 2.0.5
And v3 will be released today
