### ISSUE TITLE
bug(typeahead): Different HTML in MacOS

### ISSUE THREAD

**Issue by SidekickJohn** [valor-software/ngx-bootstrap#4306]
Hi, <br/>
we are using ngx-bootstrap in version 1.9.3 (update to newer version is planned). 
I recognized the HTML that is rendered is different between Windows and MacOS. And I want to know: Is this a feature or a bug??<br/>
When opening the typeahead "dropdown" in Chrome Browser (66.0) under Windows the following HTML is rendered. <br/>

    <typeahead-container class="dropdown open" style="position: absolute; display: block; top: 26px; left: 6px;">
      <ul class="dropdown-menu">
        <li class="active">
            <a href="#" tabindex="-1">
              <h5 _ngcontent-c11="">bla bla bla<br><span>Blablabla</span></h5>            
            </a>
          </li>  
      </ul>
    </typeahead-container>

When the same component is opened in Chrome Browser (66.0) under MacOS (10.13.4) the HTML differs. It's not an unordered list with items anymore. Instead it's: <br/>

    <typeahead-container class="dropdown open" style="position: absolute; display: block; top: 26px; left: 6px;">
      <button class="dropdown-item active">
        <h5 _ngcontent-c11="">bla bla bla<br><span>Blablabla</span></h5>
      </button>
    </typeahead-container>

Question-Time: Is this a Bug or a Feature?

**Comment by valorkin** [comment]
It's a bug most probably, but 1.9.4 will not fixed for sure. If you will be able to reproduce this issue with lates ngx bs version please drop me a note.
PS could not reproduce it locally
