### ISSUE TITLE
Timepicker arrows not hiding

### ISSUE THREAD

**Issue by roblawford** [valor-software/ngx-bootstrap#4307]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Bug description or feature request:
Bug

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.4

Angular: 5.2.3

Bootstrap:  4

### Build system: Angular CLI, System.js, webpack, starter seed:

Angular CLI

When i add a timepicker with the options [arrowkeys]="false" this has no impact on the component and does not work as expected. I would like not to see the arrows there at all if set to false.

Thanks.

**Comment by dayesouza** [comment]
I saw here (https://github.com/valor-software/ngx-bootstrap/issues/1672) that if you put 
`.hidden { display: none; }` 
on the css it will hide and I guess it's the only way for now

**Comment by valorkin** [comment]
It's a bug, sorry
Gonna fix it 

Link for me: https://valor-software.com/ngx-bootstrap/#/timepicker#arrow%20keys

**Comment by tarusin** [comment]
@roblawford there are no bugs in this demo.
In this demo, we can disable/enable changing the values of hours and minutes using the up/down arrow keys on the keyboard.

**Comment by tarusin** [comment]
@roblawford 
if you want to use a demo with arrows that can be hidden, you can use this https://valor-software.com/ngx-bootstrap/#/timepicker#spinners
