### ISSUE TITLE
ngx bootstrap error with Angular -v6.0.0 and rxjs -v6.0.0

### ISSUE THREAD

**Issue by javsal** [valor-software/ngx-bootstrap#4308]
package.json looks like following: 

```
"dependencies": {
    "@angular/animations": "6.0.0",
    "@angular/common": "6.0.0",
    "@angular/compiler": "6.0.0",
    "@angular/core": "6.0.0",
    "@angular/forms": "6.0.0",
    "@angular/http": "6.0.0",
    "@angular/platform-browser": "6.0.0",
    "@angular/platform-browser-dynamic": "6.0.0",
    "@angular/router": "6.0.0",
    "ngx-bootstrap": "2.0.5",
    "ngx-uploader": "4.2.4",
    "core-js": "2.5.4",
    "rxjs": "6.0.0",
    "zone.js": "0.8.26",
    "@angular/upgrade": "6.0.0",
    "@nguniversal/express-engine": "6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "6.0.0"
  },
```

Errors: 

```
ERROR in ./node_modules/ngx-bootstrap/typeahead/typeahead.directive.js
Module not found: Error: Can't resolve 'rxjs/add/operator/debounceTime' in 
'/node_modules/ngx-bootstrap/typeahead'
ERROR in ./node_modules/ngx-bootstrap/datepicker/bs-datepicker.component.js
Module not found: Error: Can't resolve 'rxjs/add/operator/filter' 
in '/node_modules/ngx-bootstrap/datepicker'
ERROR in ./node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.effects.js
Module not found: Error: Can't resolve 'rxjs/add/operator/filter'
 in '/node_modules/ngx-bootstrap/datepicker/reducer'
ERROR in ./node_modules/ngx-bootstrap/dropdown/bs-dropdown.directive.js
Module not found: Error: Can't resolve 'rxjs/add/operator/filter' in 
'/node_modules/ngx-bootstrap/dropdown'
ERROR in ./node_modules/ngx-bootstrap/typeahead/typeahead.directive.js
Module not found: Error: Can't resolve 'rxjs/add/operator/filter' in 
'/node_modules/ngx-bootstrap/typeahead'
ERROR in ./node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.effects.js
Module not found: Error: Can't resolve 'rxjs/add/operator/map'
 in '/node_modules/ngx-bootstrap/datepicker/reducer'
ERROR in ./node_modules/ngx-bootstrap/typeahead/typeahead.directive.js
Module not found: Error: Can't resolve 'rxjs/add/operator/map' 
in '/node_modules/ngx-bootstrap/typeahead'
```
Node: 8.11.1,
OS: Ubuntu 16.04,
AngularCLI: 6.0.0

**Comment by rysilva** [comment]
rxjs v6 has several breaking changes including simplifying import points for operators.  Try installing `rxjs-compat`, which adds back those import paths until the code has been migrated. 

I'm not a maintainer of this project though so I don't know if ngx-bootstrap will otherwise work with Angular 6.

**Comment by javsal** [comment]
@rysilva You have just rescued me.

**Comment by itbrandonsilva** [comment]
Seems there have been multiple issues posted in relation to RXJS6 breaking changes, already. Hoping to learn if there are any existing plans on moving toward RXJS6. Happy to help, if needed.

**Comment by rkusuma** [comment]
https://github.com/valor-software/ngx-bootstrap/tree/ngv6
already have branch for angular v6. coming soon.

**Comment by loveneetchahal** [comment]
npm install rxjs@6 rxjs-compat@6 --save

**Comment by valorkin** [comment]
Ngx bootstrap v3 is ready to go, today I will fix cypress e2e tests at ci and we are publishing

**Comment by PhotoPaul** [comment]
So for those of us who have run "npm install rxjs@6 rxjs-compat@6 --save", do we need to take extra steps to remove it when ngx bootstrap starts working with rxjs 6?

**Comment by BrouWilliam** [comment]
Uninstall the Node.js in Panel Control of Windws and Delete the pasta

C:\Users\Youuser\AppData\Roaming\npm-cache

After install the Node.js

**Comment by nimatrazmjo** [comment]
Hey guys I have the same probelm. Can anyone tell me what am I doing wrong ?

```

node --max_old_space_size=5048 ./node_modules/@angular/cli/bin/ng run jobsaf-website:server && webpack --config webpack.server.config.js --progress --colors

                                                                                         
Date: 2018-11-13T10:07:53.036Z
Hash: 95020ba2ac26a1552fc0
Time: 172662ms
chunk {main} main.js, main.js.map (main) 18.5 MB [entry] [rendered]

ERROR in ./src/app/app.server.module.ngfactory.js
Module not found: Error: Can't resolve 'ngx-bootstrap/dropdown/bs-dropdown.module' in '/home/razmjo/workstation/jobsaf-website/src/app'
ERROR in ./src/app/admin/routes/routes.module.ngfactory.js
Module not found: Error: Can't resolve 'ngx-bootstrap/dropdown/bs-dropdown.module' in '/home/razmjo/workstation/jobsaf-website/src/app/admin/routes'
ERROR in ./src/app/admin/routes/bank-accounts/bank-account.module.ngfactory.js
Module not found: Error: Can't resolve 'ngx-bootstrap/dropdown/bs-dropdown.module' in '/home/razmjo/workstation/jobsaf-website/src/app/admin/routes/bank-accounts'
```

**Comment by rhari008** [comment]
> Hey guys I have the same probelm. Can anyone tell me what am I doing wrong ?
> 
> ```
> 
> node --max_old_space_size=5048 ./node_modules/@angular/cli/bin/ng run jobsaf-website:server && webpack --config webpack.server.config.js --progress --colors
> 
>                                                                                          
> Date: 2018-11-13T10:07:53.036Z
> Hash: 95020ba2ac26a1552fc0
> Time: 172662ms
> chunk {main} main.js, main.js.map (main) 18.5 MB [entry] [rendered]
> 
> ERROR in ./src/app/app.server.module.ngfactory.js
> Module not found: Error: Can't resolve 'ngx-bootstrap/dropdown/bs-dropdown.module' in '/home/razmjo/workstation/jobsaf-website/src/app'
> ERROR in ./src/app/admin/routes/routes.module.ngfactory.js
> Module not found: Error: Can't resolve 'ngx-bootstrap/dropdown/bs-dropdown.module' in '/home/razmjo/workstation/jobsaf-website/src/app/admin/routes'
> ERROR in ./src/app/admin/routes/bank-accounts/bank-account.module.ngfactory.js
> Module not found: Error: Can't resolve 'ngx-bootstrap/dropdown/bs-dropdown.module' in '/home/razmjo/workstation/jobsaf-website/src/app/admin/routes/bank-accounts'
> ```

Did you happen to resolve this issue?

**Comment by valorkin** [comment]
Don't use deep imports, use imports like in documentation
Plus in v3.1+ we refactored bundling process

**Comment by hg5734** [comment]
@valorkin  I'm also facing this issue. 
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'ngx-bootstrap/dropdown/bs-dropdown.module'

Could you please help me ?
i'm not using even that import but during --prod build this issue is coming

**Comment by Krishna2107** [comment]
@hg5734 Am also facing same issue.

ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'ngx-bootstrap/dropdown/bs-dropdown.module'

Could you please help me ?
i'm not using even that import but during --prod build this issue is coming

**Comment by default-writer** [comment]
https://stackoverflow.com/questions/54529027/node-modules-rxjs-internal-types-d-ts81-44-error-ts1005-expected-error-a
