### ISSUE TITLE
Unable to access opened modal when injecting through template ref

### ISSUE THREAD

**Issue by saikiriti11** [valor-software/ngx-bootstrap#4311]
We are unable to access the opened modal when passing the bsmodal as template ref instead of the component. Below is the plunker link
https://plnkr.co/edit/F36mQTLfaE0bSuuMJpUx?p=preview
We have a work around to pass the modal reference as Input variable to the component but we dont want to go that route. Can we acheive this by injecting the reference as in the below case.
https://plnkr.co/edit/j3DS1VTyV0TW92D5o4vA?p=preview

**Comment by Domainv** [comment]
close as outdated
