### ISSUE TITLE
Alert not respecting changes to input properties

### ISSUE THREAD

**Issue by dricha** [valor-software/ngx-bootstrap#441]
All of the logic for binding the alert properties to the markup are only bound on ngOnInit. When they change the underlying markup isn't changed.

For example, if I have a component like this:

``` js
@Component({
  template: '<alert [type]="alertType">{{alertMsg}}</alert>',
  directives: [Alert]
})
export class Example {
  public alertType: string = 'info';
  constructor(zone: NgZone) {
    setTimeout(() => {
      // some async code
      zone.run(() => {
        this.alertType = 'warning';
      });
    }, 5000);
  }
}
```

The alert will not change from blue to green. This makes it hard when you have a singleton instance of the alert that you are just showing/hiding and updating, instead of an array.

**Comment by valorkin** [comment]
should be working fine now
