### ISSUE TITLE
Can't apply css to Tabs

### ISSUE THREAD

**Issue by anhtranqs3** [valor-software/ngx-bootstrap#443]
I have custom css rules for tabs, tab handles and tab panes inside components.
Since I can't add class to `<ul>, <li>, <a>, <div class="tab-pane">`, I used external css file for that component.

Unfortunately,  `<ul>, <li>, <a>, <div class="tab-pane">` which is generated by directive doesn't apply the rules since the rules were added some kind of custom attribute generated by Angular due to simulate the shadow dom, but above generated doms.

Please give me any solution for these.

**Comment by lanocturne** [comment]
+1

**Comment by johanchouquet** [comment]
Same issue for me, but for Typeahead component

**Comment by katestearns-suplari** [comment]
What was the solution for this? I am trying to do the same - add css to the tabs and am not succeeding

**Comment by smallswan399** [comment]
Cant add a custom class to the ul generated by ngx-bootstrap

**Comment by devfomichov** [comment]
Hi, @anhtranqs3cate ! My solution to the problem in this issue #1698
