### ISSUE TITLE
demo(pagination): add demo with list

### ISSUE THREAD

**Issue by kalpeshrajvir-virtueinfo** [valor-software/ngx-bootstrap#450]
I get the pagination working with PAGINATION_DIRECTIVES. Is there any sample that shows the list as well so, on change list gets changed in example/demo everything is fixed I want them to be dynamic.

**Comment by valorkin** [comment]
sorry, did not understood what do you really need

**Comment by kalpeshrajvir-virtueinfo** [comment]
@valorkin In this demo there is pager only shown so, I can move from one page to another page. I have listing as well. How I can bind it with the pager. so, when I move from one page to another page it change the listing too. Initially I tried it with below shown method.

https://github.com/michaelbromley/ng2-pagination

**Comment by valorkin** [comment]
OK, seems I got your point, more or less.
I will check it asap when I get back from ngconf

**Comment by kalpeshrajvir-virtueinfo** [comment]
@valorkin Do you have any update on this?

**Comment by valorkin** [comment]
Actually yes it is
no promises it will be soon,
but yes, I am planning to include non bootstrap core components
in this repo

**Comment by ludmilanesvitiy** [comment]
Closed as not actual anymore.
