### ISSUE TITLE
Readme Documentation Issue

### ISSUE THREAD

**Issue by danielle5** [valor-software/ngx-bootstrap#453]
I am trying to get the datepicker popup to work but I am confused, where can I seek assistance?

**Comment by valorkin** [comment]
datepicker pop up not yet implemented :)

**Comment by valorkin** [comment]
follow this for updates https://github.com/valor-software/ng2-bootstrap/issues/273

**Comment by danielle5** [comment]
@valorkin thank you for your (and others) help and your hard work on this. It is awesome to have people that help other learn and develop :)

**Comment by valorkin** [comment]
Thanks for kind words :)
