### ISSUE TITLE
System is not defined

### ISSUE THREAD

**Issue by NN77** [valor-software/ngx-bootstrap#460]
``` bash
shims.js?1461767721346:formatted:4639: Uncaught ReferenceError: System is not defined
```

Hi, do you have info when ng2-bootstrap will be ready for production build using system builder? On production SystemJS of course is missing because is not neccessary, but is required by ng2-bootstrap in registering bundled components.

**Comment by valorkin** [comment]
If you use `system.js` builder use common.js js files, not already bundled

**Comment by valorkin** [comment]
ReferenceError: System is not defined
this one means you forgot to add system.js files in html
this should help:
https://github.com/valor-software/angular2-quickstart
