### ISSUE TITLE
splitbutton compile error

### ISSUE THREAD

**Issue by DaSchTour** [valor-software/ngx-bootstrap#464]
Since beta.16 I get this compile error.

`node_modules/primeng/components/splitbutton/splitbutton.d.ts(4,18): error TS2305: Module '".../node_modules/angular2/router"' has no exported member 'Location'.`

**Comment by kevin-dsouza** [comment]
Please see;

http://forum.primefaces.org/viewtopic.php?f=35&t=45287

and

#260

In summary, upcoming beta4 adds support for angular2 beta16.

**Comment by valorkin** [comment]
hey, this issue has nothing to do with ng2-bootstrap :)
