### ISSUE TITLE
feat(rating): half star in Rating component

### ISSUE THREAD

**Issue by hongbo-miao** [valor-software/ngx-bootstrap#466]
In Bootstrap 4, if ng2-bootstrap Rating component [switches to Font Awesome](https://github.com/valor-software/ng2-bootstrap/issues/423), adding support for half star using [fa-star-half](http://fortawesome.github.io/Font-Awesome/icon/star-half/) will be great!

Thanks

**Comment by valorkin** [comment]
Nice idea, PR? :)

**Comment by hongbo-miao** [comment]
I really wish I can.. but my skills are not at that level.. :P

**Comment by perara** [comment]
+1

**Comment by IlyaSurmay** [comment]
Closing in favor of #1437

**Comment by arunshivar** [comment]
How to hide titles on hover on start itmes?
