### ISSUE TITLE
Mapping moment.js

### ISSUE THREAD

**Issue by achimha** [valor-software/ngx-bootstrap#473]
The library requires moment.js and you show how to map "moment" to the script URL using SystemJS.

In my setup, moment.js is already included as part of a combined "scripts.js" that has all external legacy JavaScript stuff rolled up into one file (using gulp).

How would I tell SystemJS/the library to not load moment.js because it's already there?

**Comment by DaSchTour** [comment]
Just use jspm to create the bundle including moment.js instead of gulp.

**Comment by achimha** [comment]
While I couldn't find it in the SystemJS documentation, I was pointed to this which solves the problem:

```
System.config({
   map: {
      moment: '@empty'
   }
})
```
