### ISSUE TITLE
tooltipHtml does't show any tooltip

### ISSUE THREAD

**Issue by theunreal** [valor-software/ngx-bootstrap#474]
`tooltipHtml="<b>Hello</b>"`
 does't show any tooltip (same happens in the demo)

Feature: when `tooltip=""`, don't show tooltip.

**Comment by michalstepien** [comment]
I see its not implemented.

**Comment by vmironovs** [comment]
> I see its not implemented.
this is implemented, but not in release 1.0.17.
need new release

**Comment by vmironovs** [comment]
not included in v1.0.17.
need new release

**Comment by valorkin** [comment]
published
