### ISSUE TITLE
Support Angular 2.0.0-rc.0 (2016-05-02)

### ISSUE THREAD

**Issue by RolfVeinoeSorensen** [valor-software/ngx-bootstrap#477]
Good news everyone!

Angular is now in RC0 and it would be awesome if this module could support it.

**Comment by ciriarte** [comment]
I have an open PR #481, and there's some progress on PR #472 as well.

**Comment by marcodelgatto** [comment]
We're looking forward for support to RC. Is there any forecast ?

**Comment by RolfVeinoeSorensen** [comment]
Thank you for fast delivery!
