### ISSUE TITLE
bug(rating): There is no directive with "exportAs" set to "index"

### ISSUE THREAD

**Issue by hongbo-miao** [valor-software/ngx-bootstrap#482]
After updating to version 1.0.15, RatingComponent does not work well, which works well before.
The code is like this, very simple:

```
import { Component } from 'angular2/core';
import { RatingComponent } from 'ng2-bootstrap/components/rating';

@Component({
  selector: 'home-component',
  directives: [RatingComponent],
  template: `
    <rating [(ngModel)]="rate" [max]="max"></rating>
  `
})
export class HomeComponent {
  max: number = 5;
  rate: number = 3;
}
```

When I load this page, I got error:

> EXCEPTION: Error: Uncaught (in promise): Template parse errors:
> There is no directive with "exportAs" set to "index" ("a-valuemax]="range.length" [attr.aria-valuenow]="value">
>       <template ngFor #r [ngForOf]="range" [ERROR ->]#index="index">
>         <span class="sr-only">({{ index < value ? '*' : ' ' }})</span>
>         <i (mo"): RatingComponent

**Comment by ciriarte** [comment]
This one is related to changes on angular 2.0.0-beta.17 and up. It should be fixed in a newer release. There's a couple of PRs pending #472, #481 (either one will do it) that should fix this issue.

**Comment by hongbo-miao** [comment]
@ciriarte thanks! Just realized this issue is similar too https://github.com/valor-software/ng2-bootstrap/issues/480
So can be closed together later.
