### ISSUE TITLE
CAROUSEL_DIRECTIVES: deprecate use of *ngFor="#slidez of slides", throws template parsing error in Angular2.0.0.beta.17

### ISSUE THREAD

**Issue by ydagana** [valor-software/ngx-bootstrap#484]
In Carousel Component 
`<ol class="carousel-indicators" *ngIf="slides.length > 1">
         <li [ERROR ->]*ngFor="#slidez of slides" [class.active]="slidez.active === true" (click)="select(slidez)"></li>`

We have deprecate use of #slidez, should be `let slidez of slides` instead.

**Comment by valorkin** [comment]
fixed with #481
