### ISSUE TITLE
New errors with RC.0

### ISSUE THREAD

**Issue by timfogarty1549** [valor-software/ngx-bootstrap#487]
compiling against angular2 rc 0 gives the following errors

node_modules/ng2-bootstrap/components/tabs/tab-heading.directive.d.ts(4,18): error TS2314: Generic type 'TemplateRef<C>' requires 1 type argument(s).
node_modules/ng2-bootstrap/components/tabs/tab-heading.directive.d.ts(5,30): error TS2314: Generic type 'TemplateRef<C>' requires 1 type argument(s).
node_modules/ng2-bootstrap/components/tabs/tab.directive.d.ts(13,17): error TS2314: Generic type 'TemplateRef<C>' requires 1 type argument(s).

**Comment by laurelnaiad** [comment]
ng2-bootstrrap isn't at all compatible with rc.0 yet. It is at beta 16. https://github.com/valor-software/ng2-bootstrap/blob/development/package.json#L56

**Comment by theunreal** [comment]
We are all still waiting for the ng2-bootstrap compactability to the rc version of angular 2.
See #481

**Comment by valorkin** [comment]
should be fixed by #481
