### ISSUE TITLE
chore(build): tsc module system systemsjs vs commonjs

### ISSUE THREAD

**Issue by miqmago** [valor-software/ngx-bootstrap#49]
In [Angular docs 5 Min Quickstart](https://angular.io/docs/ts/latest/quickstart.html#!#configure-typescript) and [Appendix: TypeScript configuration](https://angular.io/docs/ts/latest/quickstart.html#!#tsconfig) they teach using `module: "system"` for tsc:

``` json
{
  "compilerOptions": {
    "target": "ES5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules"
  ]
}
```

This issue is just to evaluate if it would be a better option to transpile ng2-bootstrap with system as well (don't know the implications given that ng2-bootstrap uses webpackBootstrap and I don't really know how it works). I suppose that the reason to use `system` is the detection order, from [Systemjs](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#module-format-detection):

> The module format detection happens in the following order:
> - _System.register / System.registerDynamic_ If the source code starts with a number of comments, followed by System.register or System.registerDynamic as the first line of code.
> - _ES modules_ The source is only detected as an ES module if it contains explicit module syntax - valid import or export statements.
> - _AMD modules_ The presence of a valid AMD define statement in the code.
> - _CommonJS modules_ The presence of require(...) or exports / module.exports assigments
> - _Global_ This is the fallback module format after all the above fail.

The problem would be to a new angular2 developer strictly following the 5 Min Quickstart: in the [systemjs config](https://angular.io/docs/ts/latest/quickstart.html#!#systemjs) they teach using `format: "register"` option.

**Comment by miqmago** [comment]
Hmm.. I've seen in the published npm version it's being transpiled with module "system", so it would not be a problem for a user of ng2-bootstrap, just for a developer of ng2-boostrap.

**Comment by cuitianze** [comment]
I used Angular2 Webpack Starter to start my app and i used ng2-bootstrap . When  i run the script ` npm run server:prod `, i  got `Uncaught TypeError`. How could i solve this problem ?

**Comment by flamurey** [comment]
Hi, I'm newbi in web programming and i has problems to integrate your project in mine.
My project based on [angular2-seed](https://github.com/mgechev/angular2-seed) and it uses **systemjs** libs as custom dependencies. This seed is the most popular and it is would be nice if **ng2-bootstrap npm package** has systemjs bundle.

**Comment by valorkin** [comment]
npm package will be same as angular2 npm package,
right now it is commonjs, and ng2-bootstrap will be commonjs by default
other thing that it will have systemjs bundles
