### ISSUE TITLE
fix(typeahead): Tab does not behave as click in field at Typeahead component

### ISSUE THREAD

**Issue by Jeetah** [valor-software/ngx-bootstrap#490]
Changing with Tab into the Typeahead field should work as clicking with the mouse into it.
Currently Tab triggers **always** a search - event if there is nothing in the field (which could also lead to crashes if model is still undefined).
Also Tab in Typeahead popup/dropdown does not behave like Enter/Click.

**Comment by Dinistro** [comment]
@Jeetah This should work just fine. What Browser are you using?

**Comment by Jeetah** [comment]
Chrome - I will test it again with latest version and report back

**Comment by karthikv-26** [comment]
@valorkin 
First of all thanks for this great library. 
I see the issue for skipping tab event triggering search is fixed and merged. When would this be available through NPM? I see the current(Latest) version still does not have this fix.

**Comment by karthikv-26** [comment]
@valorkin Thank you for the quick reply.. Any info when are you planning for the release of v2.. Just to plan things from our end..

**Comment by valorkin** [comment]
v1.9.2 was last big version of ngx bs, 
Starting from tomorrow we will work on v2
I would say v2 will be just a middleware before v3

**Comment by karthikv-26** [comment]
@valorkin Can there be any patch release for v1.9.x for this tab key handling for typeahead. Because as of now everything else in the typeahead looks stable.

**Comment by valorkin** [comment]
in v2 will focus trap, and it will be applied to such elements, for more correct keyboard handling

**Comment by karthikv-26** [comment]
@valorkin Thank you..
