### ISSUE TITLE
Pagination component: items per page scews pages calulation

### ISSUE THREAD

**Issue by markmaynard** [valor-software/ngx-bootstrap#491]
Setting `itemsPerPage` changes the number of items shown per page, but does not correctly update the number of pages. For example, with 20 total items at 10 items per page the pagination component should show two pages, and does. However, if I set the `itemsPerPage` to 5 it still only shows 2 pages instead of 4. It appears the calculation for the number of pages is not recalculated when `itemsPerPage` is changed.

**Comment by oillada** [comment]
same problem here.

**Comment by oillada** [comment]
I fix it, you have to add the attribute itemsPerPage inside the pagination tag in the html file.
For example I put it in my xxxx.component.html like this:
`<pagination [itemsPerPage]="20"  [totalItems]="bigTotalItems" [(ngModel)]="bigCurrentPage" [maxSize]="maxSize" class="pagination-sm"
                      [boundaryLinks]="true" [rotate]="false" (numPages)="numPages = $event" (pageChanged)="pageChanged($event)"></pagination>`

**Comment by erashu212** [comment]
Hence I am closing this, Can be opened if new issue arise

**Comment by sasastojkovicgfi** [comment]
Well, if you simply put a value, it works but I have a variable in my code that is bound to [itemsPerPage] and it doesn't work (it doesn't work when you change it)

**Comment by sasastojkovicgfi** [comment]
My mistake... sorry people

**Comment by akvaliya** [comment]
I am facing the same issue. Any solution for this?

**Comment by yuricano** [comment]
In my case this works

import { ChangeDetectorRef } from '@angular/core';

constructor(
       private _changeDetectionRef: ChangeDetectorRef) {}

 resetPage(): void {;
       ...
       ...
      this._changeDetectionRef.detectChanges();
    }

I use resetPage when the content was changed.
