### ISSUE TITLE
Create barrels to simplify import

### ISSUE THREAD

**Issue by Namek** [valor-software/ngx-bootstrap#492]
[doc says](http://valor-software.com/ng2-bootstrap/index-bs4.html):

``` ts
import { RatingComponent } from 'ng2-bootstrap/ng2-bootstrap';
// or
import { RatingComponent } from 'ng2-bootstrap/components/rating';
```

I would suggest to create a [barrel (mentioned in Angular 2 Style Guide)](https://angular.io/styleguide#!#create-and-import-barrels) so this would be possible:

``` ts
import { RatingComponent } from 'ng2-bootstrap';
```

**Comment by valorkin** [comment]
OK, I will check

**Comment by jeetendra** [comment]
@Namek 
I just check the source 
`import { RatingComponent } from 'ng2-bootstrap/ng2-bootstrap';`
'ng2-bootstrap/ng2-bootstrap' is barrel

so we can close this issue :+1:

**Comment by valorkin** [comment]
oh, ok :)

**Comment by Namek** [comment]
The idea is to create `index.js`file which exports everything inside of the barrel. So this would be possible:
`import { RatingComponent } from 'ng2-bootstrap';`

which I suppose it's not the case at the moment.

**Comment by valorkin** [comment]
I'm module resolution set to node, tsc should read file accordingly to main
field in package.json, but anyway ng2-bootstrap is a barrel
