### ISSUE TITLE
 Uncaught (in promise): No precompiled component TypeaheadContainer found

### ISSUE THREAD

**Issue by fahad-nxvt** [valor-software/ngx-bootstrap#496]
Getting this weird error when trying to implement Typeahead. I have made no changes in the demo code. Any help would be highly appreciated.

**Comment by valorkin** [comment]
to be honest I have never seen this issue,
how to reproduce it?
plunker or repo would be the best

**Comment by Dinistro** [comment]
@eloquent0 Any news on this, or can we close it?

**Comment by fahad-nxvt** [comment]
yes you can :) I had a complex scenario. I was using it inside a component that was passed to a Dialog. Not used it since. Used Ng2-select instead. I will implement it again some day and will try to figure out the issue. So for now you can close it.

**Comment by valorkin** [comment]
@Dinistro https://github.com/valor-software please accept invite to ng2-team

**Comment by Dinistro** [comment]
@valorkin sorry, I thought that I already accepted it
