### ISSUE TITLE
unable to set theme to bootstrap4 with systemjs

### ISSUE THREAD

**Issue by mjhugo** [valor-software/ngx-bootstrap#507]
When using SystemJS, you cannot switch the theme to Bootstrap 4 via the recommended method:

```
import {Ng2BootstrapConfig, Ng2BootstrapTheme} from 'ng2-bootstrap/ng2-bootstrap';

Ng2BootstrapConfig.theme = Ng2BootstrapTheme.BS4;

enableProdMode();

 bootstrap(AppComponent);
```

When this is done, the AppComponent will recognize the BS4 theme, but the ng2 components will not.  

As an example, clone https://github.com/mjhugo/angular2-quickstart (which has been updated to bs4 theme, see https://github.com/mjhugo/angular2-quickstart/commit/953d888991c058dbf75318393367b54c818b627b) and run `npm i` and `npm start` and notice that the theme will not be applied correctly

![wrong theme](https://cloud.githubusercontent.com/assets/33178/15256714/66522df2-1908-11e6-801f-fdbd5d376745.png)

If it had applied the bs4 theme correctly, it should look more like this:

![image](https://cloud.githubusercontent.com/assets/33178/15256739/86f8cafc-1908-11e6-91af-2d46d12bc903.png)

As indicated in https://github.com/valor-software/ng2-bootstrap/issues/371 there is a workaround - add this script block and ng2-bootstrap will switch to bootstrap4 theme.

```
  <script type="text/javascript">
    // temporary hack for enable bootstrap 4
    window.__theme = 'bs4';
  </script>
```

**Comment by maxfisher05** [comment]
this is because Glyphicons is included in bootstrap 3 but not in 4, you are missing the glyphicon-chevron-left and glyphicon-chevron-right icons.  I think that it would be nice if ng2-bootstrap had support for changing out icon pack for bs4.

if you are using font-awesome + bs4 you can add css aliases like this (using sass):

``` sass

.glyphicon {
  @extend .fa;

  &.glyphicon-chevron-left {
    @extend .fa-chevron-left;
  }

  &.glyphicon-chevron-right {
    @extend .fa-chevron-right;
  }

  &.glyphicon-chevron-up {
    @extend .fa-chevron-up;
  }

  &.glyphicon-chevron-down {
    @extend .fa-chevron-down;
  }
}
```

**Comment by valorkin** [comment]
@mjhugo you can check

``` html
  <link rel="stylesheet" href="assets/css/style.css">
  <link rel="stylesheet" href="assets/css/glyphicons.css">
```

from demo folder

but I am completely agreed with @maxfisher05 
And I working on more simple template switching

**Comment by valorkin** [comment]
@mjhugo please close an issue if @maxfisher05 answer was helpful

**Comment by mjhugo** [comment]
Thanks for the feedback and suggestion.  

I tried adding glyphicons but still no luck.  (https://github.com/mjhugo/angular2-quickstart/commit/eb6c1acb6cb0fd9e354763d49821f0d5d3b64ffe) so I don't think that's the actual issue.  You're correct that the glyphicons are missing in my screen shot - but also notice that the CSS styling is BS3 styles, not BS4.

If you set a debugging breakpoint in the `DATEPICKER_DIRECTIVES` and check the value of `Ng2BootstrapConfig.theme` you will find that it still set to BS3 instead of BS4.  My guess is that the ng2 components are initializing _before_ `AppComponent` and as such, they are initialized with a theme of BS3 before the AppComponent changes the theme to BS4.

**Comment by alexciesielski** [comment]
+1 for way of changing icon package, I would like to use FontAwesome instead of Glyphicons.

**Comment by hongbo-miao** [comment]
Similar here, I am using Typeahead.

```
import { Ng2BootstrapConfig, Ng2BootstrapTheme } from 'ng2-bootstrap/ng2-bootstrap';
Ng2BootstrapConfig.theme = Ng2BootstrapTheme.BS4;
```

does not work for me, it gives me bad style:
![image](https://cloud.githubusercontent.com/assets/3375461/16859693/fa6d6124-49fe-11e6-85a4-a68f0c7599e5.png)

But

```
  <script type="text/javascript">
    window.__theme = 'bs4';
  </script>
```

gives me good style:
![image](https://cloud.githubusercontent.com/assets/3375461/16859680/ddbf9d30-49fe-11e6-8f1a-42107ebbf2dd.png)

**Comment by searchforac** [comment]
The daypicker left right buttons seem to show text arrows instead of the cheveron glyphicons that are on the monthpicker and yearpicker.  This is also the case in the example.  I've tried setting the ARROW_LEFT and ARROW_RIGHT variables to the icons instead of &lt and &gt but that doesn't change anything.  What am I missing?

I was able to get the glyphicons to show by using the script workaround and downloading the glyphicons.  

![screen shot 2016-08-18 at 11 15 30 am](https://cloud.githubusercontent.com/assets/14316760/17779400/830c0584-6535-11e6-945f-3a0a3335bc45.png)
![screen shot 2016-08-18 at 11 15 42 am](https://cloud.githubusercontent.com/assets/14316760/17779404/857cdf28-6535-11e6-9b93-1e8dd8cc9779.png)

**Comment by fstof** [comment]
@searchforac 
I can confirm this issue, It seems the glyphicons-chevron-left/right were replaced with &gt; and &lt; on the day page but the month and year are still using the glyphicons

would be great if this can be sorted out, seems simple enough

**Comment by cfm017** [comment]
+1

**Comment by StealthyDev** [comment]
Is there a fix or workaround for this issue? How does it work in DEMO page?

**Comment by tommiv** [comment]
@StealthyDev, it's in the first message of this thread

```
<script type="text/javascript">
    // temporary hack for enable bootstrap 4
    window.__theme = 'bs4';
</script>
```

**Comment by StealthyDev** [comment]
Sorry, I tried this. I'm also using WebPack.

**Comment by tommiv** [comment]
It worked for me, but i've tried it while ago. Btw, it doesn't matter if you use WebPack, since Webpack just bundles your code. You still need to include target bundle in page `<head>`. Just make sure you put workaround script above the webpack bundle.

**Comment by valorkin** [comment]
This hack was written a long long time ago
Now I can switch to 'forRoot' method to choose app theme

**Comment by StealthyDev** [comment]
How do you do it?

**Comment by valorkin** [comment]
You can check our demo page source
https://github.com/valor-software/ng2-bootstrap/blob/development/demo/index-bs4.html

**Comment by StealthyDev** [comment]
Yes, it fixed it. Thank you.
