### ISSUE TITLE
fix(demo): add Intl polyfill for Safari

### ISSUE THREAD

**Issue by BAndonovski** [valor-software/ngx-bootstrap#512]
Clicking any date doesn't actually change it, nor calls any event. 
It doesn't work on the demo page, as well.

**Comment by valorkin** [comment]
http://valor-software.com/ng2-bootstrap/#datepicker
Works fine in chrome?

What kind of browser do you use?

**Comment by BAndonovski** [comment]
Doesn't work in Safari. 

Error's thrown right away: 
EXCEPTION: Error in ./DatepickerDemoComponent class DatepickerDemoComponent - inline template:14:76
ORIGINAL EXCEPTION: ReferenceError: Can't find variable: Intl

**Comment by valorkin** [comment]
Intl is a different story
need to add `Intl` poly fill for safari, my bad

**Comment by ps2goat** [comment]
Even with Intl, not guaranteed to work on all Android browsers.  Chrome generally works, but the old native browser does not work well with things like the currency pipe, e.g.  I believe anything older than kit kat was giving us trouble.

**Comment by valorkin** [comment]
I decided to use moment.js for date picker
so I can export date pipe as well (with localization :p )
