### ISSUE TITLE
html showing in typeahead container

### ISSUE THREAD

**Issue by ps2goat** [valor-software/ngx-bootstrap#520]
When searching for a match, the `<strong>` tags are placed around the matching text.  When I trim the value the user entered, all the rest of your demo code remaining the same, I see the following when I enter "A  " (an 'A' followed by two spaces).  At this point you'll see `strong>A</strong>labama` in the popup container.  Keep pressing space and you'll notice the html tags being pushed off one-by-one.

I even recreated this on your demo site by modifying this line of code in `getAsyncData()`:

`let query = new RegExp(context.asyncSelected, 'ig');`

new code:

`let query = new RegExp(context.asyncSelected.trim(), 'ig');`

I dug in a little bit, but not much.  We're mostly trying to make this more friendly for a user who may not be able to see that they've typed in a trailing space.

**Comment by mike-tomaras** [comment]
We are having the exact same problem. Is there any progress on this? 

Thank you

**Comment by valorkin** [comment]
I will work on to provide custom filtering things

**Comment by AlthafAzeez** [comment]
typeaheadPhraseDelimiters=' '
Set this, this should be fixed

**Comment by IlyaSurmay** [comment]
Closed as can't reproduce (version 2.0.0-beta-8), will be reopened if we have sample to reproduce
