### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by maxkarpovets** [valor-software/ngx-bootstrap#526]
After installation i got next Error:

npm WARN ng2-bootstrap@1.0.16 requires a peer of @angular/common@^2.0.0-rc.1 but none was installed.
npm WARN ng2-bootstrap@1.0.16 requires a peer of @angular/compiler@^2.0.0-rc.1 but none was installed.
npm WARN ng2-bootstrap@1.0.16 requires a peer of @angular/core@^2.0.0-rc.1 but none was installed.
npm WARN ng2-bootstrap@1.0.16 requires a peer of @angular/platform-browser@^2.0.0-rc.1 but none was installed.
npm WARN ng2-bootstrap@1.0.16 requires a peer of @angular/platform-browser-dynamic@^2.0.0-rc.1 but none was installed.

How i can fix it?

**Comment by Dinistro** [comment]
@maxkarpovets You need to upgrade the angular2 version to rc.1 or downgrade ng2-bootstrap to 1.0.13.

Some information about RC.1: https://yakovfain.com/2016/05/06/starting-an-angular-2-rc-1-project/
