### ISSUE TITLE
Override CSS on components

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#529]
Hi,

I am not sure if this is an actual error, but I want to add custom styling to the accordion control. when I try use:

.accordion{
  color: $custom_white;
  background-color: $custom_blue;
}

This is just a basic idea of what I want, but the problem is this doesn't change anything.

**Comment by kucharzyk** [comment]
It's not an error. Just use correct css classes.

Try something like this:

```
accordion-group>.panel {
    background: red;
    color: white;
}
```

or like this:

```
accordion-group>.panel>.panel-heading {
    background: blue
    color: white;
}
```

**Comment by valorkin** [comment]
@kucharzyk Thanks for helping!

**Comment by frontenddevelops** [comment]
hello everyone! 
why this method isn't work now?

**Comment by webkhushboo** [comment]
If you are using accordion module of ngx-bootstrap in your angular application and you want to override its heading background color then you can override CSS of that particular element having some class (say panel) using below code: 

:host >>> .panel {
  background-color : #fff;
  }

**Comment by Qasmi2** [comment]
https://stackoverflow.com/a/54407890/7781666
