### ISSUE TITLE
Errors. Can not find components.

### ISSUE THREAD

**Issue by maxkarpovets** [valor-software/ngx-bootstrap#532]
When I try to use come components, a always got errors
EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on DatePickerComponent (or another) 

How I can fix this issue?? ?

"ng2-bootstrap": "^1.0.16", ( from package.json )

**Comment by Dinistro** [comment]
Which angular2 version are you using? If not RC.1 this will be the problem.

**Comment by maxkarpovets** [comment]
Which should i use?

**Comment by Dinistro** [comment]
You need to upgrade to the release candidate. Some informations can be found here: https://angular.io/docs/ts/latest/quickstart.html

**Comment by maxkarpovets** [comment]
"dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/platform-server": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "@angular2-material/button": "2.0.0-alpha.2",
    "@angular2-material/card": "2.0.0-alpha.2",
    "@angular2-material/checkbox": "2.0.0-alpha.2",
    "@angular2-material/core": "2.0.0-alpha.2",
    "@angular2-material/input": "2.0.0-alpha.2",
    "@angular2-material/list": "2.0.0-alpha.2",
    "@angular2-material/progress-circle": "2.0.0-alpha.2",
    "@angular2-material/radio": "2.0.0-alpha.2",
    "@angular2-material/sidenav": "2.0.0-alpha.2",
    "@angular2-material/toolbar": "2.0.0-alpha.2",
    "angular2": "2.0.0-beta.15",
    "core-js": "^2.2.2",
    "ng2-bootstrap": "^1.0.16",
    "ng2-table": "^1.0.2",
    "ng2-translate": "^1.7.0",
    "normalize.css": "^4.1.1",
    "rxjs": "5.0.0-beta.6",
    "underscore": "^1.8.3",
    "zone.js": "~0.6.11"
  },

"@angular/upgrade":  "2.0.0-rc.1", will helps me??

**Comment by valorkin** [comment]
you don't need this:

```
"@angular2-material/button": "2.0.0-alpha.2",
"@angular2-material/card": "2.0.0-alpha.2",
"@angular2-material/checkbox": "2.0.0-alpha.2",
"@angular2-material/core": "2.0.0-alpha.2",
"@angular2-material/input": "2.0.0-alpha.2",
"@angular2-material/list": "2.0.0-alpha.2",
"@angular2-material/progress-circle": "2.0.0-alpha.2",
"@angular2-material/radio": "2.0.0-alpha.2",
"@angular2-material/sidenav": "2.0.0-alpha.2",
"@angular2-material/toolbar": "2.0.0-alpha.2",
```

if you are planning to use ng2-*
