### ISSUE TITLE
minDate is not working on the fly.

### ISSUE THREAD

**Issue by erashu212** [valor-software/ngx-bootstrap#534]
Hi,

I have used two date picker to work as range picker. On change of first date picker I am setting minDate of second date picker, similarly for second datepicker on change action.

But it seems minDate does not work on the fly.

Thanks

**Comment by rvdmolen** [comment]
I have also some strange behavior, when setting the minDate from the component class. When using the input bind variable (and yes it has a valid value), the minDate is not working.

// Working:
public minDate: Date;

ngOnInit() {
  this.minDate = moment('01-01-2016', 'DD-MM-YYYY').toDate();
}

// Not working:
@Input() inputDate: string;
public minDate: Date;

ngOnInit() {
  this.minDate = moment(this.inputDate, 'DD-MM-YYYY').toDate(); 
}

// Template:
<datepicker  [minDate]="minDate "></datepicker>

**Comment by erashu212** [comment]
@rvdmolen What should I do then. I am using behaviorsubject for setting up minDate on the fly.

**Comment by ekaitzht** [comment]
To me it's not working on the fly minDate. What was the reason to close this issue? @erashu212
