### ISSUE TITLE
Issue in calling bootstrap file 

### ISSUE THREAD

**Issue by levon27143** [valor-software/ngx-bootstrap#539]
Hi,
I'am not able to call ng2-bootstrap, However ng2-bootstrap  folder already exists in ng-module.

Please find below screenshot for folder directory for ng2-bootstrap.

https://github.com/levon27143/angular2/blob/6c700414732ab240194787ea88848097fa2dc84f/Screenshot_1.jpg

https://github.com/levon27143/angular2/blob/6c700414732ab240194787ea88848097fa2dc84f/Screenshot_2.jpg

Please find below my github repository link.

https://github.com/levon27143/angular2

Thanks & Regards
Varun Dev

**Comment by justin-romano** [comment]
This is a setup issue. With typescript its not enough to just import. You need to setup your loader
for the angular2 quickstart setup for rc1 my config looks like this. (note // <====== HERE)

``` js
...
  var map = {
    'app': 'app', // 'dist',
    'directives': 'directives',
    'rxjs': 'node_modules/rxjs',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    '@angular': 'node_modules/@angular',
   'moment': 'node_modules/moment/moment.js',// <====== HERE
    'ng2-bootstrap': 'node_modules/ng2-bootstrap' // <====== HERE
  };

  var packages = {
    'meta': { defaultExtension: 'js' },
    'directives': { defaultExtension: 'js' },
    'app': { main: 'main.js', defaultExtension: 'js' },
    'rxjs': { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { defaultExtension: 'js' }, 
    'ng2-bootstrap': { defaultExtension: 'js' } // <====== HERE
  };
```

**Comment by valorkin** [comment]
@justin-romano Thanks for helping!
