### ISSUE TITLE
ng2-bootstrap with angular-cli (Uncaught ReferenceError: webpackJsonp is not defined)

### ISSUE THREAD

**Issue by asmaliukas** [valor-software/ngx-bootstrap#54]
Hi,

just starting playing with angular 2.

I use angular-cli (https://github.com/angular/angular-cli) and everything works.

But when I try to load this module (ng2-bootstrap) it fails:
1) I inlcude `<script src="node_modules/ng2-bootstrap/build/angular2-bootstrap.js"></script>`
2) and after refresh I see `angular2-bootstrap.js:1Uncaught ReferenceError: webpackJsonp is not defined`

I think this module "compiled" to be used with webpack or something (I didn't use it before).

Do I need:
a) somehow include webpack module
b) re-compile ng2-bootstrap without webpack
?

If I should recompile, please advise how to do that. Thank you!

**Comment by valorkin** [comment]
b) re-compile ng2-bootstrap without webpack
and build folder is for demo page
check links in readme how to start using ng2-bootstrap
there are samples with system.js and webpack

**Comment by asmaliukas** [comment]
Thank you

**Comment by valorkin** [comment]
you are welcome, drop a messages if it will work for you :)
