### ISSUE TITLE
Not exactly clear demo for Pager Rotate  (pagination)

### ISSUE THREAD

**Issue by dalu** [valor-software/ngx-bootstrap#5401]
Rotate on Pager demo does nothing

**Comment by daniloff200** [comment]
No, @dalu , you're wrong
But yeah, demo looks slightly unclear.

By default, when you open demo page and press, for example, 4, it will be centered

![Selection_208](https://user-images.githubusercontent.com/13692220/67024999-f774b300-f10d-11e9-838b-3ac33dc8863d.png)

if you press then 6, the same, centered

But, if you reload page, and click on **Toggle centering current page link**  , and then choose 4, you will see that
![Selection_209](https://user-images.githubusercontent.com/13692220/67025111-29861500-f10e-11e9-9f08-ea6e8348df94.png)

**Comment by daniloff200** [comment]
I think, here we can make 2 conditions for the button
By default, rotate = **true**, so, button can be like `Current page link center is ON`, then, if user press it, we change the text to `.... is OFF`, and maybe, can change the button color, for example, why not? By default it can be blue, after choosing to off,  red, or orange, etc
