### ISSUE TITLE
[DatePicker] (click) event delay

### ISSUE THREAD

**Issue by brandenwagner** [valor-software/ngx-bootstrap#542]
<datepicker (click)="doSomething">

doSomething function will return the current value of the date and then update to the new selected date.

For example if i click on the 24th (since its first click nothing happens), and then click on 25th, doSomething gets the date of the 24th. Its like its emitting an event and then updating the model

**Comment by Dinistro** [comment]
@brandenwagner What do you mean with `doSomething` function?

**Comment by brandenwagner** [comment]
`<datepicker [(ngModel)]="dt" (click)="doSomething()"></datepicker>`

the doSomething function

```
public doSomething() {
     console.log(this.dt);
}
```

Is always 1 click behind

**Comment by Dinistro** [comment]
@brandenwagner You need to wait until the date is updated. The moment you click, the `doSomething()` function is called, but the date is not yet updated.

**Comment by brandenwagner** [comment]
How do I do that?

**Comment by erashu212** [comment]
HI @brandenwagner,

You can use like this too
`<datepicker [ngModel]="dt" (ngModelChange)="doSomething()"></datepicker>`

Thanks,

**Comment by brandenwagner** [comment]
That worked! i feel like an idiot. i kept tying to do onChange and it wouldn't work.. just had to use the right word. THANKS!
