### ISSUE TITLE
[DatePicker] EventEmitter

### ISSUE THREAD

**Issue by brandenwagner** [valor-software/ngx-bootstrap#544]
...datepicker-inner.component.ts(72,3):
Error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<Date>'.
Type '{}' is not assignable to type 'Date'.
Property 'toDateString' is missing in type '{}'.

just need to change
     private update:EventEmitter<Date> = new EventEmitter(false);
to
     private update:EventEmitter<Date> = new EventEmitter<Date>(false);

**Comment by Dinistro** [comment]
@brandenwagner You posted 2 times the same code. And what exactly is your problem?

**Comment by brandenwagner** [comment]
Oops. Sorry about that. I didn't do the markdown properly for the `<date>`
Currently it says: 
`private update:EventEmitter<Date> = new EventEmitter(false);`

and it should be 
`private update:EventEmitter<Date> = new EventEmitter<Date>(false);`

**Comment by Dinistro** [comment]
@brandenwagner when do you get this error? By just using it?
If yes, what Typescript version are you using?

**Comment by brandenwagner** [comment]
I get the error when compiling. But even with the error it still runs, i was just trying to figure out my other but/problem when i came across this one.

**Comment by Dinistro** [comment]
@brandenwagner I don't get this error on compilation. Which version of typescript do you use?

**Comment by brandenwagner** [comment]
Im using atom with the atom-typescript package.
Typescript: 1.8
Node: 5.11.1
NPM: 3.8.6

once i changed it to this, then everything worked
`private update:EventEmitter<Date> = new EventEmitter<Date>(false);`

**Comment by Dinistro** [comment]
@brandenwagner I can't reproduce these errors on my local machine. Have you tried to upgrade to the newest typescript version?

**Comment by erashu212** [comment]
Hi @brandenwagne,

Is this problem solved as per Dinistro  suggestion?

Thanks

**Comment by brandenwagner** [comment]
Yes

**Comment by valorkin** [comment]
@Dinistro thanks!:)
