### ISSUE TITLE
Tooltip component, tooltipAppendToBody property

### ISSUE THREAD

**Issue by likerRr** [valor-software/ngx-bootstrap#546]
Hello,

How soon are you planning to implement `tooltipAppendToBody` property? I have an overflowed container and tooltip cuts inside it, so I thought these property could solve the issue, but unfortunately it isn't implemented yet.

**Comment by likerRr** [comment]
@valorkin bump

**Comment by brandonreid** [comment]
This is labeled `enhancement`, but these tooltips are almost unusable without appending to the body. Any position or overflow properties risk tooltips not positioning right. 

It also messes up a lot of CSS kung fu. For example `button + button { margin-left: 1em; }`, the tooltip falls between the buttons and interrupts that margin left.

**Comment by likerRr** [comment]
@brandonreid for now I came up to bootstrap's tooltip wrapped in angular2 component. Not the best solution but at least it works. It's a pity that so much time has passed but no changes related to the issue.

**Comment by Neill83** [comment]
When we do you think this will be done? I need this for my Table-Header-Cells and can't give them tooltips because the tooltip-element is created next to the td-element.

Regards

**Comment by brandonreid** [comment]
@Neill83 You could apply the tooltip to a `<span>` element inside the table cell for now.

**Comment by Neill83** [comment]
@brandonreid ok thanks, i'll try

**Comment by seiyria** [comment]
Just wanted to chime in and bump this, also reminding that tooltips are basically unusable if they don't have append to body.

**Comment by damiandennis** [comment]
This is the same for modals, some modals are not affected but it depends on the positioning.

**Comment by DethAriel** [comment]
@valorkin any plans to fix/implement this in the near future? Are PRs accepted for this issue?

**Comment by valorkin** [comment]
There PR which gave an idea, but it should use component helper to append to body, not just element

**Comment by DethAriel** [comment]
@valorkin I guess you're referring to PR #1074 , correct? From what I see, it already uses the `componentsHelper`. Or do you imply that it should be using `appendNextToRoot` instead of `getDocument().body.appendChild`?

**Comment by valorkin** [comment]
>  it should be using appendNextToRoot

Yes
problem I see here is a bit wider, dynamic component creation, positioning is hard to understand and use, but it can be actually very simple

**Comment by DethAriel** [comment]
Do you mind leaving review comments for this PR, please, so that @jtomaszewski could address them? Right now from the PR's comment thread it looks like everything's okie-doke, when in fact it isn't

**Comment by valorkin** [comment]
I am planning to rewrite append, positioning, content provider services. And things like this will became much easier and consistent

**Comment by valorkin** [comment]
It is 4am, your question woke so much ideas in my head, and I can not sleep now :)

**Comment by DethAriel** [comment]
Sounds awesome, thanks for sharing your ideas! And I'm really sorry for keeping you awake this late :) Спокойной ночи!

**Comment by valorkin** [comment]
Thanks :)

**Comment by DethAriel** [comment]
I believe this can be closed now

**Comment by seiyria** [comment]
The docs still say not implemented. So if it was implemented (according to the changelog it is), then that should probably also be updated.

**Comment by likerRr** [comment]
Seems like it's finally done in #1074. [Demo](http://valor-software.com/ng2-bootstrap/#/tooltip) is also updated. Thx @valorkin and @jtomaszewski !
