### ISSUE TITLE
typeahead.ts line 49 should be [innerHtml]

### ISSUE THREAD

**Issue by dad-exuan** [valor-software/ngx-bootstrap#55]
For Angular2@2.0.0-beta.0, [inner-html] should be changed to [innerHtml].

Many thanks for your efforts.

**Comment by valorkin** [comment]
didn't it fixed in in 1.0.0-beta.1 ?

**Comment by valorkin** [comment]
yeap, here it is https://github.com/valor-software/ng2-bootstrap/pull/51
