### ISSUE TITLE
feat(tooltip): add support for embedded html

### ISSUE THREAD

**Issue by opiepj** [valor-software/ngx-bootstrap#56]
Hi, I'm unable to see the embedded html in your tooltip demo for bootstrap 3.

**Comment by valorkin** [comment]
Yeap, I know it will be implemented
I was looking for some generic solution for embedding html

**Comment by Hongbo-Miao** [comment]
+1

**Comment by sqwk** [comment]
+1

**Comment by olegkaplya** [comment]
+1

**Comment by mkovrigovich** [comment]
need it too

**Comment by adrianfaciu** [comment]
@valorkin Would adding a boolean 'tooltipHtml' property as option and if true bind the content to innerHtml work ? If yes, I could create a simple pull request with this. (or look at some other preferred alternative)

**Comment by vmironovs** [comment]
html input i see was implemented, but its not in release version v1.0.17
You can see https://github.com/valor-software/ng2-bootstrap/pull/553

**Comment by adrianfaciu** [comment]
@vmironovs Thanks, I've missed that pull request. Will wait for the merge.

**Comment by adrianfaciu** [comment]
Tooltip now supports embedded html and template reference.

**Comment by vmironovs** [comment]
uf... thx
