### ISSUE TITLE
ng2-bootstrap with angular-cli

### ISSUE THREAD

**Issue by joetlg** [valor-software/ngx-bootstrap#560]
Hi,

I'm trying to go with angular-cli and would like to avoid using gulp or any other build tool.

I've added bootstrap-sass and ng2-bootstrap in package.json. From within my app I'm then importing the main _bootstrap.scss (relative path to node_modules/bootstrap-sass/assets/stylesheets/bootstrap)  into my custom styles.

But when running ng build, the sass compiler copies files to a temporary work directory and then cannot find the includes.

Does anyone know how to handle this properly? Is there a configuration that I'm missing?

Your help would be highly appreciated.

TIA

**Comment by valorkin** [comment]
Hey try to ask here: https://gitter.im/valor-software/ng2-bootstrap
but to be honest, if you are not planning to modify bootstrap,
use precompiled css from bootstrap dist folder
