### ISSUE TITLE
two chinese characters will be displayed in two lines??

### ISSUE THREAD

**Issue by zenghuiLee** [valor-software/ngx-bootstrap#567]
@ciriarte @jimthedev @rkintzi  @nhydock @NathanWalker 

```

like this ------------- 中
                        国
not  中国
```

**Comment by hongbo-miao** [comment]
Which component? More details will help.

**Comment by zenghuiLee** [comment]
tooltip

**Comment by erashu212** [comment]
Hi @zenghuiLee ,

Tooltip with html support is on the way. You can use that for displaying Chinese character.

You can wait for this [PR](https://github.com/valor-software/ng2-bootstrap/pull/562) 

Thanks

**Comment by Martin-Luft** [comment]
HTML support: https://valor-software.com/ng2-bootstrap/#/tooltip -> `tooltipHtml`
