### ISSUE TITLE
the main file in package.json is ng2-boostrap instead of ng2-bootstrap

### ISSUE THREAD

**Issue by ronzeidman** [valor-software/ngx-bootstrap#57]
the main file in package.json is ng2-boostrap.js instead of ng2-boo**t**strap.js causing import "node" style to not work and hard-to-debug 404 errors.

**Comment by valorkin** [comment]
Thanks, I fill so stupid now :)

**Comment by ronzeidman** [comment]
:) Great migration by the way.

**Comment by valorkin** [comment]
@ronzeidman thank you :)
