### ISSUE TITLE
feat(collapse): add eventemitter

### ISSUE THREAD

**Issue by otelnov** [valor-software/ngx-bootstrap#576]
- `collapsed()` - An optional expression called after the element finished collapsing.
- `collapsing()` - An optional expression called before the element begins collapsing.
  If the expression returns a promise, animation won't start until the promise resolves.
  If the returned promise is rejected, collapsing will be cancelled.
- `expanded()` - An optional expression called after the element finished expanding.
- `expanding()` - An optional expression called before the element begins expanding.
  If the expression returns a promise, animation won't start until the promise resolves.
  If the returned promise is rejected, expanding will be cancelled.

**Comment by Dinistro** [comment]
I would work with Observables and not with Promises.
