### ISSUE TITLE
feat(typeahead): add accessibility attributes

### ISSUE THREAD

**Issue by stevenao** [valor-software/ngx-bootstrap#582]
Since bootstrap components will have a big user base, It is a good time to think of accessibility on all of the components. In particular, this typeahead widget is not currently accessible. When results are show, there is no indication how many results are there and how to navigate the results. 

With screen reader turned on, please look at this example: http://www.bu.edu/webteam/clrux/accessibility/autocomplete/autocomplete.html. 

Also, current implementation doesn't seem to allow overriding the "result" template. I have no way to adding some aria attributes to enable accessibility.

**Comment by TonD83** [comment]
We would really benefit from an accessible typeahead component, too. Is there anything you can say about the likelihood this will be implemented a) at all and b) if so, within what timespan?
Thanks a lot, really appreciate the ng2-bootstrap components.

**Comment by skesarwani** [comment]
Hi, Can it be mentioned, till when the accessibility (ARIA) attributes will be added in the typeahead so it's items can be read on the screen reader

**Comment by vd-nagarro** [comment]
@valorkin  - Do we have any update on this as we need to add ARIA attributes for Accessibility with typeahead so that items can be read on the screen reader.

**Comment by gthom9** [comment]
Hello, is there any update on when this will be added? Thanks

**Comment by JHorm** [comment]
@valorkin  It is still an issue :(. Thanks!

**Comment by samshay** [comment]
I send a pull request with modifications #5547
