### ISSUE TITLE
Invalid bootstrap progress after uploading app to Apache web hosting

### ISSUE THREAD

**Issue by theunreal** [valor-software/ngx-bootstrap#585]
Progress bar in localhost:

![image](https://cloud.githubusercontent.com/assets/6171883/15825629/3738a650-2c0d-11e6-8c08-210976566e33.png)

Progress bar in web hosting:

![image](https://cloud.githubusercontent.com/assets/6171883/15825714/813800b6-2c0d-11e6-8082-7b33bf8fae3d.png)

Everything is on 100%. 

This is the code:

```
<progressbar class="progress-striped" 
[value]="object.current_hp" 
[max]="object.max_hp" 
[type]="type">
{{object.current_hp/object.max_hp | percent:'1.0-1'}} HP ({{object.current_hp}}/{{object.max_hp}})</progressbar>
```

What's wrong? feels like the [max] is not initalized or something..

**Comment by valorkin** [comment]
I am not sure that problem is in progressbar
