### ISSUE TITLE
Support Angular 10.0

### ISSUE THREAD

**Issue by sun293529884** [valor-software/ngx-bootstrap#5876]
error TS2307: Cannot find module 'ngx-bootstrap' or its corresponding type declarations.

Is there any way to make ngx-bootstrap support angular10.

**Comment by HitkoDev** [comment]
v4 seems to work for now

**Comment by daniloff200** [comment]
Actually,  ngx-bootstrap now supports Angular 10 - from version 6.0.0
I wanna know more information, to be able to help you with this error

**Comment by daniloff200** [comment]
Closed, because of inactivity, and no response.
Feel free to drop comments here, I'll reopen this issue, if needed
