### ISSUE TITLE
[dropdownToggle] issue with disabled attribute

### ISSUE THREAD

**Issue by marcalj** [valor-software/ngx-bootstrap#588]
https://github.com/valor-software/ng2-bootstrap/blob/master/components/dropdown/dropdown-toggle.directive.ts

You're using `disabled` as an input value and gets conflict when I want to use in a template like this:

``` html
<button dropdownToggle [disabled]="!isActive()">
```

The attribute disabled is not specified correctly. Maybe you can use `@Attribute('disabled')` in the constructor to fix this issue.

Thanks!

**Comment by valorkin** [comment]
@marcalj thanks for hint, may be I should use [dd-disabled] or [isDisabled]

**Comment by marcalj** [comment]
You name it, if you want to use standard element attributes you cannot change the desired behaviour.
Maybe with `@Attribute` you can maintain standard behaviour.

PD: Your avatar is so scary! :)

**Comment by marcalj** [comment]
@valorkin Can you define the new variables please? I'll try to send you a pull request with this implemented :)

There's instructions about how to contribute? (to which branch, how to setup workspace, unit tests, etc?) Thanks!

**Comment by erashu212** [comment]
Hi @marcalj,

I will create a PR in sometime. I would prefer to use isDisabled.

Thanks

**Comment by marcalj** [comment]
It's working, thanks! Can you merge @valorkin ?

**Comment by zakton5** [comment]
Has not fix not been released? I am on 1.1.14 and I am seeing this issue for radio buttons.

**Comment by valorkin** [comment]
It is merged 4 month ago, I am sure it was released. Try clean install

**Comment by zakton5** [comment]
The issue should be closed if so. I am up to date and here is my code. It is not working, so it does not disable the button.

``` html
<button class="btn btn-white" [(ngModel)]="myModel.property" btnRadio="Y" uncheckable [disabled]="true">Yes</button>
```

**Comment by marcalj** [comment]
Use ```isDisabled``` input variable on directive. Closing issue.

**Comment by zakton5** [comment]
This same change needs to also be done for all buttons.

**Comment by valorkin** [comment]
it is very painful question actually
binding to html attributes - it could override default behavior
so it is better if `isDisable` will set .disabled class or attribute
than vise versa, plus there are were IE9 compatibility issues

**Comment by sharathdaniel** [comment]
Still cannot disable a button having dropdown.
