### ISSUE TITLE
docs(samples): please include in documentation ...

### ISSUE THREAD

**Issue by valorkin** [valor-software/ngx-bootstrap#590]
Please drop in comments what ever you want to see added in documentation
1. (improvement) could we remove the top bar and move the Icon beside ng2-bootstrap? Then we have more space left for the docs, mostly on small screens.

**Comment by hongbo-miao** [comment]
A table of content to navigate will be helpful! : )

**Comment by valorkin** [comment]
ToC like menu on left side (http://valor-software.com/ng2-bootstrap/#/datepicker)
or ToC in each section (like sample1, annotation, cookbook 1, etc.)?
//cc @Hongbo-Miao

**Comment by hongbo-miao** [comment]
Oh, forget my comment. Just saw the UI changed, awesome!!

**Comment by meorfi** [comment]
if is possible, include in documentation a good demo for modal with yes/no (positive/negative) buttons and according functions. It would be very useful. Thanks

**Comment by jhiemer** [comment]
Perhaps an improvement suggestion I heard from a colleague yesterday. Could we remove the top bar and move the Icon beside ng2-bootstrap? Then we have more space left for the docs, mostly on small screens.

**Comment by valorkin** [comment]
closing it for now, we well a tech writer soon :)

**Comment by valorkin** [comment]
closing it for now, we will have a tech writer soon :)
