### ISSUE TITLE
bug(accordion): heading with markup not working

### ISSUE THREAD

**Issue by sylc** [valor-software/ngx-bootstrap#593]
Hi, the accordion heading with markup is not working

from doc example:
`<i class="pull-right glyphicon" [ngClass]="{'glyphicon-chevron-down': group?.isOpen, 'glyphicon-chevron-right': !group?.isOpen}"></i>`

chevron never goes down when group is open.

thanks

**Comment by valorkin** [comment]
It is still using DynamicContentLoader, and it loses context
It is known issue

**Comment by youngpayters** [comment]
Not sure if this is a workaround or not but changing variable from `let group` to `#group` resolved it for me.

**Comment by calvinKG** [comment]
@youngpayters  thanks it did solve the problem on my side. 

With the # it those reference the group on the html page.

**Comment by artemvfrolov** [comment]
can't reproduce this issue, please provide more information

**Comment by IlyaSurmay** [comment]
Closed as can't reproduce, will be reopened if we have sample to reproduce.
Header with markup works fine in demo  https://valor-software.com/ngx-bootstrap/#/accordion#simple-accordion
