### ISSUE TITLE
Calling modal from typescript code

### ISSUE THREAD

**Issue by madfiles** [valor-software/ngx-bootstrap#594]
Hi,
In the basic bootstrap library you have an option for calling the modal from code 
$('#myModal').modal(options)

On the ng2-bootstrap example you are only able to call on a button click from the template.
<button class="btn btn-primary" (click)="lgModal.show()">Large modal</button>

The lgModal/smModal are not available within the transpiled typescript code .

Is there any way to open a modal dialog from code? I want to show the modal off a subscription to an AJAX event and populate with the returned JSON data.

The bootstrap example uses $ and I'd like to avoid jquery (that being the main reason for using ng2-bootstrap).

Many thanks for any help.

**Comment by valorkin** [comment]
You just need to inject modal instance into your component (which html should contain modal inside of it)
there are a variate of ways how to do this
with ContentChild for example

if you will find it problematic you can seek for help here: https://gitter.im/valor-software/ng2-bootstrap
