### ISSUE TITLE
Pager doesn't trigger callback on page change.

### ISSUE THREAD

**Issue by jaesung2061** [valor-software/ngx-bootstrap#595]
Everything works for me except the function call. The `metadata.current_page` is changing when I hit the pager, but it isn't calling the function. 

```
<pager [totalItems]="articles.metadata.total"
       [(ngModel)]="articles.metadata.current_page"
       onPageChanged="pageChanged($event)">
</pager>

{{articles.metadata.current_page}}
```

Component (same place where `articles` property is):

```
pageChanged(event:any):void {
    console.log('Page changed to: ' + event.page);
    console.log('Number items per page: ' + event.itemsPerPage);
};
```

I've also tried `(onPageChanged)="pageChanged($event)"` which doesn't work.

**Comment by adrianfaciu** [comment]
The event is called pageChanged, and since it's an event binding you need the (), so it should be something like: `(pageChanged)="pageChanged($event)`
