### ISSUE TITLE
bug(dropdown): two consecutive dropdown clicks

### ISSUE THREAD

**Issue by sumigoma** [valor-software/ngx-bootstrap#6]
if you click to open one dropdown, then click on another dropdown, the menu no longer disappears when you click away.

**Comment by valorkin** [comment]
@sumigoma thx for issue, in which browser\system it happens?
because at osx\linux \safari\chrome\ff works fine
maybe some error in console?

**Comment by sumigoma** [comment]
I've seen the issue both on the latest chrome and firefox on a windows box. No console errors.

The sequence is quite specific - you have to click on one dropdown button, then click on another dropdown button directly (without closing the first), then click away on the page body. I can try to repro on my linux box and investigate the cause.

**Comment by valorkin** [comment]
@sumigoma I am currently working on documentation, I am expecting to ship fix to this issue in nearest days, ok?

**Comment by mpetkov** [comment]
Any update on this issue?  I am getting same behavior on latest Chrome on Windows

**Comment by alaalqadi** [comment]
still have this problem :(
when i click the second dropdown it closes the parent dropdown please help
