### ISSUE TITLE
request: i18n in datepicker

### ISSUE THREAD

**Issue by hxlniada** [valor-software/ngx-bootstrap#606]
Need to show chinese in the year and week area;

**Comment by nereujunior** [comment]
+1

**Comment by valorkin** [comment]
![c0033c85867bf418f7fce9ad5a2735d0](https://cloud.githubusercontent.com/assets/1107171/16941153/057db26c-4d97-11e6-940f-acce36fe5afa.png)

it will be there :)
Working on new version of datepicker,
most probably I will need some help with additional translations
stay tuned
https://www.hamsterpad.com/chat/ng2

**Comment by valorkin** [comment]
@hxlniada BTW can you confirm that it looks correct?

**Comment by kinglionsoft** [comment]
+1
