### ISSUE TITLE
How to disable leading 0 on datepicker popup?

### ISSUE THREAD

**Issue by arturstarodaj** [valor-software/ngx-bootstrap#609]
How to disable leading 0 on the datepicker popup?

![Image of datepicker format](http://i.imgur.com/NY9Tsy0.png)

**Comment by adrianfaciu** [comment]
If you look at the documentation you'll see that there is a formatDay option. If not specified, the default value of "DD" will be used. To remove the leading 0 just add it to your component like formatDay="D".

**Comment by valorkin** [comment]
@adrianfaciu thanks!

**Comment by arturstarodaj** [comment]
[formatDay]="d" 

Still shows up "dd" instead.
This option seems to be ingored. 
Other options are working fine

**Comment by adrianfaciu** [comment]
formatDay="d" is different than formatDay="D". Have a look [here](http://momentjs.com/docs/#/displaying/).
