### ISSUE TITLE
Unable to stack modals on top of each other (2nd modal displays behind the first modal shown).

### ISSUE THREAD

**Issue by chrismcgregor** [valor-software/ngx-bootstrap#620]

**Comment by eRez-ebs** [comment]
try adding this - `style="z-index: 1200 !important;` to your top modal HTML

**Comment by valorkin** [comment]
as for now http://v4-alpha.getbootstrap.com/components/modal/

> Multiple open modals not supported
> Be sure not to open a modal while another is still visible. Showing more than one modal at a time requires custom code.

It will change most probably later
