### ISSUE TITLE
How to use DatePicker Popup

### ISSUE THREAD

**Issue by harishrohokale** [valor-software/ngx-bootstrap#623]
I do not want to use default datepicker which is inline.

Please help me to use show hide datepicker or datepicker popup.

**Comment by adrianfaciu** [comment]
What issues do you have with showing / hiding the control ?
You could just add an NgIf to the element, maybe something along the lines of:

```
<input type="text" [ngModel]="dt" (focus)="showDatePicker = true">
  <div *ngIf="showDatePicker" style="position: absolute; z-index:10; min-height:290px;">
    <datepicker [(ngModel)]="dt" [minDate]="minDate" [showWeeks]="true"></datepicker>
  </div>
```

**Comment by valorkin** [comment]
please follow this issue: https://github.com/valor-software/ng2-bootstrap/issues/273
it should be released this week
