### ISSUE TITLE
Typeahead wrong style

### ISSUE THREAD

**Issue by AndersonDev** [valor-software/ngx-bootstrap#626]
Hi. I am using last Angular 2 and last Bootstrap 4. When I created typeahead I noticed that style is terrible:
![image](https://cloud.githubusercontent.com/assets/6890368/16180008/b7f012a2-367f-11e6-83f4-810ab18505e3.png)

And rendered DOM is different than on yours site:

![image](https://cloud.githubusercontent.com/assets/6890368/16180012/ee40ed2c-367f-11e6-8403-e9098171be09.png)

Simple code:
`<input class="form-control" [(ngModel)]="studentToAdd" [typeahead]="students"
                 [typeaheadOptionField]="'surname'">`

Thanks!

**Comment by jprinaldi** [comment]
Same issue here.

**Comment by Dinistro** [comment]
Can you please provide a plunkr?

**Comment by AndersonDev** [comment]
@Dinistro hi. For a what? I anly add `<input class="form-control" [(ngModel)]="studentToAdd" [typeahead]="students" [typeaheadOptionField]="'surname'">` and have wrong styles. And for ng-select I have the same issue. Thanks!

**Comment by AndersonDev** [comment]
@Dinistro any ideas about that?

**Comment by Dinistro** [comment]
@AndersonDev I can't reproduce this issue. This is why I asked for a plunkr.

**Comment by hongbo-miao** [comment]
@AndersonDev The problem is because

```
import { Ng2BootstrapConfig, Ng2BootstrapTheme } from 'ng2-bootstrap/ng2-bootstrap';
Ng2BootstrapConfig.theme = Ng2BootstrapTheme.BS4;
```

does not work.

The walkaround way is using

```
  <script type="text/javascript">
    window.__theme = 'bs4';
  </script>
```

in your html file.

**Comment by hongbo-miao** [comment]
Dup with https://github.com/valor-software/ng2-bootstrap/issues/507

**Comment by valorkin** [comment]
Working on simpler way for theming
Closing as duplicate
