### ISSUE TITLE
feat: Support the RC.2 Forms

### ISSUE THREAD

**Issue by Dinistro** [valor-software/ngx-bootstrap#627]
We should work on a version that supports the new forms: https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub

Currently, when I disable the deprecated forms, some of the ng2-bootstrap components are not able to find NgModel and other stuff (for example in typeaheads).

**Comment by eugene1985** [comment]
I confirm, here was my problem. I have used following [seed project](https://github.com/mgechev/angular2-seed) and the **angular.forms** was used by default. I had no idea, why my early working code was broken in this seed project. Thank you for this issue, i have fixed my code now. If it can help, I have described my problem by [stackoverflow](http://stackoverflow.com/questions/37932493/ng2-bootstrap-btnradio-in-angular-2-rc2-seed-project-two-way-binding-to-ngmodel/37954763#37954763).

**Comment by born2net** [comment]
might as well go to rc.3

**Comment by valorkin** [comment]
@Dinistro next week I will be landing a lot of changes
as you can see @otelnov helps me a lot with test coverage
so we are ready to move forward :)

**Comment by smnbbrv** [comment]
@valorkin any news on that topic? Cannot wait for this 👍

**Comment by Dinistro** [comment]
@smnbbrv There is a new PR #678. Unfortunately there are still issues with the test -> work in progress

**Comment by smnbbrv** [comment]
the issue can be closed I guess...
