### ISSUE TITLE
chore(angular2 webpack starter): Uncaught TypeError

### ISSUE THREAD

**Issue by TinChak** [valor-software/ngx-bootstrap#63]
I used Angular2 Webpack Starter to start my app and i used ng2-bootstrap . When  i run the script `npm run server:prod`, i  got `Uncaught TypeError`. How could i solve this problem ?

**Comment by valorkin** [comment]
link to your repo please, so I can see what kind of changes your did
and how it is related to ng2-bootstrap
node,npm,ts version please

**Comment by TinChak** [comment]
https://github.com/cuitianze/learn-your-ng2

My demo here, thanks.

**Comment by TinChak** [comment]
I think it's the problem with webpack config of  angular2 webpack starter (by AngularClass).

**Comment by TinChak** [comment]
https://github.com/AngularClass/angular2-webpack-starter/issues/203

**Comment by PatrickJS** [comment]
@cuitianze can you update the prod config

``` es6
    new DefinePlugin({
      // Environment helpers
      'process.env': {
        'ENV': JSON.stringify(metadata.ENV),
        'NODE_ENV': JSON.stringify(metadata.ENV)
      },
      // TypeScript helpers
      // '__metadata': 'Reflect.metadata',
      // '__decorate': 'Reflect.decorate'
    }),
    new ProvidePlugin({
      '__metadata': 'ts-helper/metadata',
      '__decorate': 'ts-helper/decorate',
      '__awaiter': 'ts-helper/awaiter',
      '__extends': 'ts-helper/extends',
      '__param': 'ts-helper/param',
      'Reflect': 'es7-reflect-metadata/dist/browser'
    }),
```

**Comment by TinChak** [comment]
Thanks for updating webpack config ! @gdi2290

**Comment by PatrickJS** [comment]
no problem :+1: open another issue (in my repo) if you have a question or run into another problem with the starter

**Comment by valorkin** [comment]
Issue solved?

**Comment by PatrickJS** [comment]
ya

**Comment by valorkin** [comment]
Thanks for helping! :)
