### ISSUE TITLE
typeahead performance issue

### ISSUE THREAD

**Issue by fdu-axiometrics** [valor-software/ngx-bootstrap#637]
typeahead setup

`
<input type="text" class="form-control" placeholder="Search for..."
                       [typeahead]="getAsyncData(getContext())"(typeaheadOnSelect)="typeaheadOnSelect($event)"  [(ngModel)]="searchTerm">
`

```
private getContext():any {
        return this;
    }

private getAsyncData(context:any):Function {

      return function ():Promise<Object[]> {
                return context.searchService.searchCompaniesByName(context.addCompaniesModalSearchTerm.trim()).toPromise();
            };
}
```

getAsyncData function would be constantly called as long as the page is open and no user interaction is on the page.

[Attached timeline results on chrome]

![angular2_timeline](https://cloud.githubusercontent.com/assets/14625848/16275034/e7b16500-386d-11e6-8b10-f40f220c97e8.PNG)

**Comment by Dinistro** [comment]
This should be fixed with the new Observable implementation #584 .
