### ISSUE TITLE
chore(documentation) JSPM usage instructions

### ISSUE THREAD

**Issue by evanplaice** [valor-software/ngx-bootstrap#64]
Shouldn't take much work. Is the plan to just split the 'Installation' section into 'Installation - NPM' and 'Installation - JSPM'?

**Comment by valorkin** [comment]
Unfortunately I am not jspm user, so if you have a sample how to use it, I can try it and include in readme

**Comment by evanplaice** [comment]
The ng2-bootstrap is in the JSPM registry. Unless the registry entry needs to be updated with a shim, the hard part should be over. That means...

_To install:_

``` bash
jspm install ng2-bootstrap
```

_To use:_

``` javascript
import 'ng2-bootstrap';
```

That's it. I haven't tried it yet so I can't verify that it works. I have a demo app that is sorely in need of a UI update. I can use ng2-bootstrap and update the docs if everything works as expected.

**Comment by valorkin** [comment]
jspm did not get popular + it is pretty easy right now
