### ISSUE TITLE
How to use api in typescript

### ISSUE THREAD

**Issue by keyiis** [valor-software/ngx-bootstrap#644]
I want create a global modal,it can be called from anywhere in my project and needn't declare in template html.so i write code below,but not work
--------------globalmodal.component.ts------------

```
import {Component,ViewChild, ElementRef} from '@angular/core';
import {CORE_DIRECTIVES} from '@angular/common';
import {MODAL_DIRECTVES, BS_VIEW_PROVIDERS} from 'ng2-bootstrap';

@Component({
    selector: 'modal',
    directives: [MODAL_DIRECTVES, CORE_DIRECTIVES],
    viewProviders: [BS_VIEW_PROVIDERS],
    template: require('./globalmodal.component.html')
})
export class ModalComponent {
    @ViewChild('lgModal') modal:ElementRef;
    public constructor(options?:any){
                 how to send option to modal?
    }
    show(){
        this.modal.show();//Property 'show' does not exist on type 'ElementRef'.
    }
}
```

--------------globalmodal.component.html----------------

```
<div bsModal #lgModal="bs-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" (click)="lgModal.hide()" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Large modal</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>
```

-----------------app.component.ts(call globalmodal.component)----------

```
import { Component} from '@angular/core';
import {ModalComponent} from './component/globalmodal.component';
@Component({
  selector: 'my-app',
  template: `i won't declare any tag about modal`,
  styles: [`....`],
  directives:[ModalComponent]
})
export class AComponent{
  modal:ModalComponent;
  edit(){
    this.modal.show();
  }
}
```

**Comment by Dinistro** [comment]
1. Please provide a plunkr. 
2. Why do you do this?:

`@ViewChild('lgModal') modal:ElementRef;`

With this code, you search for a lgModel and save it as `ElementRef`, but this `ElementRef` has no method `show()`. Have you tried to do something like this?:

`@ViewChild('lgModal') modal:ModalComponent` 

or

`@ViewChild('bsModal') modal:ModalComponent`

**Comment by keyiis** [comment]
@Dinistro i living china,plunkr is blocked.
**Why do you do this?**for reason:
i want add some warp(like: add foot button) to modal.
`@ViewChild('lgModal') modal:ElementRef;` in ModalComponent,so how to let modal can use ng2-bootstrap's modal api?

**Comment by Dinistro** [comment]
@keyiis Sorry, I forgot about your problem. I now found a solution:

`
@ViewChild(ModalDirective) modal : ModalDirective;
`

**Comment by valorkin** [comment]
@keyiis I suppose it is fixed?

**Comment by henrysteven** [comment]
@Dinistro Thank you very much, you helped me a lot, greetings from Ecuador
