### ISSUE TITLE
Uncaught (in promise): TypeError: Cannot read property 'parentInjector' of undefined

### ISSUE THREAD

**Issue by rubinus** [valor-software/ngx-bootstrap#646]
Uncaught (in promise): TypeError: Cannot read property 'parentInjector' of undefined

when i use the angular2  2.0.0.rc1   .
====================================pls fix this it.

MODALS

```
        <!-- Large modal -->
```

<button class="btn btn-primary" (click)="lgModal.show()">Large modal</button>

<div bsModal #lgModal="bs-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" (click)="lgModal.hide()" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Large modal</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>

# 

import {Component} from '@angular/core';
import {CORE_DIRECTIVES} from '@angular/common';

// todo: change to ng2-bootstrap
import {MODAL_DIRECTVES, BS_VIEW_PROVIDERS} from '../../../ng2-bootstrap';
// webpack html imports
let template = require('./modal-demo.html');

@Component({
  selector: 'modal-demo',
  directives: [MODAL_DIRECTVES, CORE_DIRECTIVES],
  viewProviders:[BS_VIEW_PROVIDERS],
  template: template
})
export class ModalDemoComponent {

}

**Comment by Makhlab** [comment]
2.0.0.rc4, same thing

**Comment by valorkin** [comment]
@Makhlab please read _Important notes_ carefully http://valor-software.com/ng2-bootstrap/#/modals
