### ISSUE TITLE
EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'parentInjector' of undefined

### ISSUE THREAD

**Issue by rubinus** [valor-software/ngx-bootstrap#648]
Don't forget to add hack to your application root component (why?)

import {Component, ViewContainerRef} from '@angular/core';

@Component({selector:'app-root'})
class AppRoot {
  public constructor(viewContainerRef:ViewContainerRef) {
    // You need this small hack in order to catch application root view container ref
    this.viewContainerRef = viewContainerRef;
  }
}
# 

what is mean ?
app-root  and AppRoot

**Comment by rubinus** [comment]
ng2-bootstrap doc is too low
i can't undersdan

**Comment by rubinus** [comment]
error TS2339: Property 'viewContainerRef' does not exist on type 'AppRoot'.

**Comment by rubinus** [comment]
do you provide  complete example

**Comment by moloch--** [comment]
Basically the modal needs access to the AppRoot so it can do the fancy fading/overlay. To achieve this you need to create an `viewContainerRef` class member in you AppRoot component:

```
export class AppComponent implements OnInit {

  viewContainerRef: ViewContainerRef;

  constructor(viewContainerRef:ViewContainerRef) {
    this.viewContainerRef = viewContainerRef;
  }
```

**Comment by valorkin** [comment]
@moloch--  thanks for help, that's correct

**Comment by leowaisblatt** [comment]
worked for me! I was adding the ViewcontainerRef hack to the component instead of the root app.
leaving the comment just in case someone else commit the same mistake than me.

**Comment by rogerfar** [comment]
Can this be added to the docs? It took me quite a while to figure this out.

**Comment by valorkin** [comment]
@yesman85 it is in doc http://valor-software.com/ng2-bootstrap/#/modals
Prior rc.4 you didn't need it until you use modals,
Now you do

**Comment by rogerfar** [comment]
Yeah I read that part, but it was missing this line:
viewContainerRef: ViewContainerRef;

it threw me off guard as TS wouldn't compile without it.

**Comment by 1thrasher** [comment]
This doesn't appear to fix the issue when using nested routers. Has anyone else experienced this?
