### ISSUE TITLE
Typeahead multiple result sets, and custom templating

### ISSUE THREAD

**Issue by dessalines** [valor-software/ngx-bootstrap#652]
I need to include multiple result sets in my search bar dropdown, for example, searching for songs, and albums. Is there any way to do this yet?

[Example](https://twitter.github.io/typeahead.js/examples/#multiple-datasets)

Also, custom templating is pretty crucial too.

**Comment by dessalines** [comment]
Thanks! It'd be nice to have an example in the docs too. 

EDIT: Oops, Should I add multiple result sets as another ticket?

**Comment by adrianfaciu** [comment]
I'll think about how we could implement this. 
You can create a new issue and we'll close that one once the functionality is added.

**Comment by dessalines** [comment]
Will do.

**Comment by bohrasankalp** [comment]
Any updates?
