### ISSUE TITLE
installing with bower and running gulp fails

### ISSUE THREAD

**Issue by sgannu** [valor-software/ngx-bootstrap#653]
I am trying to install np2-bootstrap as bower module and build with gulp, but npm install fails with below error. Any help?

299008 error Windows_NT 10.0.10586
299009 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
299010 error node v4.4.5
299011 error npm  v2.15.5
299012 error code ELIFECYCLE
299013 error ng2-bootstrap@1.0.17 prepublish: `npm run flow.clean && npm run flow.compile`
299013 error Exit status 1
299014 error Failed at the ng2-bootstrap@1.0.17 prepublish script 'npm run flow.clean && npm run flow.compile'.
299014 error This is most likely a problem with the ng2-bootstrap package,
299014 error not with npm itself.
299014 error Tell the author that this fails on your system:
299014 error     npm run flow.clean && npm run flow.compile
299014 error You can get information on how to open an issue for this project with:
299014 error     npm bugs ng2-bootstrap
299014 error Or if that isn't available, you can get their info via:
299014 error
299014 error     npm owner ls ng2-bootstrap
299014 error There is likely additional logging output above.

**Comment by adrianfaciu** [comment]
Is this all the error logging that you get ? I assume it might be a bit more than this...

**Comment by valorkin** [comment]
closing as inactive
