### ISSUE TITLE
[DatePicker] onChange

### ISSUE THREAD

**Issue by daco** [valor-software/ngx-bootstrap#655]
Hi,

Is there a way of telling that the date value has changed, ie somebody selected a new date? I'm trying with (change) on the same input as the [(ngModel)]. But that (change) only seems to fire when I manually change the value of that input, instead of using datepicker.
I also tried with (click) on the datepicker, but than of course (click) also fires when somebody select a your or month, without actually changing the date.
Timepicker seems to have (change)="changed()" implemented, but datepicker not.
Thanks for any help.

**Comment by adrianfaciu** [comment]
You could separate the property binding and the event. Something like: 

`<datepicker [ngModel]="dt" (ngModelChange)="onChange($event)"></datepicker>`

Then in the event handler you can do whatever you want.

**Comment by daco** [comment]
Thanks adrianfaciu. It works like that. Still, I don't know why the Timepicker has a explicit change event emitter implemented, and Datepicker not. But, it's not so much an issue.

**Comment by daco** [comment]
One more thing!
If you want your change detection to update the model, you have to keep banana in a box syntax [(ngModel)]="dt", on top of (ngModelChange)="onChange($event)" to do other stuff you want when the model kets updated.

**Comment by drewpintus** [comment]
Having same issue, just inexperienced with typescript. Uploaded my html and typescript so you can see the whole thing. Basically I just want to disable the submit button if one or both of inputs is blank. Issue is that if I manually make one of the inputs blank and then choose a new date from datepicker, the form validation doesn't recognize. I tried both [ngModel] and [(ngModel)] 
[hypertml.txt](https://github.com/valor-software/ng2-bootstrap/files/567463/hypertml.txt)
[typescript.txt](https://github.com/valor-software/ng2-bootstrap/files/567464/typescript.txt)

**Comment by somzJosf** [comment]
AN ISSUE WITH THIS...
<span class="glyphicon glyphicon-calendar" (click)="showDatepicker = true">< /span>
<datepicker class="popup" [(ngModel)]="dateReported" *ngIf="showDatepicker" [showWeeks]="true" name="dateReported"
                                                   (ngModelChange)="onChange($event)">< /datepicker>

If I do this, clicking the calender icon triggers the onChange event..

**Comment by pegaltier** [comment]
Same issue than @somithajoseph If I do this, clicking the calender icon triggers the onChange event..

**Comment by pulfabio** [comment]
Same here! As @somithajoseph and @pegaltier.
Is anyone going to address this issue?

**Comment by chrisjmccrum** [comment]
Checking if there have been any updates on this. I just need a way to know when a date was clicked so I can fire off other events.

**Comment by himajaM** [comment]
Once after inserting into DB the datepicker value is reducing by '1'  i.e 2016-02-21 TO 2016-02-20               If i am using ng2-datepicker with ngModelChange....
why i am facing this issue??  any help pls...

**Comment by Aravinthan27** [comment]
@himajaM  faced same issue but i fixed using the datepicker data as slicing the Time Data from datepicker data

**Comment by ronskyi** [comment]
I'm using ngx timepicker and datepicker for same object property, so using ngModelChange in both will cause infinite calls to callback functions

**Comment by apbedi** [comment]
I want to use the ngx datepicker with formcontrol so,  I have taken like this
<input type="text" bsDatepicker formControlName="sDateValue" (bsValueChange) ="value($event) >

On function I am getting selected value.  But I am manupulating that value as start date and calculate the value for end date.  But in manupulation my start date value changes to end date.  Which click event should fired for selected date with formcontrolname

**Comment by apbedi** [comment]
I want to use the ngx datepicker with formcontrol so,  I have taken like this
<input type="text" bsDatepicker formControlName="sDateValue" (bsValueChange) ="value($event) >

On function I am getting selected value.  But I am manupulating that value as start date and calculate the value for end date.  But in manupulation my start date value changes to end date.  Which click event should fired for selected date with formcontrolname

**Comment by hassan209** [comment]
I'm using ngx-bootstrap datepicker. I want to change daterangepicker into two input fields. when I change date from one field automatically date change in second input field. Anyone tell how I make this event.
