### ISSUE TITLE
Cannot customize the backdrop action

### ISSUE THREAD

**Issue by linnobita** [valor-software/ngx-bootstrap#656]
I need to prevent user close the modal accidentally by clicking outside the modal or pressing "ESC" on keyboard. So I set the config for the modal as `[config]="{ backdrop: 'static', keyboard: false}"`. It changed the keyboard action but not the backdrop. It seems that the backdrop is using the default configuration rather than the customized one.

**Comment by valorkin** [comment]
@linnobita all seems to behaive correctly
