### ISSUE TITLE
tooltip with input 

### ISSUE THREAD

**Issue by vmironovs** [valor-software/ngx-bootstrap#660]
i try to do html tooltip with input like 
`tooltipHtml='<input [(ngModel)]="someModel" />'
`
but now we know  tooltip work only with mouse over and focus and hide when live.
can you do some method for tooltip mouseover not hide ? or some event for hiding

**Comment by Dinistro** [comment]
Can you give us an example, where this will be useful?

**Comment by vmironovs** [comment]
this can bee useful for add comment by click open tooltipe with input.  
may be this is specific for me. 
it better use in UI like a table , for see on row  and add comment to some component do not change UI , but show near this row.

**Comment by Dinistro** [comment]
This should not be in a tooltip. Per definition a tooltip only contains information about his parent. You are searching for something popup related.

**Comment by vmironovs** [comment]
thx
