### ISSUE TITLE
Directive is undefined with ng2-bootstrap and systemJS

### ISSUE THREAD

**Issue by Skuriles** [valor-software/ngx-bootstrap#669]
I'm using ng2-boostrap with systemJS:

system.config.js

```
var map = {
    'app': 'app',
    'rxjs': 'vendor/rxjs',
    'zonejs': 'vendor/zone.js',
    'reflect-metadata': 'vendor/reflect-metadata',
    '@angular': 'vendor/@angular',
    'jquery': 'libs/libs.js',   
    'ng2-bootstrap/ng2-bootstrap': 'libs/libs.js',
    'symbol-observable': 'libs/libs.js'
};

var packages = {
    'app': { main: 'main', defaultExtension: 'js' },
    'rxjs': { main: 'Rx.js',  defaultExtension: 'js' },
    'zonejs': { main: 'zone', defaultExtension: 'js' },
    'reflect-metadata': { main: 'Reflect', defaultExtension: 'js' }
};
```

gulpfile

```
gulp.task('bundle:libs', function () {
    return gulp.src([
        'node_modules/jquery/dist/jquery.min.js',
        'node_modules/ng2-bootstrap/bundles/ng2-bootstrap.js',
        'node_modules/jquery-slimscroll/jquery.slimscroll.min.js',
        'extScripts/hammer.min.js',
        'public/css/AdminLte/js/app.min.js',
        //'node_modules/moment/moment.js'
    ])
        .pipe(concat('libs.js'))
        .pipe(gulp.dest('dist/libs'));
});
```

Gulp compiler works, but when I start loading the app following error occurs:

```
vendors.js:2298 Unhandled promise rejection
message: "Unexpected directive value 'undefined' on the View of component 'HomePage'"

```

home.ts

```
import {DROPDOWN_DIRECTIVES} from 'ng2-bootstrap/ng2-bootstrap';
...

@Component({
    selector: 'start-page',
    templateUrl: 'public/app/views/home/home.html',
    directives: [DROPDOWN_DIRECTIVES, CORE_DIRECTIVES, TimesList]
})

```

If I debug the js file: 

ng2_bootstrap_1.DROPDOWN_DIRECTIVES -> undefined
and ng2_bootstrap_1 is an object with properties like AttrRecognizer, DIRECTION_ALL: 30 etc.

I tried to add the ng2-bootstrap.min.js (from node_modules/bundles) in my index.html manually, but then the gulp task exited with an error: no file or directory ...component/accordion...
Why is there a reference in the bundle file to the components folder?

The trick with import {directice_name} from 'ng2-bootstrap/ng2-bootstrap' is not working because this results in same error or in ...libs.js/ng2-bootstrap.js is not found error (depending on systemjs config)

-> 

So how can I add it to my app correctly without adding the whole node_modules/ng2-bootstrap folder? All workarounds I found here resulted in errors...

**Comment by vmironovs** [comment]
why you din`t use   'node_modules/ng2-bootstrap/ng2-bootstrap.js'?

**Comment by Skuriles** [comment]
With this solution gulp tasks run, but If I start my app I get error: "require is not defined"
in this line:
var accordion_1 = require('./components/accordion');

**Comment by vmironovs** [comment]
i use in my project  ng2-bootstrap.js from 'node_modules/ng2-bootstrap/ng2-bootstrap.js' but not  'node_modules/ng2-bootstrap/bundles/ng2-bootstrap.js'. and don`t have problem..
at the packeges set to`'ng2-bootstrap': { main: 'ng2-bootstrap.js', defaultExtension: 'js' }`,

**Comment by Skuriles** [comment]
As said: If I use node_modules/ng2-bootstrap/ng2-bootstrap.js in my libs.js instead of node_modules/ng2-bootstrap/bundles/ng2-bootstrap.js I get the "require is not defined error"

**Comment by vmironovs** [comment]
yes.. i get it to.. then added to gulpfile row 
`'node_modules/ng2-bootstrap/ng2-bootstrap.js',`

then remove this row from grunt all work fine

sorry for taken your time, may be some one else can help you :) way for dev response

**Comment by Skuriles** [comment]
Sorry, didn't get it.

what exactly shall I add and what shall I remove?

**Comment by vmironovs** [comment]
in my system.js 

```
 var map = { 
    '@angular': 'node_modules/@angular',
    .........................
    'ng2-bootstrap': 'node_modules/ng2-bootstrap', 
    'moment': 'node_modules/moment/moment.js'
  };
 var packages = {
   ......................................
    'ng2-bootstrap': { main: 'ng2-bootstrap.js', defaultExtension: 'js' },
  };
```

**Comment by Skuriles** [comment]
hm, problem with this is that I want to bundle all the vendor files in gulp in one vendor.js file!!

This will not work with this solution. So I thought the bundles/ng2-bootstrap.js is the rigth file, but this throws error...

Maybe I have to rethink of my "bundle all in one js file" solution

**Comment by Skuriles** [comment]
So I got this to work with systemjs builder. 

But this error still occurs if I you use 
import {MODAL_DIRECTVES, BS_VIEW_PROVIDERS} from 'ng2-bootstrap/ng2-bootstrap';

Dropdown directive is working:
import {DROPDOWN_DIRECTIVES} from 'ng2-bootstrap/ng2-bootstrap';

-> I'm using RC4 and ng2-bootstrap dev branch (which is also for RC4 as I understood).

I've added 

```
public constructor(viewContainerRef:ViewContainerRef) {
    // You need this small hack in order to catch application root view container ref
    this.viewContainerRef = viewContainerRef;
  }

```

to my start.ts as well

Is only the modal directive broken?

**Comment by valorkin** [comment]
@Skuriles please check again, and pay attention modal directives name fixes( typo in name)

**Comment by Skuriles** [comment]
Just found it this morning after updating to new npm version 1.0.20. 

Modal and typeahead are working fine now!

**Comment by valorkin** [comment]
awesome!
