### ISSUE TITLE
Question: The Benefits of Using this Over Standard Bootstrap?

### ISSUE THREAD

**Issue by JessRascal** [valor-software/ngx-bootstrap#670]
Hi,

I've just started getting in to Angular2 recently and I stumbled across this project. I'm not sure what benefit it is to use this project instead of just incorporating Bootstrap in to an Angular2 project like any other project. I'm using the Bootstrap CSS and everything seems to work fine, is it that it's not recommended to link to the Bootstrap.js file for some reason, or are there other reasons why this project should be used instead?

I'm guessing I'm missing something with this so if anyone could shed some light on the benefits, or why this project is needed to use Bootstrap in an Angular2 project then it would be very much appreciated.

Cheers

**Comment by WolvenOne27** [comment]
This library is intended to replace the [JavaScript/Jquery](http://getbootstrap.com/javascript/) interaction that comes with Bootstrap out of the box, allowing you to interact with the bootstrap components in a native Angular 2 fashion using directives/components, data binding, and events. 

You can definitely keep using the css styles in your own components, in fact the library is built on top of them, so you'll get a consistent look and feel that way. 

Example: you can have a normal Bootstrap button right alongside a radio button, which just allows the ng2-bootstrap directive to handle the selection/deselection and data binding. In this case, the radioModel property will be set to the string of "Left", "Middle", or "Right" depending on which radio button is checked. Also, the button will call the okClick method when it's clicked. 

```
<div class="btn-group">
    <button type="button" class="btn btn-primary" (click)="okClick()">OK</button>
</div>  
<div class="btn-group">
    <button class="btn btn-default" [(ngModel)]="radioModel" btnRadio="Left">Left</button>
    <button class="btn btn-default" [(ngModel)]="radioModel" btnRadio="Middle">Middle</button>
    <button class="btn btn-default" [(ngModel)]="radioModel" btnRadio="Right">Right</button>
</div>
```

**Comment by Vylest** [comment]
Imagine you have a client that wants to use Angular 2 and bootstrap 4 alpha for use exclusively on  Internet Explorer 11. Many more use cases appear with such conditions. Foremost, IE11 doesn't have built in datepickers unlike Chrome.

That is the reality I am living, and with all the release candidates coming out, going back to fix this packages code with every release is a real headache.

**Comment by JessRascal** [comment]
@WolvenOne27 Alright ok, so it sounds like it's just a case of allowing Bootstrap to be used in a more Angular way.

I'd have thought the example you gave would have been able to have been done without this project though, I didn't think it would matter what type of elements (i.e. Bootstrap or not Bootstrap) the click events, and data binding were attached to, Angular would just process them the same anyway. I've only been studying Angular2 for a couple of weeks though so I'm far from an expert.

Would I still be fine to link to the Bootstrap JS file so that things like the hamburger menu of a navbar could function properly, etc. or is there some reason I should stay away from using the out of the box Bootstrap JS all together?

Thanks for your input.

@Vylest Yeah the frequent updates of Angular2 have already impacted me but as you said, that's what you get for using bleeding edge technology. Hopefully there will be a stable release soon.

**Comment by WolvenOne27** [comment]
@JessRascal My example was intended to be simple and to show that you can use them together, and that's really how it was intended. This becomes much more pronounced when dealing with the more complex components like dropdowns and modals. 

I think your question mainly comes down to whether you want to have two different ways of your code interacting with the UI: jQuery (programmatically interacting with the elements directly in your code) and Angular2 (data binding and events). While that can be done, I don't think that it should be done (if it can be avoided), especially if those features are available in this toolkit and you intend to use it anyway. Back to your original question, that's why this toolkit was created, so we wouldn't have to pollute Angular2 apps with jQuery, using two very different conventions of interacting with the UI.

**Comment by JessRascal** [comment]
@WolvenOne27 Yeah after looking in to this further I agree that my question seems to really come down to if it's possible to use jQuery, and Angular2 together which turns out is really not recommended. From my understanding, the main issue is that Angular2 should be in charge of the DOM so having jQuery in there as well could create problems (which is what you seem to have just said).

My aim now is to integrate this toolkit (I'm literally just about to attempt that now), and then do my very best not to involve jQuery at all which would seem to be your recommendation as well.

My understanding of this is definitely improving so thanks for your help with that, it's much appreciated.
