### ISSUE TITLE
Dropdowns: autoClose attribute does not work

### ISSUE THREAD

**Issue by iradovanovic** [valor-software/ngx-bootstrap#672]
If I try to set [autoClose] to 'nonInput' or 'outsideClick' that will be ignored. Dropdown will close anyway, everytime.

```
<div dropdown (onToggle)="dropdownToggled($event)" [autoClose]="'nonInput'">
    <div class="dropdown-toggle-btn" [class.disabled]="isDisabled()">
        <i class="fa fa-ellipsis-v" dropdownToggle [disabled]="isDisabled()"></i></div>
    <div class="dropdown-menu"> . . .</div>
</div>
```

**Comment by adrianfaciu** [comment]
Not sure why it's not working for you, I have dropdowns with both options 'nonInput' or 'outsideClick' and they work as expected.

Can you show a complete example on how are you able to reproduce this ?

**Comment by camatangelo** [comment]
Also having this issue - using version `1.0.16`

**Comment by camatangelo** [comment]
@iradovanovic - does `"'disabled'"` work for you - that seems to be one of the options that I can get working, however `"'outsideClick'"` also does not work. Like so...

```
 <div class="" dropdown 
                  [(isOpen)]="status.isopen"
                  (onToggle)="onToggle($event)"
                  [autoClose]="'disabled'"
                  [ngStyle]="styles">
```

**Comment by iradovanovic** [comment]
I have to check. sorry, i'm on vacation now :)

**Comment by Dinistro** [comment]
@rgbchris Can you upgrade to 1.0.20?

**Comment by camatangelo** [comment]
@Dinistro - tried upgrading to 1.0.20 and 1.0.22 but no luck - `"'outsideClick'"` doesn't seem to work, it always closes the dropdown whenever I click on the dropdown-menu.

**Comment by adrianfaciu** [comment]
[Here's an example](http://plnkr.co/dvZwTrBADSWlhaE7w1pt) with 'outsideClick', working as expected. Can you update the sample to show how you can reproduce this ?

**Comment by camatangelo** [comment]
@adrianfaciu & @Dinistro - got it working, I was kebab casing my `dropdownMenu` directive [facepalm] .  I assume that's what @iradovanovic was doing as well.

**Comment by valorkin** [comment]
@rgbchris it happens :)

**Comment by valorkin** [comment]
@adrianfaciu thanks for help

**Comment by Xalior** [comment]
1 hour of debugging later and this happened to me also. I make this comment purely to help google find this page for others `<li dropdown [autoClose]="'nonInput'">`  does not to work when `dropdownMenu ` is misspelt as dropDownMenu. 👍
