### ISSUE TITLE
Does not trigger onPageChanged

### ISSUE THREAD

**Issue by sudheerec107** [valor-software/ngx-bootstrap#674]
pager on click of next or previous button does not trigger onPageChanged event

**Comment by Dinistro** [comment]
@sudheerec107 @ashok176 I can not reproduce this Issue. What have you tried, can you please add parts of your code?

**Comment by adrianfaciu** [comment]
See [this issue](https://github.com/valor-software/ng2-bootstrap/issues/595), event is called pageChanged. I'll submit a pull request to update the demo code.
