### ISSUE TITLE
No value accessor for '' when trying to use datepicker direcitve

### ISSUE THREAD

**Issue by moellerchen** [valor-software/ngx-bootstrap#680]
I'm not sure if this is the right place to post this, but I could not find any solution elsewhere. 

I am trying to use the Datepicker Directive and keep getting this error:

> browser_adapter.ts:74 Error: No value accessor for ''
>     at new BaseException (exceptions.ts:13)
>     at _throwError (shared.ts:57)
>     at Object.setUpControl (shared.ts:29)
>     at NgModel._addStandaloneControl (ng_model.ts:72)
>     at NgModel._addControl (ng_model.ts:67)
>     at NgModel.ngOnChanges (ng_model.ts:36)
>     at DebugAppView._View_TimeRecordingComponent0.detectChangesInternal (TimeRecordingComponent.template.js:296)
>     at DebugAppView.AppView.detectChanges (view.ts:255)
>     at DebugAppView.detectChanges (view.ts:372)
>     at DebugAppView.AppView.detectViewChildrenChanges (view.ts:283)

This is my Component including the Datepicker: 

> import { Component } from '@angular/core';
> import {CORE_DIRECTIVES, FORM_DIRECTIVES} from '@angular/common';
> 
> import { DATEPICKER_DIRECTIVES } from 'ng2-bootstrap/ng2-bootstrap';
> 
> @Component({
>   selector: 'time-recording-form',
>   template: `<h2>Datepicker</h2>
>                 <div style="display:inline-block; min-height:290px;">
>                   <datepicker [(ngModel)]="dt" [minDate]="minDate" [showWeeks]="true"></datepicker>
>                 </div>`,
>   directives: [DATEPICKER_DIRECTIVES, CORE_DIRECTIVES, FORM_DIRECTIVES]
> })
> 
> export class TimeRecordingForm {
> 
>   public dt : Date = new Date();
>   public minDate : Date = void 0;
> 
>   constructor() {
>     (this.minDate = new Date()).setDate(this.minDate.getDate() - 1000);
>   }
> }

And the AppComponent importing the first Component: 

```
import { Component } from '@angular/core';

import { TimeRecordingForm } from './time-recording-form.component';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  template: '<time-recording-form></time-recording-form>',
  directives: [TimeRecordingForm],
  styleUrls: ['./app.component.css']
})

export class AppComponent { }
```

**Comment by Dinistro** [comment]
The new form API is currently not supported. You need to wait for this PR to be merged: #678
