### ISSUE TITLE
typeaheadOptionField option useless with async queries

### ISSUE THREAD

**Issue by okaufmann** [valor-software/ngx-bootstrap#685]
I use the `typehead` directive to search a backend of people. There a data structure like the following will be returned:

``` json
[{
  "id": 1,
   "name": "Hennry"
},
{
   "id":2,
   "name": "John"
}]
```

When I set the attribute `typeaheadOptionField` to "name" there's still `[Object object]` shown up.

![image](https://cloud.githubusercontent.com/assets/4414498/16556318/a5be7a64-41d9-11e6-865f-f02e20eb7b79.png)

I tried with a Observable Datasource and a Promise one. Non of them worked.

Any Ideas what I doing wrong ?

**Comment by adrianfaciu** [comment]
Check how you're setting the value, to be sure it's a string. For example: `[typeaheadOptionField]="'name'"`. If you forget the '' surrounding the name you'll get the behaviour you're describing.

**Comment by okaufmann** [comment]
Hi,

I just had "name".... 

Thank you
