### ISSUE TITLE
Typeahead TAB unwanted behavior

### ISSUE THREAD

**Issue by rbaarsma** [valor-software/ngx-bootstrap#686]
The typeahead specifically selects the active match when pressing TAB, but I think this is simply wrong.

ENTER should select the active match (as it does)
TAB should not select anything and simply move to the next field (default behavior)

To fix this only a single line needs to change in `typeahead.directive.ts`:
145      this.container.selectActiveMatch();
==>
145      this.hide()

If you guys agree I could make a pull request, but it would be simpler for me if someone from the core team can just fix it ;)

**Comment by Dinistro** [comment]
In #490 someone asked to add this "feature".

**Comment by karthikv-26** [comment]
@rbaarsma Any idea on when would this fix be available to download through NPM?
