### ISSUE TITLE
Vertical positioning problem with tooltips when wrapping text

### ISSUE THREAD

**Issue by keliel** [valor-software/ngx-bootstrap#688]
When a tooltip is forced to wrap its content, it is no longer positioned correctly in vertical space. (not moved upwards)

![image](https://cloud.githubusercontent.com/assets/5556710/16570017/0cd40606-423e-11e6-8fdb-8022f49098bf.png)

_Sidenote: This causes a bug with the hover effect in cases with little space available._

**Comment by PEsteves8** [comment]
I solved that problem for now, by using this:
.some-container .tooltip .tooltip-inner {
  width: 7em;
  white-space: normal;
}

From https://github.com/valor-software/ng2-bootstrap/issues/808

EDIT:

Actually to avoid using the general .css file I found out I could use this in styles of the component that is using the tooltips:

:host /deep/ .tooltip .tooltip-inner {
  max-width: none;
  white-space: nowrap;
}

**Comment by Manningham** [comment]
@PEsteves8 thank you! :D

**Comment by valorkin** [comment]
Should be fixed
