### ISSUE TITLE
about problem with use

### ISSUE THREAD

**Issue by SallyOne** [valor-software/ngx-bootstrap#69]
hi,i use ng2-bootstrap directives,version 1.0.0-beta2,but i find in console have two error ,
Uncaught SyntaxError: Unexpected token <  and Uncaught SyntaxError: Unexpected token <
    Evaluating http://localhost:3000/ng-bootstrap2/ng-bootstrap2
    Error loading http://localhost:3000/app/boot.js,i don't kown where error,what should i do???

**Comment by valorkin** [comment]
hi, link to your repo please
it is not bootstrap problem, rather static file server configuration
but I see it second time
so how are you starting an app?

**Comment by SallyOne** [comment]
"scripts": {
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "start": "concurrent 'npm run tsc:w' 'npm run lite'"
  },
this is my package.json ,angular2 official website 5min quickstart have this configuration。

**Comment by valorkin** [comment]
just push your current work dir as some public repo and give a link here
it will be faster for me to reproduce and fix issue

**Comment by SallyOne** [comment]
https://github.com/SallyOne/TheieX

**Comment by valorkin** [comment]
@SallyOne all simple
update you systemjs config in index.html

``` js
        System.config({
            packages: {
                './app': {
                    format: 'register',
                    defaultExtension: 'js'
                },
                'ng2-bootstrap': {
                    defaultExtension: 'js'
                }
            },
            map: {
                // place for ng2 modules mapping
                'ng2-bootstrap': 'node_modules/ng2-bootstrap'
            }
        });
```

**Comment by valorkin** [comment]
adding 
`<alert type="info" dismissible="true">Welcome to Angular 2 QuickStart</alert>` to content.html
produces

**Comment by valorkin** [comment]
![d08d371253f39c02c242a68c57b141b6](https://cloud.githubusercontent.com/assets/1107171/12262397/5ffac712-b930-11e5-867d-e2ef07e79f0f.png)

**Comment by valorkin** [comment]
I tried to explain how to solve this issue here https://github.com/angular/angular.io/pull/681

**Comment by SallyOne** [comment]
thankyou very much.
