### ISSUE TITLE
fix the travis-ci build

### ISSUE THREAD

**Issue by Dinistro** [valor-software/ngx-bootstrap#690]
As we already noticed, the travis build is failing. We have to fix this as soon as possible, otherwise we have problems verifying PRs. 

Link to a failed build: https://travis-ci.org/valor-software/ng2-bootstrap/builds/142375294

Note: I can not reproduce this in my linux ubuntu VM. But I found something interesting only in travis:

> ../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler

https://travis-ci.org/valor-software/ng2-bootstrap/builds/142375294#L320

And after that, there are a lot of warnings and errors.

@valorkin Perhaps you know someone in the team that can fix this.

**Comment by valorkin** [comment]
compression webpack plugin -> failing to load zopfli
I am ill and will get to work only next week, sorry about it :(
@otelnov has access to merging into development here
if you have any ideas I will much appreciate it :)

**Comment by Dinistro** [comment]
@valorkin get well soon :(

Unluckily I have zero experience with travis, so I think that I will not be able to help here. 

But one think I can add:

My VM is also not able to load zopfli, but it works anyway.

**Comment by Dinistro** [comment]
Should be fixed with #691
