### ISSUE TITLE
Tooltip set tooltiphtml did not work! can not show tip.

### ISSUE THREAD

**Issue by liuxue0905** [valor-software/ngx-bootstrap#693]
Tooltip set tooltiphtml did not work! can not show tip.
Even official demo
http://valor-software.com/ng2-bootstrap/#/tooltip

**Comment by adrianfaciu** [comment]
This is not yet implemented. Although there is a [pull request](https://github.com/valor-software/ng2-bootstrap/pull/562) open.

**Comment by liuxue0905** [comment]
T_T
