### ISSUE TITLE
Tab active attribute works only for first change

### ISSUE THREAD

**Issue by ttecho** [valor-software/ngx-bootstrap#694]
When you use [active]="tabs[0].active" this works only the first time. 

If I click to change tabs and then attempt to reset the first tab to active in the .ts using `this.tabs[0].active = true` The tab is not shown as active.

This behavior can be seen in [plunker here](http://plnkr.co/edit/Z0X76NSiRqUpamq9ijF2?p=preview)

**Comment by slubowsky** [comment]
Setting the tab active to false when it becomes inactive fixes the problem. See http://plnkr.co/edit/Rd8FFdo7VXledhOclzVc?p=preview

**Comment by valorkin** [comment]
@ttecho it seems to be working @slubowsky sample

**Comment by tmoodley** [comment]
This worked this.tabs[0].active = true when I added it to the ngOnInit();

**Comment by phil123456** [comment]
changing the tab also does not update the variable, is double binding supported?
