### ISSUE TITLE
Need way to veto tab selected

### ISSUE THREAD

**Issue by slubowsky** [valor-software/ngx-bootstrap#699]
Using tabs with tab.active bound to my models tab.active I register for the select event and only set the "active" flag on my tab model to true if certain conditions are met (actually poping up an observable save dialog and giving option to cancel). When I dont set active to true I am left with a model that is out of sync with the UI. My model thinks tab 1 is active and the UI shows tab 2 is active. How can I force the UI to resync with the model and show the correct tab to be active. (short of toggling the tabs variable in a timeout)

**Comment by valorkin** [comment]
Seems you are doing some some stuff our of `zone` lifecycle
you can try to use `mark for check` or some thing similar
this one could be helpfull
https://angular.io/docs/ts/latest/api/core/index/ChangeDetectorRef-class.html

**Comment by slubowsky** [comment]
I dont think its anything I'm doing out of the zone because I'm not doing anything!.  I'm simply not updating the active flag on my tab model to be true - expecting that the UI will then match my model and not show the tab as active, but it doesn't. (i.e. Im trying to ignore the active by not updating the active flag on my model object)
I looked around a bit and think that this is probably the same issue as https://github.com/valor-software/ng2-bootstrap/issues/694. The UI doesn't stay in sync with the active flag on the tabs as would be expected.
I tried adding a call to ChangeDetectionRef.detectChanges after active on the model and the UI are out of sync to the plunker for that issue and it did not help.

**Comment by valorkin** [comment]
Hey, can try immutable change of tab object?
Show me peace of code where you set tab active

**Comment by slubowsky** [comment]
Not sure what you mean. Basically I think its confusion on my part about the relation between the initial model that provides the inputs for the tabs and what happens when changes are made later.

If you dont do the equivalent of the code in the demo
(select)="tabz.active = true"
(deselect)="tabz.active = false"
Then the model and the UI will not be in sync. This is I think the problem in issue #694. The active state for tab #1 is never set to false - nor are any others set to true.. Setting the first to true again has no effect since its already true... This quickly becomes confusing as the model and the UI get out of sync

In my case I do keep everything in sync and set the selected tab.active to true and set all the rest of the tabs.active to false whenever selected is fired (I dont listen for deselect at all). This works as expected. Then in the case when I want to veto the tab becoming active I simply dont set the new tab to active or the old one to false. At this point the model and the UI are now out of sync - just as in the original case where they become out of sync when you dont listen to select/deselect and set the active flag.

The hack I used to get them back into sync is to set tabs to null and then in a timeout set them back to my original unchanged model.

Basically Im doing something like below (couldn't get plunker working with current version of angular and ng2-bootstrap)
In template:

```
<tabset>
    <tab *ngFor="let tabz of tabs"
         [heading]="tabz.title"
         [active]="tabz.active"
         (select)="tabSelected(tabz)">
    </tab>
</tabset>
```

Then in code

```
tabSelected(tab: any): void {
    let deactivate = false; // really gets it from an observable
    if (deactivate) {
        this.tabs.forEach(t => {
            t.active = t === tab;
        });
    } else {
        //this.changeDetectorRef.markForCheck(); -- doesnt help
        //this.changeDetectorRef.detectChanges(); -- doesnt help

         // Hack to resync UI to model.
        let tabs = this.tabs;
        this.tabs = [{}];
        setTimeout(() => {
            this.tabs = tabs;
        }, 0);
    }
}
```

**Comment by slubowsky** [comment]
Just to keep this issue updated my current workaround (since I now have the TabsetComponent as a ViewChild anyway to workaround another issue) is:
```
if (!success) {
    const activeTabIndex = this.tabs.findIndex(t => t.active); // find which tab my model thinks is active
    this.tabset.tabs.forEach((t, index) => t.active = index === activeTabIndex); // make the tabset component tabs match
    this.changeDetectorRef.markForCheck();
}
```
where success is false if the canDeactivate guard resolves to false.

**Comment by szh** [comment]
Are there plans to implement this natively?

**Comment by IlyaSurmay** [comment]
Closing this in favor of #1502
