### ISSUE TITLE
Modal as a separate component?

### ISSUE THREAD

**Issue by csquillen** [valor-software/ngx-bootstrap#701]
Is it possible to use the modal as a separate component?  In other words, is it possible to put the modal button in another component's template?  Like so:

```
<!-- Page/component that uses the modal -->

<button class="btn btn-primary" (click)="lgModal.show()">Large modal</button>

<modal></modal>  <!-- Modal component that encapsulates the modal's markup and code -->
```

When I try this, I get the following error:

TypeError: Cannot read property 'show' of undefined

**Comment by valorkin** [comment]
yes, you can
but then you need to expose your component API
and add `exportAs` to component declaration
https://github.com/valor-software/ng2-bootstrap/blob/development/components/modal/modal.component.ts#L30

**Comment by marcoturi** [comment]
@valorkin Your link is not working anymore. Any chance to get an example/plunker ?

**Comment by vovkats** [comment]
@valorkin please, fix link
