### ISSUE TITLE
Close modal via JavaScript?

### ISSUE THREAD

**Issue by csquillen** [valor-software/ngx-bootstrap#702]
How do you close the modal via JavaScript?  Specifically, I have a modal form and need to close the modal after submitting the form.

**Comment by Dinistro** [comment]
@cquillen2003 Do you want to close the model in a component? If yes, you can grab it with `@ViewChild()` like this:

`@ViewChild(ModalDirective) modal : ModalDirective;`

and now, you can use

`this.modal.hide()`

to close it.

**Comment by valorkin** [comment]
added sample to demo page
