### ISSUE TITLE
Cannot install on Angular 2.0.0-rc4

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#717]
npm install ng2-bootstrap --save

npm WARN peerDependencies The peer dependency @angular/router@3.0.0-beta.2 included from ng2-bootstrap will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ng2-bootstrap" "--save"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

**Comment by Dinistro** [comment]
@Toadskin It seems like you missed the router 3.0.0.beta-2 in your `package.json`. Can you add it and try again? If this doesn't work, you can add the `package.json` here and I will hopefully be able to help you.

**Comment by valorkin** [comment]
@Dinistro @Toadskin 
router removed from peer decencies, please check latest version
