### ISSUE TITLE
Upgrading to 1.0.18 breaks application

### ISSUE THREAD

**Issue by ArtemBrovko** [valor-software/ngx-bootstrap#718]
Just upgraded ng2-bootstrap to version 1.0.18 and started receiving this error in console every time I load my application

> Error: (SystemJS) ReferenceError: __decorate is not defined
>         at eval (http://localhost:3000/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:30:5)
>         at Object.eval (http://localhost:3000/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:46:2)
>         at eval (http://localhost:3000/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:49:4)
>         at eval (http://localhost:3000/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:50:3)
>     Evaluating http://localhost:3000/node_modules/ng2-bootstrap/components/accordion/accordion.component.js
>     Evaluating http://localhost:3000/node_modules/ng2-bootstrap/components/accordion.js
>     Evaluating http://localhost:3000/node_modules/ng2-bootstrap/ng2-bootstrap.js
>     Evaluating http://localhost:3000/build/component/configuration/configuration-mode.component.js
>     Evaluating http://localhost:3000/build/component/configuration/routes.js
>     Evaluating http://localhost:3000/build/app.routes.js
>     Evaluating http://localhost:3000/build/main.js
>     Error loading http://localhost:3000/build/main.js

Downgrading to 1.0.17 resolves this issue.
Thanks in advance

**Comment by slubowsky** [comment]
See https://github.com/valor-software/ng2-bootstrap/issues/719

**Comment by Dinistro** [comment]
@ArtemBrovko Fixed in `1.0.20`
