### ISSUE TITLE
Checkbox  directive error, @angular/forms. 

### ISSUE THREAD

**Issue by dessalines** [valor-software/ngx-bootstrap#725]
Here's an error I'm getting now in the console:
`Error loading http://localhost:4200/vendor/@angular/forms as "@angular/forms" from http://localhost:4200/vendor/ng2-bootstrap/components/buttons/button-checkbox.directive.js"`

**Comment by Dinistro** [comment]
Do you use the `@angular/forms`? If not, we found the issue.

**Comment by dessalines** [comment]
I think so, should I upgrade to `@angular-rc3` and the new angular forms?

**Comment by Dinistro** [comment]
@tchoulihan You can upgrade to rc.4 and `@angular/forms@0.2.0`. Then it should work without a problem.

If you install ng2-bootstrap@1.0.22 these are peer-dependencies: 
https://github.com/valor-software/ng2-bootstrap/blob/development/package.json#L55-L60

**Comment by dessalines** [comment]
Okay cool, thanks!

**Comment by valorkin** [comment]
@tchoulihan please recheck an confirm that all ok

**Comment by dessalines** [comment]
I think I have this working okay, now I'm having trouble getting the upgraded typeahead to work, because the example doesn't use a real observable. You can close this issue out, I'll make another one for that.
