### ISSUE TITLE
The right way to reset modal content

### ISSUE THREAD

**Issue by PRR24** [valor-software/ngx-bootstrap#734]
What is the current recommended solution to reset modal content on each show?
Smth like in Angular1, $modal created a new controller/template on each call.

Without resetting the modal I have two issues:
- there is no way to reset the form used in my bsModal, so after first use the settings are unexpected
- can't get autofocus to work

Sorry, if it is a trivial question, but could not find any doc or sample about it.
Any comments/suggestions appreciated.

**Comment by valorkin** [comment]
modals is not a solution, it is just a tool to should your component in a popup
any way, best way to reset something is to clean or reset value to default (it does not relate to modal)
if you have a form in modal, use `form.reset()`
