### ISSUE TITLE
Error when using btnCheckbox

### ISSUE THREAD

**Issue by WolvenOne27** [valor-software/ngx-bootstrap#735]
I'm receiving the following error when using the btnCheckbox directive:

> EXCEPTION:
> Error in app/Home/home.component.html:38:47
> ORIGINAL EXCEPTION: No value accessor for ''
> ERROR CONTEXT:
>     at DebugAppView.prototype._rethrowWithContext (eval code:12264:21)
>     at DebugAppView.prototype.detectChanges (eval code:12250:17)
>     at AppView.prototype.detectViewChildrenChanges (eval code:12169:17)
>     at AppView.prototype.detectChangesInternal (eval code:12154:13)
>     at AppView.prototype.detectChanges (eval code:12143:13)
>     at DebugAppView.prototype.detectChanges (eval code:12247:17)
>     at AppView.prototype.detectViewChildrenChanges (eval code:12169:
>     at AppView.prototype.detectChanges (eval code:12143:13)
>     at AppView.prototype.detectChanges (eval code:12143:13)
>     at DebugAppView.prototype.detectChanges (eval code:12247:17)

There are several other errors that show up in the console, but they all seem to boil down to 

> No value accessor for ''

I'm using 

> "@angular/***": "2.0.0-rc.4",
> "@angular/forms": "0.2.0",
> "ng2-bootstrap": "1.0.22"

I have the Core, Form, and Button directives passed as directives into the component. 
My Html is:
`<label class="btn btn-primary" [(ngModel)]="checkModel" btnCheckbox>Checkbox</label>`

My property is:
`public checkModel: boolean = false;`

The exact same code was working prior to my upgrade from RC1 to RC4. 
Also, after playing around with variations, it appears that it only breaks when I add in `[(ngModel)]`

Any ideas on how to get this working?

**Comment by adrianfaciu** [comment]
Do you have BUTTON_DIRECTIVES added to the component directives ?

**Comment by valorkin** [comment]
you should import ngModel from angular/forms

**Comment by WolvenOne27** [comment]
Yes, I have the following directives referenced in the `@Component`: selector

> directives: [BUTTON_DIRECTIVES, DROPDOWN_DIRECTIVES, CORE_DIRECTIVES, FORM_DIRECTIVES, ROUTER_DIRECTIVES, NgModel ]

I just added the import of NgModel from `@angular/forms` and added it as a directive (shown above); however, I'm still seeing the same error.

**Comment by valorkin** [comment]
@WolvenOne27 show your import part, where do you get `FORM_DIRECTIVES`

**Comment by valorkin** [comment]
BTW you don't need ngModel if you have `FORM_DIRECTIVES`

**Comment by WolvenOne27** [comment]
I only added NgModel because it was suggested here. 
This is the current file in its entirety:

```
import { Component } from '@angular/core';
import { CORE_DIRECTIVES } from '@angular/common';
import { FORM_DIRECTIVES, NgModel } from '@angular/forms';
import { HTTP_PROVIDERS } from '@angular/http';
import { ROUTER_DIRECTIVES } from '@angular/router';

import { BUTTON_DIRECTIVES, DROPDOWN_DIRECTIVES } from 'ng2-bootstrap/ng2-bootstrap';

@Component({
    selector: 'home-component',
    templateUrl: 'app/Home/home.component.html',
    directives: [BUTTON_DIRECTIVES, DROPDOWN_DIRECTIVES, CORE_DIRECTIVES, FORM_DIRECTIVES, ROUTER_DIRECTIVES, NgModel ]
})
export class HomeComponent {
    public radioModel: string = 'Middle';
    public checkModel: boolean = false;
    public disabled: boolean = false;
    public status: { isopen: boolean } = { isopen: false };


    constructor() {
    }

    btnClick(text: string, type: string) {
        toastr[type](text);
    }
}

```

**Comment by xtiancapil** [comment]
@WolvenOne27 Take a look at issue #722. I upgraded from 1.0.17 to 1.0.23 and had to add these two lines to my app.ts and it started working for me. Hope that helps

https://github.com/valor-software/ng2-bootstrap/blob/development/demo/index.ts#L57-L58

**Comment by WolvenOne27** [comment]
@xtiancapil Adding those two lines to the bootstrapping fixed the issue. However, that solution is not an obvious one. We'll probably want to add that to the ng2-bootstrap usage and documentation, at least until Angular2 itself removes the need for using disableDeprecatedForms.

**Comment by valorkin** [comment]
@WolvenOne27 oh, it is angular2 breaking change, not ng2-bootstrap
if you will check issues you will see how much pain it brings :)

**Comment by WolvenOne27** [comment]
@valorkin Yeah, I understand. We're trying to hit a moving target right now with the angular2 releases. I figured if I am hitting this problem (and didn't see any other issues about it) I should create one in case others run into it also.

I appreciate having ng2-bootstrap available. Keep up the good work!

**Comment by valorkin** [comment]
Thanks!
