### ISSUE TITLE
Transition between slides

### ISSUE THREAD

**Issue by JW2006778** [valor-software/ngx-bootstrap#740]
I'm grateful to the author for this marvelous Bootstrap plugin for Angular. I implemented carousel slides in my project but one thing: there is no transition between images. Is there any other variables should be defined? Thanks in advance.

**Comment by valorkin** [comment]
@yaoshuqi as soon as ng2 animate will became a bit more stable
animation option will be added to a lot of things here

**Comment by mkwsra** [comment]
Is there any news about this ability?

**Comment by rajtukadia** [comment]
@valorkin there is no transition between images, any other way to transition possible?
