### ISSUE TITLE
Error: (SystemJS) Error: XHR error (404) loading https://npmcdn.com/@angular/src/forms

### ISSUE THREAD

**Issue by MichaelGradek** [valor-software/ngx-bootstrap#744]
I get this error when I'm trying to implements modals using your documentation

**package.json:**

```
"dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "3.0.0-alpha.7",
    "@angular/upgrade": "2.0.0-rc.4",
    "angular2-jwt": "0.1.16",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.0",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "font-awesome": "4.6.3",
    "ng2-bootstrap": "1.0.23",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.31",
    "zone.js": "^0.6.12"
  },
```

Th error appears as soon as I pass BS_VIEW_PROVIDERS into the viewProviders key in the @Components

**my.component.ts**

```
import {BS_VIEW_PROVIDERS, MODAL_DIRECTIVES} from 'ng2-bootstrap/ng2-bootstrap';

@Component({
    templateUrl: '/app/my.template.html',
    viewProviders: [BS_VIEW_PROVIDERS],
    directives: [MODAL_DIRECTIVES]
})
export class MyComponent {
...
}
```

**Comment by Dinistro** [comment]
@MichaelGradek You have to use the new @angular/forms. 

https://angular.io/docs/ts/latest/guide/forms.html

**Comment by MichaelGradek** [comment]
My project doesn't use @angular/forms, but ng2-bootstrap has it as a dependency. I think ng2-bootstrap is causing this error.

Does this mean you have to update the dependency to point to the new @angular/forms in your code?

**Comment by Dinistro** [comment]
@MichaelGradek You are using rc.4, so you should use the @angular/forms. The other once are already deprecated.
