### ISSUE TITLE
Datepicker and Bootstrap 4 compatibility 

### ISSUE THREAD

**Issue by omargon** [valor-software/ngx-bootstrap#746]
I'm integrating the Datepicker with Bootstrap 4 alpha but while in your demo site it renders perfectly ones I integrate into my Bootstrap 4 application it doesn't. I compared the code and it seems that it renders Boostrap 3 code like `glyphicons` and `btn-default`. Anything I should do to make sure that the html output is compatible with Bootstrap 4?

**Comment by hongbo-miao** [comment]
Dup with https://github.com/valor-software/ng2-bootstrap/issues/507

**Comment by valorkin** [comment]
I am working on new version of datepicker, so it will be fixed soon
Closing as duplicate
