### ISSUE TITLE
v. 1.0.17 (and probably +): SystemJS is not defined when bundling the app for production

### ISSUE THREAD

**Issue by dragGH102** [valor-software/ngx-bootstrap#748]
In my Angular RC2-TS+SystemJS app I'm using ng2-bootstrap's **dropdown** and **datepicker** components.

In **development** mode (no bundling, minification etc. as n https://angular.io/'s starter tutorial) everything works fine.

However when bundling it for production (I'm not using Angular-CLI but Gulp based on https://github.com/templth/angular2-packaging), I get this issue:

> Uncaught ReferenceError: System is not defined

First error is thrown at this line:

> System.registerDynamic("ng2-bootstrap/components/accordion/accordion.component", ["@angular/core"], true, function($__require, exports, module) {

Looks like **ng2-bootstrap can't find SystemJS as SystemJS builder (used to pack dependencies for production) probably doesn't expose it the way ng2-bootstrap expects**.

I see 2 **possible solutions**:
- allow **initialing ng2-bootstrap bundle by passing SystemJS into it manually** (not sure how it could work however)
- allow **registering single ng2-bootstrap's components** directly into systemjs.config.js file (If this is already possible, please explain **how to do it**).

Thanks for the consideration.

**Comment by valorkin** [comment]
ng2-bootstrap available in common.js and system.js (bundles)
choose right one for you
but if you choose system.js bundles it is obvious to provide system.js itself
or use common.js version

**Comment by dragGH102** [comment]
@valorkin it is fine for me to use CommonJS However can you please explain how to use it to include ng2-bootstrap? (of if there is a tutorial)

**EDIT**: I looked into http://valor-software.com/ng2-bootstrap/#/ but as I remembered there is no clear explanation about CommonJS implementation

Also, for future reference, how to pass SystemJS into ng2-bootstrap's init?

**Comment by valorkin** [comment]
system.js bundles is mainly for such usage: https://github.com/valor-software/angular2-quickstart
common.js for webpack, gulp, or other bundlers

**Comment by dragGH102** [comment]
@valorkin I appareciate your answer and not to be insisting but following your links only leads to:
- SystemJS setup
- weppack setup for ng2 (in general, not even referred to ng2-bootstrap)

So, unless I'm missing some determining piece of information (it could be), I really don't see **how to include ng2-bootstrap with a commonjs+systemjs (not webpack) configuration.**

Thank you for understanding

**Comment by dragGH102** [comment]
I looked into it and you say

> ng2-bootstrap available in common.js .. bundles

where is the commonjs bundle?
Via npm I could install ng2-bootstrap but I only see 2 files: ng2-bootstrap.js and ng2-bootstrap.min.ts both will calls to **System.register...** (and no .ts file to just include it manually in my Typescript project)

**EDIT**: I tried by (in index.html)

```
   <script src="../node_modules/ng2-bootstrap/ng2-bootstrap.js"></script>
```

SystemJS is not an issue this way (no System calls in that file) but insetad

> Uncaught ReferenceError: require is not defined

**Comment by valorkin** [comment]
> Uncaught ReferenceError: require is not defined

you have copypasted sample from demo, do you? :)

**Comment by dragGH102** [comment]
@valorkin not exactly. I actually solved it (even though it was not clear at all from the docs) by adding ng2-bootstrap in systemjs config (but not index.html) so it loads it as a commonjs module (VS adding it in index.html = either required is not defined or System isn't)

**Comment by valorkin** [comment]
@dragGH102 that's true
