### ISSUE TITLE
ng2-bootstrap error with systemjs

### ISSUE THREAD

**Issue by sqlsolver** [valor-software/ngx-bootstrap#752]
ng2-bootstrap accordion component appears to conflict with systemjs loader.

Here's what's showing in the Chrome dev tools console:
`zone.js:323 Error: (SystemJS) TypeError: Reflect.getOwnMetadata is not a function at PropDecorator (http://easyofficeforms.com/easyOfficeForms/node_modules/@angular/core/bundles/core.umd.js:2817:40) at __decorate (http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:5:110) at eval (http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:39:5) at Object.eval (http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:55:2) at eval (http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:58:4) at eval (http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:59:3) Evaluating http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion/accordion.component.js Evaluating http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion.js Evaluating http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/ng2-bootstrap.js Error loading http://easyofficeforms.com/easyOfficeForms/app/EOFapp.ts
`
[http://easyofficeforms.com](http://easyofficeforms.com)

I created a second app without ng2-bootstrap and systemjs loads all the components without error.

**Comment by valorkin** [comment]
@sqlsolver please compare to sample system.js app, works fine
https://github.com/valor-software/angular2-quickstart

**Comment by valorkin** [comment]
https://www.hamsterpad.com/chat/ng2
join slack, so you can ask for help configuring app
but prepare sample repo with config to share

**Comment by sqlsolver** [comment]
Thanks - I see several things to change after viewing your sample. Good to know they work together!

**Comment by sqlsolver** [comment]
Thanks for the sample, the app is back up. The only remaining error is non-blocking:
`Failed to parse SourceMap: http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/bundles/ng2-bootstrap.min.js.map` which seems to already be on your radar #367

**Comment by valorkin** [comment]
Yeap, most probably system.js bundle will be deprecated, and one Umd bundle will replace it
