### ISSUE TITLE
 TypeAhead with initial object value #749

### ISSUE THREAD

**Issue by Kekstas** [valor-software/ngx-bootstrap#753]
Hi,

I am still having issue with Initial input field value when using TypeAhead.
Updated Plunk to use latest version. Same issue. 
http://plnkr.co/edit/WSUJ49?p=preview

> I am having trouble to set initial input field value when input value is Object using TypeAhead.
> I crated a plunk to demonstrate the issue: http://plnkr.co/edit/WSUJ49?p=preview
> 
> It is showing [object Object] because it is actually an object, but when TypeAhead getting object from [typeahead] it is able to set object to [(ngModel)] and display value described in [typeaheadOptionField]
> I need to do same but on init from object that is set in [(ngModel)].
> 
> I could see that same solution was working with angular1.
> 
> Any solutions...?
> Any comments/suggestions appreciated.
> 
> @Kekstas You are using a really old version of angular2 and ng2-bootstrap. Try to upgrade to rc.4 and ng2-bootstrap 1.0.24
> @Dinistro Dinistro closed this 18 hours ago

**Comment by Dinistro** [comment]
@Kekstas Currently you can not add the Object as Value, you need to add the field, in your example, `Alabama`;
