### ISSUE TITLE
TimePicker - readonlyInput option

### ISSUE THREAD

**Issue by antitoine** [valor-software/ngx-bootstrap#759]
Hi,

I wonder if it would be possible to make the option `readonlyInput` more efficient in the `TimePicker` component. The display style is correctly apply, but we can continue to change value in the input.

Thank

**Comment by valorkin** [comment]
hm, why would you render whole timepicker in readonly mode

**Comment by antitoine** [comment]
this makes sense with the option, right?

`readonlyInput (?boolean=false) - if true hours and minutes fields will be readonly`

For me, this option is like put the "disabled" attribute in every input

**Comment by adrianfaciu** [comment]
What would be the desired behavior here ? I would say, if read only, hide the arrows. But one could just want them there but not clickable (which would be worse from UX point of view, but would maintain the same height all the time for example). AM/PM toggle should also be affected by this.
