### ISSUE TITLE
Is there a way to bind to the "slide" and "slid" events for carousel?

### ISSUE THREAD

**Issue by quiringk** [valor-software/ngx-bootstrap#760]
Once the carousel opens and you begin sliding left or right, how do you know which slide you are on? (If the [active] attribute worked perfectly, then whatever slide is active is the one you are on. But is there a way to know when the active attribute changes?)

**Comment by valorkin** [comment]
@quiringk please join slack to ask more questions :)
https://www.hamsterpad.com/chat/ng2

**Comment by valorkin** [comment]
@quiringk if can please check my commit, does it provides required functionality?

**Comment by adrianfaciu** [comment]
This also fixes #11.

**Comment by day01** [comment]
Hi, Is a chance to merge the change to the current line?

**Comment by killface** [comment]
I, for one, would love to see this merged in. Right now there's no way to update a selected thumbnail when the carousel changes slides.

**Comment by IlyaSurmay** [comment]
CarouselComponent exposes `activeSlideChange` event https://valor-software.com/ngx-bootstrap/#/carousel#carousel-component
