### ISSUE TITLE
*ngif select=footer does not work

### ISSUE THREAD

**Issue by borgotecnologia** [valor-software/ngx-bootstrap#761]
Hi.

This is my Set:

**base-modal.component.html:**

`<div bsModal #lgModal="bs-modal" (onHide)="hideBackdrop($event)" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
  aria-hidden="true">
  <div class="modal-dialog {{size}}">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" (click)="hideBotton()" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">{{title}}</h4>
      </div>
      <div class="modal-body">
        <ng-content></ng-content>
      </div>
      <div class="modal-footer" *ngIf="hasFooter(rodape)" >
        <ng-content select="rodape"></ng-content>
      </div>
    </div>
  </div>
</div>`

**base-modal.component.ts:**

`import {Component, ViewChild, OnInit, Input, Output, EventEmitter, AfterViewInit, ElementRef, ContentChild  } from '@angular/core';
import {CORE_DIRECTIVES} from '@angular/common';
import {MODAL_DIRECTIVES, BS_VIEW_PROVIDERS} from 'ng2-bootstrap';

@Component({
  selector: "base-modal",
  directives: [MODAL_DIRECTIVES, CORE_DIRECTIVES],
  viewProviders: [BS_VIEW_PROVIDERS],
  templateUrl: "app/shared/modais/base-modal.component.html",
  exportAs: 'modal'
})

export class BaseModalComponent {
  @Input() title: string;
  @Input() size: string
  @Output()
  public aoFechar: EventEmitter<any> = new EventEmitter<any>();

  @ViewChild('lgModal') lgModal: any;
  show() {
    this.lgModal.show();
  }

  private hideBotton(valor: boolean = false) {
    this.lgModal.hide();
  }

  hideBackdrop(modal: any): void {
    this.aoFechar.emit(null);
  }

  hasFooter(valor: any): boolean { 
    return true;
  } 
}
`
**My problem is:**

When I try to make *ngIf to hide footer, I can't, because it did not find footer selected 

What I shall  do to hide footer in ng2-bootstrap?

**Comment by valorkin** [comment]
footer? like modal footer?
create a component which has you modal template and expose functionality you need

**Comment by valorkin** [comment]
join https://www.hamsterpad.com/chat/ng2 and ask more question if you like
