### ISSUE TITLE
Nested routing problem !!!!

### ISSUE THREAD

**Issue by alaa-bourouissi** [valor-software/ngx-bootstrap#762]
I want to create a nested route , so I created a Component called TableComponent and another Component calledDetailsTableComponent , The TableComponent is added to the Menu , when I open the TableComponent from the Menu  ( http://localhost:3000/#/Table) I found a link that send me to the  DetailsComponent (http://localhost:3000/#/Table/Details)

This is the hierarchy that I created : 
<details><summary>

## - the TableComponent.ts : </summary>

let template = require('./TableComponent.html');
@Component({
  selector: 'table-component',
  template: template,
  directives: [ROUTER_DIRECTIVES]
})
export  class TableComponent {
  public cursens:Array<any> = TableData;
}
</details>

<details><summary>

##  - the TableComponent.html : </summary>

......
.....
< a routerLink="/Details"></a>
< router-outlet></router-outlet>
</details>

<details><summary>

## - the Tablecomponentroutes.ts : </summary>

export const subroutes: RouterConfig = [
  {
    path: 'Table',
    component: TableComponent,
    children: [ {
        path: 'Details',
        component: DetailsTableComponent,
      }  ]}  ];
## -and in the config.ts:

  ...subroutes,
  {
    path: '',
    data: ['Getting started'],
    component: GettingStartedSectionComponent
  },
......
......
</details>

when i run the in no error in the terminal but in the Browser it blocks and in the console : 
<details>
<summary>

EXCEPTION: TypeError: self.context.$implicit.data is undefined vendor.bundle.js:42386:14</summary>

STACKTRACE: vendor.bundle.js:42386:14

anonymous/_View_MainMenuComponent4.prototype.detectChangesInternal@MainMenuComponent.template.js:415:7
AppView</AppView.prototype.detectChanges@http://localhost:3000/vendor.bundle.js:51520:10
AppView</AppView.prototype.detectContentChildrenChanges@http://localhost:3000/vendor.bundle.js:51538:14
anonymous/_View_MainMenuComponent1.prototype.detectChangesInternal@MainMenuComponent.template.js:248:3
AppView</AppView.prototype.detectChanges@http://localhost:3000/vendor.bundle.js:51520:10
AppView</AppView.prototype.detectContentChildrenChanges@http://localhost:3000/vendor.bundle.js:51538:14
anonymous/_View_MainMenuComponent0.prototype.detectChangesInternal@MainMenuComponent.template.js:110:3
AppView</AppView.prototype.detectChanges@http://localhost:3000/vendor.bundle.js:51520:10
AppView</AppView.prototype.detectViewChildrenChanges@http://localhost:3000/vendor.bundle.js:51546:14
anonymous/_View_DemoComponent0.prototype.detectChangesInternal@DemoComponent.template.js:57:3
AppView</AppView.prototype.detectChanges@http://localhost:3000/vendor.bundle.js:51520:10
AppView</AppView.prototype.detectViewChildrenChanges@http://localhost:3000/vendor.bundle.js:51546:14
anonymous/_View_DemoComponent_Host0.prototype.detectChangesInternal@DemoComponent.template.js:28:3
AppView</AppView.prototype.detectChanges@http://localhost:3000/vendor.bundle.js:51520:10
ViewRef_</ViewRef_.prototype.detectChanges@http://localhost:3000/vendor.bundle.js:38893:55
ApplicationRef_</ApplicationRef_.prototype.tick/<@http://localhost:3000/vendor.bundle.js:24760:76
ApplicationRef_</ApplicationRef_.prototype.tick@http://localhost:3000/vendor.bundle.js:24760:14
ApplicationRef_</ApplicationRef_.prototype._loadComponent@http://localhost:3000/vendor.bundle.js:24731:10
ApplicationRef_</ApplicationRef_.prototype.bootstrap/<@http://localhost:3000/vendor.bundle.js:24718:14
ApplicationRef_</ApplicationRef_.prototype.run/<@http://localhost:3000/vendor.bundle.js:24689:27
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/polyfills.bundle.js:16823:21
NgZoneImpl/this.inner<.onInvoke@http://localhost:3000/vendor.bundle.js:41365:33
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/polyfills.bundle.js:16822:21
Zone</Zone</Zone.prototype.run@http://localhost:3000/polyfills.bundle.js:16716:26
NgZoneImpl</NgZoneImpl.prototype.runInner@http://localhost:3000/vendor.bundle.js:41396:61
NgZone</NgZone.prototype.run@http://localhost:3000/vendor.bundle.js:27466:52
ApplicationRef_</ApplicationRef_.prototype.run@http://localhost:3000/vendor.bundle.js:24687:10
ApplicationRef_</ApplicationRef_.prototype.bootstrap@http://localhost:3000/vendor.bundle.js:24709:17
coreLoadAndBootstrap/</<@http://localhost:3000/vendor.bundle.js:24491:44
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/polyfills.bundle.js:16823:21
NgZoneImpl/this.inner<.onInvoke@http://localhost:3000/vendor.bundle.js:41365:33
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/polyfills.bundle.js:16822:21
Zone</Zone</Zone.prototype.run@http://localhost:3000/polyfills.bundle.js:16716:26
scheduleResolveOrReject/<@http://localhost:3000/polyfills.bundle.js:17071:54
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/polyfills.bundle.js:16856:25
NgZoneImpl/this.inner<.onInvokeTask@http://localhost:3000/vendor.bundle.js:41356:33
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/polyfills.bundle.js:16855:25
Zone</Zone</Zone.prototype.runTask@http://localhost:3000/polyfills.bundle.js:16756:30
drainMicroTaskQueue@http://localhost:3000/polyfills.bundle.js:16974:27
notify/</run@http://localhost:3000/polyfills.bundle.js:9254:23
notify/<@http://localhost:3000/polyfills.bundle.js:9267:29
module.exports/flush@http://localhost:3000/polyfills.bundle.js:7761:10
 vendor.bundle.js:42386:14

EXCEPTION: TypeError: self.context.$implicit.data is undefined vendor.bundle.js:42395
EXCEPTION: TypeError: self.context.$implicit.data is undefined vendor.bundle.js:42386:14

EXCEPTION: TypeError: self.context.$implicit.data is undefined
</details>

Please can anyone help me !!!

**Comment by valorkin** [comment]
`self.context.$implicit.data`
means that you try populate `data` in html
but it is not found in component
unfortunately it has nothing to do with ng2-bootstrap
please try to ask here https://gitter.im/angular/angular
and you need to provide your full html
