### ISSUE TITLE
Is this a complete implementation of bootstrap?

### ISSUE THREAD

**Issue by danielnieto** [valor-software/ngx-bootstrap#763]
Is this a full implementation of the whole bootstrap framework? Because I'm looking for a framework to use with Angular2 and all I've seen (Material2, MDL, Foundation, Semantic,etc) are like "work in progress" and do not have all components and features implemented yet... 

So what I'm asking here is, is ng2-bootstrap ready to create a production webapps? or what are the limitations of this project?

Thank you!

**Comment by valorkin** [comment]
1. no one will they say that lib is ready for prod while ng2 is RC, after each ng2 release we have to do a lot of changes (last pain was @angular/forms)
2. BS 4 is still work in progress and continue to add new components
3. right not ng2-bootstrap is missing popovers and scrollspy

if you have any other questions please join slack: https://www.hamsterpad.com/chat/ng2

**Comment by virtualSharif** [comment]
Is there any plan to add scrollspy in coming days?
