### ISSUE TITLE
Put BS_VIEW_PROVIDERS in other file

### ISSUE THREAD

**Issue by hoangnguyenba** [valor-software/ngx-bootstrap#765]
Hi there,

I am using your modal. 
So I need to import BS_VIEW_PROVIDERS.
`import { BS_VIEW_PROVIDERS } from 'ng2-bootstrap';`
That makes it load all components. 
But I just want to load component modal.
Is there any way to prevent this ?

**Comment by erashu212** [comment]
Hi @hoangnguyenba ,
You can use like this

```
import {MODAL_DIRECTIVES} from
'ng2-bootstrap/components/modal';
import {ComponentsHelper} from
'ng2-bootstrap/components/utils/components-helper.service';

  directives: [ MODAL_DIRECTIVES, CORE_DIRECTIVES],
  viewProviders: [{provide: ComponentsHelper, useClass: ComponentsHelper}],
```

**Comment by valorkin** [comment]
@erashu212 thanks!
