### ISSUE TITLE
Add CSS class to tab in tabset

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#766]
Hi, 

I can't find a solution to add a "custom" CSS class to tab in my tabset (I want to align only one tab to the right of stack).

Do you have planned this feature in next releases?

```
<tab [disabled]="true" [ngClass]="pull-right">
    <template tabHeading>
        TITLE
    </template>
    CONTENT
</tab>
```

There is another similar issue open https://github.com/valor-software/ng2-bootstrap/issues/443 regarding the possibility to customize tabset/tab.
Thank you!

**Comment by valorkin** [comment]
yeap

**Comment by ghost** [comment]
Any update about this issue?

**Comment by kaojo** [comment]
I am looking for same feature. 

I want to add a css class dynamically: 
`
[class.bg-info]="tabz.dragOver"
`

**Comment by Confusedfish** [comment]
Just spotted kaojo's suggestion which would be better than my pr. Not sure how to implement that though

**Comment by Confusedfish** [comment]
Having looked into how the `[class.classname]="binding"` works (fairly sure it's [here in the template parser](https://github.com/angular/angular/blob/f1b6c6efa1f25b725a8da6a3b91865698a7cafb4/modules/%40angular/compiler/src/template_parser/template_parser.ts#L958)) I can't see it being easy to implement the same behaviour. For now the PR should be enough to allow setting a custom class attribute on the element.

**Comment by kaojo** [comment]
The PR looks solid to me. Maybe add a testcase to it? 

I don't know how to upvote (or something simular) the PR since i haven't participated in that yet. I hope it gets approved soon.

**Comment by devfomichov** [comment]
Look here #1698

**Comment by valorkin** [comment]
@devfomichov thanks for replying to issues :)
