### ISSUE TITLE
Use booleans with btnRadio

### ISSUE THREAD

**Issue by JohannesRudolph** [valor-software/ngx-bootstrap#771]
Is it somehow possible to use a boolean with btnRadio instead of a string?

E.g. `btnRadio="true"` sets ngModel to `true` instead of `"true"`?

**Comment by adrianfaciu** [comment]
Since it could have more than two sates, the property is defined as string `@Input() private btnRadio:string`, so I don't see any option of using it as boolean.

You could however just convert it to a bool, or expose in your component a different property that just returns `model == 'true'`;

**Comment by ds82** [comment]
Just for docoumentation purposes:
This now works (current v1.3.3) when using [btnRadio]="true|false" binding.
