### ISSUE TITLE
Animation for the components

### ISSUE THREAD

**Issue by urosjarc** [valor-software/ngx-bootstrap#774]
Is it possible to activate animation for ng2-bootstrap components, for [example Accordion](https://angular-ui.github.io/bootstrap/#/accordion)? If not will this feature be implemented in the future?

**Comment by valorkin** [comment]
stable animation for angular2 should land with rc.5
and of course it will be added
if you can any more question please use slack:
https://www.hamsterpad.com/chat/ng2
