### ISSUE TITLE
Datepicker - default datepickerMode conflicts with minMode/maxMode

### ISSUE THREAD

**Issue by tiagoroldao** [valor-software/ngx-bootstrap#780]
When using the datepicker component, if a minMode/maxMode range is set that doesn't include the datepickerMode set, behaviour becomes buggy.

This is noticeable/a potential problem when leaving `datepickerMode` out. This:

``` html
<datepicker 
    [(ngModel)]="date" 
    [minMode]="'month'"
    [maxMode]="'month'">
</datepicker>
```

Seems expected to work properly, but doesn't, as the user sees a day picker (and for some reason the picker disappears when selecting one of those days).

**Comment by valorkin** [comment]
Makes sense, I am rewriting it, so I will take it in count
