### ISSUE TITLE
Using Pager example throws  No value accessor for ''

### ISSUE THREAD

**Issue by bjaajb11** [valor-software/ngx-bootstrap#782]
I am attempting to use the pager in 1.0.24. When I use the pagination like:
`<pagination [totalItems]="totalItems" [(ngModel)]="currentPage"  itemsPerPage="10" class="pagination-sm"
            boundaryLinks="true" rotate="true" [maxSize]="5" 
            previousText="&lsaquo;" nextText="&rsaquo;" firstText="&laquo;" lastText="&raquo;">
        </pagination>`

I get a "No value accessor for ''" error:
`browser_adapter.ts:82Error: No value accessor for ''
    at new BaseException (exceptions.ts:21)
    at _throwError (shared.ts:66)
    at Object.setUpControl (shared.ts:38)
    at NgModel.ngOnChanges (ng_model.ts:42)
    at DebugAppView._View_PaginationDemoComponent0.detectChangesInternal (PaginationDemoComponent.template.js:113)
    at DebugAppView.AppView.detectChanges (view.ts:261)
    at DebugAppView.detectChanges (view.ts:377)
    at DebugAppView.AppView.detectViewChildrenChanges (view.ts:288)
    at DebugAppView.AppView.detectChangesInternal (view.ts:273)
    at DebugAppView.AppView.detectChanges (view.ts:261)`

My test component looks like
`import {Component} from "@angular/core";
import {CORE_DIRECTIVES} from "@angular/common";
import {FORM_DIRECTIVES} from "@angular/forms";
import {PAGINATION_DIRECTIVES} from "ng2-bootstrap/ng2-bootstrap";

@Component({
    selector: "pagination-demo",
    directives: [PAGINATION_DIRECTIVES, FORM_DIRECTIVES, CORE_DIRECTIVES],
    template: `<pagination [totalItems]="totalItems" [(ngModel)]="currentPage"  itemsPerPage="10" class="pagination-sm"
            boundaryLinks="true" rotate="true" [maxSize]="5" 
            previousText="&lsaquo;" nextText="&rsaquo;" firstText="&laquo;" lastText="&raquo;">
        </pagination>`
})
export class PaginationDemoComponent {
    public totalItems: number = 64;
    public currentPage: number = 4;
    public maxSize: number = 5;

```
public bigTotalItems: number = 175;
public bigCurrentPage: number = 1;

public setPage(pageNo: number): void {
    this.currentPage = pageNo;
}

public pageChanged(event: any): void {
    console.log(`Page changed to: ${event.page}`);
    console.log(`Number items per page: ${event.itemsPerPage}`);
}
```

}`

**Comment by bjaajb11** [comment]
Found the solution from [http://stackoverflow.com/questions/38197255/forms-in-angular-2-rc4](url).

The bootstrap for the app needs to be updated to explicitly disable deprecated forms and set the new form provider. 
`import {disableDeprecatedForms, provideForms} from '@angular/forms';

bootstrap(AppComponent, [
  disableDeprecatedForms()
  provideForms()
]);`

**Comment by reach4thelasers** [comment]
this was half the solution for me.  I had to remove the FORM_DIRECTIVES import from my component and replace it with the new one:

```
import {FORM_DIRECTIVES} from '@angular/forms/src/directives'
```
