### ISSUE TITLE
Add exportAs to dropdown directive

### ISSUE THREAD

**Issue by tiagoroldao** [valor-software/ngx-bootstrap#784]
This is relevant when using multiple dropdowns in a component, and requiring programatic setting of `isOpen`, for example.

**Comment by valorkin** [comment]
@tiagoroldao nice reason to make a PR :)
`exportAs: 'bs-dropdown'`
https://github.com/valor-software/ng2-bootstrap/blob/development/components/modal/modal.component.ts#L29

**Comment by tiagoroldao** [comment]
Was going to immediately, but had to teach a class meanwhile 😄
