### ISSUE TITLE
better modals

### ISSUE THREAD

**Issue by stalniy** [valor-software/ngx-bootstrap#788]
The current concept of modal window is really inconvenient as it exposes bootstrap implementation (because `bsModal` is Directive).
It would be more comfortable to work with component like this:

``` html
<button (click)="isModalVisible = !isModalVisible">toggle modal</button>
<bs-modal *ngIf="isModalVisible" backdrop="static" title="My Title">
   <my-component-in-body></my-component-in-body>
</bs-modal>
```

So, this is feature request

**Comment by valorkin** [comment]
right now `bsModal` is directive because it extends functionality available at element
and this is good

`bs-modal` as a component will be done one day, but it will contain html and some structure
and those are not better, they are different

it is planned and will be added

**Comment by stalniy** [comment]
An interesting answer. The current behavior requires:
- to copy/paste bloated markup of bootstrap modal html across the app what makes readability worse because of huge amount of attrs on `.modal`
- it can't be use with something different because it uses structure of bootstrap modal (I.e. Classes)
- modal window can't be a behavior (this what directive is), currently it just breaks encapsulation of bootstrap modal
- if one day I  want to upgrade to bootstrap 4 I will be forced to refactor the whole project (and there are lots of risks like this)

This is why I said "better modals" in the ticket. 
So, it's true that they are different but component encapsulated modal is much better than directive.

**Comment by valorkin** [comment]
there are no migration changes between bs3 -> bs4 modal
there are 2 things left:
- modal components
- modal service

I see your point, but it is not better, it is just different

**Comment by valorkin** [comment]
using bsModal as directive you are able to implement things like sweet alerts, you not hardcoded
to header\body\footer bs structure
