### ISSUE TITLE
Bug in Tabs 2-way binding ? 

### ISSUE THREAD

**Issue by panuganti** [valor-software/ngx-bootstrap#79]
When I try to close the tab by splicing the tabs array, tabset doesn't update. i.e a tab doesn't get destroyed.
However, adding a new item to the tabs array updates the tabs in the tabset. Is there a bug ? 
![image](https://cloud.githubusercontent.com/assets/2431946/12343235/b8165c06-bae6-11e5-9c5e-c099ef42c1fb.png)

**Comment by valorkin** [comment]
not really, it is not angular1, it will not do deep equality check in digest for you :)
so, be functional, and avoid side effects :)
not best but easiest way to achieve what you need is:
`this.tabs = this.tabs.slice().splice(index,1)`
should work

**Comment by Motassem-MK** [comment]
nop it doesn't work, see this
![image](https://cloud.githubusercontent.com/assets/13342609/21830578/05f809f4-d79e-11e6-9d77-63b15c80edf8.png)

(removed the first element of the array then added a new element to it)
the only output is one added tab, nothing removed from the view
I'm certain there is a bug in there.

(PS: I did console.log the array before and after, it is modified properly)
