### ISSUE TITLE
Getting 404 traceur

### ISSUE THREAD

**Issue by karthikastra** [valor-software/ngx-bootstrap#790]
Hi,

Once i added ng2-bootstrap i am getting http://localhost/traceur 404 error. Is there any solution for this?

**Comment by dekonunes** [comment]
What version of Angular? RC6? 
if yes you will need do some changes in system-config.ts (if using angular-cli) or update systemjs.config.js (if using quick-start angular).

Look in angular Issues

**Comment by Martin-Luft** [comment]
@karthikastra does the hint from @dekonunes helps you? Can I close the issue?

**Comment by Martin-Luft** [comment]
https://github.com/angular/angular/issues/11358
