### ISSUE TITLE
Tooltip doesn't refresh content when open

### ISSUE THREAD

**Issue by aszechlicki** [valor-software/ngx-bootstrap#791]
When tooltip is open, its content doesn't refresh when dynamic property it is bound to changes

**Comment by adrianfaciu** [comment]
Can you show a sample on how to reproduce this ?

**Comment by aszechlicki** [comment]
@adrianfaciu sure, please have a look at this gist:

https://gist.github.com/aszechlicki/09ce7edd72a4585e20490422849f9c44

**Comment by adrianfaciu** [comment]
Yes, value is passed and initialized on show, so it will not change while displayed. 

As a workaround you could use a custom template with a TemplateRef and specify the context as the property bound to changes. This could work.

**Comment by aszechlicki** [comment]
thanks, will try that

are there plans to fix that? because tbh, the whole idea of angular is to reflect changes to the model as they happen

**Comment by adrianfaciu** [comment]
I guess changing the data while the tool tip is open is not that common, so was not a top priority when this was implemented. Will try to look at this.

**Comment by valorkin** [comment]
not sure it is a good idea after all, added in `nice to haves`
