### ISSUE TITLE
Accordion with bootstrap 4

### ISSUE THREAD

**Issue by bprgit** [valor-software/ngx-bootstrap#796]
Hi, it looks like the accordion component needs to be updated to use "cards" in bootstrap 4 as "panels" have been dropped in bootstrap 4.

Not sure if I can change this myself as I'm new to all this git stuff

**Comment by RolfVeinoeSorensen** [comment]
Duplicate [#449](https://github.com/valor-software/ng2-bootstrap/issues/449)
