### ISSUE TITLE
DatePicker - activeDate not updated when navigating using arrows

### ISSUE THREAD

**Issue by mstawick** [valor-software/ngx-bootstrap#797]
In standalone mode, when navigating using '<' '>' arrows (or selecting year / month), the activeDate is not updated. Only mouse click on specific date updates activeDate. This is misleading, since after navigating, the 1st of given month is marked as selected.

**Comment by valorkin** [comment]
join https://www.hamsterpad.com/chat/ng2 to watch a process of new datepicker development

**Comment by valorkin** [comment]
this one will be just thrown away :)

**Comment by mstawick** [comment]
That's awesome, thanks!
