### ISSUE TITLE
not compatible with rc4

### ISSUE THREAD

**Issue by git4sun** [valor-software/ngx-bootstrap#798]
Is there a plan to update the project so that it can work with rc4?

**Comment by aaronczichon** [comment]
Jep, support for RC4 would be nice. I think the problem is not RC4 itself. I get an @angular/forms error (cannot be found). 

ng2-bootstrap seems not to support the new angular forms API.

**Comment by adrianfaciu** [comment]
While there were/are some problems with specific components, mainly it does support RC4. (I'm actually using it in a project). So it would be helpful to give some details on what specific problem you have, and how they can be reproduced so we can have a look at them.

**Comment by git4sun** [comment]
I got exception: Cannot find module 'angular2/angular2' in most of the components. It should be @angular/core now and view is no longer with rc4. Some old components are throwing exceptions, e.g., View, NgIf, NgClass, ...

**Comment by valorkin** [comment]
@git4sun you are using outdated ng2-bootstrap version
make a clean install of ng2-bootstrap

**Comment by git4sun** [comment]
npm install --save ng2-bootstrap
this is how I installed ng2-bootstrap as described in readme. How else can I install a clean version?

**Comment by valorkin** [comment]
npm install --save ng2-bootstrap@latest

check 'npm-check' module it will save you some time
Plus search for 'angular2' in your project and later in dependencies, something is out of date for suew
