### ISSUE TITLE
Date disabled attribute in ng2-bootstrap date Picker is not working

### ISSUE THREAD

**Issue by lmudhaliyar** [valor-software/ngx-bootstrap#799]
Date disable attribute is not working.
Added below code in .ts file.
this.testDateDisabled = [
                {date: (new Date("October 13, 2016 11:13:00")), mode: 'day'}
            ];
October 13 is not disable in the datepicker.

**Comment by VirendraWankhede** [comment]
Facing same issue, anyone know about it please share your answer, thanku

**Comment by AlexLovato** [comment]
it's marked as "todo" in the source code, doesn't seem to be implemented fully

**Comment by vcernomschi** [comment]
+1

**Comment by Misenooooo** [comment]
+1 When could we expect a release of this feature?

**Comment by ghost** [comment]
Hi
I see the feature implemented but it is not available in npm version.
Any update on that front?

Thanks

**Comment by valorkin** [comment]
available in old datepicker
not yet in new one
