### ISSUE TITLE
Bug in docs (accordion)

### ISSUE THREAD

**Issue by vcorr** [valor-software/ngx-bootstrap#80]
There's a little bug in the accordion example in docs I think, it says

```
<accordion-group *ngFor="#group of groups" [heading]="group.title">

</accordion-group>
```

should be: 

```
<accordion-group *ngFor="#group of groups" [heading]="group.title">
   {{group.content}}
</accordion-group>
```

**Comment by tgrecojs** [comment]
@vcorr I was just looking into tackling this. Is this the section you're referring to: [Accord-Demo Line 24](https://github.com/valor-software/ng2-bootstrap/blob/master/demo/components/accordion/accordion-demo.html#L24)? I do see that they're a question mark there now, so i'm not sure if this has been resolved or not

**Comment by vcorr** [comment]
@thomasjosephgreco Actually I meant the project's website, http://valor-software.github.io/ng2-bootstrap/#accordion - it doesn't seem to match the source you linked (it's still empty)

**Comment by valorkin** [comment]
yeap, I am rendering code with prismjs, and it has issue with {{?.}} notation
so I need to or fix it, or choose something else

**Comment by tgrecojs** [comment]
@vcorr Ok I see. Is that something I, personally, can implement? What i mean by this is: is this something I can access via GitHub?

**Comment by valorkin** [comment]
Yes, you can.
Git clone, npm i, npm start, open localhost 8080
You will see demo with docs.
If you will open any demo/components/section*.ts file
You will see how source code are required via prismjs loader.
This is the starting point :)
Now the funny part, update prism to latest version, and find out why it is bugging this.
Maybe, it will be much easier to create failing use case for prism and debug from there
Good luck!:)
