### ISSUE TITLE
ViewContainerRef in parent

### ISSUE THREAD

**Issue by shashankkrjain** [valor-software/ngx-bootstrap#804]
I have a root component `AppComponent` which all other components derive from. Now, because `ViewContrinerRef` needs to be injected in the constructor, the `AppComponent` ends up with the last child's `ViewContainerRef`.

There is a modal in `AppComponent` which I want to show. But, its reference though `@ViewChild` is always `undefined`. That is because the `viewContainerRef` in `AppComponent` is of a child, and not of the parent.

Can you suggest me what should be done in this case?

**Comment by cyberbobjr** [comment]
Same problem here

**Comment by valorkin** [comment]
In latest versions I have removed requirement of viewContainerRef, it is needed only for ngUpgrade apps

**Comment by valorkin** [comment]
So
- remove viewContainerRef
- clean install latest or latest @beta version
- if did not helped please use plunkr from readme and create a plunkr to reproduce your issue

**Comment by valorkin** [comment]
if above did not fixed your issue, please refer to https://github.com/valor-software/ng2-bootstrap/blob/development/components/utils/components-helper.service.ts#L25-L43
