### ISSUE TITLE
ng2-bootstrap is looking for @angular/core, but I'm referencing this as angular2/core

### ISSUE THREAD

**Issue by claudneto** [valor-software/ngx-bootstrap#805]
How can I change my package alias to reference it as @angular instead of angular2? Or how can I change which lib ng2-bootstrap will load?
This is crashing my app when I use ng2-bootstrap!

**Comment by joff1979** [comment]
I believe the namespaces were changed in angular 2 after RC2 was released. I'm guessing you need to upgrade your project to use the latest Angular 2 RC(4).

**Comment by valorkin** [comment]
yeap, `angular2/core` was deprecated couple of months ago
so your only option is updating your app
