### ISSUE TITLE
Karma Error: Missing dependencies

### ISSUE THREAD

**Issue by Kize** [valor-software/ngx-bootstrap#809]
Hi all,

I'm trying to add ng2-bootstrap to Karma _(v0.13.22)_, but I'm stuck with the same message error :

```
Missing error handler on 'socket'.
TypeError: (msg || "").replace is not a function
```

This error usually means that dependencies are not correctly included, but I really don't know what I'm doing wrong...

My **karma.conf.js** file :

```
files: [
    ...
    'node_modules/moment/moment.js',
    {pattern: 'node_modules/ng2-bootstrap/**/*.js', included: false, watched: false},
    {pattern: 'node_modules/ng2-bootstrap/**/*.js.map', included: false, watched: false},
    ...
]
```

I tried to include only this file instead : `'node_modules/ng2-bootstrap/ng2-bootstrap.js'`, but it doesn't change anything.

My **karma-test-shim.js** file :

```
System.config(
    {
        map: {
            ...
            'moment': 'node_modules/moment',
            'ng2-bootstrap': 'node_modules/ng2-bootstrap'

        },
        packages: {
            ...
            'moment': {
                defaultExtension: 'js'
            },
            'ng2-bootstrap': {
                defaultExtension: 'js',
                main: 'ng2-bootstrap.js'
            }
        }
    });
```

I added moment, but I am only using Modals from ng2-bootstrap, so dependencies with **moment.js** should not be a problem.

If someone has an idea, I'd be really grateful. :pray:

**Comment by justinmchase** [comment]
There are two files missing from the package in npm:
- ng2-bootstrap.js.map
- ng2-bootstrap.min.js.map

![deps_missing](https://cloud.githubusercontent.com/assets/10974/17456656/f548bb28-5ba4-11e6-820e-e6bcb6375be6.png)

**Comment by Kize** [comment]
Hi, thank you for your response, but sadly I still got the same error.

In my nodes_modules, I now have the **.js.map** files :
![ng2 nodes modules](https://cloud.githubusercontent.com/assets/6702319/17474802/31b1f0ca-5d58-11e6-872d-fad9e7965e58.png)

I changed my imports to specify the '_bundles_' directory, in the karma configuration, like this :
(I also tried without changing anything, with the same configuration as mentioned before, but it still have the error message)

My **karma.conf.js** file :

```
files: [
    ...
    'node_modules/moment/moment.js',
    {pattern: 'node_modules/ng2-bootstrap/bundles/*.js', included: false, watched: false},
    {pattern: 'node_modules/ng2-bootstrap/bundles/*.js.map', included: false, watched: false},
    ...
]
```

My **karma-test-shim.js** file :

```
System.config(
    {
        map: {
            ...
            'moment': 'node_modules/moment',
            'ng2-bootstrap': 'node_modules/ng2-bootstrap/bundles'

        },
        packages: {
            ...
            'moment': {
                defaultExtension: 'js'
            },
            'ng2-bootstrap': {
                defaultExtension: 'js',
                main: 'ng2-bootstrap.js'
            }
        }
    });
```

**Comment by Martin-Luft** [comment]
@Kize can I close this issue?

**Comment by Kize** [comment]
Yes, i changed SystemJS by Webpack in my project, which solved this problem.
