### ISSUE TITLE
Datepicker customClass

### ISSUE THREAD

**Issue by masiamj** [valor-software/ngx-bootstrap#811]
Docs are fine for the most part, but missing a good example of using the customClass property. Can we please get an example of that? Thanks!

**Comment by aidemsined** [comment]
havent been able to use that either. can we get a one liner example pretty please?
the below doesnt seem to be working...
```js
public todayStyling = [{date: new Date(), mode: 'day', clazz: 'today-class'}];
```
```html
<datepicker
                            [(ngModel)]="model.date"
                            [ngModelOptions]="{standalone: true}"
                            [minDate]="minDate"
                            [maxDate]="maxDate"
                            [showWeeks]="false"
                            [customClass]="todayStyling"
                            (selectionDone)="onSelectionDone($event)"
                        >
                        </datepicker>
```

**Comment by poltorak** [comment]
@aidemsined I believe you will have to use beginning of the day you want add class.
e.g.
```javascript
public todayStyling = [{date: moment().startOf('day'), mode: 'day', clazz: 'today-class'}];
```
if you use moment ofc.
or simply date
```javascript
public todayStyling = [{date: new Date().setHours(0,0,0,0), mode: 'day', clazz: 'today-class'}];
```

this helped me :)

**Comment by defra91** [comment]
@poltorak solution worked for me!!! 

```
this.holidays = this.bowling.holidays.map((item) => {
      let date = new Date(item.date);
      this.customDateClasses.push({
        date: date.setHours(0,0,0,0),
        mode: 'day',
        clazz: 'calendar-holiday'
      });
      return date;
    });
```

Output of `customDateClasses` is:

```
[
    {
        "date": 1451602800000,
        "mode": "day",
        "clazz": "calendar-holiday"
    },
    {
        "date": 1495404000000,
        "mode": "day",
        "clazz": "calendar-holiday"
    }
]
```

**Comment by JoseRCayetano** [comment]
@poltorak is it possible do the same with month and year? I´m trying it but it doesn't works

**Comment by poltorak** [comment]
@JoseRCayetano I'm not sure. I wasn't using for a long time. Can you show your code? Or if you want to try style month/year I think you can use similar solution to @defra91. So if you want to style whole month you can just create simply 30/31 days that should be styled.

**Comment by defra91** [comment]
@JoseRCayetano, @poltorak  my solution was cycling through a set of dates. There is no support for customize a range of dates so you should implement some workaround, shouldn't take too much time.

**Comment by JoseRCayetano** [comment]
I want to apply the some custome style to actual month and actual year. 

If i use {date: new Date().setHours(0, 0, 0, 0), mode: 'day', clazz: 'today-class'}, y can apply my custome class but only to the day. I want the same custome class be applied  to month and year.
I did this : date: new Date().setHours(0, 0, 0, 0), mode: 'month', clazz: 'today-class'} but it doesnt't works

**Comment by poltorak** [comment]
@JoseRCayetano so if you want to apply this class to more than one day just create an Array with these days. Similar as @defra91 did. e.g.: (I'm not sure if this gonna work as it is, but for sure something smiliar)
```javascript
public styled = [
  {date: new Date('05-07-2017').setHours(0,0,0,0), mode: 'day', clazz: 'today-class'},
  {date: new Date('06-07-2017').setHours(0,0,0,0), mode: 'day', clazz: 'today-class'},
  {date: new Date('07-07-2017').setHours(0,0,0,0), mode: 'day', clazz: 'today-class'},
  {date: new Date('08-07-2017').setHours(0,0,0,0), mode: 'day', clazz: 'today-class'},
  {date: new Date('09-07-2017').setHours(0,0,0,0), mode: 'day', clazz: 'today-class'},
  {date: new Date('10-07-2017').setHours(0,0,0,0), mode: 'day', clazz: 'today-class'}
];
```

**Comment by Maysam1993** [comment]
I used the following
 public todayStyling = [{date: new Date().setHours(0,0,0,0), mode: "day", clazz: "full"}];

<datepicker class="tasks-list" 
             [showWeeks]="false"
             [startingDay]="1"
             [formatDayHeader]="'ddd'"
             [shortcutPropagation]="true"
             [maxMode]="'day'"
             [customClass]="todayStyling"></datepicker>

in css I added file:

.full button span{
    background-color: red;
    border-radius: 32px;
    color: black;
  }

but no result, 
can any one tell me is css selector is correct " .full button span" or what's the problem?

**Comment by nasirIdeos** [comment]
@poltorak customClass is not applying class for desired dates.

I am trying to highlight **TODAY** when user selects date other than today.


` private get selectedDays(): Array<CustomDayStyle> {
      let days = new Array<CustomDayStyle>();
      let toDay= new Date();
      days.push(new CustomDayStyle( toDay.setHours(0,0,0,0), "day", "full"));
          return days;
    }`

`class CustomDayStyle {
    public date: Date;
    public mode: string;
    public clazz: string;
    constructor(date: Date, mode: string, clazz: string) {
        this.date = date;
        this.mode = mode;
        this.clazz = clazz;
    }
}
`

Css class 
`.full button  {
    background-color: limegreen;
    color: black;
  }`

At template 
`<datepicker [customClass]="selectedDays" [(ngModel)]="dt" [showWeeks]="true" ></datepicker>`

**Comment by valorkin** [comment]
added in new datepicker
available in v1.9.2
http://valor-software.com/ngx-bootstrap/#/datepicker

**Comment by experionakash** [comment]
`<input type="text" class="form-control" readonly="readonly" #dp="bsDatepicker" bsDatepicker [bsValue]="bsValue" [minDate]="minDate" [maxDate]="maxDate" (bsValueChange)="datepickerValueChange($event)" [bsConfig]="{ dateInputFormat: dateFormat }"  [customClass]="todayStyling">`

I'm getting the following error while using the customClass property. 

> Template parse errors:
> Can't bind to 'customClass' since it isn't a known property of 'input'.

**Comment by bandhavya** [comment]
customClass is not working either on datepicker or bsdatepicker.
