### ISSUE TITLE
TypeAhead Can't bind to 'typeaheadItemTemplate' since it isn't a known native property

### ISSUE THREAD

**Issue by hanmingming66** [valor-software/ngx-bootstrap#812]
I'm using ng2-TypeAhead ;
error
`EXCEPTION: Template parse errors:
Can't bind to 'typeaheadItemTemplate' since it isn't a known native property ("
    <input [(ngModel)]="customSelected"
           [typeahead]="statesComplex"
           [ERROR ->][typeaheadItemTemplate]="customItemTemplate"
           [typeaheadOptionField]="'name'"
           "): TypeaheadDemoComponent@17:11
Can't bind to 'typeahead' since it isn't a known native property ("
    <form [formGroup]="myForm">
        <input formControlName="state"
               [ERROR ->][typeahead]="states"
               (typeaheadOnSelect)="typeaheadOnSelect($event)"
               "): TypeaheadDemoComponent@46:15
Can't bind to 'typeaheadOptionsLimit' since it isn't a known native property ("typeahead]="states"
               (typeaheadOnSelect)="typeaheadOnSelect($event)"
               [ERROR ->][typeaheadOptionsLimit]="7"
               [typeaheadOptionField]="'name'"
               [typeahea"): TypeaheadDemoComponent@48:15
Can't bind to 'typeaheadOptionField' since it isn't a known native property ("adOnSelect)="typeaheadOnSelect($event)"
               [typeaheadOptionsLimit]="7"
               [ERROR ->][typeaheadOptionField]="'name'"
               [typeaheadMinLength]="0"
               placeholder="): TypeaheadDemoComponent@49:15
Can't bind to 'typeaheadMinLength' since it isn't a known native property ("        [typeaheadOptionsLimit]="7"
               [typeaheadOptionField]="'name'"
               [ERROR ->][typeaheadMinLength]="0"
               placeholder="Typeahead inside a form"
               class="): TypeaheadDemoComponent@50:15`

testtypeahead.ts
`import {bootstrap} from '@angular/platform-browser-dynamic';
import {TypeaheadDemoComponent} from './component/testtypeaheadcomponent.js'
//import {enableProdMode} from '@angular/core';

bootstrap(TypeaheadDemoComponent);`

testtypeaheadcomponent.ts
import {Component} from '@angular/core';
import {CORE_DIRECTIVES} from '@angular/common';
import {FORM_DIRECTIVES, REACTIVE_FORM_DIRECTIVES, FormGroup, FormControl} from '@angular/forms';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/of';
import {TYPEAHEAD_DIRECTIVES} from 'ng2-bootstrap/ng2-bootstrap';

@Component({
    selector: 'typeahead-demo',
    directives: [TYPEAHEAD_DIRECTIVES, CORE_DIRECTIVES, FORM_DIRECTIVES, REACTIVE_FORM_DIRECTIVES],
    templateUrl: "ts/component/typeahead-demo.html" 
})
export class TypeaheadDemoComponent {
   //copy from demo
}

ts/component/typeahead-demo.html , copy from demo
`<div class='container-fluid'>
    
    <h4>Static arrays</h4>
    <pre class="card card-block card-header">Model: {{selected | json}}</pre>
    <input [(ngModel)]="selected"
           [typeahead]="states"
           (typeaheadOnSelect)="typeaheadOnSelect($event)"
           class="form-control">

```
<!-- Custom item template -->
<template #customItemTemplate let-model="item" let-index="index">
    <h5>This is: {{model | json}} Index: {{ index }}</h5>
</template>
<h4>Custom item template</h4>
<pre class="card card-block card-header">Model: {{customSelected | json}}</pre>
<input [(ngModel)]="customSelected"
       [typeahead]="statesComplex"
       [typeaheadItemTemplate]="customItemTemplate"
       [typeaheadOptionField]="'name'"
       (typeaheadOnSelect)="typeaheadOnSelect($event)"
       class="form-control">

<!-- Asynchronous results -->
<h4>Asynchronous results</h4>
<pre class="card card-block card-header">Model: {{asyncSelected | json}}</pre>
<input [(ngModel)]="asyncSelected"
       [typeahead]="dataSource"
       (typeaheadLoading)="changeTypeaheadLoading($event)"
       (typeaheadNoResults)="changeTypeaheadNoResults($event)"
       (typeaheadOnSelect)="typeaheadOnSelect($event)"
       [typeaheadOptionsLimit]="7"
       [typeaheadOptionField]="'name'"
       placeholder="Locations loaded with timeout"
       class="form-control">
<div *ngIf="typeaheadLoading===true">
    <i class="glyphicon glyphicon-refresh ng-hide" style=""></i>
</div>
<div *ngIf="typeaheadNoResults===true" class="" style="">
    <i class="glyphicon glyphicon-remove"></i> No Results Found
</div>

<!--Typeahead inside a form-->
<h4>Typeahead inside a form</h4>
<pre class="card card-block card-header">Model: {{myForm.value.state | json}}</pre>
<form [formGroup]="myForm">
    <input formControlName="state"
           [typeahead]="states"
           (typeaheadOnSelect)="typeaheadOnSelect($event)"
           [typeaheadOptionsLimit]="7"
           [typeaheadOptionField]="'name'"
           [typeaheadMinLength]="0"
           placeholder="Typeahead inside a form"
           class="form-control">
</form>
```

</div>`

I think i have import TYPEAHEAD_DIRECTIVES ,but it can't bind to 'typeaheadItemTemplate' or 'typeahead',is this means TYPEAHEAD_DIRECTIVES  not loaded correctly ,or i missed some thing important.

**Comment by adrianfaciu** [comment]
@tuomahan How did you installed ng2-bootstrap ? If you got it from npm it will not work since the change that added typeaheadItemTemplate was not released yet. See #778
