### ISSUE TITLE
Error with dropdown toggle input attribute

### ISSUE THREAD

**Issue by sdornan** [valor-software/ngx-bootstrap#819]
I am attempting to use the dropdown component using the example as a guide and I am getting an error and a non-functional button. It seems that maybe `isOpen` isn't being honored as an input by the component. I am using `ng2-bootstrap@1.0.24`. Removing `isOpen` fixes the error but does not cause the dropdown toggle to  work.

``` javascript
VM15222:84 EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Can't bind to 'isOpen' since it isn't a known native property ("><button class="btn btn-secondary" id="sort-button" type="button" dropdown-toggle="dropdown-toggle" [ERROR ->][(isOpen)]="isSortDropdownOpen">Action&nbsp;<i class="fa fa-caret-down"></i></button><ul dropdownMenu"): RfpListComponent@0:270
```

Here's the relevant parts of my code:

TS:

``` typescript
import { Component, OnInit } from '@angular/core';
import { ROUTER_DIRECTIVES} from '@angular/router';
import { DROPDOWN_DIRECTIVES } from 'ng2-bootstrap';

@Component({
  selector: 'rfp-list',
  directives: [DROPDOWN_DIRECTIVES],
  template: require('./rfp-list.component.pug'),
  styles: [require('./rfp-list.component.scss')]
})
export class RfpListComponent implements OnInit {
  isSortDropdownOpen: boolean = false;

  constructor() { }
```

HTML:

``` html
<button id="sort-button" type="button" dropdown-toggle="dropdown-toggle" [(isOpen)]="isSortDropdownOpen" class="btn btn-secondary">Action&nbsp;<i class="fa fa-caret-down"></i></button>
<ul dropdownMenu="dropdownMenu" role="menu" aria-labelledby="sort-button">
  <li role="menuitem"><a href="#" class="dropdown-menu">Due Date</a></li>
  <li role="menuitem"><a href="#" class="dropdown-menu">Name</a></li>
</ul>
```

**Comment by vadjs** [comment]
I have same error but with datepicker(using exactly as in example in `readme.md`) when using **pug**. In html templates all works good. 
Looks like it's **pug-html-loader** problem when using ng2-bootstrap(when using Webpack).
My idea to fix it - using **pug-loader** instead **pug-html-loader**. But i couldn't run it properly in webpack loaders config.

P.S. I think will be good idea to describe properly integration ng2-bootstrap with pug in Wiki.

**Comment by valorkin** [comment]
ok, you are trying to banana bind to isOpen
but is only a property, so only `[isOpen]` will work
but there are no `isOpenChanged`, so you can not use it as `[(isOpen)]`
I will close this issue, but if you will need this functionality
just create feature request or even PR
it will be really simple one
