### ISSUE TITLE
Pagination @Input definitions

### ISSUE THREAD

**Issue by apatryda** [valor-software/ngx-bootstrap#821]
[Getters and setters](https://github.com/valor-software/ng2-bootstrap/blob/development/components/pagination/pagination.component.ts#L99-L117)  for _itemsPerPage_ and _totalItems_ are decorated wrongfully. @Input decorator should decorate the setter, not the getter. This makes it impossible to use the pagination component.

**Comment by adrianfaciu** [comment]
@apatryda Pull request ? :smile:
