### ISSUE TITLE
Datepicker not working (resolved)

### ISSUE THREAD

**Issue by gubagu** [valor-software/ngx-bootstrap#822]
Hey guys First of all great work !
I have an issue with the datepicker. Copied the code from your demo page and followed the webpack install guide unfortunately it is not working.
Could give me a hint what am i doing wrong.
Here my package.json

```
"@angular/common": "2.0.0-rc.4",
"@angular/compiler": "2.0.0-rc.4",
"@angular/core": "2.0.0-rc.4",
"@angular/forms": "0.2.0",
"@angular/http": "2.0.0-rc.4",
"@angular/platform-browser": "2.0.0-rc.4",
"@angular/platform-browser-dynamic": "2.0.0-rc.4",
"@angular/router": "3.0.0-beta.1",
"core-js": "^2.4.0",
"font-awesome-webpack": "0.0.4",
"moment": "^2.14.1",
"ng2-bootstrap": "^1.0.24",
"ng2-table": "^1.0.2",
"reflect-metadata": "0.1.2",
"rxjs": "5.0.0-beta.6",
"zone.js": "0.6.12"
```

The error message is something like:

```
 "Error: No value accessor for ''   ......"
 "Error in ./DatepickerCmp class DatepickerCmp - inline template:18:18"
```

row 18:18 is just where the datepicker is declared :(

Any help highly appreciated thanks in advance

Guby

**Comment by chris-cartwright** [comment]
Switching to the new forms module fixed the issue for me.

I followed the little bit here: https://angular.io/docs/ts/latest/guide/forms.html#!#bootstrap

**Comment by lexmark-awilliams** [comment]
I'm seeing the same error. package.json versions are the same as @gubagu 's

**Comment by lexmark-awilliams** [comment]
Fixed this by adding `disableDeprecatedForms()` to my bootstrap function. Seems like I had a conflict between the new `@angular/forms` and the old forms. 

```
document.addEventListener('DOMContentLoaded', function main() {
  bootstrap(AppComponent, [
    APP_ROUTER_PROVIDERS,
    ...ENV_PROVIDERS,
    ...HTTP_PROVIDERS,
    disableDeprecatedForms(),
    provideForms(),
    provide(LocationStrategy, { useClass: HashLocationStrategy }),
    provide(FormBuilder, { useClass: FormBuilder })
  ])
  .catch(err => console.error(err));

});
```

**Comment by gubagu** [comment]
```
disableDeprecatedForms(),
provideForms()
```

Hey @lexmark-awilliams did the trick. :smile: 

Cheerz
