### ISSUE TITLE
feat(build): Add jsnext:main bundle

### ISSUE THREAD

**Issue by tamascsaba** [valor-software/ngx-bootstrap#826]
Angular2 use rollup to create es6 bundle, it would be greet define a jsnext:main field in its package.json to allow easier integration with other ES6 code, by letting them find the entry point.

See https://github.com/rollup/rollup/wiki/jsnext:main and https://github.com/caridy/grunt-bundle-jsnext-lib/blob/master/README.md#optionsmain.

**Comment by goleary** [comment]
Just curios what the status of this is or if I can help out in any way?

**Comment by valorkin** [comment]
Angular team deprecated this practice
