### ISSUE TITLE
With bootstrap 3, also use of "card" css classes ???

### ISSUE THREAD

**Issue by fabm22** [valor-software/ngx-bootstrap#83]
Hi 
I'd like to be sure. When on demo page I select bootstrap 3 "version" of the demo page, and the snippets still use, for example, the "card" components css classes.

Those appeared on Bootstrap 4 so is it intended ? 

Thanks for clarification.

**Comment by valorkin** [comment]
Hey, using both classes for bs3 and bs4 doesn't pushes me to duplicate html templates for components right now, but to be clear, there are will be 3 versions:
- with bs3 templates
- with bs4 templates
- without templates

**Comment by fabm22** [comment]
Thanks for precise answer !

**Comment by valorkin** [comment]
I am trying to work out generic requirements to ng2 packages https://github.com/valor-software/ng2-plans
