### ISSUE TITLE
Error with new angular RC5

### ISSUE THREAD

**Issue by whuang04** [valor-software/ngx-bootstrap#834]
Getting this error when angular app starting

```
Error: Error: Error: Input 'previousText' defined multiple times in 'PagerComponent'
        at new BaseException (http://localhost:8000/node_modules/@angular/compiler//bundles/compiler.umd.js:5116:27)
        at eval (http://localhost:8000/node_modules/@angular/compiler//bundles/compiler.umd.js:12845:31)
        at Array.forEach (native)
        at DirectiveResolver._merge (http://localhost:8000/node_modules/@angular/compiler//bundles/compiler.umd.js:12842:24)
        at DirectiveResolver._mergeWithPropertyMetadata (http://localhost:8000/node_modules/@angular/compiler//bundles/compiler.umd.js:12834:25)
        at DirectiveResolver.resolve (http://localhost:8000/node_modules/@angular/compiler//bundles/compiler.umd.js:12786:33)
        at CompileMetadataResolver.getDirectiveMetadata (http://localhost:8000/node_modules/@angular/compiler//bundles/compiler.umd.js:13097:55)
        at addDirective (http://localhost:8000/node_modules/@angular/compiler//bundles/compiler.umd.js:13367:37)
        at eval (http://localhost:8000/node_modules/@angular/compiler//bundles/compiler.umd.js:13376:77)
        at Array.forEach (native)
    Evaluating http://localhost:8000/app/main.js
    Error loading http://localhost:8000/app/main.js
```

**Comment by marcalj** [comment]
We need `@NgModule` support to use the directives.

**Comment by awilhelmer** [comment]
i only get:
Error: Uncaught (in promise): No provider for ComponentsHelper! 
And i can't get it to import in my NgModule Providers...

**Comment by marcalj** [comment]
I'm getting: "browser_adapter.js:84 Error: Type TooltipContainerComponent is part of the declarations of 2 modules: AppModule and constructor!", and of course it's not declared in two modules... :(

**Comment by awilhelmer** [comment]
I fixed the error now. I removed `viewProviders: [BS_VIEW_PROVIDERS]` from my component
what caused the error. Readding it resolved my problem. I am using this components of ng2-bootstrap without any errors in RC5:
import `{MODAL_DIRECTIVES,TOOLTIP_DIRECTIVES,TYPEAHEAD_DIRECTIVES,CollapseDirective,PaginationComponent } from "ng2-bootstrap/ng2-bootstrap";`

Simply remove all Directives in all your Components and place them in your declarations of `@NgModule`

**Comment by marcalj** [comment]
Ok my problem is because I'm using ngUpgrade (I'm in the middle of an upgrade process...)

**Comment by achimha** [comment]
This is what I get trying to compile my project with RC5:

```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'templateUrl' since it isn't a known property of 'datepicker-inner'.
1. If 'datepicker-inner' is an Angular component and it has 'templateUrl' input, then verify that it is part of this module.
2. If 'datepicker-inner' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("ustomClass]="customClass"
                      [dateDisabled]="dateDisabled"
                      [ERROR ->][templateUrl]="templateUrl"
                      [onlyCurrentMonth]="onlyCurrentMonth"
             "): DatePickerComponent@20:22 ; Zone: <root> ; Task: Promise.then ; Value: 
```

**Comment by marcalj** [comment]
@achimha  Maybe other error you have `("ustomClass]="customClass"` ==> `[customClass]="customClass"`

There's no `templateUrl` input in datepicker-inner or datepicker components.

**Comment by daemonblade** [comment]
The root cause is that ng2-bootstrap needs to add NgModule support so that it can be added to the **imports** section of the application module.

However, until that happens, a workaround is to add ng2-bootstrap components and directives to the **declarations** section of the root application module, and removing the ng2-bootstrap declarations from the application's Component decorators.

Unfortunately, any attempt to introduce NgModule feature modules to the application will break this workaround.

**Comment by marcalj** [comment]
@daemonblade RC5 support with modules is coming.

**Comment by jmoeyersons** [comment]
@achimha @marcalj Is there already any solution for that problem? Because I suffer the same error as @achimha  does:

```
Error: Uncaught (in promise): Template parse errors:
Can't bind to 'level' since it isn't a known property of 'as-my-battery'.
1. If 'as-my-battery' is an Angular component and it has 'level' input, then verify that it is part of this module.
2. If 'as-my-battery' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 (""checkbox" name={{data.name}} value={{data.name}}> {{data.name}}
                    <as-my-battery [ERROR ->][level]='data.battery'></as-my-battery>
                    <as-my-signal [level]='data.signal'></as-"): a@19:35
```

where as-my-battery has a `@Input() level: number;` declaration in his class

**Comment by matthijsl** [comment]
I'm experiencing the same issue as @moeyerke. Input defined as `@Input` or `inputs: ['config']` does not make a difference.

**Comment by marcalj** [comment]
Meanwhile the upgrade to RC5 work is not complete try to use `feat-rc5` branch or try to add `directives: [ ... ]` on your component.

I couldn't use tooltips neither by the way...

**Comment by jmoeyersons** [comment]
@MatthijsLiethof I founded a solution for the problem, if you are building with gulp, try to set the mangle option to false.
This solved to problem for me!

**Comment by matthijsl** [comment]
I can confirm that stopping the mangling of the code with the UglifyPlugin I use in Webpack solves the problem.

**Comment by bahodirk** [comment]
Is the any other way than setting the mangle option to false? I am not using gulp-uglify.

**Comment by jmoeyersons** [comment]
@bahodirk Did you used the directives in a component description? And can you give the error log?

**Comment by wcsdev15** [comment]
Yes, I am using only one directive, and I have added it to NgModule declarations.
```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'bu-toggle'.
1. If 'my-toggle' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'my-toggle' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("ch || displayCloseButton">
    <div class="switch__wrapper" *ngIf="displaySwitch">
      <my-toggle [ERROR ->][value]="false" [label]="'Advanced'" (valueChanged)="onSwitchValueChanged($event)"></my-toggle>
    <"): MyPanelHeader@4:17
```

**Comment by bahodirk** [comment]
Yes, I am using only one directive, and I have added it to NgModule declarations.

Unhandled Promise rejection: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'bu-toggle'.
1. If 'my-toggle' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'my-toggle' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("ch || displayCloseButton">
    <div class="switch__wrapper" *ngIf="displaySwitch">
      <my-toggle [ERROR ->][value]="false" [label]="'Advanced'" (valueChanged)="onSwitchValueChanged($event)"></my-toggle>
    <"): MyPanelHeader@4:17

**Comment by bahodirk** [comment]
Yes, I am using only one directive, and I have added it to NgModule declarations.

```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'my-toggle'.
1. If 'my-toggle' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'my-toggle' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("ch || displayCloseButton">
    <div class="switch__wrapper" *ngIf="displaySwitch">
      <my-toggle [ERROR ->][value]="false" [label]="'Advanced'" (valueChanged)="onSwitchValueChanged($event)"></my-toggle>
    <"): MyPanelHeader@4:17
```

**Comment by jmoeyersons** [comment]
@bahodirk Can you give me the code of the component my-toggle, because the error log names a property of bu-toggle?

**Comment by bahodirk** [comment]
@moeyerke Sorry for confusion, while adding the log, did not properly renamed bu to my. 

`import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'my-toggleEdit',
  host: {
    'class': 'switch__wrapper'
  },
  template: `
  <span *ngIf="!vm.hideLabel && vm.labelPosition === 'left'" 
        class="switch__text"
        (click)="onClick()">
        {{ vm.label }}
  </span>
  <div class="switch switch--with-text">
    <input type="checkbox" 
           id="{{ vm.name }}" 
           class="switch__field" 
           [disabled]=vm.readOnly />
    <label class="switch__label" 
           [attr.for]="label">{{ label }}</label>
  </div>
  <span *ngIf="!vm.hideLabel && vm.labelPosition === 'right'" 
        class="switch__text" 
        (click)="onClick()">
        {{ vm.label }}
  </span>`
})
export class MyToggleEdit {
  @Input() vm: any;
  @Input() formControl: FormControl;
  @Input() label: string;

  public onClick(): void {
    let ctrl = this.formControl;
    if (ctrl) {
      ctrl.updateValue(!ctrl.value);
    }
  }
}

@Component({
  selector: 'my-toggle',
  host: {
    'class': 'switch__wrapper'
  },
  template: `
  <span *ngIf="!hideLabel && labelPosition === 'left'"
        class="switch__text"              
        (click)="onClick()">
        {{ label }}
  </span>
  <div class="switch switch--with-text">
    <input type="checkbox"
           id="{{ label }}"
           class="switch__field" 
           [value]="value"
           [checked]="value"
           [attr.name]="label" 
           [disabled]=readOnly 
           (click)="onClick()" />
    <label class="switch__label" 
           [attr.for]="label">{{ label }}</label>
  </div>
  <span *ngIf="!hideLabel && labelPosition === 'right'" 
        class="switch__text"           
        (click)="onClick()">
        {{ label }}
  </span>`
})
export class MyToggle {
  @Input() value = false;
  @Input() label = 'unknown label';
  @Input() labelPosition = 'left';
  @Input() hideLabel = false;
  @Input() readOnly = false;
  @Output() valueChanged: EventEmitter<boolean> = new EventEmitter<boolean>();

  public onClick(): void {
    this.value = !this.value;
    this.valueChanged.emit(this.value);
  }
}
`

**Comment by jmoeyersons** [comment]
@bahodirk I inspected your code, and it seems fine to me, how to you build your application? Because while doing research, the way you build could be a reason for that error

**Comment by bahodirk** [comment]
@moeyerke 1. I am creating controls,module.ts, then adding all components to NgModule. 2. Importing control.module to app.module.ts.

I am using gulp to build, it is a large: 
```
'use strict';

/// <binding BeforeBuild='clean, bundle' />

// modules
var gulp = require('gulp');
var del = require('del');
var path = require('path');
var tslint = require('gulp-tslint');
var ts = require('gulp-typescript');
var sourcemaps = require('gulp-sourcemaps');
var less = require('gulp-less');
var usemin = require('gulp-usemin');
var liveServer = require('live-server');
var merge = require('merge2');
var Builder = require('systemjs-builder');
var chmod = require('gulp-chmod');
var uglify = require('gulp-uglify');
// var imagemin = require('gulp-imagemin');
// var svgSymbols = require('gulp-svg-symbols');
var rename = require("gulp-rename");
var karma = require('karma');

// Configuration
// ----------------------------------------
var config = function() {
  var root = '';
  var src = root + 'src/';
  var app = src + 'app/';
  var assets = src + 'assets/';
  var assetsPath = {
    fonts: assets + 'fonts/',
    images: assets + 'images/',
    styles: assets + 'styles/',
    icons: assets + 'icons/'
  };
  var index = src + 'index.html';
  var htmlFiles = [
    app + '**/*.html'
  ];
  var tsFiles = [
    app + '**/!(*.spec)+(.ts)'
  ];
  var tsTestFiles = {
    unit: [app + '**/*.spec.ts']
  };
  var build = {
    tmp: {
      path: 'tmp/',
      app: 'tmp/app/',
      test: 'dist/test/',
      js: 'tmp/js/',
      icons: 'tmp/icons/'
    },
    dev: {
      path: 'dist/dev/',
      app: 'dist/dev/app/',
      styles: 'dist/dev/css/',
      images: 'dist/dev/images/',
      fonts: 'dist/dev/fonts/',
      vendor: 'dist/dev/vendor'
    }
  };
  var liveServer = {
    dev: {
      port: 3000,
      host: "127.0.0.1",
      root: 'dist/dev/',
      file: "index.html",
      wait: 1000
    }
  };

  var config = {
    root: root,
    src: src,
    app: app,
    assets: assets,
    index: index,
    htmlFiles: htmlFiles,
    build: build,
    assetsPath: assetsPath,
    tsFiles: tsFiles,
    tsTestFiles: tsTestFiles,
    liveServer: liveServer
  };

  return config;
} ();


/* #### Compile tasks #### */

/* Initialize TS Project */
var tsProject = ts.createProject(config.root + 'tsconfig.json');
var tsUnitFiles = [].concat(config.tsTestFiles.unit);
var tsFiles = [].concat(config.tsFiles, tsUnitFiles);

gulp.task('clean-tsc-app', function() {
  return del([
    config.build.tmp.app + '**/*.js',
    config.build.tmp.app + '**/*.js.map'
  ]);
});

gulp.task('tsc-app', function() {
  return compileTs(config.tsFiles, config.build.dev.app)
});

gulp.task('tsc-test', function () {
  return compileTs(tsFiles, config.build.dev.app);
});

/**
 * Compiles TypeScript files
 * @param {files} array of TypeScript file to compile
 * @param {tsOutDir} output directory where the compiled files will be saved
 * @param {watchMode} if true the TypeScript compiler emits tslint errors directly to the output 
 */
function compileTs(files, tsOutDir, watchMode) {
  watchMode = watchMode || false;
  var res = gulp.src(files)
    .pipe(tslint())
    .pipe(tslint.report('prose', {
      summarizeFailureOutput: true,
      emitError: !watchMode
    }))
    .pipe(sourcemaps.init())
    .pipe(ts(tsProject))
    .on('error', function() {
      process.exit(1);
    });

  return res.js
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(tsOutDir));
}

function compileTsForBundle(files, tsOutDir, inlineSourceMaps) {
  var res = gulp.src(files)
    .pipe(sourcemaps.init())
    .pipe(ts(tsProject))
    .on('error', function() {
      process.exit(1);
    });

  return merge([
    res.dts
      .pipe(gulp.dest(tsOutDir)),
    res.js
      .pipe(inlineSourceMaps ? sourcemaps.write(): sourcemaps.write('.'))
      .pipe(gulp.dest(tsOutDir))
  ]);
}


/* #### Assets tasks #### */
gulp.task('fonts', function() {
  var fonts = [
    config.assetsPath.fonts + '**/*.*',
    'node_modules/font-awesome/fonts/' + '**/*.*'
  ];
  gulp.src(fonts)
    .pipe(chmod(755))
    .pipe(gulp.dest(config.build.dev.fonts));
});

gulp.task('images', function() {
  gulp.src(config.assetsPath.images + '**/*.*')
    .pipe(chmod(755))
    .pipe(gulp.dest(config.build.dev.images));
});

// ICONS (TEMP REMOVED)
// ----------------------------------------
/*
function generateIconLibrary(libraryName, outputPath) {
  return gulp.src(config.assetsPath.icons + libraryName +'/*.svg')
    .pipe(imagemin([
      imagemin.svgo({
        plugins: [
          { removeViewBox: false },
          { removeDesc: true },
          { removeTitle: true }
        ]
      })
    ]))
    .pipe(chmod(755))
    .pipe(svgSymbols({
      id: libraryName + '--%f',
      title: '%f',
      templates: [
        config.assetsPath.icons + '_icon-sprite-template.svg'
      ]
    }))
    .pipe(rename('icon-' + libraryName + '.svg'))
    .pipe(gulp.dest(outputPath));
}
*/
gulp.task('icons-brand', function () {
  return gulp.src(config.assetsPath.icons + 'icon-brand.svg')
    .pipe(chmod(755))
    .pipe(gulp.dest(config.build.dev.images + 'icons/'));
  //return generateIconLibrary('brand', config.build.dev.images + 'icons/');
});

gulp.task('icons-wincos', function () {
  //return generateIconLibrary('wincos', config.build.dev.images + 'icons/');
});

// Icon workflow
gulp.task('icons', ['icons-brand', 'icons-wincos']);

gulp.task('styles', function() {
  return gulp.src(config.assetsPath.styles + 'shell.less')
    .pipe(less())
    .pipe(chmod(755))
    .pipe(gulp.dest(config.build.dev.styles));
});

gulp.task('views', function () {
  var files = [config.src + 'index.html',
    config.src + 'systemjs.config.js'];

  gulp.src(files)
    .pipe(usemin())
    .pipe(gulp.dest(config.build.dev.path));

  return gulp.src(config.htmlFiles)
    .pipe(gulp.dest(config.build.dev.app))
});

gulp.task('fake-data', function () {
  return gulp.src(config.app + '**/*.json')
    .pipe(gulp.dest(config.build.dev.app))
});

gulp.task('bundle-deps', function () {
  return bundleDependencies();
});
function bundleDependencies() {
  var builderConfig = {
    defaultJSExtensions: true,
    format: 'cjs',
    paths: {
      'app/*': config.build.dev.app + '*.js',
      'rxjs/*': 'node_modules/rxjs/*',
      '@angular/*': 'node_modules/@angular/*'
    },
    packages: {
      '@angular/common': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/compiler': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/core': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/forms': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/http': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/platform-browser': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/platform-browser-dynamic': {
        main: 'index',
        defaultExtension: 'js'
      },
      '@angular/router': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      'rxjs': {
        main: 'Rx.js',
        defaultExtension: 'js'
      }
    }
  }

  var expressionOrTree = 'app/* - [app/*]';
  var outFile = 'dist/dev/lib/dependencies.bundle.js';
  var minOutFile = 'dist/dev/lib/dependencies.bundle.min.js';

  // 3. bundle
  bundle(builderConfig, expressionOrTree, outFile, { minify: false, sourceMaps: false });
  return bundle(builderConfig, expressionOrTree, minOutFile, { minify: true, sourceMaps: false });
}
function bundle(builderConfig, expressionOrTree, outFile, bundleOptions) {
  var builder = new Builder(builderConfig);
  return builder.bundle(expressionOrTree, outFile, bundleOptions);
}

gulp.task('assets', ['bundle-deps', 'fake-data', 'fonts', 'images', 'icons', 'styles', 'views']);

gulp.task('clean-assets', function() {
  return del([
    config.build.dev.fonts + '**/*.*',
    config.build.dev.images + '**/*.*',
    config.build.dev.styles + '**/*.*',
    config.build.dev.app + '**/*.html'
  ]);
});


/* #### Build tasks #### */
gulp.task('build-dev', ['tsc-app', 'assets']);
gulp.task('clean-build', function() {
  return del([
    config.build.tmp.path,
    config.build.dev.path
  ]);
});
gulp.task('clean', ['clean-build', 'clean-bundle']);


/* #### Bundle tasks #### */
gulp.task('tsc-bundle', function() {
  return compileTsForBundle(config.tsFiles, config.build.tmp.app, false)
});

gulp.task('js-bundle', ['tsc-bundle'], function() {
  return gulp.src([config.build.tmp.app + 'controls/**/*.js'])
    .pipe(gulp.dest(config.build.tmp.js));
});

gulp.task('fetch-sources', ['js-bundle'], function() {
  // provide ts source files
  gulp.src(config.app + 'controls/**/*.ts')
    .pipe(chmod(755))
    .pipe(gulp.dest('dist/src/controls/'));
  // provide icons sprites
  // generateIconLibrary('brand', 'dist/icons/');
  // generateIconLibrary('wincos', 'dist/icons/');
  gulp.src(config.assetsPath.icons + 'icon-brand.svg')
    .pipe(chmod(755))
    .pipe(gulp.dest('dist/icons/'));

  return gulp.src(config.build.tmp.app + 'controls/**/*')
    .pipe(chmod(755))
    .pipe(gulp.dest(config.root));
});

gulp.task('bundle', ['fetch-sources'], function() {
  var builderConfig = {
    defaultJSExtensions: true,
    format: 'cjs',
    paths: {
      'bu-controls/*': config.build.tmp.js + '*.js',
      'rxjs/*': 'node_modules/rxjs/*',
      'angular2/*': 'node_modules/angular2/*'
    }
  }
  var expressionOrTree = 'bu-controls/* - angular2/*.js';
  bundle(builderConfig, expressionOrTree, 'dist/bundle/controls.js', { minify: false, sourceMaps: false });
  return bundle(builderConfig, expressionOrTree, 'dist/bundle/controls.min.js', { minify: true, sourceMaps: false });
});
gulp.task('clean-bundle', function() {
  return del(['tmp', 'dist/bundle', 'dist/src', 'dist/icons', 'editors', 'containers', 'overlays', '*.ts', '*.map', '*.js', '!gulpfile.js', '!karma.conf.js', '!test.main.js']);
});

function bundle(builderConfig, expressionOrTree, outFile, bundleOptions) {
  var builder = new Builder(builderConfig);
  return builder.bundle(expressionOrTree, outFile, bundleOptions);
}

gulp.task('clean-src', function () {
  return del([
    config.src + '**/*.js',
    config.src + '**/*.js.map',
    config.src + '**/*.d.ts'
  ]);
});


/* #### Test tasks #### */
gulp.task('test', ['tsc-test'], function (done) {
  new karma.Server({
    configFile: __dirname + '/karma.conf.js',
    singleRun: true
  }, karmaDone).start();

  function karmaDone(exitCode) {
    console.log('Unit tests done with exit code: ' + exitCode);
    if (exitCode === 0) {
      done();
    } else {
      done('Unit tests failed.');
    }
  }
});

/* #### Serve tasks #### */
gulp.task('serve-build', ['build-dev', 'watch-ts', 'watch-styles', 'watch-views'], function() {
  liveServer.start(config.liveServer.dev);
});


/* #### Watch tasks #### */
gulp.task('watch-ts', function() {
  return gulp.watch(config.tsFiles, function(file) {
    console.log('Compiling ' + file.path + '...');
    return compileTs(file.path, config.build.dev.path, true);
  });
});

gulp.task('watch-styles', function() {
  gulp.watch(config.assetsPath.styles + '**/*.less', ['styles']);
});

gulp.task('watch-views', function() {
  gulp.watch(config.htmlFiles, ['views']);
});

/* #### Default task #### */
gulp.task('default', ['build-dev']);
```

**Comment by jmoeyersons** [comment]
@bahodirk Can you try this please?

```
var systemJs = { //ADD THIS VAR 
        builder: {
            normalize: true,
            minify: true,
            mangle: false, //Bug in mangle with RC5!
            runtime: false,
            globalDefs: {
                DEBUG: false,
                ENV: 'production'
            }
        }
    };

  var config = {
    root: root,
    src: src,
    app: app,
    assets: assets,
    index: index,
    htmlFiles: htmlFiles,
    build: build,
    assetsPath: assetsPath,
    tsFiles: tsFiles,
    tsTestFiles: tsTestFiles,
    liveServer: liveServer,
    systemJs: systemJs // ADD THIS ONE
  };
```

**Comment by bahodirk** [comment]
@moeyerke thank you, shall I call config.systemJs somewhere else? It is my fist time using gulp, sorry.

**Comment by jmoeyersons** [comment]
@bahodirk I don't think thats needed, did you runned your application again?

**Comment by wcsdev15** [comment]
@moeyerke yep, getting the same error...

**Comment by bahodirk** [comment]
@moeyerke yep, getting the same error...

**Comment by jmoeyersons** [comment]
@bahodirk I missed something in your code, I think this should work:

```
 // 3. bundle
bundle(builderConfig, expressionOrTree, outFile, { minify: false, sourceMaps: false, mangle: false });
  return bundle(builderConfig, expressionOrTree, minOutFile, { minify: true, sourceMaps: false, mangle: false });
```

So just add the mangle option while setting it false should do the trick (I hope)

**Comment by wcsdev15** [comment]
@moeyerke I have tried this, did not help ...

**Comment by bahodirk** [comment]
@moeyerke I have tried this, did not help ...

**Comment by aviramga** [comment]
@marcalj how do I make the dependency install the feat-rc5 branch?
I've tried adding this
    `"ng2-bootstrap": "git+https://github.com/valor-software/ng2-bootstrap.git#feat-rc5",`
to my package.json but after installing again the app fails to import any components from ng2-bootstrap.
I've looked into the ng2-bootstrap directory and found it roughly contains only what was in the last commit.
What am I doing wrong?

**Comment by marcalj** [comment]
Doing it this way It's not prepared as a package for importing on your app. You should clone it and execute gulp task to prepare for publish and then copy the "build" folder inside your `node_modules` folder.

Try: `npm run flow.clean && npm run flow.compile` and use `bundles` folder (not sure if it's how it should be).

**Comment by aviramga** [comment]
I'll give it a shot, thanks!

**Comment by jchewitt** [comment]
DatePickerComponent has issues because it is trying to bind to [templateUrl] which doesn't have an input on DatePickerInnerComponent.

see below

 **datepicker.component.js** - line 158
`template: "\n    <datepicker-inner [activeDate]=\"activeDate\"\n                      (update)=\"onUpdate($event)\"\n                      [datepickerMode]=\"datepickerMode\"\n                      [initDate]=\"initDate\"\n                      [minDate]=\"minDate\"\n                      [maxDate]=\"maxDate\"\n                      [minMode]=\"minMode\"\n                      [maxMode]=\"maxMode\"\n                      [showWeeks]=\"showWeeks\"\n                      [formatDay]=\"formatDay\"\n                      [formatMonth]=\"formatMonth\"\n                      [formatYear]=\"formatYear\"\n                      [formatDayHeader]=\"formatDayHeader\"\n                      [formatDayTitle]=\"formatDayTitle\"\n                      [formatMonthTitle]=\"formatMonthTitle\"\n                      [startingDay]=\"startingDay\"\n                      [yearRange]=\"yearRange\"\n                      [customClass]=\"customClass\"\n                      [dateDisabled]=\"dateDisabled\"\n`

**[templateUrl]**`=\"templateUrl\"\n                      [onlyCurrentMonth]=\"onlyCurrentMonth\"\n                      [shortcutPropagation]=\"shortcutPropagation\"\n                      (selectionDone)=\"onSelectionDone($event)\">\n      <daypicker tabindex=\"0\"></daypicker>\n      <monthpicker tabindex=\"0\"></monthpicker>\n      <yearpicker tabindex=\"0\"></yearpicker>\n    </datepicker-inner>\n    ",`

I have no workaround. Anyone? It shouldn't be trying to bind to an input that isn't available. I don't see where it's even used. I removed the binding from ng2-bootstrap.min.js and it loads.

**Comment by marcalj** [comment]
@jchewitt: @otelnov is doing a rewrite of DatePicker.

**Comment by laurelnaiad** [comment]
I see uglify choking on `get()` shorthand, e.g. this line: https://github.com/valor-software/ng2-bootstrap/blob/development/components/dropdown/dropdown-toggle.directive.ts#L37 .

**Comment by pratiksharma9** [comment]
I want to use date-picker. and update ng2-bootstrap as soon as you can.

**Comment by Martin-Luft** [comment]
@valorkin close?

**Comment by valorkin** [comment]
@Martin-Wegner please accept invite to ng2-team, drop me a dm in slack

**Comment by valorkin** [comment]
Thanks for all your help!

**Comment by dexstakker** [comment]
uhh, did this bug get fixed, I see the same issues in RC6? Same complaining that it needs @input on the class when it already exists on the class and so refuses to bind.

**Comment by Martin-Luft** [comment]
@dexstakker why you use RC6?
