### ISSUE TITLE
feature: Support RC5

### ISSUE THREAD

**Issue by marcalj** [valor-software/ngx-bootstrap#838]
I'm trying to add support for `@NgModule`, trying to create a pull request.

**Comment by marcalj** [comment]
Once update `package.json` to latest version I cannot pass tests, also I'm not familiarized with Webpack and I don't know how to follow steps and debug.

Anyone can give me advise or follow work from mine?

Thanks!

**Comment by carlosthe19916** [comment]
+1

**Comment by jan-zajic** [comment]
+1

**Comment by theunreal** [comment]
+1

**Comment by marcalj** [comment]
(please, don't comment "+1" on this issue, use the reaction feature in the top-right side of the first comment :) thanks!)

**Comment by Martin-Luft** [comment]
@valorkin close?
