### ISSUE TITLE
Need event.preventDefault in tab click event

### ISSUE THREAD

**Issue by slubowsky** [valor-software/ngx-bootstrap#842]
The anchors in tabs handle normal clicks like this:
``(click)="tabz.active = true"`
but clicks on remove are handled like this:
`(click)="$event.preventDefault(); removeTab(tabz);"`

Not sure under what circumstances exactly (couldn't reproduce in simple plunker) but after updating to RC 5 clicking on tabs in my application cause the app to reload (after my selected function completes). Adding $event.preventDefault(); to the anchor click function should prevent this behavior.
(Tested using jQuery

```
$('a').click(function( event ) {
  event.preventDefault();
});
```

and that fixed the issue...)

**Comment by valorkin** [comment]
(click)="removeTab(tabz); return false;"
should do the trick

**Comment by slubowsky** [comment]
I was referring to the ng2-bootstrap code in the tabset.component.ts template, not my code.

```
<a href class="nav-link"
            [class.active]="tabz.active" [class.disabled]="tabz.disabled"
            (click)="tabz.active = true">
            <span [ngTransclude]="tabz.headingRef">{{tabz.heading}}</span>
            <span *ngIf="tabz.removable">
              <span (click)="$event.preventDefault(); removeTab(tabz);" class="glyphicon glyphicon-remove-circle"></span>
            </span>
</a>
```

Where on remove it does $event.preventDefault(); for you but for regular clicks it doesn't. Shouldn't it?

At the time I think I was trying to get it working using $event.preventDefault(); in my click handler but that didn't work. Returning false from a handler seems to.

**Comment by valorkin** [comment]
@slubowsky oh, I know where the issue could be
