### ISSUE TITLE
Can't bind to '[XXX]' since it isn't a known property of 'component'

### ISSUE THREAD

**Issue by gitemconte** [valor-software/ngx-bootstrap#844]
Since upgrading to RC5 I have been experiencing these errors with various ng2-bootstrap components

Specifically:
Can't bind to 'type' since it isn't a known property of 'alert'
Can't bind to 'dismissible' since it isn't a known property of 'alert'
Can't bind to 'justified' since it isn't a known property of 'tabset'

Similar to this issue below re: datepicker and RC5
#833

**Comment by gitemconte** [comment]
So, it appears this is not an ng2-bootstrap issue, but an issue with minifying and compressing my bundled js file after the latest angular updated.

This build_dev build script works with RC4, but produces the above errors once I switched to RC5:

"scripts": {
    "build_dev": "tsc && browserify -s main dist/app/main.js > dist/app/bundle.js && npm run minify && npm run compress",
    "minify": "uglifyjs dist/app/bundle.js --screw-ie8 --compress --mangle --output dist/app/bundle.min.js",
    "compress": "gzip dist/app/bundle.min.js"
  },

If I remove the  && npm run minify && npm run compress from the script, everything works fine with RC5.

**Comment by rgripper** [comment]
https://github.com/angular/angular/issues/10618

**Comment by lanocturne** [comment]
I am having same issue with angular2-webpack build

**Comment by Martin-Luft** [comment]
@valorkin close?

**Comment by amali1025** [comment]
This is the most annoying error I've ever encountered and I hate it
