### ISSUE TITLE
Accordion in Bootstrap4

### ISSUE THREAD

**Issue by linusbrolin** [valor-software/ngx-bootstrap#846]
Since the accordion in Bootstrap 4 is currently very ugly, I have made an ng2-bootstrap4 accordion based on the Bootstrap 4 'card' classes instead.

I previously made an ng2-bootstrap4 accordion using buttons, but this should be more in line with the philosophy of Bootstrap4, where cards are the basis for most things.

My component is based on the accordion component from ng2-bootstrap and uses the CollapseDirective from ng2-bootstrap, and so has ng2-bootstrap as a requirement.

I would be happy to submit it to this project, but my question is whether it would best belong in this project or in the modules project?

**Comment by Hongbo-Miao** [comment]
I think we should not change styles from original Bootstrap, and just leave it "ugly".

The reason is because we custom/overwrite Bootstrap 4 (including Accordion) by ourselves using our own CSS.

**Comment by valorkin** [comment]
all changed :)
now cards should be used, and there are a place for pills

**Comment by Martin-Luft** [comment]
Please have a look at https://github.com/valor-software/ng2-bootstrap/tree/PR1109 which I created for https://github.com/valor-software/ng2-bootstrap/pull/1109

**Comment by xgebi** [comment]
Is there a plan for making accordion compatible with bootstrap 4 in foreseeable future?

**Comment by valorkin** [comment]
Sure thing, this week we are applying last fixes before publishing next version
