### ISSUE TITLE
Entire page is  backdropped

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#847]
Hi ,
 I am trying to use model popup in one of my page, but when I click a button to open the popup, the popup comes but entire page will be blurred, so I can not close the popup. 

Any tips for this issue.

**Comment by vexxra** [comment]
Try checking the z-index of the blur-overlay. I assume it is set too high, causing it to overlay the modal too.

**Comment by ghost** [comment]
I tried to change the z-index also, but no luck

**Comment by Richard87** [comment]
Hi, I have the same problem... The overlay covers the entire page, but the z-index is correct:

My problem is that I have the button-trigger AND the modal template in my nav header

What is the best way to solve this? (I have a loginComponent that have the template and the button to show the template, wich are both inside of my header component)

[https://1drv.ms/i/s!AqNaS28XjQ7xiTVhfpQvr1qlVhxe](https://1drv.ms/i/s!AqNaS28XjQ7xiTVhfpQvr1qlVhxe)

Richard

**Comment by Martin-Luft** [comment]
@vsanat you closed this issue, how do you solved your problem?
