### ISSUE TITLE
modal need update with rc5

### ISSUE THREAD

**Issue by keyiis** [valor-software/ngx-bootstrap#849]
ComponentResolver is deprecated for dynamic compilation. Use ComponentFactoryResolver together with @NgModule/@Component.entryComponents or ANALYZE_FOR_ENTRY_COMPONENTS provider instead. For runtime compile only, you can also use Compiler.compileComponentSync/Async.

**Comment by keyiis** [comment]
I found temp a temporary solution,
1、update components-helper.service.ts
modify ComponentResolver to ComponentFactoryResolver
2、add ModalBackdropComponent to entryComponents[]
modal work fine!

**Comment by vlahanas** [comment]
@keyiis What is entryComponents[] and where do you include it? In the NgModule or in the @Component that uses the modal?

**Comment by batchu** [comment]
@vlahanas

  providers:    [ ],
entryComponents: [ CustomModal ]

**Comment by keyiis** [comment]
@vlahanas 
in NgModule 

```
@NgModule({
  imports: [.....],
  declarations: [
    ...... 
    ModalComponent,ModalBackdropComponent,
    .....
  ],
  entryComponents: [
    ModalBackdropComponent,
    FormComponent
  ],
```
