### ISSUE TITLE
Datepicker adding custom css template

### ISSUE THREAD

**Issue by Redlab1** [valor-software/ngx-bootstrap#855]
Hello, and thank you so much for your work!

I've got an angular 2 project going on for a company, and I'm currently using your datepicker in my implementation.

The project is using systemjs, and is currently on RC4 (planning on updating to RC5 soon).

I'm wondering if it is possible to add a custom css template, to override the current css which is implemented in the daypicker component?

We have currently got an ang 1.5 daypicker component, which I'm trying to replicate with your angular 2 daypicker component.

Any help would be greatly appreciated, and I apologize if there alreadys exists an issue regarding the same question (I tried to find one, without success).

**Comment by Redlab1** [comment]
Temp fixed it by overriding in main.css file.

Would also like to get some examples on how to use the customClass, like #811 is refering to!

**Comment by valorkin** [comment]
check docs for new datepicker
now it is much easier
available in v1.9.2
http://valor-software.com/ngx-bootstrap/#/datepicker

**Comment by experionakash** [comment]
`<input type="text" class="form-control" readonly="readonly" #dp="bsDatepicker" bsDatepicker [bsValue]="bsValue" [minDate]="minDate" [maxDate]="maxDate" (bsValueChange)="datepickerValueChange($event)" [bsConfig]="{ dateInputFormat: dateFormat }"  [customClass]="todayStyling">`

I'm getting the following error while using the customClass property. 

> Template parse errors:
> Can't bind to 'customClass' since it isn't a known property of 'input'.

**Comment by mirellyssl** [comment]
Olá, para customizar o componente datepicker, adicione ao seu css :
::ng-deep (Sempre que for customizar o componente comece com isso)  e em seguida a classe, por exemplo: 
::ng-deep.bs-datepicker-body{
   width: 130% !important;
 }
