### ISSUE TITLE
Datepicker short month

### ISSUE THREAD

**Issue by searchforac** [valor-software/ngx-bootstrap#857]
I'm trying to use short month names in the monthpicker.  I thought it looked straightforward using formatMonth but am not getting any results.  

` 
@Component({
  selector: 'datepicker',
  template: 
   <div id="datepicker-container" style="display:inline-block;">
      <datepicker 
        [(ngModel)]="dt" 
        [formatMonth]="formatMonth"
      </datepicker>
   </div>
})

export class Datepicker {
  public dt:Date = moment('2016-01-01', 'YYYY-MM-DD').toDate();
  public monthFormat = "MM"
  }`

**Comment by macav** [comment]
could you please confirm that this is still an issue? or even better, could you give plunker demonstrating the issue? I tried to reproduce it but `[formatMonth]` works for me.
