### ISSUE TITLE
angular-cli@1.0.0-beta.11-webpack.2 Support

### ISSUE THREAD

**Issue by hamiarcher** [valor-software/ngx-bootstrap#860]
How to setup in angular-cli@1.0.0-beta.11-webpack.2

**Comment by AlBlanc** [comment]
Hi @hamiarcher,

angular-cli@1.0.0-beta.11-webpack.2 is using angular@rc5, ng2-bootstrap is not compatible yet but it's on its way. See [PR](https://github.com/valor-software/ng2-bootstrap/pull/864)

Anyway to setup ng2-bootstrap you just need to install it with npm.

**Comment by adrianfaciu** [comment]
If you use the latest versions of angular-cli@webpack and ng2-bootstrap everything works fine. I've just checked this. Create a new project and just npm install ng2-bootstrap, then you can use it in the application.
