### ISSUE TITLE
Default "no time selected"

### ISSUE THREAD

**Issue by karljv** [valor-software/ngx-bootstrap#863]
Hello

I am using the datepicker, but I cannot figure out how to default to no date selected.

Example:

My database stores a date 0000-00-00 00:00:00, since no date is selected. This means that my ngModel is also of data zero. When I pass this model to the datepicker, I am shown an "Invalid date". How could I somehow tell the datepicker, that if the date is zero, then It just shows for example "yyyy/mm/dd"?

**Comment by valorkin** [comment]
use `null`
