### ISSUE TITLE
Datepicker Format

### ISSUE THREAD

**Issue by porf25** [valor-software/ngx-bootstrap#868]
Trying to figure out how to change the format of the selected dates to something like "08/24/2016"

What I keep getting is something like this: 
Wed Aug 24 2016 00:00:00 GMT-0400 (Eastern Daylight Time)

Anyone know how to change it?

**Comment by hggeorgiev** [comment]
Applying the [DatePipe](https://angular.io/docs/ts/latest/api/common/index/DatePipe-class.html) to your model should help.

**Comment by porf25** [comment]
Trying to use it for a model like so:

`[(ngModel)]="policy.effective | date: 'shortDate"`

I tried to add a pipe to that but got an error:
Cannot have a pipe in an action expression.

I was just curious since I see this bit of code in the example:

```
public formats:Array<string> = ['DD-MM-YYYY', 'YYYY/MM/DD', 'DD.MM.YYYY', 'shortDate'];
  public format:string = this.formats[0];
```

And was hoping that there was a place to put that in the calendar so it display the way I want it to.

**Comment by mhov** [comment]
`[(ngModel)]="something"` is a two-way binding.  So it's actually trying to assign the new value back to `policy.effective | date: 'shortDate'` which doesn't make sense.

**Comment by porf25** [comment]
I was able to get this working the way I wanted to by doing this...

In the component I made a get method like this:

```
get effectiveDate(): string {
        var date = new Date(<any>this.policy.effective);
        return date.toLocaleDateString();
    }
```

And then in the view I changed the input field to this:

`[(ngModel)]="effectiveDate"`

So now it displays the selected date like this: (M/DD/YYYY)

![image](https://cloud.githubusercontent.com/assets/6655998/17865260/b61545d4-686f-11e6-9be5-f458733e783d.png)


Hope it helps someone, and if someone thinks this is a bad idea, please let me know so I don't find out the hard way later.

**Comment by mhov** [comment]
You effectively want a one-way binding since nothing can be written TO `effectiveDate`. `[ngModel]="effectiveDate"` (no parenthesis) would be more appropriate.

**Comment by washingtong33k** [comment]
Sorry to open this thread again. But did anyone find a way to format the date using reactive forms?

**Comment by pbouda** [comment]
@washingtonphp As a workaround I use a separate input that toggles the datepicker and shows the formatted date. I then set the bsDatepicker field to hidden:

```
<input
  type="text"
  class="form-control"
  bsDatepicker
  #newDateControl
  [style.visibility]="'hidden'"
  [formControl]="newOptionDate">
<input
  type="text"
  class="form-control"
  (focus)="newDateControl.toggle()"
  [value]="newOptionDate.valueChanges | async | date:'mediumDate'">
```

**Comment by mrajaraman** [comment]
Is there any way to store only MM/dd/yyyy in my ngModel using new bsDatepicker? Than the full date.

**Comment by Dunnpopo** [comment]
I did this.

Two way binding
<input type="text" [bsConfig]="bsConfig" [(ngModel)]="this.pilot.dob"
                   name="bsDatepicker" class="form-control"
                   #dp="bsDatepicker" bsDatepicker  placeholder="MM-dd-yyyy">
          </div>

on my submit function I change the format of my model value to MM/dd/yyyy ie 01/01/2018
      const date = new Date(<any>this.pilot.dob);
      this.pilot.dob = moment(date).format('MM/DD/YYYY');

**Comment by RodrigoBastos22** [comment]
<input type="text" class="form-control" bsDatepicker #dp="bsDatepicker" [bsConfig]="bsConfig" id="date" name="date" maxlength="10" [(ngModel)]="date">

**app.component.ts**

**import {formatDate} from '@angular/common';**

submit() {
    const date = new Date(this.date);
    this.date = formatDate(date, 'MM/dd/yyyy', 'en');
    console.log(this.date);
}
