### ISSUE TITLE
Compatible with server rendering

### ISSUE THREAD

**Issue by jaumard** [valor-software/ngx-bootstrap#872]
I found all your repo and they look pretty amazing ! Thanks for your work :)

I wanted to know if all your component are compatible with angular universal for server rendering ? 

If you follow the [best practice](https://github.com/angular/universal#best-practices) you are (will be) compatible pretty easily

**Comment by valorkin** [comment]
Hey, yes it was universal compatible,
but universal is very fresh yet
But yes, this module will be universal compatible for sure!

**Comment by rajatKumarr** [comment]
@valorkin can you tell me which version is universal compatible because i am using v1.9.3 and it doesn't look like one.

**Comment by valorkin** [comment]
@rajatKumarr you can check version and how we did it here https://github.com/valor-software/ngx-bootstrap/pull/2925
