### ISSUE TITLE
chore(dropdown): broken in version 1.0.1-beta.0

### ISSUE THREAD

**Issue by rlodge** [valor-software/ngx-bootstrap#88]
Using dropdown in 1.0.1-beta.0, I get the error

```
XHR error (404 Not Found) loading http://localhost:5555/node_modules/ng2-bootstrap/components/dropdown/dropdown.directive.ts.js
```

I think it's because of a require line added to the dropdown typescript files that does

```
import {Dropdown} from './dropdown.directive.ts';
```

instead of

```
import {Dropdown} from './dropdown.directive';
```

Commit a16555438edbb0d006a207f89887d43404836843

**Comment by danielgerlag** [comment]
I'm getting this issue too

**Comment by valorkin** [comment]
Thanks, for issue report, fixed :)

**Comment by valorkin** [comment]
btw published to npm

**Comment by rlodge** [comment]
Thanks for the quick turnaround.

**Comment by valorkin** [comment]
as a module consumer, most of all I hated to wait for small fixes :feelsgood:
