### ISSUE TITLE
datePicker error on `prod` mode

### ISSUE THREAD

**Issue by a5hik** [valor-software/ngx-bootstrap#884]
Hi I use angular cli for the build with SystemJS.

I ran my app with angular rc5 and I'm using the feat-rc5 branch for the ng2-bootstrap.
My App uses 

`[DatePickerModule, ModalModule, DropdownModule]` from ng2-bootstrap.

I have things working fine when I ran the application on `dev` mode. which use JIT compilation.

However I get the below error when I run the app on `--prod` mode. which use AOT compilation.

`Can't bind to 'activeDate' since it isn't a known property of 'datepicker-inner'.
1. If 'datepicker-inner' is an Angular component and it has 'activeDate' input, then verify that it is part of this module.
2. If 'datepicker-inner' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("
    <datepicker-inner [ERROR ->][activeDate]="activeDate"
                      (update)="onUpdate($event)"
                      [da"): a@1:22
Can't bind to 'datepickerMode' since it isn't a known property of 'datepicker-inner'.
1. If 'datepicker-inner' is an Angular component and it has 'datepickerMode' input, then verify that it is part of this module.
2. If 'datepicker-inner' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("r [activeDate]="activeDate"
                      (update)="onUpdate($event)"
                      [ERROR ->][datepickerMode]="datepickerMode"
                      [initDate]="initDate"
                      ["): a@3:22
Can't bind to 'initDate' since it isn't a known property of 'datepicker-inner'.
1. If 'datepicker-inner' is an Angular component and it has 'initDate' input, then verify that it is part of this module.
2. If 'datepicker-inner' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("e)="onUpdate($event)"
                      [datepickerMode]="datepickerMode"
                      [ERROR ->][initDate]="initDate"
                      [minDate]="minDate"
                      [maxDate]="maxD"): a@4:22
Can't bind to 'minDate' since it isn't a known property of 'datepicker-inner'.``

**Comment by a5hik** [comment]
This happened with the SystemJS build of angular cli, switching to WebPack resolved these.

**Comment by macav** [comment]
@a5hik I have the same issue with ng2-bootstrap 1.1 and with webpack (i'm using angular2-webpack-starter).. can you please describe how did you solve it?
