### ISSUE TITLE
Tabs order don't work correctly with ngFor and static tabs

### ISSUE THREAD

**Issue by ildarnm** [valor-software/ngx-bootstrap#889]
If write that code (before create tab through ngFor, after static tab)

``` html
<tabset>
    <tab  *ngFor="let tab of tabs">
      hello!
    </tab>
    <tab heading="static tab">
       static tab
    </tab>
</tabset>
```

first will be showed static tab and after them will be tabs from ngFor

**Comment by adrianfaciu** [comment]
This looks to be the same behaviour as in #823

**Comment by adrianfaciu** [comment]
Implemented an index property for tab component. Waiting for the feat-rc5 branch to be merged before creating a pull request.

**Comment by valorkin** [comment]
duplicate, closing this one
