### ISSUE TITLE
chore(typeahead): async loading broken with angular in dev mode

### ISSUE THREAD

**Issue by danielgerlag** [valor-software/ngx-bootstrap#89]
The Typeahead async example no longer works, unless you put angular in production mode.
You will get "EXCEPTION: Expression has changed after it was checked." errors

https://github.com/angular/angular/issues/6005

**Comment by valorkin** [comment]
try to use `ChangeDetectionStrategy.OnPush` in your component
It should solve the problem
it is not only typeahead problem, so I will have to figure out how to handle it better
current typeahead implementation will be replaced with Observables

**Comment by ps2goat** [comment]
Do you know what the timeline is for the conversion to Observables?

**Comment by Dinistro** [comment]
This should be fixed in the Observable version: #584
