### ISSUE TITLE
feat(modals): add support for nested modals (Modal removes the scrollbar to add its own)

### ISSUE THREAD

**Issue by Scipionh** [valor-software/ngx-bootstrap#896]
When I do open a modal on a page which has a scrollbar, the page is shifted to the right, as the page scrollbar is removed, then shifted back to the left (if the modal has its own scrollbar) which makes the whole thing very wonky.
It looks like opening a modal set overflow: hidden on the body tag (.modal-open class), and then add its own overflow-y: visible.
The same thing happens if you do close the modal.

I am yet to find a way to avoid this wonkyness. While the whole behavior makes sense, I am not sure how to prevent seeing the scrollbar switch.

**Comment by PRR24** [comment]
Connected to the issue is if you have a modal that has a scroll and you open another modal on top of it, then after closing the topmost one, scrollbar for the first modal does not return and you can no longer scroll it (not tested in 1.1, is present in 1.0.24).
My typical use case of double modals:
... => edit item => modal dialog => changes to the item => are-you-sure modal => action => ...

**Comment by valorkin** [comment]
nested modal, this use case not covered in twitter bootstrap, so this behavior simply not supported yet :)

**Comment by nampdn** [comment]
@PRR24 I meet same problem like you, can't scroll the parent when the child modal is closed. Hope this behavior will support soon :)

**Comment by Martin-Luft** [comment]
The first issue (page has scrollbars which disappear when opening a model) is  very annoying :(

Workaround:

`<body style="overflow-y: visible !important;">`

**Comment by Martin-Wegner** [comment]
Workaround:

`<body style="overflow-y: visible !important;">`

**Comment by szh** [comment]
Any update on this? I have Modal A which opens Modal B, but Modal B is bigger than Modal A, so it only shows up as big as Modal A, and has a vertical scrollbar. I think it should instead be appended to the body outside of Modal A.
Thanks

**Comment by Martin-Luft** [comment]
Better workaround is to use in the main CSS:

```
.modal-open {
  overflow-y: auto;
}
```

**Comment by IlyaSurmay** [comment]
Implemented by #1987
