### ISSUE TITLE
multi select for datepicker

### ISSUE THREAD

**Issue by nasreddineskandrani** [valor-software/ngx-bootstrap#900]
hi,
is their a way to activate multi-select in datepicker of ng2-bootstrap?

**Comment by valorkin** [comment]
multi select of dates?

**Comment by Martin-Luft** [comment]
Is this supported in orignal bootstrap widgets?

**Comment by marcalj** [comment]
You mean, a selector of start and end date?

**Comment by valorkin** [comment]
range selection will be in new version of datepicker

**Comment by nasreddineskandrani** [comment]
sorry i was on vacations. Yes a selector of start and end date

**Comment by darkguy2008** [comment]
What about multiple dates though? (not range, just multiple dates)
