### ISSUE TITLE
Give link in the tooltip (which appears on hover of an element)

### ISSUE THREAD

**Issue by monica11** [valor-software/ngx-bootstrap#904]
I want to give a link in the tooltip.For which i need to show the tooltip even when i move my cursor from the element to the tooltip container. But as soon as i do that, the tooltip disappears. 
For reference, please see http://jsfiddle.net/hermanho/4886bozw/. I want such behaviour with ng2-bootstrap.

**Comment by dessalines** [comment]
That's a popover, not a tooltip. ng2-bootstrap doesn't include any popovers, but [here's](https://github.com/pleerock/ng2-popover) one.

**Comment by valorkin** [comment]
it will be added soon!
nice link @tchoulihan :)

**Comment by dessalines** [comment]
@valorkin Thanks! [Multiple typeahead result sets](https://github.com/valor-software/ng2-bootstrap/issues/794) [example](https://twitter.github.io/typeahead.js/examples/#multiple-datasets) is on my ng2-bootstrap wishlist now.
