### ISSUE TITLE
Support for RC6

### ISSUE THREAD

**Issue by isaackehle** [valor-software/ngx-bootstrap#906]
I just upgraded to RC6, and now webpack is giving errors:

```
[default] /Users/pgkehle/projects/security-portal/node_modules/ng2-bootstrap/components/datepicker/datepicker-popup.component.d.ts:1:10
    Module '"/Users/pgkehle/projects/security-portal/node_modules/@angular/core/index"' has no exported member 'DynamicComponentLoader'.
[default] /Users/pgkehle/projects/security-portal/node_modules/ng2-bootstrap/components/tooltip/tooltip.directive.d.ts:1:10
    Module '"/Users/pgkehle/projects/security-portal/node_modules/@angular/core/index"' has no exported member 'DynamicComponentLoader'.
[default] /Users/pgkehle/projects/security-portal/node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts:1:54
    Module '"/Users/pgkehle/projects/security-portal/node_modules/@angular/core/index"' has no exported member 'DynamicComponentLoader'.
[default] /Users/pgkehle/projects/security-portal/node_modules/ng2-bootstrap/components/utils/components-helper.service.d.ts:1:58
    Module '"/Users/pgkehle/projects/security-portal/node_modules/@angular/core/index"' has no exported member 'ComponentResolver'.
[default] /Users/pgkehle/projects/security-portal/node_modules/ng2-bootstrap/components/utils/components-helper.service.d.ts:42:32
    Generic type 'Type<T>' requires 1 type argument(s).
```

From here:  http://stackoverflow.com/questions/38332249/angular-2-rc4-dynamiccomponentloader-deprecated

ComponentResolver and ViewContainerRef are alternatives.

**Comment by glaucomorais** [comment]
Same thing here.
Every `@Component` usage is getting the`"@angular/core/index" has no exported member 'ComponentResolver'` error message.

**Comment by spock123** [comment]
Yeah, according to the changelog for RC6, https://github.com/angular/angular/blob/master/CHANGELOG.md, ComponentResolver is deprecated.

> core: deprecated ComponentResolver was removed. Please use ComponentFactoryResolver instead.

**Comment by spock123** [comment]
Also:

`core: Type is now Type<T> which means that in most cases you have to use Type<any> in place of Type.`

**Comment by spock123** [comment]
Seems ng2-bootstrap 1.1 is out, with upgrades to RC6.. let's give it a try

Thank you so much for all your hard work, guys
update: sorry, no 1.1.0 is for RC5.

**Comment by Martin-Luft** [comment]
@valorkin can you please publish a new npm release 1.1.1 (1.1.0 is RC5)? But before please merge PR https://github.com/valor-software/ng2-bootstrap/pull/909

**Comment by Hongbo-Miao** [comment]
https://github.com/valor-software/ng2-bootstrap/pull/908 just updated to rc6

**Comment by elaijuh** [comment]
probably not related to here, but when can we hve `@types` ?

**Comment by elirenato** [comment]
also waiting for npm release 1.1.1 to support RC6 :)

**Comment by sprypradeep** [comment]
Need to make changes to components-helper.service.d.ts

> core: merge Type and ConcreteType<?> into Type<?> (#10616) (b96869a), closes #9729

https://github.com/angular/angular/pull/10616

**Comment by elirenato** [comment]
just to complement @sprypradeep. 

I get the error below when using angular-rc6 with ng2-bootstrap 1.1.0:

.../node_modules/ng2-bootstrap/components/utils/components-helper.service.d.ts(2,10): error TS2305: Module '".../node_modules/@angular/core/src/facade/lang"' has no exported member 'ConcreteType'.

**Comment by Martin-Luft** [comment]
@sprypradeep this is already fixed in master. We must wait until @valorkin merged the PR https://github.com/valor-software/ng2-bootstrap/pull/909 and created a new npm release (1.1.1). I hope he will do it tomorrow :)

**Comment by goeranhomberg** [comment]
Same problem here:

`ng2-bootstrap/components/utils/components-helper.service.d.ts(2,10): error TS2305: Module '.../client/node_modules/@angular/core/src/facade/lang"' has no exported member 'ConcreteType'.`

a new release would be nice :)

**Comment by isaackehle** [comment]
Thank you for the quick work!

**Comment by elirenato** [comment]
Thank you!, I just updated my project and it's working.

**Comment by valorkin** [comment]
Glad to hear it helped :)

**Comment by ashwinirajput** [comment]
import { Component,OnInit,ModuleWithProviders,ViewContainerRef,Injector,DynamicComponentLoader} from '@angular/core';
file: 'file:///Users/ashwini/Documents/angular-quickstart/app/app.component.ts'
severity: 'Error'
'"/Documents/angular-quickstart/node_modules/@angular/core/index"' 
has no exported member 'DynamicComponentLoader'.'

**Comment by valorkin** [comment]
Update ng2 bootstrap to latest
