### ISSUE TITLE
How to add new Tab dynamically?

### ISSUE THREAD

**Issue by sanket360** [valor-software/ngx-bootstrap#907]
As mentioned in TABS directive documentation (https://github.com/valor-software/ng2-bootstrap/tree/development/components/tabs), tabs has 3 events - select, deselect and removed.

How to add new Tab dynamically? and is there a event available to do a functionality on onLoad kind of event?

**Comment by adrianfaciu** [comment]
Keep the tabs in a collection and display them with NgFor. Then you can simply add or remove items from the collection as needed.

You can have a look at the dynamic tabs from the [demo page](http://valor-software.com/ng2-bootstrap/#/tabs).

For _onLoad_ functionality you should have a look at the component [lifecycle hooks](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#hooks-overview).
