### ISSUE TITLE
Modal exception in rc5 - No provider for AppComponent

### ISSUE THREAD

**Issue by Gillardo** [valor-software/ngx-bootstrap#910]
I have just updated to the latest version, which includes all the rc5 NgModule changes (thanks for this).

My code loads fine, so i believe i am including the `ModalModule` in the correct places, but when i try to open one, i get this exception

> EXCEPTION: No provider for AppComponent!

I have included the following code in my AppComponent.ts file as stated by the docs

> import {Component, ViewContainerRef} from '@angular/core';
> 
> @Component({selector:'app-root'})
> class AppRoot {
>   public constructor(viewContainerRef:ViewContainerRef) {
>     // You need this small hack in order to catch application root view container ref
>     this.viewContainerRef = viewContainerRef;
>   }
> }

Am i missing something?

**Comment by Martin-Luft** [comment]
duplicate of https://github.com/valor-software/ng2-bootstrap/issues/854 ?

**Comment by valorkin** [comment]
it looks like you copied this line `import { AppComponent }  from './app.component';` from `readme`
remove it if you don't need it

**Comment by Gillardo** [comment]
@valorkin where do you see that? Which file should i remove it in?
