### ISSUE TITLE
Dropdowns rendering incorrectly

### ISSUE THREAD

**Issue by slubowsky** [valor-software/ngx-bootstrap#911]
With 1.1.0 split button dropdowns are rendering incorrectly (no arrow). See this on dropdown demo page at http://valor-software.com/ng2-bootstrap/index-bs4.html#/dropdowns as well.

**Comment by slubowsky** [comment]
Made no significant changes but seems to work today...

**Comment by Martin-Luft** [comment]
I think it was the use of `Type` instead of `window` als `global` replacement. Good to know that it works now :)

**Comment by slubowsky** [comment]
Yes - Actually forgot that I had updated to 1.1.1 this morning. Got involved in something else before testing and then noticed this working later on.
