### ISSUE TITLE
errors on rc.6

### ISSUE THREAD

**Issue by born2net** [valor-software/ngx-bootstrap#912]
```
Uncaught (in promise) Error: (SystemJS) SyntaxError: Unexpected token export
        at Object.eval (http://localhost:9089/jspm_packages/npm/ng2-bootstrap@1.1.0/components/ng2-bootstrap-config.js:2:14)
        at eval (http://localhost:9089/jspm_packages/npm/ng2-bootstrap@1.1.0/components/ng2-bootstrap-config.js:29:4)
        at eval (http://localhost:9089/jspm_packages/npm/ng2-bootstrap@1.1.0/components/ng2-bootstrap-config.js:30:3)
    Evaluating http://localhost:9089/jspm_packages/npm/@angular/core@2.0.0-rc.6/src/facade/lang.js
    Evaluating http://localhost:9089/jspm_packages/npm/ng2-bootstrap@1.1.0/components/ng2-bootstrap-config.js
    Evaluating http://localhost:9089/jspm_packages/npm/ng2-bootstrap@1.1.0/components/carousel/carousel.component.js
    Evaluating http://localhost:9089/jspm_packages/npm/ng2-bootstrap@1.1.0/components/carousel.js
    Evaluating http://localhost:9089/jspm_packages/npm/ng2-bootstrap@1.1.0/ng2-bootstrap.js
    Error loading http://localhost:9089/src/App.ts
```

**Comment by Martin-Luft** [comment]
This is already fixed in master. The reason is: https://github.com/angular/angular/issues/11197

**Comment by born2net** [comment]
TX ... any chance of pushing it to npm?

**Comment by born2net** [comment]
any workaround to apply fix as I need to get ng2-bootstrap working so I can continue and work on ng2 rc.6 project... tx

Sean

**Comment by born2net** [comment]
does that mean we have to wait for rc.7 to be able to use this lib?

**Comment by Martin-Luft** [comment]
@born2net I really hope that it will released tomorrow! Btw. I don't know if RC7 is planned before final release: https://github.com/angular/angular/milestones

**Comment by born2net** [comment]
so how do we get the fix tomorrow, re-install rc.6?

**Comment by Martin-Luft** [comment]
@born2net it is not an Angular 2 bug. ng2-bootstrap used internal API from Angular 2 and the Angular 2 team blocked that abuse since RC6. ng2-bootstrap 1.1.0 is for Angular 2 RC5. I hope that @valorkin will release ng2-bootstrap 1.1.1 (for Angular RC6) soon. The code in the master branch works with Angular 2 RC6 but the release is missing :(

**Comment by valorkin** [comment]
@Martin-Wegner please join https://www.hamsterpad.com/chat/ng2
so you can get my attention faster where it is needed

**Comment by layton-glympse** [comment]
I'm still seeing this issue, even with the update to ng2-boostrap 1.1.1.
Though, mine stems from lang.js:

`lang.js:21Uncaught SyntaxError: Unexpected token export`

That's all I get... there's no stack trace.
