### ISSUE TITLE
Breaking changes in 1.1.0

### ISSUE THREAD

**Issue by klpx** [valor-software/ngx-bootstrap#914]
Just a tip for further releases.
Semver suppose that "^1.0.24" is "any version compatible with 1.0.24". And in semver it means ">=1.0.24 <2.0.0" (https://docs.npmjs.com/misc/semver).

Today my CI build was broken because of new version 1.1.0 is uncompatible with 1.0.24. I've got this error:

```
(8,9): error TS2305: Module '.../node_modules/ng2-bootstrap/ng2-bootstrap"' has no exported member 'PAGINATION_DIRECTIVES'.
```

**Comment by Martin-Luft** [comment]
I would vote for a X.X.XX pattern :) So next version 1.1.01 or 1.1.10? @valorkin?

**Comment by marcalj** [comment]
For npm `"^1.0.24"` it means `1.0.0 --> 1.0.x`.
For npm `>=1.0.24 <2.0.0` it means `1.0.25 --> 1.x.x`.

1.0 to 1.1 it means it can contain breaking changes.
1.0.24 to 1.0.25 it can only contain fixes without serious code refactoring.

Set `^1.0.24` to package.json to make sure it won't enter huge breaking changes.

**Comment by marcalj** [comment]
semver versioning it's a lovely standard. I won't ask to change it as @Martin-Wegner propose (1.1.01 it's a non-sense for semver, next 1.1.9++ is 1.1.10)

**Comment by Martin-Luft** [comment]
@marcalj ahh you are totally right :) Can npm handle this example?

`^1.0.1` and then a version `1.0.10` released? I know that other frameworks have problems if the number of digits change.

**Comment by Martin-Luft** [comment]
> next 1.1.9++ is 1.1.10

OK, so npm can handle this :)

In summary: The change from 1.0.24 to 1.1.0 is correct because RC5 contains many breaking changes. And the current pattern follows the the semver versioning. So everything is fine and we can close this issue.
