### ISSUE TITLE
After upgrade to 1.1.0 with angular rc.5, child modal does not work

### ISSUE THREAD

**Issue by rernens** [valor-software/ngx-bootstrap#916]
I have upgraded an existing app to angular rc.5 and moved my code to ngModule implementation now that ng2-bootstrap supports rc.5 with version 1.1.0

This app is based on Nathan Walker angular2-seed-advanced.

Upgraded my web.module.ts to import Ng2BootstrapModule
my main app module is also imported here
this module imports a shared module that handles shared components and services for my entire app including a toolbar component that uses child modal to display user profile info.

Now when application is loading I get te following error 

Template parse errors: There is no directive with "exportAs" set to "bs-modal"

Here is the code used :

toolbar.component.html

```
...
<mcapps-profile [ngClass]="{'hidden': !auth.isLoggedIn }" #profile="profileModal" ></mcapps-profile>
```

profile.component.html

```
<div bsModal #profileModal="bs-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myProfileModalLabel" aria-hidden="true" [config]="{backdrop: 'static'}">
...
</div>
```

profile.component.ts

```
// angular
import { ViewChild, OnInit, DoCheck, ChangeDetectionStrategy, ChangeDetectorRef }  from '@angular/core';
import { FormBuilder, FormGroup, Validators }   from '@angular/forms';

// lib
import { ModalDirective } from 'ng2-bootstrap/ng2-bootstrap';


// app
import { BaseComponent, LogService } from '../../../core/index';
import { IProfile, AuthService, PasswordValidator, ProfileValidator, EmailValidator, MyClubAppsApiService } from '../../index';


@BaseComponent({
  moduleId: module.id,
  selector: 'mcapps-profile',
  templateUrl: 'profile.component.html',
  exportAs: 'profileModal',
  changeDetection: ChangeDetectionStrategy.OnPush
})


export class ProfileComponent implements OnInit, DoCheck {

  @ViewChild('profileModal') public profileModal: ModalDirective;

....
```

I can't figure out what I am doing wrong here.

Worked perfectly well prior to moving to 1.10 and NgModule implementation.

Help appreciated.

**Comment by Martin-Luft** [comment]
Can you show us your `ngmodule` declaration, please?

**Comment by rernens** [comment]
thanks for your reply, meanwhile I found what the problem was : ModalModule was imported twice from different places.
