### ISSUE TITLE
rc.6 error

### ISSUE THREAD

**Issue by phmello** [valor-software/ngx-bootstrap#918]
after update to rc.6

ERROR in [default] /node_modules/ng2-bootstrap/components/utils/components-helper.service.d.ts:2:9 
Module '"/node_modules/@angular/core/src/facade/lang"' has no exported member 'ConcreteType'.

**Comment by marcalj** [comment]
RC6 support is coming in the next version. Team is aware of this issue. Thanks :)

**Comment by elaijuh** [comment]
this is really breaking change and it's in `development` branch already, can we get it released asap, thanks.

**Comment by Martin-Luft** [comment]
1.1.1 with RC6 support is out -> close :)
