### ISSUE TITLE
use ng2-bootstrap with native javascript app

### ISSUE THREAD

**Issue by BehnamAbdy** [valor-software/ngx-bootstrap#921]
i want to import ng2-bootstrap modules inside my angular2 app written with pure javascript, when i try to add some of module inside app imports the app crashes and dont find the references,
also ive added the reference to ng2-bootstrap.js file in html document
here is the source 
(function (app) {

```
app.AppModule =
  ng.core.NgModule({
      imports: [ng.platformBrowser.BrowserModule,
                ng.forms.FormsModule,
                ng2Bootstrap.Ng2BootstrapModule], // **this is the way id import it**
      declarations: [app.AppComponent],          
      bootstrap: [app.AppComponent]
  })
  .Class({
      constructor: function () { }
  });
```

})(window.app || (window.app = {}));

**Comment by Martin-Luft** [comment]
I think you should import the modules you need e.g. DropdownModule, AlertModule and so one.

**Comment by BehnamAbdy** [comment]
I couldn't find any sample implementing ng2-bootstrap in pure JavaScript.I tried different approaches including for importing modules like DropdownModule, AlertModule but crashes.I need the syntax

**Comment by PEsteves8** [comment]
Keep in mind that almost everything that is "Typescript" is also pure native javascript, although it's the new Ecmascript 2015 version. Most of those features are supported by modern browser versions. I think the only thing that is unique to typescript apart from the optional types is the part related to dependency injection that works by simply declaring the services in the constructor parameters of the classes.

So, I wouldn't say it's accurate to suggest that the syntax you're using is pure native javascript. It is pure native ES5 javascript (but you could just use pure native ES2015, although for now, to allow support for older browsers converting to ES5 should be done)

**Comment by Martin-Luft** [comment]
Duplicate of #923.
