### ISSUE TITLE
use ng2-bootstrap with plain javascript

### ISSUE THREAD

**Issue by BehnamAbdy** [valor-software/ngx-bootstrap#923]
I'm looking for a way to implement the ng2-bootstrap  in my   angular2 app written with plain JavaScript instead of typescript.
.actually I found nothing helpful through my googlings
Please help me

Regards

**Comment by Martin-Luft** [comment]
Because there is no JavaScript version of https://angular.io/docs/js/latest/guide/ngmodule.html it's difficult to help you :(

**Comment by Martin-Luft** [comment]
Modules (ngModul) are described in the Angular 2 quickstart:
https://angular.io/docs/js/latest/quickstart.html
