### ISSUE TITLE
carousel not working with R.C.5

### ISSUE THREAD

**Issue by ahmedolaibrahim** [valor-software/ngx-bootstrap#924]
i tried to implement the carousel component using angular R.C 5  as demonstrated in the demo example  but i get this error when trying to compile with webpack.

ERROR in [default] c:/node_modules/ng2-bootstrap/components/utils/components-helper.service.d.ts:45:44
Type 'Type' is not generic.

**Comment by manh-vv** [comment]
I had the same error when trying to use ng2-bootstrap datepicker with angular2-webpack-starter

**Comment by goorockey** [comment]
+1

**Comment by Martin-Luft** [comment]
You used ng2-bootstrap version 1.1.1 which only works with Angular RC6. For Angular RC5 you need ng-boostrap 1.1.0.

**Comment by ModalSeoul** [comment]
Still having this issue on Angular RC.5 using 1.1.0 of ng2-bootstrap

**Comment by Martin-Luft** [comment]
@ModalSeoul version 1.1.0 source code does not contain any `Type<...>`...
 Is it possible that you downgraded from 1.1.1 to 1.1.0 and forgotten to clean up your working directory?
