### ISSUE TITLE
feat(ng2-cli): add *.metadata.json

### ISSUE THREAD

**Issue by n-sviridenko** [valor-software/ngx-bootstrap#933]
**Update** by valorkin:
- npm prepublish should generate metadata

---

When I'm try to launch `ng-xi18n` on rc6 via npm, I have this error:

```
$ ng-xi18n
```

```
Error: Unexpected value 'TypeaheadModule' imported by the module 'LocationModule'
    at /srv/app/node_modules/@angular/compiler/bundles/compiler.umd.js:14118:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/srv/app/node_modules/@angular/compiler/bundles/compiler.umd.js:14103:46)
    at /srv/app/node_modules/@angular/compiler/bundles/compiler.umd.js:12947:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (/srv/app/node_modules/@angular/compiler/bundles/compiler.umd.js:12946:21)
    at Extractor.extract (/srv/app/node_modules/@angular/compiler-cli/src/extract_i18n.js:92:47)
    at extract (/srv/app/node_modules/@angular/compiler-cli/src/extract_i18n.js:16:35)
    at Object.main (/srv/app/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/srv/app/node_modules/@angular/compiler-cli/src/extract_i18n.js:161:9)
Extraction failed
```

**Comment by n-sviridenko** [comment]
The code of the `LocationModule`:

```
...
import { TypeaheadModule } from 'ng2-bootstrap';

@NgModule({
  imports: [
    ...,
    TypeaheadModule,
  ],
  ...
})
export class LocationModule {}
```

**Comment by Martin-Luft** [comment]
Please try `import { TypeaheadModule } from 'ng2-bootstrap/ng2-bootstrap';`

**Comment by n-sviridenko** [comment]
Unfortunately, the same behaviour.

**Comment by tamaracha** [comment]
I get the same behavior with compiler-cli by importing CollapseModule this way:

``` javascript
import { CollapseModule } from 'ng2-bootstrap/components/collapse';
```

and this way:

``` js
import { CollapseModule } from 'ng2-bootstrap/ng2-bootstrap';
```

It happens, when CollapseModule is included in NgModule imports array. In urish/angular2-moment#68 and chymz/ng2-ckeditor#36 it is assumed, that a *.metadata.json is expected by compiler-cli. The angular packages contain them, ng2-bootstrap package does not.

**Comment by freezy** [comment]
Any update on this? I've tried generating the metadata files, but it fails with `Error encountered resolving symbol values statically. Expression form not supported` for all the template literals used in the `@Component` definitions.

**Comment by otelnov** [comment]
working on it. there are lot of es6 template literals I should change, no chance compile with it.

**Comment by raphaelmesquita** [comment]
Also, I noticed that some parts of the code just wont compile to js after building the transpiled typescript with ngc. Apparently this is because angular does not allow private or protected fields to be used in the template when compiling AoT. Are you guys aware of this issue?
