### ISSUE TITLE
Error: TS2315: Type 'Type' is not generic.

### ISSUE THREAD

**Issue by hkulekci** [valor-software/ngx-bootstrap#936]
Firstly I integrate and use ng2-bootstrap. Then, I removed `node_modules` for a clear install and installed all packages again. Now, I am getting below error when I start angular app with `npm start`.  

```
    "@angular/common": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
```

And I am getting below error:

```
node_modules/ng2-bootstrap/components/utils/components-helper.service.d.ts(45,45): error TS2315: Type 'Type' is not generic.
node_modules/ng2-bootstrap/components/utils/components-helper.service.d.ts(56,41): error TS2315: Type 'Type' is not generic.

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/*******/.nvm/versions/node/v6.1.0/bin/node" "/Users/*******/.nvm/versions/node/v6.1.0/bin/npm" "start"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
```

There is some logs on Changelog of Angular2 but it is about `rc.6`. I am using `rc.5`. 

> ...
> core: merge Type and ConcreteType<?> into Type<?> (#10616) (b96869a), closes #9729
> ...

**Comment by Martin-Luft** [comment]
For old Angular RC5 you must use ng2-bootstrap 1.1.0.
