### ISSUE TITLE
Selecting typeahead option throws error

### ISSUE THREAD

**Issue by MarkoSulamagi** [valor-software/ngx-bootstrap#94]
I have the latest ng2-bootstrap and I'm getting errors implementing typeahead. When I select option from typeahead autocomplete, I get following error:
ORIGINAL EXCEPTION: TypeError: Cannot read property 'boundElements' of undefined

I managed to track error to typeahead.directive.ts, line 11:
renderer.setElementProperty(elementRef.nativeElement, propName, propValue);

Problem was that setElementProperty is expecting elementRef, not elementRef.nativeElement. If I changed it, then I'm not getting following error anymore. The option is selected, dropdown is closed, but my (typeahead-on-select) event is not called. 

I'm using static autocomplete (tried with complex and not complex solutions). 

```
<input class="form-control" placeholder="placeholder"
   [(ngModel)]="itemType"
   [typeahead]="itemTypesCache"
   [typeaheadOptionField]="'name'"
   [typeaheadOptionsLimit]="7"
   (typeahead-on-select)="onItemTypeSelect($event)">
```

---

```
public onItemTypeSelect(e: any) {
    console.log("Selected"); // <-- This line is not called
}
```

**Comment by MarkoSulamagi** [comment]
Figured out, there's a mistake in doc. (typeahead-on-select) event is actually typeaheadOnSelect .
I'll fork it, fix it and make pull request

**Comment by valorkin** [comment]
hey, I have closed PR for now, it seems you are using angular2 beta0 with ng2-bootstrap beta.1
please check and reopen if necessary
