### ISSUE TITLE
RC6 error

### ISSUE THREAD

**Issue by chambersDon** [valor-software/ngx-bootstrap#945]
According to issue #918 RC6 is supported with version 1.1.1.  I have that version but I can't get it to work with RC6.

Following the the instruction on gitHub I setup app.module like this:

```
import {AlertModule} from 'ng2-bootstrap/ng2-bootstrap';
@NgModule({
    imports: [BrowserModule, AlertModule],
    exports: [],
    providers: [],
    declarations: [AppComponent],
    bootstrap: [AppComponent]
})
```

This throws the following error:

> Error: SyntaxError: Unexpected token <
> at Object.eval (http://localhost:54675/lib/js/ng2-bootstrap/components/datepicker/date-formatter.js:2:14)
> at eval (http://localhost:54675/lib/js/ng2-bootstrap/components/datepicker/date-formatter.js:13:4)
> at eval (http://localhost:54675/lib/js/ng2-bootstrap/components/datepicker/date-formatter.js:14:3)
> Evaluating http://localhost:54675/lib/js/moment/moment
> .....

At this point I have done nothing else.  I have not added any of the components.

I am actually interested in the modal, but when that would not work I decided to follow the instructions   at gitHub and got this error.

**Comment by dalibor-sanzeru** [comment]
Hi, I suppose tht this can be related to system.js connfiguration. I dont know about your build/deployment process... but it seams that system.js try to parse JS file located at url 
http://localhost:54675/lib/js/ng2-bootstrap/components/datepicker/date-formatter.js
But probably there is HTML tag - maybe Loading... page or simply HTML page.

I got the same error for my app only by importing NgBootstrapModule to @NgComponent. For my current mapping in system.js was missing this:

 packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      **"ng2-bootstrap": {
        defaultExtension: 'js'
      }**
...
    }

**Comment by Martin-Luft** [comment]
@chambersDon does the hint from @dalibor-sanzeru helps you? Can I close the issue?

**Comment by valorkin** [comment]
closed for inactivity, and @dalibor-sanzeru comment should help, thanks!

**Comment by chambersDon** [comment]
It did not.  I already had this setup in system.config.

**Comment by chambersDon** [comment]
I've upgraded to 1.1.2.  I still have the problem but I'll open a separate issue about it.  You can close this.
