### ISSUE TITLE
No provider for TabsetComponent!

### ISSUE THREAD

**Issue by vixriihi** [valor-software/ngx-bootstrap#946]
I keep getting "No provider for TabsetComponent!" error using v1.1.1 in rc6. Other components are working without issues.
using like this

```
....
import { TabsModule,CarouselModule,AlertModule,DropdownModule,ModalModule,PaginationModule,TypeaheadModule } from 'ng2-bootstrap/ng2-bootstrap;

....
@NgModule({
  declarations: [
    AppComponent,
    HomeComponent
  ],
  imports: [
    BrowserModule, FormsModule, HttpModule, TabsModule, CarouselModule, AlertModule, DropdownModule, ModalModule, PaginationModule, TypeaheadModule,
    RouterModule.forRoot(rootRouterConfig)
  ],
  providers: [
    { provide: LocationStrategy, useClass: PathLocationStrategy }
  ],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule {

}

```

Already tried to import the whole Ng2BootstrapModule but with same effect

**Comment by Martin-Luft** [comment]
Can you show us your template please?

**Comment by valorkin** [comment]
This very strange, have you solved in issue?

**Comment by vixriihi** [comment]
wow not sure exactly what the real issue was, but I pinpointed the problem to these lines in the component that wrapped tabset:

```
<observation-result [tab]="'map'"></observation-result>
....
@Input() tab:string;
```

I changed them to be like this

```
<observation-result [activeTab]="'map'"></observation-result>
....
@Input() activeTab:string;
```

and everything is working again. It could be that it's because there was tab tag defined and I was using that also as input variable... It used to work just fine in rc4, but after updating to rc6... problem began.

**Comment by valorkin** [comment]
Yeap, most probably :) glad you fixed
