### ISSUE TITLE
How to keep tabs in one row?

### ISSUE THREAD

**Issue by sanket360** [valor-software/ngx-bootstrap#952]
I have created simple tabset like this-

```
import { Component, OnInit } from '@angular/core';
import {CORE_DIRECTIVES} from '@angular/common';
import {TAB_DIRECTIVES } from 'ng2-bootstrap/ng2-bootstrap';

@Component({
  selector: 'my-app',
   directives: [TAB_DIRECTIVES, CORE_DIRECTIVES],
  template: `<h1>My First Angular 2 App</h1>

    <tabset>
    <tab heading="Static title">Static content</tab>
    <tab *ngFor="let tabz of tabs"
         [heading]="tabz.title"
         [active]="tabz.active"
         (select)="tabz.active = true"
         (deselect)="tabz.active = false"
         [disabled]="tabz.disabled"
         [removable]="tabz.removable"
         (removed)="removeTabHandler(tabz)">
      {{tabz?.content}}
    </tab>
    <tab (select)="alertMe()">
      <template tabHeading>
        <i class="glyphicon glyphicon-bell"></i> Alert!
      </template>
      I've got an HTML heading, and a select callback. Pretty cool!
    </tab>
  </tabset>

  `
})
```

when there are 4-5 tabs it looks fine. But when users keep adding tabs beyond screen width it moves to next row and then another row.

we would like to implement visual studio like tabs where additional tabs will be available in dropdown. 

![untitled](https://cloud.githubusercontent.com/assets/16756121/18416591/593a66ec-7836-11e6-81ab-789db26013ae.png)

Is this feature supported by your TAB_Directives? or is there any other way to keep TABS in one line only?

**Comment by valorkin** [comment]
nope, this is not solved by tabs directive
not here, not in original twt bootstrap
basically you need to control amount of visible tabs grammatically
you can extend tabs components with additional logic
