### ISSUE TITLE
ng2-bootstrap 404 (Not Found) On Angular RC6

### ISSUE THREAD

**Issue by calvinKG** [valor-software/ngx-bootstrap#954]
Hi, 

Am using Angular RC 6 and ng2-bootstrap those not want to load, I get the 404 error 

My Code 

SystemsJS 
`(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'dist',
            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            // other libraries
            'rxjs':                       'npm:rxjs',
            'angular2-in-memory-web-api': 'npm:angular2-in-memory-web-api',
            'ng2-bootstrap':              'npm:ng2-bootstrap',
            'primeng':                    'npm:primeng',
            'moment':                     'npm:moment/moment.js'

```
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
        app: {
            main: './main.js',
            defaultExtension: 'js'
        },
        "ng2-bootstrap": {
            defaultExtension: 'js'
        },
        rxjs: {
            defaultExtension: 'js'
        },
        'angular2-in-memory-web-api': {
            main: './index.js',
            defaultExtension: 'js'
        }
    }
});
```

})(this);`
Index 

`   <html>
<head>
    <base href="/">
    <title>Index</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

```
<link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="node_modules/primeui/themes/bootstrap/theme.css"/>
<link rel="stylesheet" href="node_modules/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="node_modules/primeui/primeui-ng-all.min.css" />

<link rel="stylesheet" href="src/assets/css/styles.css">
<!-- 1. Load libraries -->
<!-- Polyfill(s) for older browsers -->
<!-- Polyfill(s) for older browsers -->
<script src="node_modules/core-js/client/shim.min.js"></script>
<script src="node_modules/zone.js/dist/zone.js"></script>
<script src="node_modules/reflect-metadata/Reflect.js"></script>
<script src="node_modules/systemjs/dist/system.src.js"></script>
<!-- 2. Configure SystemJS -->
<script src="systemjs.config.js"></script>
<script src="node_modules/ng2-bootstrap/bundles/ng2-bootstrap.js"></script>
<script>
    System.import('dist').catch(function(err){ console.error(err); });
</script>

<script src="node_modules/jquery/dist/jquery.min.js"></script>

<script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="src/assets/js/menu.js"></script>
```

</head>

<body>
<my-app>Loading...</my-app>
</body>
</html>
 `

package.json
`
 {
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/compiler-cli": "0.6.0",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.6",
    "angular2-in-memory-web-api": "0.0.14",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.1",
    "ng2-bootstrap": "^1.1.2",
    "primeng": "^1.0.0-beta.15",
    "primeui": "^4.1.14",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.11",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.17"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "font-awesome": "^4.6.3",
    "font-awesome-animation": "0.0.8",
    "i": "^0.3.5",
    "jquery": "^3.1.0",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10",
    "typings": "^1.3.2",
    "moment": "^2.14.1"
  }
}
`

**Comment by Martin-Luft** [comment]
Please check https://github.com/valor-software/ng2-bootstrap/issues/945 and https://github.com/valor-software/ng2-bootstrap/issues/790
