### ISSUE TITLE
Error when trying to use AOT with ngc

### ISSUE THREAD

**Issue by mstawick** [valor-software/ngx-bootstrap#956]
When trying to compile with ngc, I'm getting:

```
Error: Unexpected value 'DatepickerModule' imported by the module 'SharedModule'
```

same for TooltipModule and probably every other one.

DatepickerModule is imported (also tried importing from ng2-bootstrap/components/datepicker/datepicker.module):

```
import { DatepickerModule } from "ng2-bootstrap";
```

and when building with webpack it works fine.

According to discussion here:
https://github.com/angular/angular/issues/11262

it's due to missing *.metadata.json files.

**Comment by valorkin** [comment]
yeah, you are right, this is about metadata.json need to generate them additionality
same as #933
