### ISSUE TITLE
RC6 error when adding Module: Unexpected token <

### ISSUE THREAD

**Issue by chambersDon** [valor-software/ngx-bootstrap#957]
My application was working with ng2-bootstrap before RC5.  I have converted to RC6 now and removed ng2-bootstrap and everything is working. Now I want to add ng2-bootstrap.  I am just using the AlertModule and DatepickerModule because they are in the instructions.

In app.module.ts, I add the import:
`import {AlertModule, DatepickerModule} from 'ng2-bootstrap/ng2-bootstrap';`

Then I add AlertModule and DatepickerModule to the import of @NgModel as described in the instructions.  At this point I get a run time error - I have not even added the actual components to a page.  The error is:

```

Error: SyntaxError: Unexpected token <
at Object.eval (http://localhost:54675/lib/js/ng2-bootstrap/components/datepicker/date-formatter.js:2:14)
at eval (http://localhost:54675/lib/js/ng2-bootstrap/components/datepicker/date-formatter.js:13:4)
at eval (http://localhost:54675/lib/js/ng2-bootstrap/components/datepicker/date-formatter.js:14:3)
Evaluating http://localhost:54675/lib/js/moment/moment
Evaluating http://localhost:54675/lib/js/ng2-bootstrap/components/datepicker/date-formatter.js
Evaluating http://localhost:54675/lib/js/ng2-bootstrap/components/datepicker/datepicker-inner.component.js
Evaluating http://localhost:54675/lib/js/ng2-bootstrap/components/datepicker/datepicker.module.js
Evaluating http://localhost:54675/lib/js/ng2-bootstrap/components/datepicker.js
Evaluating http://localhost:54675/lib/js/ng2-bootstrap/ng2-bootstrap.js
Evaluating http://localhost:54675/lib/spa/app.module.js
Evaluating http://localhost:54675/lib/spa/main.js
Error loading http://localhost:54675/lib/spa/main.js
```

If I remove DateModule and just use AlertModule I get the same error that references datepicker.  If I remove AlertModule and add ModalModule I still get the error that reference datepicker.

Here are the relevant parts of systemjs.config.

```
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            'ng2-bootstrap': 'lib/js/ng2-bootstrap'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            'ng2-bootstrap': { defaultExtension: 'js' }
    });
```

Any idea what I'm missing?

**Comment by valorkin** [comment]
try to compare with https://github.com/valor-software/angular2-quickstart/blob/master/systemjs.config.js
`/lib/js/ng2-bootstrap/components/datepicker/date-formatter.js`
path seems correct, is file in place?

**Comment by chambersDon** [comment]
This is resolved.

It was not finding moment.  I need to add the js extension is systemjs.config.  Pre-RC5 it was appending it for me with the default extension.

**Comment by valorkin** [comment]
Awesome!
