### ISSUE TITLE
'rating' is not a known element:

### ISSUE THREAD

**Issue by born2net** [valor-software/ngx-bootstrap#958]
very odd, I am getting the error of:

```
Unhandled Promise rejection: Template parse errors:
'rating' is not a known element:
1. If 'rating' is an Angular component, then verify that it is part of this module.
2. If 'rating' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("ss="list-group">
                        <li class="list-group-item">
                            [ERROR ->]<rating></rating>
```

I did import the modules

```
import {DropdownModule} from 'ng2-bootstrap/ng2-bootstrap';
import {RatingModule} from 'ng2-bootstrap/ng2-bootstrap';
```

and drop down works fine... but yet RatingModule generates an error... mmm

any ideas?

ver 1.1.2

Regards,

Sean

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate

**Comment by Martin-Luft** [comment]
Please show us your complete ngmodule definition and the template which throws the error.

**Comment by born2net** [comment]
sure:
here:
https://github.com/born2net/studioDashboard/blob/master/src/App.ts

and used here:
https://github.com/born2net/studioDashboard/blob/master/src/comps/app1/adnet/network/AdnetNetworkTargetProps.html

**Comment by born2net** [comment]
and the controller:
https://github.com/born2net/studioDashboard/blob/master/src/comps/app1/adnet/network/AdnetNetworkTargetProps.ts

**Comment by Martin-Luft** [comment]
The rating component needs an ngModel binding.

**Comment by born2net** [comment]
haaaa.. it must? seems odd, as I was going to use it in reactive form with no ngModel (manual updates), trying now

**Comment by Martin-Luft** [comment]
I'm not 100% sure but the rating definition says: `selector: 'rating[ngModel]'` :)

**Comment by born2net** [comment]
ya that's a problem for me, as I am using 

```
[formGroup]="contGroup"
```

for reactive form and now will get an error of:

```
EXCEPTION: Error in http://localhost:9089/src/comps/app1/adnet/network/AdnetNetworkTargetProps.html:13:36 caused by: 
      ngModel cannot be used to register form controls with a parent formGroup directive.  Try using
      formGroup's partner directive "formControlName" instead.  Example:


    <div [formGroup]="myGroup">
      <input formControlName="firstName">
```

mmm

:/

**Comment by born2net** [comment]
will open bug as rating should not force ngModel in selector for reactive forms
