### ISSUE TITLE
rating component does not support reactive forms (requires ngModel)

### ISSUE THREAD

**Issue by born2net** [valor-software/ngx-bootstrap#959]
rating component does not support reactive forms (requires ngModel)
please change selector to <rating instead of [ngModel]

It implements ControlValueAccessor, but never provides NG_VALUE_ACCESSOR so that implementation is useless.

tx

Sean

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate

**Comment by born2net** [comment]
here is an example of how the components should be supported:
https://github.com/born2net/ng2Boilerplate/blob/master/src/comps/counterinputcomponent/CounterInputComponent.ts

**Comment by Martin-Luft** [comment]
The following ng2-bootstrap components use the ngModel selector binding:

> pagination.component
> pager.component
> datepicker.component
> datepicker-popup.component
> button-checkbox.directive
> button-radio.directive
> timepicker.component
> rating.component

**Comment by Martin-Luft** [comment]
What do you mean with

>  selector to <rating

Is the solution to use ngControl binding instead of ngModel binding?

**Comment by born2net** [comment]
if you look at the component, it uses ngModel, but reactive forms do not use ngModel, thus the directive does not bind to the component element.

**Comment by Martin-Luft** [comment]
https://github.com/valor-software/ng2-bootstrap/pull/1023

**Comment by valorkin** [comment]
fixed with #298
