### ISSUE TITLE
Timepicker spinner click won't trigger change function

### ISSUE THREAD

**Issue by linnobita** [valor-software/ngx-bootstrap#962]
Here is my code:

``` html
<div class="operation-time col-sm-6">
    <div class="modal-form-label">Open Time:</div>
    <timepicker [(ngModel)]="selectedStartTime" (change)="startTimeChanged()"></timepicker>
</div>
<div class="operation-time col-sm-6">
    <div class="modal-form-label">Close Time:</div>
   <timepicker [(ngModel)]="selectedEndTime" [min]="minEndTime"></timepicker>
</div>
```

I need to change the minEndTime value when the start time has been changed. When I changed the time from the input, it works perfectly. But when I clicked on the spinner to change the start time, the startTimeChanged() was not called. And then I checked the demo, it seems there is no way to trigger change function while using the spinners. Will there be a workaround or something?

**Comment by temokallc** [comment]
I need this feature as well

**Comment by fikretkurtiiev** [comment]
Also need this feature
