### ISSUE TITLE
Resize carousel height

### ISSUE THREAD

**Issue by svojislav** [valor-software/ngx-bootstrap#966]
Is there a way to reduce carousel height. When I display small images it remains on default height.
I have tried to put max-height on both carousel and surrounded div but nothing happens.
Width can be reduced but height no. I assume that there might be some default margins but can U please guide me how can I change that.
Best regards

**Comment by valorkin** [comment]
I am afraid it doesn't related to ng2-bootstrap,
but you can join slack and guys could help you with css

**Comment by rochapablo** [comment]
If someone else need:

```
.carousel.slide {
  .carousel-item {
    position: relative;
    min-height: 127px;
    max-height: 227px;
    @media (max-width: 576px) {
      height: 127px;
    }
    @media (min-width: 576px) {
      height: 227px;
    }
    .item {
      width: 100%;
      height: 100%;
      position: absolute;
      .image {
        width: 100%;
        height: 100%;
        position: absolute;
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;
      }
    }
  }
}
```

```
<carousel>
  <slide *ngFor="let slide of [1,2,3,4]">
    <div class="image" [ngStyle]="{ 'background-image': 'url(assets/carousel/slide-img-' + slide + '.jpg)' }"></div>
  </slide>
</carousel>
```

**Comment by IntelligaiaVivek** [comment]
Is there any way to auto height the carousel when more data come in text. Following my issue
![carousel](https://user-images.githubusercontent.com/23469188/30467702-3c83fd42-9a04-11e7-993a-4b5ee573fd16.png)
