### ISSUE TITLE
.npmignore?

### ISSUE THREAD

**Issue by Namek** [valor-software/ngx-bootstrap#967]
# Problem

Let's say someone forks the library and we want to **use** that **fork**, e.g.:

`npm i --save ng2-fileupload@git://github.com/adrianfaciu/ng2-file-upload#feat-rc6` (which I got from https://github.com/valor-software/ng2-file-upload/pull/379)

this results in no code inside `node_modules/{library}` - there are no `.js` files and no `.ts` files.
# Source of problem

`.npmignore` file contains following fragment:

```
#typescript sources
*.ts
*.js.map
!*.d.ts
/components/**/*.ts
!/components/**/*.d.ts
```
# Solution?

I'd like to know why this is configured this way and if we could change it.

https://github.com/valor-software/ng2-file-upload and https://github.com/valor-software/ng2-select are also affected by this issue.

**Comment by valorkin** [comment]
It is not an issue, it is planned to contain only source files and exclude generated
Real solution is to clone module you need and make npm install via relative path, like
`npm i ../ng2-select`
