### ISSUE TITLE
WAR file?

### ISSUE THREAD

**Issue by alaa-bourouissi** [valor-software/ngx-bootstrap#968]
Please How can I get the WAR file for the prodcution . More specifically , What to do for the production Mode ??

**Comment by valorkin** [comment]
this is a wide question, what is WAR file?

**Comment by Martin-Luft** [comment]
A WAR file is a web container. But the question is not related to ng2-bootstrap. You can create a WAR file in 100 ways. Before you must compile your Angular 2 application for production mode.

**Comment by valorkin** [comment]
@Martin-Wegner oh, thanks did not knew :)
