### ISSUE TITLE
Can't bind to 'ngModel' since it isn't a known property of 'datepicker'

### ISSUE THREAD

**Issue by ceolinwill** [valor-software/ngx-bootstrap#969]
I'm getting the error above when using a `datepicker` with `Angular RC.6`, `ng2-bootstrap 1.1.2` and `angular-cli@webpack-beta.11-webpack.8`.

**app.module.ts**

```
import { DatepickerModule } from 'ng2-bootstrap/ng2-bootstrap';

@NgModule({
  imports: [DatepickerModule], ...
})
```

**app.component.ts**

```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './my-app.component.html'
})

export class MyAppComponent {
  public dt:Date = new Date();
}
```

**my-app.component.html**

`<datepicker [(ngModel)]="dt"></datepicker>`

Any ideas?

**Comment by valorkin** [comment]
you forgot to add FormsModule to `imports` section in main module

**Comment by ceolinwill** [comment]
True. Thanks, @valorkin
