### ISSUE TITLE
dropdowns - not working with angular2-beta

### ISSUE THREAD

**Issue by sspranay** [valor-software/ngx-bootstrap#97]
I am using the angular2 5 min quickstart.

When I try to use the bare-minimum markups and Component provided for the drowdowns directive, I encouter 3 issues
1. The Caret doesn't appear
2. The dropdowns don't work
3. Split-button caret appears but half the size of primary action button.

Here are my dependencies, mostly from the angular2 5 min quickstart:

"dependencies": { "angular2": "2.0.0-beta.0", "bootstrap": "https://github.com/twbs/bootstrap/tarball/v4-dev", "es6-promise": "^3.0.2", "es6-shim": "^0.33.3", "ng2-bootstrap": "^1.0.1-beta.1", "reflect-metadata": "0.1.2", "rxjs": "5.0.0-beta.0", "systemjs": "0.19.6", "zone.js": "0.5.10" },

I am not aware of any protocol to be followed to raise a concern/issue. My apologies!

**Comment by valorkin** [comment]
Answer in your issue, you are using angular2 beta 0 with ng2 bootstrap beta 1, there are breaking changes between them :(

**Comment by valorkin** [comment]
I will issue a PR to update an angular 2 quick start

**Comment by sspranay** [comment]
Thanks for pointing out the problem. Can you quickly tell me the correct version numbers (for both angular2 and ng-bootstrap) that work well together?

**Comment by bbrink68** [comment]
Are there any plans to update for angular2-beta.0 or angular2-beta.1 ?? Running into same issue but would really love to use this library!

**Comment by valorkin** [comment]
@bbrink68 plunkr with issue reproduce will be very usefull
http://plnkr.co/edit/2lDiJaezvCOcSyd2dd2Q?p=preview

**Comment by sspranay** [comment]
Here is the plunkr
http://plnkr.co/edit/YBenGHBZCeDLbpfzqevM?p=preview

 If I update the version number to what you suggested in the quickstart update note - 2.0.1.beta.0, it breaks completely. Apparently angular2 1.beta is yet not out.

Thanks!

**Comment by valorkin** [comment]
@sspranay https://code.angularjs.org/
version is not correct
by the link you can see available versions of ng1 and ng2

**Comment by sspranay** [comment]
Apologies @valorkin if this sounds redundant, but can you please point out which angular2 version number to use to make it work?

**Comment by valorkin** [comment]
no worries, you can always check current recommended ng2 version in package.json
https://github.com/valor-software/ng2-bootstrap/blob/master/package.json#L43

**Comment by otabekgb** [comment]
I have reopened the issue #207

**Comment by otabekgb** [comment]
Sorry issue #205
