### ISSUE TITLE
feat(plunker): create plunker for each demo

### ISSUE THREAD

**Issue by markpritchett** [valor-software/ngx-bootstrap#970]
I think it would be useful to the community if each demo had a plunker.  This would bring consistency with how demos are done on [angular.io](https://angular.io/).

**Comment by valorkin** [comment]
I want it soo much! And we are working on bringing new docs, so I hope it will happen soon

**Comment by valorkin** [comment]
couple of steps in this direction is made:
- converted bundles from system.js to UMD
- created base plunker for issues http://bit.ly/ng2-bootstrap-plnkr
