### ISSUE TITLE
Suggestion: consider bringing in popover component from an existing repository

### ISSUE THREAD

**Issue by markpritchett** [valor-software/ngx-bootstrap#971]
There are a few repositories that have a popover component for angular 2.  The one I've briefly played around with is [ng2-popover](https://github.com/pleerock/ng2-popover).

Would it be worth contacting the author of this component (or the authors of any other popover components) to discuss using their implementation in this project?

Just thinking that as this project is gaining a fair amount of momentum, it might make sense to re-use some of the existing work done elsewhere to fill the gaps of missing components.

**Comment by valorkin** [comment]
done on 80%
I am in the middle of rewriting positioning service to allow auto positioning of elements which did not feet in view port...

**Comment by valorkin** [comment]
Implement ed
