### ISSUE TITLE
'No provider for NgModel' errors - RC7

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#974]
error_handler.js:46 EXCEPTION: Uncaught (in promise): Error: Template parse errors:
No provider for NgModel ("[ERROR ->]<datepicker ngModel></datepicker>"): DatePickerComponent_Host@0:0

This error arise because the provider is not declared in the component datepicker, I've tried to add the provider into the compiled file datepicker.component.js and it works but another error arise in pagination because also I'm using that component too.

Also this is not a common behehavior, it's only when I use a compiler function since Angular2 RC6 Compiler.compileModuleAndAllComponentsAsync()

Can you perform that modification in order to fix that issue, or tell us how we can use the ng2-bootstrap components when we use compileModuleAndAllComponentsAsync() function?

Thanks

**Comment by Martin-Luft** [comment]
When you import the FormsModule, what the ng2-modules do, the NgModel is provided.

I think this is related to https://github.com/valor-software/ng2-bootstrap/issues/929 and https://github.com/valor-software/ng2-bootstrap/pull/963

**Comment by valorkin** [comment]
which version of ng2-bootstrap are you using?
in latest it is already fixed
and don't forget to add `FormsModule` to your module imports statement
