### ISSUE TITLE
Issue while adding styles using - <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

### ISSUE THREAD

**Issue by PoojaVM** [valor-software/ngx-bootstrap#980]
I am trying to use ng2-bootstrap's timepicker in my application. I am successful in integrating the library in the node modules and the timepicker also works fine on the UI. The issue is I have imported CSS on my page as using the link tag as suggested but because of this other parts on my page where I am using some other CSS are getting distorted.

**Comment by valorkin** [comment]
Most probably you have styles overlapping with twitter bootstrap css
I can only wish you patience fixing all of them

**Comment by PoojaVM** [comment]
Thank you.
