### ISSUE TITLE
Few problems.

### ISSUE THREAD

**Issue by jurienhamaker** [valor-software/ngx-bootstrap#983]
Hello,

I've been using this project for a while. But now I am getting a few problems;
- Tooltips stopped working `No provider for TooltipOptions`
- Datepicker stops working when using `ReactiveFormsModule` (Completely dissapears from available directives) (Works fine with forms module)

Anyone knows how to solve this :S?

**Comment by valorkin** [comment]
since rc.5 you need to import modules and not directives
than you will have all needed providers
ReactiveForm will be added in nearest days

**Comment by jurienhamaker** [comment]
I imported the `Ng2BootstrapModule`

**Comment by jurienhamaker** [comment]
How can you even close an issue when It's not done yet @valorkin

**Comment by valorkin** [comment]
oh, sorry forgot to drop a link,
it duplicates couple of other issues:
https://github.com/valor-software/ng2-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20no%20provider

**Comment by valorkin** [comment]
can not find that issue,
there 2 main issues after rc.5
`no provider for ...`  and hanging modals (because of hack used to achieve root container ref)

**Comment by valorkin** [comment]
here the issue I was referring too: https://github.com/valor-software/ng2-bootstrap/issues/854#issuecomment-247252585

**Comment by valorkin** [comment]
Sorry again for closing an issue, I am in rush to bring those issues fixed :(

**Comment by jurienhamaker** [comment]
Allright, so is this a duplicate? Do you need something?

**Comment by valorkin** [comment]
Sample repo to reproduce issue, will speed up me a lot, thanks in advance :)

**Comment by valorkin** [comment]
@KingsDevelopment hey, can you join slack https://www.hamsterpad.com/chat/ng2
I want to here a bit more about disappearing with Reacting forms

**Comment by jurienhamaker** [comment]
allright, joining in

**Comment by Martin-Luft** [comment]
@KingsDevelopment is your problem solved? Can we close this issue?

**Comment by jurienhamaker** [comment]
Not sure, will test in an hour, had been doing a lot of work in the meantime (working with/on this on a company platform)

**Comment by Martin-Luft** [comment]
@KingsDevelopment any news?

**Comment by Martin-Luft** [comment]
@KingsDevelopment can I close this issue?

**Comment by Martin-Luft** [comment]
No reaction... -> close...
