### ISSUE TITLE
tsc errors

### ISSUE THREAD

**Issue by klanglie** [valor-software/ngx-bootstrap#989]
I am using latest - thanks for the quick response. However, for some reason tsc is throwing errors. 

I added an exclude section to tsconfig:

`"exclude": [
        "node_modules"
    ]`

'npm run tsc' produces the following:

node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts(14,22): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts(15,22): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/buttons/button-radio.directive.d.ts(10,14): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/buttons/button-radio.directive.d.ts(10,22): error TS1005: ';' expected.
node_modules/ng2-bootstrap/components/dropdown/dropdown-toggle.directive.d.ts(11,14): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/dropdown/dropdown-toggle.directive.d.ts(11,20): error TS1005: ';' expected.
node_modules/ng2-bootstrap/components/modal/modal.component.d.ts(14,14): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/modal/modal.component.d.ts(14,21): error TS1005: ';' expected.
node_modules/ng2-bootstrap/components/modal/modal.component.d.ts(22,22): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/position.d.ts(29,22): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/position.d.ts(30,22): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/tooltip/tooltip-container.component.d.ts(21,14): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/tooltip/tooltip-container.component.d.ts(21,24): error TS1005: ';' expected.
node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts(18,14): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts(18,26): error TS1005: ';' expected.
node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts(18,44): error TS1005: '(' expected.
node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts(46,14): error TS1005: '=' expected.
node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts(46,21): error TS1005: ';' expected.
node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts(46,33): error TS1005: '(' expected.

**Comment by valorkin** [comment]
Hm, try to add "skip lib check" option to tsc config

**Comment by pj-martins** [comment]
Having the same problem, adding skipLibCheck did not solve the problem. Seems to be a problem with anything marked "readonly".

**Comment by valorkin** [comment]
Are you using gulp? If so you should explicitly pass typescript as option
Check #982

**Comment by pj-martins** [comment]
using visual studio 2015 and Microsoft.TypeScript.Compiler v1.8.11 and typescript ^2.0.2 as a dependency in package.json

**Comment by valorkin** [comment]
You need ts 2, 1.\* will not work
ng2 is using ts2, so I had to use it too

**Comment by pj-martins** [comment]
here's what I have:
package.json
"devDependencies": {
    "concurrently": "^2.2.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.2",
    "typings": "^1.3.2"
  }

packages.config
package id="Microsoft.TypeScript.Compiler" version="2.0.2-rc" targetFramework="net452" developmentDependency="true"

but still no luck

**Comment by dhardtke** [comment]
https://blogs.msdn.microsoft.com/typescript/2016/07/11/announcing-typescript-2-0-beta/
You guys need to manually install typescript 2

**Comment by klanglie** [comment]
I am using VS Code + TSC Version 2.0.0. I tried again to compile but am getting the same error.

**Comment by pj-martins** [comment]
after installing 2, opening up the project file in notepad and replacing 

`<TypeScriptToolsVersion>1.8</TypeScriptToolsVersion>`
with
`<TypeScriptToolsVersion>2.0</TypeScriptToolsVersion>`

did the trick

**Comment by klanglie** [comment]
For now I think the error went away. Had to remove node_modules, re-install everything including tsc. Now I have other growing pains upgrading to 2.0.0. Fingers crossed.

**Comment by valorkin** [comment]
Good luck :)

**Comment by sjatkins** [comment]
Well all of the above does not describe my world.  I get the same error and I am under webpack.  So stuff about tsc explicitly doesn't make a lot of sense to me.  My package.json says I am at typescript "2.0.3".  It is not a good story when module by module we have these worries.  BTW why does typings get used for this now at all?   It is my understanding that in later versions of angular (I am at 2.4.4) that some of this went away.

**Comment by valorkin** [comment]
With ng v2 you need ts at least 2.0.10
With v4+ ts 2.1+
