### ISSUE TITLE
Syntax error when compiling with TypeScript 2.0.2

### ISSUE THREAD

**Issue by alvachien** [valor-software/ngx-bootstrap#991]
Error list:

/node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts(14,22): error TS1005: '=' expected.
/node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts(15,22): error TS1005: '=' expected.
/node_modules/ng2-bootstrap/components/buttons/button-radio.directive.d.ts(10,14): error TS1005: '=' expected.
/node_modules/ng2-bootstrap/components/buttons/button-radio.directive.d.ts(10,22): error TS1005: ';' expected.
/node_modules/ng2-bootstrap/components/dropdown/dropdown-toggle.directive.d.ts(11,14): error TS1005: '=' expected.
/node_modules/ng2-bootstrap/components/dropdown/dropdown-toggle.directive.d.ts(11,20): error TS1005: ';' expected.
/node_modules/ng2-bootstrap/components/modal/modal.component.d.ts(14,14): error TS1005: '=' expected.
/node_modules/ng2-bootstrap/components/modal/modal.component.d.ts(14,21): error TS1005: ';' expected.
/node_modules/ng2-bootstrap/components/modal/modal.component.d.ts(22,22): error TS1005: '=' expected.
/node_modules/ng2-bootstrap/components/position.d.ts(29,22): error TS1005: '=' expected.
/node_modules/ng2-bootstrap/components/position.d.ts(30,22): error TS1005: '=' expected.
/node_modules/ng2-bootstrap/components/tooltip/tooltip-container.component.d.ts(21,14): error TS1005: '=' expected.
/node_modules/ng2-bootstrap/components/tooltip/tooltip-container.component.d.ts(21,24): error TS1005: ';' expected.
/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts(18,14): error TS1005: '=' expected.
/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts(18,26): error TS1005: ';' expected.
/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts(18,44): error TS1005: '(' expected.
/node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts(46,14): error TS1005: '=' expected.
/node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts(46,21): error TS1005: ';' expected.
/node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts(46,33): error TS1005: '(' expected.

**Comment by ThatOneBro** [comment]
My team is also having this issue. We are running Ubuntu 32-bit and WIndows systems, same issue across the board with 2.0.2

**Comment by valorkin** [comment]
Please search in issues, it is common issue.
seems I will have to create a FAQ on ts update.
What are using atom, vs, gulp?
They ignore ts installed in project, you have tweak them

**Comment by ThatOneBro** [comment]
We were using TSC stand-alone.

So the fix is, as found from other issues:

Install TypeScript 2.0.2 (make sure its in package.json of project)
Add "skipLibCheck": true    in tsconfig.json

Thanks valorkin!

**Comment by alvachien** [comment]
@valorkin Thanks for the hint. I found the issue: https://github.com/valor-software/ng2-bootstrap/issues/989

**Comment by valorkin** [comment]
Awesome :)

**Comment by priteshacharya** [comment]
Typescript 2 is only available for Visual studio 2015 and I'm using Visual Studio 2013. Any work around in this case?

**Comment by valorkin** [comment]
@priteshacharya you can search issues here, guys was mentioning something similar, or speak with @typescript team

**Comment by sjatkins** [comment]
Well all of the above does not describe my world.  I get the same error and I am under webpack.  So stuff about tsc explicitly doesn't make a lot of sense to me.  My package.json says I am at typescript "2.0.3".  It is not a good story when module by module we have these worries.  BTW why does typings get used for this now at all?   It is my understanding that in later versions of angular (I am at 2.4.4) that some of this went away.  

The old issue does seem adequate to fix this.  Anyone have more clues?

**Comment by sjatkins** [comment]
I pulled the source out directly into my project as I noticed the install used older versions of a number of things plus typing which I think are part of what causes me grief.    So far it seems to have escaped from the early error.
