### ISSUE TITLE
Ahead of Time (AoT) Issue when running ngc

### ISSUE THREAD

**Issue by mil3nium** [valor-software/ngx-bootstrap#992]
When running Ngc command I get this error: 

`Unexpected value 'CarouselModule' imported by the module 'SharedModule'`

Hopefully you can make it work with AoT compiler.

Tried importing each of the components and directives, but no luck

**Comment by valorkin** [comment]
It is related to metadata.json issue

**Comment by freezy** [comment]
I'm simply getting:

```
Error: Unexpected value 'Ng2BootstrapModule' imported by the module 'AppModule'
```

Related to that issue as well?
