### ISSUE TITLE
hack: Missing encapsulation attribute / how to change CSS in components?

### ISSUE THREAD

**Issue by jakub-astrahit** [valor-software/ngx-bootstrap#993]
I have a Home component with this inside:
`<alert type="info">Hello from ng2-bootstrap</alert>`

Inside my home.style.scss, I have this:

```
:host .alert {
  background-color: green;
}
```

which should change the background color to green, but it does not.

The above css code will produce this style:

```
[_nghost-wjn-3]   .alert[_ngcontent-wjn-3] {
  background-color: green; }
```

and the final HTML looks like this:

```
<home _nghost-wjn-3="">
  <div _ngcontent-wjn-3="" class="card-container">
    <alert _ngcontent-wjn-3="" type="info" ng-reflect-type="info">
      <div class="alert alert-info" role="alert" ng-reflect-initial-classes="alert" ng-reflect-ng-class="alert-info">
        Hello from ng2-bootstrap  Sat Sep 17 2016
      </div>
    </alert>
  </div>
</home>
```

I don't know what the problem is here, but I think the selector is wrong. I'd like the final selector to be:
`[_nghost-wjn-3]   .alert`
instead of:
`[_nghost-wjn-3]   .alert[_ngcontent-wjn-3]`

Or in other words, why is there no _ngcontent-wjn-3 attribute on `<div class="alert">...</div>`?

Maybe I'm doing the whole thing wrong. I'm new to this. What I'm trying to achieve is to customize the CSS of the individual bootstrap components (`<alert>` in the code above) as provided by this library inside my custom components (`<home>` in the code above).

How can I do that please?

**Comment by jakub-astrahit** [comment]
Never mind, I figured it out myself.  This is the selector I was looking for:

```
:host /deep/ .alert {
  background-color: green;
}
```

The above code will produce the following:

```
[_nghost-wjn-3] .alert {
  background-color: green;
}
```

This way I can modify the default styles of a bootstrap class (.alert, in this case) inside of my component `<home>`.

But still, it would be nice to know why this `<div class="alert">...</div>` has no `_ngcontent-wjn-3` attribute, any ideas?

**Comment by valorkin** [comment]
@jakub2 BTW I have seen similar issue in angular2 project
about compiling `:host` selector
if you can find it and propose your solution I suppose guys will be grateful

**Comment by ojourmel** [comment]
Issue angular/angular#12215 seems to cover this. Until then, I guess we just rely on the `:host /deep/` selectors :/

Perhaps this should be added to the docs somewhere? This will affect any dynamically generated elements, which happen a lot in ngx-bootstrap.

**Comment by valorkin** [comment]
I was thinking of adding `wrapperClass` options, by adding it to dynamic components could simplify customizing them

**Comment by simeyla** [comment]
#### For dynamic components only:

I've added a pretty extensive solution I'm quite happy with using a custom directive and ComponentPortal.

It will automatically add the `_ngcontent` attribute for you - and be in a single place if a change ever needs to be made!

Using `::ng-deep` can be dangerous if styles leak into child components, and it's always nice to eliminate usage of it wherever possible. In my case the primary driving factor was I needed to add a margin to a dynamic component and I couldn't even set it in the host component's scss without `::ng-deep` which was just awful!

[Added to 12215](https://github.com/angular/angular/issues/12215#issuecomment-872533034).
