### ISSUE TITLE
feat(slider): add slider component 

### ISSUE THREAD

**Issue by jaumard** [valor-software/ngx-bootstrap#995]
I didn't find any slider component, maybe it can be cool to add :) found this one for bootstrap http://seiyria.com/bootstrap-slider/

**Comment by valorkin** [comment]
+1

**Comment by jaumard** [comment]
If you give me some advices/leads on how to proceed I can try to do something @valorkin  :)

**Comment by valorkin** [comment]
Join slack and we can chat about it ;)

**Comment by KKrisu** [comment]
Hi guys, I can see that the PR has been merged https://github.com/valor-software/ngx-bootstrap/pull/1012
When are you going to public this out?

**Comment by valorkin** [comment]
It was some breaking change, so I had to revert it

**Comment by KKrisu** [comment]
@valorkin Any further plans for this or should I use a different component, out of ngx-bootstrap for now?

**Comment by valorkin** [comment]
I am working on version 2 of ngx bootstrap

**Comment by agil-NUBBA** [comment]
still planning to add this?

**Comment by valorkin** [comment]
Yep, we released v2 and now working on new samples for docs, tests and new components
Stay tuned :)

**Comment by florenthobein** [comment]
Is there any news about the inclusion of a slider & range component on the roadmap?
