### ISSUE TITLE
No provider for NgModel' errors upgrade angular 2.0.0.0 release

### ISSUE THREAD

**Issue by yasemincidem** [valor-software/ngx-bootstrap#996]
We was using angular rc 4 version in our project.Everything is clear in angular rc4 version.We upgraded to angular 2.0.0.0 release but we are taking a such error.
`Provider parse errors:
No provider for NgModel: in NgModule AppModule`.
What is the reason this error.

**Comment by hongbo-miao** [comment]
It is a breaking change for Angular 2 since RC5.
Check https://angular.io/docs/ts/latest/guide/ngmodule.html
and
https://github.com/valor-software/ng2-bootstrap/blob/development/README.md#quick-start
