### ISSUE TITLE
update npm ng2-bootstrap angular2

### ISSUE THREAD

**Issue by ipoweb** [valor-software/ngx-bootstrap#999]
Hi, could you update package ng2-bootstrap on NPM to get compiled files d.ts for angular2 ?

**Comment by Martin-Luft** [comment]
The d.ts files are already included!? My node_modules/ng2-bootstrap directory includes all d.ts files.

**Comment by ipoweb** [comment]
yes actually d.ts files are included but if you compare github with ts and npm with d.ts, you will see than the d.ts are not updated correctly.

type in cmd: npm install 
ng2-bootstrap\components\buttons\button-checkbox.directive.d.ts
check this file and get github download zip, compare with 
ng2-bootstrap\components\buttons\button-checkbox.directive.ts

you will see on npm that js are updated but not d.ts
in npm package, you will get only .d.ts files and in github only .ts files

**Comment by Martin-Luft** [comment]
The `button-checkbox.directive.d.ts` file from the npm package is identical with my local compiled `button-checkbox.directive.d.ts` file (clone the GIT repository, checkout the v1.1.5 tag and run npm install).

The v1.1.5 `button-checkbox.directive.ts` file matches perfectly with the `button-checkbox.directive.d.ts` file.

So what is the problem?

The npm package only contains the compiled files -> `.js` and the related `.d.ts`
Github only contains the source code -> `.ts`

**Comment by Martin-Luft** [comment]
No reaction -> close...
